### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1080]
develop b2b9b3b567291c02a34f16b510621f8ac75d368c running on raspberry pi (`go version go1.4.2 linux/arm`)

after importing an export of the blockchain (using `./go-ethereum/build/bin/geth import blockchain.bin`):

```
[pi@etherpi ~]$ ./go-ethereum/build/bin/geth
I0523 11:19:33.567409   32367 backend.go:252] Protocol Version: 60, Network Id: 0
I0523 11:19:33.567883   32367 backend.go:252] Blockchain DB Version: 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x11d4ac]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0x38
github.com/ethereum/go-ethereum/core.(*ChainManager).setLastState(0x56db92b0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:237 +0x158
github.com/ethereum/go-ethereum/core.NewChainManager(0x46c1c010, 0x56e887a0, 0x46c1c010, 0x56dfcc60, 0x46c1c3c8, 0x56e822c0, 0x56e88920, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:119 +0x204
github.com/ethereum/go-ethereum/eth.New(0x56d80300, 0x4, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:252 +0x1480
main.run(0x56d9e3f0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:309 +0x64
github.com/codegangsta/cli.(*App).Run(0x56d80280, 0x56d4e000, 0x1, 0x1, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:133 +0xd58
main.main()
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:300 +0x94
```

**Comment by 886981109464** [comment]
MMS

**Comment by obscuren** [comment]
run `geth removedb` and try again. The linked issue is the real problem. Closing this one.
