### ISSUE TITLE
blockchain corruption, or similar nil panic

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1093]
I've been stuck on a block that I couldn't import, was considered invalid for some reason (latest develop as of now)

```
I0525 14:23:14.557295    8676 chain_manager.go:743] INVALID block #433182 (b83ca3c4d28bc2233f5c6cfed4a1536d2ee05fcbc2781669a7202960ee7338ac)
I0525 14:23:14.557349    8676 chain_manager.go:744] Transaction w/ invalid nonce. tx=5184  state=0)
I0525 14:23:14.557371    8676 sync.go:66] Block insertion failed: Transaction w/ invalid nonce. tx=5184  state=0)
I0525 14:23:14.557499    8676 sync.go:114] Synchronisation failed: block downloading cancelled (requested)
```

so I figured I'd set my head block a bit backwards to maybe pull a fresh batch if for some reason I've got a just block). After running `admin.debug.setHead(430000)` geth more or less froze. I terminated it with `Ctrl+C`, after which every time I tried to start geth I got a nil panic.

```
> geth console
I0525 14:31:09.633109    8921 backend.go:255] Protocol Version: 60, Network Id: 0
I0525 14:31:09.634549    8921 backend.go:265] Blockchain DB Version: 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5063ca]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
        /work/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0xca
github.com/ethereum/go-ethereum/core.(*ChainManager).setLastState(0xc20878b7a0)
        /work/src/github.com/ethereum/go-ethereum/core/chain_manager.go:237 +0x155
github.com/ethereum/go-ethereum/core.NewChainManager(0x7fba19fd8e18, 0xc20813f620, 0x7fba19fd8e18, 0xc2085fd2c0, 0x7fba19fda728, 0xc208734b60, 0xc2085fc0c0, 0x0)
        /work/src/github.com/ethereum/go-ethereum/core/chain_manager.go:119 +0x23f
github.com/ethereum/go-ethereum/eth.New(0xc20806d800, 0x4, 0x0, 0x0)
        /work/src/github.com/ethereum/go-ethereum/eth/backend.go:287 +0x1778
main.console(0xc20807c540)
        /work/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:329 +0x175
github.com/codegangsta/cli.Command.Run(0xca7e90, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdc1c70, 0x30, 0xf51eb0, ...)
        /work/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208166000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /work/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
        /work/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:300 +0x80
```

In the end I just dumped the entire block chain database. However, this was an unpleasant xp and now I have to resync 1+ hours, so it would be nice if we could look into this.

**Comment by karalabe** [comment]
Seems to hit the same issue as #1080.

**Comment by fjl** [comment]
This is a good hint as to where the nil blocks might be coming from.Seems as if interrupting during sync causes invalid block data to get written.

**Comment by Quiark** [comment]
I think the same thing happened to me, running b2b9b3b567291c02a34f16b510621f8ac75d368c

I was stuck on invalid block and went back

```
> eth.blockNumber
446423
> admin.debug.setHead(444444)
undefined
> eth.blockNumber
444467
> eth.blockNumber
444630
> eth.blockNumber
444634
> eth.blockNumber
4
```
Then I tried to `exit`  geth but it never finished so I Ctrl-C'ed it. Now got this crash

```
I0526 07:03:00.582247    1320 peer.go:109] [262167eb28c7ce1b] fetching 128 blocks
I0526 07:03:00.758725    1320 downloader.go:413] Added 128 blocks from: 3b3bd5cdd92c02e7
I0526 07:03:00.759520    1320 peer.go:109] [3b3bd5cdd92c02e7] fetching 128 blocks
I0526 07:03:00.965860    1320 sync.go:60] Inserting chain with 128 blocks (#446924 - #447051)
I0526 07:03:00.980398    1320 state_object.go:241] 82b27dbe07d34fb96309d2306e2729b6c5d155ff: gas (+ 3142770)
I0526 07:03:00.984677    1320 downloader.go:413] Added 0 blocks from: fdd299011508d51b
I0526 07:03:00.984914    1320 ethash.go:73] Generating cache for epoch 14 (526ee6e688a9b3d466fe4a7355197a89898593509d75c570942cc73a5ca8299d)
I0526 07:03:00.994985    1320 state_object.go:197] 82b27dbe07d34fb96309d2306e2729b6c5d155ff: #1 46975858129337085034714 (+ 1500000000000000000)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x50621f]

goroutine 534 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(0x0, 0x30540b85f5a78477)
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:269 +0x1f
github.com/ethereum/go-ethereum/core.(*ChainManager).diff(0xc2089ac900, 0xc20800a300, 0x0, 0x0, 0x0, 0x0)
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:670 +0xa13
github.com/ethereum/go-ethereum/core.(*ChainManager).merge(0xc2089ac900, 0xc20800a300, 0xc20d13be00)
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:696 +0x45
github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc2089ac900, 0xc209d44400, 0x80, 0x80, 0x0, 0x0, 0x0)
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:596 +0x1379
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).processBlocks(0xc2094a63c0, 0x0, 0x0)
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:64 +0x374
github.com/ethereum/go-ethereum/eth.func·005()
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:37 +0x33
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).update
        /root/ether/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:39 +0x2bd


```

**Comment by karalabe** [comment]
Closing this. The shutdown procedure was fixed to not allow force closing, but rather finish up syncing with the database first. If we/you still force kill the app, then we can accept data corruption.

**Comment by Quiark** [comment]
oh so that's why I had to reboot to get rid of the stuck geth process the other day :D
