### ISSUE TITLE
upgradedb fatal error: runtime: out of memory and crashes

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1116]
develop f5ce848cfe8cc1912714b8185f8dd3358a16687a

Ran geth upgradedb

```
I0527 01:18:00.348640    2287 chain_manager.go:655] imported 2500 block(s) (0 queued 0 ignored) in 3m45.516628691s. #300000 [2f10525b / 330ad119]
I0527 01:19:40.653822    2287 chain_manager.go:655] imported 2500 block(s) (0 queued 0 ignored) in 1m40.246064495s. #302500 [9c76eea9 / cd648a90]
fatal error: runtime: out of memory

goroutine 1 [running]:
runtime.throw(0x172ac97)
        /usr/lib/go/src/pkg/runtime/panic.c:464 +0x69 fp=0x7f1ddfe07f58
runtime.SysMap(0xc2d71c0000, 0x100000, 0x17ee078)
        /usr/lib/go/src/pkg/runtime/mem_linux.c:131 +0xfe fp=0x7f1ddfe07f88
----- stack segment boundary -----
runtime.MHeap_SysAlloc(0x17f7fc0, 0x100000)
        /usr/lib/go/src/pkg/runtime/malloc.goc:473 +0x10a fp=0x7f1ddf5c5120
MHeap_Grow(0x17f7fc0, 0x10)
        /usr/lib/go/src/pkg/runtime/mheap.c:241 +0x5d fp=0x7f1ddf5c5160
MHeap_AllocLocked(0x17f7fc0, 0x1, 0x7f1d00000004)
        /usr/lib/go/src/pkg/runtime/mheap.c:126 +0x305 fp=0x7f1ddf5c51a0
runtime.MHeap_Alloc(0x17f7fc0, 0x1, 0x4, 0x7f1d00000001)
        /usr/lib/go/src/pkg/runtime/mheap.c:95 +0x7b fp=0x7f1ddf5c51c8
MCentral_Grow(0x17fed18)
        /usr/lib/go/src/pkg/runtime/mcentral.c:180 +0x8c fp=0x7f1ddf5c5228
runtime.MCentral_AllocList(0x17fed18, 0x7f1df1902050)
        /usr/lib/go/src/pkg/runtime/mcentral.c:46 +0x4f fp=0x7f1ddf5c5250
runtime.MCache_Refill(0x7f1df1902000, 0x4)
        /usr/lib/go/src/pkg/runtime/mcache.c:22 +0x7c fp=0x7f1ddf5c5270
runtime.mallocgc(0x30, 0x999181, 0x1)
        /usr/lib/go/src/pkg/runtime/malloc.goc:71 +0xff fp=0x7f1ddf5c52e0
cnew(0x999180, 0x5, 0xc200000001)
        /usr/lib/go/src/pkg/runtime/malloc.goc:718 +0xc1 fp=0x7f1ddf5c5300
runtime.cnewarray(0x999180, 0x5)
        /usr/lib/go/src/pkg/runtime/malloc.goc:731 +0x3a fp=0x7f1ddf5c5320
```

full stack:  http://paste.ubuntu.com/11381805/

**Comment by ethers** [comment]
maybe related to #1018

**Comment by ethers** [comment]
on fjl commit e99bf30

I still see a crash: http://paste.ubuntu.com/11400358/

**Comment by obscuren** [comment]
Let me know if https://github.com/ethereum/go-ethereum/pull/1129 fixed your issue

**Comment by karalabe** [comment]
@ethers Can we close this?

**Comment by ethers** [comment]
yes (not sure how I didn't see this in github notifications earlier)
