### ISSUE TITLE
geth import: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1119]
Running `geth import` on my Raspberry Pi2 (1GB ram, 2GB swap) after #1080 has been fixed:

develop f5ce848cfe8cc1912714b8185f8dd3358a16687a

```
I0527 09:38:30.863326    1416 chain_manager.go:593] imported 2500 block(s) (0 queued 0 ignored) in 3m5.006749402s. #72500 [24749720 / adee3b79]
I0527 09:41:38.206941    1416 chain_manager.go:593] imported 2500 block(s) (0 queued 0 ignored) in 3m7.068239648s. #75000 [4344bf4c / f580d3fe]
I0527 09:45:26.259715    1416 chain_manager.go:593] imported 2500 block(s) (0 queued 0 ignored) in 3m47.773229733s. #77500 [155711ab / ecd41e60]
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0x5bfa0000, 0xf6d80000, 0x1, 0xc3bfb8)
        /usr/lib/go/src/runtime/mem_linux.c:159 +0x134
runtime.MHeap_MapBits(0xc3ed30)
        /usr/lib/go/src/runtime/mgc0.c:1900 +0xc0
runtime.MHeap_SysAlloc(0xc3ed30, 0x100000, 0x1)
        /usr/lib/go/src/runtime/malloc.c:286 +0x164
runtime.MHeap_Alloc(0xc3ed30, 0x1, 0x19, 0x100, 0x0)
        /usr/lib/go/src/runtime/mheap.c:240 +0x50
runtime.MCentral_CacheSpan(0xc43984, 0x744133d8)
        /usr/lib/go/src/runtime/mcentral.c:85 +0x204
runtime.MCache_Refill(0x46bd54b0, 0x19, 0x4)
        /usr/lib/go/src/runtime/mcache.c:90 +0x88

goroutine 1 [running]:
runtime.switchtoM()
        /usr/lib/go/src/runtime/asm_arm.s:193 +0x4 fp=0x74413058 sp=0x74413054
runtime.mallocgc(0x200, 0x6f9c20, 0x0, 0x10)
        /usr/lib/go/src/runtime/malloc.go:178 +0x87c fp=0x744130b0 sp=0x74413058
runtime.newobject(0x6f9c20, 0x46be3e98)
        /usr/lib/go/src/runtime/malloc.go:353 +0x4c fp=0x744130c4 sp=0x744130b0
reflect.New(0x46be3e98, 0x6f9c20, 0x0, 0x0, 0x0)
        /usr/lib/go/src/reflect/value.go:2082 +0xb4 fp=0x744130e8 sp=0x744130c4
github.com/ethereum/go-ethereum/rlp.func·003(0x76c5bc20, 0x6e5c48, 0x649ce640, 0xd6, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/decode.go:382 +0x88 fp=0x74413124 sp=0x744130e8
github.com/ethereum/go-ethereum/rlp.func·002(0x76c5bc20, 0x6ceb60, 0x649ce640, 0xd9, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/decode.go:359 +0x190 fp=0x74413224 sp=0x74413124
github.com/ethereum/go-ethereum/rlp.(*Stream).Decode(0x76c5bc20, 0x5e52c0, 0x649ce640, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/decode.go:728 +0x20c fp=0x744132e4 sp=0x74413224
github.com/ethereum/go-ethereum/core/types.(*StorageBlock).DecodeRLP(0x76cb0480, 0x76c5bc20, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:190 +0x58 fp=0x7441332c sp=0x744132e4
github.com/ethereum/go-ethereum/rlp.decodeDecoderNoPtr(0x76c5bc20, 0x6f1cd8, 0x76cb0480, 0xd9, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/decode.go:455 +0xd0 fp=0x74413364 sp=0x7441332c
github.com/ethereum/go-ethereum/rlp.(*Stream).Decode(0x76c5bc20, 0x6ab220, 0x76cb0480, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/decode.go:728 +0x20c fp=0x74413424 sp=0x74413364
github.com/ethereum/go-ethereum/rlp.Decode(0x46bef4f0, 0x649ce620, 0x6ab220, 0x76cb0480, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/decode.go:92 +0x64 fp=0x7441343c sp=0x74413424
github.com/ethereum/go-ethereum/core.(*ChainManager).GetBlock(0x56d8b520, 0xe6848051, 0xb11881ce, 0x2974836a, 0x47d4f6f7, 0x6a7ab9db, 0x47ddd740, 0x56ef66fd, 0x3984c3d, 0x1)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:436 +0x2b4 fp=0x74413500 sp=0x7441343c
github.com/ethereum/go-ethereum/core.(*BlockProcessor).Process(0x56e52340, 0x628c1780, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/block_processor.go:185 +0x31c fp=0x74413588 sp=0x74413500
github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0x56d8b520, 0x72358000, 0x9c4, 0x9c4, 0x0, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:568 +0x56c fp=0x74413a28 sp=0x74413588
github.com/ethereum/go-ethereum/cmd/utils.ImportChain(0x56d8b520, 0x7eed3903, 0xe, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:196 +0x6b0 fp=0x74413af4 sp=0x74413a28
main.importchain(0x56d71b90)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:530 +0x248 fp=0x74413bb8 sp=0x74413af4
github.com/codegangsta/cli.Command.Run(0x72d6e8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x795470, 0x18, 0x0, ...)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:97 +0xecc fp=0x74413de4 sp=0x74413bb8
github.com/codegangsta/cli.(*App).Run(0x56db4280, 0x56d20000, 0x3, 0x3, 0x0, 0x0)
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:133 +0xd0c fp=0x74413f6c sp=0x74413de4
main.main()
        /home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:301 +0x94 fp=0x74413fc0 sp=0x74413f6c
runtime.main()
        /usr/lib/go/src/runtime/proc.go:63 +0x108 fp=0x74413fe4 sp=0x74413fc0
runtime.goexit()
        /usr/lib/go/src/runtime/asm_arm.s:1322 +0x4 fp=0x74413fe4 sp=0x74413fe4
```

**Comment by jorisbontje** [comment]
related to #1018

**Comment by obscuren** [comment]
Poor RPi :-( Best to just update using the net. Upgrade uses a lot of memory

**Comment by karalabe** [comment]
We've just figured out an issue why this might happen. Hopefully it'll be sorted out in a few hours. Until then it's probably simpler to just pull from the net (unless bandwidth is a concern, it'll take roughly the same amount of time).

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/pull/1129 should address this

**Comment by jorisbontje** [comment]
with 27e0d2a97325edc9a870a747412d0b9a2abd1ed1 the import is now successfully getting past the block where it previously crashed (still importing though).
