### ISSUE TITLE
panic ChainManager Stop (close of closed channel)

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1278]
Geth
Version: 0.9.31
Git Commit: dfd18d245af37344f8e6fadca55f22a639d7f1ba
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2

ctrl-c took a long time to stop geth, and then it logged:

```
panic: close of closed channel

goroutine 10 [running]:
github.com/ethereum/go-ethereum/core.(*ChainManager).Stop(0xc208d20360)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:513 +0x2f
github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc2081ca6e0)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:549 +0x41
github.com/ethereum/go-ethereum/cmd/utils.func·002(0x7f812d4377e8, 0xc212552000)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:153 +0x2a
github.com/ethereum/go-ethereum/cmd/utils.RunInterruptCallbacks(0x7f812d4377e8, 0xc212552000)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:68 +0x77
github.com/ethereum/go-ethereum/cmd/utils.func·001()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:61 +0x241
created by github.com/ethereum/go-ethereum/cmd/utils.HandleInterrupt
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:63 +0xb5

goroutine 1 [runnable]:
github.com/ethereum/go-ethereum/logger.Flush()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:119 +0x68
main.main()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:282 +0x199

goroutine 5 [runnable]:
sync.(*WaitGroup).Wait(0xc20801e4a0)
	/usr/lib/go/src/sync/waitgroup.go:132 +0x169
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:91 +0x600
created by github.com/ethereum/go-ethereum/logger.init·1
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:44 +0x25

goroutine 8 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x1533b00)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x78
created by github.com/ethereum/go-ethereum/logger/glog.init·1
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x77

goroutine 7 [syscall, 1 minutes]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 2064 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 37 [runnable]:
github.com/ethereum/go-ethereum/miner.(*worker).update(0xc223226380)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:196 +0x28a
created by github.com/ethereum/go-ethereum/miner.newWorker
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:129 +0x310

goroutine 38 [chan receive, 2064 minutes]:
github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc223226380)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:235 +0x6f
created by github.com/ethereum/go-ethereum/miner.newWorker
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:130 +0x32a

goroutine 25 [runnable]:
github.com/ethereum/go-ethereum/event/filter.(*FilterManager).filterLoop(0xc21f0e0cc0)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/filter/eth_filter.go:74 +0x27f
created by github.com/ethereum/go-ethereum/event/filter.(*FilterManager).Start
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/filter/eth_filter.go:31 +0x32

goroutine 125 [runnable]:
github.com/ethereum/go-ethereum/event/filter.(*FilterManager).filterLoop(0xc21f0e0ac0)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/filter/eth_filter.go:74 +0x27f
created by github.com/ethereum/go-ethereum/event/filter.(*FilterManager).Start
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/filter/eth_filter.go:31 +0x32

goroutine 52 [select]:
github.com/ethereum/go-ethereum/xeth.(*XEth).start(0xc2145b1450)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/xeth.go:122 +0x702
created by github.com/ethereum/go-ethereum/xeth.New
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/xeth.go:112 +0x5c0

goroutine 54 [IO wait, 2063 minutes]:
net.(*pollDesc).Wait(0xc214832300, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc214832300, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2148322a0, 0x0, 0x7f812d43bac0, 0xc20c271a38)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc22270b620, 0xdeaddeaddeaddead, 0x0, 0x0)
	/usr/lib/go/src/net/unixsock_posix.go:282 +0x56
github.com/ethereum/go-ethereum/rpc/comms.func·002()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/comms/ipc_unix.go:37 +0x5e
created by github.com/ethereum/go-ethereum/rpc/comms.startIpc
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/comms/ipc_unix.go:72 +0x2aa

goroutine 55 [select]:
github.com/ethereum/go-ethereum/xeth.(*XEth).start(0xc2145b1520)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/xeth.go:122 +0x702
created by github.com/ethereum/go-ethereum/xeth.New
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/xeth.go:112 +0x5c0

goroutine 57 [IO wait]:
net.(*pollDesc).Wait(0xc214832370, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc214832370, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc214832310, 0x0, 0x7f812d43bac0, 0xc24e15a7a0)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc222cee008, 0xecd13147b, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/ethereum/go-ethereum/rpc.(*stoppableTCPListener).Accept(0xc2222b8450, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/types.go:346 +0xe8
net/http.(*Server).Serve(0xc2222daa80, 0x7f811b54aa50, 0xc2222b8450, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f811b54aa50, 0xc2222b8450, 0x7f812d43be68, 0xc22270bdc0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1606 +0xa1
created by github.com/ethereum/go-ethereum/rpc.Start
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:51 +0x98f
```

maybe related to #869 but the trace above is different in case it helps

**Comment by fjl** [comment]
fixed in #1416.
