### ISSUE TITLE
http panic on RPC from an eth-net-intelligence-api call

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#1312]
This was caused by a eth-net-intelligence-api call.  

````
0622 08:54:17.327456    8116 server.go:1775] http: panic serving 127.0.0.1:45968: runtime error: index out of range
goroutine 9233907 [running]:
net/http.func·011()
        /usr/lib/go/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/rpc.NewBlockRes(0xc24bca6840, 0xffffffffffffff00, 0xc24bca6840)
        /home/aeufemio/projects/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/responses.go:155 +0xe92
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc21615a018, 0xc241930b90, 0xc2350c7988, 0x0, 0x0)
        /home/aeufemio/projects/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/api.go:118 +0x309a
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc21615a018, 0xc241930b90, 0x200)
        /home/aeufemio/projects/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:134 +0x7f
github.com/ethereum/go-ethereum/rpc.func·001(0x7f206c4b0800, 0xc21e3d2000, 0xc208035040)
        /home/aeufemio/projects/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:90 +0x496
net/http.HandlerFunc.ServeHTTP(0xc216f9e450, 0x7f206c4b0800, 0xc21e3d2000, 0xc208035040)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x7f206c4b0800, 0xc21e3d2000, 0xc208035040)
        /home/aeufemio/projects/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/types.go:318 +0x201
net/http.HandlerFunc.ServeHTTP(0xc210e51a20, 0x7f206c4b0800, 0xc21e3d2000, 0xc208035040)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20f300960, 0x7f206c4b0800, 0xc21e3d2000, 0xc208035040)
        /usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc24651a0a0)
        /usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1751 +0x35e
```

Corresponding error from eth-net-intelligence-api

```
015-06-22 08:54 +08:00: [eth] xx> getPending error:  [Error: Invalid JSON RPC response]
2015-06-22 08:54 +08:00: [eth] ==> Got same block: 668291

**Comment by bas-vk** [comment]
Will be fixed in #1241
