### ISSUE TITLE
Crash & DB corruption after heavy RPC use

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#1345]
After several hours of heavy RPC usage via IPC geth crashed and corrupted it's database. See the following gist for the stack trace: https://gist.github.com/anonymous/f709552e2b0aef1e481b

DB error was: Fatal: LastBlock not found. Please run removedb and resync.

RPC calls used were: eth_getFilterChanges, eth_getCode, eth_getBalance, eth_call and eth_getBlockByNumber

**Comment by obscuren** [comment]
Thanks. Relevant part @zsfelfoldi 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x51cc1f]

goroutine 95 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(0x0, 0x7d2ac1c642ad3c2e)
	/home/go/src/github.com/ethereum/go-ethereum/core/types/block.go:293 +0x1f
github.com/ethereum/go-ethereum/eth.(*GasPriceOracle).processBlock(0xc28a207220, 0x0)
	/home/go/src/github.com/ethereum/go-ethereum/eth/gasprice.go:81 +0x33
github.com/ethereum/go-ethereum/eth.(*GasPriceOracle).processPastBlocks(0xc28a207220)
	/home/go/src/github.com/ethereum/go-ethereum/eth/gasprice.go:57 +0xa1
github.com/ethereum/go-ethereum/eth.NewGasPriceOracle(0xc2081d0b00, 0xc28a207220)
	/home/go/src/github.com/ethereum/go-ethereum/eth/gasprice.go:44 +0x34b
github.com/ethereum/go-ethereum/xeth.(*XEth).DefaultGasPrice(0xc288335c70, 0xc279e33a00)
	/home/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:46 +0x39
github.com/ethereum/go-ethereum/xeth.(*XEth).Call(0xc288335c70, 0x0, 0x0, 0xc32d36e8d0, 0x2a, 0xc2605f4f40, 0x1, 0xccdf30, 0x5, 0xccdf30, ...)
	/home/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:845 +0x3c7
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).doCall(0xc22c5c5ec0, 0xc25b619180, 0x92, 0xa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:330 +0x30f
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Call(0xc22c5c5ec0, 0xc28a207040, 0x0, 0x0, 0x0, 0x0)
	/home/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:307 +0x87
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Execute(0xc22c5c5ec0, 0xc28a207040, 0x0, 0x0, 0x0, 0x0)
	/home/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:96 +0xa6
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc22a30eea0, 0xc28a207040, 0x0, 0x0, 0x0, 0x0)
	/home/go/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:51 +0x2fd
github.com/ethereum/go-ethereum/rpc/comms.handle(0x7fe38c69dce0, 0xc21eba8098, 0x7fe3942d9e00, 0xc22a30eea0, 0x0)
	/home/go/src/github.com/ethereum/go-ethereum/rpc/comms/comms.go:61 +0x271
created by github.com/ethereum/go-ethereum/rpc/comms.funcÂ·003
	/home/go/src/github.com/ethereum/go-ethereum/rpc/comms/ipc_unix.go:51 +0x1d1
```

**Comment by obscuren** [comment]
Please re open if the issue persists
