### ISSUE TITLE
SEC-53 DoS in block_processor on txs with invalid EC sig

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1384]
If at https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L77
an error is returned which does not match
```go
(IsNonceErr(err) || state.IsGasLimitErr(err) || IsInvalidTxErr(err))
```
Then it panics on line 84 as the gas variable is nil:

```go
--- FAIL: TestBcInvalidRLPTests (0.28s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5197a8]

goroutine 1457 [running]:
testing.func·006()
	/home/gs/golang/src/testing/testing.go:441 +0x181
math/big.(*Int).Add(0xc20889df80, 0xc20889df80, 0x0, 0xc2085b1600)
	/home/gs/golang/src/math/big/int.go:112 +0x38
github.com/ethereum/go-ethereum/core.(*BlockProcessor).ApplyTransaction(0xc208c22c00, 0xc208515290, 0xc2088d4980, 0xc2092798c0, 0xc2085b1680, 0xc20889df80, 0xc20876a500, 0x30, 0x0, 0x0, ...)
	/home/gs/go/src/github.com/ethereum/go-ethereum/core/block_processor.go:84 +0x3f6
```

The error returned for for test cases TRANSCT_rvalue_TooShort, TRANSCT_rvalue_TooLarge and TRANSCT_svalue_TooLarge in https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcInvalidRLPTest.json

is https://github.com/ethereum/go-ethereum/blob/develop/core/types/transaction.go#L172

We can fix this by either making these errors of type IsInvalidTxErr, but the core problem here is the check for errors specific to package core. This breaks as the tx processing calls into other packages, for example crypto, which has it's own set of errors and does not import package core.

Probably a better solution is to reconsider the error type checking in this case, and explicitly handle generic errors in a way that will properly reject the tx.

**Comment by Gustav-Simonsson** [comment]
This PR adds but skips the test that trigger this: https://github.com/ethereum/go-ethereum/pull/1385

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/1395
