### ISSUE TITLE
Clique: 2 blocks mined then : "Failed to prepare header for mining  err=unauthorized"

### ISSUE THREAD

**Issue by bgrieder** [ethereum/go-ethereum#14408]
#### System information

Geth version: 
    Version: 1.6.0-stable
    Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
    Architecture: amd64
    Protocol Versions: [63 62]

OS & Version: OSX 10.12.4 & alpine 3.5

#### Expected behaviour

Blocks are mined by sealer/miner

#### Actual behaviour

On a sealer/miner after two blocks are mined, mining stops with
 ```
geth    | INFO [05-02|16:11:56] Starting mining operation
geth    | INFO [05-02|16:11:56] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=527.021µs
geth    | INFO [05-02|16:11:57] Successfully sealed new block            number=1 hash=4b19a6…e4259d
geth    | INFO [05-02|16:11:57] 🔨 mined potential block                  number=1 hash=4b19a6…e4259d
geth    | INFO [05-02|16:11:57] Commit new mining work                   number=2 txs=0 uncles=0 elapsed=1.047ms
geth    | INFO [05-02|16:12:11] Successfully sealed new block            number=2 hash=887d0c…0767d6
geth    | INFO [05-02|16:12:11] 🔨 mined potential block                  number=2 hash=887d0c…0767d6
geth    | ERROR[05-02|16:12:11] Failed to prepare header for mining      err=unauthorized
```

On any other node when synchronizing, the output is 
````
INFO [05-02|18:16:29] Block synchronisation started
INFO [05-02|18:16:29] Imported new block headers               count=2 elapsed=1.377ms  number=2 hash=887d0c…0767d6 ignored=0
INFO [05-02|18:16:29] Imported new chain segment               blocks=2 txs=0 mgas=0.000 elapsed=1.213ms  mgasps=0.000 number=2 hash=887d0c…0767d6
ERROR[05-02|18:16:29] Failed to prepare header for mining      err=unauthorized
````

Restarting the node yields
````
INFO [05-02|18:17:50] Initialised chain configuration          config="{ChainID: 3762 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Engine: clique}"
INFO [05-02|18:17:50] Initialising Ethereum protocol           versions="[63 62]" network=3762
INFO [05-02|18:17:50] Loaded most recent local header          number=2 hash=887d0c…0767d6 td=3
INFO [05-02|18:17:50] Loaded most recent local full block      number=2 hash=887d0c…0767d6 td=3
INFO [05-02|18:17:50] Loaded most recent local fast block      number=2 hash=887d0c…0767d6 td=3
WARN [05-02|18:17:50] Blockchain not empty, fast sync disabled
ERROR[05-02|18:17:50] Failed to prepare header for mining      err=unauthorized
````

#### Steps to reproduce the behaviour

1. Assuming a data-dir of DATA_DIR; a subdirectory `DATA_DIR/keystore` is created and an existing 
 key is dropped. That key is for an account registered as a "sealer" when generating `genesis.json` with `puppeth`
2. The data-dir is initialized with : ` /geth --datadir "$DATA_DIR" init genesis.json` 
3. The node is started:
```
/geth \
     --networkid 3762 \
     --datadir "$DATA_DIR" \
     --ethash.dagdir "$DATA_DIR/.etash" \
     --rpc --rpcaddr "0.0.0.0" --rpcport "8545"  --rpcapi "admin,net,miner,personal,eth,web3" --rpccorsdomain "*"\
     --ws --wsaddr "0.0.0.0" --wsport "8546" --wsapi "admin,miner,net,personal,eth,web3" --wsorigins "*"\
     --ipcpath "$DATA_DIR/geth.ipc" \
     --port "18002" \
     --cache 1024 \
     --nat "any" \
     --verbosity $GETH_VERBOSITY \
     --botnodes $GETH_BOOT_NODES
```
4. the account is unlocked using the javascript console: `personal.unlockAccount('0x12...456','pass')`
5. mining is started: `miner.start(1)`

#### genesis.json 

Generated using `puppeth`

```
{
  "config": {
    "chainId": 3762,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "clique": {
      "period": 15,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5908570a",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x4f6e6469666c6f20436c69717565203337363200000000000000000000000000035e19356880f86804b5fbf7015192be271ab8e426177afe720b3ad16a84d04e195dc6d4a66f82cd801e1cf176afdf340b190a98799666d534f8e953c4849b7564b9763e65f63d0754472374a420af940000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0000000000000000000000000000000000000000": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000001": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000002": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000003": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000004": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000005": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000006": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000007": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000008": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000009": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000000a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000000b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000000c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000000d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000000e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000000f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000010": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000011": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000012": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000013": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000014": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000015": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000016": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000017": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000018": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000019": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000001a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000001b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000001c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000001d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000001e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000001f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000020": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000021": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000022": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000023": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000024": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000025": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000026": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000027": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000028": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000029": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000002a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000002b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000002c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000002d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000002e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000002f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000030": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000031": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000032": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000033": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000034": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000035": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000036": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000037": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000038": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000039": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000003a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000003b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000003c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000003d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000003e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000003f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000040": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000041": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000042": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000043": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000044": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000045": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000046": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000047": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000048": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000049": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000004a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000004b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000004c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000004d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000004e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000004f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000050": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000051": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000052": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000053": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000054": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000055": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000056": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000057": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000058": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000059": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000005a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000005b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000005c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000005d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000005e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000005f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000060": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000061": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000062": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000063": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000064": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000065": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000066": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000067": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000068": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000069": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000006a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000006b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000006c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000006d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000006e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000006f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000070": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000071": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000072": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000073": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000074": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000075": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000076": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000077": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000078": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000079": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000007a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000007b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000007c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000007d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000007e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000007f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000080": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000081": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000082": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000083": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000084": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000085": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000086": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000087": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000088": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000089": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000008a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000008b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000008c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000008d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000008e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000008f": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000090": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000091": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000092": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000093": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000094": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000095": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000096": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000097": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000098": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000099": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000009a": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000009b": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000009c": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000009d": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000009e": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000009f": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a0": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a1": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a2": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a3": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a4": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a5": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a6": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a7": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a8": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000a9": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000aa": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ab": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ac": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ad": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ae": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000af": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b0": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b1": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b2": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b3": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b4": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b5": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b6": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b7": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b8": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000b9": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ba": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000bb": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000bc": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000bd": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000be": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000bf": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c0": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c1": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c2": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c3": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c4": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c5": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c6": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c7": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c8": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000c9": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ca": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000cb": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000cc": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000cd": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ce": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000cf": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d0": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d1": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d2": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d3": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d4": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d5": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d6": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d7": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d8": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000d9": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000da": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000db": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000dc": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000dd": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000de": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000df": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e0": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e1": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e2": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e3": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e4": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e5": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e6": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e7": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e8": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000e9": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ea": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000eb": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ec": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ed": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ee": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ef": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f0": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f1": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f2": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f3": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f4": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f5": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f6": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f7": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f8": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000f9": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000fa": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000fb": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000fc": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000fd": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000fe": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ff": {
      "balance": "0x1"
    },
    "26177afe720b3ad16a84d04e195dc6d4a66f82cd": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "801e1cf176afdf340b190a98799666d534f8e953": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  }
}
````

**Comment by karalabe** [comment]
As far as I know, the JavaScript console only temporarily unlocks an account, so after some time (5 mins I believe), it will get locked back up. You can permanently unlock an account from the CLI, or from within the console you can do `personal.unlockAccount("0x...", "password", 0)`, where the last `0` means to permanently unlock.

**Comment by bgrieder** [comment]
@karalabe Thanks. Tried that but I am still getting the error. 

I removed the chaindata and reinitialized the node but as you can see from the timestamps of the trace below, it happens almost immediately

````
geth    | INFO [05-03|07:08:16] Starting mining operation
geth    | INFO [05-03|07:08:16] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=563.494µs
geth    | INFO [05-03|07:08:16] Successfully sealed new block            number=1 hash=cc2986…fcc6ab
geth    | INFO [05-03|07:08:16] 🔨 mined potential block                  number=1 hash=cc2986…fcc6ab
geth    | INFO [05-03|07:08:16] Commit new mining work                   number=2 txs=0 uncles=0 elapsed=1.668ms
geth    | INFO [05-03|07:08:32] Successfully sealed new block            number=2 hash=21c1b3…03ec57
geth    | INFO [05-03|07:08:32] 🔨 mined potential block                  number=2 hash=21c1b3…03ec57
geth    | ERROR[05-03|07:08:32] Failed to prepare header for mining      err=unauthorized
````

**Comment by karalabe** [comment]
What does `clique.getSnapshot()` print?

**Comment by bgrieder** [comment]
@karalabe  Here is what I did

1. reinitialize the node and run `clique.getSnaphsot()`:

```
{
  hash: "0x964a8d12b8c0b2e4fd9bc62a0431e0e51ea2d2e162bbee0d2c25df4dccfb8525",
  number: 0,
  recents: {},
  signers: {
    0x035e19356880f86804b5fbf7015192be271ab8e4: {},
    0x26177afe720b3ad16a84d04e195dc6d4a66f82cd: {},
    0x801e1cf176afdf340b190a98799666d534f8e953: {},
    0xc4849b7564b9763e65f63d0754472374a420af94: {}
  },
  tally: {},
  votes: null
}
```

2. unlock the account, start mining() => the error mentioned above happens

3. run `clique.getSnapshot()` and I get

````
Error: unauthorized
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
````

**Comment by karalabe** [comment]
Hmmm, it shouldn't have let you mine the second block. If you have 4 signers, that each singer is allowed to sign 1 out of 3 blocks. That's probably the reason why it goes belly up. I'll have to look into it though as to why it managed to sign the second block. Let me try to repro it and I'll get back to you.

**Comment by bgrieder** [comment]
@karalabe Thanks. Same result with version Geth/v1.6.1-unstable-59966255/linux-amd64/go1.7.3 (running on alpine 3.5 inside a docker container)

**Comment by karalabe** [comment]
Nvm, found the bug. It can only ever happen when starting the chain (and it will happen if the number of miners > 3) :)) Will submit a fix in a moment.

**Comment by bgrieder** [comment]
Great !

just in case this is of any help (run on OSX with v1.6.0-stable)

Before mining starts, I get,

````
Error: write unix ->/opt/geth.data/clique-3762/geth.ipc: use of closed network connection
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
````

After mining started and failed, I get

````
{
  hash: "0x94a91a32d6470a0c1a9fd0744751658767ea2db4bd3d103332df91a529b9e468",
  number: 1,
  recents: {
    1: "0x801e1cf176afdf340b190a98799666d534f8e953"
  },
  signers: {
    0x035e19356880f86804b5fbf7015192be271ab8e4: {},
    0x26177afe720b3ad16a84d04e195dc6d4a66f82cd: {},
    0x801e1cf176afdf340b190a98799666d534f8e953: {},
    0xc4849b7564b9763e65f63d0754472374a420af94: {}
  },
  tally: {},
  votes: []
}
````

**Comment by karalabe** [comment]
I think I have a fix https://github.com/ethereum/go-ethereum/issues/14411 :) If you want to give it a spin, I'd appreciate any feedback.

**Comment by bgrieder** [comment]
@karalabe Sure. As soon as the Travis build is finished; I will give it a go.

**Comment by bgrieder** [comment]
@karalabe Looks good. I built a docker version from sources with your commit

`instance=Geth/v1.6.1-unstable-02fa3e31/linux-amd64/go1.7.3`

After mining, I get,

```
geth    | INFO [05-03|08:50:03] WebSocket endpoint opened: ws://0.0.0.0:8546
geth    | INFO [05-03|08:50:34] Starting mining operation
geth    | INFO [05-03|08:50:34] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=298.261µs
geth    | INFO [05-03|08:50:35] Successfully sealed new block            number=1 hash=293c36…c8322e
geth    | INFO [05-03|08:50:35] 🔨 mined potential block                  number=1 hash=293c36…c8322e
geth    | INFO [05-03|08:50:35] Commit new mining work                   number=2 txs=0 uncles=0 elapsed=952.25µs
geth    | INFO [05-03|08:50:35] Signed recently, must wait for others
```

I will upgrade all my nodes and fire up my network to confirm

**Comment by karalabe** [comment]
The commit was also merged to master, so it should pop un on docker hub fairly quick.

**Comment by karalabe** [comment]
Yup, just published it.

**Comment by bgrieder** [comment]
@karalabe 👍  Managed to get the network mining with 3 out of the 4 signers started

**Comment by karalabe** [comment]
Sweet, then it works correctly :) Half+1 miners are needed for the chain to progress.

**Comment by bgrieder** [comment]
@karalabe Since I have your attention ;)

I updated this prior question on StakExchange: https://ethereum.stackexchange.com/questions/15644/setting-up-a-private-poa-clique-network-with-puppeth

It would be great if you could answer that one: https://ethereum.stackexchange.com/questions/15541/how-to-add-new-sealer-in-geth-1-6-proof-of-authority

**Comment by karalabe** [comment]
Done :)

**Comment by minherc** [comment]
err:
The node is started:
`/geth \
     --networkid 3762 \
     --datadir "$DATA_DIR" \
     --ethash.dagdir "$DATA_DIR/.etash" \
     --rpc --rpcaddr "0.0.0.0" --rpcport "8545"  --rpcapi "admin,net,miner,personal,eth,web3" --rpccorsdomain "*"\
     --ws --wsaddr "0.0.0.0" --wsport "8546" --wsapi "admin,miner,net,personal,eth,web3" --wsorigins "*"\
     --ipcpath "$DATA_DIR/geth.ipc" \
     --port "18002" \
     --cache 1024 \
     --nat "any" \
     --verbosity $GETH_VERBOSITY \
     --b**OO**tnodes $GETH_BOOT_NODES`

**Comment by coinmini** [comment]
bootnode problem. should use admin.addPeers()
