### ISSUE TITLE
Mobile: go.Seq$Ref.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14429]
#### System information

Geth version: 1.6.1
OS & Version: Android

#### Expected behaviour

Should not crash

#### Actual behaviour

crashes

#### Steps to reproduce the behaviour

This is mainly happening when the service is in background - googling the error a bit hints that it might have to to with power save functions of the phone.
That said I did not experience this problem often before - will have to research more if this came with rinkeby getting more blocks or an update of geth (will go back some versions soon to check if this is the problem)

#### Backtrace

````
05-05 20:24:11.886 28500-28509/org.walleth E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
                                                             Process: org.walleth, PID: 28500
                                                             java.util.concurrent.TimeoutException: go.Seq$Ref.finalize() timed out after 10 seconds
                                                                 at go.Seq.destroyRef(Native Method)
                                                                 at go.Seq$Ref.finalize(Seq.java:128)
                                                                 at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                 at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                 at java.lang.Thread.run(Thread.java:818)
````

**Comment by ligi** [comment]
closing this as I might have found the reason - will reopen if this is not the case
