### ISSUE TITLE
RPC: crash on personal.importRawKey

### ISSUE THREAD

**Issue by chfast** [ethereum/go-ethereum#14542]
#### System information

Geth version: 1.6.1
OS & Version: Linux

#### Steps to reproduce the behaviour
```
personal.importRawKey("", "")
```

#### Backtrace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x693bdb]

goroutine 567 [running]:
github.com/ethereum/go-ethereum/accounts/keystore.newKeyFromECDSA(0x0, 0x513124)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/key.go:143 +0x4b
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).ImportECDSA(0xc420114000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:449 +0x6e
github.com/ethereum/go-ethereum/internal/ethapi.(*PrivateAccountAPI).ImportRawKey(0xc42043a160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:290 +0x184
reflect.Value.call(0xc42038eb00, 0xc42000ef30, 0x13, 0xe99ef7, 0x4, 0xc423bd4550, 0x3, 0x3, 0xc423b80e00, 0x10, ...)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc42038eb00, 0xc42000ef30, 0x13, 0xc423bd4550, 0x3, 0x3, 0x2, 0x2, 0x0)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc420e67ce0, 0x16bfca0, 0xc423bf2120, 0x16c4200, 0xc423bd4460, 0xc423bb7b90, 0xc421c2c3c0, 0xc420e67cfc, 0x836413)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:328 +0x758
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc420e67ce0, 0x16bfca0, 0xc423bf2120, 0x16c4200, 0xc423bd4460, 0xc423bb7b90)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:350 +0x1ba
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc423bce510, 0xc420e67ce0, 0xc423bce520, 0x16c4200, 0xc423bd4460, 0xc42245d1f8, 0x1, 0x1, 0xc42048a000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0xa9
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0x352
```

**Comment by fjl** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/14502
