### ISSUE TITLE
puppeth segfault installing faucet if genesis.json is missing

### ISSUE THREAD

**Issue by roo2** [ethereum/go-ethereum#14789]
#### System information

Geth version: 
```
Geth
Version: 1.6.6-stable
Git Commit: 10a45cb59bd9bc9f717817afc029a57b222e558d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

```
OS & Version: ubuntu 16.10
Commit hash : 10a45cb59bd9bc9f717817afc029a57b222e558d

#### Expected behaviour

An error message explaining that the network needs to be setup with a genesis.json before deploying a faucet

#### Actual behaviour
Crash

#### Steps to reproduce the behaviour

Setup an (ubuntu 16.x) server with docker.io and docker-compose
**DONT** setup genesis.json via puppeth
Add the server to puppeth via ` 3. Manage tracked machines`
Select to install a network component via ` 5. Faucet    - Crypto faucet to give away funds`

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x83dc67]

goroutine 1 [running]:
main.(*wizard).deployFaucet(0xc4200e8120)
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_faucet.go:51 +0x177
main.(*wizard).deployComponent(0xc4200e8120)
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_network.go:192 +0x532
main.(*wizard).run(0xc4200e8120)
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_intro.go:144 +0x10e2
main.main.func1(0xc4200cfa40, 0xc4200cfa40, 0xc420149c57)
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:51 +0x2fc
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x8be5a0, 0x987d88, 0xc4200cfa40, 0xc420021020, 0x0)
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xd4
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200cad00, 0xc4200102c0, 0x1, 0x1, 0x0, 0x0)
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:259 +0x70d
main.main()
	/build/ethereum-VipGVy/ethereum-1.6.6+build10111+yakkety/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:54 +0x261

````

**Comment by karalabe** [comment]
Whoops, thanks for the report! Will fix.

**Comment by karalabe** [comment]
Btw, puppeth can retrieve the genesis json from active bootnodes, so if you already deployed a bootnode, that should be enough too.

**Comment by roo2** [comment]
thanks!
