### ISSUE TITLE
Geth on OSX segfaults for most of 1.6x releases

### ISSUE THREAD

**Issue by slothbag** [ethereum/go-ethereum#14877]
#### System information

Geth version: 1.6.x
OS & Version: OSX

I had to go back to 1.5.9 for it to not crash.. although I skipped 1.6.0, 1.6.1, 1.6.2

#### Expected behaviour
Not crash

#### Actual behaviour
It crashes

#### Backtrace

````
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff84d48939]

runtime stack:
runtime.throw(0x4af5223, 0x2a)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x489c220, 0xc420496728, 0xc420496720)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/cgocall.go:131 +0xe2 fp=0xc4204966e8 sp=0xc4204966a8
github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid._Cfunc_hid_enumerate(0x0, 0x0)
	github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid/_obj/_cgo_gotypes.go:248 +0x4e fp=0xc420496728 sp=0xc4204966e8
github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid.Enumerate(0xc400000000, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid/hid_enabled.go:70 +0x71 fp=0xc4204967f8 sp=0xc420496728
github.com/ethereum/go-ethereum/accounts/usbwallet.(*LedgerHub).refreshWallets(0xc4200be0f0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/ledger_hub.go:120 +0xd5 fp=0xc420496bf8 sp=0xc4204967f8
github.com/ethereum/go-ethereum/accounts/usbwallet.NewLedgerHub(0xc42016e6c0, 0x28, 0x40000)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/ledger_hub.go:75 +0x84 fp=0xc420496c30 sp=0xc420496bf8
github.com/ethereum/go-ethereum/node.makeAccountManager(0xc4201a8000, 0x4, 0x4aa2967, 0x4, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/node/config.go:396 +0x1d5 fp=0xc420496d10 sp=0xc420496c30
github.com/ethereum/go-ethereum/node.New(0xc4201a8000, 0xc42006f2d0, 0x6, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/node/node.go:110 +0x1c7 fp=0xc420496dd8 sp=0xc420496d10
main.makeConfigNode(0xc42008f540, 0xc42006ee00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/config.go:127 +0x3e4 fp=0xc4204975c0 sp=0xc420496dd8
main.makeFullNode(0xc42008f540, 0x47e7c4)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/config.go:152 +0x60 fp=0xc420497cb8 sp=0xc4204975c0
main.geth(0xc42008f540, 0x4b55940, 0xb2d05e00)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:202 +0x2b fp=0xc420497ce0 sp=0xc420497cb8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x494fa00, 0x4b56bb0, 0xc42008f540, 0xc42008f540, 0xc420497f48)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xd4 fp=0xc420497d08 sp=0xc420497ce0
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420122d00, 0xc4200101f0, 0x1, 0x1, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:259 +0x70d fp=0xc420497f28 sp=0xc420497d08
main.main()
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:192 +0x55 fp=0xc420497f88 sp=0xc420497f28
runtime.main()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/proc.go:185 +0x20a fp=0xc420497fe0 sp=0xc420497f88
runtime.goexit()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420497fe8 sp=0xc420497fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc420014960)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:125 +0x63
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newRecursiveTree
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:119 +0x1d4

goroutine 7 [sleep, locked to thread]:
time.Sleep(0x3b9aca00)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/time.go:59 +0xf9
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.gosource(0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:76 +0x2a
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify._cgoexpwrap_bb0f79ac5475_gosource(0x0)
	github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/_obj/_cgo_gotypes.go:384 +0x2b
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/_obj/_cgo_gotypes.go:212 +0x41
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1.func1()
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:68 +0x6f
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:70 +0x4e

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/os/signal/signal_unix.go:28 +0x41

goroutine 9 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x51a34e0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/meter.go:221 +0x4c
created by github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics.NewMeter
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/meter.go:40 +0x127

goroutine 18 [select, locked to thread]:
runtime.gopark(0x4b574e0, 0x0, 0x4aa59e6, 0x6, 0x18, 0x2)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420032f50, 0x0, 0x18)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420032f50)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/signal_unix.go:434 +0x265
runtime.goexit()
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/asm_amd64.s:2197 +0x1

goroutine 35 [semacquire]:
sync.runtime_Semacquire(0x51c902c)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0x51c9020)
	/Users/travis/.gimme/versions/go1.8.3.darwin.amd64/src/sync/waitgroup.go:131 +0x7a
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*stream).Start(0xc42000c3e0, 0x28, 0xc420010320)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:161 +0x5b
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*fsevents).watch(0xc420011bc0, 0xc42016e6c0, 0x28, 0x1b00, 0x4984420, 0xc420016720)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents.go:206 +0x1dd
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*fsevents).Watch(0xc420011bc0, 0xc42016e6c0, 0x28, 0x1b0000001b00, 0x0, 0xc4204a2180)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents.go:230 +0x4f
go.(*struct { github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.watcher; github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.recursiveWatcher }).Watch(0xc42000d880, 0xc42016e6c0, 0x28, 0xc400001b00, 0xc4204a2180, 0x1b00)
	<autogenerated>:47 +0x65
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*recursiveTree).Watch(0xc420014960, 0xc42016e6c0, 0x28, 0xc4204a2180, 0xc420010210, 0x1, 0x1, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:288 +0x10cd
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.Watch(0xc42016e6c0, 0x28, 0xc4204a2180, 0xc420010210, 0x1, 0x1, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/notify.go:64 +0x78
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc420176b80)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:68 +0x1b3
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x5f
````

**Comment by fjl** [comment]
Assigned to @karalabe because USB stuff is on the stack.

**Comment by karalabe** [comment]
Should be fixed now on master.
