### ISSUE TITLE
consensus/ethash: segfault race

### ISSUE THREAD

**Issue by immesys** [ethereum/go-ethereum#14943]
#### System information

Geth version: `geth version`
Commit  ab5646c53 (1.6.7) embedded into a different program

OS & Version: Linux, Ubuntu 16.04

#### Expected behaviour
Private chain syncs ok

#### Actual behaviour
A few seconds into fast sync, it crashes with sigsegv, backtrace below.

I think it might have something to do with concurrency. If I put a lock around VerifySeal so that only one call happens at a time, the problem goes away (and I lose all of the performance). Is VerifySeal expected to be threadsafe? I would expect so. Does anyone have any ideas on how to debug this?

```
unexpected fault address 0x7f87eafe6d08
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f87eafe6d08 pc=0x92159f]

goroutine 3017 [running]:
runtime.throw(0x11e4127, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc429d457d0 sp=0xc429d457b0
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc429d45820 sp=0xc429d457d0
github.com/ethereum/go-ethereum/consensus/ethash.fnvHash(0xc429d45880, 0x10, 0x10, 0x7f87eafe6d08, 0x4064b0, 0x4064b0)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:183 +0x2f fp=0xc429d45830 sp=0xc429d45820
github.com/ethereum/go-ethereum/consensus/ethash.generateDatasetItem(0x7f87eafc0008, 0x40fff0, 0x40fff0, 0xc4006fb18a, 0xc423df30c0, 0x10, 0x40, 0x40)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:210 +0x2dd fp=0xc429d458d8 sp=0xc429d45830
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoLight.func1(0xc4006fb18a, 0x20, 0x20, 0xc421281280)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:336 +0x51 fp=0xc429d45940 sp=0xc429d458d8
github.com/ethereum/go-ethereum/consensus/ethash.hashimoto(0xc429d45c00, 0x20, 0x20, 0x8bd27dbedc1a4441, 0x40ffef80, 0xc423e02030, 0x9dbabc8e5d2e7bbf, 0x1b79c118f127ffe2, 0x3a8aadddeea0cc5a, 0x21575580ec58deed, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:312 +0x30d fp=0xc429d45ad8 sp=0xc429d45940
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoLight(0x40ffef80, 0x7f87eafc0008, 0x40fff0, 0x40fff0, 0xc429d45c00, 0x20, 0x20, 0x8bd27dbedc1a4441, 0xc423e02000, 0x20, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:344 +0x131 fp=0xc429d45b58 sp=0xc429d45ad8
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifySeal(0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc42137c240, 0x1, 0x5)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:456 +0x1e2 fp=0xc429d45c88 sp=0xc429d45b58
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeader(0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc42137c240, 0xc42137c000, 0x10100, 0x0, 0xc42119a980)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:271 +0x6fd fp=0xc429d45e48 sp=0xc429d45c88
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeaderWorker(0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc4248fa000, 0x780, 0x780, 0xc43027c800, 0x780, 0x780, 0x38, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:164 +0x20c fp=0xc429d45ee8 sp=0xc429d45e48
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders.func1(0xc42ecf9f80, 0xc42c388000, 0x780, 0x780, 0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc4248fa000, 0x780, 0x780, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:115 +0xe9 fp=0xc429d45f70 sp=0xc429d45ee8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc429d45f78 sp=0xc429d45f70
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:118 +0x320
```

**Comment by immesys** [comment]
I can elucidate a bit more. In [VerifySeal in ethash's consensus.go](https://github.com/ethereum/go-ethereum/blob/8c313eed2614990089114bfe5fea7540f4298752/consensus/ethash/consensus.go#L471), there is this line:

```
cache := ethash.cache(number)
```

cache is a `[]uint32`. Now you would agree that doing this should change nothing right?

```
origcache := ethash.cache(number)
cache := make([]uint32,len(origcache))
for i, v := range origcache {
   cache[i] = v
}
```
Well if I do this (essentially "verifying" that the cache array is valid memory by touching every element) then the segfault happens inside the for loop rather than happening later inside fnvHash. There is definitely something fishy about the way this cache array is handled and it is 100% reproducible on one of my machines (but not the other, which perplexes me)

**Comment by immesys** [comment]
Also if I build with race detection, I get a race report a few milliseconds before the segfault:

```
WARNING: DATA RACE
Read at 0x00c428e6f4d0 by goroutine 209:
  runtime.convT2E()
      /usr/local/go/src/runtime/iface.go:191 +0x0
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).cache()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:449 +0x4d1
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifySeal()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:455 +0x343
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeader()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:272 +0x8ef
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeaderWorker()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:165 +0x375
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders.func1()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:116 +0x104

Previous write at 0x00c428e6f4d0 by goroutine 236:
  [failed to restore the stack]

Goroutine 209 (running) created at:
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:119 +0x355
  github.com/ethereum/go-ethereum/core.(*HeaderChain).ValidateHeaderChain()
      /home/michael/go/src/github.com/ethereum/go-ethereum/core/headerchain.go:228 +0x4d4
  github.com/ethereum/go-ethereum/core.(*BlockChain).InsertHeaderChain()
      /home/michael/go/src/github.com/ethereum/go-ethereum/core/blockchain.go:1306 +0xec
  github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders()
      /home/michael/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1268 +0x733
  github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func6()
      /home/michael/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:477 +0x5b
  github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
      /home/michael/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:500 +0x5e

Goroutine 236 (running) created at:
  github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders()
      /home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:119 +0x355
  github.com/ethereum/go-ethereum/core.(*HeaderChain).ValidateHeaderChain()
      /home/michael/go/src/github.com/ethereum/go-ethereum/core/headerchain.go:228 +0x4d4
0x7f232f796000  github.com/ethereum/go-ethereum/core.(*BlockChain).InsertHeaderChain()
      /home/michael/go/src/github.com/ethereum/go-ethereum/core/blockchain.go:1306 +0xec

  github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders()
      /home/michael/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1268 +0x733
  github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func6()
      /home/michael/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:477 +0x5b
  github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
      /home/michael/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:500 +0x5e
==================
```

**Comment by fjl** [comment]
The cache slice is memory-mapped. It's nice that you can reproduce the crasher (we can't). The issue could be related to memory alignment. Can you check the memory address of the slice for a case where it crashes?

**Comment by immesys** [comment]
The memory addresses are all aligned. I added this code:

```go
        ocache := ethash.cache(number)
	fmt.Printf("XXX cache pointer is %p\n", ocache)
	cache := make([]uint32, len(ocache))
	for i, v := range ocache {
		cache[i] = v
	}
	fmt.Printf("cache was ok\n")
```
And this is what I got
```
INFO [08-10|09:47:23] Imported new state entries               count=34 flushed=4 elapsed=232.651ms processed=68 pending=347 retry=0 duplicate=0 unexpected=0
INFO [08-10|09:47:24] Imported new block receipts              count=0  elapsed=20.282ms  number=989209 hash=4aa34f…c6fbbf ignored=749
XXX cache pointer is 0x7fabf8bfc008
XXX cache pointer is 0x7fabf8bfc008
XXX cache pointer is 0x7fabf8bfc008
cache was ok
cache was ok
XXX cache pointer is 0x7fabeebe0008
unexpected fault address 0x7fabf8bfc008
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fabf8bfc008 pc=0x925c7b]
... same segfault ...
```

Interesting to see that the cache address was fine for two of the iterations through it, the third faulted. My guess is that it is being unmapped while it is still in use. I'll try some sysdig and see if I can catch the unmap syscall

**Comment by immesys** [comment]
Yeah take a look at this:

```
198250 09:58:01.421664062 1  (19642) < write res=162 data=INFO [08-10|09:58:01] Imported new state entries               count=310 flushed 
210092 09:58:01.451059040 3  (19633) > write fd=2 size=135 
210100 09:58:01.451068741 3  (19633) < write res=135 data=INFO [08-10|09:58:01] Imported new block receipts              count=280 elapsed 
224810 09:58:01.498264793 13  (19633) > write fd=1 size=51 
224815 09:58:01.498276182 13  (19633) < write res=51 data=XXX cache pointer is  0x7f360c7fb008. 
225229 09:58:01.499680120 7  (19636) > munmap addr=7F360C7FB000 length=16776904 
225241 09:58:01.499729258 7  (19636) < munmap res=0 vm_size=1336836 vm_rss=139296 vm_swap=0 
225246 09:58:01.499745667 13  (19633) > write fd=2 size=25 
225247 09:58:01.499748942 7  (19636) > write fd=1 size=51 
225248 09:58:01.499751563 13  (19633) < write res=25 data=unexpected fault address  
225249 09:58:01.499752842 13  (19633) > write fd=2 size=14 
225250 09:58:01.499753076 7  (19636) < write res=51 data=XXX cache pointer is  0x7f35eefe0008. 
225252 09:58:01.499757122 13  (19633) < write res=14 data=0x7f360c9f0000 
```

This is a sysdig trace, you can see it writes the "XXX cache pointer..." line to stdout (but not yet the "ok" line, so it is still using that array). A short while later, a munmap syscall with that address is executed. The rest of the sysdig trace is just the panic

**Comment by immesys** [comment]
@fjl this is an embedded geth, so it's possible that the way I am using the API is different to how it is used in geth standalone (I never see this just running geth console even on the same private chain), but I figured it would be important to report anyway because this shouldn't be possible, no matter how I interact with the API.

**Comment by fjl** [comment]
It's a real bug and affects geth too. Thanks for digging! In my comment earlier I meant we should look at the data pointer of the slice header (the slice is created using unsafe) but munmap while the cache is in use sounds like a probably cause.

**Comment by ralmeida** [comment]
I am also experiencing this issue, I can provide output if needed
