### ISSUE TITLE
geth panic on shutdown when running les server

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#14955]
#### System information

Geth version:
Version: 1.7.0-unstable
Git Commit: 17ce0a37de5a2712a8bf9d58df705e718b3b2cd6
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux

OS & Version: Ubuntu 16.04.2 LTS (64 bit)

Commit hash : master branch (17ce0a37de5a2712a8bf9d58df705e718b3b2cd6)

#### Expected behaviour

Clean shutdown

#### Actual behaviour

Panic on shutdown

#### Steps to reproduce the behaviour

was running geth with full node sync, synced to head, then stopped it and ran it with following flags:
``` bash
./build/bin/geth --nousb --cache 2048 --vmodule les=5,light=5 --lightserv 50
```

The light client server was generating new CHT, this was the last one generated before shutdown:
```
TRACE[08-09|15:45:55] Generated CHT                            number=217     root=0x06bdaa0f9d1ebe88f6601f762c09ba2ade88f68b581ec77dcf2b3e666e071a5c
```

#### Backtrace

````
^CINFO [08-09|15:45:56] Got interrupt, shutting down... 
INFO [08-09|15:45:56] IPC endpoint closed: /home/gs/.ethereum/geth.ipc 
INFO [08-09|15:45:56] Blockchain manager stopped 
INFO [08-09|15:45:56] Stopping Ethereum protocol 
INFO [08-09|15:45:56] Ethereum protocol stopped 
INFO [08-09|15:45:56] Stopping light Ethereum protocol 
INFO [08-09|15:45:56] Terminated topic registration            topic=LES@d4e56740f876aef8
INFO [08-09|15:45:56] Light Ethereum protocol stopped 
INFO [08-09|15:45:56] Transaction pool stopped 
panic: Canonical hash not found

goroutine 4590 [running]:
github.com/ethereum/go-ethereum/les.makeCht(0x16db380, 0xc4200720d0, 0xc4c7755920)
	/home/gs/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server.go:383 +0x505
github.com/ethereum/go-ethereum/les.(*ProtocolManager).blockLoop.func1.1(0xc423b5c010, 0xc42023e8c0, 0xc423ab43c0)
	/home/gs/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server.go:315 +0x4a
created by github.com/ethereum/go-ethereum/les.(*ProtocolManager).blockLoop.func1
	/home/gs/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server.go:321 +0x829
````

**Comment by Gustav-Simonsson** [comment]
Looks like `hash := core.GetCanonicalHash(db, num)` returns the empty hash because the DB is shutdown?

This code is running in a routine spawned at https://github.com/ethereum/go-ethereum/blob/master/les/server.go#L277

I'm guessing this routine should listen to a shutdown message emitted in https://github.com/ethereum/go-ethereum/blob/master/les/server.go#L89 to conform to the service behavior defined at https://github.com/ethereum/go-ethereum/blob/master/node/service.go#L74
