### ISSUE TITLE
Panic Node

### ISSUE THREAD

**Issue by Slinky13th** [ethereum/go-ethereum#15011]
#### System information

Geth version: `geth version`
Geth
Version: 1.6.5-stable
Git Commit: cf87713dd42162861b7ed227f79f0638a33571df
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: windows
GOPATH=
GOROOT=c:\go
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

```
INFO [08-20|11:43:19] Block synchronisation started
panic: node 988638752a1683e1c0d156ef1d56f3b6eb6009096fb2aff6e77c99d96d629dd0: invalid number of list elements: 0

goroutine 1140 [running]:
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc04492c0c0, 0x20, 0x20, 0xc044402d80, 0x214, 0x240, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/node.go:110 +0x20b
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc0420629a0, 0xc04492c0c0, 0x20, 0x20, 0xc04493b810, 0x4, 0x41, 0xc04493b814, 0x3d, 0x3d, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:458 +0x2d5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0420629a0, 0x1480ee0, 0xc04492c0e0, 0xc04493b810, 0x41, 0x41, 0x4, 0x20, 0x20, 0xc044402b40, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:183 +0x13e
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0420629a0, 0x147ee20, 0xc0437b1cc0, 0xc04493b810, 0x41, 0x41, 0x3, 0xc04493b813, 0x3e, 0x3e, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x882
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0420629a0, 0x1480ee0, 0xc042d39c80, 0xc04493b810, 0x41, 0x41, 0x3, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:187 +0x27d
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0420629a0, 0x147ee20, 0xc043064780, 0xc04493b810, 0x41, 0x41, 0x2, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x882
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0420629a0, 0x147ee20, 0xc048024a00, 0xc04493b810, 0x41, 0x41, 0x1, 0xab49bee5e7b4729b, 0x281f90225f7268b6, 0xffd9d3b2cee2dc0e, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x882
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0420629a0, 0x147ee20, 0xc043614a00, 0xc04493b810, 0x41, 0x41, 0x0, 0xc042c84930, 0x64996f, 0xc0441dec40, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x882
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc0420629a0, 0xc0420629e8, 0x20, 0x2b, 0xc0420629e8, 0x20, 0x2b, 0xb5ba1ef, 0x14)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:149 +0xaa
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc0420629a0, 0xc0424d3ce0, 0x14, 0x14, 0x304654bfeeac96b2, 0xc042c84a08, 0x40a10a, 0xc042c84ac4, 0xb5ba1ef)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:84 +0x82
github.com/ethereum/go-ethereum/trie.(*SecureTrie).Get(0xc0420629a0, 0xc0424d3ce0, 0x14, 0x14, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:73 +0x60
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(0xc042035100, 0xa42a56fe7ad79ff5, 0x467ba6e7a66db6e5, 0x38c5fa51, 0x1)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:418 +0x134
github.com/ethereum/go-ethereum/core/state.(*StateDB).Exist(0xc042035100, 0xa42a56fe7ad79ff5, 0x467ba6e7a66db6e5, 0x38c5fa51, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:226 +0x46
github.com/ethereum/go-ethereum/core.(*StateTransition).from(0xc0439d2310, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state_transition.go:139 +0x99
github.com/ethereum/go-ethereum/core.(*StateTransition).preCheck(0xc0439d2310, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state_transition.go:197 +0x5f
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc0439d2310, 0x1485f20, 0xc04409af00, 0xc0441d6ea0, 0xc0439d2310, 0xc042c87c68, 0xc04409af00, 0xe5e820)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state_transition.go:212 +0x4a
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc043759500, 0x1485f20, 0xc04409af00, 0xc0441d6ea0, 0x467ba6e7a66db6e5, 0x38c5fa51, 0xc0424d3c60, 0xee098337d544bc52, 0x1bde71bf3915bf2a, 0xb5e37b7d)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state_transition.go:133 +0x62
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x155f660, 0xc04413c000, 0x0, 0xc0441d6ea0, 0xc042035100, 0xc0442cbb00, 0xc04520c990, 0xc0441d6de0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state_processor.go:101 +0x262
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc042139280, 0xc044e6d7a0, 0xc042035100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/state_processor.go:73 +0x541
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc04413c000, 0xc0452fe000, 0x2, 0x800, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:973 +0x11bc
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain-fm(0xc0452fe000, 0x2, 0x800, 0x8d, 0x15ada60, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/handler.go:164 +0x4f
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processContent(0xc04420e000, 0xf398a0, 0xc044f1cc40)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1409 +0x11f9
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc044f1cc40, 0xc044d85c20, 0xc04420e000)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:457 +0x5c
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:457 +0xc6
```

#### Backtrace

````
[backtrace]
````

**Comment by tomtom87** [comment]
+1 mine is doing this also

**Comment by holiman** [comment]
The reported version is `1.6.5`, which is a couple of releases back. There has been work done on the trie and downloader since then. 

Please try a recent version (either head or `1.6.7`). I'll close this ticket, but if you get the same error with the new version, please open it again.
