### ISSUE TITLE
How to use  eth_sendRawTransaction in Rpc

### ISSUE THREAD

**Issue by wunaigong** [ethereum/go-ethereum#15045]
How to use  eth_sendRawTransaction in Rpc?
Share Demo ?

**Comment by holiman** [comment]
I'm not sure exactly what you're wondering - how the thing works or how to invoke it over RPC? 

Example: 
```
> tx = eth.getBlock("latest").transactions[0]
"0x3fc6064c9d21a3884aecc725611e6e546e47a399f50110a65880fa64976e87d1"
> raw = eth.getRawTransaction(tx)
"0xf86b0d85104c533c008252099475e7f640bf6968b6f32c47a3cd82c3c2c9dcae6887aa1581278b8c418026a00671ec9175f59b712b02072c873a365f0c3537f629debb9cd11b89aabbc3ca7ba07962bff118d21ae43279d9dcf9e3e75596619cdcfa598676aa790288db8ac969"
> eth.sendRawTransaction(raw)
Error: nonce too low
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

```
If you want to use rpc instead of ipc, use something like this: 

``` 
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":[<rlp>],"id":74}' localhost:8545
```
