### ISSUE TITLE
trie: node with invalid number of list elements

### ISSUE THREAD

**Issue by paddymahoney** [ethereum/go-ethereum#15105]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Sync chain

#### Actual behaviour
panic

#### Steps to reproduce the behaviour
geth --rpc

#### Backtrace

``` 
INFO [09-06|12:43:49] Block synchronisation started 
panic: node 2c2d27f6e05dc07fab8fd97720f690b095d64a7d7a8b9054ba9bb8b95d244356: invalid number of list elements: 70

goroutine 1839 [running]:
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc4260a8040, 0x20, 0x20, 0xc425ff5b00, 0x214, 0x240, 0x0, 0x0, 0x0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/node.go:110 +0x204
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc42136db80, 0xc4260a8040, 0x20, 0x20, 0xc42607da40, 0x4, 0x41, 0xc425ff5ad3, 0x1, 0x2d, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:453 +0x2e3
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16de880, 0xc4260a8060, 0xc42607da40, 0x41, 0x41, 0x4, 0x20, 0x20, 0xc425ff58c0, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:183 +0xff
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16dc640, 0xc42608ef00, 0xc42607da40, 0x41, 0x41, 0x3, 0x16dc640, 0xc42608ef00, 0x0, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x841
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16de880, 0xc42608dce0, 0xc42607da40, 0x41, 0x41, 0x3, 0x20, 0x20, 0xc425ff5680, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:187 +0x23e
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16dc640, 0xc42608edc0, 0xc42607da40, 0x41, 0x41, 0x2, 0x16dc640, 0xc42608edc0, 0x0, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x841
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16de880, 0xc4250a2600, 0xc42607da40, 0x41, 0x41, 0x2, 0xca2b081b287a27ff, 0xb9730a39b48249b6, 0xf54594f718f89cb2, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:187 +0x23e
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16dc640, 0xc42608eb40, 0xc42607da40, 0x41, 0x41, 0x1, 0xa865ec3fc4f0366e, 0x6bec860755e6f860, 0xd3f8e0255511d960, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x841
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc42136db80, 0x16dc640, 0xc42608ec80, 0xc42607da40, 0x41, 0x41, 0x0, 0xc421618c68, 0x649e08, 0xc420635fc0, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:175 +0x841
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc42136db80, 0xc42136dbc8, 0x20, 0x2b, 0xc42136dbc8, 0x20, 0x2b, 0xc42282bbc0, 0xcc38c0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:149 +0xa3
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc42136db80, 0xc42608dae0, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:84 +0x7b
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(0xc4252274a0, 0x1cd9c74309628225, 0x12bd19e8fcde62bd, 0xf325eb22, 0x1)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:363 +0x132
github.com/ethereum/go-ethereum/core/state.(*StateDB).Exist(0xc4252274a0, 0x1cd9c74309628225, 0x12bd19e8fcde62bd, 0xf325eb22, 0xc424fbb960)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:175 +0x3f
github.com/ethereum/go-ethereum/core.(*StateTransition).to(0xc425fc3f80, 0x0, 0x0, 0x0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:155 +0xa8
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc425fc3f80, 0x16e3ca0, 0xc420cfb1a0, 0xc4250a2160, 0xc425fc3f80, 0xc42161bd90, 0xc420cfb1a0, 0xe861c0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:243 +0x377
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc425f8d500, 0x16e3ca0, 0xc420cfb1a0, 0xc4250a2160, 0x2acd4295af7cf981, 0x5bf06269, 0xc42608ca00, 0x97fd14e7dd4f67ea, 0x71a96af5f0ede39d, 0xc88e896b)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:133 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x16af560, 0xc4211ce000, 0x0, 0xc4250a2160, 0xc4252274a0, 0xc4250a4000, 0xc421139b00, 0xc4250a20a0, 0x0, 0x0, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:101 +0x25b
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc42020b580, 0xc42065a6c0, 0xc4252274a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:73 +0x53a
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc4211ce000, 0xc422e30340, 0x2, 0x2, 0x0, 0x0, 0x0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:968 +0x11c6
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc420487ba0, 0xc422e301f0, 0x2, 0x2, 0xae6b177914ef0eeb, 0xc425318780)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1355 +0x607
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc420487ba0, 0xc425318790, 0xc421234f80)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1330 +0x7f
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).(github.com/ethereum/go-ethereum/eth/downloader.processFullSyncContent)-fm(0xce71bfba00000008, 0xf612b0)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:482 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc4220ee210, 0xc422062180, 0xc4220ee200)
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:500 +0x51
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/build/ethereum-_mBr7p/ethereum-1.6.7+build10273+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:500 +0xd2

````

**Comment by holiman** [comment]
Could you provide any more info ? Were you synching from scratch, or close to the head?

**Comment by fjl** [comment]
Please follow the instructions below to display the offending value in your database. This would help us with debugging the issue.

* install go using `apt get install golang`

**Comment by fjl** [comment]
@paddymahoney ping

**Comment by ksedgwic** [comment]
I got the same error too:
```
,panic: node 3ad573c083fc3493030b9f91fd4172228fabfa3859d0319178d55fb1e2fcbee7: invalid number of list elements: 0
​
goroutine 47 [running]:
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc0aa216300, 0x20, 0x20, 0xc01fe42000, 0x93, 0x93, 0x16d, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/node.go:123 +0x1e3
github.com/ethereum/go-ethereum/trie.(*Database).node(0xc00048a780, 0x9334fc83c073d53a, 0x227241fd919f0b03, 0x9131d05938faab8f, 0xe7befce2b15fd578, 0x16d, 0xc00b32a5e0, 0x594736)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/database.go:367 +0x44e
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc07432f180, 0xc0aa2161e0, 0x20, 0x20, 0xc042b34aa0, 0x6, 0x41, 0xc01e05fe00, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:434 +0x140
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f4c80, 0xc02fd81e80, 0xc042b34aa0, 0x41, 0x41, 0x6, 0x214, 0x214, 0x16d, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:167 +0xf8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f2dc0, 0xc01e05fe00, 0xc042b34aa0, 0x41, 0x41, 0x5, 0x11f2dc0, 0xc01e05fe00, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f4c80, 0xc021cb1080, 0xc042b34aa0, 0x41, 0x41, 0x5, 0xc042b34a50, 0x8, 0x50, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:171 +0x22a
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f2dc0, 0xc020ea8500, 0xc042b34aa0, 0x41, 0x41, 0x4, 0xc042b34a50, 0x8, 0x50, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f2dc0, 0xc084a18640, 0xc042b34aa0, 0x41, 0x41, 0x3, 0xc042b34a50, 0x8, 0x50, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f2dc0, 0xc09e2e2780, 0xc042b34aa0, 0x41, 0x41, 0x2, 0xc0332336e0, 0xc07e5edea0, 0x20, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f2dc0, 0xc04019a000, 0xc042b34aa0, 0x41, 0x41, 0x1, 0x6f12dacbfe6fd007, 0x90e66b6f34b770af, 0xc00b32b158, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc07432f180, 0x11f2dc0, 0xc01e05fcc0, 0xc042b34aa0, 0x41, 0x41, 0x0, 0x20, 0xc07432f1a0, 0x20, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc07432f180, 0xc07432f1a0, 0x20, 0x20, 0xc07432f1a0, 0x20, 0x20, 0xd78d70, 0xc04e5f4880)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:133 +0x7b
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc07432f180, 0xc07e5edfc0, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:80 +0x7b
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(0xc068b048f0, 0x5a37d8e7b1177aba, 0x31b923f067f8288c, 0xa6352f4e, 0xc0498b0710)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:416 +0x131
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetNonce(0xc068b048f0, 0x5a37d8e7b1177aba, 0x31b923f067f8288c, 0xc0a6352f4e, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:216 +0x3f
github.com/ethereum/go-ethereum/core.(*TxPool).demoteUnexecutables(0xc000323dc0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1121 +0x5f6
github.com/ethereum/go-ethereum/core.(*TxPool).reset(0xc000323dc0, 0xc0966ee240, 0xc0966ee480)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:446 +0x262
github.com/ethereum/go-ethereum/core.(*TxPool).loop(0xc000323dc0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:314 +0x43c
```

**Comment by holiman** [comment]
First reporter was seemingly on `1.6.7`, second on `1.7.3`. @ksedgwic how about your version? 
@fjl can you take a look at the `checknode` output provided by @ekhvalov ?

**Comment by mdz** [comment]
@ksedgwic 's stack trace is from Geth/v1.8.20-stable-24d727b6/linux-amd64/go1.11.2
