### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference - via RPC sendRawTransaction

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#1518]
I'm sending a raw signed transaction via web3.js (sendRawTransaction) into geth, I get an invalid RPC response (i.e. geth freaks out, and response badly).

I shouldn't be able to trigger an error like this should I (especially via web3.js RPC). My node keeps working after the error (i.e. continues to mine).

Thoughts? Let me know if you need the actual raw signed transaction. I figure, even if my keys are invalid and my rpc incorrect, the error should be handled properly, at least the geth console shouldn't look like what it does below.

In order to trigger this I set my gasLimit to '00' in the raw tx. When a gasLimit is set, the runtime error doesn't get triggered.

My keys:

```
{"address":"0x900d29e97b921a4f7682ad53517838a8efdd5b6f",
"private":"761626cf9de3d4d17e2b616d77f43e4dd864bf1db6fbc3d066460f791ba627fc",
"public":"d40266fc9a1072c31c7e49aa2045ab76d76fb704e1234148cda02d87584f121bbcfcc93512a6d7a185a4b74c6dc3a2737f577c36aef1f70a0387b44820ec4651"}
```

The GETH console response:

```
I0724 10:55:21.285239    6611 server.go:1775] http: panic serving 127.0.0.1:56445: runtime error: invalid memory address or nil pointer dereference
goroutine 2999 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
math/big.(*Int).Cmp(0x0, 0xc20801caa0, 0xa95c40)
	/usr/local/go/src/math/big/int.go:311 +0x24
github.com/ethereum/go-ethereum/crypto.ValidateSignatureValues(0x0, 0x0, 0x0, 0x8)
	/home/nick/go/src/github.com/ethereum/go-ethereum/crypto/crypto.go:176 +0x3d
github.com/ethereum/go-ethereum/core/types.(*Transaction).publicKey(0xc2080a0e10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:197 +0x88
github.com/ethereum/go-ethereum/core/types.(*Transaction).From(0xc2080a0e10, 0x0, 0x0, 0x721fe35e00000000, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:175 +0xfc
github.com/ethereum/go-ethereum/core.(*TxPool).validateTx(0xc208e41c70, 0xc2080a0e10, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:175 +0xd4
github.com/ethereum/go-ethereum/core.(*TxPool).add(0xc208e41c70, 0xc2080a0e10, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:224 +0x254
github.com/ethereum/go-ethereum/core.(*TxPool).Add(0xc208e41c70, 0xc2080a0e10, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:276 +0x9f
github.com/ethereum/go-ethereum/xeth.(*XEth).PushTx(0xc208e8d6c0, 0xc208eb5200, 0x856, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:771 +0xd7
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).SendRawTransaction(0xc208eaad80, 0xc22a1fe230, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:282 +0x265
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Execute(0xc208eaad80, 0xc22a1fe230, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:119 +0xa6
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc2094a84e0, 0xc22a1fe230, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:67 +0x35d
github.com/ethereum/go-ethereum/rpc/comms.func·002(0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:152 +0x5a1
net/http.HandlerFunc.ServeHTTP(0xc208ead060, 0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/home/nick/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc208ead080, 0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc/comms.func·001(0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:111 +0x223
net/http.HandlerFunc.ServeHTTP(0xc208ead0a0, 0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208e9d680, 0x7f064dfdb348, 0xc20905a8c0, 0xc208e8c750)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208054780)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
I0724 10:55:21.286011    6611 server.go:1775] http: panic serving 127.0.0.1:56455: runtime error: invalid memory address or nil pointer dereference
goroutine 3010 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
math/big.(*Int).Cmp(0x0, 0xc20801caa0, 0xa95c40)
	/usr/local/go/src/math/big/int.go:311 +0x24
github.com/ethereum/go-ethereum/crypto.ValidateSignatureValues(0x0, 0x0, 0x0, 0x8)
	/home/nick/go/src/github.com/ethereum/go-ethereum/crypto/crypto.go:176 +0x3d
github.com/ethereum/go-ethereum/core/types.(*Transaction).publicKey(0xc2080a1050, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:197 +0x88
github.com/ethereum/go-ethereum/core/types.(*Transaction).From(0xc2080a1050, 0x0, 0x0, 0x721fe35e00000000, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:175 +0xfc
github.com/ethereum/go-ethereum/core.(*TxPool).validateTx(0xc208e41c70, 0xc2080a1050, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:175 +0xd4
github.com/ethereum/go-ethereum/core.(*TxPool).add(0xc208e41c70, 0xc2080a1050, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:224 +0x254
github.com/ethereum/go-ethereum/core.(*TxPool).Add(0xc208e41c70, 0xc2080a1050, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:276 +0x9f
github.com/ethereum/go-ethereum/xeth.(*XEth).PushTx(0xc208e8d6c0, 0xc208eb7600, 0x856, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:771 +0xd7
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).SendRawTransaction(0xc208eaad80, 0xc22a1fe2d0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:282 +0x265
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Execute(0xc208eaad80, 0xc22a1fe2d0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:119 +0xa6
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc2094a84e0, 0xc22a1fe2d0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:67 +0x35d
github.com/ethereum/go-ethereum/rpc/comms.func·002(0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:152 +0x5a1
net/http.HandlerFunc.ServeHTTP(0xc208ead060, 0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc208ead080, 0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc/comms.func·001(0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:111 +0x223
net/http.HandlerFunc.ServeHTTP(0xc208ead0a0, 0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208e9d680, 0x7f064dfdb348, 0xc20905a960, 0xc22a3220d0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208fee6e0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
I0724 10:55:21.286926    6611 server.go:1775] http: panic serving 127.0.0.1:56456: runtime error: invalid memory address or nil pointer dereference
goroutine 2924 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
math/big.(*Int).Cmp(0x0, 0xc20801caa0, 0xa95c40)
	/usr/local/go/src/math/big/int.go:311 +0x24
github.com/ethereum/go-ethereum/crypto.ValidateSignatureValues(0x0, 0x0, 0x0, 0x8)
	/home/nick/go/src/github.com/ethereum/go-ethereum/crypto/crypto.go:176 +0x3d
github.com/ethereum/go-ethereum/core/types.(*Transaction).publicKey(0xc208fc7e60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:197 +0x88
github.com/ethereum/go-ethereum/core/types.(*Transaction).From(0xc208fc7e60, 0x0, 0x0, 0x721fe35e00000000, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:175 +0xfc
github.com/ethereum/go-ethereum/core.(*TxPool).validateTx(0xc208e41c70, 0xc208fc7e60, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:175 +0xd4
github.com/ethereum/go-ethereum/core.(*TxPool).add(0xc208e41c70, 0xc208fc7e60, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:224 +0x254
github.com/ethereum/go-ethereum/core.(*TxPool).Add(0xc208e41c70, 0xc208fc7e60, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/core/transaction_pool.go:276 +0x9f
github.com/ethereum/go-ethereum/xeth.(*XEth).PushTx(0xc208e8d6c0, 0xc209660900, 0x856, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:771 +0xd7
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).SendRawTransaction(0xc208eaad80, 0xc22a3340a0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:282 +0x265
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Execute(0xc208eaad80, 0xc22a3340a0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:119 +0xa6
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc2094a84e0, 0xc22a3340a0, 0x0, 0x0, 0x0, 0x0)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:67 +0x35d
github.com/ethereum/go-ethereum/rpc/comms.func·002(0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:152 +0x5a1
net/http.HandlerFunc.ServeHTTP(0xc208ead060, 0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/home/nick/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc208ead080, 0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc/comms.func·001(0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/home/nick/go/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:111 +0x223
net/http.HandlerFunc.ServeHTTP(0xc208ead0a0, 0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208e9d680, 0x7f064dfdb348, 0xc208055220, 0xc208e8cc30)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20905aa00)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by obscuren** [comment]
Thanks. Confirmed.

**Comment by linagee** [comment]
@SilentCicero can you please paste the sendRawTransaction command you used? I'd like to try and replicate this.

**Comment by zelig** [comment]
fixed in https://github.com/ethereum/go-ethereum/pull/1541/commits
