### ISSUE TITLE
Geth Start-Up Error

### ISSUE THREAD

**Issue by farhankhwaja** [ethereum/go-ethereum#15227]
#### System information

Geth version: Version: 1.7.0-stable
                       Git Commit: 6c6c7b2af3efdad4d2f64f70f3a724af434bbcd2
OS & Version: Linux (Ubuntu 16.04.3 LTS)
Commit hash : (if `develop`)

#### Expected behaviour
 Expected behavior is, the GETH should start syncing

#### Actual behaviour

It starts setting up the client for syncing but then fails. and gives me a [signal SIGSEV] error. Below are the logs

#### Steps to reproduce the behaviour
I ran the below command:

geth --testnet --cache=1024 --identity "FirstTestNode_gCloud" --rpc --rpcpo
rt "8545" --rpccorsdomain "*" --rpcapi "db,eth,net,web3,debug" --rpcaddr "<IP_Address>" --verbosity=3 --syncmode=fast

#### Backtrace

````
WARN [10-02|20:18:40] No etherbase set and no accounts found as default 
INFO [10-02|20:18:40] Starting peer-to-peer node               instance=Geth/FirstTestNode_gCloud/v1.7.0-stable-6c6c7b2a/linux-amd64/go1.9
INFO [10-02|20:18:40] Allocated cache and file handles         database=/home/farhank/.ethereum/testnet/geth/chaindata cache=1024 handles=1024
INFO [10-02|20:18:40] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Engine: ethash}"
INFO [10-02|20:18:40] Disk storage enabled for ethash caches   dir=/home/farhank/.ethereum/testnet/geth/ethash count=3
INFO [10-02|20:18:40] Disk storage enabled for ethash DAGs     dir=/home/farhank/.ethash                       count=2
INFO [10-02|20:18:40] Initialising Ethereum protocol           versions="[63 62]" network=3
INFO [10-02|20:18:40] Loaded most recent local header          number=0 hash=419410…ca4a2d td=1048576
INFO [10-02|20:18:40] Loaded most recent local full block      number=0 hash=419410…ca4a2d td=1048576
INFO [10-02|20:18:40] Loaded most recent local fast block      number=0 hash=419410…ca4a2d td=1048576
INFO [10-02|20:18:40] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-02|20:18:40] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-02|20:18:40] Starting P2P networking 
INFO [10-02|20:18:42] UDP listener up                          self=enode://cdc9bab2646c22b8b2625ba1f3af723c9a9b2e202fe08697a4ff6f9adeb47f242891631057efb15d7f8b40bcbd6221a0782efc269329f3ad16e9e6fa5878ab29@[::]:30303
INFO [10-02|20:18:42] IPC endpoint closed: /home/farhank/.ethereum/testnet/geth.ipc 
INFO [10-02|20:18:42] Blockchain manager stopped 
INFO [10-02|20:18:42] Stopping Ethereum protocol 
INFO [10-02|20:18:42] RLPx listener up                         self=enode://cdc9bab2646c22b8b2625ba1f3af723c9a9b2e202fe08697a4ff6f9adeb47f242891631057efb15d7f8b40bcbd6221a0782efc269329f3ad16e9e6fa5878ab29@[::]:30303
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb75640]

goroutine 79 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc4205f7e00)
        /build/ethereum-L88vJ9/ethereum-1.7.0+build10939+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:422 +0x330
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
        /build/ethereum-L88vJ9/ethereum-1.7.0+build10939+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:112 +0x104
````

**Comment by farhankhwaja** [comment]
After sometime, the above issue got resolved automatically, but then I started getting the below issue:
``````
Error starting protocol stack: listen tcp 35.185.208.38:8545: bind: cannot assign requested address
``````

I am trying to setup my client on Google Compute Engine as I have had bad experiences on AWS as the client used shutdown automatically.

**Comment by holiman** [comment]
Probably something already listening, or not your actual address? Try `netstat -nlp`, and `ifconfig`
