### ISSUE TITLE
Geth crashes with error unexpectedly

### ISSUE THREAD

**Issue by jatarga** [ethereum/go-ethereum#15334]
#### System information

> Version: 1.7.2-stable
> Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
> Architecture: amd64
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.9
> Operating System: linux
> GOPATH=
> GOROOT=/usr/lib/go-1.9
> 

#### Steps to reproduce the behaviour

`geth --rpc --rpcapi "personal,eth,web3" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --cache=1024`

#### Error

``` go
github.com/ethereum/go-ethereum/p2p.(*Server).run.func2.1(0x181ea60, 0xc462bc6e70, 0xc4200ba900, 0xc42bc5e300)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:493 +0x3b
created by github.com/ethereum/go-ethereum/p2p.(*Server).run.func2
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:493 +0x18d

goroutine 7272 [chan receive]:
github.com/ethereum/go-ethereum/p2p/discover.(*udp).ping(0xc4201d8cb0, 0x7be8359edfa72dca, 0xdc49c1f0604afbdc, 0xb038459fca75f8eb, 0xd97510a5f1918055, 0x73645606fc5ddbc3, 0xa314200f81a799a4, 0x552d27ebb662da8f, 0x87f60bd9c3a8ba20, 0xc49ed17a40, ...)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/udp.go:279 +0x267
github.com/ethereum/go-ethereum/p2p/discover.(*Table).ping(0xc4204d8900, 0x7be8359edfa72dca, 0xdc49c1f0604afbdc, 0xb038459fca75f8eb, 0xd97510a5f1918055, 0x73645606fc5ddbc3, 0xa314200f81a799a4, 0x552d27ebb662da8f, 0x87f60bd9c3a8ba20, 0xc49ed17a40, ...)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:533 +0xd3
github.com/ethereum/go-ethereum/p2p/discover.(*Table).pingpong(0xc4204d8900, 0xc4fded17a0, 0xe8359edfa72dca00, 0x49c1f0604afbdc7b, 0x38459fca75f8ebdc, 0x7510a5f1918055b0, 0x645606fc5ddbc3d9, 0x14200f81a799a473, 0x2d27ebb662da8fa3, 0xf60bd9c3a8ba2055, ...)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:513 +0xb5
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bond(0xc4204d8900, 0xe8359edfa72dca00, 0x49c1f0604afbdc7b, 0x38459fca75f8ebdc, 0x7510a5f1918055b0, 0x645606fc5ddbc3d9, 0x14200f81a799a473, 0x2d27ebb662da8fa3, 0xf60bd9c3a8ba2055, 0xd85a87, ...)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:485 +0x6b5
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall.func1(0xc4204d8900, 0xc4fb13b2c0, 0xc4fd922700)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:430 +0xdb
created by github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:429 +0x9a

goroutine 7146 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).handle(0xc451bd5e00, 0x14, 0x18d7e, 0x181dc60, 0xc49086a300, 0xbe7231b80b3cd2cb, 0x24bf5b0016, 0x190bda0, 0x0, 0x0)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:284 +0x176
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc451bd5e00, 0xc451bd5ec0)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:257 +0x188
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:189 +0xf2

goroutine 7081 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc481807860)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:235 +0x182
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:190 +0x117

```

**Comment by karalabe** [comment]
Please paste the head of the crash dump, that's where the actual crash is.
