### ISSUE TITLE
panic: Canonical hash not found

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15342]
Now that I was just mentioning the rinkeby node being so stable in (https://github.com/ethereum/go-ethereum/issues/15340) - also the Rinkeby node crashed:

```
INFO [10-20|07:17:33] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=664.952µs mgasps=0.000    number=1096061 hash=2fd7f3…e70665
INFO [10-20|07:17:33] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=1.091ms   mgasps=0.000    number=1096061 hash=0eeaef…53d11a
panic: Canonical hash not found

goroutine 1800641 [running]:
github.com/ethereum/go-ethereum/les.makeCht(0x1830020, 0xc42008e680, 0x0)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/server.go:382 +0x8f7
github.com/ethereum/go-ethereum/les.(*ProtocolManager).blockLoop.func1.1(0xc420710050, 0xc44074ab60, 0xc4201e1b00)
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/server.go:315 +0x4a
created by github.com/ethereum/go-ethereum/les.(*ProtocolManager).blockLoop.func1
        /build/ethereum-xqXRJH/ethereum-1.7.2+build11187+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/server.go:313 +0x1f5
```

Happens with version 1.7.2 

These are the parameters I started it with:

`geth --datadir=$HOME/.rinkeby --cache=1024 --syncmode=full --ethstats='WALLETH FCM push node:Respect my authoritah!@stats.rinkeby.io' --rinkeby -rpc --rpcaddr 127.0.0.1 --rpcport 9003 --lightserv 23`

Before this node was running for really long times with no crash at all. But I just recently added the "--lightserv 23' flag as I have the feeling to few Rinkeby nodes serve light-clients. And the trace indicates it might be a problem originating in this added flag.

**Comment by karalabe** [comment]
Yes, I've told @zsfelfoldi about this exact problem. He said it's solved in the LES/2 PR.
