### ISSUE TITLE
geth crashes with SIGBUS in ethash.(*cache).generate.func1() during fast-sync

### ISSUE THREAD

**Issue by cwajh** [ethereum/go-ethereum#15379]
This has happened to me twice. I completely cleared the DB and started over, only to encounter it again.

I suspect the bug is in block header validation somehow. When I run geth in a loop, I see "most recent local fast block" slowly advance, but "most recent local header" seems stuck at 3521652.

#### System information

Geth version: `1.7.2-stable`
OS & Version: Linux
Commit hash : 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9

#### Expected behaviour

geth should correctly handle received block info during sync, or at least not crash.

#### Actual behaviour

geth dies to a bus error.

#### Steps to reproduce the behaviour

1. Unpack the "Ethereum Wallet" package.
2. Run geth with fastsync params (`./geth --syncmode "fast" --cache 1024 console`)
3. Restart it from time to time if it gets stuck finding peers.
4. Wait.

#### Backtrace

````
goroutine 1844 [running]:
runtime.throw(0xf26f26, 0x5)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:605 +0x95 fp=0xc4238b4bb0 sp=0xc4238b4b90 pc=0x431f75
runtime.sigpanic()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/signal_unix.go:364 +0x29d fp=0xc4238b4c00 sp=0xc4238b4bb0 pc=0x44902d
github.com/ethereum/go-ethereum/consensus/ethash.memoryMap(0xc42b1b4d40, 0x3e, 0x2, 0x182e6a0, 0xc42b28b280, 0xc42b5ae440, 0x1a, 0xc428e34d80, 0x199, 0xfdcb18, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:76 +0xf8 fp=0xc4238b4c90 sp=0xc4238b4c00 pc=0x882658
github.com/ethereum/go-ethereum/consensus/ethash.(*cache).generate.func1()
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:186 +0x4a8 fp=0xc4238b4f30 sp=0xc4238b4c90 pc=0x8881c8
sync.(*Once).Do(0xc42a1843d8, 0xc421335f78)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/sync/once.go:44 +0xbe fp=0xc4238b4f68 sp=0xc4238b4f30 pc=0x47aa5e
github.com/ethereum/go-ethereum/consensus/ethash.(*cache).generate(0xc42a184380, 0xc420360810, 0x23, 0x3, 0xc42abd2d00)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:160 +0x96 fp=0xc4238b4fb8 sp=0xc4238b4f68 pc=0x8831f6
runtime.goexit()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4238b4fc0 sp=0xc4238b4fb8 pc=0x4634e1
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).cache
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:484 +0x6fc
````

Full log of the sync attempt can be inspected [here](http://www.rodl16.com/_tmp_sync.log)

**Comment by cwajh** [comment]
...I'm using a kind of unusual FUSE filesystem. It occurs to me that memoryMapFile might be failing somehow because of that. I'm gonna double check that.

**Comment by cwajh** [comment]
Okay, I can definitely mmap files on this FS in general.

```
Python 2.7.10 (default, Feb 15 2016, 15:13:16) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmap
>>> qq = open('_tmp.lst','rb')
>>> q = mmap.mmap(qq.fileno(),0,mmap.MAP_SHARED,mmap.PROT_READ)
>>> q[2:4]
'23'
```

Looking back in the log, the original trigger seems to be a crash with this error message:

```
CRIT [10-25|10:16:44] Failed to store header                   err="open /home/garnett/.ethereum/geth/chaindata/018669.ldb: too many open files"
```

I'm guessing this leaves the cache file in an inconsistent state, thus dooming subsequent launches.

I'll try to work around and report back.

**Comment by cwajh** [comment]
Removed most recent cache file and seem to be making progress again.

I don't know Go, so I'm not sure I should be the one to write a patch. But shouldn't this be prevented by a check in [the cache mmap code](https://github.com/ethereum/go-ethereum/blob/0095531a58772b1f5bd1547169790dbde84ec78a/consensus/ethash/ethash.go#L75) that the file is big enough?

**Comment by karalabe** [comment]
Oh, sweet, I've seen this error a few times but never could figure out where it originates from. I'm still unsure if the crash is due to the file size or not, but that buffer there should definitely be checked to make sure it's large enough!
