### ISSUE TITLE
[iOS] - account import out of memory crash

### ISSUE THREAD

**Issue by lprokein** [ethereum/go-ethereum#15523]
Geth version: `Geth (1.7.2)`
OS & Version: iOS 11.1.2

#### Bug description
When I call `.importKey(keyJSON, passphrase:, newPassphrase:)` first time with wrong import password it throws error as expected.

But when I call it for the second time (good or wrong password) it crash with `out of memory` error.

#### Backtrace

````
2017-11-19 15:19:56.749679+0100 trustair[808:138147] [Common] _BSMachError: port a913; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
runtime: out of memory: cannot allocate 268435456-byte block (272072704 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x100f37e2a, 0xd)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/panic.go:605 +0x70
runtime.largeAlloc(0x10000000, 0x100660101, 0x104b006c8)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/malloc.go:829 +0xec
runtime.mallocgc.func1()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/malloc.go:722 +0x3c
runtime.systemstack(0x0)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/asm_arm64.s:241 +0x8c
runtime.mstart()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/proc.go:1125

goroutine 17 [running, locked to thread]:
runtime.systemstack_switch()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/asm_arm64.s:190 +0x8 fp=0x10b41f690 sp=0x10b41f680 pc=0x100664160
runtime.mallocgc(0x10000000, 0x100de7700, 0x10b3ee401, 0x10b6e2800)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/malloc.go:721 +0x66c fp=0x10b41f750 sp=0x10b41f690 pc=0x100622244
runtime.makeslice(0x100de7700, 0x4000000, 0x4000000, 0x10b6e2800, 0x200, 0x200)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/slice.go:54 +0x74 fp=0x10b41f780 sp=0x10b41f750 pc=0x100650b8c
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0x10b3ea3e0, 0x2, 0x8, 0x10b3e81a0, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:235 +0xd0 fp=0x10b41f840 sp=0x10b41f780 pc=0x10080b068
github.com/ethereum/go-ethereum/accounts/keystore.getKDFKey(0x10b3ea360, 0xb, 0x10b3ee280, 0x40, 0x10b3e8140, 0x20, 0x10b3ea348, 0x6, 0x10b4489c0, 0x10b3ee340, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:282 +0x5a8 fp=0x10b41f950 sp=0x10b41f840 pc=0x100813c90
github.com/ethereum/go-ethereum/accounts/keystore.decryptKeyV3(0x10b6ba080, 0x10b3ea09c, 0x2, 0x100dbcec0, 0x10b6ba080, 0x0, 0x0, 0x0, 0x0, 0x100621a40, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:219 +0x21c fp=0x10b41fab0 sp=0x10b41f950 pc=0x100812fc4
github.com/ethereum/go-ethereum/accounts/keystore.DecryptKey(0x10b44c000, 0x1eb, 0x1eb, 0x10b3ea09c, 0x2, 0x104b05268, 0x100e18301, 0x10063a3f0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:179 +0x174 fp=0x10b41fb70 sp=0x10b41fab0 pc=0x100812b5c
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).Import(0x10b626000, 0x10b44c000, 0x1eb, 0x1eb, 0x10b3ea09c, 0x2, 0x10b3ea09e, 0x2, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:437 +0x64 fp=0x10b41fc70 sp=0x10b41fb70 pc=0x1008117dc
github.com/ethereum/go-ethereum/mobile.(*KeyStore).ImportKey(0x10b6c0048, 0x104c073e0, 0x1eb, 0x1eb, 0x10b3ea09c, 0x2, 0x10b3ea09e, 0x2, 0x1, 0x100617400, ...)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/mobile/accounts.go:193 +0x80 fp=0x10b41fd90 sp=0x10b41fc70 pc=0x100c872e8
_/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/gomobile-work-186187889/src/gomobile_bind.proxygeth_KeyStore_ImportKey(0x1ffffffe8, 0x104c073e0, 0x1eb, 0x1c4009f80, 0x2, 0x1c400a1e0, 0x2, 0x1006645fc)
	/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/gomobile-work-186187889/src/gomobile_bind/go_gethmain.go:2857 +0xf4 fp=0x10b41fe40 sp=0x10b41fd90 pc=0x100cb506c
_/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/gomobile-work-186187889/src/gomobile_bind._cgoexpwrap_bee124c4ec16_proxygeth_KeyStore_ImportKey(0xffffffe8, 0x104c073e0, 0x1eb, 0x1c4009f80, 0x2, 0x1c400a1e0, 0x2, 0x1c400a1e0)
	_/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/gomobile-work-186187889/src/gomobile_bind/_obj/_cgo_gotypes.go:3285 +0x50 fp=0x10b41fe90 sp=0x10b41fe40 pc=0x100c9fe38
runtime.call64(0x0, 0x16f854aa8, 0x16f854bd8)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/asm_arm64.s:413 +0x70 fp=0x10b41fee0 sp=0x10b41fe90 pc=0x100664688
runtime.cgocallbackg1(0x0)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/cgocall.go:305 +0x140 fp=0x10b41ff60 sp=0x10b41fee0 pc=0x100614868
runtime.cgocallbackg(0x0)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/cgocall.go:187 +0x70 fp=0x10b41ffc0 sp=0x10b41ff60 pc=0x100614698
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x10b424000)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/asm_arm64.s:643 +0x90 fp=0x10b41ffe0 sp=0x10b41ffc0 pc=0x1006660e8
runtime.goexit()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/asm_arm64.s:931 +0x4 fp=0x10b41ffe0 sp=0x10b41ffe0 pc=0x10066648c

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x1016a9a40)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/meter.go:221 +0x24
created by github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics.NewMeter
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/meter.go:40 +0x114

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/sigqueue.go:131 +0xc8
os/signal.loop()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.0
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/os/signal/signal_unix.go:28 +0x30

goroutine 9 [select, locked to thread]:
runtime.gopark(0x101020528, 0x0, 0x100f2d548, 0x6, 0x18, 0x1)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/proc.go:277 +0xe8
runtime.selectgo(0x10b413f50, 0x10b3e5aa0)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/select.go:395 +0xcd4
runtime.ensureSigM.func1()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/signal_unix.go:511 +0x1c0
runtime.goexit()
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/asm_arm64.s:931 +0x4
````

**Comment by ligi** [comment]
Are you using Geth.LightScryptN and Geth.LightScryptP?

**Comment by lprokein** [comment]
Yes

**Comment by ligi** [comment]
OK then it must be something different - just looked you might have had the same as this dev: https://github.com/ethereum/go-ethereum/issues/14459

**Comment by karalabe** [comment]
You were trying to decrypt a key that used the standard encryption parameters (needs 256MB of memory for decoding). That's way too heavy for a mobile (or might explain your limits).

```
runtime: out of memory: cannot allocate 268435456-byte block
```

Please make sure that any keys decrypted on a mobile have originally been encrypted with Light KDF flags.
