### ISSUE TITLE
geth wallet import runtime error

### ISSUE THREAD

**Issue by gtcode** [ethereum/go-ethereum#15668]
#### System information

Geth version: `1.7.3-stable`
OS & Version: macOS 10.12.16

#### Steps to reproduce the behaviour
1) Export wallet https://ethtools.com/ropsten/wallet/load/
2) Run command and get result:
````
$ geth wallet import /Path/To/Downloaded.json
WARN [12-13|13:01:11] No etherbase set and no accounts found as default 
Passphrase: 
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/ethereum/go-ethereum/accounts/keystore.decryptPreSaleKey(0xc420216400, 0x1f2, 0x3f2, 0xc4204e9150, 0x8, 0x0, 0x80487414, 0xc4201ccbe0)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/presale.go:61 +0x640
github.com/ethereum/go-ethereum/accounts/keystore.importPreSaleKey(0x5210a60, 0xc4202362a0, 0xc420216400, 0x1f2, 0x3f2, 0xc4204e9150, 0x8, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/presale.go:36 +0xa2
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).ImportPreSaleKey(0xc4200dc000, 0xc420216400, 0x1f2, 0x3f2, 0xc4204e9150, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:478 +0xe6
main.importWallet(0xc420204c60, 0x4b3942e, 0x8)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go:352 +0x28a
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc420204c60, 0x0, 0xc420204c60)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1213 +0x103
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x49be420, 0xc4204ea290, 0xc420204c60, 0xc4204f6500, 0x0)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x4b36591, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4b7659f, 0x1e, 0x0, ...)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa95
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc420226340, 0xc420204840, 0x0, 0x0)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0xa7b
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0x4b36e0d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4b78297, 0x1f, 0x0, ...)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x944
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x4b36e0d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4b78297, 0x1f, 0x0, ...)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x1319
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420226000, 0xc420010140, 0x4, 0x4, 0x0, 0x0)
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6f8
main.main()
	/private/tmp/ethereum-20171209-6979-quau6x/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:204 +0x55
````

**Comment by gtcode** [comment]
````
Jim McDonald @mcdee 13:17
That's a keystore then not a wallet. You can just copy the file to the relevant location rather than import it
Should be ~/Library/Ethereum/keystore
````

I misused the command, but geth is throwing slicing out of bounds error.

**Comment by karalabe** [comment]
Ah yeah, the `wallet` command is only relevant for importing pre-sale wallets. We don't much touch that part of the code since it a) it kind of works for it's very limited use case b) it doens't have any practical use case since the pre-sale.

If anyone wants to pick this up and fix the ugly crash though, I'd be happy to review it.
