### ISSUE TITLE
Two separate main-net Geth nodes (v1.8.0-unstable-c6069a62) crashed on the same block number

### ISSUE THREAD

**Issue by infamousrev** [ethereum/go-ethereum#15711]
Two Geth nodes running on two completely independent servers with plenty of memory and other system resources crashed while processing the exact same block number with the exact same error, leading me to believe it may be caused by a reproducible bug in the software.

 Server1:
````
INFO [12-19|22:20:49] Imported new chain segment               blocks=1 txs=305  mgas=7.985  elapsed=2.510s    mgasps=3.181  number=4762226 hash=23e774…a28e8e
INFO [12-19|22:20:57] Imported new chain segment               blocks=1 txs=112  mgas=7.996  elapsed=498.418ms mgasps=16.042 number=4762227 hash=db6bf0…27d0a5
INFO [12-19|22:21:01] Imported new chain segment               blocks=1 txs=245  mgas=7.992  elapsed=2.146s    mgasps=3.724  number=4762227 hash=b2814d…f45cc6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8c80db]



goroutine 14809 [running]:
github.com/ethereum/go-ethereum/core.(*TxPool).Status(0xc420211dc0, 0xc4587cb220, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:841 +0x29b
github.com/ethereum/go-ethereum/les.(*ProtocolManager).txStatus(0xc4220e2000, 0xc4587cb220, 0x1, 0x1, 0xc4479fa110, 0x1, 0x1)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1111 +0xb6
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handleMsg(0xc4220e2000, 0xc4201de480, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1020 +0x82a6
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle(0xc4220e2000, 0xc4201de480, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:315 +0x72f
github.com/ethereum/go-ethereum/les.NewProtocolManager.func1(0xc4353b4cc0, 0x1850ba0, 0xc42f308150, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:175 +0x252
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc42f308150, 0xc4353b4cc0, 0x1850ba0, 0xc42f308150)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:349 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x228
````

Server2:
````
INFO [12-19|22:20:43] Imported new chain segment               blocks=1 txs=271  mgas=7.989  elapsed=3.142s    mgasps=2.542  number=4762225 hash=c027ca…f9d46e
INFO [12-19|22:20:50] Imported new chain segment               blocks=1 txs=305  mgas=7.985  elapsed=2.785s    mgasps=2.866  number=4762226 hash=23e774…a28e8e
INFO [12-19|22:20:56] Imported new chain segment               blocks=1 txs=112  mgas=7.996  elapsed=588.105ms mgasps=13.596 number=4762227 hash=db6bf0…27d0a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8c80cb]


goroutine 11021853 [running]:
github.com/ethereum/go-ethereum/core.(*TxPool).Status(0xc42020bdc0, 0xc445ab38e0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:841 +0x29b
github.com/ethereum/go-ethereum/les.(*ProtocolManager).txStatus(0xc4202b4ee0, 0xc445ab38e0, 0x1, 0x1, 0xc42bd004a0, 0x1, 0x1)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1111 +0xb6
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handleMsg(0xc4202b4ee0, 0xc4354d6180, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1020 +0x82a6
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle(0xc4202b4ee0, 0xc4354d6180, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:315 +0x72f
github.com/ethereum/go-ethereum/les.NewProtocolManager.func1(0xc456c6dda0, 0x184fba0, 0xc422a53260, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:175 +0x252
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc422a53260, 0xc456c6dda0, 0x184fba0, 0xc422a53260)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:349 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x228
````

OS: 
Linux Centos 7.3 running: docker run -ti -p 30303:30303 docker.io/ethereum/client-go --maxpeers 150 --lightserv 90 --lightpeers 150

It seems hash=db6bf0…27d0a5 was the block that caused the crash, two other servers running the same software and hardware did not crash, so it is likely a bug that gets triggered only with a certain probability.

**Comment by infamousrev** [comment]
Update: Another node crashed with the same error, but this time only one node crashed:

````
INFO [12-20|03:25:03] Imported new chain segment               blocks=1  txs=173  mgas=7.994  elapsed=1.160s    mgasps=6.887  number=4763367 hash=1426a3…ff4f75
INFO [12-20|03:25:09] Imported new chain segment               blocks=1  txs=44   mgas=1.133  elapsed=657.926ms mgasps=1.722  number=4763368 hash=80d9e5…83685d
INFO [12-20|03:25:16] Imported new chain segment               blocks=1  txs=14   mgas=0.335  elapsed=90.226ms  mgasps=3.718  number=4763369 hash=2131f2…3066b1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8c80db]

goroutine 31290856 [running]:
github.com/ethereum/go-ethereum/core.(*TxPool).Status(0xc4201fddc0, 0xc4a75475e0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:841 +0x29b
github.com/ethereum/go-ethereum/les.(*ProtocolManager).txStatus(0xc4202a6ee0, 0xc4a75475e0, 0x1, 0x1, 0xc42e6a72c0, 0x1, 0x1)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1111 +0xb6
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handleMsg(0xc4202a6ee0, 0xc486480e40, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1020 +0x82a6
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle(0xc4202a6ee0, 0xc486480e40, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:315 +0x72f
github.com/ethereum/go-ethereum/les.NewProtocolManager.func1(0xc4408f8120, 0x1850ba0, 0xc494d41c00, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:175 +0x252
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc494d41c00, 0xc4408f8120, 0x1850ba0, 0xc494d41c00)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:349 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x228
````

**Comment by Marco8** [comment]
Hi!

Happens the same in my private network. The node that crashes is the node serving light clients (--lightserv 20) if I remove that parameter it doesn't crash. It crashes sometimes when the light client connected to it sends a tx.

Any fix?

**Comment by karalabe** [comment]
Thanks for this! It's indeed a bug in the txpool used only by the light client. I've opened a PR, will probably be merged today into master.
