### ISSUE TITLE
Exceptions & Hang

### ISSUE THREAD

**Issue by niclash** [ethereum/go-ethereum#15765]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: Whatever version comes in Ethereum Wallet 0.9.3
OS & Version: Linux Debian stable
Commit hash : (if `develop`)

#### Expected behaviour
That the Wallet manage to re-establish its sync.

#### Actual behaviour
Crash

#### Steps to reproduce the behaviour
I had a fully sync'd Wallet two days ago. Then I turned it off for a day, because I needed the RAM for other use, and since then I can not get it to sync again.

On my computer, 20 times in a row; start, wait 1 - 90 minutes and stack trace follows and nothing happens.

I ran with --loglevel=trace, to get more output of what is going on.

And the output quickly fills the console buffer (I have 5000 lines), but I notice that the number of peers goes up and down a lot. Personally I suspect that there is a condition somewhere where a disconnecting peer causes a poor state in this node. And since a lot of recommendations online about recovering from "hanged" is to restart. So if people keep restarting and restarting, we all induce more and more problems with others. Only if one is "lucky" to get hold of fully operational and stable peers, then the sync manages to get through.

My friend is having the same kind of problems, and eventually gave up after 2 weeks (I am more persistent), but he has similar problems with "parity". Are the problems at a deeper Ethereum protocol level, and it is all built on sand? Of course you will all deny that possibility, but I haven't seen anything this shaky since the introduction of TCP/IP over leased lines in the late 1980s. And since I am in the process of building a company on top of EVM, I am not convinced at all that this is useful, and that the situation is pushing people to (effectively) insecure, online wallets.

I am willing to help out in any way I can, to help resolve this, because IMHO, nothing can be more crucial at the moment than to get stability of the user experience to a reasonable level. 

OTOH, seeing how many "Issues" there is here, I am not that hopeful that anyone bothers with users, and that this report will be collecting dust, long after I have either figured it out on my own, or moved on to better technologies in this space.

#### Backtrace
````
[2017-12-27 23:58:31.471] [TRACE] Sockets/node-ipc - Write data {"jsonrpc":"2.0","id":"e4ae1426-b61f-4968-9434-24073c6e6d2d","method":"eth_syncing","params":[]}
[2017-12-27 23:58:31.471] [ERROR] Sockets/node-ipc - { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:305:12)
    at Web3IpcSocket.write (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:181:22)
    at Q.try (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:55:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/method.js:39:29)
    at Web3IpcSocket.send (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:29:21)
    at EthereumNode.send (/opt/Ethereum Wallet/resources/app.asar/modules/ethereumNode.js:242:29)
    at _.delay (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:113:26)
    at Timeout._onTimeout (/opt/Ethereum Wallet/resources/app.asar/node_modules/underscore/underscore.js:768:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
[2017-12-27 23:58:31.476] [ERROR] NodeSync - Node crashed while syncing? { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:305:12)
    at Web3IpcSocket.write (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:181:22)
    at Q.try (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:55:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/method.js:39:29)
    at Web3IpcSocket.send (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:29:21)
    at EthereumNode.send (/opt/Ethereum Wallet/resources/app.asar/modules/ethereumNode.js:242:29)
    at _.delay (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:113:26)
    at Timeout._onTimeout (/opt/Ethereum Wallet/resources/app.asar/node_modules/underscore/underscore.js:768:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
[2017-12-27 23:58:31.476] [ERROR] NodeSync - Sync error { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:305:12)
    at Web3IpcSocket.write (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:181:22)
    at Q.try (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:55:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/method.js:39:29)
    at Web3IpcSocket.send (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:29:21)
    at EthereumNode.send (/opt/Ethereum Wallet/resources/app.asar/modules/ethereumNode.js:242:29)
    at _.delay (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:113:26)
    at Timeout._onTimeout (/opt/Ethereum Wallet/resources/app.asar/node_modules/underscore/underscore.js:768:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
[2017-12-27 23:58:31.477] [ERROR] main - Error syncing node { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:305:12)
    at Web3IpcSocket.write (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:181:22)
    at Q.try (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:55:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/method.js:39:29)
    at Web3IpcSocket.send (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:29:21)
    at EthereumNode.send (/opt/Ethereum Wallet/resources/app.asar/modules/ethereumNode.js:242:29)
    at _.delay (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:113:26)
    at Timeout._onTimeout (/opt/Ethereum Wallet/resources/app.asar/node_modules/underscore/underscore.js:768:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
[2017-12-27 23:58:31.478] [INFO] NodeSync - Sync loop ended
[2017-12-27 23:58:31.478] [ERROR] main - Error starting up node and/or syncing { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:305:12)
    at Web3IpcSocket.write (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/base.js:181:22)
    at Q.try (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:55:18)
    at tryCatcher (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Ethereum Wallet/resources/app.asar/node_modules/bluebird/js/release/method.js:39:29)
    at Web3IpcSocket.send (/opt/Ethereum Wallet/resources/app.asar/modules/sockets/web3Base.js:29:21)
    at EthereumNode.send (/opt/Ethereum Wallet/resources/app.asar/modules/ethereumNode.js:242:29)
    at _.delay (/opt/Ethereum Wallet/resources/app.asar/modules/nodeSync.js:113:26)
    at Timeout._onTimeout (/opt/Ethereum Wallet/resources/app.asar/node_modules/underscore/underscore.js:768:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
````

**Comment by niclash** [comment]
I just want to add the lovely news that I now found the reason why it will never recover. LevelDB is now corrupted. I am pretty sure that error message wasn't there in the initial failures.

````

[2017-12-28 00:08:13.729] [TRACE] EthereumNode - GETH: CRIT [12-28|00:08:13] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"
[2017-12-28 00:08:13.729] [TRACE] Windows - Broadcast { '0': 'uiAction_nodeLogText',
  '1': ' Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"' }
[2017-12-28 00:08:13.729] [TRACE] Windows/loading - Sending data { '0': 'uiAction_nodeLogText',
  '1': ' Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"' }
[2017-12-28 00:08:13.730] [TRACE] Windows/splash - Sending data { '0': 'uiAction_nodeLogText',
  '1': ' Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"' }
[2017-12-28 00:08:13.730] [TRACE] EthereumNode - GETH: CRIT [12-28|00:08:13] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"
[2017-12-28 00:08:13.730] [TRACE] Windows - Broadcast { '0': 'uiAction_nodeLogText',
  '1': ' Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"' }
[2017-12-28 00:08:13.730] [TRACE] Windows/loading - Sending data { '0': 'uiAction_nodeLogText',
  '1': ' Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=136743): checksum mismatch, want=0xc1056df2 got=0x8f0bb064 [file=475260.ldb]"' }
````

And when trying to repair the LevelDB with node tool "level-repair", I get the fantastic news of

````
niclas@devdesk:~/.ethereum/geth/chaindata$ level-repair
node: ../deps/leveldb/leveldb-1.20/db/dbformat.h:99: leveldb::Slice leveldb::ExtractUserKey(const leveldb::Slice&): Assertion `internal_key.size() >= 8' failed.
Aborted
````

which to me sounds like; "Delete all and start over".  Seriously guys??

**Comment by fjl** [comment]
I'm not sure C++ leveldb tools will work on the our database because the implementation we use might be incompatible.

**Comment by fjl** [comment]
The corruption issue is tracked in #2289

**Comment by niclash** [comment]
First of all, thanks for not reading very carefully.
I am pretty sure that the LevelDB corruption is a consequence of my dozens of restarts and not because of the underlying problem. I am pretty sure it wasn't there early on. And EVEN IF it was the cause (it ran 5-6 hours before the first of this series of crashes), then having a data corruption issue open for nearly 2 YEARS, is simply unacceptable. 

Secondly, in aggregate, I have ended up in this situation (non-sync'd wallet) in 5 out of 5 times in the last 4 weeks. On 3 of those occasions, I managed to get it to a sync'd state for a while. But soon enough, it gets out of sync. That is abysmal odds for a consumer application, especially considering it is supposed to handle financially relevant assets (not tweets, nor photos, nor messages).

**Comment by niclash** [comment]
I ran the following snippet of code;

````
	opts := &goleveldbOpt.Options{}
	opts.ErrorIfMissing = true
	opts.ForceRebuild = true
	opts.DropTableOnRebuildError = true

	db, err := goleveldb.RecoverFile(DB_PATH, opts)
````
from https://github.com/rchunping/leveldb-tools/blob/master/main.go and that overcame the corruption complaint in Ethereum Wallet. Also, it only took sub-second to execute, so one could wonder if it shouldn't be built in to Ethereum Wallet.
