### ISSUE TITLE
Panic in 1.7.3: runtime error: index out of range: syndtr/goleveldb/leveldb/memdb. (*DB).findGE

### ISSUE THREAD

**Issue by blair** [ethereum/go-ethereum#15865]
A new build from source on the 1.7.3 tag on Ubuntu 17.10 using the git branch and setting up a new node with

```
$ "${HOME}/go-ethereum.git/build/bin/geth" \
  --verbosity 4 \
  --syncmode full \
  --cache 4096 \
  --datadir "${HOME}/geth-data"
```

```
$ "${HOME}/go-ethereum.git/build/bin/geth" version
Geth
Version: 1.7.3-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8
```

Got this panic after 2 to 3 hours:

```
DEBUG[01-11|23:22:43] Inserted new block                       number=1437941 hash=389e63…242046 uncles=0 txs=6    gas=181035  elapsed=6.551ms
DEBUG[01-11|23:22:43] Trie cache stats after commit            misses=21212779 unloads=3330615
DEBUG[01-11|23:22:43] Inserted new block                       number=1437942 hash=5c7b75…64eb6c uncles=0 txs=9    gas=206669  elapsed=6.504ms
DEBUG[01-11|23:22:43] Trie cache stats after commit            misses=21212810 unloads=3330623
DEBUG[01-11|23:22:43] Inserted new block                       number=1437943 hash=0bcd43…ff3935 uncles=0 txs=3    gas=86091   elapsed=3.244ms
DEBUG[01-11|23:22:43] Trie cache stats after commit            misses=21213149 unloads=3330639
DEBUG[01-11|23:22:43] Inserted new block                       number=1437944 hash=1f87c0…5d5f19 uncles=0 txs=99   gas=2102091 elapsed=83.434ms
DEBUG[01-11|23:22:43] VM returned with error                   err="out of gas"
DEBUG[01-11|23:22:43] Trie cache stats after commit            misses=21213805 unloads=3330650
panic: runtime error: index out of range

goroutine 99392 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.(*DB).findGE(0xc46dc907e0, 0xc587f793c0, 0x29, 0x33, 0x2d01, 0x499e9, 0x2d00)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:218 +0x19a
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put(0xc46dc907e0, 0xc587f793c0, 0x29, 0x33, 0xc580bf530e, 0x27, 0x4f545, 0x0, 0x0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:281 +0xda
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*Batch).putMem(0xc4c1cf7340, 0x3c717d1, 0xc46dc907e0, 0x1, 0x3c717d1)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/batch.go:219 +0x257
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).writeLocked(0xc420242000, 0xc4c1cf7340, 0x0, 0xc5a5220001, 0x0, 0x0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:226 +0x4db
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).Write(0xc420242000, 0xc4c1cf7340, 0x0, 0x0, 0x0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:305 +0x2a8
github.com/ethereum/go-ethereum/ethdb.(*ldbBatch).Write(0xc58a7c6e80, 0xc4201bc5b0, 0x15f0f9)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/ethdb/database.go:295 +0x40
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlockAndState(0xc420244000, 0xc4c4ef7950, 0xc43f5a8000, 0xde, 0x100, 0xc5ac4b4690, 0x101, 0x0, 0x0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:845 +0x7f5
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc420244000, 0xc5af968000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:983 +0x145e
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc420244000, 0xc5af968000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:864 +0x67
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc42024c1a0, 0xc42cec0000, 0x1000, 0x1000, 0x0, 0x0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1359 +0x607
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc42024c1a0, 0xc420480f90, 0xc588f6b240)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1334 +0x7f
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).(github.com/ethereum/go-ethereum/eth/downloader.processFullSyncContent)-fm(0x400e9e400000008, 0x10371d8)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:482 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc588c954f0, 0xc59ca6a9c0, 0xc588c954e0)
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:500 +0x51
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/miner-ethereum/go-ethereum.git/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:500 +0xd2
```

**Comment by klim0v** [comment]
I caught the same

```
E[2022-01-24|14:07:51.640] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: slice bounds out of range [:85960316395] with capacity 268435456" stack="goroutine 628 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/consensus/state.go:726 +0x4c\npanic({0x1301f00, 0xc05b8ca168})\n\t/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1038 +0x215\ngithub.com/syndtr/goleveldb/leveldb/memdb.(*DB).findGE(0xc000985c00, {0xc06487ea20, 0x29, 0x29}, 0x1)\n\t/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/memdb/memdb.go:219 +0x19f\ngithub.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put(0xc000985c00, {0xc06487ea20, 0x53196f, 0x29}, {0xc01d49a3c4, 0x6b, 0x19cf00de9})\n\t/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/memdb/memdb.go:281 +0xf8\ngithub.com/syndtr/goleveldb/leveldb.(*Batch).putMem(0xc01b6e7e00, 0x19cf00d5c, 0x1)\n\t/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/batch.go:219 +0x239\ngithub.com/syndtr/goleveldb/leveldb.(*DB).writeLocked(0xc000271a40, 0xc01b6e7e00, 0x0, 0x1, 0x0)\n\t/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_write.go:238 +0x350\ngithub.com/syndtr/goleveldb/leveldb.(*DB).Write(0xc000271a40, 0xc01b6e7e00, 0xc0559ff3e0)\n\t/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_write.go:317 +0x4eb\ngithub.com/tendermint/tm-db.(*goLevelDBBatch).write(0xc047108080, 0x0)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tm-db@v0.6.6/goleveldb_batch.go:63 +0x52\ngithub.com/tendermint/tm-db.(*goLevelDBBatch).Write(0x0)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tm-db@v0.6.6/goleveldb_batch.go:51 +0x1b\ngithub.com/cosmos/iavl.(*nodeDB).Commit(0xc000483500)\n\t/home/runner/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/nodedb.go:554 +0xa2\ngithub.com/cosmos/iavl.(*MutableTree).SaveVersion(0xc001040910)\n\t/home/runner/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/mutable_tree.go:546 +0x2c5\ngithub.com/MinterTeam/minter-go-node/tree.(*mutableTree).Commit(0xc00018f720, {0xc01d2095c0, 0xc, 0xc064529a40})\n\t/home/runner/work/minter-go-node/minter-go-node/tree/tree.go:46 +0xf5\ngithub.com/MinterTeam/minter-go-node/coreV2/state.(*State).Commit(0xc0001b4b60)\n\t/home/runner/work/minter-go-node/minter-go-node/coreV2/state/state.go:189 +0x25c\ngithub.com/MinterTeam/minter-go-node/coreV2/minter.(*Blockchain).Commit(0xc000332000)\n\t/home/runner/work/minter-go-node/minter-go-node/coreV2/minter/blockchain.go:575 +0x13c\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc052762c00)\n\t/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/abci/client/local_client.go:264 +0xb6\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)\n\t/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/proxy/app_conn.go:93 +0x22\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc057286e20, 0x10}, 0x3207c3, 0x84e63d, {{0xc06fcaf140, ...}, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/state/execution.go:228 +0x269\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc057286e20, 0x10}, 0x3207c3, 0x84e63d, {{0xc06fcaf140, ...}, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/state/execution.go:180 +0x6ee\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc00037f500, 0x84e63d)\n\t/home/runner/go/pkg/mod/github.com/!minter!team/tendermin
```

After restart:
`panic: can't get node 32AAE9D4B3227A9638F99BC73473C360A93D9AF73DBA6B196ABC5F56A7017EDE: leveldb/table: corruption on data-block (pos=391295): checksum mismatch, want=0x23c63648 got=0x5361b24d [file=421702.ldb]`

**Comment by holiman** [comment]
Reformatting:
```
E[2022-01-24|14:07:51.640] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: slice bounds out of range [:85960316395] with capacity 268435456" stack="goroutine 628 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
	/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/consensus/state.go:726 +0x4c
panic({0x1301f00, 0xc05b8ca168})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1038 +0x215
github.com/syndtr/goleveldb/leveldb/memdb.(*DB).findGE(0xc000985c00, {0xc06487ea20, 0x29, 0x29}, 0x1)
	/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/memdb/memdb.go:219 +0x19f
github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put(0xc000985c00, {0xc06487ea20, 0x53196f, 0x29}, {0xc01d49a3c4, 0x6b, 0x19cf00de9})
	/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/memdb/memdb.go:281 +0xf8
github.com/syndtr/goleveldb/leveldb.(*Batch).putMem(0xc01b6e7e00, 0x19cf00d5c, 0x1)
	/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/batch.go:219 +0x239
github.com/syndtr/goleveldb/leveldb.(*DB).writeLocked(0xc000271a40, 0xc01b6e7e00, 0x0, 0x1, 0x0)
	/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_write.go:238 +0x350
github.com/syndtr/goleveldb/leveldb.(*DB).Write(0xc000271a40, 0xc01b6e7e00, 0xc0559ff3e0)
	/home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_write.go:317 +0x4eb
github.com/tendermint/tm-db.(*goLevelDBBatch).write(0xc047108080, 0x0)
	/home/runner/go/pkg/mod/github.com/tendermint/tm-db@v0.6.6/goleveldb_batch.go:63 +0x52
github.com/tendermint/tm-db.(*goLevelDBBatch).Write(0x0)
	/home/runner/go/pkg/mod/github.com/tendermint/tm-db@v0.6.6/goleveldb_batch.go:51 +0x1b
github.com/cosmos/iavl.(*nodeDB).Commit(0xc000483500)
	/home/runner/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/nodedb.go:554 +0xa2
github.com/cosmos/iavl.(*MutableTree).SaveVersion(0xc001040910)
	/home/runner/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/mutable_tree.go:546 +0x2c5
github.com/MinterTeam/minter-go-node/tree.(*mutableTree).Commit(0xc00018f720, {0xc01d2095c0, 0xc, 0xc064529a40})
	/home/runner/work/minter-go-node/minter-go-node/tree/tree.go:46 +0xf5
github.com/MinterTeam/minter-go-node/coreV2/state.(*State).Commit(0xc0001b4b60)
	/home/runner/work/minter-go-node/minter-go-node/coreV2/state/state.go:189 +0x25c
github.com/MinterTeam/minter-go-node/coreV2/minter.(*Blockchain).Commit(0xc000332000)
	/home/runner/work/minter-go-node/minter-go-node/coreV2/minter/blockchain.go:575 +0x13c
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc052762c00)
	/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/abci/client/local_client.go:264 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)
	/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc057286e20, 0x10}, 0x3207c3, 0x84e63d, {{0xc06fcaf140, ...}, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc057286e20, 0x10}, 0x3207c3, 0x84e63d, {{0xc06fcaf140, ...}, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/!minter!team/tendermint@v0.34.11-0.20211217161414-dda5434727d3/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc00037f500, 0x84e63d)
	/home/runner/go/pkg/mod/github.com/!minter!team/tendermin
```
