### ISSUE TITLE
Error with the log files

### ISSUE THREAD

**Issue by RobbieArmz** [ethereum/go-ethereum#15923]
Hi, currently I've been having this random crash on my get during my mining sessions, how can I fix this? Its hindering my work.

```
F0118 12:00:02.430386 logger/glog/glog.go:1225] remove C:\Users\Pessoal\AppData\Roaming\EthereumClassic\mainnet\log\geth.Pessoal-PC.Pessoal-PC_Pessoal.log.INFO.20180118-120002.7112: File is being used by another process.
goroutine 5899 [running]:
github.com/ethereumproject/go-ethereum/logger/glog.stacks(0xc0420a2100, 0xc057406960, 0xea, 0x1dc)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1053 +0xd6
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).output(0x17a71c0, 0xc000000003, 0xc05a00aa50, 0x13e2282, 0x13, 0x4c9, 0x0)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1004 +0x32e
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).printDepth(0x17a71c0, 0xc000000003, 0x1, 0xc04bb87f48, 0x1, 0x1)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:933 +0x131
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).print(0x17a71c0, 0x3, 0xc04bb87f48, 0x1, 0x1)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:924 +0x61
github.com/ethereumproject/go-ethereum/logger/glog.Fatal(0xc04bb87f48, 0x1, 0x1)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1777 +0x5a
github.com/ethereumproject/go-ethereum/logger/glog.(*syncBuffer).rotateOld(0xc044a1c140, 0xbe9047f88e4fec10, 0x7aeef55759, 0x17a67c0)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1225 +0x308
created by github.com/ethereumproject/go-ethereum/logger/glog.(*syncBuffer).Write
        c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1105 +0x1b1
```

**Comment by karalabe** [comment]
That is the Ethereum Classic fork, not our code. You'll need to go to them to figure what's wrong.
