### ISSUE TITLE
mist won't start

### ISSUE THREAD

**Issue by soloist624** [ethereum/go-ethereum#16042]
Hi there,

I started mist 0.9.3 from windows powershell with no argument and it stocked on "Ethereum node needs to sync" "looking for peers..." but never ends and clicking on "Launch application" does not work.

bytheway ethereum wallet 0.9.3 works fine (even on running multiple instances) and whole my network is local on my own device

here is what I see in powershell:
```
PS F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked> .\Mist.exe
PS F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked>
[2018-02-08 18:41:24.643] [INFO] main - Running in production mode: true
[2018-02-08 18:41:24.729] [INFO] EthereumNode - undefined null 'fast'
[2018-02-08 18:41:24.732] [INFO] EthereumNode - Defaults loaded: geth main fast
[2018-02-08 18:41:26.132] [INFO] main - Starting in Mist mode
[2018-02-08 18:41:26.200] [INFO] Db - Loading db: C:\Users\NaviD\AppData\Roaming\Mist\mist.lokidb
[2018-02-08 18:41:26.231] [INFO] Windows - Creating commonly-used windows
[2018-02-08 18:41:26.232] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-02-08 18:41:26.361] [INFO] updateChecker - Check for update...
[2018-02-08 18:41:33.457] [INFO] Windows - Create primary window: main, owner: notset
[2018-02-08 18:41:33.511] [INFO] Windows - Create primary window: splash, owner: notset
[2018-02-08 18:41:34.630] [INFO] ipcCommunicator - Backend language set to:  en
[2018-02-08 18:41:35.590] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2018-02-08 18:41:35.733] [INFO] (ui: splashscreen) - Meteor starting up...
[2018-02-08 18:41:35.743] [ERROR] updateChecker - Error checking for update { RequestError
    at ClientRequest.req.once.err (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at connectErrorNT (net.js:1032:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND api.github.com api.github.com:443',
  host: 'api.github.com',
  hostname: 'api.github.com',
  method: 'GET',
  path: '/repos/ethereum/mist/releases' }
[2018-02-08 18:41:35.864] [INFO] ClientBinaryManager - Initializing...
[2018-02-08 18:41:35.866] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-02-08 18:41:35.873] [WARN] ClientBinaryManager - Error fetching client binaries config from repo { RequestError
    at ClientRequest.req.once.err (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at connectErrorNT (net.js:1032:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443',
  host: 'raw.githubusercontent.com',
  hostname: 'raw.githubusercontent.com',
  method: 'GET',
  path: '/ethereum/mist/master/clientBinaries.json' }
[2018-02-08 18:41:35.877] [INFO] ClientBinaryManager - No config for the ClientBinaryManager could be loaded, using local clientBinaries.json.
[2018-02-08 18:41:35.887] [INFO] ClientBinaryManager - Initializing...
[2018-02-08 18:41:35.906] [INFO] ClientBinaryManager - Resolving platform...
[2018-02-08 18:41:35.909] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-02-08 18:41:35.913] [INFO] ClientBinaryManager - 1 possible clients.
[2018-02-08 18:41:35.916] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-02-08 18:41:35.925] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-02-08 18:41:36.283] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-02-08 18:41:36.284] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-02-08 18:41:36.552] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.7.2" in Geth output
    at Promise.resolve.then.then.then (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:635:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
[2018-02-08 18:41:36.560] [INFO] ClientBinaryManager - Download binary for Geth ...
[2018-02-08 18:41:36.567] [INFO] ClientBinaryManager - Downloading package from https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.7.2-1db4ecdc.zip to C:\Users\NaviD\AppData\Roaming\Mist\binaries\Geth\archive.zip ...
[2018-02-08 18:41:36.577] [ERROR] ClientBinaryManager - { RequestError
    at ClientRequest.req.once.err (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at connectErrorNT (net.js:1032:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND gethstore.blob.core.windows.net gethstore.blob.core.windows.net:443',
  host: 'gethstore.blob.core.windows.net',
  hostname: 'gethstore.blob.core.windows.net',
  method: 'GET',
  path: '/builds/geth-windows-amd64-1.7.2-1db4ecdc.zip' }
[2018-02-08 18:41:36.581] [ERROR] ClientBinaryManager - Error: Error downloading package for Geth: getaddrinfo ENOTFOUND gethstore.blob.core.windows.net gethstore.blob.core.windows.net:443
    at DuplexWrapper.stream.on (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:251:16)
    at emitOne (events.js:96:13)
    at DuplexWrapper.emit (events.js:191:7)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at ClientRequest.req.once.err (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\got\index.js:73:7)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at connectErrorNT (net.js:1032:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2018-02-08 18:41:36.587] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-02-08 18:41:36.605] [INFO] Sockets/node-ipc - Connected!
[2018-02-08 18:41:36.607] [INFO] NodeSync - Ethereum node connected, re-start sync
[2018-02-08 18:41:36.610] [INFO] NodeSync - Starting sync loop
[2018-02-08 18:41:36.615] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-02-08 18:41:36.630] [INFO] Sockets/3 - Connected!
[2018-02-08 18:41:44.827] [ERROR] main - Error starting up node and/or syncing { RequestError: net::ERR_NAME_NOT_RESOLVED
    at ClientRequest.req.once.err (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\app.asar\node_modules\swarm-js\node_modules\got\index.js:111:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest._emitRequestEvent (F:\source\EthereumInUseTools\Mist-win64-0-9-3\win-unpacked\resources\electron.asar\browser\api\net.js:89:24)
  name: 'RequestError',
  host: 'ethereum-mist.s3.amazonaws.com',
  hostname: 'ethereum-mist.s3.amazonaws.com',
  method: 'GET',
  path: '/swarm/swarm-windows-amd64-1.6.7.exe.tar.gz',
  protocol: 'http:',
  url: 'http://ethereum-mist.s3.amazonaws.com/swarm/swarm-windows-amd64-1.6.7.exe.tar.gz' }
[2018-02-08 18:42:00.246] [INFO] NodeSync - Sync has been skipped
[2018-02-08 18:42:00.247] [INFO] NodeSync - Sync loop ended
```

**Comment by karalabe** [comment]
Please open an issue on the Mist repository https://github.com/ethereum/mist/issues. I don't see anything Geth related in the logs.
