### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#16076]
#### System information
Rinkeby testnet crash
Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)
gethv1.8.0-unstable-8d32c4b9/windows-amd64/go1.9.2"

#### Expected behaviour
No crash

#### Actual behaviour

crash

#### Backtrace

```
INFO [02-12|13:59:01] Imported new chain segment               blocks=1461 txs=3610  mgas=634.773  elapsed=8.021s    mgasps=79.134   number=1514490 hash=59516fâ€¦1fcb7d cache=17.19mB
INFO [02-12|13:59:03] Imported new chain segment               blocks=587  txs=1061  mgas=158.929  elapsed=1.959s    mgasps=81.106   number=1515077 hash=06bb5bâ€¦8b15f3 cache=15.26mB
INFO [02-12|13:59:08] Imported new chain segment               blocks=2048 txs=3980  mgas=463.905  elapsed=5.248s    mgasps=88.396   number=1517125 hash=c49d2eâ€¦8ff07d cache=17.07mB
panic: runtime error: index out of range

goroutine 35432 [running]:
github.com/ethereum/go-ethereum/p2p/discover.(*Table).replace(0xc04e5bbb80, 0xc04e775980, 0xc04ed520a0, 0x1b4e68848c3ba14a)
	C:/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:766 +0x223
github.com/ethereum/go-ethereum/p2p/discover.(*Table).doRevalidate(0xc04e5bbb80, 0xc04e7486c0)
	C:/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:489 +0x1b5
created by github.com/ethereum/go-ethereum/p2p/discover.(*Table).loop
	C:/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:400 +0x766
```

**Comment by karalabe** [comment]
Sweeeet, nice catch! Thank you for reporting this.

**Comment by rfikki** [comment]
Thanks for the quick fix!!!
