### ISSUE TITLE
Some bugs cause the program to exit unexpectedly.

### ISSUE THREAD

**Issue by CarilKing** [ethereum/go-ethereum#16180]
Hi there,

the geth Some bugs cause the program to drop out unexpectedly.
#### System information

Geth version: `1.7`
OS & Version:  Linux
Commit hash : 

#### Error
```
goroutine 12568048 [chan receive, 312 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc42796a078, 0xe32840, 0xc47866ae10, 0x5fb9bb)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0xc9
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteTx
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:747 +0x2ae
```

**Comment by veox** [comment]
Do you experience this with the more recent `1.8.x` version?..

**Comment by vladislav-karamfilov** [comment]
Yes, the latest 1.8.7 is affected too...
