### ISSUE TITLE
Ambiguity in Wei fractional denominations documented in wiki

### ISSUE THREAD

**Issue by lazzarello** [ethereum/go-ethereum#16220]
#### System information

Geth version: 
```
Geth
Version: 1.8.1-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.10/libexec
```
OS & Version: `10.13.3 (17D102)`

#### Expected behaviour

The units expressed in the wiki should be consistent with the output of geth.

#### Actual behaviour

The units expressed in the wiki are not consistent with the output of geth.

#### Steps to reproduce the behaviour

At the time of this issue, the wiki docs say

```
web3.fromWei
web3.fromWei(number, unit)
Converts a number of wei into the following ethereum units:

kwei/ada
mwei/babbage
gwei/shannon
szabo
finney
ether
kether/grand/einstein
mether
gether
tether
```

When I run this function on my computer with geth, the output looks like this

```
> web3.fromWei(1, 'babbage')
"0.001"
> web3.fromWei(1, 'kwei')
"0.001"
> web3.fromWei(1, 'mwei')
"0.000001"
> web3.fromWei(1, 'ada')
Error: This unit doesn't exists, please use the one of the following units{
  "Gwei": "1000000000",
  "Kwei": "1000",
  "Mwei": "1000000",
  "babbage": "1000",
  "ether": "1000000000000000000",
  "femtoether": "1000",
  "finney": "1000000000000000",
  "gether": "1000000000000000000000000000",
  "grand": "1000000000000000000000",
  "gwei": "1000000000",
  "kether": "1000000000000000000000",
  "kwei": "1000",
  "lovelace": "1000000",
  "mether": "1000000000000000000000000",
  "micro": "1000000000000",
  "microether": "1000000000000",
  "milli": "1000000000000000",
  "milliether": "1000000000000000",
  "mwei": "1000000",
  "nano": "1000000000",
  "nanoether": "1000000000",
  "noether": "0",
  "picoether": "1000000",
  "shannon": "1000000000",
  "szabo": "1000000000000",
  "tether": "1000000000000000000000000000000",
  "wei": "1"
}
    at web3.js:2135:19
    at web3.js:2162:53
    at <anonymous>:1:1
```

I would edit the wiki but I don't know which is correct, 'babbage' or 'kwei'

**Comment by ligi** [comment]
> I would edit the wiki but I don't know which is correct, 'babbage' or 'kwei'

I would say Kwei is correct  - Kilo (1000) Wei - babbage might be a synonym - but personally I find them rather confusing - I understand the urge to give credits to some important figures this way - but let's not surface this to users and confuse them this way ..-)
