### ISSUE TITLE
Puppeth - cant deploy faucet to remote machine

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/go-ethereum#16268]
Cant seem to deploy the faucet network component - I get the errors below

Geth
Version: 1.8.2-unstable
Git Commit: 4c845bdc271c46706ea4af248a1efec8683dc53a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

```
goroutine 1 [running]:
math/big.(*Int).Int64(...)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_faucet.go:52
main.(*wizard).deployFaucet(0xc42007a200)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_faucet.go:52 +0x17b
main.(*wizard).deployComponent(0xc42007a200)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_network.go:194 +0x407
main.(*wizard).manageComponents(0xc42007a200)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_network.go:165 +0xdcf
main.(*wizard).run(0xc42007a200)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_intro.go:150 +0x9f0
main.main.func1(0xc4200aab00, 0xc4200aab00, 0xc42012dc8f)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:51 +0x3f2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x8f33a0, 0x9ca978, 0xc4200aab00, 0xc4200565a0, 0x0)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42006cea0, 0xc4200101b0, 0x1, 0x1, 0x0, 0x0)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
main.main()
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:54 +0x261
```

**Comment by karalabe** [comment]
Did you configure a genesis block for your network? Seems to crash wen trying to access some data about the genesis.

**Comment by REPTILEHAUS** [comment]
Yeah I used Puppeth to generate the genesis block. line 52 in wizard_faucet.go seems to reference the chainID in the genesis block, the chainID im using for testing is simply 2018 and i tried to change it to other numbers like 20180228 etc and it still gives this error

**Comment by adamschmideg** [comment]
The beginning of the log is missing, not enough information to inspect it. @REPTILEHAUS if you still have the issue, please open another ticket with more details.
