### ISSUE TITLE
Hash mismatch from https://gethstore.blob.core.windows.net

### ISSUE THREAD

**Issue by codercurtis** [ethereum/go-ethereum#16262]
When I attempt to start mist:

```
[2018-03-05 20:20:29.865] [INFO] main - Running in production mode: true
[2018-03-05 20:20:29.889] [INFO] EthereumNode - undefined null 'fast'
[2018-03-05 20:20:29.890] [INFO] EthereumNode - Defaults loaded: geth main fast
[2018-03-05 20:20:30.252] [INFO] main - Starting in Mist mode
[2018-03-05 20:20:30.268] [INFO] Db - Loading db: C:\Users\XXXXXXX\AppData\Roaming\Mist\mist.lokidb
[2018-03-05 20:20:30.274] [INFO] Windows - Creating commonly-used windows
[2018-03-05 20:20:30.274] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-03-05 20:20:30.308] [INFO] updateChecker - Check for update...
[2018-03-05 20:20:32.682] [INFO] Windows - Create primary window: main, owner: notset
[2018-03-05 20:20:32.693] [INFO] Windows - Create primary window: splash, owner: notset
[2018-03-05 20:20:32.981] [INFO] ipcCommunicator - Backend language set to:  en
[2018-03-05 20:20:33.271] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
[2018-03-05 20:20:33.318] [INFO] (ui: splashscreen) - Meteor starting up...
[2018-03-05 20:20:33.351] [INFO] ClientBinaryManager - Initializing...
[2018-03-05 20:20:33.352] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-03-05 20:20:33.455] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
[2018-03-05 20:20:33.456] [INFO] ClientBinaryManager - Initializing...
[2018-03-05 20:20:33.456] [INFO] ClientBinaryManager - Resolving platform...
[2018-03-05 20:20:33.457] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-03-05 20:20:33.457] [INFO] ClientBinaryManager - 1 possible clients.
[2018-03-05 20:20:33.458] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-03-05 20:20:33.458] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-03-05 20:20:33.507] [INFO] updateChecker - App is up-to-date.
[2018-03-05 20:20:33.562] [ERROR] ClientBinaryManager - Unable to resolve Geth executable: geth.exe
[2018-03-05 20:20:33.563] [INFO] ClientBinaryManager - Download binary for Geth ...
[2018-03-05 20:20:33.564] [INFO] ClientBinaryManager - Downloading package from https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.8.2-b8b9f7f4.zip to C:\Users\XXXXXXX\AppData\Roaming\Mist\binaries\Geth\archive.zip ...
[2018-03-05 20:20:38.304] [ERROR] ClientBinaryManager - md5
[2018-03-05 20:20:38.304] [ERROR] ClientBinaryManager - f498df54aaa42f4269c2d2d06df482fd
[2018-03-05 20:20:38.305] [ERROR] ClientBinaryManager - 3080558f77ea924596379d15b3df5dcd
[2018-03-05 20:20:38.306] [ERROR] ClientBinaryManager - Error: Hash mismatch: 3080558f77ea924596379d15b3df5dcd
    at checksum.then (D:\Mist\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:294:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
[2018-03-05 20:20:38.312] [ERROR] main - Error starting up node and/or syncing Error: Hash mismatch: 3080558f77ea924596379d15b3df5dcd
    at checksum.then (D:\Mist\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:294:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by karalabe** [comment]
@evertonfraga ?

**Comment by evertonfraga** [comment]
Please follow from here: https://github.com/ethereum/mist/issues/3730
