### ISSUE TITLE
GETH Throwing geth closed with code 1

### ISSUE THREAD

**Issue by bluecoderNR** [ethereum/go-ethereum#16306]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
1. i am using geth with node it was working fine but when i exits out of node server and restarts the server it is throwing error
/************************************************ Error ********************************************/
Error: geth closed with code 1
    at ChildProcess.listeners.close (/media/bluecoder/b4ec19a3-3ccc-43c9-8e71-98d93f2c4bc6/Projects/yollup_app/node_modules/geth/index.js:164:38)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
undefined
/****************************************************************************************************/

But when i run the the project via ssh it's working fine  

2. When i use geth on amazon elastic bean server i always get this error 

#### What did you expect to see?
 I expect the code to run my project 
#### What did you see instead?
 Error: geth closed with code 1
    at ChildProcess.listeners.close (/media/bluecoder/b4ec19a3-3ccc-43c9-8e71-98d93f2c4bc6/Projects/yollup_app/node_modules/geth/index.js:164:38)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
undefined
#### System details
ubuntu for the first case and amazon linux for second case 

Version: 1.7.3-stable
Go Version: go1.9
OS: linux
uname -sr: Linux 4.13.0-36-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by karalabe** [comment]
This is only the error produced by your own code. We can't really do much with it. What logs does Geth print?

**Comment by lhfly5201314** [comment]
I met the same issue like the described by the author.
I failed to launch the geth from javascript code with the geth.js installed by npm.
https://www.npmjs.com/package/geth
But launching from the shell console works.
How to fix that?

**Comment by karalabe** [comment]
I have no idea what `geth.js` is. You'll have to find whoever maintains is and ask. It's not done by us.
