### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by poctek** [ethereum/go-ethereum#16355]
Hi everyone!

Running the go-ethererum client in docker, got the following exception during the client work:

```
panic: runtime error: invalid memory address or nil pointer dereference
```

It worked fine before (for several weeks) and after the container restart.

The client was statrted with this command:

```
geth --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcport 6588  --rpcapi "eth,net,web3" --syncmode "light" --cache=1024 "$@" --unlock '0x0' --password <(echo $PASSWORD)
```

The server workload is quite high. Might this cause the error?

Here's the full log:

```
2018-03-17T07:44:14.901605733Z INFO [03-17|07:44:14] Imported new block headers count=0 elapsed=159.626µs number=5270190 hash=aca955…06441a ignored=1
2018-03-17T07:44:45.607798437Z panic: runtime error: invalid memory address or nil pointer dereference
2018-03-17T07:44:45.607861390Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xb1eb3f]
2018-03-17T07:44:45.607876080Z
2018-03-17T07:44:45.607887094Z goroutine 3395332 [running]:
2018-03-17T07:44:45.674325398Z math/big.(*Int).Uint64(...)
2018-03-17T07:44:45.674377123Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/fetcher.go:567
2018-03-17T07:44:45.674400338Z github.com/ethereum/go-ethereum/les.(*lightFetcher).checkAnnouncedHeaders(0xc420102100, 0xc4245b3000, 0xc4268ce260, 0x1, 0x1, 0xc4268ce258, 0x1, 0x1, 0xa)
2018-03-17T07:44:45.674410340Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/fetcher.go:567 +0x19f
2018-03-17T07:44:45.674420687Z github.com/ethereum/go-ethereum/les.(*lightFetcher).checkKnownNode(0xc420102100, 0xc4308e8240, 0xc422f15680, 0xc431b923a8)
2018-03-17T07:44:45.674431174Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/fetcher.go:652 +0x1fa
2018-03-17T07:44:45.674463041Z github.com/ethereum/go-ethereum/les.(*lightFetcher).announce(0xc420102100, 0xc4308e8240, 0xc4260767d0)
2018-03-17T07:44:45.674482660Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/fetcher.go:327 +0x861
2018-03-17T07:44:45.674492546Z github.com/ethereum/go-ethereum/les.(*ProtocolManager).handleMsg(0xc431ad8d20, 0xc4308e8240, 0x0, 0x0)
2018-03-17T07:44:45.674501497Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:398 +0x931
2018-03-17T07:44:45.674510644Z github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle(0xc431ad8d20, 0xc4308e8240, 0x0, 0x0)
2018-03-17T07:44:45.674521256Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:325 +0x770
2018-03-17T07:44:45.674539430Z github.com/ethereum/go-ethereum/les.NewProtocolManager.func1(0xc426208120, 0x185f2a0, 0xc4201f79d0, 0x0, 0x0)
2018-03-17T07:44:45.674548580Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:174 +0x252
2018-03-17T07:44:45.674566975Z github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc4201f79d0, 0xc426208120, 0x185f2a0, 0xc4201f79d0)
2018-03-17T07:44:45.674577402Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:349 +0x66
2018-03-17T07:44:45.848625581Z created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
2018-03-17T07:44:45.848672950Z /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x228
```

geth version: 1.8.0-unstable-40656953

**Comment by holiman** [comment]
Thanks for the report, but this was fixed with https://github.com/ethereum/go-ethereum/pull/16103

**Comment by poctek** [comment]
@holiman thank you, updated the geth version :)
