### ISSUE TITLE
run 2 nodes in private network will cause fatal error

### ISSUE THREAD

**Issue by gravin** [ethereum/go-ethereum#16401]
```
nohup geth --identity "node00" --networkid 99 --datadir ./data/00 --nodiscover --mine --rpc --rpcport 8200 --port 61910 >>data00.log 2>&1 &

nohup geth --identity "node01" --networkid 99 --datadir ./data/01 --nodiscover --mine --rpc --rpcport 8201 --port 61911 >>data01.log 2>&1 &
```
when the second command start up, the first process will break up immediately, end with 
```
INFO [03-28|16:10:49] Commit new mining work                   number=9 txs=0 uncles=0 elapsed=152.759µs
unexpected fault address 0x7f03d5f70000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f03d5f70000 pc=0x46a060]

goroutine 77 [running]:
runtime.throw(0xf02b33, 0x5)
	/home/sw/go/src/runtime/panic.go:619 +0x81 fp=0xc4203ade68 sp=0xc4203ade48 pc=0x4399f1
runtime.sigpanic()
	/home/sw/go/src/runtime/signal_unix.go:385 +0x273 fp=0xc4203adeb8 sp=0xc4203ade68 pc=0x44f6b3
runtime.memmove(0x7f03d5f6ffc8, 0xc42824ad00, 0x40)
	/home/sw/go/src/runtime/memmove_amd64.s:191 +0x180 fp=0xc4203adec0 sp=0xc4203adeb8 pc=0x46a060
github.com/ethereum/go-ethereum/consensus/ethash.generateDataset.func2(0xc4201f6060, 0x407fff80, 0x2, 0xc4204f6000, 0x407f30, 0x407f30, 0x0, 0x7f03b3800008, 0x407fff80, 0x407fff80, ...)
	/home/sw/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:318 +0x201 fp=0xc4203adf58 sp=0xc4203adec0 pc=0x9e5c91
runtime.goexit()
	/home/sw/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4203adf60 sp=0xc4203adf58 pc=0x469671
```

**Comment by holiman** [comment]
Can confirm! And this is great, we've been hit by that bug several times, but never easily reproduceable.

**Comment by holiman** [comment]
The first one:
```
INFO [03-28|10:41:06] IPC endpoint opened                      url=/tmp/data00/geth.ipc
TRACE[03-28|10:41:06] Requiring new ethash dataset             epoch=0
TRACE[03-28|10:41:06] Requiring new future ethash dataset      epoch=1
DEBUG[03-28|10:41:06] Failed to load old ethash dataset        epoch=0 err="open /home/user/.ethash/full-R23-0000000000000000: no such file or directory"
DEBUG[03-28|10:41:07] Generated ethash verification cache      epoch=0 elapsed=976.187ms
DEBUG[03-28|10:41:08] Couldn't add port mapping                proto=tcp extport=61910 intport=61910 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
unexpected fault address 0x76cd2c3ad308
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x76cd2c3ad308 pc=0x470e01]

goroutine 15 [running]:
```

The second one:

```
INFO [03-28|10:41:09] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=244.193µs
TRACE[03-28|10:41:09] Requiring new ethash dataset             epoch=0
TRACE[03-28|10:41:09] Requiring new future ethash dataset      epoch=1
DEBUG[03-28|10:41:09] Failed to load old ethash dataset        epoch=0 err="open /home/user/.ethash/full-R23-0000000000000000: no such file or directory"
DEBUG[03-28|10:41:10] Generated ethash verification cache      epoch=0 elapsed=1.247s

```
Command:
```
BIN=./build/bin/geth
FLAGS="--verbosity 5 --networkid 99 --datadir /tmp/data00 --nodiscover --mine --rpc --etherbase=0x0000000000000000000000000000000000001337"

./build/bin/geth $FLAGS --identity "node00" --datadir /tmp/data00 --rpcport 8200 --port 61910
```

So obviously, the ethash generator does not respect the `datadir`.

**Comment by holiman** [comment]
Ah
```
	EthashDatasetDirFlag = DirectoryFlag{
		Name:  "ethash.dagdir",
		Usage: "Directory to store the ethash mining DAGs (default = inside home folder)",
		Value: DirectoryString{eth.DefaultConfig.Ethash.DatasetDir},
	}
```
It defaults to the home folder, not the datadir. Seems to be intentional, which kind of makes sense, since if you are running several miners, you want to reuse the dag. 

However, I guess the bug is that there is no lockfile used to determine which process is allowed ownership of generating dags there...? @karalabe?

**Comment by gravin** [comment]
found it is because i let 2 processes to mine, only 1 process miner allowed, so close. as this https://github.com/ethereum/go-ethereum/issues/16033
