### ISSUE TITLE
EVM out of memory exception during bytecode processing

### ISSUE THREAD

**Issue by kedenk** [ethereum/go-ethereum#16475]
#### System information

Geth version: `1.8.3-unstable-62bc179b`
OS & Version: Ubuntu 16.04 LTS

#### Expected behaviour
The EVM should process the given bytecode sequence and provide the appropriated. 

#### Actual behaviour
The EVM crashes with an `out of memory` exception at program count 10 (bytecode `f3`). This happens after the EVM consumes all of the memory and swap. The given bytecode sequence to the EVM is: `435b5944425b59594243f3`. The crash happens every time I execute this statement. 

#### Steps to reproduce the behaviour
Execute the following statement: 
`/evms/geth-evm --code 435b5944425b59594243f3 --prestate /tmp/genesis-geth.json --gas 1152921504606846975 --nomemory --nostack --json run`

The given genesis file is the following: 
`{"extraData": "0x0000000000000000000000000000000000000000000000000000000000000000", "alloc": {"0x123456789a123456789a123456789a123456789c": {"nonce": "0x0", "balance": "0x293da15dff53c", "code": "0x1337"}, "0x123456789a123456789a123456789a123456789a": {"nonce": "0x0", "balance": "0x1b162307f492d0", "code": "0x1337"}, "0x123456789a123456789a123456789a123456789e": {"nonce": "0x0", "balance": "0x13bbc5b0d92635", "code": "0x1337"}, "0x333456789a123456789a123453289a1234512893": {"nonce": "0x0", "balance": "0x14eea6976d3297", "code": "0x1337"}, "0x123456789a321232189a123456789a123456789f": {"nonce": "0x0", "balance": "0x741ced22c4dd1", "code": "0x1337"}}, "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000", "config": {"eip150Block": 0, "byzantiumBlock": 0, "daoForkBlock": 0, "eip158Block": 0, "eip155Block": 0, "homesteadBlock": 0}, "number": "0x00", "coinbase": "0x0000000000000000000000000000000000000000", "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "difficulty": "0x01", "gasLimit": "0x3D0900", "timestamp": "0x00", "nonce": "0x0000000000000000"}`

#### Backtrace

````
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb42f2a, 0x16)
	/usr/lib/go-1.9/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc70bb50000, 0xe0730000, 0x1469800, 0x1495058)
	/usr/lib/go-1.9/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x147b9c0, 0xe0730000, 0x7ffe5ac45650)
	/usr/lib/go-1.9/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x147b9c0, 0x70394, 0x0)
	/usr/lib/go-1.9/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x147b9c0, 0x70394, 0x1495068, 0x113cc20)
	/usr/lib/go-1.9/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x147b9c0, 0x70394, 0xffffffffffff0101, 0x7ffe5ac45720)
	/usr/lib/go-1.9/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.9/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7ffe5ac45738)
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x147b9c0, 0x70394, 0x7fc3f0000101, 0x7ffe5ac457b8)
	/usr/lib/go-1.9/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0xe0728000, 0x460100, 0xc658146000)
	/usr/lib/go-1.9/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
	/usr/lib/go-1.9/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0x1469800)
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/lib/go-1.9/src/runtime/proc.go:1135

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:298 fp=0xc47afd3068 sp=0xc47afd3060 pc=0x46f640
runtime.mallocgc(0xe0728000, 0x0, 0x8fa56000, 0xc658146000)
	/usr/lib/go-1.9/src/runtime/malloc.go:721 +0x7ae fp=0xc47afd3110 sp=0xc47afd3068 pc=0x42639e
runtime.growslice(0xa37d00, 0xc658146000, 0xb38ec000, 0xb38ec000, 0xb38ec002, 0xc658146000, 0x8fa56000, 0xb38ec000)
	/usr/lib/go-1.9/src/runtime/slice.go:140 +0x20c fp=0xc47afd3178 sp=0xc47afd3110 pc=0x45915c
fmt.(*fmt).fmt_sbx(0xc420184100, 0x0, 0x0, 0xc47afd8000, 0x5acb7f0a, 0x5acb8000, 0xb3e808, 0x11)
	/usr/lib/go-1.9/src/fmt/format.go:388 +0x21c fp=0xc47afd3200 sp=0xc47afd3178 pc=0x4da05c
fmt.(*fmt).fmt_bx(0xc420184100, 0xc47afd8000, 0x5acb7f0a, 0x5acb8000, 0xb3e808, 0x11)
	/usr/lib/go-1.9/src/fmt/format.go:404 +0x6f fp=0xc47afd3250 sp=0xc47afd3200 pc=0x4da4af
fmt.(*pp).fmtBytes(0xc4201840c0, 0xc47afd8000, 0x5acb7f0a, 0x5acb8000, 0x78, 0xb35a1e, 0x6)
	/usr/lib/go-1.9/src/fmt/print.go:475 +0x9f6 fp=0xc47afd3358 sp=0xc47afd3250 pc=0x4de526
fmt.(*pp).printArg(0xc4201840c0, 0xa2c8a0, 0xc42000c020, 0x78)
	/usr/lib/go-1.9/src/fmt/print.go:666 +0x403 fp=0xc47afd33d8 sp=0xc47afd3358 pc=0x4dfa63
fmt.(*pp).doPrintf(0xc4201840c0, 0xb34767, 0x5, 0xc47afd5088, 0x1, 0x1)
	/usr/lib/go-1.9/src/fmt/print.go:996 +0x15a fp=0xc47afd3508 sp=0xc47afd33d8 pc=0x4e382a
fmt.Fprintf(0x112b1a0, 0xc42007e008, 0xb34767, 0x5, 0xc47afd5088, 0x1, 0x1, 0x1, 0xc42000c020, 0xc42000c020)
	/usr/lib/go-1.9/src/fmt/print.go:181 +0x72 fp=0xc47afd3570 sp=0xc47afd3508 pc=0x4dbaf2
fmt.Printf(0xb34767, 0x5, 0xc47afd5088, 0x1, 0x1, 0x0, 0xc4200f91f0, 0xc47afd8000)
	/usr/lib/go-1.9/src/fmt/print.go:190 +0x72 fp=0xc47afd35d0 sp=0xc47afd3570 pc=0x4dbc02
main.runCmd(0xc4201ccb00, 0x0, 0x0)
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/evm/runner.go:240 +0x1413 fp=0xc47afd7a98 sp=0xc47afd35d0 pc=0x95ceb3
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xa4a4a0, 0xb60598, 0xc4201ccb00, 0xc420062900, 0x0)
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2 fp=0xc47afd7ac0 sp=0xc47afd7a98 pc=0x6ffeb2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb33c2c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb44459, 0x18, 0x0, ...)
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa95 fp=0xc47afd7d40 sp=0xc47afd7ac0 pc=0x701225
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4201ec820, 0xc420086000, 0xa, 0xa, 0x0, 0x0)
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6f8 fp=0xc47afd7f20 sp=0xc47afd7d40 pc=0x6fe018
main.main()
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/evm/main.go:146 +0x55 fp=0xc47afd7f80 sp=0xc47afd7f20 pc=0x95b7b5
runtime.main()
	/usr/lib/go-1.9/src/runtime/proc.go:195 +0x226 fp=0xc47afd7fe0 sp=0xc47afd7f80 pc=0x442926
runtime.goexit()
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc47afd7fe8 sp=0xc47afd7fe0 pc=0x472271

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.9/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/lib/go-1.9/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go-1.9/src/os/signal/signal_unix.go:28 +0x41

goroutine 4 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc420062780, 0xc4200626c0)
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xc0
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x149

goroutine 5 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc420062780, 0xc420062720)
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x88
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/user/thesis/project_eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x178
````

**Comment by holiman** [comment]
So, the code is
```
NUMBER
JUMPDEST
MSIZE
DIFFICULTY
TIMESTAMP
JUMPDEST
MSIZE
MSIZE
TIMESTAMP
NUMBER
RETURN 
```
Basically, "Put some arbitrary large numbers on the stack, then do `RETURN` with data of size `TIMESTAMP` starting from memory position `NUMBER`"

Normally, that would go out of gas, since `TIMESTAMP` is rather large. However, since you also supply it with 1.152 TRILLION gas, it just goes ahead and tries to allocate that for you. 

The mainnet has 8 MILLION gas per block -- it's easy to crash the VM by using orders of magnitude more gas .
