### ISSUE TITLE
starting private network node stops with "runtime error: invalid memory address or nil pointer dereference" filter_system.go:434

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16675]
Hi there,

Geth stops with nil pointer derefence error when running new private network.  
While something may be not implemented, a software should not stop without pointing to reason of error.

#### System information

Geth version: `geth version`
```
E:\Geth>geth version
Geth
Version: 1.8.2-stable
Git Commit: b8b9f7f4476a30a0aaf6077daade6ae77f969960
Architecture: amd64
```
OS & Version: Windows/Linux/OSX   
Windows 7

#### Expected behaviour

node can start

#### Actual behaviour

node fails with nil pointer derefence error

#### Steps to reproduce the behaviour

1. modify previouly successful genesis.json (generated by puppeth)
(genesis json shown fully in #16676)
2. geth init
3. geth run (see below)

#### Backtrace

````
INFO [05-04|15:05:34] Successfully wrote genesis state         database=lightchaindata                          hash=61c7cc…b502fb

E:\Geth>geth --datadir .bc5202/ --networkid 5202 --syncmode "full" --port 35202 --nodiscover --nousb --rpc --rpcaddr "localhost" --rpcport 8502 --rpcapi "admin,
personal,db,eth,net,web3,txpool,miner" --txpool.pricelimit 0 --mine --gasprice 0 --etherbase 0x31a5e0e68b4ca721a2005144f6c32f6d1c1c4b99 --unlock 0x31a5e0e68b4ca
721a2005144f6c32f6d1c1c4b99 --password password31.txt --extradata node1
INFO [05-04|15:07:59] Maximum peer count                       ETH=25 LES=0 total=25
INFO [05-04|15:07:59] Starting peer-to-peer node               instance=Geth/v1.8.2-stable-b8b9f7f4/windows-amd64/go1.9.2
INFO [05-04|15:07:59] Allocated cache and file handles         database=E:\\Geth\\.bc5202\\geth\\chaindata cache=768 handles=1024
WARN [05-04|15:08:00] Upgrading database to use lookup entries
INFO [05-04|15:08:00] Initialised chain configuration          config="{ChainID: 5202 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 By
zantium: 0 Constantinople: <nil> Engine: clique}"
INFO [05-04|15:08:00] Initialising Ethereum protocol           versions="[63 62]" network=5202
INFO [05-04|15:08:00] Database deduplication successful        deduped=0
INFO [05-04|15:08:00] Loaded most recent local header          number=0 hash=61c7cc…b502fb td=1
INFO [05-04|15:08:00] Loaded most recent local full block      number=0 hash=61c7cc…b502fb td=1
INFO [05-04|15:08:00] Loaded most recent local fast block      number=0 hash=61c7cc…b502fb td=1
WARN [05-04|15:08:00] Sanitizing invalid txpool price limit    provided=0 updated=1
INFO [05-04|15:08:00] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-04|15:08:00] Starting P2P networking
INFO [05-04|15:08:00] RLPx listener up                         self="enode://1b77169a3d234f83646b0f91f6aec0c7dc2074da6c2a5a900d6c72116a0036567cee4c69panic: 
runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xab2c57]

goroutine 82 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc0422ed500)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:434 +0x337
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:113 +0x10b
````

Code in question

https://github.com/ethereum/go-ethereum/blob/release/1.8/eth/filters/filter_system.go#L113

https://github.com/ethereum/go-ethereum/blob/release/1.8/eth/filters/filter_system.go#L434

**Comment by paulvi** [comment]
TODO check in 1.8.8
