### ISSUE TITLE
100% CPU usage when starting node on Raspberry PI3b+ on Android Things

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#16791]
was introduced with 1.8.4 - same code on 1.8.3 does not block with 100%CPU usage
```
(pprof) top10
Showing nodes accounting for 29.89s, 99.73% of 29.97s total
Dropped 42 nodes (cum <= 0.15s)
Showing top 10 nodes out of 15
      flat  flat%   sum%        cum   cum%
    29.89s 99.73% 99.73%     29.89s 99.73%  runtime.cgocall
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).refreshWallets
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/accounts/usbwallet.NewLedgerHub
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/accounts/usbwallet.newHub
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/mobile.NewNode
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/node.New
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/node.makeAccountManager
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid.Enumerate
         0     0% 99.73%     29.89s 99.73%  github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid._Cfunc_hid_enumerate
         0     0% 99.73%     29.89s 99.73%  main._cgoexpwrap_35c606efd04e_proxygeth__NewNode
```
![pi3_problem_prof big](https://user-images.githubusercontent.com/111600/40428882-9a0538c0-5ea1-11e8-942d-34b9f3152e41.png)

```
goroutine 47 [running]:
runtime/pprof.writeGoroutineStacks(0x94cca310, 0x504b3c20, 0x0, 0x0)
	/usr/lib/go-1.10/src/runtime/pprof/pprof.go:650 +0x88
runtime/pprof.writeGoroutine(0x94cca310, 0x504b3c20, 0x2, 0x940fcd70, 0x50433964)
	/usr/lib/go-1.10/src/runtime/pprof/pprof.go:639 +0x30
runtime/pprof.(*Profile).WriteTo(0x9506f980, 0x94cca310, 0x504b3c20, 0x2, 0x504b3c20, 0x72)
	/usr/lib/go-1.10/src/runtime/pprof/pprof.go:310 +0x2e8
net/http/pprof.handler.ServeHTTP(0x50773271, 0x9, 0x94ccde08, 0x504b3c20, 0x504dca00)
	/usr/lib/go-1.10/src/net/http/pprof/pprof.go:243 +0x1cc
net/http/pprof.Index(0x94ccde08, 0x504b3c20, 0x504dca00)
	/usr/lib/go-1.10/src/net/http/pprof/pprof.go:254 +0x178
net/http.HandlerFunc.ServeHTTP(0x94cc60b8, 0x94ccde08, 0x504b3c20, 0x504dca00)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x34
net/http.(*ServeMux).ServeHTTP(0x9514f168, 0x94ccde08, 0x504b3c20, 0x504dca00)
	/usr/lib/go-1.10/src/net/http/server.go:2337 +0x110
net/http.serverHandler.ServeHTTP(0x50730380, 0x94ccde08, 0x504b3c20, 0x504dca00)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0x74
net/http.(*conn).serve(0x506f03c0, 0x94cce2e8, 0x506f3560)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x5c8
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2795 +0x234

goroutine 45 [IO wait]:
internal/poll.runtime_pollWait(0xa66f5dc0, 0x72, 0x0)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x507b2014, 0x72, 0x94191700, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0xa0
internal/poll.(*pollDesc).waitRead(0x507b2014, 0xffffff00, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Accept(0x507b2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:372 +0x17c
net.(*netFD).accept(0x507b2000, 0x940fe144, 0x940fe0dc, 0x507ec040)
	/usr/lib/go-1.10/src/net/fd_unix.go:238 +0x20
net.(*TCPListener).accept(0x50714288, 0x507ec040, 0x94c00548, 0x94c00548)
	/usr/lib/go-1.10/src/net/tcpsock_posix.go:136 +0x20
net.(*TCPListener).AcceptTCP(0x50714288, 0x9415a8f8, 0x5075d728, 0x5075d72c)
	/usr/lib/go-1.10/src/net/tcpsock.go:246 +0x3c
net/http.tcpKeepAliveListener.Accept(0x50714288, 0x94cc5fa4, 0x507ec000, 0x94cce348, 0x50711660)
	/usr/lib/go-1.10/src/net/http/server.go:3216 +0x1c
net/http.(*Server).Serve(0x50730380, 0x94cce1e8, 0x50714288, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/http/server.go:2770 +0x16c
net/http.(*Server).ListenAndServe(0x50730380, 0x50730380, 0x0)
	/usr/lib/go-1.10/src/net/http/server.go:2711 +0x94
net/http.ListenAndServe(0x5078b490, 0x10, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/http/server.go:2969 +0x7c
github.com/ethereum/go-ethereum/internal/debug.StartPProf.func1(0x5078b490, 0x10)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/internal/debug/flags.go:148 +0x30
created by github.com/ethereum/go-ethereum/internal/debug.StartPProf
	/home/ligi/go/src/github.com/ethereum/go-ethereum/internal/debug/flags.go:147 +0x1a4

goroutine 17 [syscall, locked to thread]:
github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid._Cfunc_hid_enumerate(0x2c97, 0x0)
	_cgo_gotypes.go:332 +0x3c
github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid.Enumerate(0x2c97, 0x0, 0x0, 0x0)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid/hid_enabled.go:82 +0x74
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).refreshWallets(0x504e5140)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:138 +0xb4
github.com/ethereum/go-ethereum/accounts/usbwallet.newHub(0x94879ed2, 0x6, 0x504b2c97, 0x5078b4fc, 0x2, 0x2, 0xffa0, 0x0, 0x94cc4d9c, 0x0, ...)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:93 +0xe8
github.com/ethereum/go-ethereum/accounts/usbwallet.NewLedgerHub(0x504fb090, 0x4a, 0x40000)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:71 +0x90
github.com/ethereum/go-ethereum/node.makeAccountManager(0x50508ea0, 0x94877a59, 0x4, 0x0, 0x0, 0x0)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/node/config.go:424 +0x124
github.com/ethereum/go-ethereum/node.New(0x50508ea0, 0x50508d80, 0x2, 0x504fb090)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/node/node.go:102 +0x168
github.com/ethereum/go-ethereum/mobile.NewNode(0x504fb040, 0x41, 0x507560c0, 0x41, 0xffffffe8, 0x504b3588)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/mobile/geth.go:134 +0x268
main.proxygeth__NewNode(0x92c83000, 0x41, 0xffffffe8, 0x940fccbc, 0x940fcd4c)
	/tmp/gomobile-work-268348506/src/gobind/go_gethmain.go:4743 +0x68
main._cgoexpwrap_35c606efd04e_proxygeth__NewNode(0x92c83000, 0x41, 0xffffffe8, 0x0, 0xa1d1f790)
	_cgo_gotypes.go:5452 +0x2c

goroutine 37 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0x504ba340, 0x504ba2c0)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x9c
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xdc

goroutine 38 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0x504ba340, 0x504ba300)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x3c
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x104

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0xa66f5d40, 0x72, 0x506f358d)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x504de6a4, 0x72, 0xffffff00, 0x94ccae68, 0x9508b9d8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0xa0
internal/poll.(*pollDesc).waitRead(0x504de6a4, 0x506f3500, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x504de690, 0x506f358d, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x150
net.(*netFD).Read(0x504de690, 0x506f358d, 0x1, 0x1, 0x50494000, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x504b1ed8, 0x506f358d, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x58
net/http.(*connReader).backgroundRead(0x506f3580)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x48
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xbc

goroutine 54 [syscall]:
syscall.Syscall6(0xfc, 0x30, 0x504bc7ac, 0x1, 0xffffffff, 0x0, 0x0, 0x9410bf74, 0x507320f0, 0x0)
	/usr/lib/go-1.10/src/syscall/asm_linux_arm.s:48 +0x8
github.com/ethereum/go-ethereum/vendor/golang.org/x/sys/unix.EpollWait(0x30, 0x504bc7ac, 0x1, 0x1, 0xffffffff, 0x507320f0, 0x0, 0x1)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go:1949 +0x58
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).loop(0x5050c000, 0x50732140)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:194 +0x74
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:134 +0x134

goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0xa66f5fc0, 0x72, 0x50760000)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x50607f94, 0x72, 0xffffff01, 0x94ccae68, 0x9508b9d8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0xa0
internal/poll.(*pollDesc).waitRead(0x50607f94, 0x50760001, 0x400, 0x400)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x50607f80, 0x50760000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x150
os.(*File).read(0x504b19d0, 0x50760000, 0x400, 0x400, 0x5049b628, 0x2, 0x941303cc)
	/usr/lib/go-1.10/src/os/file_unix.go:226 +0x3c
os.(*File).Read(0x504b19d0, 0x50760000, 0x400, 0x400, 0x5049b5e0, 0x941354c8, 0x50440008)
	/usr/lib/go-1.10/src/os/file.go:107 +0x4c
bufio.(*Reader).fill(0x504c37b8)
	/usr/lib/go-1.10/src/bufio/bufio.go:100 +0x104
bufio.(*Reader).ReadSlice(0x504c37b8, 0x9478790a, 0x947c65c0, 0x504c371c, 0x0, 0x504c371c, 0x947875ac)
	/usr/lib/go-1.10/src/bufio/bufio.go:341 +0x1c
bufio.(*Reader).ReadLine(0x504c37b8, 0xabc727e8, 0xa1d1fcd0, 0x73, 0x506fc070, 0x6b, 0x0)
	/usr/lib/go-1.10/src/bufio/bufio.go:370 +0x24
golang.org/x/mobile/internal/mobileinit.lineLog(0x504b19d0, 0x6)
	/home/ligi/go/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:55 +0x98
created by golang.org/x/mobile/internal/mobileinit.init.0
	/home/ligi/go/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:82 +0x10c

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0xa66f5ec0, 0x72, 0x50760400)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x50756014, 0x72, 0xffffff01, 0x94ccae68, 0x9508b9d8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0xa0
internal/poll.(*pollDesc).waitRead(0x50756014, 0x50760401, 0x400, 0x400)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x50756000, 0x50760400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x150
os.(*File).read(0x504b19e0, 0x50760400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/os/file_unix.go:226 +0x3c
os.(*File).Read(0x504b19e0, 0x50760400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/os/file.go:107 +0x4c
bufio.(*Reader).fill(0x504c3fb8)
	/usr/lib/go-1.10/src/bufio/bufio.go:100 +0x104
bufio.(*Reader).ReadSlice(0x504c3fb8, 0xacf6130a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/bufio/bufio.go:341 +0x1c
bufio.(*Reader).ReadLine(0x504c3fb8, 0x400, 0x400, 0x50760400, 0x400, 0x400, 0x0)
	/usr/lib/go-1.10/src/bufio/bufio.go:370 +0x24
golang.org/x/mobile/internal/mobileinit.lineLog(0x504b19e0, 0x4)
	/home/ligi/go/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:55 +0x98
created by golang.org/x/mobile/internal/mobileinit.init.0
	/home/ligi/go/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:92 +0x1c8

goroutine 43 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0x14c
os/signal.loop()
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.0
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x34

goroutine 44 [select, locked to thread]:
runtime.gopark(0x94cc62b8, 0x0, 0x9487a364, 0x6, 0x18, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x10c
runtime.selectgo(0x5075cfa0, 0x504970c0)
	/usr/lib/go-1.10/src/runtime/select.go:392 +0xee4
runtime.ensureSigM.func1()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x1e0
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_arm.s:1015 +0x4

goroutine 46 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0x50659e70)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:94 +0x430
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/home/ligi/go/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x54

goroutine 55 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).send(0x5050c000, 0x50732140)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:254 +0x98
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:137 +0x184

goroutine 56 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).send(0x5050c000, 0x50732140)
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:254 +0x98
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/ligi/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:137 +0x184
```

Can't we just drop all the HID code - don't really think this is very helpful on mobile anyway and just wastes memory/cpu-cycles and makes problems like this

**Comment by karalabe** [comment]
Is this still relevant?

**Comment by ligi** [comment]
No - actually Android-Tings is discontinued :-(
