### ISSUE TITLE
geth crashed

### ISSUE THREAD

**Issue by SvenMeyer** [ethereum/go-ethereum#16897]
#### System information
Geth Version: 1.8.10-stable
Git Commit: eae63c511ceafab14b92e274c1b18bf1700e2d3d
OS & Version: Linux Mint 18.3
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

#### Expected behaviour
syncing

#### Actual behaviour
crash

#### Steps to reproduce the behaviour
```
$ geth --cache 4096 --ethash.cachesinmem 64 --trie-cache-gens 1024  --maxpeers 32


INFO [05-31|07:21:46] Imported new chain segment               blocks=1  txs=153  mgas=7.984  elapsed=1.053s    mgasps=7.579  number=5704678 hash=f595e4…e1c10d cache=124.16mB
INFO [05-31|07:21:52] Imported new chain segment               blocks=1  txs=202  mgas=7.884  elapsed=930.199ms mgasps=8.476  number=5704678 hash=afb301…40cba2 cache=124.39mB
INFO [05-31|07:22:13] Imported new chain segment               blocks=1  txs=133  mgas=7.989  elapsed=1.099s    mgasps=7.265  number=5704680 hash=31b5d2…7d5cf3 cache=124.36mB
panic: leveldb: internal key "", len=0: invalid length

goroutine 1671817 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.internalKey.assert(0xc5ab69401e, 0x0, 0x1ff1)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/key.go:111 +0x161
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.internalKey.ukey(0xc5ab69401e, 0x0, 0x1ff1, 0x22e9, 0xc4b26d0b40, 0x20)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/key.go:116 +0x3f
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0xc42020ad40, 0xc5ab69401e, 0x0, 0x1ff1, 0xc4b26d0b40, 0x28, 0x28, 0xffffffffffffffff)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/comparer.go:38 +0x4c
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0x152, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:71 +0x1c1
sort.Search(0x1ea, 0xc4ff3072e0, 0xc54c3aaef8)
	/usr/lib/go-1.10/src/sort/search.go:66 +0x58
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*block).seek(0xc4482a8c80, 0x109dc20, 0xc42020ad40, 0x0, 0x1ea, 0xc4b26d0b40, 0x28, 0x28, 0x8, 0xc569a43880, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:65 +0xc1
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Seek(0xc4b26cf590, 0xc4b26d0b40, 0x28, 0x28, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:232 +0xe7
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).find(0xc4ec96eb60, 0xc4b26d0b40, 0x28, 0x28, 0xc4ff307501, 0x0, 0xc420203800, 0x0, 0x0, 0x0, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:834 +0x1d1
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).Find(0xc4ec96eb60, 0xc4b26d0b40, 0x28, 0x28, 0x1, 0x0, 0xc42020ad40, 0xc5690fb680, 0x20, 0xc4ff307590, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:918 +0x7a
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*tOps).find(0xc420388f00, 0xc451067130, 0xc4b26d0b40, 0x28, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.go:382 +0x132
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).get.func1(0x5, 0xc451067130, 0x20)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:176 +0x44e
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).walkOverlapping(0xc4e52e4140, 0x0, 0x0, 0x0, 0xc4b26d0b40, 0x28, 0x28, 0xc4ff307818, 0xc4ff3077e8)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:125 +0x457
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).get(0xc4e52e4140, 0x0, 0x0, 0x0, 0xc4b26d0b40, 0x28, 0x28, 0x0, 0x1656f600, 0x0, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:160 +0x2ae
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).get(0xc42021e1a0, 0x0, 0x0, 0x0, 0x0, 0xc42863f300, 0x20, 0x20, 0x294498b2, 0x0, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:779 +0x397
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).Get(0xc42021e1a0, 0xc42863f300, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:845 +0x12f
github.com/ethereum/go-ethereum/ethdb.(*LDBDatabase).Get(0xc4202e3080, 0xc42863f300, 0x20, 0x20, 0xc5a0d52780, 0x1, 0x0, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/ethdb/database.go:112 +0x5a
github.com/ethereum/go-ethereum/trie.(*Database).Node(0xc4200305a0, 0xff85f79ad7d4a0a, 0x65fff228dc60a6ce, 0xaeb797b6d2a91c6a, 0x29fc326624314026, 0x118, 0x130, 0xc5a0d528c0, 0x0, 0xc434179c00)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/database.go:133 +0x160
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc51f6c19d0, 0xc51e4b9620, 0x20, 0x20, 0xc4c24daaf0, 0x5, 0x41, 0xc4c24da910, 0x4d, 0x50, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:437 +0x159
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc51f6c19d0, 0x109bfa0, 0xc44ac2f000, 0xc4c24daaf0, 0x41, 0x41, 0x5, 0xc4c24da910, 0x4d, 0x50, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:169 +0xef
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc51f6c19d0, 0x109a1a0, 0xc54f530780, 0xc4c24daaf0, 0x41, 0x41, 0x4, 0xc4c24da910, 0x4d, 0x50, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:161 +0x6d7
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc51f6c19d0, 0x109a1a0, 0xc58768be00, 0xc4c24daaf0, 0x41, 0x41, 0x3, 0xc4c24da910, 0x4d, 0x50, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:161 +0x6d7
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc51f6c19d0, 0x109a1a0, 0xc51fa79e00, 0xc4c24daaf0, 0x41, 0x41, 0x2, 0x14ed256cd52da44f, 0x82b357c7094ae25b, 0x425bf9, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:161 +0x6d7
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc51f6c19d0, 0x109a1a0, 0xc5af7b57c0, 0xc4c24daaf0, 0x41, 0x41, 0x1, 0xaaaa975f82488ee7, 0xc4ff308458, 0x56c4fd, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:161 +0x6d7
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc51f6c19d0, 0x109a1a0, 0xc5a0d52dc0, 0xc4c24daaf0, 0x41, 0x41, 0x0, 0x20, 0xc51f6c1a10, 0x20, ...)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:161 +0x6d7
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc51f6c19d0, 0xc51f6c1a10, 0x20, 0x20, 0xc51f6c1a10, 0x20, 0x20, 0xcf2230, 0xc5d86a1880)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:135 +0x7b
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc51f6c19d0, 0xc42863f2c0, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:80 +0x7b
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(0xc4e0c100e0, 0x93c9a1216ff4e563, 0x6e2ae3000f0b57a9, 0xcab20ec, 0xffffffffffffffff)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:372 +0x130
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetNonce(0xc4e0c100e0, 0x93c9a1216ff4e563, 0x6e2ae3000f0b57a9, 0xc40cab20ec, 0x1)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:200 +0x3f
github.com/ethereum/go-ethereum/core.(*TxPool).validateTx(0xc42027ddc0, 0xc4a3230120, 0x59209504676ef00, 0x1d39c1a970c53a0e, 0x909bf7abcb749f05)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:579 +0x231
github.com/ethereum/go-ethereum/core.(*TxPool).add(0xc42027ddc0, 0xc4a3230120, 0xc4ff308e00, 0xc4cc21e600, 0x10917e0, 0xc54b838ef0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:613 +0xde
github.com/ethereum/go-ethereum/core.(*TxPool).addTxsLocked(0xc42027ddc0, 0xc4b649e000, 0x211, 0x2c7, 0xc522b20100, 0xe79380, 0xc57805b080, 0xc4ff3090e8)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:817 +0x12e
github.com/ethereum/go-ethereum/core.(*TxPool).addTxs(0xc42027ddc0, 0xc4b649e000, 0x211, 0x2c7, 0x1df84a46f93db800, 0x0, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:805 +0xaf
github.com/ethereum/go-ethereum/core.(*TxPool).AddRemotes(0xc42027ddc0, 0xc4b649e000, 0x211, 0x2c7, 0x7131a37ca414cab3, 0x1a1d75e7d2d2, 0x1af00c0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:779 +0x4e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc425e42180, 0xc5316a9c30, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:674 +0x491
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc425e42180, 0xc5316a9c30, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:309 +0x846
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc5a58c8f00, 0x1095720, 0xc52482f0a0, 0x0, 0x0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:142 +0x1db
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc52482f0a0, 0xc5a58c8f00, 0x1095720, 0xc52482f0a0)
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/build/ethereum-aQVICZ/ethereum-1.8.10+build13740+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:347 +0x201
```

**Comment by karalabe** [comment]
Can't say I've ever seen this error message. Seems to originate from leveldb, some internal corruption. Not sure if there's anything we can do about it. Did your instance crash by any chance? Power outage? Bad sectors on disk?
