### ISSUE TITLE
can not restart geth after first close

### ISSUE THREAD

**Issue by joelcho** [ethereum/go-ethereum#17082]
Hi there,
    I encountered a thorny issue. 
    I downloaded the Windows version of geth from Ethereum and finish synchronized all the nodes. 
    For some reason I must to restart the operating system. So I executed "ctrl + c" in the geth window, but after that geth can not start. 
    The system disk size is 1TB, memory is 16GB, IBM Server r2 ent,.

I am an Ethereum rookie. At present, I have no other solution and information to solve this problem.  if you have links, please share with me,  thank you.

    Start a while will throw the following error:

```
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:
628 +0x144
github.com/ethereum/go-ethereum/p2p.(*rlpx).ReadMsg(0xc0a35ea6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:
89 +0x1e2
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc08f9ccb00, 0xc08a104e40)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:
214 +0x97
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:
145 +0x100

goroutine 18628 [runnable]:
net.runtime_pollWait(0x7828198, 0x72, 0xc0a0a9ebc8)
        C:/Go/src/runtime/netpoll.go:160 +0x67
net.(*pollDesc).Wait(0xc0d54f2170, 0x72, 0x0, 0x0)
        C:/Go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082404000, 0xc0d54f2060, 0x1001d50, 0x7, 0x12b1838, 0xcef5e0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:183 +0x177
net.(*netFD).Read(0xc0d54f2000, 0xc0974260e0, 0xd2, 0xd2, 0x0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:482 +0x17e
net.(*conn).Read(0xc1247cc560, 0xc0974260e0, 0xd2, 0xd2, 0x0, 0x0, 0x0)
        C:/Go/src/net/net.go:172 +0xeb
io.ReadAtLeast(0x781f5e8, 0xc1247cc560, 0xc0974260e0, 0xd2, 0xd2, 0xd2, 0x0, 0x0, 0x0)
        C:/Go/src/io/io.go:297 +0xed
io.ReadFull(0x781f5e8, 0xc1247cc560, 0xc0974260e0, 0xd2, 0xd2, 0xd2, 0x0, 0x0)
        C:/Go/src/io/io.go:315 +0x69
github.com/ethereum/go-ethereum/p2p.readHandshakeMsg(0x781f610, 0xc082076f80, 0xd2, 0xc0829375c0, 0x
781f5e8, 0xc1247cc560, 0x0, 0x0, 0x0, 0x0, ...)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:
474 +0xcb
github.com/ethereum/go-ethereum/p2p.initiatorEncHandshake(0x781f590, 0xc1247cc560, 0xc0829375c0, 0xb
0507f27f1692384, 0x92d7ca02b7e896fa, 0x2238b9fdd18ea996, 0x7c2e77baafb4e159, 0xeb460081fb040f41, 0xa
4488356172f8989, 0xfa0ec4b64c7192d9, ...)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:
283 +0x2d5
github.com/ethereum/go-ethereum/p2p.(*rlpx).doEncHandshake(0xc854a43200, 0xc0829375c0, 0xc0889d3a00,
 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:
171 +0x2f5
github.com/ethereum/go-ethereum/p2p.(*Server).setupConn(0xc08248c900, 0x781f4e8, 0xc1247cc560, 0x1,
0xc0889d3a00)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/server.g
o:616 +0x248
github.com/ethereum/go-ethereum/p2p.(*dialTask).dial(0xc871eb67b0, 0xc08248c900, 0xc0889d3a00, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/dial.go:
270 +0x442
github.com/ethereum/go-ethereum/p2p.(*dialTask).Do(0xc871eb67b0, 0xc08248c900)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/dial.go:
217 +0x79
github.com/ethereum/go-ethereum/p2p.(*Server).run.func2.1(0x57f1360, 0xc871eb67b0, 0xc08248c900, 0xc
082cb6060)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/server.g
o:431 +0x38
created by github.com/ethereum/go-ethereum/p2p.(*Server).run.func2
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/server.g
o:431 +0x27e

goroutine 18627 [IO wait]:
net.runtime_pollWait(0x7828498, 0x77, 0xc11cbe1d78)
        C:/Go/src/runtime/netpoll.go:160 +0x67
net.(*pollDesc).Wait(0xc116a02770, 0x77, 0x0, 0x0)
        C:/Go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082404008, 0xc116a026e8, 0x1011b30, 0x9, 0x12b1858, 0x0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:183 +0x177
net.(*netFD).connect(0xc116a02600, 0x19b1830, 0xc878ed24a0, 0x19b1830, 0xc878ed2480, 0xed2c3a01e, 0x
3b31500c, 0x18215c0, 0x0, 0x0, ...)
        C:/Go/src/net/fd_windows.go:369 +0x6ae
net.(*netFD).dial(0xc116a02600, 0x77b1ec8, 0x0, 0x77b1ec8, 0xc8799423c0, 0xed2c3a01e, 0x3b31500c, 0x
18215c0, 0x0, 0x0, ...)
        C:/Go/src/net/sock_posix.go:137 +0x36b
net.socket(0x10092c0, 0x3, 0x2, 0x1, 0x0, 0xc879942300, 0x77b1ec8, 0x0, 0x77b1ec8, 0xc8799423c0, ...
)
        C:/Go/src/net/sock_posix.go:89 +0x37f
net.internetSocket(0x10092c0, 0x3, 0x77b1ec8, 0x0, 0x77b1ec8, 0xc8799423c0, 0xed2c3a01e, 0x3b31500c,
 0x18215c0, 0x1, ...)
        C:/Go/src/net/ipsock_posix.go:161 +0x15a
net.dialTCP(0x10092c0, 0x3, 0x0, 0xc8799423c0, 0xed2c3a01e, 0x3b31500c, 0x18215c0, 0x0, 0x0, 0x0, ..
.)
        C:/Go/src/net/tcpsock_posix.go:171 +0x132
net.dialSingle(0xc0a4605200, 0x77b1e60, 0xc8799423c0, 0xed2c3a01e, 0x3b31500c, 0x18215c0, 0x0, 0x0,
0x0, 0x0)
        C:/Go/src/net/dial.go:371 +0x413
net.dialSerial.func1(0xed2c3a01e, 0x3b31500c, 0x18215c0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:343 +0x7c
net.dial(0x10092c0, 0x3, 0x77b1e60, 0xc8799423c0, 0xc878ed2460, 0xed2c3a01e, 0x3b31500c, 0x18215c0,
0x0, 0x0, ...)
        C:/Go/src/net/fd_windows.go:87 +0x113
net.dialSerial(0xc0a4605200, 0xc11cbe1d10, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:345 +0x7d7
net.(*Dialer).Dial(0xc0828ef450, 0x10092c0, 0x3, 0xc878ed2420, 0x12, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:239 +0x519
github.com/ethereum/go-ethereum/p2p.(*dialTask).dial(0xc871eb6780, 0xc08248c900, 0xc08b28e000, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/dial.go:
264 +0x28e
github.com/ethereum/go-ethereum/p2p.(*dialTask).Do(0xc871eb6780, 0xc08248c900)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/dial.go:
217 +0x79
github.com/ethereum/go-ethereum/p2p.(*Server).run.func2.1(0x57f1360, 0xc871eb6780, 0xc08248c900, 0xc
082cb6060)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/server.g
o:431 +0x38
created by github.com/ethereum/go-ethereum/p2p.(*Server).run.func2
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/server.g
o:431 +0x27e
```

There is a strange problem here. I don’t have a drive letter "D:\" at all.

**Comment by joelcho** [comment]
Here are some special messages when I started

```
I0626 11:46:43.403018 eth/downloader/downloader.go:319] Block synchronisation started
I0626 11:46:52.401649 eth/handler.go:290] Peer 7b60549e5d789e91 [eth/63]: timed out DAO fork-check, dropping
I0626 11:46:52.401649 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I0626 11:47:11.684142 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I0626 11:47:44.876977 eth/handler.go:290] Peer 1d475134ac8ffee9 [eth/63]: timed out DAO fork-check, dropping
I0626 11:48:04.180490 eth/downloader/queue.go:885] Peer 01fb8ed0109ca731: header #2309501 [965c4325] broke chain ancestry
I0626 11:48:05.056332 eth/downloader/queue.go:885] Peer 01fb8ed0109ca731: header #2322596 [2430d2c6] broke chain ancestry
I0626 11:48:07.137326 eth/downloader/queue.go:885] Peer 01fb8ed0109ca731: header #2336219 [6c568ae5] broke chain ancestry
I0626 11:48:07.891049 eth/downloader/queue.go:885] Peer 01fb8ed0109ca731: header #2345248 [3304a853] broke chain ancestry
```

**Comment by karalabe** [comment]
Please paste the entire crash dump. The beginning of it is the most interesting as that contains the actual crash.
