### ISSUE TITLE
geth 1.7.2 crashes on mainnet , only starts after removedb , the same incident occured on 2 of my geth servers

### ISSUE THREAD

**Issue by amitOodles** [ethereum/go-ethereum#17128]
#### System information

Geth version: `1.7.2`
OS & Version: Linux

#### Backtrace

````
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.shortenb(0x100412c3468, 0x4, 0xc428ab7a60)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.go:30 +0x157
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).computeCompaction(0xc435fdbb30)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:395 +0x4d8
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*versionStaging).finish(0xc428ab7d58, 0xc4203941e0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:510 +0x1ea
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).spawn(0xc4200f81e0, 0xc4203941e0, 0xc4200f81e0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:279 +0x87
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*session).commit(0xc4200820c0, 0xc4203941e0, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/session.go:195 +0x91
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0xc42027c000, 0xc42027c000, 0xc42046e900)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:538 +0xddf
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB(0xc4200820c0, 0x0, 0x0, 0xc4200820c0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x77e
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.Open(0x17f8220, 0xc4203a40e0, 0xc420e9c2f0, 0x0, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:194 +0x109
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.OpenFile(0xc4204aa810, 0x24, 0xc420e9c2f0, 0xc420f78358, 0x4, 0x4)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:216 +0x97
github.com/ethereum/go-ethereum/ethdb.NewLDBDatabase(0xc4204aa810, 0x24, 0x80, 0x400, 0x24, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethdb/database.go:77 +0x3f3
github.com/ethereum/go-ethereum/node.(*ServiceContext).OpenDatabase(0xc4201562a0, 0xf67b2a, 0x9, 0x80, 0x400, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/service.go:46 +0x133
github.com/ethereum/go-ethereum/eth.CreateDB(0xc4201562a0, 0xc4204bc380, 0xf67b2a, 0x9, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:199 +0x5d
github.com/ethereum/go-ethereum/eth.New(0xc4201562a0, 0xc4204bc380, 0x17b85a0, 0xc420f9d800, 0xc420f9db40)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:109 +0x8f
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc4201562a0, 0xc4204aa780, 0xc420f9db18, 0x0, 0xc4204aa7b0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1011 +0x3d
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc420252000, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:175 +0x59b
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc420252000)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:62 +0x2f
main.startNode(0xc42007e580, 0xc420252000)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:219 +0x43
main.geth(0xc42007e580, 0x1016618, 0xb2d05e00)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:209 +0x48
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xdf20a0, 0x1017bb8, 0xc42007e580, 0xc42007e580, 0xc420499f48)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd4
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200f5520, 0xc420010100, 0x8, 0x8, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x6ac
main.main()
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:198 +0x55

````

#### Backtrace verbosity level 5
````
TRACE[07-05|06:49:23] Started watching keystore folder         path=/opt/belfrics/mainnet/keystore
DEBUG[07-05|06:49:23] FS scan times                            list=26.771875ms set=14.33238ms diff=8.032263ms
DEBUG[07-05|06:49:23] FS scan times                            list=25.562146ms set=14.422134ms diff=23.279445ms
TRACE[07-05|06:49:23] Handled keystore changes                 time=260.95168ms
TRACE[07-05|06:49:23] Handled keystore changes                 time=291.64882ms
INFO [07-05|06:49:23] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.8.3
INFO [07-05|06:49:23] Allocated cache and file handles         database=/opt/belfrics/mainnet/geth/chaindata cache=128 handles=1024
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.shortenb(0x100412c3468, 0x4, 0xc43fa2da60)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.go:30 +0x157
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).computeCompaction(0xc43a0fc1e0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:395 +0x4d8
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*versionStaging).finish(0xc43fa2dd58, 0xc4201f0280)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:510 +0x1ea
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).spawn(0xc420120320, 0xc4201f0280, 0xc420120320)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:279 +0x87
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*session).commit(0xc4201d8180, 0xc4201f0280, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/session.go:195 +0x91
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0xc421244180, 0xc420252ea0, 0xc420252ea0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:538 +0xddf
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB(0xc4201d8180, 0x0, 0x0, 0xc4201d8180)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x77e
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.Open(0x17f8220, 0xc420aea0e0, 0xc420e0a2f0, 0x0, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:194 +0x109
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.OpenFile(0xc42001a540, 0x24, 0xc420e0a2f0, 0xc420e66408, 0x4, 0x4)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:216 +0x97
github.com/ethereum/go-ethereum/ethdb.NewLDBDatabase(0xc42001a540, 0x24, 0x80, 0x400, 0x24, 0x6e6f736a2e313162, 0x6c65622f74706f2f)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethdb/database.go:77 +0x3f3
github.com/ethereum/go-ethereum/node.(*ServiceContext).OpenDatabase(0xc42000c5e0, 0xf67b2a, 0x9, 0x80, 0x400, 0x6164313766653539, 0x3466363464626430, 0x6336396133323835, 0x6e6f736a2e383934)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/service.go:46 +0x133
github.com/ethereum/go-ethereum/eth.CreateDB(0xc42000c5e0, 0xc420071180, 0xf67b2a, 0x9, 0x66383161612d2d5a, 0x3062343130313166, 0x3439353961343864, 0x3731633035633230)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:199 +0x5d
github.com/ethereum/go-ethereum/eth.New(0xc42000c5e0, 0xc420071180, 0x17b85a0, 0xc420e07800, 0xc420e07b40)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:109 +0x8f
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc42000c5e0, 0xc42001a4b0, 0xc420e07b18, 0x0, 0xc42001a4e0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1011 +0x3d
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc4200cc000, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:175 +0x59b
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc4200cc000)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:62 +0x2f
main.startNode(0xc420090580, 0xc4200cc000)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:219 +0x43
main.geth(0xc420090580, 0x1016618, 0xb2d05e00)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:209 +0x48
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xdf20a0, 0x1017bb8, 0xc420090580, 0xc420090580, 0xc4204a7f48)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd4
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420114680, 0xc42007c000, 0xa, 0xa, 0x0, 0x0)
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x6ac
main.main()
	/home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:198 +0x55
````
Geth was unable to restart until i used removedb , with geth version updated to 1.8.11 and go version 1.9.7 from 1.8.3

The older geth executable were working fine for almost 6 months , until the above issue , which occured on the instances in span of two days. After which both of them went down.

Also with geth updated , it has pulled almost 150000000 states and is still not in sync , i have taken the keystore backup , what is the issue here ?

**Comment by rjl493456442** [comment]
We already have a fix for this problem. Here is the link https://github.com/syndtr/goleveldb/pull/214

**Comment by amitOodles** [comment]
Hi is this issue only specific to geth version 1.7.2 or every geth instance where the chaindata has reached above 1Tb storage ?

Before you answered , i switched the geth version to 1.8.11 and go version to 1.9 , what other thing do i need to update ?

**Comment by rjl493456442** [comment]
> Hi is this issue only specific to geth version 1.7.2 or every geth instance where the chaindata has reached above 1Tb storage ?

Before the fix, all geth version will have this problem.

> Before you answered , i switched the geth version to 1.8.11 and go version to 1.9 , what other thing do i need to update ?

You mean the chain data is not between v1.7.2 and v1.8.11? Is there a problem with direct startup?

**Comment by rjl493456442** [comment]
The latest version includes this fix, you can upgrade to latest or a stable version if you want.
