### ISSUE TITLE
eth.getBalance('account', 'block-no') returns 'Error: missing trie node'

### ISSUE THREAD

**Issue by Sandipan99** [ethereum/go-ethereum#17133]
Hi there,
For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.11`
OS & Version: Linux

#### Expected behaviour
>eth.getBalance('0x05a56e2d52c817161883f50c441c3228cfe54d9f',5851000)
8130

#### Actual behaviour
eth.getBalance('0x05a56e2d52c817161883f50c441c3228cfe54d9f',5850000)
Error: missing trie node 1a3bddc494098bac19ef26e6506812caa12ca5cf036a13ef0eabde38beab5d21 (path )
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

I have used --gcmode=archive so that pruning is disabled. I am new to ethereum and I think I am missing something obvious. I understand this is less of an issue but I did post this question at Ethereum stack exchange but have not received an answer yet.

**Comment by Sandipan99** [comment]
I did put --gcmode=archive but did not put any option for syncmode hence I think it went to synmode fast and only archived the state tries from my pivot block. Anyway, I am now trying with --syncmode=full --gcmode=archive
