### ISSUE TITLE
OOM when create account on geth ver 1.8.11 

### ISSUE THREAD

**Issue by ylight007** [ethereum/go-ethereum#17131]
Hi there,

I've done cross-compilation for Ethereum client "geth" (without modified), 
and executed on an armv7 platform.
When I want to create a user account on the geth console, I got out of memory dump.
The device has limited memory. Before running geth, it has about 80MB for free in size.
I know the default db cache size will be 1024MB on ver 1.8.11.
And it seem likes it can self-adjust the cache value on ver 1.8.11.
But somehow when I create account on the console, always got OOM error there.
Even I specify the cache size as 16MB. 
note: it works well on x64 enviornment

Thanks for reading and replying.

#### System information

Geth version: 1.8.11-stable 
OS & Version: Linux
Commit hash : n/a

#### Expected behaviour
\# ./geth init genesis.json --datadir hi
\# ./geth --fast --cache=16 --networkid 123 --datadir hi --rpc --rpcaddr x.x.x.x --port 3000 console
\> personal.newAccount("1234567")
Account created successfully.

#### Actual behaviour
\# ./geth init genesis.json --datadir hi
```
WARN [07-06|17:54:38] Sanitizing cache to Go's GC limits       provided=1024 updated=61
INFO [07-06|17:54:38] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-06|17:54:38] Allocated cache and file handles         database=/mnt/hi/geth/chaindata cache=16 handles=16
INFO [07-06|17:54:39] Persisted trie from memory database      nodes=0 size=0.00B time=3.828667ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [07-06|17:54:39] Successfully wrote genesis state         database=chaindata                        hash=54d897…ec32ef
INFO [07-06|17:54:39] Allocated cache and file handles         database=/mnt/hi/geth/lightchaindata cache=16 handles=16
INFO [07-06|17:54:40] Persisted trie from memory database      nodes=0 size=0.00B time=415.667µs  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [07-06|17:54:40] Successfully wrote genesis state         database=lightchaindata                        hash=54d897…ec32ef
```
\# ./geth --fast --cache=16 --networkid 123 --datadir hi --rpc --rpcaddr x.x.x.x --port 3000 console
```
INFO [07-06|17:55:07] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-06|17:55:07] Starting peer-to-peer node               instance=Geth/v1.8.11-stable/linux-arm/go1.10.3
INFO [07-06|17:55:07] Allocated cache and file handles         database=/mnt/hi/geth/chaindata cache=16 handles=512
INFO [07-06|17:55:07] Initialised chain configuration          config="{ChainID: <nil> Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil> Byzantium: <nil> Constantinople: <nil> Engine: unknown}"
INFO [07-06|17:55:07] Disk storage enabled for ethash caches   dir=/mnt/hi/geth/ethash count=3
INFO [07-06|17:55:07] Disk storage enabled for ethash DAGs     dir=/mnt/ramdisk/.ethash          count=2
INFO [07-06|17:55:07] Initialising Ethereum protocol           versions="[63 62]" network=123
INFO [07-06|17:55:07] Loaded most recent local header          number=0 hash=54d897…ec32ef td=10
INFO [07-06|17:55:07] Loaded most recent local full block      number=0 hash=54d897…ec32ef td=10
INFO [07-06|17:55:07] Loaded most recent local fast block      number=0 hash=54d897…ec32ef td=10
INFO [07-06|17:55:07] Loaded local transaction journal         transactions=0 dropped=0
INFO [07-06|17:55:08] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-06|17:55:08] Starting P2P networking
INFO [07-06|17:55:11] UDP listener up                          self=enode://f5b60b84e95dfc118dba821650e55826e39f385592295cdd934310a70d27a44f25d5d886c0ff4708372d8b6a4e37260c2e3d8584be61f65f3871e2355a2bdf4a@[::]:3000
INFO [07-06|17:55:11] RLPx listener up                         self=enode://f5b60b84e95dfc118dba821650e55826e39f385592295cdd934310a70d27a44f25d5d886c0ff4708372d8b6a4e37260c2e3d8584be61f65f3871e2355a2bdf4a@[::]:3000
INFO [07-06|17:55:12] IPC endpoint opened                      url=/mnt/hi/geth.ipc
INFO [07-06|17:55:12] HTTP endpoint opened                     url=http://x.x.x.x:8545      cors= vhosts=localhost
```
\> personal.newAccount("1234567")
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x99e2ab, 0x16)
        /usr/local/go/src/runtime/panic.go:616 +0x60
runtime.sysMap(0x13000000, 0x10000000, 0x42f01, 0x12ee8c0)
        /usr/local/go/src/runtime/mem_linux.go:227 +0x11c
runtime.(*mheap).sysAlloc(0x12e1718, 0x10000000, 0x118cec01)
        /usr/local/go/src/runtime/malloc.go:470 +0x23c
runtime.(*mheap).grow(0x12e1718, 0x8000, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x48
runtime.(*mheap).allocSpanLocked(0x12e1718, 0x8000, 0x12ee8d0, 0x9fe4)
        /usr/local/go/src/runtime/mheap.go:820 +0x30c
runtime.(*mheap).alloc_m(0x12e1718, 0x8000, 0xb2b90101, 0x60000010)
        /usr/local/go/src/runtime/mheap.go:686 +0x118
...
```
\# cat genesis.json
```
{
        "config": {},
        "gasLimit": "2000000",
        "difficulty": "10",
        "alloc": {}
}
```
#### Steps to reproduce the behaviour
./geth init genesis.json --datadir hi
./geth --fast --cache=16 --networkid 123 --datadir hi --rpc --rpcaddr x.x.x.x --port 3000 console
\> personal.newAccount("1234567")

#### Backtrace

````
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x99e2ab, 0x16)
        /usr/local/go/src/runtime/panic.go:616 +0x60
runtime.sysMap(0x13000000, 0x10000000, 0x42f01, 0x12ee8c0)
        /usr/local/go/src/runtime/mem_linux.go:227 +0x11c
runtime.(*mheap).sysAlloc(0x12e1718, 0x10000000, 0x118cec01)
        /usr/local/go/src/runtime/malloc.go:470 +0x23c
runtime.(*mheap).grow(0x12e1718, 0x8000, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x48
runtime.(*mheap).allocSpanLocked(0x12e1718, 0x8000, 0x12ee8d0, 0x9fe4)
        /usr/local/go/src/runtime/mheap.go:820 +0x30c
runtime.(*mheap).alloc_m(0x12e1718, 0x8000, 0xb2b90101, 0x60000010)
        /usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:753 +0x3c
runtime.(*mheap).alloc(0x12e1718, 0x8000, 0x10101, 0x12e34b8)
        /usr/local/go/src/runtime/mheap.go:752 +0x60
runtime.largeAlloc(0x10000000, 0x80101, 0xb6dc6000)
        /usr/local/go/src/runtime/malloc.go:826 +0x74
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:721 +0x38
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_arm.s:349 +0x80
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1175

goroutine 341 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_arm.s:294 +0x4 fp=0x12a4687c sp=0x12a46878 pc=0x8156c
runtime.mallocgc(0x10000000, 0x899920, 0x1163d401, 0x1238a000)
        /usr/local/go/src/runtime/malloc.go:720 +0x8a0 fp=0x12a468e0 sp=0x12a4687c pc=0x33aa0
runtime.makeslice(0x899920, 0x4000000, 0x4000000, 0x1238a000, 0x200, 0x200)
        /usr/local/go/src/runtime/slice.go:61 +0x68 fp=0x12a468f4 sp=0x12a468e0 pc=0x67cf4
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0x12ab5cb0, 0x7, 0x8, 0x11ad3ac0, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
        /home/ngips/blockchain/go-ethereum-source/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:236 +0x140 fp=0x12a46954 sp=0x12a468f4 pc=0x29f764
...
````

**Comment by ligi** [comment]
please try to use  
`--lightkdf                        Reduce key-derivation RAM & CPU usage at some expense of KDF strength
`

**Comment by ylight007** [comment]
Thanks for your advice.
I have tried it and it worked well.
Here I provide my new command again:
\# ./geth --fast --cache=16 --lightkdf --networkid 123 --datadir hi --rpc --rpcaddr x.x.x.x --port 3000 console
\> personal.newAccount("1234567")
**Account created successfully.**

Thanks @ligi , have a good day.
