### ISSUE TITLE
Not generating new account

### ISSUE THREAD

**Issue by gjalvarez** [ethereum/go-ethereum#17200]
Hi there,

I am trying to generate a new account it asks the password, and after that it frezee, only on the pop up window.

Also on the main window in develop menu, ethereum node appears sometimes, usually is not there

#### System information

Geth version: `1.8.11`
OS & Version: Windows/
Commit hash : (if `develop`)

#### Expected behaviour
Generate the new wallet and able to see the GETH version

#### Actual behaviour
Never generate the new wallet and the GETH version is not always there.

#### Steps to reproduce the behaviour
open the wallet and go to generate new account

#### Backtrace

````
[2018-07-18T21:43:05.915] [INFO] Settings - Running in production mode: true
[2018-07-18T21:43:05.998] [INFO] EthereumNode - undefined 'fast' 'light'
[2018-07-18T21:43:06.000] [INFO] EthereumNode - Defaults loaded: geth main fast
[2018-07-18T21:43:06.650] [INFO] main - Starting in Wallet mode
[2018-07-18T21:43:06.706] [INFO] Db - Loading db: C:\Users\gjalv\AppData\Roaming\Ethereum Wallet\mist.lokidb
[2018-07-18T21:43:06.730] [INFO] Windows - Creating commonly-used windows
[2018-07-18T21:43:06.732] [INFO] Windows - Create secondary window: loading, owner: notset
[2018-07-18T21:43:06.887] [INFO] updateChecker - Check for update...
[2018-07-18T21:43:13.046] [INFO] Sockets/node-ipc - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-07-18T21:43:14.700] [INFO] Windows - Create primary window: main, owner: notset
[2018-07-18T21:43:14.973] [INFO] ClientBinaryManager - Initializing...
[2018-07-18T21:43:14.975] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
[2018-07-18T21:43:14.999] [INFO] main - Loading Interface at file://C:\Users\gjalv\Desktop\eth wallet\resources\app.asar/interface/wallet/index.html
[2018-07-18T21:43:15.180] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-18T21:43:16.184] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-18T21:43:17.186] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-07-18T21:43:17.983] [WARN] ClientBinaryManager - Error fetching client binaries config from repo { RequestError: Request timed out
    at timeoutFn (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\got\index.js:131:53)
    at asPromise (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\got\index.js:134:9)
    at got (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\got\index.js:386:10)
    at Manager._checkForNewConfig (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\modules\clientBinaryManager.js:62:12)
    at Manager.init (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\modules\clientBinaryManager.js:39:17)
    at onReady (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\main.js:213:23)
    at App.<anonymous> (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\main.js:168:5)
    at Generator.next (<anonymous>)
    at step (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\main.js:25:191)
    at C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\main.js:25:361
    at <anonymous>
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'raw.githubusercontent.com',
  hostname: 'raw.githubusercontent.com',
  method: 'GET',
  path: '/ethereum/mist/master/clientBinaries.json',
  protocol: 'https:',
  url: 'https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json' }
[2018-07-18T21:43:18.005] [INFO] ClientBinaryManager - No config for the ClientBinaryManager could be loaded, using local clientBinaries.json.
[2018-07-18T21:43:18.035] [INFO] ClientBinaryManager - Initializing...
[2018-07-18T21:43:18.035] [INFO] ClientBinaryManager - Resolving platform...
[2018-07-18T21:43:18.036] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-07-18T21:43:18.038] [INFO] ClientBinaryManager - 1 possible clients.
[2018-07-18T21:43:18.039] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-07-18T21:43:18.040] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-07-18T21:43:18.174] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2018-07-18T21:43:18.176] [WARN] EthereumNode - Failed to connect to an existing local node. Starting our own...
[2018-07-18T21:43:18.176] [INFO] EthereumNode - Node type: geth
[2018-07-18T21:43:18.177] [INFO] EthereumNode - Network: main
[2018-07-18T21:43:18.177] [INFO] EthereumNode - SyncMode: fast
[2018-07-18T21:43:18.177] [INFO] EthereumNode - Start node: geth main fast
[2018-07-18T21:43:18.182] [ERROR] EthereumNode - Failed to start node Error: Node "geth" binPath is not available.
    at EthereumNode.__startNode (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\modules\ethereumNode.js:374:13)
    at stop.then (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\modules\ethereumNode.js:300:19)
    at tryCatcher (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[2018-07-18T21:43:18.822] [INFO] updateChecker - App is up-to-date.
[2018-07-18T21:43:19.514] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-07-18T21:43:19.515] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-07-18T21:43:20.825] [ERROR] (ui: popupWindow) - Unable to load preload script: C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\modules/preloader/popupWindows.js
[2018-07-18T21:43:20.827] [ERROR] (ui: popupWindow) - Error: %1 is not a valid Win32 application.
\\?\C:\Users\gjalv\AppData\Local\Temp\abcee510-ff66-4ff9-b744-20c1b350e029.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\scrypt\index.js:3:20)
    at Object.<anonymous> (C:\Users\gjalv\Desktop\eth wallet\resources\app.asar\node_modules\scrypt\index.js:388:3)
[2018-07-18T21:43:21.131] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-07-18T21:43:22.453] [INFO] (ui: popupWindow) - Meteor starting up...
[2018-07-18T21:43:32.709] [INFO] Sockets/3 - Disconnecting...
[2018-07-18T21:43:46.400] [ERROR] (ui: popupWindow) - connection not open on send()````

**Comment by karalabe** [comment]
This seems to be a `mist` issue, not related to `go-ethereum`. Please open an issue on their tracker https://github.com/ethereum/mist/issues
