### ISSUE TITLE
Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by turtlewen** [ethereum/go-ethereum#17222]
Hi there,

I encountered issue of   bailing. Network state unknown. Review successful transactions manually. and insufficient funds for gas * price + value

when migrate it , it not successful and come out this error

this is my deploy_contract.js

`var Voting = artifacts.require("./Voting.sol");
module.exports = function(deployer) {
  deployer.deploy(Voting, ['Rama', 'Nick', 'Jose'],{gas: 4700000});
};`

and my truffle.js

`require('babel-register')
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      network_id: '*',
      gas: 4700000
    }
  }
}`

#### System information

Geth version: `geth version`
OS & Version: Windows
Commit hash : 

#### Actual behaviour
`  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: insufficient funds for gas * price + value
    at Object.InvalidResponse (C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.j
s:38:1)
    at C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-migrate\index.js:225:1
    at C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web
3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\
lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.j
s:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xh
r2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\ling\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:
469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
You account apparently has less funds than it would take to run your code. Please ensure your balance is >= than `gas * price + value`.

**Comment by turtlewen** [comment]
i accidentally created 2 test net account  using this `web3.personal.newAccount('password')` 

one of the test net account have 3 ether and another one has 18 ether , is it still not enough ??

**Comment by karalabe** [comment]
What does `eth.getBalance(your account)` print? How much is the gas price you are sending the transactions with?

**Comment by turtlewen** [comment]
me try `eth.getBalance(your account)`

2 account return this value : 
`BigNumber { s: 1, e: 0, c: [ 0 ] }`

but i go to [rikeby website](https://rinkeby.etherscan.io ) and enter my address, both of the account got ether. 

i get the ether from this website https://faucet.rinkeby.io/

the gas price me sending is **gas: 4700000** (for deploy contract, and the truffle.js)

**Comment by RolandBarro** [comment]
I have the same error. I tried to view my account on ropsten etherscan network, it says I have 1Eth and running web3.eth.getBalance("myAddress") it says '1000000000000000000'
