### ISSUE TITLE
Failed to create mining context   err="missing trie node xxxxxx (path )"

### ISSUE THREAD

**Issue by zhuquanbin** [ethereum/go-ethereum#17286]
Hi there,
    When I use the program to continuously commit transactions,  Why does it appear ` Failed to create mining context          err=missing trie node  xxxx`.  **who can tell me ?  Thanks!**

- System information
```shell
prod@AWS-NX-15-002:~/deploys$ geth version
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
````
- Error console
```
prod@AWS-NX-15-002:~/deploys/$ geth attach http://127.0.0.1:8545
Welcome to the Geth JavaScript console!

instance: Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2
coinbase: 0xd2764136d6fae4e5344cc51a58f2a643970d3d1d
at block: 76185 (Tue, 31 Jul 2018 17:12:21 CST)
 datadir: /home/prod/deploys/data20180719
 modules: admin:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.getBalance(eth.coinbase)
Error: missing trie node ff354885bd551ad1f5dfa42e1ca05298fd035b33c93ef0a16f8f1ec1174c8f8d (path )
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

> 
```
- Geth log
```log
INFO [07-31|17:12:17] 🔗 block reached canonical chain          number=76178 hash=302861…3d5417
INFO [07-31|17:12:17] 🔨 mined potential block                  number=76183 hash=476151…1aca5c
INFO [07-31|17:12:17] Commit new mining work                   number=76184 txs=47  uncles=0 elapsed=15.687ms
INFO [07-31|17:12:17] Submitted transaction                    fullhash=0x2155cbddf2199afb35c4201a9e0d492f8d199e59311d0f8d9d31cc7f6cf6e30c recipient=0x5056183ecB2941aa6a939092146D38a9D81fcB8E
INFO [07-31|17:12:18] Submitted transaction                    fullhash=0x4d2b695e8c83b7cf0ec68dffe6d11db5fa163e564f56a420cf157c009c9cbb96 recipient=0x5e4fe880e79d9A1ae488F79E970b414bff38b850
INFO [07-31|17:12:18] Submitted transaction                    fullhash=0x6d99526246735045ad68d6ee388c8a6fa7ed52c2cdb29d2dd0797ba01b4d0943 recipient=0xF3A964053A251dad7Df474259a98244a2F9CAb80
INFO [07-31|17:12:19] Submitted transaction                    fullhash=0x49951e9d24eee331d0c926f5463af95050c9aab91048c0a2c961068f12086ea1 recipient=0xc16e3B51e00b91777653640028F2ff5Df4874725
INFO [07-31|17:12:19] Submitted transaction                    fullhash=0xc9ae243d8e5b0b8b17213c2d95f1aa28141e00b35f681b1e4574d2bccf737faa recipient=0x0E77fD343Fdb31b2d118ab771E58235A61648641
INFO [07-31|17:12:21] Successfully sealed new block            number=76184 hash=f568e3…a896c6
INFO [07-31|17:12:21] 🔗 block reached canonical chain          number=76179 hash=d00e28…007466
INFO [07-31|17:12:21] 🔨 mined potential block                  number=76184 hash=f568e3…a896c6
INFO [07-31|17:12:21] Commit new mining work                   number=76185 txs=5   uncles=0 elapsed=1.515ms
INFO [07-31|17:12:21] Submitted transaction                    fullhash=0xbafa398c4c84e92d132f88b4a6fe0041490c0b83c97be8d467d68c72a443bedd recipient=0x0A575e426512D0A4972f3e8266fCDb87eE3C2690
INFO [07-31|17:12:22] Submitted transaction                    fullhash=0x190701197aea6b7fbe6bbce5c75ab60e7c729f563f4dfcdd939c2e935e7194d5 recipient=0xb9De483C71a771571CBdc1Bf5F4B724882EeDd95
INFO [07-31|17:12:24] Submitted transaction                    fullhash=0xf1b769e2dcffe525d85cc01330fce481a9f658d231cf8e4e38c9bb2fe50dfce9 recipient=0x6c5D415a95294B33601DAa53877b8DEF3ef325DA
INFO [07-31|17:12:24] Submitted transaction                    fullhash=0xd06c02544b01cde5c7ad22ca686c190c1663d8a252aab0625efdbd2e5dc04a07 recipient=0x5E37EE97E9f6305F5D48889fa21e6C2E0B4164d6
INFO [07-31|17:12:24] Submitted transaction                    fullhash=0xe62ca5ada4bf5859a46b647bcff769fbcf88c835acecb01aabc5a5742207209e recipient=0x2f9beA013c93dfe5a2E8D0331EF117a0413a683d
INFO [07-31|17:12:25] Submitted transaction                    fullhash=0xef495a0806a2b83e6d3088c0710d2a03661a95ef2c56482d30377e5f283c973f recipient=0x3e4170335b8Fb0Ef1aE5Cdc43F73ECdC065C70a2
INFO [07-31|17:12:25] Submitted transaction                    fullhash=0x348c89056cbe9591d8fed024cd81712ff9118d584bcad44b295c998e2863ab0d recipient=0xBb77C6521Cae63eB1c82bBaD2ADC9612C4f04C0e
INFO [07-31|17:12:25] Submitted transaction                    fullhash=0x74618abc09073a53a92ce2a413793ba1ea95aa07c960065826d57a1951763027 recipient=0x0D0984F47Ca68cb8c1E8bA0431682cA872070af6
INFO [07-31|17:12:26] Submitted transaction                    fullhash=0x8119aed69b8d74c28defe711eeb7e7cfb87874a7370f916c5b4310d4dfe181ec recipient=0xBe860B2043C31c03297F2F645d87BFBA1E8E9A4C
INFO [07-31|17:12:26] Successfully sealed new block            number=76185 hash=724603…fe2397
INFO [07-31|17:12:26] 🔗 block reached canonical chain          number=76180 hash=4c65fe…9a11dc
INFO [07-31|17:12:26] 🔨 mined potential block                  number=76185 hash=724603…fe2397
ERROR[07-31|17:12:26] Failed to create mining context          err="missing trie node ff354885bd551ad1f5dfa42e1ca05298fd035b33c93ef0a16f8f1ec1174c8f8d (path )"
ERROR[07-31|17:12:26] Failed to reset txpool state             err="missing trie node ff354885bd551ad1f5dfa42e1ca05298fd035b33c93ef0a16f8f1ec1174c8f8d (path )"
INFO [07-31|17:12:26] Submitted transaction                    fullhash=0x09eced644b532181e22e6b09fbb6253c134a4b00a76a4806200e2e49b589c180 recipient=0xa1836c7cA2181fFAdBDe6BF1A9d5bb6AB3148095
````

**Comment by karalabe** [comment]
That's a 14 release old release. Please use a fresh version. Btw, it seems as if your db is corrupted.
