### ISSUE TITLE
Puppeth (for PoA bootnode) created docker image restarting always

### ISSUE THREAD

**Issue by karthika-glance** [ethereum/go-ethereum#17434]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
Please specify a network name to administer (no spaces or hyphens, please)
> testpuppeth3 

Sweet, you can set this via --network=testpuppeth3 next time!

INFO [08-17|20:52:24.891] Administering Ethereum network           name=testpuppeth3
WARN [08-17|20:52:24.891] No previous configurations found         path=/home/ubuntu/.puppeth/testpuppeth3

What would you like to do? (default = stats)
 1. Show network stats
 2. Configure new genesis
 3. Track new remote server
 4. Deploy network components
> 2

Which consensus engine to use? (default = clique)
 1. Ethash - proof-of-work
 2. Clique - proof-of-authority
> 2

How many seconds should blocks take? (default = 15)
> 5

Which accounts are allowed to seal? (mandatory at least one)
> 0x3cb359018604bffd282dca629aa8e4b014914331
> 0x2caa5105bedfe1e80aa1e89e5177867bf7f2fa76
> 0x

Which accounts should be pre-funded? (advisable at least one)
> 0x3cb359018604bffd282dca629aa8e4b014914331
> 0x2caa5105bedfe1e80aa1e89e5177867bf7f2fa76
> 0x581e6818f835c6b8eec86e32bd034bb69bb68e00
> 0x3d186495787760f803a64163190ec3846dd49c51
> 0x329fbc1b7db2808a9f103b5d86d2555f6831eff0
> 0x

Specify your chain/network ID if you want an explicit one (default = random)
> 700
INFO [08-17|20:53:24.859] Configured new genesis block 

What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
> 4

What would you like to deploy? (recommended order)
 1. Ethstats  - Network monitoring tool
 2. Bootnode  - Entry point of the network
 3. Sealer    - Full node minting new blocks
 4. Explorer  - Chain analysis webservice (ethash only)
 5. Wallet    - Browser wallet for quick sends
 6. Faucet    - Crypto faucet to give away funds
 7. Dashboard - Website listing above web-services
> 1

Which server do you want to interact with?
 1. Connect another server
> 1

Please enter remote server's address:
> x.x.x.x

The authenticity of host 'x.x.x.x:22 (x.x.x.x:22)' can't be established.
SSH key fingerprint is df:89:2f:60:5a:19:00:18:1d:8f:42:74:b8:a7:38:8e [MD5]
Are you sure you want to continue connecting (yes/no)? yes

Which port should ethstats listen on? (default = 80)
> 8080

Allow sharing the port with other services (y/n)? (default = yes)
> n

What should be the secret password for the API? (must not be empty)
> PrivateTest-DockerNode2
Creating network "testpuppeth3_default" with the default driver
Building ethstats
Step 1/2 : FROM puppeth/ethstats:latest
 ---> fb62abe59cb2
Step 2/2 : RUN echo 'module.exports = {trusted: ["x.x.x.x"], banned: [], reserved: ["yournode"]};' > lib/utils/config.js
 ---> Using cache
 ---> aba8e97485df
Successfully built aba8e97485df
Successfully tagged testpuppeth3/ethstats:latest
Creating testpuppeth3_ethstats_1
INFO [08-17|20:54:29.020] Starting remote server health-check      server=x.x.x.x
+--------------+--------------+----------+-----------------------+-------------------------+
|    SERVER    |   ADDRESS    | SERVICE  |        CONFIG         |          VALUE          |
+--------------+--------------+----------+-----------------------+-------------------------+
| x.x.x.x | x.x.x.x | ethstats | Banned addresses      | []                      |
|              |              |          | Login secret          | PrivateTest-DockerNode2 |
|              |              |          | Website address       | x.x.x.x            |
|              |              |          | Website listener port | 8080                    |
+--------------+--------------+----------+-----------------------+-------------------------+
What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Manage tracked machines
 4. Manage network components
> 4

 1. Tear down Ethstats on x.x.x.x
 2. Deploy new network component
> 2

What would you like to deploy? (recommended order)
 1. Ethstats  - Network monitoring tool
 2. Bootnode  - Entry point of the network
 3. Sealer    - Full node minting new blocks
 4. Explorer  - Chain analysis webservice (ethash only)
 5. Wallet    - Browser wallet for quick sends
 6. Faucet    - Crypto faucet to give away funds
 7. Dashboard - Website listing above web-services
> 2

Which server do you want to interact with?
 1. x.x.x.x
 2. Connect another server
> 1

Where should data be stored on the remote machine?
> /home/ubuntu/testpuppeth3/bootnode   

Which TCP/UDP port to listen on? (default = 30303)
> 30305

How many peers to allow connecting? (default = 512)
> 

How many light peers to allow connecting? (default = 256)
> 
What should the node be called on the stats page?
> testpuppeth3_bootnode
Found orphan containers (testpuppeth3_ethstats_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building bootnode
Step 1/4 : FROM ethereum/client-go:latest
 ---> 985900870511
Step 2/4 : ADD genesis.json /genesis.json
 ---> 5e41a4c0a8f2
Step 3/4 : RUN   echo 'geth --cache 512 init /genesis.json' > geth.sh && 	echo $'geth --networkid 700 --cache 512 --port 30305 --maxpeers 512 --lightpeers=256 --lightserv=50 --ethstats \'testpuppeth3_bootnode:PrivateTest-DockerNode2@x.x.x.x:8080\'    --targetgaslimit 0 --gasprice 0' >> geth.sh
 ---> Running in 56bd4b9d6e26
Removing intermediate container 56bd4b9d6e26
 ---> b13cde356c8d
Step 4/4 : ENTRYPOINT ["/bin/sh", "geth.sh"]
 ---> Running in 6ff777398881
Removing intermediate container 6ff777398881
 ---> 2f3e2408fbf6
Successfully built 2f3e2408fbf6
Successfully tagged testpuppeth3/bootnode:latest
Creating testpuppeth3_bootnode_1
INFO [08-17|20:56:02.659] Waiting for node to finish booting 
INFO [08-17|20:56:05.659] Starting remote server health-check      server=13.58.151.81
+--------------+--------------+----------+-----------------------+-------------------------+
|    SERVER    |   ADDRESS    | SERVICE  |        CONFIG         |          VALUE          |
+--------------+--------------+----------+-----------------------+-------------------------+
| x.x.x.x | x.x.x.x | bootnode | offline               | service unreachable     |
|              |              |          | --------------------- | ----------------------- |
|              |              | ethstats | Banned addresses      | []                      |
|              |              |          | Login secret          | PrivateTest-DockerNode2 |
|              |              |          | Website address       | x.x.x.x            |
|              |              |          | Website listener port | 8080                    |
+--------------+--------------+----------+-----------------------+-------------------------+
#### Actual behaviour
On the server-side @x.x.x.x
 $ docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS                          PORTS                    NAMES
76cdd0a6e2cd        testpuppeth3/bootnode   "/bin/sh geth.sh"   11 minutes ago      Restarting (2) 11 seconds ago                            testpuppeth3_bootnode_1
08b10ae8081f        testpuppeth3/ethstats   "npm start"         21 minutes ago      Up 21 minutes                   0.0.0.0:8080->3000/tcp   testpuppeth3_ethstats_1
****Few Minutes Later...*****
$docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS                          PORTS                    NAMES
76cdd0a6e2cd        testpuppeth3/bootnode   "/bin/sh geth.sh"   24 minutes ago      Restarting (2) 10 seconds ago                            testpuppeth3_bootnode_1
08b10ae8081f        testpuppeth3/ethstats   "npm start"         34 minutes ago      Up 34 minutes 
#### Backtrace

````
[backtrace]
````
1. I get the same behaviour for creating sealer nodes on another server. 
2. Why does the boot node or the seal node docker container issued by puppeth for PoA setup crashes and is in an infinite loop to restart?

Am I doing anything wrong here? Did I get the eth-stats setup right?

Please help, thanks
Karthika

**Comment by karthika-glance** [comment]
I am using gethv1.8.12 thanks again!

**Comment by smalaichami** [comment]
This may be useful for you....
https://hackernoon.com/setup-your-own-private-proof-of-authority-ethereum-network-with-geth-9a0a3750cda8

**Comment by karthika-glance** [comment]
I have been trying to setup this one many times so please ignore the container name - might differ: But here is the output of the docker logs for the bootnode:

***********log start**************
**2018-08-20T15:50:49.371173789Z goroutine 116 [running]:
2018-08-20T15:50:49.371177310Z github.com/ethereum/go-ethereum/les.(*LesOdr).ChtIndexer(...)
2018-08-20T15:50:49.371181017Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/odr.go:63
2018-08-20T15:50:49.371184896Z github.com/ethereum/go-ethereum/les.(*ProtocolManager).NodeInfo(0xc420122ff0, 0xc420030480)
2018-08-20T15:50:49.371188402Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:1224 +0xc4
2018-08-20T15:50:49.371191721Z github.com/ethereum/go-ethereum/les.NewProtocolManager.func2(0xe03f00, 0xc4211777a0)
2018-08-20T15:50:49.371194968Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/handler.go:192 +0x2a
2018-08-20T15:50:49.371198277Z github.com/ethereum/go-ethereum/p2p.(*Server).NodeInfo(0xc420134a00, 0xffffffffffffffff)
2018-08-20T15:50:49.371201582Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:1001 +0x389
2018-08-20T15:50:49.371204934Z github.com/ethereum/go-ethereum/ethstats.(*Service).login(0xc4203aff80, 0xc4201b6510, 0x0, 0x0)
2018-08-20T15:50:49.371208206Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:373 +0x43
2018-08-20T15:50:49.371211606Z github.com/ethereum/go-ethereum/ethstats.(*Service).loop(0xc4203aff80)
2018-08-20T15:50:49.371214849Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:227 +0x558
2018-08-20T15:50:49.371228718Z created by github.com/ethereum/go-ethereum/ethstats.(*Service).Start
2018-08-20T15:50:49.371232448Z 	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:123 +0x57
2018-08-20T15:51:49.729712382Z INFO [08-20|15:51:49.729] Maximum peer count                       ETH=25 LES=0 total=25
2018-08-20T15:51:49.730034216Z INFO [08-20|15:51:49.729] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=16 handles=16
2018-08-20T15:51:49.748556741Z INFO [08-20|15:51:49.748] Persisted trie from memory database      nodes=363 size=53.29kB time=1.749024ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
2018-08-20T15:51:49.748875265Z INFO [08-20|15:51:49.748] Successfully wrote genesis state         database=chaindata                      hash=009939…7afc79
2018-08-20T15:51:49.748887567Z INFO [08-20|15:51:49.748] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=16 handles=16
2018-08-20T15:51:49.766560782Z INFO [08-20|15:51:49.766] Persisted trie from memory database      nodes=363 size=53.29kB time=1.178704ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
2018-08-20T15:51:49.767298946Z INFO [08-20|15:51:49.767] Successfully wrote genesis state         database=lightchaindata                      hash=009939…7afc79
2018-08-20T15:51:49.802773137Z INFO [08-20|15:51:49.802] Maximum peer count                       ETH=256 LES=256 total=512
2018-08-20T15:51:49.803281716Z INFO [08-20|15:51:49.803] Starting peer-to-peer node               instance=Geth/v1.8.14-unstable-2cdf6ee7/linux-amd64/go1.10.3
2018-08-20T15:51:49.803296145Z INFO [08-20|15:51:49.803] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=384 handles=1024
2018-08-20T15:51:49.814736703Z INFO [08-20|15:51:49.814] Initialised chain configuration          config="{ChainID: 2523 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}"
2018-08-20T15:51:49.814902464Z INFO [08-20|15:51:49.814] Initialising Ethereum protocol           versions="[63 62]" network=2523
2018-08-20T15:51:49.815807021Z INFO [08-20|15:51:49.815] Loaded most recent local header          number=0 hash=009939…7afc79 td=1
2018-08-20T15:51:49.815821480Z INFO [08-20|15:51:49.815] Loaded most recent local full block      number=0 hash=009939…7afc79 td=1
2018-08-20T15:51:49.815826370Z INFO [08-20|15:51:49.815] Loaded most recent local fast block      number=0 hash=009939…7afc79 td=1
2018-08-20T15:51:49.815974510Z INFO [08-20|15:51:49.815] Loaded local transaction journal         transactions=0 dropped=0
2018-08-20T15:51:49.816024961Z INFO [08-20|15:51:49.815] Regenerated local transaction journal    transactions=0 accounts=0
2018-08-20T15:51:49.816362450Z INFO [08-20|15:51:49.816] Starting P2P networking 
2018-08-20T15:51:51.928104985Z INFO [08-20|15:51:51.927] UDP listener up                          self=enode://f10abaca3b96a27d9cd424ad5b10842d21557049265a92bcf8ab259f95793907aacea9f10810b6bff34aec619759fd50e27e835158d6de8c931849480d7a2637@[::]:30305
2018-08-20T15:51:51.929920591Z INFO [08-20|15:51:51.929] UDP listener up                          net=enode://f10abaca3b96a27d9cd424ad5b10842d21557049265a92bcf8ab259f95793907aacea9f10810b6bff34aec619759fd50e27e835158d6de8c931849480d7a2637@[::]:30305
2018-08-20T15:51:51.932268022Z INFO [08-20|15:51:51.932] Stats daemon started 
2018-08-20T15:51:51.933760347Z INFO [08-20|15:51:51.933] IPC endpoint opened                      url=/root/.ethereum/geth.ipc
2018-08-20T15:51:51.933899877Z INFO [08-20|15:51:51.933] RLPx listener up                         self=enode://f10abaca3b96a27d9cd424ad5b10842d21557049265a92bcf8ab259f95793907aacea9f10810b6bff34aec619759fd50e27e835158d6de8c931849480d7a2637@[::]:30305
2018-08-20T15:51:51.934419296Z INFO [08-20|15:51:51.934] Starting topic registration              topic=LES2@009939c30c3e78d0
2018-08-20T15:51:51.939792462Z panic: runtime error: invalid memory address or nil pointer dereference
2018-08-20T15:51:51.939811283Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae39d4]**

**********log end************

1. should I be running a normal or a sealer node before initiating the bootnode or its deployment?
2. I want the boot nodes and ethstats on one AWS server while the sealers and normal nodes across other AWS servers. It will be a distributed infrastructure, (eventually secured). Should I keep in mind something?


Thanks for your reply here. 
Karthika

**Comment by karthika-glance** [comment]
For the trial which this log is based on, I used gethv1.8.14
I have the same problems for gethv1.8.12 too. Thanks!

**Comment by karthika-glance** [comment]
Also, does it matter if my different AWS servers have different versions of geth , for e.g. one has v1.8.14 and the other has gethv1.8.12

**Comment by karthika-glance** [comment]
Any leads on how to tackle this restart conditions?

**Comment by rjl493456442** [comment]
@karthika-glance Hi, there is a panic in your bootnode(unfortunately there is specific reason for the panic in your log). 

First for your questions:
1. should I be running a normal or a sealer node before initiating the bootnode or its deployment?
> No, you are recommanded to deploy bootnode first

2. I want the boot nodes and ethstats on one AWS server while the sealers and normal nodes across other AWS servers. It will be a distributed infrastructure, (eventually secured). Should I keep in mind something?
> It is allowed to deploy different components on the different server.

4. Does it matter if my different AWS servers have different versions of geth , for e.g. one has v1.8.14 and the other has gethv1.8.12
> It is compatible.

Can you try with latest version and check again whether there still some issues? If so, please mind to capture the docker log which start with 

```
2018-08-20T15:51:51.939792462Z panic: runtime error: invalid memory address or nil pointer dereference
2018-08-20T15:51:51.939811283Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae39d4]
```

**Comment by adamschmideg** [comment]
I assume the problem has been fixed in the newer version. If it persists, please open a new issue.
