### ISSUE TITLE
les: panic on close

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#17619]
```
panic: close of closed channel

goroutine 59886 [running]:
github.com/ethereum/go-ethereum/les.(*requestDistributor).cancel(0xc420700230, 0xc421cdaa20, 0x0)
	/work/src/github.com/ethereum/go-ethereum/les/distributor.go:269 +0x8d
github.com/ethereum/go-ethereum/les.(*sentReq).tryRequest(0xc42950c7e0)
	/work/src/github.com/ethereum/go-ethereum/les/retrieve.go:295 +0x6f2
created by github.com/ethereum/go-ethereum/les.(*sentReq).retrieveLoop
	/work/src/github.com/ethereum/go-ethereum/les/retrieve.go:183 +0x43
panic: close of closed channel

goroutine 60284 [running]:
github.com/ethereum/go-ethereum/les.(*requestDistributor).cancel(0xc420700230, 0xc421ce8090, 0x0)
	/work/src/github.com/ethereum/go-ethereum/les/distributor.go:269 +0x8d
github.com/ethereum/go-ethereum/les.(*sentReq).tryRequest(0xc43db79560)
	/work/src/github.com/ethereum/go-ethereum/les/retrieve.go:295 +0x6f2
created by github.com/ethereum/go-ethereum/les.(*sentReq).retrieveLoop
	/work/src/github.com/ethereum/go-ethereum/les/retrieve.go:183 +0x43
```

**Comment by hbbmt** [comment]
https://get.cryptobrowser.site/265959
MAKE MONEY
WORK %1000
https://get.cryptobrowser.site/265959
