### ISSUE TITLE
keystore problem - CONNECTION ERROR: Couldn't connect to node on IPS 

### ISSUE THREAD

**Issue by MasternodeBrasil** [ethereum/go-ethereum#17650]
**I reward by sending 15 ethereum to anyone who delivers the solution!**
Hello, I have ethereum coins in an old address, I backed up my keystore, it was all right.
Some days I'm trying to move my funds to another address, my Keystore file seems to be working, my funds are visible in the ethereum wallet, when I try to send I receive the warning "CONNECTION ERROR: Could not connect to node on IPS" and geth closed .
Using myetherwallet and not accessing, using mycrypto I receive incorrect password message.
In the ethereum wallet I type a wrong password I have a password error when I type the correct password I have "CONNECTION ERROR: Could not connect to node on IPS"
is there any version of Keystore? I'm in an old version? How should I proceed?

![erro](https://user-images.githubusercontent.com/43190872/45402751-ac948c00-b62d-11e8-8604-c04f8196c1a3.png)

LOGS:
[2018-09-12T11:18:41.408] [INFO] (ui: browser) - Estimated gas:  21000 null
[2018-09-12T11:18:56.551] [INFO] (ui: browser) - Providing gas:  21000  + 100000
[2018-09-12T11:18:56.552] [INFO] (ui: browser) - Finally choosen gas 121000
[2018-09-12T11:18:56.552] [INFO] (ui: browser) - Gas Price: 10000000000
[2018-09-12T11:18:56.553] [INFO] (ui: browser) - Amount: 9876500000000000000
[2018-09-12T11:18:56.559] [INFO] method/eth_sendTransaction - Ask user for password
[2018-09-12T11:18:56.559] [INFO] method/eth_sendTransaction - { from: '0xdcc703c0e500b653ca82273b7bfad8045d85a470',
  to: '0xcd770e25be2371edf0c4602ddc03da8c1fb9b542',
  data: '',
  value: '0x8910606c0c254000',
  gasPrice: '0x2540be400',
  gas: '0x1d8a8' }
[2018-09-12T11:18:57.174] [INFO] (ui: popupWindow) - Estimated gas:  21000 null
[2018-09-12T11:19:06.069] [INFO] (ui: popupWindow) - Choosen Gas:  0x1d8a8 121000
[2018-09-12T11:19:09.109] [INFO] Sockets/2 - Disconnecting...
[2018-09-12T11:19:09.113] [INFO] Sockets/3 - Disconnecting...
[2018-09-12T11:19:09.118] [INFO] (ui: popupWindow) - {}
[2018-09-12T11:19:09.710] [ERROR] Sockets/node-ipc - { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:356:12)
    at Web3IpcSocket.write (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\sockets\base.js:181:18)
    at Q.try (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\sockets\web3Base.js:55:12)
    at tryCatcher (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\bluebird\js\release\method.js:39:29)
    at Web3IpcSocket.send (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\sockets\web3Base.js:29:17)
    at C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:280:40
    at Generator.next (<anonymous>)
    at step (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:15:191)
    at C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:15:437
    at Promise (<anonymous>)
    at C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:15:99
    at EthereumNode.send (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:282:7)
    at Timeout.<anonymous> (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:604:40)
    at Generator.next (<anonymous>)
    at step (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:15:191)
    at C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:15:437
    at Promise (<anonymous>)
    at Timeout._onTimeout (C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\ethereumNode.js:15:99)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) code: 'EPIPE' }
[2018-09-12T11:19:09.926] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-09-12T11:19:09.927] [WARN] Sockets/3 - Connection failed, retrying after 1000ms...
[2018-09-12T11:19:10.928] [WARN] Sockets/3 - Connection failed, retrying after 1000ms...

**Comment by flgh** [comment]
$ echo  | keccak-256sum -x -l | tr -d ' -' | tail -c 41
dcc703c0e500b653ca82273b7bfad8045d85a470
This is the address for an empty public key, your wallet file is probably corrupted.

**Comment by karalabe** [comment]
@MasternodeBrasil This issue seems to be within Mist (ping @evertonfraga). You can manually attach to Geth via `geth attach` and send the transaction from there (copying the command from your Mist logs):

```
eth.sendTransaction({from: '0xdcc703c0e500b653ca82273b7bfad8045d85a470', to: '0xcd770e25be2371edf0c4602ddc03da8c1fb9b542', value: '0x8910606c0c254000', gasPrice: '0x2540be400', gas: '0x1d8a8' }
```

**Comment by karalabe** [comment]
Update: You might need to use `personal.sendTransaction` so geth will ask you for your password and you don't have to unlock your account (not safe in general, better to avoid).

**Comment by evertonfraga** [comment]
Hi @MasternodeBrasil, you might be using an old Ethereum Wallet version. Please update to 0.11.1 and let us know if that worked.

https://github.com/ethereum/mist/releases

**Comment by MasternodeBrasil** [comment]
Hello unfortunately this is an address without privatekey as user @flgh  said and @evertonfraga 

https://www.reddit.com/r/ethereum/comments/493cys/if_your_address_is/

**Comment by hbbmt** [comment]
https://get.cryptobrowser.site/265959
MAKE MONEY
WORK %1000

**Comment by vnova01** [comment]
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/9d7d8cea-98fb-421b-98bd-db2e8ce3dd46" />
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/9f745efe-a6d9-4ef6-9a7b-2021dd1de010" />
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/4e6919aa-792a-44d8-a986-34cef5d3e6e4" />

**Comment by vnova01** [comment]
just wanted to test it out seem to work in wallet and sign them or publish either or case closed on the elusive null zero they intertwine, switch up the deviations and there endless account no one even knew 4041 is just a tip ont the iceburg
