### ISSUE TITLE
geth cannot connect on rinkeby!

### ISSUE THREAD

**Issue by pikejun** [ethereum/go-ethereum#17777]
Hi there, when I connected to rinkeby the error is follow:

INFO [09-28|10:41:09] Maximum peer count                       ETH=30 LES=0 total=30
INFO [09-28|10:41:09] Starting peer-to-peer node               instance=Geth/tdog001/v1.8.9-unstable-55b579e0/linux-amd64/go1.10
INFO [09-28|10:41:09] Allocated cache and file handles         database=/eth/rinkebydata/geth/chaindata cache=384 handles=1024
INFO [09-28|10:41:09] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: <nil> Engine: clique}"
INFO [09-28|10:41:09] Initialising Ethereum protocol           versions="[63 62]" network=4
WARN [09-28|10:41:09] Head block missing, resetting chain      hash=8985da…301132
WARN [09-28|10:41:09] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).CurrentBlock(...)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:342
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0xc4208d0000, 0x0, 0x0, 0x0)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:285 +0xb5d
github.com/ethereum/go-ethereum/core.(*BlockChain).ResetWithGenesisBlock(0xc4208d0000, 0xc4208be2d0, 0x0, 0x0)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:398 +0x54
github.com/ethereum/go-ethereum/core.(*BlockChain).Reset(0xc4208d0000, 0x23, 0xc420692220)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:391 +0x37
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc4208d0000, 0x0, 0xc4208be2d0)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:217 +0x1213
github.com/ethereum/go-ethereum/core.NewBlockChain(0x10a31a0, 0xc4202aaf20, 0xc4204a8140, 0xc42020c280, 0x10a5880, 0xc4204beaf0, 0x0, 0x0, 0x0, 0x0, ...)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:177 +0x5e3
github.com/ethereum/go-ethereum/eth.New(0xc4204dd620, 0xc420131000, 0xec8ce0, 0xc4201d1838, 0x426558)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:149 +0x5fd
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc4204dd620, 0xc4204d6750, 0xc4201d1b28, 0xc4204dd5e0, 0x2)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1132 +0x3d
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc4204d0780, 0x0, 0x0)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:182 +0x42c
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc4204d0780)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc420212dc0, 0xc4204d0780)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:229 +0x81
main.geth(0xc420212dc0, 0xfa24f8, 0xb2d05e00)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:217 +0x43
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xd97420, 0xfa3a08, 0xc420212dc0, 0xc420212dc0, 0xc4201d1f48)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4201fd040, 0xc420030160, 0x16, 0x16, 0x0, 0x0)
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee
main.main()
        /eth/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:206 +0x55

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information
Geth
Version: 1.8.9-unstable
Git Commit: 55b579e02ce6f374bf81061269eabde0d82ae567
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=/root/go
GOROOT=/usr/local/go

**Comment by pikejun** [comment]
after update geth the issue still exist!
Geth
Version: 1.8.17-unstable
Git Commit: e39a9b3480af0ac8044294f46e0e9e4c3948d23c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=/root/go
GOROOT=/usr/local/go

INFO [09-28|13:58:19.408] Maximum peer count                       ETH=30 LES=0 total=30
INFO [09-28|13:58:19.413] Starting peer-to-peer node               instance=Geth/tdog001/v1.8.17-unstable-e39a9b34/linux-amd64/go1.10
INFO [09-28|13:58:19.413] Allocated cache and file handles         database=/eth/rinkebydata/geth/chaindata cache=384 handles=1024
INFO [09-28|13:58:19.575] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: <nil> Engine: clique}"
INFO [09-28|13:58:19.575] Initialising Ethereum protocol           versions="[63 62]" network=4
WARN [09-28|13:58:19.581] Head block missing, resetting chain      hash=8985da…301132
WARN [09-28|13:58:19.581] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).CurrentBlock(...)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:344
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0xc420a66000, 0x0, 0x0, 0x0)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:287 +0xb45
github.com/ethereum/go-ethereum/core.(*BlockChain).ResetWithGenesisBlock(0xc420a66000, 0xc4202c0240, 0x0, 0x0)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:400 +0x54
github.com/ethereum/go-ethereum/core.(*BlockChain).Reset(0xc420a66000, 0x23, 0xc4204b8098)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:393 +0x37
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc420a66000, 0x0, 0xc4202c0240)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:219 +0x1693
github.com/ethereum/go-ethereum/core.NewBlockChain(0x10ff4c0, 0xc4200ee420, 0xc4201cdfa0, 0xc42021c280, 0x1102f00, 0xc420364e70, 0x0, 0x0, 0x0, 0x0, ...)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:179 +0x5fc
github.com/ethereum/go-ethereum/eth.New(0xc4202d00e0, 0xc420231200, 0xf1c240, 0xc4204bd800, 0x426608)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:159 +0x896
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc4202d00e0, 0xc4200cb080, 0xc4204bdaf0, 0xc4202d00a0, 0x2)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1267 +0x3d
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc42022db80, 0x0, 0x0)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:182 +0x42c
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc42022db80)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc42010c160, 0xc42022db80)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:280 +0x81
main.geth(0xc42010c160, 0x0, 0x0)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:268 +0xe3
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xde1fa0, 0xff9d58, 0xc42010c160, 0xc42010c160, 0xc4204bdf48)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200d0340, 0xc420030160, 0x16, 0x16, 0x0, 0x0)
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee
main.main()
        /eth/go-ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:254 +0x55

**Comment by pikejun** [comment]
when i delete some last ldb files and delete LOG and MANIFEST-341852 and modify CURRENT file then restart geth . And it worked again!

delete file list:
-rw-r--r-- 1 root root 2122855 Sep 28 14:13 342551.ldb
-rw-r--r-- 1 root root   13385 Sep 28 14:13 342552.ldb 
-rw-r--r-- 1 root root      16 Sep 28 14:12 CURRENT.bak
-rw-r--r-- 1 root root       0 Sep 28 14:09 LOCK
-rw-r--r-- 1 root root  356535 Sep 28 14:15 LOG
-rw-r--r-- 1 root root 1048635 Sep 28 14:15 LOG.old
-rw-r--r-- 1 root root 3521726 Sep 28 14:15 MANIFEST-341852
