### ISSUE TITLE
can not connect the node that running in the docker

### ISSUE THREAD

**Issue by Herry143** [ethereum/go-ethereum#17898]
1.I have run the docker image successfully.use the command
```
"docker run -it -p 8545:8545 -p 30303:30303 -v /Users/admin/Desktop/docker-build/eth_blockdata:/root/.ethereum ethereum/client-go  --rpc --rpcaddr "0.0.0.0"";
```
2.I want to use the web3's function in my code to getBalance of address
```
const Web3 = require("web3");
var web3 = new Web3(new Web3.providers.HttpProvider("http://172.17.0.2:8545"))
var address="0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98"
web3.eth.getBalance(address, function (err, balance) {
    if (err) {
        console.log(err)
    }
    console.log("hahah");
    console.log(balance)
    
});
(ps:172.17.0.2 is the ip of docker container)
```
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
return the balance

#### Actual behaviour
```
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/admin/Desktop/eth_api/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/admin/Desktop/eth_api/node_modules/web3-providers-http/src/index.js:87:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/admin/Desktop/eth_api/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
```

#### Backtrace

````
[backtrace]
````

**Comment by charlesgdalton** [comment]
Do you remember how you fixed this?
