### ISSUE TITLE
trie/database on insert - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hello2mao** [ethereum/go-ethereum#18094]
Related issue  #17280, but is was closed.

#### System information

Geth version: v1.8.12
OS & Version: Linux

#### Expected behaviour
stable env

#### Actual behaviour
multiple nodes are crashing

#### Steps to reproduce the behaviour
private PoA net
submit 10000+ tx
it will crash

#### Backtrace

````
BUG[11-14|05:07:28.402] VM returned with error                   err="evm: execution reverted"
DEBUG[11-14|05:07:28.402] VM returned with error                   err="evm: execution reverted"
DEBUG[11-14|05:07:28.403] VM returned with error                   err="evm: execution reverted"
DEBUG[11-14|05:07:28.403] VM returned with error                   err="evm: execution reverted"
DEBUG[11-14|05:07:28.404] VM returned with error                   err="evm: execution reverted"
DEBUG[11-14|05:07:28.404] VM returned with error                   err="evm: execution reverted"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x69aff2]

goroutine 264346 [running]:
github.com/ethereum/go-ethereum/trie.(*Database).insert(0xc420146780, 0xebad0ccc4221d0e2, 0x3c15568f34947bfc, 0x99928b562f5398ce, 0x7cbba04dc4e683de, 0xc438339d40, 0x21, 0x226, 0x10c2220, 0xc434a3a820)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/database.go:316 +0x3b2
github.com/ethereum/go-ethereum/trie.(*hasher).store(0xc42a26a140, 0x10c2220, 0xc434a3a820, 0xc420146780, 0x10c2200, 0xc434a3a820, 0x10c2220, 0xc434a3a870, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:190 +0x2a0
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc42a26a140, 0x10c2220, 0xc42b3d4b90, 0xc420146780, 0x0, 0x10c4020, 0xc42ff1f800, 0x10c4020, 0xc42ff1f800, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:98 +0x17a
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc42a26a140, 0x10c21a0, 0xc428990780, 0xc420146780, 0x10c4001, 0x10c4020, 0xc434ab7180, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18f
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc42a26a140, 0x10c21a0, 0xc428990780, 0xc420146780, 0xc420042500, 0x10c4020, 0xc434ab7180, 0x10c4020, 0xc434ab7180, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x10f
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc42a26a140, 0x10c21a0, 0xc428990500, 0xc420146780, 0x1, 0x10, 0xc4209a4210, 0xc4577e15c8, 0x57f7e6, 0xda4100)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18f
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc42a26a140, 0x10c21a0, 0xc428990500, 0xc420146780, 0xc420042500, 0x10c4020, 0xc4281a6f00, 0x10c4020, 0xc4281a6f20, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x10f
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc42a26a140, 0x10c21a0, 0xc428990140, 0xc420146780, 0x1, 0x10, 0xc4209a4210, 0xc4577e17d8, 0x57f7e6, 0xda4100)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18f
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc42a26a140, 0x10c21a0, 0xc428990140, 0xc420146780, 0x10c4000, 0x10c4020, 0xc4281a6c40, 0x10c4020, 0xc4281a6c60, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x10f
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc42a26a140, 0x10c21a0, 0xc4341cbe00, 0xc420146780, 0x1b48501, 0xc48ab46a2b, 0x21, 0x13c35d5, 0xc435181e80, 0x2a)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18f
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc42a26a140, 0x10c21a0, 0xc4341cbe00, 0xc420146780, 0x0, 0x32, 0x456501, 0x6b1df, 0xd9bd00, 0x1, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x10f
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc42a26a140, 0x10c21a0, 0xc4341cb900, 0xc420146780, 0x418b01, 0xc4200aa7d8, 0xc4200aa780, 0x42665c, 0x7ff71ff60cd8, 0x18)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18f
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc42a26a140, 0x10c21a0, 0xc4341cb900, 0xc420146780, 0x101, 0xe71d60, 0xc4577e1d01, 0xc4275265a0, 0xc4577e1d50, 0xc4577e1d90, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x10f
github.com/ethereum/go-ethereum/trie.(*Trie).hashRoot(0xc44a5ca380, 0xc420146780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:475 +0xe6
github.com/ethereum/go-ethereum/trie.(*Trie).Commit(0xc44a5ca380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc45f34f0ba)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:460 +0x71
github.com/ethereum/go-ethereum/trie.(*SecureTrie).Commit(0xc44a5ca380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a2889eedc64cb99, 0xc4577e2078)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:155 +0x49e
github.com/ethereum/go-ethereum/core/state.(*stateObject).CommitTrie(0xc43ca1e380, 0x10c8220, 0xc42027f890, 0xc43c21e158, 0xc4319afd01)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/state_object.go:229 +0x9a
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit(0xc43ca1e000, 0xc4577e2501, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:603 +0x31e
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlockWithState(0xc420080000, 0xc4285abd40, 0xc42258e200, 0x30, 0x40, 0xc43ca1e000, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:902 +0x5e8
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc420080000, 0xc4202287a8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1161 +0x1853
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc420080000, 0xc4202287a8, 0x1, 0x1, 0xc4202287a8, 0x8, 0x8)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:999 +0x67
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func6(0xc4202287a8, 0x1, 0x1, 0x1b1ff01, 0xc464206510, 0xfbaa1a42e87f6596)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:177 +0x329
github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert.func1(0xc4200b7ba0, 0xd5d8b2694e44fa78, 0x74445326920c440e, 0xfbaa1a42e87f6596, 0xa220638fc37a0361, 0xc4285abd40, 0xc4348f16c0, 0x10)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:669 +0x53b
created by github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:643 +0x317
````
Another:
````
TRACE[11-16|09:30:35.704] << NEIGHBORS/v4                          addr=10.244.104.40:30303  err=nil
DEBUG[11-16|09:30:36.005] Queued propagated block                  peer=487e199d711345b9 number=36015 hash=b90980…b6a6bb queued=1
DEBUG[11-16|09:30:36.005] Importing propagated block               peer=487e199d711345b9 number=36015 hash=b90980…b6a6bb
TRACE[11-16|09:30:36.005] Propagated block                         hash=b90980…b6a6bb recipients=1 duration=923.399µs
TRACE[11-16|09:30:36.006] Propagated block                         id=c22d7a3b7a69ad4c conn=inbound number=36015 hash=b90980…b6a6bb td=72682
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x69aff2]

goroutine 4070563 [running]:
github.com/ethereum/go-ethereum/trie.(*Database).insert(0xc42035ad20, 0x6ff4ed9f5f3cdaad, 0x1cda45de4beb7f62, 0x7805a3143ae80b40, 0xdee64be70d3234c, 0xc467d83000, 0x727, 0x800, 0x10c40a0, 0xc4304d4f60)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/database.go:316 +0x3b2
github.com/ethereum/go-ethereum/trie.(*Database).InsertBlob(0xc42035ad20, 0x6ff4ed9f5f3cdaad, 0x1cda45de4beb7f62, 0x7805a3143ae80b40, 0xdee64be70d3234c, 0xc467d83000, 0x727, 0x800)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/database.go:287 +0x117
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit(0xc454bce380, 0xc4ac6fc501, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:599 +0x4d7
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlockWithState(0xc4202ee000, 0xc463b9a480, 0xc4203bd598, 0x1, 0x1, 0xc454bce380, 0x0, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:902 +0x5e8
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc4202ee000, 0xc4b1aee590, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1161 +0x1853
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc4202ee000, 0xc4b1aee590, 0x1, 0x1, 0xc4b1aee590, 0x8, 0x8)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:999 +0x67
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func6(0xc4b1aee590, 0x1, 0x1, 0x1b1ff01, 0xc481834000, 0x8a5ed7ed02c7cee3)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:177 +0x329
github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert.func1(0xc420269c70, 0x844845d1818009b9, 0xc37a2e01870c4926, 0x8a5ed7ed02c7cee3, 0xbba6b61d7fd8f58f, 0xc463b9a480, 0xc431230fa0, 0x10)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:669 +0x53b
created by github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:643 +0x317
````

**Comment by hello2mao** [comment]
CC: @karalabe 
Hi,  v1.8.12 still has this problem?

**Comment by hadv** [comment]
@hello2mao Could you please scroll up the output log to see is there any `out of memory` error?

**Comment by hello2mao** [comment]
> @hello2mao Could you please scroll up the output log to see is there any `out of memory` error?
No such error. My block gas limit is 209773332254395460, it is large enough.

**Comment by hadv** [comment]
> > @hello2mao Could you please scroll up the output log to see is there any `out of memory` error?
> 
> No such error. My block gas limit is 209773332254395460, it is large enough.

Okay, by the way I mentioned about the computing memory, RAM, of your node. I also have node crashed on a low performance machine that's why I'm asking about `out of memory` error.

**Comment by karalabe** [comment]
We've put in quite a few changes/tweaks into this part of the code since the .12 release. (we're at .18 as of this morning). Could you please check if the latest release still behaves like this? If yes, could you create a repro for us?

**Comment by hello2mao** [comment]
> We've put in quite a few changes/tweaks into this part of the code since the .12 release. (we're at .18 as of this morning). Could you please check if the latest release still behaves like this? If yes, could you create a repro for us?

At v1.8.17, I has this issue #18082, so I go back to  v1.8.12. -_-
I will try .18.
Thank you for your advice.

**Comment by crackcomm** [comment]
It will most likely fail at some point unless we add `db.oldest == nil || ...` in [trie/database.go line 339](https://github.com/ethereum/go-ethereum/blob/master/trie/database.go#L339).

**Comment by hello2mao** [comment]
Hi @karalabe ,could you help me check is this pr #17282 made by you fix this problem?

**Comment by holiman** [comment]
I believe this is fixed by that ^ commit. I'll close this as it's on fairly old code. Feel free to open a new ticket if it persists on latest release or master.
