### ISSUE TITLE
Mist doesn't start on OSX

### ISSUE THREAD

**Issue by frewsxcv** [ethereum/go-ethereum#181]
Just tried to build the project with Homebrew. Couldn't start Mist.

```
~ $ brew reinstall go-ethereum --HEAD
==> Reinstalling go-ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Library/Caches/Homebrew/go-ethereum--git
==> Checking out branch master
==> go env
==> go get -v -u -d github.com/ethereum/go-ethereum/ethereum
==> go get -v -u -d github.com/ethereum/go-ethereum/mist
==> mv mist src/
==> mv ethereum src/
==> go build -v ./src/ethereum
==> go build -v ./src/mist
==> mv src/mist/assets /usr/local/Cellar/go-ethereum/0.6.7-33/Resources
==> Caveats
To have launchd start go-ethereum at login:
    ln -sfv /usr/local/opt/go-ethereum/*.plist ~/Library/LaunchAgents
Then to load go-ethereum now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.go-ethereum.plist
==> Summary
🍺  /usr/local/Cellar/go-ethereum/0.6.7-33: 2100 files, 77M, built in 81 seconds
```
```
~ $ mist
2014/11/11 12:15:03 [CLI] identity created
panic: runtime error: index out of range

goroutine 22 [running]:
runtime.panic(0x4747060, 0x4c5907c)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/ethereum/eth-go.getOurIP(0x0, 0x0, 0x6b8ae08, 0xc208544800)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/ethereum/eth-go/natupnp.go:177 +0x11c
github.com/ethereum/eth-go.Discover(0x0, 0x0, 0x0, 0x0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/ethereum/eth-go/natupnp.go:85 +0x89d
github.com/ethereum/eth-go.New(0x6b897f0, 0xc208046090, 0x6b89968, 0xc20806e410, 0xc2080a8180, 0x107, 0x417e86f, 0x0, 0x0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/ethereum/eth-go/ethereum.go:106 +0x78
github.com/ethereum/go-ethereum/utils.NewEthereum(0x6b897f0, 0xc208046090, 0x6b89968, 0xc20806e410, 0xc2080a8180, 0x1, 0x47c7b00, 0x5, 0xa, 0xc208002120)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/ethereum/go-ethereum/utils/cmd.go:150 +0x7d
main.run(0x0, 0x0)
	/private/tmp/go-ethereum-UiW9sG/src/mist/main.go:45 +0x349
gopkg.in/qml%2ev1.func·002()
	/private/tmp/go-ethereum-UiW9sG/src/gopkg.in/qml.v1/bridge.go:60 +0x46
created by gopkg.in/qml%2ev1.Run
	/private/tmp/go-ethereum-UiW9sG/src/gopkg.in/qml.v1/bridge.go:62 +0x1a5

goroutine 16 [syscall]:
gopkg.in/qml%2ev1._Cfunc_applicationExec(0x472a360)
	gopkg.in/qml.v1/_obj/_cgo_defun.c:71 +0x31
gopkg.in/qml%2ev1.Run(0x4a10c40, 0x0, 0x0)
	/private/tmp/go-ethereum-UiW9sG/src/gopkg.in/qml.v1/bridge.go:63 +0x1ac
main.main()
	/private/tmp/go-ethereum-UiW9sG/src/mist/main.go:74 +0x6b

goroutine 19 [finalizer wait]:
runtime.park(0x40f3a20, 0x4c7b710, 0x4c5c4c9)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x4c7b710, 0x4c5c4c9)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 21 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 23 [chan send]:
github.com/ethereum/eth-go/ethlog.start()
	/private/tmp/go-ethereum-UiW9sG/src/github.com/ethereum/eth-go/ethlog/loggers.go:75 +0x129
created by github.com/ethereum/eth-go/ethlog.AddLogSystem
	/private/tmp/go-ethereum-UiW9sG/src/github.com/ethereum/eth-go/ethlog/loggers.go:125 +0xec

goroutine 24 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080ba2a0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:192 +0x1b4
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:222 +0x202

goroutine 25 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080226c0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:115 +0x1fa
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x476

goroutine 26 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2080226c0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0xfb
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x48e

goroutine 27 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2080226c0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:699 +0x774
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db.go:125 +0x4d0

goroutine 28 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080226c0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:646 +0x235
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x4e8

goroutine 29 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080226c0)
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x143
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/go-ethereum-UiW9sG/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x500
~ $
```

**Comment by frewsxcv** [comment]
Sorry I never got back to you; I just tried reinstalling from master and things seem to work now

**Comment by obscuren** [comment]
Develop is even better ;-)
