### ISSUE TITLE
how to uses the Genesis block to create a contact ?

### ISSUE THREAD

**Issue by liwei00wade** [ethereum/go-ethereum#18206]
type GenesisAccount struct {
		Code       *hexutil.Bytes              `json:"code,omitempty"`
		Storage    map[storageJSON]storageJSON `json:"storage,omitempty"`
		Balance    *math.HexOrDecimal256       `json:"balance" gencodec:"required"`
		Nonce      *math.HexOrDecimal64        `json:"nonce,omitempty"`
		PrivateKey *hexutil.Bytes              `json:"secretKey,omitempty"`
	}

how to define   Code and Storage in genesis.json file ?
Please give me an example or some document,Thanks .

**Comment by liwei00wade** [comment]
https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format


The accounts object maps from addresses (40-nibble strings without the 0x prefix) to objects, each with a number of allowed keys:

balance: Integer to specify the balance of the account at genesis in wei.
nonce: Integer to specify the nonce of the account at genesis.
code: 0x-prefixed hex specifying the code of the account at genesis.
storage: Object mapping hex-encoded integers for the account's storage at genesis.
builtin: Alternative to code, used to specify that the account's code is natively implemented. Value is an object with further fields:
"name": The name of the builtin code to execute as a string. e.g. "identity", "ecrecover".
"pricing": Enum to specify the cost of calling this contract.
"linear": Specify a linear cost to calling this contract. Value is an object with two fields: base which is the basic cost in Wei and is always paid; and word which is the cost per word of input, rounded up.



Who can give me an example ??

**Comment by liwei00wade** [comment]
how to  uses the Genesis block to create a contact ?

**Comment by hadv** [comment]
> how to uses the Genesis block to create a contact ?

you can compile your smart contract then put the byte code into the genesis as below

```
"cafecafecafecafecafecafecafecafecafecafe": {
"code": "0x60806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063b688a36314610051578063d66d9e1914610068575b600080fd5b34801561005d57600080fd5b5061006661007f565b005b34801561007457600080fd5b5061007d6100e7565b005b60013390806001815401808255809150509060018203906000526020600020016000909192909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b60008090505b6001805490508110156102685760018181548110151561010957fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561025b5760018080805490500381548110151561017c57fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff166001828154811015156101b657fe5b9060005260206000200160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060018080805490500381548110151561021357fe5b9060005260206000200160006101000a81549073ffffffffffffffffffffffffffffffffffffffff02191690556001805480919060019003610255919061026c565b50610269565b80806001019150506100ed565b5b50565b815481835581811115610293578183600052602060002091820191016102929190610298565b5b505050565b6102ba91905b808211156102b657600081600090555060010161029e565b5090565b905600a165627a7a723058201643c670757cdf1940e3f657b7ad97d5f76cfe82de027f5470c9b85424fd135a0029",
```

**Comment by liwei00wade** [comment]
@hadv  thank you response 

Here's the contract source:
pragma solidity ^0.4.17;

contract getAndSet {
    uint public num;
    function set(uint val){
        num = val;
    }
}


wade@wade-work:~/goWorkSpace/src/192.168.1.188/ipc/ipc-bridge/contracts$ solc --bin-runtime genesiscontract.sol 
genesiscontract.sol:5:5: Warning: No visibility specified. Defaulting to "public". 
    function set(uint val){
    ^ (Relevant source part starts here and spans across multiple lines).

======= genesiscontract.sol:getAndSet =======
Binary of the runtime part: 
6080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680634e70b1dc14604e57806360fe47b1146076575b600080fd5b348015605957600080fd5b50606060a0565b6040518082815260200191505060405180910390f35b348015608157600080fd5b50609e6004803603810190808035906020019092919050505060a6565b005b60005481565b80600081905550505600a165627a7a72305820763aaf00b5df0efb5f8e059d4149dde8eb0526fae491ddf17c69253e7a2f203d0029
wade@wade-work:~/goWorkSpace/src/192.168.1.188/ipc/ipc-bridge/contracts$ 

genesis file ---------------------------------------------

    },
    "ed9d02e382b34818e88b88a309c7fe71e65f419d": {
     "balance": "0x8", 
     "code":"0x6080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680634e70b1dc14604e57806360fe47b1146076575b600080fd5b348015605957600080fd5b50606060a0565b6040518082815260200191505060405180910390f35b348015608157600080fd5b50609e6004803603810190808035906020019092919050505060a6565b005b60005481565b80600081905550505600a165627a7a72305820763aaf00b5df0efb5f8e059d4149dde8eb0526fae491ddf17c69253e7a2f203d0029"
    },
    "176f497aa20cb01625846b2f6f4fa67d381b7e1f": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

geth console -----------------------------------------------------------------------------------------_

 getAndSetContract = eth.contract([{"constant":true,"inputs":[],"name":"num","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"val","type":"uint256"}],"name":"set","outputs":[],"type":"function"}])

 getAndSet = getAndSetContract.at("ed9d02e382b34818e88b88a309c7fe71e65f419d")


getAndSet.set(2, {gas: 1000000})



++++++++++++++++++++++++error+++++++++++++++++++++++++++++++
Error: invalid address
    at web3.js:3930:15
    at web3.js:3756:20
    at web3.js:5025:28
    at map (<native code>)
    at web3.js:5024:12
    at web3.js:5050:18
    at web3.js:5075:23
    at web3.js:4137:16
    at apply (<native code>)
    at web3.js:4223:16

**Comment by liwei00wade** [comment]
https://ethereum.stackexchange.com/questions/7707/is-it-possible-to-preload-contracts-in-the-genesis-block

**Comment by hadv** [comment]
@liwei00wade I thought that contract address in the calling method `getAndSetContract.at()` should be prefix with `0x`

**Comment by hadv** [comment]
> @hadv
> Thank you,
> I have tested contract address with prefix 0x,
> But it still return same error.

confirm that your web3js code working properly with normal deployed smart contract?

**Comment by holiman** [comment]
@hadv answered this correctly (thanks!), and there's been no activity for a long time, so I'll close this
