### ISSUE TITLE
geth v1.8.18 crashes due to concurrent map access

### ISSUE THREAD

**Issue by vjoke** [ethereum/go-ethereum#18240]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Run normally

#### Actual behaviour

Do nothing, it just crash

#### Steps to reproduce the behaviour
Run a single node to mine blocks for testing

#### Backtrace

````
fatal error: concurrent map iteration and map write

goroutine 137131 [running]:
runtime.throw(0xfc6319, 0x26)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc43a0c59a8 sp=0xc43a0c5988 pc=0x4418a5
runtime.mapiternext(0xc43a0c5db8)
	/usr/local/go/src/runtime/hashmap.go:778 +0x6f1 fp=0xc43a0c5a40 sp=0xc43a0c59a8 pc=0x41f731
runtime.mapiterinit(0xe5ffe0, 0xc421201a40, 0xc43a0c5db8)
	/usr/local/go/src/runtime/hashmap.go:768 +0x270 fp=0xc43a0c5aa8 sp=0xc43a0c5a40 pc=0x41ede0
github.com/ethereum/go-ethereum/core/state.(*StateDB).Copy(0xc42026e1c0, 0x0)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:486 +0x5b1 fp=0xc43a0c5e88 sp=0xc43a0c5aa8 pc=0x7201e1
github.com/ethereum/go-ethereum/miner.(*worker).pending(0xc4200a94a0, 0x0, 0x0)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:188 +0x125 fp=0xc43a0c5ec0 sp=0xc43a0c5e88 pc=0xa8d545
github.com/ethereum/go-ethereum/miner.(*Miner).Pending(0xc4201f2ff0, 0xc43a0c5f38, 0x440179)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/miner/miner.go:167 +0x2f fp=0xc43a0c5ee8 sp=0xc43a0c5ec0 pc=0xa8a73f
github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).StateAndHeaderByNumber(0xc4203213c0, 0x18826c0, 0xc4384f8200, 0xfffffffffffffffe, 0x1bd4540, 0x0, 0x0, 0x41a417f7e8db497b)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/eth/api_backend.go:88 +0x12e fp=0xc43a0c5f48 sp=0xc43a0c5ee8 pc=0xadda0e
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicBlockChainAPI).doCall(0xc420321460, 0x18826c0, 0xc4384f8200, 0x0, 0x0, 0x0, 0xc439380b00, 0x0, 0x0, 0x0, ...)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:617 +0x163 fp=0xc43a0c8a80 sp=0xc43a0c5f48 pc=0xa7dcd3
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicBlockChainAPI).Call(0xc420321460, 0x18826c0, 0xc4384f8200, 0x0, 0x0, 0x0, 0xc439380b00, 0x0, 0x0, 0x0, ...)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:679 +0xcc fp=0xc43a0cb390 sp=0xc43a0c8a80 pc=0xa7e5bc
runtime.call256(0xc4203d5020, 0xc42000f7a0, 0xc4384fc8f0, 0xa0000000c8)
	/usr/local/go/src/runtime/asm_amd64.s:512 +0x55 fp=0xc43a0cb4a0 sp=0xc43a0cb390 pc=0x470815
reflect.Value.call(0xc4200a4980, 0xc42000f7a0, 0x13, 0xfa2a19, 0x4, 0xc42038a720, 0x4, 0x4, 0x0, 0xc42038a720, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905 fp=0xc43a0cb778 sp=0xc43a0cb4a0 pc=0x4d1165
reflect.Value.Call(0xc4200a4980, 0xc42000f7a0, 0x13, 0xc42038a720, 0x4, 0x4, 0x2, 0x2, 0x2)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc43a0cb7e0 sp=0xc43a0cb778 pc=0x4d0744
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4201fd4a0, 0x18826c0, 0xc4384f8200, 0x1887500, 0xc4202c80a0, 0xc42038a360, 0xc4202c8110, 0x0, 0xe58240)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:312 +0x6ce fp=0xc43a0cb988 sp=0xc43a0cb7e0 pc=0x83a33e
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4201fd4a0, 0x18826c0, 0xc4384f8200, 0x1887500, 0xc4202c80a0, 0xc42038a360)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1ba fp=0xc43a0cb9f8 sp=0xc43a0cb988 pc=0x83af3a
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc4201fd4a0, 0x1882780, 0xc420562b70, 0x1887500, 0xc4202c80a0, 0xfab701, 0x1, 0x0, 0x0)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:195 +0x3b5 fp=0xc43a0cbb48 sp=0xc43a0cb9f8 pc=0x838ea5
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc4201fd4a0, 0x1882780, 0xc420562b70, 0x1887500, 0xc4202c80a0, 0x1)
	/home/wxx/go-ethereum-1.8.11/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:226 +0x65 fp=0xc43a0cbba0 sp=0xc43a0cbb48 pc=0x8397c5
````

**Comment by holiman** [comment]
The stack trace indicates that it is in fact `go-ethereum-1.8.11`, not `1.8.18`. Please verify
