### ISSUE TITLE
panic: runtime error: when export genesis for aleth without precompile-addresses

### ISSUE THREAD

**Issue by hadv** [ethereum/go-ethereum#18343]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth 1.8.20`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Can export *-aleth.json\*-parity.json\*-harmony.json genesis files even without precompile-addresses

#### Actual behaviour
Cannot export because panic error in export *-aleth.json file

#### Steps to reproduce the behaviour
export genesis json file without precompile-addresses

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x444945a]

goroutine 1 [running]:
main.(*alethGenesisSpec).setPrecompile(...)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/genesis.go:177
main.newAlethGenesisSpec(0xc000192020, 0x7, 0xc0001cc000, 0x2, 0x2, 0xc0000001a4)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/genesis.go:150 +0x79a
main.(*wizard).manageGenesis(0xc0000e2100)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_genesis.go:251 +0x8de
main.(*wizard).run(0xc0000e2100)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/wizard_intro.go:149 +0x818
main.runWizard(0xc0001069a0, 0x3, 0x4a2c9e0)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:63 +0xfc
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x44eefe0, 0x45d11e8, 0xc0001069a0, 0xc0000808a0, 0x0)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00009b040, 0xc00008c1a0, 0x1, 0x1, 0x0, 0x0)
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x59d
main.main()
	/Users/hadv/go/src/github.com/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:54 +0x24b
````

**Comment by holiman** [comment]
Seems to be fixed with https://github.com/ethereum/go-ethereum/pull/18344
