### ISSUE TITLE
Cant start geth

### ISSUE THREAD

**Issue by nany3surf** [ethereum/go-ethereum#18380]
#### System information

Geth version: `1.7.2-beta-01bf0f30`
Version: Ubuntu Server 16.04

#### Expected behaviour
Initialize geth attach

#### Actual behaviour
```You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues
index allocation went beyond available resultCache space
/home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:491
goroutine 382 [running]:
runtime/debug.Stack(0x8f, 0x0, 0x0)
    /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
    /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ethereum/go-ethereum/common.Report(0xc421a8f8b0, 0x1, 0x1)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x1f2
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc4200c5300, 0xc422d3e960, 0x78, 0xc422f4b500, 0xc4200a2e00, 0xc422f4b530, 0xc422f4b590, 0x1104d60, 0xc422e856a8, 0xc421a8f990, ...)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:491 +0x81b
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xc4200c5300, 0xc422d3e960, 0x78, 0x0, 0xc422d3e900, 0x0, 0x0)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:442 +0xf4
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies-fm(0xc422d3e960, 0x78, 0xc, 0xc, 0x4, 0x4)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:938 +0x3e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc420134820, 0x19dada0, 0xc4202095d0, 0xc42005ad80, 0xc4209d6b20, 0xc4201ce460, 0xc421a8feb0, 0xc421a8ff00, 0xc421a8fef0, 0xc421a8fee0, ...)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1110 +0x8d9
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xc420134820, 0x11c69f4, 0xc42331cf98, 0xc4254a6b00)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:937 +0x33e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0xc400000008, 0x1107218)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:482 +0x37
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc422f9f510, 0xc4224f2060, 0xc422fbade0)
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:507 +0x51
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
    /home/marcos/dev/workspace/1.8/src/github.com/alastria/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:507 +0xc7
#### BUG! PLEASE REPORT ####

**Comment by karalabe** [comment]
You seem to be using `quorum`. Please open an issue in their repo, this is `go-ethereum`. Also, we've released 21 versions since 1.7.2, so this code is ancient (2017).
