### ISSUE TITLE
Swarm Travis errors

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#18513]
New (?) travis errors from swarm
```
ok  	github.com/ethereum/go-ethereum/swarm/network/simulations/discovery	11.353s	coverage: 0.0% of statements
ERROR[01-23|18:26:50.812|swarm/network/stream/peer.go:91] Message send error, dropping peer        peer=bdcac44b0c07db54 err="write tcp 127.0.0.1:58908->127.0.0.1:34148: use of closed network connection"
ERROR[01-23|18:26:50.812|swarm/network/stream/peer.go:91] Message send error, dropping peer        peer=bdcac44b0c07db54 err="shutting down"
ERROR[01-23|18:26:50.812|swarm/network/stream/peer.go:91] Message send error, dropping peer        peer=bdcac44b0c07db54 err="shutting down"
ERROR[01-23|18:26:51.937|swarm/network/stream/peer.go:91] Message send error, dropping peer        peer=3e53362d6b7b0269 err="shutting down"
ERROR[01-23|18:27:11.961|p2p/protocols/protocol.go:235]   peer.handleIncoming                      err="Message handler error: (msg code 4): write pipe: deadline exceeded"
coverage: 76.0% of statements
panic: test timed out after 5m0s

... full panic trace ... 
```
and also
```
--- FAIL: TestHiveStatePersistance (0.12s)
    hive_test.go:112: invalid number of entries: got 6, want 5
WARN [01-23|18:27:53.755] peerpot NNSet < NeighbourhoodSize 
```
The latter is pretty easy to create locally, by adding a `time.Sleep(time.Second)` here: https://github.com/ethereum/go-ethereum/blob/master/swarm/network/hive_test.go#L105

I'll assign to Anton, please reassign as you see fit

**Comment by nonsense** [comment]
@holiman we will look into these asap.

**Comment by holiman** [comment]
New one: 
```
ERROR[01-28|14:57:26.133|swarm/network/stream/delivery.go:266] Delivery.RequestFromPeers: peer doesn't have stream cap. we should have returned at sp == nil 
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="write tcp 127.0.0.1:36496->127.0.0.1:39324: use of closed network connection"
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.918|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.919|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:35.919|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=d4e6d9214d0c75d4 err="shutting down"
ERROR[01-28|14:57:36.170|swarm/network/stream/delivery.go:266] Delivery.RequestFromPeers: peer doesn't have stream cap. we should have returned at sp == nil 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90327d]
goroutine 169 [running]:
github.com/ethereum/go-ethereum/swarm/network.(*Fetcher).doRequest(0xc0000b7900, 0xcca740, 0xc0017e19e0, 0xc0013a4600, 0xc0017e23f0, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/network/fetcher.go:307 +0x25d
github.com/ethereum/go-ethereum/swarm/network.(*Fetcher).run(0xc0000b7900, 0xcca740, 0xc0017e19e0, 0xc0017e23f0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/network/fetcher.go:231 +0x4b8
created by github.com/ethereum/go-ethereum/swarm/network.(*FetcherFactory).New
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/swarm/network/fetcher.go:114 +0x12f
FAIL	github.com/ethereum/go-ethereum/swarm/network/stream	10.105s
```

**Comment by nonsense** [comment]
@holiman yes, we are aware of this one. @janos is working on it.

**Comment by janos** [comment]
The problem with `nil pointer dereference` in delivery should be fixed in https://github.com/ethereum/go-ethereum/pull/18971 and pss timeout in https://github.com/ethereum/go-ethereum/pull/18964. Can we close this issue?

**Comment by nonsense** [comment]
Closing. Let's re-open in case there are more flaky tests.
