### ISSUE TITLE
Update 1.1.3 to 1.2.2 lost my ether balance

### ISSUE THREAD

**Issue by imifos** [ethereum/go-ethereum#1872]
I was running version 1.1.3:

```
J:\processes\geth>geth --rpc console
I1003 09:20:34.364947   68880 database.go:73] Alloted 16MB cache to C:\Users\PC\AppData\Roaming\Ethereum\chaindata
I1003 09:20:34.573092   68880 database.go:73] Alloted 16MB cache to C:\Users\PC\AppData\Roaming\Ethereum\dapp
I1003 09:20:34.620975   68880 backend.go:291] Protocol Versions: [61 60], Network Id: 1
I1003 09:20:34.622930   68880 backend.go:328] Blockchain DB Version: 3
I1003 09:20:34.625862   68880 chain_manager.go:237] Last block (#324431) 54835baf12f0b9a95bd709b553ca271d1f5c396f367bcd48b56b95a227a0843c TD=1549036119521575734
I1003 09:20:34.689380   68880 cmd.go:125] Starting Geth/v1.1.3/windows/go1.4.2
I1003 09:20:34.689380   68880 server.go:311] Starting Server
I1003 09:20:36.552912   68880 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-PPP1
I1003 09:20:36.718060   68880 udp.go:207] Listening, enode://82f0b38d425802704fe66dfcce158d84bac6202d45abbb910a38e7895f64d62dd33cae479425bb55a1fb63c312737e2642fa74e7eb03c92addb7783e81e69e47@81.240.129.46:30303
I1003 09:20:36.719038   68880 backend.go:557] Server started
I1003 09:20:36.719038   68880 ipc_windows.go:724] IPC service started (\\.\pipe\geth.ipc)
I1003 09:20:36.719038   68880 server.go:552] Listening on [::]:30303
I1003 09:20:36.733696   68880 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-PPP1
instance: Geth/v1.1.3/windows/go1.4.2
 datadir: C:\Users\PC\AppData\Roaming\Ethereum
coinbase: 0x9f2416d4269ee4171db1ab5e090ec5a8dcab0bc2
at block: 324431 (Fri, 02 Oct 2015 23:48:52 CEST)
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
> I1003 09:20:46.720742   68880 downloader.go:278] Block synchronisation started
I1003 09:20:49.630863   68880 chain_manager.go:661] imported 46 block(s) (0 queued 1 ignored) including 25 txs in 1.5537587s. #324477 [54835baf / 408d4b88]
:
```

My ether balance was this:

```
J:\processes\geth>geth attach
instance: Geth/v1.1.3/windows/go1.4.2
 datadir: C:\Users\PC\AppData\Roaming\Ethereum
coinbase: 0x9f2416d4269ee4171db1ab5e090ec5a8dcab0bc2
at block: 318613 (Thu, 01 Oct 2015 20:30:07 CEST)
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
> web3.fromWei(eth.getBalance(eth.coinbase),"ether")
0.61195551553228672
:
:
(still running, next lines after crash description)
```

Then geth 1.1.3 crashed last night with this:

```
I1002 23:48:55.346655   74880 chain_manager.go:661] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.9078ms. #324430 [d8fb461a / d8fb461a]
I1002 23:48:55.353496   74880 worker.go:540] commit new work on block 324431 with 0 txs & 0 uncles. Took 5.8635ms
I1002 23:49:30.360928   74880 chain_manager.go:661] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.886ms. #324431 [54835baf / 54835baf]
I1002 23:49:30.371677   74880 worker.go:540] commit new work on block 324432 with 0 txs & 0 uncles. Took 10.7491ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x880e0e]

goroutine 757229 [running]:
github.com/syndtr/goleveldb/leveldb.(*dbIter).Release(0xc0858c42d0)
        D:/builds/geth_win32/build-go-win-master/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_iter.go:333 +0x16e
github.com/ethereum/go-ethereum/p2p/discover.(*nodeDB).querySeeds(0xc083a8d650, 0xa, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/p2p/discover/database.go:340 +0x364
github.com/ethereum/go-ethereum/p2p/discover.(*Table).refresh(0xc08370a000)

...

// @obscuren: removed output due to solved bug

...
```
I restarted...

And checked by balance:

```
(follow up from above)
:
:
(still running, next lines after crash description)
> web3.fromWei(eth.getBalance(eth.coinbase),"ether")
2.073359062020619136
> exit
```

Then, I check the version on the release history and installed the update to 1.2.2:

```
J:\processes\geth_1.2.2>geth --rpc console
I1003 09:33:01.616881   90312 database.go:71] Alloted 16MB cache to C:\Users\PC\AppData\Roaming\Ethereum\chaindata
I1003 09:33:01.792778   90312 backend.go:712] Old database detected, upgrading...
I1003 09:34:42.480188   90312 database.go:71] Alloted 16MB cache to C:\Users\PC\AppData\Roaming\Ethereum\dapp
I1003 09:34:42.535889   90312 backend.go:291] Protocol Versions: [62 61], Network Id: 1
I1003 09:34:42.558363   90312 backend.go:333] Blockchain DB Version: 3
I1003 09:34:42.562273   90312 chain_manager.go:248] Last block (#326557) 291e7286cb78ae83f2da428e2388e4cd7e0ab25a5d12980261155a64ae4e8070 TD=1562148790322764539
I1003 09:34:42.582795   90312 cmd.go:125] Starting Geth/v1.2.2/windows/go1.4.2
I1003 09:34:42.583772   90312 server.go:311] Starting Server
I1003 09:34:42.695172   90312 udp.go:204] Listening, enode://82f0b38d425802704fe66dfcce158d84bac6202d45abbb910a38e7895f64d62dd33cae479425bb55a1fb63c312737e2642fa74e7eb03c92addb7783e81e69e47@[::]:30303
I1003 09:34:42.695172   90312 backend.go:559] Server started
I1003 09:34:42.695172   90312 server.go:552] Listening on [::]:30303
I1003 09:34:42.719604   90312 ipc_windows.go:724] IPC service started (\\.\pipe\geth.ipc)
instance: Geth/v1.2.2/windows/go1.4.2
 datadir: C:\Users\PC\AppData\Roaming\Ethereum
coinbase: 0x9f2416d4269ee4171db1ab5e090ec5a8dcab0bc2
at block: 326557 (Sat, 03 Oct 2015 09:32:22 CEST)
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
> I1003 09:34:52.696878   90312 downloader.go:275] Block synchronisation started
I1003 09:34:55.494618   90312 chain_manager.go:722] imported 2 block(s) (0 queued 0 ignored) including 0 txs in 1.3680899s. #326559 [a8437ac5 / 61c68a0f]
I1003 09:34:55.584522   90312 chain_manager.go:722] imported 7 block(s) (0 queued 0 ignored) including 11 txs in 89.904ms. #326566 [cd34266d / 65bc273b]
I1003 09:35:00.620064   90312 chain_manager.go:722] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.8633ms. #326567 [e96d7f35 / e96d7f35]
I1003 09:35:05.274497   90312 chain_manager.go:722] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.8861ms. #326568 [11cc153e / 11cc153e]
I1003 09:35:36.779623   90312 chain_manager.go:722] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 7.8182ms. #326569 [60c1ef07 / 60c1ef07]
:
:
```

Please note the "90312 backend.go:712] Old database detected, upgrading..."

I also restarted an attached geth console:

```
J:\processes\geth_1.2.2>geth attach
instance: Geth/v1.2.2/windows/go1.4.2
 datadir: C:\Users\PC\AppData\Roaming\Ethereum
coinbase: 0x9f2416d4269ee4171db1ab5e090ec5a8dcab0bc2
at block: 326615 (Sat, 03 Oct 2015 09:49:15 CEST)
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
> web3.fromWei(eth.getBalance("0x9f2416d4269ee4171db1ab5e090ec518dcab0bc2"),"ether")
0
>
```
For comparison, with 1.1.3, coinbase and  data directory and address are the same as above.

Question: what happened? Where is my Ether?

Thanks!

**Comment by imifos** [comment]
https://etherchain.org/account/0x9f2416d4269ee4171db1ab5e090ec5a8dcab0bc2#txreceived

**Comment by dakk** [comment]
your balance is still there; try to re-sync your geth daemon and check again

2015-10-03 10:04 GMT+02:00 Tasha CARL <notifications@github.com>:

**Comment by obscuren** [comment]
First of all, and i don't know if this was intended or not, the `console` basically does the same thing as an `geth attach` but all in the same window.

When you're running with `geth console` and check the balance from that window, does it still show `0`?

**Comment by imifos** [comment]
I have tested around (restarts etc), and now it works. I don't know what happened or/and what I did (or did wrong), but the balance shows well now. 

Thanks a lot for the hyper-fast reply!!

(I was not worried, just thought it would be good to report a potential issue asap. I'll close the issue).

Finally:

re-sync - my (new) geth client runs in parallel and is nicely downloading new blocks. Out of curiosity and thirst for understanding, would indicate to me how to "re-sync" without deleting the blockchain database and restart everything, I would be ether-nally grateful :)

console/attach - yes, it was intended. I use the attached console to play around with commands, and the main console here and then for tests and graceful exit, while having the log output to the console too.

**Comment by karalabe** [comment]
You cannot resync without deleting the old chain. It would be quite messy to maintain multiple version of the database and try to merge them together. However, there's a fast sync coming very soon that can sync up the current chain in about 90 seconds, so that should help a lot ;)
