### ISSUE TITLE
geth  1.8.15-stable runtime: out of memory

### ISSUE THREAD

**Issue by friends110110** [ethereum/go-ethereum#19034]
startup script:
```
nohup $BIN_PATH/geth --datadir "$DEPLOY_PATH" \
--nodekey "$DEPLOY_PATH/nodekeys/nodekey" \
--ethash.dagdir "$DEPLOY_PATH"/ethash \
--port $port --rpc --rpcaddr $LOCAL_IP --rpcport $rpc_port --rpccorsdomain "*" \
--pprof --pprofaddr $LOCAL_IP --pprofport $ppof_port \
--rpcapi eth,personal,net,admin \
--nodiscover --syncmode "full" \
--txpool.globalslots 16000  --memprofilerate 600 \
--mine --minerthreads 1 --miner.etherbase $miner_account --gasprice 1 --extradata "0x" \
--metrics --metrics.influxdb --metrics.influxdb.endpoint http://10.xx.xx.xx:8086 --metrics.influxdb.database collectd --metrics.influxdb.host.tag 11 \
--vmdebug --verbosity 3 >> $DEPLOY_PATH/logs/chain.log 2>&1 & echo $! > $DEPLOY_PATH/logs/pid.log
```
and my code listen and server, I do not know whether it use a lot of memory or not ?
```
go func() {
		http.ListenAndServe("0.0.0.0:8899", nil)
	}()
```

the detailed url [oom](https://raw.githubusercontent.com/friends110110/errorProject/master/oom.md), the fragment is following: 
```

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x10220b7, 0x16)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc5a9b30000, 0x10000000, 0x0, 0x1d0a518)
	/usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1cf0ac0, 0x10000000, 0x3f2faf1bbfdf9d88)
	/usr/lib/go-1.10/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1cf0ac0, 0x8000, 0x0)
	/usr/lib/go-1.10/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x1cf0ac0, 0x8000, 0x1d0a528, 0x0)
	/usr/lib/go-1.10/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x1cf0ac0, 0x8000, 0x101, 0x7f8eaa7fbb38)
	/usr/lib/go-1.10/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.10/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x1cf0ac0, 0x8000, 0x7f8eaa010101, 0x7f8eaa7fbe58)
	/usr/lib/go-1.10/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x10000000, 0x101, 0x0)
	/usr/lib/go-1.10/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/lib/go-1.10/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/lib/go-1.10/src/runtime/proc.go:1175

goroutine 5217983 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:363 fp=0xc4c19a0c50 sp=0xc4c19a0c48 pc=0x46d4a0
runtime.mallocgc(0x10000000, 0xe40800, 0x1, 0xc4cc1d5000)
	/usr/lib/go-1.10/src/runtime/malloc.go:720 +0x8a2 fp=0xc4c19a0cf0 sp=0xc4c19a0c50 pc=0x4260d2
runtime.makeslice(0xe40800, 0x4000000, 0x4000000, 0xc4cc1d5000, 0x200, 0x200)
	/usr/lib/go-1.10/src/runtime/slice.go:61 +0x77 fp=0xc4c19a0d20 sp=0xc4c19a0cf0 pc=0x4575b7
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0xc4249ed320, 0x6, 0x8, 0xc42c7cb600, 0x20, 0x40, 0x40000, 0x8, 0x1, 0x20, ...)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:236 +0x152 fp=0xc4c19a0de0 sp=0xc4c19a0d20 pc=0x6e7f22
github.com/ethereum/go-ethereum/accounts/keystore.getKDFKey(0xc4249ecce0, 0xb, 0xc4de3821c0, 0x40, 0xc45bb5fd60, 0x20, 0xc4249eccc8, 0x6, 0xc4518276e0, 0xc4de382400, ...)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:295 +0x6a4 fp=0xc4c19a0ee8 sp=0xc4c19a0de0 pc=0x704114
github.com/ethereum/go-ethereum/accounts/keystore.decryptKeyV3(0xc498fa8380, 0xc4249ec7c0, 0x6, 0xe04ee0, 0xc498fa8380, 0x0, 0x0, 0xc5608c8410, 0x0, 0x0, ...)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:232 +0x2eb fp=0xc4c19a1048 sp=0xc4c19a0ee8 pc=0x702f5b
github.com/ethereum/go-ethereum/accounts/keystore.DecryptKey(0xc4200e8c00, 0x1eb, 0x3eb, 0xc4249ec7c0, 0x6, 0x0, 0x0, 0xc569b1f218)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:192 +0x1bf fp=0xc4c19a1100 sp=0xc4c19a1048 pc=0x70296f
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.GetKey(0xc4202bc990, 0x24, 0x40000, 0x1, 0x55630148291882c0, 0xf740c0dbdf940e57, 0xd2427331, 0xc4204dba80, 0x72, 0xc4249ec7c0, ...)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:83 +0x9c fp=0xc4c19a11a8 sp=0xc4c19a1100 pc=0x7015fc
github.com/ethereum/go-ethereum/accounts/keystore.(*keyStorePassphrase).GetKey(0xc420430fc0, 0x55630148291882c0, 0xf740c0dbdf940e57, 0xd2427331, 0xc4204dba80, 0x72, 0xc4249ec7c0, 0x6, 0x55630148291882c0, 0xf740c0dbdf940e57, ...)
	<autogenerated>:1 +0xb4 fp=0xc4c19a1228 sp=0xc4c19a11a8 pc=0x7073e4
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).getDecryptedKey(0xc4203c42d0, 0x55630148291882c0, 0xf740c0dbdf940e57, 0xd2427331, 0xff7941, 0x8, 0xc4204dba80, 0x72, 0xc4249ec7c0, 0x6, ...)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:382 +0x1f0 fp=0xc4c19a12f8 sp=0xc4c19a1228 pc=0x7002f0
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).TimedUnlock(0xc4203c42d0, 0x55630148291882c0, 0xf740c0dbdf940e57, 0xd2427331, 0x0, 0x0, 0x0, 0x0, 0xc4249ec7c0, 0x6, ...)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:340 +0xb6 fp=0xc4c19a1400 sp=0xc4c19a12f8 pc=0x6ffb86
github.com/ethereum/go-ethereum/internal/ethapi.(*PrivateAccountAPI).UnlockAccount(0xc4266b0780, 0x55630148291882c0, 0xf740c0dbdf940e57, 0xd2427331, 0xc4249ec7c0, 0x6, 0xc4249ec7d8, 0x0, 0x0, 0x0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:330 +0x174 fp=0xc4c19a14c8 sp=0xc4c19a1400 pc=0xac6294
runtime.call128(0xc421035e90, 0xc42023ba88, 0xc54f86e690, 0x3800000050)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:575 +0x52 fp=0xc4c19a1558 sp=0xc4c19a14c8 pc=0x46d982
reflect.Value.call(0xc42680c000, 0xc42023ba88, 0x13, 0xff21ee, 0x4, 0xc56406cae0, 0x4, 0x4, 0x3, 0xc56406cae0, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969 fp=0xc4c19a1818 sp=0xc4c19a1558 pc=0x4cc5e9
reflect.Value.Call(0xc42680c000, 0xc42023ba88, 0x13, 0xc56406cae0, 0x4, 0x4, 0x3, 0x3, 0x3)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4 fp=0xc4c19a1880 sp=0xc4c19a1818 pc=0x4cbb64
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc42686c900, 0x11d8980, 0xc42dba8f00, 0x11de0c0, 0xc5608c8370, 0xc5280565a0, 0xc5608c83e0, 0x0, 0xe8aae0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:309 +0x676 fp=0xc4c19a19f8 sp=0xc4c19a1880 pc=0x828ce6
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc42686c900, 0x11d8980, 0xc42dba8f00, 0x11de0c0, 0xc5608c8370, 0xc5280565a0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:330 +0x1a6 fp=0xc4c19a1a68 sp=0xc4c19a19f8 pc=0x829806
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc42686c900, 0x11d8a40, 0xc45834cf30, 0x11de0c0, 0xc5608c8370, 0xffdd01, 0x1, 0x0, 0x0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:192 +0x370 fp=0xc4c19a1b88 sp=0xc4c19a1a68 pc=0x827a20
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc42686c900, 0x11d8a40, 0xc45834cf30, 0x11de0c0, 0xc5608c8370, 0x1)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0x65 fp=0xc4c19a1be0 sp=0xc4c19a1b88 pc=0x8281e5
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc42686c900, 0x11d7080, 0xc4e5bfe1c0, 0xc4647e0000)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:247 +0x420 fp=0xc4c19a1c78 sp=0xc4c19a1be0 pc=0x822590
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x11d7080, 0xc4e5bfe1c0, 0xc4647e0000)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0xfe fp=0xc4c19a1cd0 sp=0xc4c19a1c78 pc=0x80e6be
net/http.HandlerFunc.ServeHTTP(0xc4268de4a0, 0x11d7080, 0xc4e5bfe1c0, 0xc4647e0000)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44 fp=0xc4c19a1cf8 sp=0xc4c19a1cd0 pc=0x7e2cd4
github.com/ethereum/go-ethereum/rpc.(*virtualHostHandler).ServeHTTP(0xc4268de4c0, 0x11d7080, 0xc4e5bfe1c0, 0xc4647e0000)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:305 +0x204 fp=0xc4c19a1d58 sp=0xc4c19a1cf8 pc=0x822df4
net/http.serverHandler.ServeHTTP(0xc4268bea90, 0x11d7080, 0xc4e5bfe1c0, 0xc4647e0000)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc fp=0xc4c19a1d88 sp=0xc4c19a1d58 pc=0x7e5b9c
net/http.(*conn).serve(0xc4288505a0, 0x11d8980, 0xc431e425c0)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651 fp=0xc4c19a1fc8 sp=0xc4c19a1d88 pc=0x7e1cf1
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4c19a1fd0 sp=0xc4c19a1fc8 pc=0x470031
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b

goroutine 1 [chan receive, 484 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc4204d3400)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:474 +0x7f
main.geth(0xc4204ac420, 0x0, 0x0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:271 +0xf1
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xe5af60, 0x10c4938, 0xc4204ac420, 0xc4204ac420, 0xc4204bff48)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4204fe680, 0xc420030380, 0x32, 0x38, 0x0, 0x0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee
main.main()
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:256 +0x55

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x1cdae20)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/metrics/meter.go:250 +0x78
created by github.com/ethereum/go-ethereum/metrics.NewMeter
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/metrics/meter.go:44 +0x10b

goroutine 7 [chan receive, 485 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc4200841e0, 0xc420084120)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xf2

goroutine 8 [chan receive, 485 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc4200841e0, 0xc420084180)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x11e

goroutine 9 [syscall, 485 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x41

goroutine 10 [chan receive, 41 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc4200675b0)
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/test/git/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0xa4
```

**Comment by karalabe** [comment]
Your crash dump indicates that you're running out of memory when doing account unlocks. Are you sure someone isn't attempting to access your node from the internet and brute force the password? That's what usually causes people to run OOM.
