### ISSUE TITLE
geth crash syncing goerli

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#19065]
just happened on my goerli node:

```
goroutine 2371 [running]:
math/big.(*Int).Cmp(0xc017de9580, 0x0, 0x1b439574fde2a8eb)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/math/big/int.go:319 +0x2e
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc00530c000, 0xc01c72f6a0, 0xc0000af5b0, 0xc0000af501, 0x1, 0x1, 0xc023de8860, 0x1, 0x1, 0xc
017d9b3e0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1333 +0x10b2
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00530c000, 0xc01496c5a0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2e1e
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00530c000, 0xc01496c5a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0xb89
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0001fc820, 0xc01496c598, 0x1, 0x1, 0x1, 0xa8c247ee84f9a3ee)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x40e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0001fc820, 0x73507dff30583f88, 0xc01416ff98)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x79
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x102ed10)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0001fc820, 0xc006390f00, 0xc017107f40)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xaf

```

with the following geth version

```
Version: 1.8.22-stable
Git Commit: 7fa3509e2eaf1a4ebc12344590e5699406690f15
```

**Comment by karalabe** [comment]
This is fixed on master.
