### ISSUE TITLE
Panic after debug.setHead() when sending from a different account

### ISSUE THREAD

**Issue by shoenseiwaso** [ethereum/go-ethereum#19212]
Edit: fix submitted in PR #19216.

Panic occurs here:
https://github.com/ethereum/go-ethereum/blob/81ed70015704737b3e5329314a62a3a5aaa74e8a/core/tx_pool.go#L395

After doing the following:

- `eth.sendTransaction({from: A, to: B, value: any})`
- `debug.setHead(back one block)`
- `eth.sendTransaction({from: not A, to: any, value: any})`

What I think is happening:

- After `setHead()`, in tx pool loop `reset()` gets called
- `oldHead` and `newHead` are valid, but one or both of them are no longer in the tx pool
- Therefore one of `add` or `rem` is nil, and prior to [line 395](https://github.com/ethereum/go-ethereum/blob/81ed70015704737b3e5329314a62a3a5aaa74e8a/core/tx_pool.go#L395) no check for nil is done
- Panic on line 395 dereferencing nil

Environment:
```
Geth
Version: 1.8.22-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: darwin
```

Steps to reproduce:

```
# 
# Setup a new geth dev mode environment
#  
$ geth --dev --datadir set_head_bug console
INFO [03-05|21:57:51.684] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-05|21:57:53.821] Using developer account                  address=0x80f3Cf82e62b7C3948DA0AffDDd2Ed31c10655B5
INFO [03-05|21:57:53.822] Starting peer-to-peer node               instance=Geth/v1.8.22-stable/darwin-amd64/go1.11.5
<snip>
INFO [03-05|21:57:53.829] Writing custom genesis block
INFO [03-05|21:57:53.830] Persisted trie from memory database      nodes=11 size=1.71kB time=102.377µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-05|21:57:53.830] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0  ConstantinopleFix: 0 Engine: clique}"
INFO [03-05|21:57:53.830] Initialising Ethereum protocol           versions="[63 62]" network=1337
INFO [03-05|21:57:53.849] Loaded most recent local header          number=0 hash=3a565f…660acd td=1 age=49y10mo2w
<snip>
INFO [03-05|21:57:53.857] Sealing paused, waiting for transactions
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.22-stable/darwin-amd64/go1.11.5
coinbase: 0x80f3cf82e62b7c3948da0affddd2ed31c10655b5
at block: 0 (Thu, 01 Jan 1970 09:00:00 JST)
 datadir: /tmp/set_head_bug
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

> eth.blockNumber
0

# 
# Setup a second account
# 
> personal.newAccount()
Passphrase:
Repeat passphrase:
"0x6941474503af6d776c0ca7f881ce399b416ed79c"
> personal.unlockAccount(eth.accounts[1], "", 86400)
true

# 
# Send the new account Ether twice to get us to block number 2
# 
> eth.sendTransaction({from: eth.accounts[0], to: eth.accounts[1], value: 1000000})
INFO [03-05|21:59:07.338] Setting new local account                address=0x80f3Cf82e62b7C3948DA0AffDDd2Ed31c10655B5
INFO [03-05|21:59:07.338] Submitted transaction                    fullhash=0x41979183f48b61b953c585be7fa6f3da9214707dc0bf904813e9580c27cc9c86 recipient=0x6941474503af6D776C0ca7f881Ce399B416Ed79C
INFO [03-05|21:59:07.338] Commit new mining work                   number=1 sealhash=e028a8…e70d2e uncles=0 txs=0 gas=0 fees=0 elapsed=94.44µs
"0x41979183f48b61b953c585be7fa6f3da9214707dc0bf904813e9580c27cc9c86"
INFO [03-05|21:59:07.339] Sealing paused, waiting for transactions
> INFO [03-05|21:59:07.339] Commit new mining work                   number=1 sealhash=4ce0e3…52aa35 uncles=0 txs=1 gas=21000 fees=2.1e-14 elapsed=382.625µs
INFO [03-05|21:59:07.339] Successfully sealed new block            number=1 sealhash=4ce0e3…52aa35 hash=c7d1b5…885c81 elapsed=742.391µs
INFO [03-05|21:59:07.340] 🔨 mined potential block                  number=1 hash=c7d1b5…885c81
INFO [03-05|21:59:07.340] Commit new mining work                   number=2 sealhash=e716ed…aca8f1 uncles=0 txs=0 gas=0     fees=0       elapsed=306.807µs
INFO [03-05|21:59:07.340] Sealing paused, waiting for transactions

> eth.blockNumber
1
> eth.sendTransaction({from: eth.accounts[0], to: eth.accounts[1], value: 1000000})
INFO [03-05|21:59:13.082] Submitted transaction                    fullhash=0xd6b4a177a7e581156660628103847d9883c78ec3bdb00e4e955107125609d2b7 recipient=0x6941474503af6D776C0ca7f881Ce399B416Ed79C
"0xd6b4a177a7e581156660628103847d9883c78ec3bdb00e4e955107125609d2b7"
> INFO [03-05|21:59:13.082] Sealing paused, waiting for transactions
INFO [03-05|21:59:13.082] Commit new mining work                   number=2 sealhash=fd477b…0d36c2 uncles=0 txs=0 gas=0     fees=0       elapsed=174.367µs
INFO [03-05|21:59:13.082] Commit new mining work                   number=2 sealhash=53d144…70cc29 uncles=0 txs=1 gas=21000 fees=2.1e-14 elapsed=460.98µs
INFO [03-05|21:59:13.083] Successfully sealed new block            number=2 sealhash=53d144…70cc29 hash=ee9dfb…c108b5 elapsed=733.969µs
INFO [03-05|21:59:13.083] 🔨 mined potential block                  number=2 hash=ee9dfb…c108b5
INFO [03-05|21:59:13.083] Commit new mining work                   number=3 sealhash=41090d…21df11 uncles=0 txs=0 gas=0     fees=0       elapsed=503.486µs
INFO [03-05|21:59:13.083] Sealing paused, waiting for transactions
>
> eth.blockNumber
2
>
>

# 
# Roll back to block number 1
# Because we sent Ether twice to the second account, it still
# has Ether for the next step 
# 
> debug.setHead("0x1")
WARN [03-05|21:59:31.606] Rewinding blockchain                     target=1
INFO [03-05|21:59:31.607] Loaded most recent local header          number=1 hash=c7d1b5…885c81 td=3 age=24s
INFO [03-05|21:59:31.607] Loaded most recent local full block      number=1 hash=c7d1b5…885c81 td=3 age=24s
INFO [03-05|21:59:31.607] Loaded most recent local fast block      number=1 hash=c7d1b5…885c81 td=3 age=24s
null
> eth.blockNumber
1

# 
# Send any transaction that's not from the first account
# 
> eth.sendTransaction({from: eth.accounts[1], to: eth.accounts[0], value: 1})
INFO [03-05|21:59:49.138] Setting new local account                address=0x6941474503af6D776C0ca7f881Ce399B416Ed79C
INFO [03-05|21:59:49.138] Submitted transaction                    fullhash=0x78d7a5672445ac66cc34177b931cc95bc59b0ceb9fac543500d470b9a4e08062 recipient=0x80f3Cf82e62b7C3948DA0AffDDd2Ed31c10655B5
INFO [03-05|21:59:49.139] Commit new mining work                   number=2 sealhash=b10065…efac29 uncles=0 txs=0 gas=0     fees=0       elapsed=105.499µs
"0x78d7a5672445ac66cc34177b931cc95bc59b0ceb9fac543500d470b9a4e08062"
INFO [03-05|21:59:49.139] Sealing paused, waiting for transactions
> INFO [03-05|21:59:49.139] Commit new mining work                   number=2 sealhash=5bc527…8ce71a uncles=0 txs=1 gas=21000 fees=2.1e-14 elapsed=329.998µs
INFO [03-05|21:59:49.139] Successfully sealed new block            number=2 sealhash=5bc527…8ce71a hash=d1138a…e77550 elapsed=577.576µs
INFO [03-05|21:59:49.139] 🔨 mined potential block                  number=2 hash=d1138a…e77550
INFO [03-05|21:59:49.140] Commit new mining work                   number=3 sealhash=b1a46f…9d3929 uncles=0 txs=0 gas=0     fees=0       elapsed=368.017µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x44b6011]

goroutine 15 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
	/private/tmp/ethereum-20190204-77575-oobokl/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:291
github.com/ethereum/go-ethereum/core.(*TxPool).reset(0xc00022da40, 0xc021f07b00, 0xc021f07d40)
	/private/tmp/ethereum-20190204-77575-oobokl/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:395 +0x6e1
github.com/ethereum/go-ethereum/core.(*TxPool).loop(0xc00022da40)
	/private/tmp/ethereum-20190204-77575-oobokl/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:314 +0x43c
created by github.com/ethereum/go-ethereum/core.NewTxPool
	/private/tmp/ethereum-20190204-77575-oobokl/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:278 +0x677
```

**Comment by shoenseiwaso** [comment]
Additional details from adding the following debug statements right before line 395 (the panic):

```go
log.Error("oldHead", "oldHead", oldHead)
log.Error("newHead", "newHead", newHead)
log.Error("rem", "rem", rem)
log.Error("add", "add", add)
```

Log output:

```
ERROR[03-06|10:55:37.383] oldHead                                  oldHead="&{ParentHash:[119 251 40 37 219 238 96 144 185 89 199 153 147 59 42 173 109 246 93 161 202 124 63 16 106 201 152 185 27 16 54 170] UncleHash:[29 204 77 232 222 199 93 122 171 133 181 103 182 204 212 26 211 18 69 27 148 138 116 19 240 161 66 253 64 212 147 71] Coinbase:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Root:[146 161 75 103 30 1 140 224 222 98 41 222 181 162 178 181 108 238 216 211 91 185 147 112 222 160 65 234 34 255 41 253] TxHash:[184 161 190 137 155 240 41 150 29 17 229 64 106 166 176 254 114 255 33 185 29 138 14 67 9 88 227 76 153 63 13 112] ReceiptHash:[5 107 35 251 186 72 6 150 182 95 229 165 155 143 33 72 161 41 145 3 196 245 125 248 57 35 58 242 207 76 162 210] Bloom:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Difficulty:+2 Number:+2 GasLimit:6295459 GasUsed:21000 Time:+1551837323 Extra:[217 131 1 9 0 132 103 101 116 104 136 103 111 49 46 49 49 46 53 134 100 97 114 119 105 110 0 0 0 0 0 0 157 206 27 25 123 91 67 104 38 52 183 120 21 218 164 25 120 200 25 226 208 216 30 21 227 18 222 94 185 68 202 185 30 103 239 151 192 14 88 180 44 52 203 31 51 240 241 233 50 66 194 79 242 120 129 175 241 30 255 235 38 252 195 140 0] MixDigest:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Nonce:[0 0 0 0 0 0 0 0]}"
ERROR[03-06|10:55:37.384] newHead                                  newHead="&{ParentHash:[119 251 40 37 219 238 96 144 185 89 199 153 147 59 42 173 109 246 93 161 202 124 63 16 106 201 152 185 27 16 54 170] UncleHash:[29 204 77 232 222 199 93 122 171 133 181 103 182 204 212 26 211 18 69 27 148 138 116 19 240 161 66 253 64 212 147 71] Coinbase:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Root:[123 55 109 220 81 254 126 33 71 91 182 186 221 163 153 234 147 190 47 99 114 35 188 241 218 65 129 80 36 61 29 82] TxHash:[43 16 108 60 166 164 165 75 45 67 166 41 208 74 161 176 247 156 144 29 224 154 60 241 40 45 187 80 33 97 158 68] ReceiptHash:[5 107 35 251 186 72 6 150 182 95 229 165 155 143 33 72 161 41 145 3 196 245 125 248 57 35 58 242 207 76 162 210] Bloom:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Difficulty:+2 Number:+2 GasLimit:6295459 GasUsed:21000 Time:+1551837337 Extra:[217 131 1 9 0 132 103 101 116 104 136 103 111 49 46 49 49 46 53 134 100 97 114 119 105 110 0 0 0 0 0 0 117 178 97 83 60 173 67 100 240 25 233 71 73 6 115 74 141 156 29 151 121 7 80 68 94 229 39 133 102 50 21 146 70 59 233 74 184 204 235 232 19 217 55 21 134 200 161 161 93 68 170 70 1 168 224 124 237 37 198 31 42 77 78 202 1] MixDigest:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Nonce:[0 0 0 0 0 0 0 0]}"
INFO [03-06|10:55:37.383] Commit new mining work                   number=3 sealhash=67b017…f0047b uncles=0 txs=0 gas=0     fees=0       elapsed=367.184µs
INFO [03-06|10:55:37.383] Sealing paused, waiting for transactions
ERROR[03-06|10:55:37.384] rem                                      rem=<nil>
ERROR[03-06|10:55:37.385] add                                      add="&{header:0xc022412480 uncles:[] transactions:[0xc021a81ef0] hash:{v:[177 67 231 79 26 234 189 180 8 95 43 12 74 159 32 193 213 201 79 219 217 47 223 11 222 171 17 43 244 208 20 236]} size:{v:<nil>} td:<nil> ReceivedAt:0001-01-01 00:00:00 +0000 UTC ReceivedFrom:<nil>}"
```

So `rem` comes up nil.
