### ISSUE TITLE
WIKI, FIX INCLUDED: Bad example of traceTransacion with custom tracer

### ISSUE THREAD

**Issue by felberj** [ethereum/go-ethereum#19277]
Hi, I did not figure out how to send PR to your wiki.

But here is a patch to the issue:

```
From 10c4630101402a700d54f1614d8c8bd811ce36eb Mon Sep 17 00:00:00 2001
From: Jonas Felber <felber.jonas@gmail.com>
Date: Fri, 15 Mar 2019 10:49:38 +0100
Subject: [PATCH] Fixed traceTransacion with custom tracer example.

Executing the previous command resulted in the following error:

Error: Trace object must expose a function fault()
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
---
 Management-APIs.md | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Management-APIs.md b/Management-APIs.md
index e342b37..3b0d767 100644
--- a/Management-APIs.md
+++ b/Management-APIs.md
@@ -784,7 +784,7 @@ Note that several values are Golang big.Int objects, not JavaScript numbers or J
 
 Usage example, returns the top element of the stack at each CALL opcode only:
 
-    debug.traceTransaction(txhash, {tracer: '{data: [], step: function(log) { if(log.op.toString() == "CALL") this.data.push(log.stack.peek(0)); }, result: function() { return this.data; }}'});
+    debug.traceTransaction(txhash, {tracer: '{data: [], fault: function(log) {}, step: function(log) { if(log.op.toString() == "CALL") this.data.push(log.stack.peek(0)); }, result: function() { return this.data; }}'});
 
 ### debug_verbosity
 
@@ -1326,4 +1326,4 @@ the number of transactions in that particular state.
   pending: 10,
   queued: 7
 }
-```
\ No newline at end of file
+```
-- 
2.15.1

```

**Comment by fjl** [comment]
Will be fixed after #18392
