### ISSUE TITLE
geth crash: in `consensus/clique.(*Clique).snapshot`  panic: runtime error: makeslice: len out of range  

### ISSUE THREAD

**Issue by sheb-gregor** [ethereum/go-ethereum#19299]
Hi there,

unable to start private chain :(

#### System information

Version: 1.8.18-stable
Git Commit: 58632d44021bf095b43a1bb2443e6e3690a94739
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=/home/sheb/go
GOROOT=/usr/lib/go-1.10

#### Expected behaviour

Node should start

#### Actual behaviour

Node crash with panic

#### Steps to reproduce the behaviour
- get actual version of `geth`
- ` ./bin/geth init --datadir ./data/geth.alpha ./geth.json`
- ` ./bin/geth --config ./geth.toml --rpc`

#### Backtrace

````
[backtrace]
> $ ./bin/geth --config ./geth.toml --rpc
WARN [03-19|10:35:01.060] Sanitizing cache to Go's GC limits       provided=1024 updated=648
INFO [03-19|10:35:01.062] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-19|10:35:01.064] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-fb458280/linux-amd64/go1.12.1
INFO [03-19|10:35:01.064] Allocated trie memory caches             clean=162.00MiB dirty=162.00MiB
INFO [03-19|10:35:01.064] Allocated cache and file handles         database=/home/sheb/geth/data/geth.alpha/geth/chaindata cache=324.00MiB handles=524288
INFO [03-19|10:35:01.091] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 15 Constantinople: 15  ConstantinopleFix: <nil> Engine: clique}"
INFO [03-19|10:35:01.092] Initialising Ethereum protocol           versions="[63 62]" network=1337 dbversion=<nil>
WARN [03-19|10:35:01.092] Upgrade blockchain database version      from=<nil> to=4
INFO [03-19|10:35:01.104] Loaded most recent local header          number=0 hash=a5ef7d…60d4b4 td=65536 age=49y11mo4d
INFO [03-19|10:35:01.104] Loaded most recent local full block      number=0 hash=a5ef7d…60d4b4 td=65536 age=49y11mo4d
INFO [03-19|10:35:01.104] Loaded most recent local fast block      number=0 hash=a5ef7d…60d4b4 td=65536 age=49y11mo4d
INFO [03-19|10:35:01.105] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-19|10:35:01.117] IPC endpoint opened                      url=/home/sheb/geth/data/geth.alpha.ipc
INFO [03-19|10:35:01.118] HTTP endpoint opened                     url=http://0.0.0.0:8555                 cors= vhosts=geth.teamo.work,localhost
INFO [03-19|10:35:01.119] WebSocket endpoint opened                url=ws://[::]:8546
panic: runtime error: makeslice: len out of range

goroutine 43 [running]:
github.com/ethereum/go-ethereum/consensus/clique.(*Clique).snapshot(0xc000488540, 0x12e2ea0, 0xc013d72000, 0x0, 0xeedcd788c37defa5, 0x353a9edb05ea1e, 0x19f30754d09fdcc2, 0xb4d46070fa8dab1e, 0x0, 0x0, ...)
        /home/sheb/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/clique/clique.go:374 +0x53d
github.com/ethereum/go-ethereum/consensus/clique.(*Clique).Prepare(0xc000488540, 0x12e2ea0, 0xc013d72000, 0xc0002ba480, 0xb4d46070fa8dab1e, 0x0)
        /home/sheb/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/clique/clique.go:494 +0xf1
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc0002d5a40, 0xc000170000, 0x0, 0x5c90b7c5)
        /home/sheb/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:852 +0x569
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc0002d5a40)
        /home/sheb/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:410 +0xbe0
created by github.com/ethereum/go-ethereum/miner.newWorker
        /home/sheb/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:218 +0x522
````

## geth.json

```json
{
  "config": {
    "chainId": 1337,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 10,
    "eip158Block": 10,
    "eip160Block": 10,
    "byzantiumBlock": 15,
    "constantinopleBlock": 15,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "nonce": "0x0000000000000042",
  "alloc": {
    "0x0000000000000000000000000000000000000001": {
      "balance": "1"
    },
    "0x0000000000000000000000000000000000000002": {
      "balance": "1"
    },
    "0x0000000000000000000000000000000000000003": {
      "balance": "1"
    },
    "0x0000000000000000000000000000000000000004": {
      "balance": "1"
    }
  },
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x3535353535353535353535353535353535353535353535353535353535353535",
  "gasLimit": "0x1000000",
  "difficulty": "0x10000",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x1acbaf36647743324f90d543c0058bb7ee31b407"
}
```

## geth.toml
```toml
[Eth]
NetworkId = 1337
SyncMode = "fast"
LightPeers = 20
DatabaseCache = 128
EnablePreimageRecording = false


[Eth.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 10
Percentile = 50

[Shh]
MaxMessageSize = 1048576
#MinimumAcceptedPOW = "2.0"

[Node]
DataDir = "/home/sheb/geth/data/geth.alpha"
KeyStoreDir = "/home/sheb/geth/keys/geth.alpha"
IPCPath = "/home/sheb/geth/data/geth.alpha.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8555
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth", "shh", "personal"]
WSPort = 8546
WSHost = "0.0.0.0"
WSOrigins = [ "localhost", "*"]
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = true
DiscoveryV5 = false
#DiscoveryV5Addr = ":30304"
# BootstrapNodes = []
# BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []
ListenAddr = "127.0.0.1:30303"
EnableMsgEvents = false
```

**Comment by sheb-gregor** [comment]
# FIX

In `geth.json` set:

```
  "extraData":"",
```

And now node started :)

**Comment by sheb-gregor** [comment]
Can be closed

**Comment by alonana** [comment]
Actually the solution is not accurate.
The extra data should include the signers addresses, as well as padding for extraVanity and extraSeal
See example at https://ethereum.stackexchange.com/questions/51091/clique-genesis-file
