### ISSUE TITLE
geth panics while syncing:  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by darren** [ethereum/go-ethereum#19305]
#### System information

Geth
Version: 1.8.22-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: darwin
GOPATH=/Users/darren/Sources/go
GOROOT=/usr/local/Cellar/go/1.11.5/libexec

#### Expected behaviour
sync ok

#### Actual behaviour
panic

#### Steps to reproduce the behaviour

geth --cache 4096 --datadir /Volumes/MDisk/ether/

#### Backtrace

````
INFO [03-20|22:27:11.720] Imported new state entries               count=1152 elapsed=5.538ms   processed=119829382 pending=13681 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:13.752] Imported new state entries               count=1920 elapsed=10.120ms  processed=119831302 pending=12742 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:17.060] Imported new state entries               count=1152 elapsed=4.878ms   processed=119832454 pending=15913 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:19.261] Imported new state entries               count=1920 elapsed=9.002ms   processed=119834374 pending=15503 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:21.084] Imported new state entries               count=1920 elapsed=10.071ms  processed=119836294 pending=14558 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:23.332] Imported new state entries               count=1920 elapsed=9.324ms   processed=119838214 pending=13961 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:25.375] Imported new state entries               count=1920 elapsed=9.758ms   processed=119840134 pending=13090 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:27.408] Imported new state entries               count=1920 elapsed=9.720ms   processed=119842054 pending=12581 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:30.078] Imported new state entries               count=768  elapsed=3.764ms   processed=119842822 pending=15352 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:32.208] Imported new state entries               count=1920 elapsed=8.991ms   processed=119844742 pending=15004 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:33.877] Imported new state entries               count=1536 elapsed=7.506ms   processed=119846278 pending=14556 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:35.932] Imported new state entries               count=1920 elapsed=10.103ms  processed=119848198 pending=13604 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:37.481] Imported new state entries               count=1536 elapsed=7.182ms   processed=119849734 pending=13288 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:38.677] Imported new block headers               count=1    elapsed=3.833ms   number=7406241 hash=abd7fe…1c4f42                                                                                                                        
INFO [03-20|22:27:39.545] Imported new state entries               count=1920 elapsed=10.359ms  processed=119851654 pending=12305 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:41.405] Imported new state entries               count=768  elapsed=3.665ms   processed=119852422 pending=13989 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:43.399] Imported new state entries               count=1920 elapsed=9.100ms   processed=119854342 pending=13442 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:45.081] Imported new state entries               count=1536 elapsed=7.724ms   processed=119855878 pending=13067 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:47.454] Imported new state entries               count=1920 elapsed=10.092ms  processed=119857798 pending=11981 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:51.509] Imported new state entries               count=1152 elapsed=5.367ms   processed=119858950 pending=15368 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:53.350] Imported new state entries               count=1536 elapsed=7.270ms   processed=119860486 pending=15025 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:55.442] Imported new state entries               count=1920 elapsed=9.239ms   processed=119862406 pending=14615 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:56.950] Imported new block headers               count=1    elapsed=3.871ms   number=7406242 hash=55b304…fe4573                                                                                                                        
INFO [03-20|22:27:57.732] Imported new state entries               count=1920 elapsed=10.066ms  processed=119864326 pending=13603 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:27:59.747] Imported new state entries               count=1920 elapsed=9.868ms   processed=119866246 pending=13024 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:28:01.663] Imported new state entries               count=1536 elapsed=8.100ms   processed=119867782 pending=12532 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:28:03.645] Imported new state entries               count=1920 elapsed=10.107ms  processed=119869702 pending=11624 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:28:05.548] Imported new state entries               count=1536 elapsed=7.662ms   processed=119871238 pending=11671 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:28:09.019] Imported new state entries               count=768  elapsed=3.641ms   processed=119872006 pending=13688 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:28:11.139] Imported new state entries               count=1920 elapsed=8.790ms   processed=119873926 pending=13460 retry=0   duplicate=11365 unexpected=40005                                                                             
INFO [03-20|22:28:12.202] Imported new block headers               count=2    elapsed=4.103ms   number=7406244 hash=4fbded…8f5b50                                                                                                                        
INFO [03-20|22:28:13.095] Imported new state entries               count=1920 elapsed=10.386ms  processed=119875846 pending=12323 retry=0   duplicate=11365 unexpected=40005                                                                             
WARN [03-20|22:28:13.173] Pivot became stale, moving               old=7406114 new=7406180
WARN [03-20|22:28:14.364] Rolled back headers                      count=2048 header=7406244->7404196 fast=7406113->7404196 block=0->0                                                                                                                   
WARN [03-20|22:28:14.364] Synchronisation failed, dropping peer    peer=4631cdc0dd565234 err="retrieved hash chain is invalid"                                                                                                                           
INFO [03-20|22:28:14.701] Imported new block headers               count=0    elapsed=1.556ms   number=7406244 hash=4fbded…8f5b50 ignored=96                                                                                                             
INFO [03-20|22:28:15.086] Imported new block receipts              count=0    elapsed=68.363µs  number=7406150 hash=58fa28…9229b9 age=23m56s    size=0.00B    ignored=2                                                                                  
INFO [03-20|22:28:16.951] Imported new block receipts              count=0    elapsed=78.643µs  number=7406157 hash=d8f9e5…4a845e age=21m46s    size=0.00B    ignored=7                                                                                  
INFO [03-20|22:28:17.778] Imported new block headers               count=1    elapsed=3.966ms   number=7406245 hash=6d8ced…8523cd                                                                                                                        
ERROR[03-20|22:28:20.838] Failed to unregister sync peer           peer=b6de6f4ff9f0aa27 err="peer is not registered"
ERROR[03-20|22:28:20.838] Peer removal failed                      peer=b6de6f4ff9f0aa27 err="peer is not registered"
WARN [03-20|22:28:21.469] Rolled back headers                      count=1    header=7406245->7406244 fast=7406157->7406157 block=0->0                                                                                                                   
WARN [03-20|22:28:21.469] Synchronisation failed, dropping peer    peer=5745aa00c4cf5e15 err="retrieved hash chain is invalid"                                                                                                                           
INFO [03-20|22:28:21.834] Imported new block headers               count=0    elapsed=1.412ms   number=7406245 hash=6d8ced…8523cd ignored=88                                                                                                             
INFO [03-20|22:28:22.518] Imported new block receipts              count=0    elapsed=69.892µs  number=7406159 hash=7b9d9f…87a0d1 age=21m46s    size=0.00B    ignored=2                                                                                  
INFO [03-20|22:28:22.916] Imported new block receipts              count=0    elapsed=68.786µs  number=7406161 hash=5f9db2…b456d3 age=21m28s    size=0.00B    ignored=2                                                                                  
WARN [03-20|22:28:24.006] Synchronisation failed, dropping peer    peer=4631cdc0dd565234 err="retrieved hash chain is invalid"                                                                                                                           
WARN [03-20|22:28:32.110] Ancestor below allowance                 peer=5745aa00c4cf5e15 number=7316161 hash=000000…000000 allowance=7316161                                                                                                             
WARN [03-20|22:28:32.110] Synchronisation failed, dropping peer    peer=5745aa00c4cf5e15 err="retrieved ancestor is invalid"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x4657d03]

goroutine 292567 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc0001e7040, 0xc05dd96780, 0xc0a41ce480, 0x0, 0x0, 0xc000040570)                                                                                                              
        /private/tmp/ethereum-20190201-36073-iknusg/go-ethereum-1.8.22/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:825 +0x15d3                                                                                     
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0001e7040, 0xc05dd96780, 0x7531f7f2e0e9eba6, 0xba76e3968879c024, 0xf7e6aad56a139493, 0x78fb64a843612319, 0xc07da44980, 0x0, 0x0)                                            
        /private/tmp/ethereum-20190201-36073-iknusg/go-ethereum-1.8.22/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:437 +0x37d                                                                                      
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0001e7040, 0xc0978c4990, 0x10, 0x7531f7f2e0e9eba6, 0xba76e3968879c024, 0xf7e6aad56a139493, 0x78fb64a843612319, 0xc07da44980, 0x1, 0x0, ...)                                  
        /private/tmp/ethereum-20190201-36073-iknusg/go-ethereum-1.8.22/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:406 +0x362                                                                                      
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc0001e7040, 0xc0978c4990, 0x10, 0x7531f7f2e0e9eba6, 0xba76e3968879c024, 0xf7e6aad56a139493, 0x78fb64a843612319, 0xc07da44980, 0x1, 0x4db4c00, ...)                            
        /private/tmp/ethereum-20190201-36073-iknusg/go-ethereum-1.8.22/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:324 +0x91                                                                                       
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc0001bf6c0, 0xc01e637080)
        /private/tmp/ethereum-20190201-36073-iknusg/go-ethereum-1.8.22/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:200 +0x313                                                                                                       
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /private/tmp/ethereum-20190201-36073-iknusg/go-ethereum-1.8.22/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:151 +0x269    
````

**Comment by holiman** [comment]
That's 1.8.22. I'm fairly certain we fixed this on master and also backported to 1.8, so should be fixed in 1.8.23. Leaving this open until confirmed (on mobile)
