### ISSUE TITLE
panic during normal operation: rlp encoding

### ISSUE THREAD

**Issue by maxgillett** [ethereum/go-ethereum#19349]
#### System information

Geth version: `master`
OS & Version: Linux
Commit hash : 313576530fe2ca0d37c6ddcdd8441030176c6c61

#### Expected behaviour

Normal operation. Blockchain fully synced, and running for 24+ hours

#### Actual behaviour

Panic

#### Steps to reproduce the behaviour

Unknown

#### Backtrace

````
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 116576940 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.9.2/src/reflect/value.go:1694 +0x1a3
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc4902de690, 0x0, 0x0, 0xfe8ca0, 0xc4902de690)
        /home/max/go/src/github.com/ethereum/go-ethereum/rlp/encode.go:183 +0x6a
github.com/ethereum/go-ethereum/rlp.EncodeToBytes(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/max/go/src/github.com/ethereum/go-ethereum/rlp/encode.go:101 +0xfe
github.com/ethereum/go-ethereum/trie.(*cachedNode).rlp(0xc42039c480, 0xc4255eb890, 0xc599794d98, 0xc53190a848)
        /home/max/go/src/github.com/ethereum/go-ethereum/trie/database.go:157 +0x76
github.com/ethereum/go-ethereum/trie.(*Database).Node(0xc42010c780, 0x0, 0x0, 0x0, 0x0, 0x426768, 0x20, 0xff34a0, 0x1, 0xc5069c4fc0)
        /home/max/go/src/github.com/ethereum/go-ethereum/trie/database.go:408 +0x2c6
github.com/ethereum/go-ethereum/core.(*BlockChain).TrieNode(0xc434e74000, 0x0, 0x0, 0x0, 0x0, 0xc4844abf50, 0xbf1f7404591e2d50, 0x3f5026c9b2fd, 0x1d3b520, 0x0)
        /home/max/go/src/github.com/ethereum/go-ethereum/core/blockchain.go:694 +0x69
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc42011c340, 0xc4802ed500, 0x0, 0x0)
        /home/max/go/src/github.com/ethereum/go-ethereum/eth/handler.go:569 +0x2285
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc42011c340, 0xc4802ed500, 0x0, 0x0)
        /home/max/go/src/github.com/ethereum/go-ethereum/eth/handler.go:321 +0x980
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc51ac9e600, 0x19bc880, 0xc498206360, 0x0, 0x0)
        /home/max/go/src/github.com/ethereum/go-ethereum/eth/handler.go:148 +0x1f2
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc498206360, 0xc51ac9e600, 0x19bc880, 0xc498206360)
        /home/max/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:361 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /home/max/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:360 +0x228

````

**Comment by ligi** [comment]
which chain?

**Comment by maxgillett** [comment]
Mainnet

**Comment by fjl** [comment]
This crash is due to `cachedNode.node` being nil. Not sure how it could end up being nil.

**Comment by karalabe** [comment]
This was fixed 1-2 months ago. Please update to latest `master` or latest stable release.
