### ISSUE TITLE
Les nodes with RPC invoke failure

### ISSUE THREAD

**Issue by fadeAce** [ethereum/go-ethereum#19445]
Geth
Version: 1.8.23-stable
Git Commit: c942700427557e3ff6de3aaf6b916e2f056c1ec2
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: darwin
GOPATH=/Users/terrill/main/envs/go:/Users/terrill/go
GOROOT=/Users/travis/.gimme/versions/go1.11.5.darwin.amd64

using ethclient in go-ethereum , to send TX but always get failed with geth crash
```
func TestSendEth(t *testing.T) {
	client, err := ethclient.Dial("http://127.0.0.1:8545")
	if err != nil {
		fmt.Println(err)
	}

	toAddress := common.HexToAddress("FC8eFa516089C2c1Fd606914c94137a98653b676")

	// make tx
	tx := types2.NewTransaction(1, toAddress, big.NewInt(21000000), 200000, big.NewInt(80000), nil)

	key := new(keystore.Key)

	// file testing

	fd, err := os.Open("key.dat")
	if err != nil {
		fmt.Println(err)
	}
	defer fd.Close()
	if err := json.NewDecoder(fd).Decode(key); err != nil {
		fmt.Println(err)
	}
	signTx, err := types2.SignTx(tx, &types2.HomesteadSigner{}, key.PrivateKey)
	fmt.Println(signTx.Hash())
	if err != nil {
		fmt.Println(err)
	}
	err = client.SendTransaction(context.TODO(), signTx)
	if err != nil {
		fmt.Println("error :", err)
	}
	fmt.Println(signTx.Hash().Hex())
}
```

and failed logs like
```
INFO [04-11|17:45:12.328] Imported new block headers               count=2 elapsed=143.822ms number=4189768 hash=fdc7fd…aeef57 ignored=1
INFO [04-11|17:45:14.761] Imported new block headers               count=1 elapsed=17.321ms  number=4189769 hash=6e0834…ac9794
INFO [04-11|17:45:29.694] Imported new block headers               count=1 elapsed=989.952µs number=4189770 hash=8c5846…6d0c6a
INFO [04-11|17:45:44.556] Imported new block headers               count=1 elapsed=13.500ms  number=4189771 hash=08a814…3f1c64
INFO [04-11|17:45:59.701] Imported new block headers               count=1 elapsed=1.052ms   number=4189772 hash=982219…e97a3f
INFO [04-11|17:46:14.585] Imported new block headers               count=1 elapsed=11.295ms  number=4189773 hash=053ef8…9cbf3b
INFO [04-11|17:46:16.293] Submitted transaction                    fullhash=0x0b366310977a8e72b72ea774a98994c2d9527f4c1cd9e2ca2f567d98320bc55e recipient=0xFC8eFa516089C2c1Fd606914c94137a98653b676
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4726e70]

goroutine 13 [running]:
github.com/ethereum/go-ethereum/les.(*peer).GetRequestCost(0xc0000f9810, 0xc, 0x1, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/les/peer.go:166 +0xa0
github.com/ethereum/go-ethereum/les.(*LesTxRelay).send.func1(0x4e16e80, 0xc0000f9810, 0xc011543d01)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/les/txrelay.go:121 +0x4e
github.com/ethereum/go-ethereum/les.(*requestDistributor).nextRequest(0xc010671900, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/les/distributor.go:195 +0x2b1
github.com/ethereum/go-ethereum/les.(*requestDistributor).loop(0xc010671900)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/les/distributor.go:129 +0x7f
created by github.com/ethereum/go-ethereum/les.newRequestDistributor
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/les/distributor.go:80 +0xf9
```

Rinkeby env activated in cmd :
./geth --rinkeby --syncmode "light" --rpc

**Comment by karalabe** [comment]
Please upgrade to Geth v1.8.26 https://github.com/ethereum/go-ethereum/releases/tag/v1.8.26
