### ISSUE TITLE
http RPC deadlock 

### ISSUE THREAD

**Issue by DmitryNevmerzhitsky** [ethereum/go-ethereum#19714]
I find rpc deadlock with http backend on CallContext func.

https://github.com/ethereum/go-ethereum/blob/f213ceb83f4d915089347485721b1f99b71596f0/rpc/client.go#L277-L304

http backed use sendHTTP func.
https://github.com/ethereum/go-ethereum/blob/f213ceb83f4d915089347485721b1f99b71596f0/rpc/http.go#L128-L150

where response send to requestOp.resp chan.
next step is waiting requestOp.wait.

https://github.com/ethereum/go-ethereum/blob/f213ceb83f4d915089347485721b1f99b71596f0/rpc/client.go#L136-L148
but if context cancel then select chose pseudorandom case and it can be context.Done case.
https://github.com/ethereum/go-ethereum/blob/f213ceb83f4d915089347485721b1f99b71596f0/rpc/client.go#L138-L144

in this case we try send requestOp to client.reqTimeout but it receive only in dispatch func than use only in not http backend. Or  waiting for closing client.

this is my routines trace.
```
goroutine 9105 [select, 37 minutes]:
casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc.(*requestOp).wait(0xc0007e5a00, 0xf14ac0, 0xc0002ec840, 0xc0002c6900, 0xd2e2c0, 0xc000191260, 0x0)
	/go/src/casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc/client.go:140 +0x1bf
casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).CallContext(0xc0002c6900, 0xf14ac0, 0xc0002ec840, 0xc1fbc0, 0xc00075a038, 0xdc5b0f, 0x19, 0xc0002ebe40, 0x1, 0x1, ...)
	/go/src/casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc/client.go:294 +0x201
casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).TransactionReceipt(0xc000011898, 0xf14ac0, 0xc0002ec840, 0xa2f5febd42840c14, 0x71500d6e30624c8e, 0x1b1607afa4c10ddb, 0x1363d59fcff65d58, 0x40, 0x40, 0xd34cc0)
	/go/src/casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:262 +0x136
casino_croupier_bot/app/pkg/eth/ethcli.(*Client).loadReceipts.func1(0xf14ac0, 0xc0002ec840, 0xa2f5febd42840c14, 0x71500d6e30624c8e, 0x1b1607afa4c10ddb, 0x1363d59fcff65d58, 0x15, 0x2, 0x0)
	/go/src/casino_croupier_bot/app/pkg/eth/ethcli/handle_events.go:192 +0x88
casino_croupier_bot/app/pkg/eth/ethcli.(*Client).loadReceipts.func2(0x0, 0x0)
	/go/src/casino_croupier_bot/app/pkg/eth/ethcli/handle_events.go:212 +0x485
casino_croupier_bot/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000bffe30, 0xc00078e420)
	/go/src/casino_croupier_bot/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by casino_croupier_bot/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/casino_croupier_bot/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66

goroutine 9138 [select, 37 minutes]:
casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc.(*requestOp).wait(0xc000b76240, 0xf14ac0, 0xc0002ec840, 0xc0002c6900, 0xd2e2c0, 0xc00017e310, 0x0)
	/go/src/casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc/client.go:140 +0x1bf
casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).CallContext(0xc0002c6900, 0xf14ac0, 0xc0002ec840, 0xc1fbc0, 0xc00075a770, 0xdc5b0f, 0x19, 0xc00048f9c0, 0x1, 0x1, ...)
	/go/src/casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/rpc/client.go:294 +0x201
casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).TransactionReceipt(0xc000011898, 0xf14ac0, 0xc0002ec840, 0xdd8c136fc77135ab, 0x4ae2b2af69d2e565, 0x7bd6baba10875bee, 0x26ec88ce6684c905, 0x40, 0x40, 0xd34cc0)
	/go/src/casino_croupier_bot/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:262 +0x136
casino_croupier_bot/app/pkg/eth/ethcli.(*Client).loadReceipts.func1(0xf14ac0, 0xc0002ec840, 0xdd8c136fc77135ab, 0x4ae2b2af69d2e565, 0x7bd6baba10875bee, 0x26ec88ce6684c905, 0x36, 0x2, 0x0)
	/go/src/casino_croupier_bot/app/pkg/eth/ethcli/handle_events.go:192 +0x88
casino_croupier_bot/app/pkg/eth/ethcli.(*Client).loadReceipts.func2(0x0, 0x0)
	/go/src/casino_croupier_bot/app/pkg/eth/ethcli/handle_events.go:212 +0x485
casino_croupier_bot/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000bffe30, 0xc00078f080)
	/go/src/casino_croupier_bot/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by casino_croupier_bot/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/casino_croupier_bot/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

maybe should use 
```
if !c.isHTTP {
	select {
	case c.reqTimeout <- op:
	case <-c.closing:
	}
}
````

**Comment by fjl** [comment]
Very nice catch!
