### ISSUE TITLE
Geth attach no longer works

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#1972]
```
jbrown@akalabeth:~/go-ethereum$ build/bin/geth attach
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xb0 pc=0x60edf0]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/rpc/api.ParseApiString(0xc820252180, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/api/utils.go:168 +0xb60
main.(*jsre).apiBindings(0xc820236ee0, 0x7f95041db788, 0xc820236ee0, 0x0, 0x0)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:279 +0x28f
main.newLightweightJSRE(0xc820250930, 0x1, 0x7f95041da570, 0xc820252000, 0xc820197f00, 0x16, 0x16f3901, 0x0)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:156 +0x16c
main.attach(0xc82019d560)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:440 +0x3fb
github.com/codegangsta/cli.Command.Run(0xe7abb0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfb4e20, 0x42, 0x10b19a0, ...)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:131 +0x1055
github.com/codegangsta/cli.(*App).Run(0xc82019d320, 0xc82000a440, 0x2, 0x2, 0x0, 0x0)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:175 +0xfd6
main.main()
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:372 +0x93

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x16f5340)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x67
created by github.com/ethereum/go-ethereum/logger/glog.init.1
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x6f

goroutine 18 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x624
created by github.com/ethereum/go-ethereum/logger.init.1
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x2b

goroutine 21 [select]:
github.com/ethereum/go-ethereum/jsre.(*JSRE).runEventLoop(0xc820246660)
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/jsre/jsre.go:139 +0xd18
created by github.com/ethereum/go-ethereum/jsre.New
	/home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/jsre/jsre.go:67 +0x139
```

**Comment by drupalnomad** [comment]
e165c2d23cf29fdec51c59f42f74735be2a8e1ff is the commit that introduced the regression

**Comment by karalabe** [comment]
@drupalnomad Could you please check https://github.com/ethereum/go-ethereum/pull/1974?
