### ISSUE TITLE
concurrent map access panic on rinkeby signer shutdown

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#19965]
I was updating our rinkeby signer to latest master, and hit a concurrent map read/write panic when shutting down the previous binary.

#### System information

Geth version: `geth-1.9.2-unstable-e46a01d5-20190801`
OS & Version: Linux
Commit hash : e46a01d5

#### Expected behaviour

Geth should stop w/o panicking.

#### Actual behaviour

When doing our bi-weekly update of our rinkeby signer to the latest master, the previous binary panicked on shutdown:

```
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]: fatal error: concurrent map read and map write
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]: goroutine 157983496 [running]:
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]: runtime.throw(0x1151601, 0x21)
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]:         /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc111cd9590 sp=0xc111cd9560 pc=0x4430d2
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]: runtime.mapaccess2(0xfb4560, 0xc0001f4750, 0xc111cd9678, 0x246e9e0, 0xc038350400)
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]:         /usr/local/go/src/runtime/map.go:472 +0x272 fp=0xc111cd95d8 sp=0xc111cd9590 pc=0x4234c2
Aug 14 23:43:18 ip-10-0-22-38 geth[13503]: github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc00020eb00, 0xed8e1e9ffe9cdb37, 0xb8ef5fc4abc3ef69, 0xfa66c2eb2e4a6be0, 0x16b7df03cead0450, 0x13e0960, 0xc0087354c0, 0xc048492988, 0x0, 0x0)
```

Full log attached below.

#### Steps to reproduce the behaviour

Shutdown a node running commit e46a01d5.  Not sure if it needs to be a Clique signer or not.

#### Backtrace

Attached.

[geth-1.9.2-unstable-e46a01d5-20190801-panic.log](https://github.com/ethereum/go-ethereum/files/3503818/geth-1.9.2-unstable-e46a01d5-20190801-panic.log)

**Comment by karalabe** [comment]
Based on the logs the error seems to be a rare race where Geth is shut down exactly when the miner found a block and is updating it's new state (hey, congrats, you managed to hit a 10ms window :D). The issue seems to be that the miner calls a block insertion on the chain, but this is not synchronized with chain termination, so the miner-insert changes the trie and concurrently the shutdown started flushing the trie.

**Comment by ryanschneider** [comment]
FWIW this seems to happen just about every time we update our rinkeby signer, still occurring with `1.9.7-unstable-73003659-20191016`:

```
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: fatal error: concurrent map read and map write
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: goroutine 143027533 [running]:
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: runtime.throw(0x116a0b3, 0x21)
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]:         /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc010702d20 sp=0xc010702cf0 pc=0x4430d2
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: runtime.mapaccess2(0xfca4c0, 0xc001245a10, 0xc010702e08, 0x20, 0xc0017e33e0)
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]:         /usr/local/go/src/runtime/map.go:472 +0x272 fp=0xc010702d68 sp=0xc010702d20 pc=0x4234c2
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc001a12000, 0xfc67f6f8c03cea2d, 0x3d07dfe47caf6436, 0xf470f8c86e41cd34, 0x35bc637f908b2def, 0x1407d60,
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]:         /ext-go/1/src/github.com/ethereum/go-ethereum/trie/database.go:774 +0xa8 fp=0xc010702e58 sp=0xc010702d68 pc=0x6a0238
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc001a12000, 0x50bc5297dfefe6b5, 0x7f2c69053d6f7ad3, 0xd907ee1462f67932, 0xa5641a809ddc18a9, 0x1407d60,
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]:         /ext-go/1/src/github.com/ethereum/go-ethereum/trie/database.go:779 +0x184 fp=0xc010702f48 sp=0xc010702e58 pc=0x6a0314
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc001a12000, 0xa4a0503ccb6d82cc, 0x530c3b981d395b78, 0x372d23aebb08b36f, 0x9d6ea4ca33525342, 0x1407d60,
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]:         /ext-go/1/src/github.com/ethereum/go-ethereum/trie/database.go:779 +0x184 fp=0xc010703038 sp=0xc010702f48 pc=0x6a0314
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]: github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc001a12000, 0xc6f2d0acac044c9e, 0xbab0718a5b29e00e, 0x4c09416e02ceebcc, 0xaaa85dafecf5c8fe, 0x1407d60,
Oct 16 17:30:05 ip-10-0-22-38 geth[11685]:         /ext-go/1/src/github.com/ethereum/go-ethereum/trie/database.go:779 +0x184 fp=0xc010703128 sp=0xc010703038 pc=0x6a0314
```

As I mentioned in #20175 we're still building w/ go 1.12 since I haven't figured out how to cross-compile w/ go 1.13, maybe this issue is unique to the older toolchain?

**Comment by shazow** [comment]
Also reproduced on

```
Version: 1.9.10-unstable
Git Commit: a67fe48b43bfaa750d264bab54c1ea1a15c2a8f7
Git Commit Date: 20191220
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.4
```

**Comment by ryanschneider** [comment]
This is still happening on 1.10.x as of `Geth/v1.10.1-unstable-dab90e4d-20210304/linux-amd64/go1.16` here's the latest incident logs: 

https://gist.github.com/ryanschneider/0afc3cdd07f273316c0056d7bb0640a2
