### ISSUE TITLE
nil pointer leading to 0 sized .log file - leading to "seek: invalid argument"

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/go-ethereum#19975]
#### System information

Geth version: `1.9.1-stable-b7b2f60f`
OS & Version: Linux

#### Actual behaviour
This might be related to geth running with `--dashboard`. I guess this is two bugs in one, the first one is: 

```
WARN [08-18|04:59:38.525] Number of active peers is greater than the limit
WARN [08-18|04:59:38.531] Number of active peers is greater than the limit
WARN [08-18|04:59:38.532] Number of active peers is greater than the limit
WARN [08-18|04:59:38.532] Number of active peers is greater than the limit
WARN [08-18|04:59:38.533] Number of active peers is greater than the limit
WARN [08-18|04:59:38.682] Synchronisation failed, dropping peer    peer=0014af2e0b97fb9e err="action from bad peer ignored"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x563c77fc56f5]
goroutine 10895188 [running]:
github.com/ethereum/go-ethereum/log.(*countingWriter).Close(...)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler.go:94
github.com/ethereum/go-ethereum/log.RotatingFileHandler.func1(0xc0b826b680, 0x0, 0x0)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler.go:164 +0x2a5
github.com/ethereum/go-ethereum/log.funcHandler.Log(0xc000453300, 0xc0b826b680, 0x0, 0x0)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler.go:36 +0x32
github.com/ethereum/go-ethereum/log.MultiHandler.func1(0xc0b826b680, 0xc02d5adc58, 0x8)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler.go:319 +0x69
github.com/ethereum/go-ethereum/log.funcHandler.Log(0xc00020cb00, 0xc0b826b680, 0x563c77de202e, 0x563c795d0f58)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler.go:36 +0x32
github.com/ethereum/go-ethereum/log.(*GlogHandler).Log(0xc000169d50, 0xc0b826b680, 0xa0, 0x563c78fc12a0)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler_glog.go:202 +0x4df
github.com/ethereum/go-ethereum/log.(*swapHandler).Log(0xc00003c780, 0xc0b826b680, 0x563c7846c9b8, 0xc02d5ade50)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/handler_go14.go:14 +0x7a
github.com/ethereum/go-ethereum/log.(*logger).write(0x563c79879ee0, 0x563c78875f59, 0x25, 0x2, 0xc02d5ade50, 0x4, 0x4, 0x2)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/logger.go:134 +0x238
github.com/ethereum/go-ethereum/log.Warn(...)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/log/root.go:49
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc007c7c000, 0xc0501f1f60, 0x10, 0x3b5ca6569bc3da78, 0xdb84037536eacd98, 0xb27bab0cfd9389b2, 0x15f6a27fc35d8e63, 0xc0321bf060, 0x0, 0x0, ...)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:331 +0x32f
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc007c48000, 0xc0cc457380)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:190 +0x2e8
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:712 +0xbe0
```
This lead to a 0 bytes sized `geth/logs/19081804593853.log` file - which made geth unable to start:

`seek geth/logs/19081804593853.log: invalid argument`

**Comment by fjl** [comment]
We are removing the directory logger as part of removing the dashboard code.
