### ISSUE TITLE
Solidity and Web3js codes are not working inside the private Ethereum(geth) network but same codes are working in public ethereum

### ISSUE THREAD

**Issue by NithinTD** [ethereum/go-ethereum#19980]
geth version : 1.9.0-stable-52f24617,
     node version : v10.16.3,
     npm version  : 6.9.0,
     web3 version : -- web3@1.0.0-beta.36.

genesis.json:
     
    {
    "config": {
    "chainId": 9663080,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "Ethash": {
      "period": 15,
      "epoch": 30000
    }
    },
    "nonce": "0x0",
    "timestamp": "0x5d5769ad",
    "gasLimit": "0x7FFFFFFFFFFFF",
    "difficulty": "0x1",
    "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
    "alloc": {
    "0x02731Eb61f258C104F1BB4191cF715d8D1014CD3": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
     },
    "number": "0x0",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    }

1. In geth deployment of the smart contract is working, while calling 
   functionalities I am facing some issues.

2.both web3 code and solidity codes are working in public ethereum but the 
  same codes are not working in private network(geth). 

3. Is there any problem with my geth or genesis.json.

Web3js error:
          
        Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (/home/nithin/project/ConnectedVehicles/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (/home/nithin/project/ConnectedVehicles/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (/home/nithin/project/ConnectedVehicles/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (/home/nithin/project/ConnectedVehicles/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/home/nithin/project/ConnectedVehicles/node_modules/web3-core-method/src/index.js:473:33)
    at /home/nithin/project/ConnectedVehicles/node_modules/web3-core-requestmanager/src/index.js:147:9
    at XMLHttpRequest.request.onreadystatechange (/home/nithin/project/ConnectedVehicles/node_modules/web3-providers-http/src/index.js:91:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/nithin/project/ConnectedVehicles/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/nithin/project/ConnectedVehicles/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/nithin/project/ConnectedVehicles/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/nithin/project/ConnectedVehicles/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

I connected to the private(geth) from the remix and I deployed the smart contract and(1) while calling functionality data is not coming. and 
(2)in the hash column, it is showing call+transaction hash

  [![remix status bar][1]][1]

  [1]: https://i.stack.imgur.com/fMCyr.png

**Comment by karalabe** [comment]
You need to enable the Constanintople and Petersburg forks in your network. Please see my previous answer on another issue on how to: https://github.com/ethereum/go-ethereum/issues/19976#issuecomment-522524158

**Comment by NithinTD** [comment]
I used the updated JSON but I am getting below error

    panic: runtime error: makeslice: len out of range

    goroutine 60 [running]:
    github.com/ethereum/go-ethereum/consensus/clique.(*Clique).snapshot(0xc00018efc0, 0x1381fc0, 0xc0052f4000, 0x0, 0x766a93acaadad036, 0x5ba93a05a386ac2b, 0x4c4293f478f1a5cc, 0xfed88f49de2386d, 0x0, 0x0, ...)
	/build/ethereum-23hs5A/ethereum- 
        1.9.2+build19708+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/clique/clique.go:377 +0x48c
github.com/ethereum/go-ethereum/consensus/clique.(*Clique).Prepare(0xc00018efc0, 0x1381fc0, 0xc0052f4000, 0xc0001b0240, 0xfed88f49de2386d, 0x40)
	/build/ethereum-23hs5A/ethereum-1.9.2+build19708+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/clique/clique.go:497 +0xcc
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc0000ae4e0, 0xc0002460e0, 0x0, 0x5d665a44)
	/build/ethereum-23hs5A/ethereum-1.9.2+build19708+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:865 +0x3a6
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc0000ae4e0)
	/build/ethereum-23hs5A/ethereum-1.9.2+build19708+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:408 +0xbe3
created by github.com/ethereum/go-ethereum/miner.newWorker
	/build/ethereum-23hs5A/ethereum-1.9.2+build19708+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:216 +0x4ec
