### ISSUE TITLE
LES `panic` due to nil balance tracker

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#20008]
Happens on latest master,  `v1.9.2` is not affected.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7c3b6]
goroutine 8918 [running]:
github.com/ethereum/go-ethereum/les.(*balanceTracker).requestCost(0x0, 0x91fa8)
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/balance.go:258 +0x26
  github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg.func2(0xf4711b098e35afa1, 0xc0, 0xc098b47540, 0x5f42c0)
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server_handler.go:246 +0x246
  github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg.func3(0xc04ada5240, 0xc077a50148, 0xc0b5ad84e0, 0xc048569220, 0xc045965680, 0xc0b383ed80)
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server_handler.go:362 +0xc96
  created by github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server_handler.go:276 +0xd9c
```

**Comment by rjl493456442** [comment]
After some investigation, I think there exist at least two issues:

* If a new inbound peer is not accepted by client pool(client pool is full), we should disconnect this peer instead of assigning a "fake" balance tracker which used for testing.
* Whenever server handler receives a msg from client peer, it will put the processing procedure in a routine. But if the peer is evicted, we should check all in-flight routines before removing it(for example, assign the balanceTracker to nil).

Working on the fix now.
