### ISSUE TITLE
trie.mustDecodeNode: invalid number of list elements: 0

### ISSUE THREAD

**Issue by felberj** [ethereum/go-ethereum#20037]
Hi there,

I am using geth as a library to access the Ethereum blockchain.

Short version of what I am doing:

1. I create a new ETH Node with a datadir that contains the full archive blockchain data
2. I then spawn many goroutines
3. Each of the routines then compute the state of a 'random' block and then trace that block with a "tracer". I go through the blockchain backwards.

I will continue to run queries and update this issue with more logs. In the meantime, I would be grateful if you can tell me whether this looks like a race condition or whether my blockchain data is corrupt. If you need more information, let me know and I will update this issue.

```go
// Tracer allows to trace blocks with a given tracer
type Tracer struct {
	eth    *eth.Ethereum // shared among goroutines
}

// computeBlockStartState creates a statedb that represents the state before that block.
func (t *Tracer) computeBlockStartState(block *types.Block) (*state.StateDB, error) {
	parent := t.eth.BlockChain().GetBlock(block.ParentHash(), block.NumberU64()-1)
	if parent == nil {
		return nil, errors.Errorf("parent %v not found", block.ParentHash())
	}
	statedb, err := t.eth.BlockChain().StateAt(parent.Root())
	if err != nil {
		// it this error is triggered, we might need to implement the following from the official ETH client:
		// (api *PrivateDebugAPI) computeStateDB
		return nil, errors.Wrap(err, "required historical state unavailable")
	}
	return statedb, nil
}

// traceBlock invokes the provided tracer for each transaction in the provided block.
func (t *Tracer) traceBlock(ctx context.Context, block *types.Block, statedb *state.StateDB, tracer Tracerer) error {
	// Recompute transactions up to the target index.
	signer := types.MakeSigner(t.config, block.Number())

	for ind, tx := range block.Transactions() {
		// Assemble the transaction call message and return if the requested offset
		msg, _ := tx.AsMessage(signer)
		context := core.NewEVMContext(msg, block.Header(), t.eth.BlockChain(), nil)

		// Not yet the searched for transaction, execute on top of the current state
		vmenv := vm.NewEVM(context, statedb, t.config, vm.Config{
			Debug:  true,
			Tracer: tracer,
		})
		if _, _, _, err := core.ApplyMessage(vmenv, msg, new(core.GasPool).AddGas(tx.Gas())); err != nil {
       return err
		}
		// Ensure any modifications are committed to the state
		// Only delete empty objects if EIP158/161 (a.k.a Spurious Dragon) is in effect
		statedb.Finalise(vmenv.ChainConfig().IsEIP158(block.Number()))
	}
	return nil
}
```

I do not want to modify my blockchain data (but unfortunately cannot make the directory readonly, because Geth does not have an option for that). Unfortunately, my queries sometimes panic, so I assumed my blockchain data just gets corrupted sometimes. But because the crashes appear so far apart, I think there could be a rare race condition in the Geth client.

Crashes I recorded so far:

#### 1

2019/09/05 05:25:38 Crashed in block 5404366 in tx db4d6a12865bf5c8cc1967e27d437499c1d463903f007ba9e172b27305bbb8e6
2019/09/05 05:25:38 Unable to finish task of block 5404366: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0
panic: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0 [recovered]
        panic: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0 [recovered]
        panic: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0

#### 2

**IMPORTANT: THIS WAS USING THE GETH 1.8.23 CLIENT**

2019/09/03 03:16:16 Crashed in block 4488802 in tx 326f7e6a155ee9c3fb6de2054f88a293f656e42702fc417889b2746bf347217a
2019/09/03 03:16:16 Unable to finish task of block 4488802: node 4aae31425048fff647b005ba389194be49335146d5a184808fe1a0f53d007c7f: decode error: rlp: expected List
panic: node 4aae31425048fff647b005ba389194be49335146d5a184808fe1a0f53d007c7f: decode error: rlp: expected List [recovered]
        panic: node 4aae31425048fff647b005ba389194be49335146d5a184808fe1a0f53d007c7f: decode error: rlp: expected List [recovered]
        panic: node 4aae31425048fff647b005ba389194be49335146d5a184808fe1a0f53d007c7f: decode error: rlp: expected List

#### System information

Geth version: `1.9.2`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

Running many block in parallel with the same ETH node does not indeterministically crash the decoder?

#### Actual behaviour

Tracer crashes while accessing the ethereum data. If I rerun the block where the tracer crashed, it works fine. Rerunning the tracer over the same blockchain crashes in a different block.

#### Steps to reproduce the behaviour

Unfortunately, I cannot yet release this code, as I am in the middle of my research.
But it might work like this:

1. Create a ETH Node with the full archive blockchain data available
2. Trace many block in parallel, while going backwards through the blockchain.

#### Backtrace

````
panic: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0 [recovered]
        panic: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0 [recovered]
        panic: node 6976b996538d306f6dc8e6da17a4dc0ec94b9d8a5ec81807b0132505af472e8d: invalid number of list elements: 0

goroutine 440 [running]:
panic(0xe2ba00, 0xc3df0a2430)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc160db57a0, 0x20, 0x20, 0xc2971e0000, 0x114, 0x114, 0x0, 0x0)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/node.go:111 +0x196
github.com/ethereum/go-ethereum/trie.(*Database).node(0xc000196800, 0x6f308d5396b97669, 0xedca417dae6c86d, 0x718c85e8a9d4bc9, 0x8d2e47af052513b0, 0xc1
60db5540, 0x20)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/database.go:390 +0x46d
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc201fdc7d0, 0xc160db55a0, 0x20, 0x20, 0xc239ccc5a0, 0x3, 0x41, 0x2000c2bc4c5790, 0xc160db55
60, 0x214, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:398 +0xe3
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc201fdc7d0, 0x11cae60, 0xc34ff1f8c0, 0xc239ccc5a0, 0x41, 0x41, 0x3, 0x214, 0x2c, 0x214, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:133 +0xf8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc201fdc7d0, 0x11c9120, 0xc1c7ea3180, 0xc239ccc5a0, 0x41, 0x41, 0x2, 0x11c9120, 0xc1c7ea3180, 0x0
, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:126 +0x6c0
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc201fdc7d0, 0x11cae60, 0xc34ff1f7e0, 0xc239ccc5a0, 0x41, 0x41, 0x2, 0x20, 0x240, 0xecf500, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:137 +0x20a
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc201fdc7d0, 0x11c9120, 0xc1c7ea3040, 0xc239ccc5a0, 0x41, 0x41, 0x1, 0x11c9120, 0xc1c7ea3040, 0x0
, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:126 +0x6c0
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc201fdc7d0, 0x11cae60, 0xc2d869e680, 0xc239ccc5a0, 0x41, 0x41, 0x1, 0xc2bc4c5e08, 0x42aa39, 0xc2
39ccc5a0, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:137 +0x20a
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc201fdc7d0, 0x11c9120, 0xc1c5c0ca00, 0xc239ccc5a0, 0x41, 0x41, 0x0, 0x20, 0xc201fdc7e8, 0x20, ..
.)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:126 +0x6c0
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc201fdc7d0, 0xc201fdc7e8, 0x20, 0x20, 0xc201fdc7e8, 0x20, 0x20, 0xda8dc0, 0xc1006d0480)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/trie.go:101 +0x7b
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc201fdc7d0, 0xc38f429e20, 0x20, 0x20, 0xc201fdc7d0, 0xc2bc4c606c, 0xc173b708b0, 0xc1544f99
bc, 0x0)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/trie/secure_trie.go:79 +0x7b
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetCommittedState(0xc244464620, 0x11de5c0, 0xc012aabca0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/state/state_object.go:196 +0x178
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetState(0xc244464620, 0x11de5c0, 0xc012aabca0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/state/state_object.go:177 +0x147
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetState(0xc30e5bf440, 0xf23784e8e679240, 0xa38fbc0f4c53a146, 0x2b898097, 0x0, 0x0, 0x0, 0x0, 0x
0, 0x0, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/state/statedb.go:285 +0x99
github.com/ethereum/go-ethereum/core/vm.opSload(0xc10b6acff8, 0xc3d5c12000, 0xc3462d2300, 0xc24c480340, 0xc24c480360, 0xc8, 0xc24c480340, 0xc24c480360
, 0xc3462d2300, 0x1)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/vm/instructions.go:631 +0x115
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc3d5c12000, 0xc3462d2300, 0xc330e5c9b0, 0x44, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/vm/interpreter.go:268 +0x47e
github.com/ethereum/go-ethereum/core/vm.run(0xc3d3644000, 0xc3462d2300, 0xc330e5c9b0, 0x44, 0x44, 0xc3462d2300, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/vm/evm.go:67 +0x276
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc3d3644000, 0x11be300, 0xc28e667740, 0xf23784e8e679240, 0xa38fbc0f4c53a146, 0x2b898097, 0xc330e5
c9b0, 0x44, 0x44, 0xb658, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/vm/evm.go:242 +0x519
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc13d612bd0, 0x11e1b60, 0xc308880300, 0xc33abc3180, 0xc13d612bd0, 0xc308880300,
0xc308880300, 0xf70120)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/state_transition.go:213 +0x3a9
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc3d3644000, 0x11e1b60, 0xc308880300, 0xc33abc3180, 0xc7939ac213f81f33, 0xada03468, 0xc1f3d7af80, 0
xee098337d544bc52, 0x1bde71bf3915bf2a, 0xb5e37b7d, ...)
        /home/vagrant/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/core/state_transition.go:132 +0x5b
felberj/tracer.(*Tracer).traceBlock(0xc03fda31e0, 0x11d87a0, 0xc000272d80, 0xc3469a2240, 0xc30e5bf440, 0x11bca20, 0xc19f92aac8, 0x0, 0x0)
        /home/vagrant/shared/trace_block.go:50 +0x596
felberj/tracer.(*Tracer).TraceBlockByNumber(0xc03fda31e0, 0x11d87a0, 0xc000272d80, 0x5276ce, 0x11bca20, 0xc19f92aac8, 0x0, 0x0)
````

**Comment by holiman** [comment]
Thanks for reporting this. We don't know what the issue is, and need to investigate this further. Let us know if you manage find some way to reproduce this  more deterministaically.

**Comment by rjl493456442** [comment]
I am working on a tool to repair the broken state. Hopefully, the tool can be used to fix it

**Comment by fjl** [comment]
For reference, this kind of issue was previously reported in https://github.com/ethereum/go-ethereum/issues/15105

**Comment by holiman** [comment]
How do you invoke `func (t *Tracer) traceBlock(ctx context.Context, block *types.Block, statedb *state.StateDB, tracer Tracerer) error {` ? You take state as a pointer input, so it might mean that you're being bit by some comcurrency issue. A statedb is not concurrecy safe

**Comment by karalabe** [comment]
Still, there's not much to go on here. If you could share your code, we might check if the concurrency is ok. Otherwise there are quite a few things than can go wrong that we can't see.
