### ISSUE TITLE
Fatal: Error starting protocol stack: missing block number for head header hash

### ISSUE THREAD

**Issue by CamposBruno** [ethereum/go-ethereum#20067]
Hi there!

I got this error right before the Geth almost full sync:
````
Fatal: Error starting protocol stack: missing block number for head header hash
````
I'm using a EC2 only for the Ethereum node, nothing else is running on this vm.
My EC2 is a t2.Xlarge with 16GB RAM and 8 Cores
My storage is 800GB EBS with 2400 IOPS

Is there a way to fix this ? or revert some of the blocks and continue with sync ?
Don't want to start syncing from the start again.

#### System information

Geth version: `1.9.3-stable`
Go : go1.12.9.linux.amd64
OS & Version: CentOS Linux

#### Expected behaviour

Geth to sincronize 

#### Actual behaviour

I get this error when almost finishing full sync:

````
Fatal: Error starting protocol stack: missing block number for head header hash
````

#### Steps to reproduce the behaviour

I ran Geth with the following parameters :

````
geth --datadir ~/NODES/ethmainnet --identity GMCNODE --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0" --rpcport "8545" --syncmode "full" --nousb  --cache=512
````

#### Backtrace

````
INFO [09-11|03:45:53.635] Imported new block headers               count=1    elapsed=5.737ms      number=8526160 hash=895afb…3fe6e3
INFO [09-11|03:45:54.777] Imported new state entries               count=1152 elapsed=7.497ms      processed=136478888 pending=15668 retry=0    duplicate=11455 unexpected=194705
INFO [09-11|03:45:55.473] Imported new state entries               count=1152 elapsed=5.237ms      processed=136480040 pending=16892 retry=0    duplicate=11455 unexpected=194705
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 5ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 10ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 20ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 5ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 10ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 20ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 40ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 80ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 160ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 320ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 640ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x84d1a41]

goroutine 479884 [running]:
github.com/ethereum/go-ethereum/core.(*HeaderChain).SetCurrentHeader(0xaffbc20, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/headerchain.go:460 +0xf1
github.com/ethereum/go-ethereum/core.(*BlockChain).Rollback(0x105a0000, 0x3774e000, 0x800, 0x800)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:881 +0x24b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders.func1(0x261b7ec8, 0x106bc000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1374 +0x189
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders(0x106bc000, 0x821951, 0x0, 0x821843, 0x0, 0x4e7944a0, 0x8e2b7d0, 0xae58440)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1393 +0x1179
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func6(0x4, 0x8c40924)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:517 +0x49
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0x106bc000, 0x4cb0d980, 0x5b7f9620)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:534 +0x46
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:534 +0x8c
INFO [09-11|03:51:27.022] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-11|03:51:27.023] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-11|03:51:27.025] Starting peer-to-peer node               instance=Geth/GMCNODE/v1.9.3-stable-cfbb969d/linux-386/go1.12.9
INFO [09-11|03:51:27.025] Allocated trie memory caches             clean=128.00MiB dirty=128.00MiB
INFO [09-11|03:51:27.025] Allocated cache and file handles         database=/home/centos/NODES/ethmainnet/geth/chaindata cache=256.00MiB handles=2048
INFO [09-11|03:51:29.848] Opened ancient database                  database=/home/centos/NODES/ethmainnet/geth/chaindata/ancient
Fatal: Error starting protocol stack: missing block number for head header hash

````

**Comment by CamposBruno** [comment]
Hey @karalabe thanks for the hint, I will erase the chain data folder except te ancient, and try to sync again.

As for the 512MB cache, it was the only config that did the trick, if I did not set it, or set it 1024MB or other value, I get the error 
````
runtime: out of memory: cannot allocate 3465216-byte block (3685285888 in use)
fatal error: out of memory
````

**Comment by karalabe** [comment]
Wait, are you using a 32 bit build? Please use a 64bit binary.

**Comment by CamposBruno** [comment]
Thanks @karalabe! I was using 32bit binary. Now I'm using 64bit and that solved the issue!
