### ISSUE TITLE
`geth --testnet --syncmode=light --unlock 0` induces SIGSEGV

### ISSUE THREAD

**Issue by NieDzejkob** [ethereum/go-ethereum#20097]
I don't know how to go about debugging this. Something's probably wrong, though, and I doubt it's my system.

#### System information

Geth version: multiple, including
```
Geth
Version: 1.9.4-stable
Git Commit: 46891c12ab54c9e179f26378ce618fd48460190c
Git Commit Date: 20190919
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.13
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
```
OS & Version: Arch Linux (not versioned)

#### Expected behaviour

No SIGSEGV.

#### Actual behaviour

SIGSEGV.

#### Steps to reproduce the behaviour

`$ geth --testnet --syncmode=light --unlock 0` is what does it for me.

#### Backtrace

````
INFO [09-19|19:41:20.910] Dropping default light client cache      provided=1024 updated=128
INFO [09-19|19:41:20.912] Maximum peer count                       ETH=0 LES=10 total=50
INFO [09-19|19:41:20.912] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-19|19:41:20.914] Starting peer-to-peer node               instance=Geth/v1.9.4-stable-46891c12/linux-amd64/go1.13
INFO [09-19|19:41:20.914] Allocated cache and file handles         database=/home/kuba/.ethereum/testnet/geth/lightchaindata cache=64.00MiB handles=262144
INFO [09-19|19:41:21.152] Persisted trie from memory database      nodes=355 size=50.67KiB time=1.741618ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-19|19:41:21.152] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846 Engine: ethash}"
INFO [09-19|19:41:21.152] Disk storage enabled for ethash caches   dir=/home/kuba/.ethereum/testnet/geth/ethash count=3
INFO [09-19|19:41:21.152] Disk storage enabled for ethash DAGs     dir=/home/kuba/.ethash                       count=2
INFO [09-19|19:41:21.159] Added trusted checkpoint                 block=6389759 hash=34b61d…54cfcc
INFO [09-19|19:41:21.159] Loaded most recent local header          number=6365073 hash=a395bc…5646a0 td=22943014814221353 age=1w2d3h
INFO [09-19|19:41:21.159] Configured checkpoint registrar          address=0xEF79475013f154E6A65b54cB2742867791bf0B84 signers=5 threshold=2
INFO [09-19|19:41:21.339] UDP listener up                          net=enode://cb1b4bcf388b44871bda4010940f6ac513ec26ee3ffeabab30329c07e15a8e64eca2e927bcc018a7511a91bc7f273d5df866747b70de7f59b37b300ac2405dd5@[::]:30303
WARN [09-19|19:41:21.343] Light client mode is an experimental feature
INFO [09-19|19:41:21.345] New local node record                    seq=21 id=3f4ed110dfa16ae9 ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-19|19:41:21.345] Started P2P networking                   self=enode://cb1b4bcf388b44871bda4010940f6ac513ec26ee3ffeabab30329c07e15a8e64eca2e927bcc018a7511a91bc7f273d5df866747b70de7f59b37b300ac2405dd5@127.0.0.1:30303
INFO [09-19|19:41:21.347] IPC endpoint opened                      url=/home/kuba/.ethereum/testnet/geth.ipc
WARN [09-19|19:41:21.347] -------------------------------------------------------------------
WARN [09-19|19:41:21.347] Referring to accounts by order in the keystore folder is dangerous!
WARN [09-19|19:41:21.347] This functionality is deprecated and will be removed in the future!
WARN [09-19|19:41:21.347] Please use explicit addresses! (can search via `geth account list`)
WARN [09-19|19:41:21.347] -------------------------------------------------------------------
Unlocking account 0 | Attempt 1/3
Password: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56214c7eb26f]

goroutine 128 [running]:
github.com/ethereum/go-ethereum/les.(*clientHandler).synchronise(0xc000527800, 0xc0002d7b00)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/sync.go:160 +0x38f
github.com/ethereum/go-ethereum/les.(*lightFetcher).newFetcherDistReqForSync.func3.1(0x56214d24da20, 0xc0002d7b00, 0xc0002625a0)
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/fetcher.go:509 +0x93
created by github.com/ethereum/go-ethereum/les.(*lightFetcher).newFetcherDistReqForSync.func3
        /build/go-ethereum/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/fetcher.go:506 +0xb7
````

**Comment by karalabe** [comment]
This is odd. Works for me on Ubuntu

**Comment by karalabe** [comment]
I guess it's unrelated to the flags and some issue depending on the light server you're connected to. Looking into it.
