### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by datajerk** [ethereum/go-ethereum#2013]
Details:

https://gist.github.com/datajerk/f50d9a14555f3afab107

**Comment by michaeldye** [comment]
Similar, but caused by a different function:

`I0219 09:14:12.167092      41 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 26.932847ms. #119693 [3bf5f447 / 3bf5f447]
94ddeb8fc8b76ed8caa86b319213d74dd39cfa83,15257,2016-02-19 09:14:16.972187354+00:00,d70d7e98434e
393464646562386663386237366564386361613836623331393231336437346464333963666138332c31353235372c323031362d30322d31392030393a31343a31362e3937323138373335342b30303a30302c643730643765393834333465
shh id good: true
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x614c4b]

goroutine 43 [running]:
github.com/ethereum/go-ethereum/xeth.(*whisperFilter).insert(0x0, 0xc82034cbb8, 0x1, 0x1)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/whisper_filter.go:72 +0x32b
github.com/ethereum/go-ethereum/xeth.(*XEth).NewWhisperFilter.func1(0xc8375f7880, 0xc8217af8c0, 0xc0, 0xc83733fc00, 0x3, 0xc8385e8fc0, 0x84, 0x56c6dce5, 0x64, 0xc83915cc80, ...)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/xeth.go:647 +0x15b
github.com/ethereum/go-ethereum/xeth.(*Whisper).Watch.func1(0xc8375f7880)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/whisper.go:107 +0x5e
github.com/ethereum/go-ethereum/whisper.(*Whisper).Watch.func1(0xdf5540, 0xc8375f7880)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/whisper/whisper.go:142 +0x3d
github.com/ethereum/go-ethereum/whisper.filterer.Trigger(0x0, 0x0, 0x0, 0x0, 0xc82145c1a0, 0xc83586d4c0, 0xdf5540, 0xc8375f7880)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/whisper/filter.go:131 +0x30
github.com/ethereum/go-ethereum/whisper.(*filterer).Trigger(0xc834e699b0, 0xdf5540, 0xc8375f7880)
        <autogenerated>:2 +0xaa
github.com/ethereum/go-ethereum/event/filter.(*Filters).loop(0xc8201fb5c0)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/filter/filter.go:81 +0x42d
created by github.com/ethereum/go-ethereum/event/filter.(*Filters).Start
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/filter/filter.go:49 +0x35
`

geth 1.3.3 (commit c541b38fb36587d23c60f5e2f2b9b3c8700ec489), linux x86_64, go 1.5.3
