### ISSUE TITLE
Can not create new wallet by geth command line, error is out of memory

### ISSUE THREAD

**Issue by bufrr** [ethereum/go-ethereum#20439]
Hi there, i downloaded geth and try to create a new account by command line, then error occur.

#### System information

Geth version: `1.9.9`
OS & Version: Linux
Commit hash : download from geth.ethereum.org

#### Expected behaviour
create new wallet, print wallet address in console

#### Actual behaviour
fatal error: runtime: out of memory

#### Steps to reproduce the behaviour
./geth account new
then input the password

#### Backtrace

````
runtime stack:
runtime.throw(0x116b198, 0x16)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc014000000, 0x10000000, 0x1ecb078)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1e999c0, 0x10000000, 0x9e00, 0x1e00)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x1e999c0, 0x8000, 0x7fdbffffffff)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x1e999c0, 0x8000, 0x1ecb088, 0x0)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x1e999c0, 0x8000, 0x7fdbd16a0101, 0x7fdbd16a0dd8)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x1e999c0, 0x8000, 0x7fdbd1010101, 0x7fffae519b18)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x10000000, 0x7fffae510101, 0x46fb0e)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/malloc.go:1138 +0x97
runtime.largeAlloc(0x10000000, 0x7fffae510101, 0x46fb0e)                                                                                                                         [51/115]
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x473314)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/asm_amd64.s:330 fp=0xc000203478 sp=0xc000203470 pc=0x473410
runtime.mallocgc(0x10000000, 0xf880a0, 0x1e94401, 0xc0000b6800)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/malloc.go:1032 +0x895 fp=0xc000203518 sp=0xc000203478 pc=0x4223f5
runtime.makeslice(0xf880a0, 0x4000000, 0x4000000, 0xc0000b6800)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/slice.go:49 +0x6c fp=0xc000203548 sp=0xc000203518 pc=0x45befc
golang.org/x/crypto/scrypt.Key(0xc000038a00, 0x8, 0x8, 0xc00003c700, 0x20, 0x40, 0x40000, 0x8, 0x1, 0x20, ...)
        /home/travis/gopath/pkg/mod/golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2/scrypt/scrypt.go:236 +0x14b fp=0xc0002035f8 sp=0xc000203548 pc=0x6fb58b
github.com/ethereum/go-ethereum/accounts/keystore.getKDFKey(0xc0000389a0, 0xb, 0xc00003c5c0, 0x40, 0xc0000366c0, 0x20, 0xc0000389b0, 0x6, 0xc000033d40, 0xc00003c640, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:333 +0x6a2 fp=0xc0002036e0 sp=0xc0002035f8 pc=0x7165a2
github.com/ethereum/go-ethereum/accounts/keystore.DecryptDataV3(0xc0000389a0, 0xb, 0xc00003c5c0, 0x40, 0xc0000366c0, 0x20, 0xc0000389b0, 0x6, 0xc000033d40, 0xc00003c640, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:258 +0x310 fp=0xc000203838 sp=0xc0002036e0 pc=0x7151c0
github.com/ethereum/go-ethereum/accounts/keystore.decryptKeyV3(0xc0000ae180, 0xc000038170, 0x8, 0xf49c80, 0xc0000ae180, 0x0, 0x0, 0x1eb, 0x3eb, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:280 +0x103 fp=0xc000203958 sp=0xc000203838 pc=0x715633
github.com/ethereum/go-ethereum/accounts/keystore.DecryptKey(0xc0000c1000, 0x1eb, 0x3eb, 0xc000038170, 0x8, 0x0, 0x0, 0x52)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:224 +0x1c2 fp=0xc000203a10 sp=0xc000203958 pc=0x714bb2
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.GetKey(0xc0003fb660, 0x1f, 0x40000, 0x1, 0x0, 0x68949a3cacdc0155, 0xda207b7f9f08a3ca, 0x73d6ca08, 0xc0000a2380, 0x7b
, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:89 +0x9c fp=0xc000203aa8 sp=0xc000203a10 pc=0x71329c
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.StoreKey(0xc0003fb660, 0x1f, 0x40000, 0x1, 0x0, 0xc00007c000, 0x6d, 0xc00007e0c0, 0xc000038170, 0x8, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:118 +0x1d2 fp=0xc000203b88 sp=0xc000203aa8 pc=0x713802
github.com/ethereum/go-ethereum/accounts/keystore.(*keyStorePassphrase).StoreKey(0xc0000322a0, 0xc00007c000, 0x6d, 0xc00007e0c0, 0xc000038170, 0x8, 0x28, 0xc0000322a0)
        <autogenerated>:1 +0xca fp=0xc000203c20 sp=0xc000203b88 pc=0x71a23a
github.com/ethereum/go-ethereum/accounts/keystore.storeNewKey(0x13ed4a0, 0xc0000322a0, 0x13d3f20, 0xc000032300, 0xc000038170, 0x8, 0xe4224d, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/key.go:178 +0x1af fp=0xc000203ce8 sp=0xc000203c20 pc=0x70e46f
github.com/ethereum/go-ethereum/accounts/keystore.StoreKey(0xc0003fb660, 0x1f, 0xc000038170, 0x8, 0x40000, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:102 +0xf2 fp=0xc000203db0 sp=0xc000203ce8 pc=0x713572
main.accountCreate(0xc0005ac000, 0x115b776, 0x8)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go:310 +0x41f fp=0xc000204990 sp=0xc000203db0 pc=0xe42e9f
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc0005ac000, 0x13ab300, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1751 +0xbe fp=0xc000204a08 sp=0xc000204990 pc=0xd3ad7e
gopkg.in/urfave/cli%2ev1.HandleAction(0xfa2b20, 0xc0002716c0, 0xc0005ac000, 0xc0005aa000, 0x0)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8 fp=0xc000204a30 sp=0xc000204a08 pc=0x9e6b68
gopkg.in/urfave/cli%2ev1.Command.Run(0x1155ffd, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1167a46, 0x14, 0x0, ...)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x991 fp=0xc000204cd8 sp=0xc000204a30 pc=0x9e7f71
gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc0002fad00, 0xc0000ddce0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:379 +0x7fa fp=0xc0002052b0 sp=0xc000204cd8 pc=0x9e5a2a
gopkg.in/urfave/cli%2ev1.Command.startApp(0x1159a7c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1161f6a, 0xf, 0x0, ...)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:298 +0x817 fp=0xc000205920 sp=0xc0002052b0 pc=0x9e9587
gopkg.in/urfave/cli%2ev1.Command.Run(0x1159a7c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1161f6a, 0xf, 0x0, ...)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:98 +0x11dc fp=0xc000205bc8 sp=0xc000205920 pc=0x9e87bc
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002fa9c0, 0xc000032180, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x6ab fp=0xc000205f00 sp=0xc000205bc8 pc=0x9e4e8b
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002fa9c0, 0xc000032180, 0x3, 0x3, 0x0, 0x0)                                                                                               [0/115]
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x6ab fp=0xc000205f00 sp=0xc000205bc8 pc=0x9e4e8b
main.main()
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:246 +0x55 fp=0xc000205f60 sp=0xc000205f00 pc=0xe4b7e5
runtime.main()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/proc.go:203 +0x21e fp=0xc000205fe0 sp=0xc000205f60 pc=0x446ebe
runtime.goexit()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000205fe8 sp=0xc000205fe0 pc=0x4754e1

goroutine 7 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc000080420, 0xc000080360)
        /home/travis/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /home/travis/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0xdc

goroutine 8 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc000080420, 0xc0000803c0)
        /home/travis/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /home/travis/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x108

goroutine 9 [syscall]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/travis/.gimme/versions/go1.13.5.linux.amd64/src/os/signal/signal_unix.go:29 +0x41

goroutine 10 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00014e880)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 19 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc000276000)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:278 +0x276
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:262 +0x2ae

goroutine 18 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x1e8cf00)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/metrics/meter.go:289 +0x78
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/metrics/meter.go:70 +0x104
````

![image](https://user-images.githubusercontent.com/3174573/70494351-f5473780-1b45-11ea-8dd5-c1aef2e6701c.png)

**Comment by bufrr** [comment]
Looks like i have 800M RAM in my computer, 1 CPU 2.0GHz

**Comment by ligi** [comment]
You might want to use `--lightkdf` with so little memory

**Comment by bufrr** [comment]
@ligi Now it works for me, thanks!
