### ISSUE TITLE
eth: sync code can crash if there is no local fastblock

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#20448]
Geth version: `1.9.9`
OS & Version: macOS 10.15.2

#### Backtrace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4116ee6]

goroutine 486 [running]:
math/big.(*Int).Cmp(0x0, 0xc00287c020, 0x45e40484944d1857)
        /usr/local/Cellar/go/1.13.4/libexec/src/math/big/int.go:326 +0x26
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc00040ba40, 0xc000730b40)
        /Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/eth/sync.go:185 +0x278
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/eth/sync.go:155 +0x22d
```
https://github.com/ethereum/go-ethereum/blob/d90d1db609c8d77baa422d49bd371207c06b4711/eth/sync.go#L183-L187

**Comment by holiman** [comment]
This is pretty old. I wonder if this is still relevant?

**Comment by adamschmideg** [comment]
This piece of code got refactored
