### ISSUE TITLE
Crash Importing DB with --syncmode full

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#20477]
#### System information

Geth version: `1.9.10-unstable-f51cf573-20191212`
OS & Version: Ubuntu 18.04.3

#### Expected behaviour
No crash

#### Actual behaviour
Crash

#### Steps to reproduce the behaviour
From a fully sync'd node (Fast Sync'd > 3 months ago)
`geth --datadir /data/ethereum --datadir.ancient /archive/ancient export <file>`

Wiped `chaindata`, wiped `ancient` folder

`geth --datadir /data/ethereum --datadir.ancient /archive/ancient --syncmode full import file`

Crash

#### Backtrace

[error.log](https://github.com/ethereum/go-ethereum/files/3989244/error.log)

**Comment by MysticRyuujin** [comment]
The import resumed seemingly without issue on restart

**Comment by holiman** [comment]
relevant part: 
```
INFO [12-20|10:31:08.045] Imported new chain segment               blocks=27    txs=2270  mgas=130.620  elapsed=8.105s    mgasps=16.115  number=4295067 hash=b448ae…62d7d9 age=2y3mo1w   dirty=254.75MiB
unexpected fault address 0x80001db9d0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80001db9d0 pc=0x8aa00e]

goroutine 1 [running]:
runtime.throw(0x115740e, 0x5)
        /usr/lib/go-1.13/src/runtime/panic.go:774 +0x72 fp=0xc000bebd58 sp=0xc000bebd28 pc=0x445392
runtime.sigpanic()
        /usr/lib/go-1.13/src/runtime/signal_unix.go:401 +0x3de fp=0xc000bebd88 sp=0xc000bebd58 pc=0x45ac8e
sync.(*RWMutex).RLock(...)
        /usr/lib/go-1.13/src/sync/rwmutex.go:48
github.com/syndtr/goleveldb/leveldb/cache.(*Node).unrefLocked(0xc0524b7e30)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/cache/cache.go:629 +0x3e fp=0xc000bebdb0 sp=0xc000bebd88 pc=0x8aa00e
github.com/syndtr/goleveldb/leveldb/cache.(*Handle).Release(0xc08a7ff8e8)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/cache/cache.go:657 +0x43 fp=0xc000bebde8 sp=0xc000bebdb0 pc=0x8aa103
github.com/syndtr/goleveldb/leveldb/cache.(*lru).Promote(0xc0001db940, 0xc06780eee0)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/cache/lru.go:114 +0x8e fp=0xc000bebe60 sp=0xc000bebde8 pc=0x8aa5ce
github.com/syndtr/goleveldb/leveldb/cache.(*Cache).Get(0xc0001db9c0, 0x3ead3, 0x200f6d, 0xc000bebf48, 0x0)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/cache/cache.go:399 +0x20b fp=0xc000bebf08 sp=0xc000bebe60 pc=0x8a919b
github.com/syndtr/goleveldb/leveldb/cache.(*NamespaceGetter).Get(...)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/cache/cache.go:58
github.com/syndtr/goleveldb/leveldb/table.(*Reader).readFilterBlockCached(0xc0a3e451e0, 0x200f6d, 0x3f44, 0x1, 0x327d, 0xdb7, 0x2, 0x976f7, 0x3)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/table/reader.go:683 +0xb9 fp=0xc000bebf80 sp=0xc000bebf08 pc=0x8b1379
github.com/syndtr/goleveldb/leveldb/table.(*Reader).getFilterBlock(0xc0a3e451e0, 0x1, 0x3280, 0x976f7, 0xdb7, 0x5, 0xc0044eaa50)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/table/reader.go:719 +0x8e fp=0xc000bebfd8 sp=0xc000bebf80 pc=0x8b16ce
github.com/syndtr/goleveldb/leveldb/table.(*Reader).find(0xc0a3e451e0, 0xc0830d7ce0, 0x28, 0x28, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/table/reader.go:853 +0xb22 fp=0xc000bec170 sp=0xc000bebfd8 pc=0x8b2e42
github.com/syndtr/goleveldb/leveldb/table.(*Reader).Find(...)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/table/reader.go:922
github.com/syndtr/goleveldb/leveldb.(*tOps).find(0xc0001dc180, 0xc08ec7abe0, 0xc0830d7ce0, 0x28, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/table.go:450 +0x158 fp=0xc000bec238 sp=0xc000bec170 pc=0x8df1b8
github.com/syndtr/goleveldb/leveldb.(*version).get.func1(0x4, 0xc08ec7abe0, 0x20)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/version.go:180 +0x45b fp=0xc000bec348 sp=0xc000bec238 pc=0x8e911b
github.com/syndtr/goleveldb/leveldb.(*version).walkOverlapping(0xc08116ad80, 0x0, 0x0, 0x0, 0xc0830d7ce0, 0x28, 0x28, 0xc000bec4b8, 0xc000bec488)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/version.go:128 +0x494 fp=0xc000bec408 sp=0xc000bec348 pc=0x8e12b4
github.com/syndtr/goleveldb/leveldb.(*version).get(0xc08116ad80, 0x0, 0x0, 0x0, 0xc0830d7ce0, 0x28, 0x28, 0x0, 0x7afc300, 0x0, ...)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/version.go:164 +0x2dd fp=0xc000bec560 sp=0xc000bec408 pc=0x8e161d
github.com/syndtr/goleveldb/leveldb.(*DB).get(0xc00049a000, 0x0, 0x0, 0x0, 0x0, 0xc083621800, 0x20, 0x20, 0x147764d7, 0x0, ...)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:785 +0x381 fp=0xc000bec678 sp=0xc000bec560 pc=0x8be901
github.com/syndtr/goleveldb/leveldb.(*DB).Get(0xc00049a000, 0xc083621800, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:851 +0x148 fp=0xc000bec748 sp=0xc000bec678 pc=0x8bf0f8
github.com/ethereum/go-ethereum/ethdb/leveldb.(*Database).Get(0xc00010e900, 0xc083621800, 0x20, 0x20, 0xcb293e625893d07e, 0xcb00000000000000, 0x0, 0xeee7a0, 0xc0c92f8560)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:160 +0x5a fp=0xc000bec7a8 sp=0xc000bec748 pc=0x8ee6aa
github.com/ethereum/go-ethereum/core/rawdb.(*freezerdb).Get(0xc00000e4c0, 0xc083621800, 0x20, 0x20, 0xc083621800, 0x20, 0x20, 0x0, 0x0)
        <autogenerated>:1 +0x62 fp=0xc000bec800 sp=0xc000bec7a8 pc=0x9148c2
github.com/ethereum/go-ethereum/trie.(*Database).node(0xc00010eb00, 0xe7c798403a6fae6d, 0xdfd3abb6895249cc, 0x140c8288f7477ba9, 0x701f2003e4e25dbe, 0x1, 0x1)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/database.go:389 +0x15e fp=0xc000bec8e0 sp=0xc000bec800 pc=0x6b17be
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc0800ce280, 0xc0836217a0, 0x20, 0x20, 0xc076963540, 0x6, 0x41, 0x10, 0xc000beca50, 0x5f0176, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:398 +0xdf fp=0xc000bec968 sp=0xc000bec8e0 pc=0x6c68df
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e4a80, 0xc054e39820, 0xc076963540, 0x41, 0x41, 0x6, 0x0, 0x13e4a80, 0x73, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:133 +0xef fp=0xc000becac0 sp=0xc000bec968 pc=0x6c332f
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e29c0, 0xc0044ec3c0, 0xc076963540, 0x41, 0x41, 0x5, 0x13e29c0, 0xc0044ec3c0, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695 fp=0xc000becc18 sp=0xc000becac0 pc=0x6c38d5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e4a80, 0xc0a56efd60, 0xc076963540, 0x41, 0x41, 0x5, 0x0, 0x13e4a80, 0xc0a6a681a0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:137 +0x201 fp=0xc000becd70 sp=0xc000becc18 pc=0x6c3441
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e29c0, 0xc0044ec280, 0xc076963540, 0x41, 0x41, 0x4, 0x13e29c0, 0xc0044ec280, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695 fp=0xc000becec8 sp=0xc000becd70 pc=0x6c38d5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e4a80, 0xc0a5161860, 0xc076963540, 0x41, 0x41, 0x4, 0x0, 0x41, 0x41, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:137 +0x201 fp=0xc000bed020 sp=0xc000becec8 pc=0x6c3441
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e29c0, 0xc0044ec140, 0xc076963540, 0x41, 0x41, 0x3, 0x13e29c0, 0xc0044ec140, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695 fp=0xc000bed178 sp=0xc000bed020 pc=0x6c38d5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e4a80, 0xc0d1133060, 0xc076963540, 0x41, 0x41, 0x3, 0xc0769634a0, 0x41, 0x41, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:137 +0x201 fp=0xc000bed2d0 sp=0xc000bed178 pc=0x6c3441
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e29c0, 0xc004276dc0, 0xc076963540, 0x41, 0x41, 0x2, 0x42b438, 0x7fb75dfdb700, 0x100, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695 fp=0xc000bed428 sp=0xc000bed2d0 pc=0x6c38d5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e29c0, 0xc0044ad900, 0xc076963540, 0x41, 0x41, 0x1, 0x88, 0xc000bed620, 0x421ce6, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695 fp=0xc000bed580 sp=0xc000bed428 pc=0x6c38d5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0800ce280, 0x13e29c0, 0xc0044ec000, 0xc076963540, 0x41, 0x41, 0x0, 0x20, 0xc0800ce298, 0x20, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695 fp=0xc000bed6d8 sp=0xc000bed580 pc=0x6c38d5
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc0800ce280, 0xc0800ce298, 0x20, 0x20, 0xc0800ce298, 0x20, 0x20, 0xeee450, 0xc004038f00)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:101 +0x78 fp=0xc000bed760 sp=0xc000bed6d8 pc=0x6c3188
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc0800ce280, 0xc083621640, 0x14, 0x14, 0xfc89c0, 0xc075dbc3c0, 0xc000bed88c, 0xc004038fd0, 0x14)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:79 +0x7b fp=0xc000bed7b8 sp=0xc000bed760 pc=0x6be94b
github.com/ethereum/go-ethereum/core/state.(*StateDB).getDeletedStateObject(0xc0bd3c5b00, 0x6b148270e8213a2a, 0xa15d7089e544754, 0xc0486ad8a8, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:477 +0x10e fp=0xc000bed990 sp=0xc000bed7b8 pc=0x72896e
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:457
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetCodeHash(0xc0bd3c5b00, 0x6b148270e8213a2a, 0xa15d7089e544754, 0xe4fe4d3b486ad8a8, 0x0, 0x0, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:277 +0x6a fp=0xc000beda00 sp=0xc000bed990 pc=0x72740a
github.com/ethereum/go-ethereum/core/vm.(*EVM).create(0xc004486000, 0x13d4100, 0xc0043bc6c0, 0xc000bedcf0, 0x33b9f, 0xc038e1de20, 0x6b148270e8213a2a, 0xa15d7089e544754, 0x486ad8a8, 0xc083621400, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:396 +0x263 fp=0xc000bedc20 sp=0xc000beda00 pc=0x933073
github.com/ethereum/go-ethereum/core/vm.(*EVM).Create(0xc004486000, 0x13d4100, 0xc0043bc6c0, 0xc083621400, 0x1f, 0x1f, 0x33b9f, 0xc038e1de20, 0x1, 0x6, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:462 +0x211 fp=0xc000bedd38 sp=0xc000bedc20 pc=0x933e61
github.com/ethereum/go-ethereum/core/vm.opCreate(0xc0806f1eb0, 0xc00448a000, 0xc0043bc6c0, 0xc061d4c320, 0xc061d4c360, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/instructions.go:700 +0x16a fp=0xc000bede88 sp=0xc000bedd38 pc=0x93f78a
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc00448a000, 0xc0043bc6c0, 0xc0b032c570, 0x24, 0x24, 0xc000bee100, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/interpreter.go:270 +0x4a6 fp=0xc000bee148 sp=0xc000bede88 pc=0x943c46
github.com/ethereum/go-ethereum/core/vm.run(0xc004486000, 0xc0043bc6c0, 0xc0b032c570, 0x24, 0x24, 0x1200, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:67 +0x276 fp=0xc000bee1d8 sp=0xc000bee148 pc=0x930a06
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc004486000, 0x13d60e0, 0xc01eeb9f20, 0x79f8b30000000000, 0xe4fe4d3b24fe30cb, 0x41c6938, 0xc0b032c570, 0x24, 0x24, 0xeeea0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:242 +0x517 fp=0xc000bee418 sp=0xc000bee1d8 pc=0x931567
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc06474c7e0, 0x1400b20, 0xc097614900, 0xc061c92df0, 0xc06474c7e0, 0xc097614900, 0xc097614900, 0x1115f20)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:218 +0x3da fp=0xc000bee5d0 sp=0xc000bee418 pc=0x977dda
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc004486000, 0x1400b20, 0xc097614900, 0xc061c92df0, 0x1767ea77b0c2a7a, 0xa5f87b73, 0xc0a17e9a40, 0xa87049d25cbee490, 0xa840adf381e2237e, 0x33b45895, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:136 +0x5b fp=0xc000bee620 sp=0xc000bee5d0 pc=0x97744b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x1d686e0, 0x13e1d00, 0xc001106000, 0x0, 0xc061c92df0, 0xc0bd3c5b00, 0xc02c095680, 0xc076918ab0, 0xc000bf5bb0, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:99 +0x2ac fp=0xc000bf22b8 sp=0xc000bee620 pc=0x976a8c
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc00000f1a0, 0xc0765c9320, 0xc0bd3c5b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:71 +0x41c fp=0xc000bf5cd8 sp=0xc000bf22b8 pc=0x9762fc
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc001106000, 0xc00026b000, 0x9c4, 0x9c4, 0x8c60df17ecc31f01, 0x0, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1648 +0xca2 fp=0xc000bfd8e0 sp=0xc000bf5cd8 pc=0x95d452
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc001106000, 0xc00026b000, 0x9c4, 0x9c4, 0x0, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1464 +0xccb fp=0xc000bfdc70 sp=0xc000bfd8e0 pc=0x95c6cb
github.com/ethereum/go-ethereum/cmd/utils.ImportChain(0xc001106000, 0x7ffc224e7e5f, 0x20, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:164 +0x8cd fp=0xc000bfdf18 sp=0xc000bfdc70 pc=0xd2d61d
main.importChain(0xc000204580, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/chaincmd.go:259 +0xf9d fp=0xc000bff880 sp=0xc000bfdf18 pc=0xe4536d
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc000204580, 0x0, 0xc000204580)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1751 +0xbe fp=0xc000bff8f8 sp=0xc000bff880 pc=0xd3aa9e
gopkg.in/urfave/cli%2ev1.HandleAction(0xfa2980, 0xc0000a37d0, 0xc000204580, 0xc0000c0600, 0x0)
        /root/go-ethereum/build/_workspace/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8 fp=0xc000bff920 sp=0xc000bff8f8 pc=0x9e69f8
gopkg.in/urfave/cli%2ev1.Command.Run(0x115883a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x116cdd8, 0x18, 0x0, ...)
        /root/go-ethereum/build/_workspace/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x991 fp=0xc000bffbc8 sp=0xc000bff920 pc=0x9e7e01
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000a8000, 0xc0000c2000, 0x2f, 0x30, 0x0, 0x0)
        /root/go-ethereum/build/_workspace/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x6ab fp=0xc000bfff00 sp=0xc000bffbc8 pc=0x9e4d1b
main.main()
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:246 +0x55 fp=0xc000bfff60 sp=0xc000bfff00 pc=0xe4b5f5
runtime.main()
        /usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc000bfffe0 sp=0xc000bfff60 pc=0x446d2e
runtime.goexit()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000bfffe8 sp=0xc000bfffe0 pc=0x475351
```

**Comment by MysticRyuujin** [comment]
Hey, this original error is from the Geth01 Ubuntu node, you can close this. The error you just copied from is the windows machine, totally separate issue totally separate system.

**Comment by holiman** [comment]
Thanks, adding a reference: https://github.com/ethereum/go-ethereum/issues/20478
