### ISSUE TITLE
Nodes with unbound txpool periodically crashes and needs to resync blocks

### ISSUE THREAD

**Issue by liamaharon** [ethereum/go-ethereum#20539]
#### System information

Geth version: 1.9.9
OS & Version: Linux

#### Expected behaviour

Node to stay in sync, or if it loses sync not need to resync blocks it has already processed

#### Actual behaviour

I manage many Geth & Parity nodes with different config options. I've found recently that mainnet nodes with config options `--txpool.globalslots=1000000 --txpool.globalqueue=1000000 --txpool.accountslots=1000000 --txpool.accountqueue=1000000` periodically stop responding to JSONRPC calls, and then start syncing blocks that they already processed in the past. 

For example in the attached pic of our internal logs
![Screenshot from 2020-01-10 15-13-27](https://user-images.githubusercontent.com/16665596/72125926-74869000-33be-11ea-8cca-b820e9d8413f.png)
1. The node stopped responding to JSONRPC requests
2. 30 seconds later the software communicating with the node attempts to reconnect
3. On reconnection, the node is 911 blocks out of sync
4. For the next few minutes the node slowly gets back into sync
5. A few seconds after the node looks like it's finally about to get back in sync, it goes out of sync even more than it was initially at 2687 blocks behind.

Note before these errors the node was running perfectly fine and staying in sync with the rest of the network. 

Here's a dump of the Geth logs during this period https://pastebin.com/mk3cReBm

Looks like an uncaught error crashed the node
```
geth[18994]: panic: Refund counter below zero
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: goroutine 144 [running]:
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core/state.(*StateDB).SubRefund(0xc0a2f80120, 0x3a98)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:207 +0x9e
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core/vm.gasSStoreEIP2200(0xc03786a000, 0xc0ca8d6900, 0xc0c90dbe60, 0xc0c90dbd40, 0x0, 0x0, 0x0, 0x0)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/gas_table.go:205 +0x690
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc037878000, 0xc0ca8d6900, 0xc05fed1c70, 0x44, 0x44, 0xc01040c300, 0x0, 0x0, 0x0, 0x0, ...)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/interpreter.go:254 +0x84f
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core/vm.run(0xc03786a000, 0xc0ca8d6900, 0xc05fed1c70, 0x44, 0x44, 0xe00, 0x0, 0x0, 0x0, 0x0, ...)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:67 +0x276
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc03786a000, 0x13d6100, 0xc09a73b620, 0x580f26ceba01989e, 0x59c415e5e6157c40, 0xf6e7518, 0xc05fed1c70, 0x44, 0x44, 0xfd38, ...)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:242 +0x517
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc15b6d83f0, 0x1400a60, 0xc12271eea0, 0xc0c25dc440, 0xc15b6d83f0, 0xc12271eea0, 0xc12271eea0, 0x1115f00)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:218 +0x3da
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core.ApplyMessage(0xc03786a000, 0x1400a60, 0xc12271eea0, 0xc0c25dc440, 0xb7baa8af3d98435f, 0xbd4d6604, 0xc0c90dbae0, 0x0, 0x0, 0x0, ...)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:136 +0x5b
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/core.ApplyTransaction(0x1d716e0, 0x13e1c20, 0xc006220000, 0xc010417648, 0xc0c25dc440, 0xc0a2f80120, 0xc07b38f680, 0xc06c474480, 0xc07b38f850, 0x0, ...)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:99 +0x2ac
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/miner.(*worker).commitTransaction(0xc0001d4820, 0xc06c474480, 0x0, 0x0, 0xb60430e500000000, 0xbd4d6604, 0x0, 0x0, 0x0, 0x0)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:698 +0x172
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/miner.(*worker).commitTransactions(0xc0001d4820, 0xc0dae90ba0, 0x0, 0x0, 0x0, 0xc0d9afd9f8, 0xbf7e1ba538a9b58c)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:768 +0x454
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc0001d4820, 0xc0d9afd9f8, 0x0, 0x5e17f712)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:942 +0x97f
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc0001d4820)
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:409 +0xca4
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]: created by github.com/ethereum/go-ethereum/miner.newWorker
Jan 10 04:01:35 Geth-1-D-STAGE geth[18994]:         /build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:216 +0x501
Jan 10 04:01:35 Geth-1-D-STAGE systemd[1]: geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 10 04:01:35 Geth-1-D-STAGE systemd[1]: geth.service: Failed with result 'exit-code'.
Jan 10 04:01:35 Geth-1-D-STAGE systemd[1]: geth.service: Service hold-off time over, scheduling restart.
Jan 10 04:01:35 Geth-1-D-STAGE systemd[1]: geth.service: Scheduled restart job, restart counter is at 9.
```

This is the full config of the node in question `geth --rpc --rpcapi "eth,web3,txpool,net" --ws --wsapi "eth,web3,txpool,net" --wsorigins="*" --rpcaddr="0.0.0.0" --wsaddr="0.0.0.0" --txpool.globalslots=1000000 --txpool.globalqueue=1000000 --txpool.accountslots=1000000 --txpool.accountqueue=1000000 --graphql`

It happens every 1-2 days, only started happening around late December. Had been running this configuration without any issues before then.

I'm not sure what's causing the blocks unsynced metric to jump half way through re-syncing.

**Comment by holiman** [comment]
For context, did you ever run 1.9.8 on these nodes? Trying to figure out how certain we can be that this is something introduced between 1.9.8 and 1.9.9

**Comment by liamaharon** [comment]
Yep, we used to run 1.9.8. Would need to check exactly when we first experienced these issues but it makes sense they started around when 1.9.9 was released

**Comment by liamaharon** [comment]
FYI this issue started affecting nodes with default txpool settings today and the frequency increased (3 times in 1 day). The nodes often crash at the exact same time.

**Comment by holiman** [comment]
@liamaharon are you using the exact same version `v1.9.9` across all nodes? 
Are they in any way sharing infrastructure (e.g. disk shares), or are they all separate from eachter? 
Would it be possible for you to test `master` / `latest` on one or some of them?

**Comment by holiman** [comment]
Oh, and also, do you persistently get the same `panic: Refund counter below zero`, or do they fail for other reason(s)  too?

**Comment by liamaharon** [comment]
@holiman we install from the ethereum ppa so I think they should be using the same version of `v1.9.9`.

The nodes run on their own separate infrastructure.

Sure, I will switch one of our staging nodes to run master and let you know when it crashes again what the logs look like.

I just had a look through the logs at previous times we experienced losing connection to the node. 
When the node crashed, it seems to have always been due to the `panic: Refund counter below zero` error. 

However I was surprised to find the node losing connection to web3.js was not always accompanied by the Geth node crashing. I could sometimes not find anything abnormal in the Geth logs around the time we saw 
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
   at Object.InvalidConnection (/home/ubuntu/bn-monitor/node_modules/web3-core-helpers/src/errors.js:35:16)
```
in our application logs, even though the automatic attempt by the application to reconnect to Geth 30 seconds later failed

**Comment by liamaharon** [comment]
Hey @holiman, the node I setup to run the `master` branch just crashed. 

Here're the Geth logs: https://pastebin.com/CeEHLicc

Note only one of our nodes was affected during this time.

**Comment by holiman** [comment]
What are the memory used by geth? IIRC, during startup, geth outputs some info about size of the caches.

**Comment by holiman** [comment]
In one of the logs, you had this
```
Jan 14 09:26:10 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:10.952] Served eth_call                          reqid=62 t=6.801721738s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.110] Served eth_call                          reqid=62 t=6.92432967s  err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.159] Served eth_call                          reqid=58 t=7.001356181s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.159] Served eth_call                          reqid=59 t=6.991368412s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.159] Served eth_call                          reqid=63 t=6.958431913s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.159] Served eth_call                          reqid=54 t=7.078143609s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.160] Served eth_call                          reqid=56 t=7.070502363s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.160] Served eth_call                          reqid=57 t=7.015178576s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.420] Served eth_call                          reqid=61 t=7.245532567s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.420] Served eth_call                          reqid=60 t=7.222146511s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.488] Served eth_call                          reqid=61 t=7.284761006s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: WARN [01-14|09:26:11.531] Served eth_call                          reqid=72 t=7.321457008s err="execution aborted (timeout = 5s)"
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: panic: Refund counter below zero (gas: 15000 > refund: 0)
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: goroutine 60 [running]:
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: github.com/ethereum/go-ethereum/core/state.(*StateDB).SubRefund(0xc0d75e5200, 0x3a98)
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]:         /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:207 +0x140
Jan 14 09:26:11 Geth-1-D-STAGE geth[30978]: github.com/ethereum/go-ethereum/core/vm.gasSStoreEIP2200(0xc00f30600
```

We can see that several `eth_call` requests timed out. What was happening there - what were those calls? Is there a lot of paralell RPC requests being done? And are those against the `pending` state, or `latest` block or some old blocks?

**Comment by liamaharon** [comment]
`htop` show Geth is using ~12gb of memory

On start, `geth` outputs this info about caches
```
Jan 20 22:25:56 Geth-1-D-STAGE geth[13097]: INFO [01-20|22:25:56.399] Allocated trie memory caches             clean=1024.00MiB dirty=1024.00MiB
Jan 20 22:25:56 Geth-1-D-STAGE geth[13097]: INFO [01-20|22:25:56.399] Allocated cache and file handles         database=/home/ubuntu/.ethereum/geth/chaindata cache=2.00GiB handles=2048
```

> We can see that several eth_call requests timed out. What was happening there - what were those calls? Is there a lot of paralell RPC requests being done? And are those against the pending state, or latest block or some old blocks?

It's hard to say exactly which calls were timing out, but I suspect they were against `pending` state. Most of the calls in our software are against `pending` state and the `latest` block.

**Comment by karalabe** [comment]
You number of `handles` seems a bit low (we generally request all available, on Linux that's 500K or so). If you run out of file descriptors, that might also explain the web3 connection errors, as the OS simply does not have more to give you. Could you try increasing the fd limit on your OS/user and see if that helps?

**Comment by adamschmideg** [comment]
Depends on #21238

**Comment by karalabe** [comment]
How many peers and RPC connections do you have? Also counting WAIT and zombie states. If your connections exceed 2K, then LevelDB will not have enough descriptors left and will start doing weird things.
