### ISSUE TITLE
all: ensure internal subscriptions are created in constructors

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#20554]
In PR #20390, we attempted to fix an issue where geth crashes if it is stopped before being fully started. The issue is that `Subscribe*` methods can fail if they use `event.SubscriptionScope` and the scope is closed before all subscriptions are created. There are two ways to fix this issue:

- Remove uses of `SubscriptionScope` for internal event providers such as `core.BlockChain`.
- Ensure internal subscriptions are created in constructor functions **before** start.

**Comment by karalabe** [comment]
Just had a PR CI build crash with this :P

https://travis-ci.org/ethereum/go-ethereum/jobs/636825311#L785

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcb1d4f]
goroutine 5115687 [running]:
github.com/ethereum/go-ethereum/les.(*serverHandler).broadcastHeaders(0xc002215b80)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:906 +0xcf
created by github.com/ethereum/go-ethereum/les.(*serverHandler).start
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:93 +0x6c
FAIL	github.com/ethereum/go-ethereum/les	15.760s
```

**Comment by Hotspot00** [comment]
[takeout-20230307T222016Z-006.zip](https://github.com/ethereum/go-ethereum/files/11310741/takeout-20230307T222016Z-006.zip)
