### ISSUE TITLE
Travis failure (internal/log)

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#20558]
Happens on travis (spuriously). Example https://travis-ci.org/ethereum/go-ethereum/jobs/636889600#L1085 :
```
panic: Log in goroutine after TestServerInboundThrottle has completed

goroutine 9726 [running]:
testing.(*common).logDepth(0xc00010e400, 0xc00057e300, 0x60, 0x3)
	/home/travis/.gimme/versions/go1.12.15.linux.amd64/src/testing/testing.go:634 +0x3a6
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.12.15.linux.amd64/src/testing/testing.go:614
testing.(*common).Logf(0xc00010e400, 0x99a7cf, 0x2, 0xc000067e98, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.12.15.linux.amd64/src/testing/testing.go:649 +0x7f
github.com/ethereum/go-ethereum/internal/testlog.(*logger).flush(0xc0001d2000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/internal/testlog/testlog.go:139 +0xfd
github.com/ethereum/go-ethereum/internal/testlog.(*logger).Trace(0xc0001d2000, 0x9aad13, 0x1c, 0xc000555c40, 0x4, 0x4)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/internal/testlog/testlog.go:80 +0xc7
github.com/ethereum/go-ethereum/p2p.(*Server).SetupConn(0xc00018a280, 0xa5b060, 0xc0002dc4e0, 0x4, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/server.go:945 +0x2d8
github.com/ethereum/go-ethereum/p2p.(*Server).listenLoop.func1(0xc00018a280, 0xa5b060, 0xc0002dc4e0, 0xc000100de0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/server.go:915 +0x60
created by github.com/ethereum/go-ethereum/p2p.(*Server).listenLoop
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/server.go:914 +0x4e7
```

**Comment by holiman** [comment]
This is due to https://github.com/ethereum/go-ethereum/blob/9e8cc00b733a505c2815b58d94315298371579cb/p2p/server.go#L914:

```
		go func() {
			srv.SetupConn(fd, inboundConn, nil)
			slots <- struct{}{}
		}()
```
We start a goroutine which does not add to the `wg`, and thus it can print a log message even after the server has been stopped
