### ISSUE TITLE
RPC `debug_traceTransaction` user provided javascript tracer code causes method handler crashes due to go panics

### ISSUE THREAD

**Issue by tintinweb** [ethereum/go-ethereum#20611]
Hi there,

as mentioned 2 weeks ago I finally found some time to debug and file the crashes @holiman. Here are the details.

There are multiple opportunities for a user with access to the `debug_traceTransaction` endpoint to crash the remote method handler by providing javascript code that causes the handler to panic. 

Please note that the node recovers from this error (goroutine -> recover 🙌). 

See test-cases below.

**Note** Even though the `debug` RPC namespace implies that critical functionality can be accessed I'd recommend adding a note to the `debug_traceTransaction` documentation that clearly outlines the risk of allowing untrusted entities to run untrusted javascript code especially because the interpreter engine is a native C library (duktape) which does not have the memory safety guarantees go provides (vulnerability in duktape).

#### System information

release and latest master. any os.

Geth version: `Geth/v1.9.11-unstable-3c776c71-20200131/darwin-amd64/go1.13.6`
OS & Version: OSX
Commit hash : `15d09038a6b1d533bc78662f2f0b77ccf03aaab0`

#### Expected behaviour

method handler should not crash.

#### Actual behaviour

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

#### quick check

```console
//start
geth --rpc --gcmode=archive --syncmode=full  --rpcapi eth,web3,debug,admin

INFO [01-31|14:33:57.470] Starting peer-to-peer node               instance=Geth/v1.9.11-unstable-3c776c71-20200131/darwin-amd64/go1.13.6
```
```json
//REQ
{
    "id": 1,
    "method": "debug_traceTransaction",
    "params": [
        "0xa56249d3ca83cd8ba2e48e3c02532c4ef94f0024004f6332cff00526a3c7de6e",
        {
            "tracer": "{depths: [],step: function(log, db) {this.depths.push(log.memory.getUint(-100000));},fault: function() {},result: function() { return this.depths; }}"
        }
    ]
}
//RESP
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

##### Slice(negative, negative) or Slice(negative, >=mw.memory.Len()) panic

**code:** 

**Note**: see `@note` comments

https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/tracer.go#L94

```go

// slice returns the requested range of memory as a byte slice.
func (mw *memoryWrapper) slice(begin, end int64) []byte {
	if mw.memory.Len() < int(end) {
		// TODO(karalabe): We can't js-throw from Go inside duktape inside Go. The Go
		// runtime goes belly up https://github.com/golang/go/issues/15639.
		log.Warn("Tracer accessed out of bound memory", "available", mw.memory.Len(), "offset", begin, "size", end-begin)
		return nil  //@note - panics later at ptr := ctx.PushFixedBuffer(len(blob)) 
	}
	return mw.memory.GetCopy(begin, end-begin)  //@note - panic (-1, -2)
}

[...]

// pushObject assembles a JSVM object wrapping a swappable memory and pushes it
// onto the VM stack.
func (mw *memoryWrapper) pushObject(vm *duktape.Context) {
	obj := vm.PushObject()

	// Generate the `slice` method which takes two ints and returns a buffer
	vm.PushGoFunction(func(ctx *duktape.Context) int {
		blob := mw.slice(int64(ctx.GetInt(-2)), int64(ctx.GetInt(-1)))
		ctx.Pop2()

		ptr := ctx.PushFixedBuffer(len(blob))  //@note - panics if blob is nil
		copy(makeSlice(ptr, uint(len(blob))), blob)
		return 1
	})
	vm.PutPropString(obj, "slice")

	// Generate the `getUint` method which takes an int and returns a bigint
	vm.PushGoFunction(func(ctx *duktape.Context) int {
		offset := int64(ctx.GetInt(-1))
		ctx.Pop()

		pushBigInt(mw.getUint(offset), ctx)
		return 1
	})
	vm.PutPropString(obj, "getUint")
}
```

**testcase:** 
```javascript
{depths: [], step: function(log) { this.depths.push(log.memory.slice(-1,-2)); }, fault: function() {}, result: function() { return this.depths; }}
```

**stacktrace:**

```console
Running tool: /usr/local/opt/go/libexec/bin/go test -timeout 30s github.com/ethereum/go-ethereum/eth/tracers -run ^(TestRegressionPanicSlice)$

--- FAIL: TestRegressionPanicSlice (0.01s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 34 [running]:
testing.tRunner.func1(0xc0000f2400)
	/usr/local/opt/go/libexec/src/testing/testing.go:874 +0x3a3
panic(0x45749e0, 0x46c8b50)
	/usr/local/opt/go/libexec/src/runtime/panic.go:679 +0x1b2
github.com/ethereum/go-ethereum/core/vm.(*Memory).GetCopy(...)
	/Users/tintin/workspace/golang/go-ethereum/core/vm/memory.go:79
github.com/ethereum/go-ethereum/eth/tracers.(*memoryWrapper).slice(0xc000010580, 0xffffffffffffffff, 0xfffffffffffffffe, 0xc79ab76d, 0xd3ee3a7ae30d56c8, 0xc000264620)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:101 +0xba
github.com/ethereum/go-ethereum/eth/tracers.(*memoryWrapper).pushObject.func1(0xc000010598, 0x7e27aa0)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:122 +0x7a
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0x7e01f70, 0x0)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/duktape.go:156 +0xb7
gopkg.in/olebedev/go-duktape%2ev3._cgoexpwrap_062d6de2de8d_goFunctionCall(0x7e01f70, 0x4060901)
	_cgo_gotypes.go:3511 +0x2b
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall_prop(0x7e01f70, 0x200000000, 0x0)
	_cgo_gotypes.go:2310 +0x4d
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp.func1(0xc000010570, 0x0, 0x2, 0x7ea0250)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/api.go:786 +0x76
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp(0xc000010570, 0x0, 0x2, 0x2)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/api.go:786 +0x3f
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).call(0xc0000b4840, 0x460296c, 0x4, 0xc000264a38, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:508 +0x120
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).CaptureState(0xc0000b4840, 0xc000254000, 0x0, 0xc00026e060, 0x2710, 0x3, 0xc0000ed6e0, 0xc0000ed700, 0xc000118240, 0x1, ...)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:568 +0x237
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc000258000, 0xc000118240, 0x4a7b240, 0x0, 0x0, 0x2700, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tintin/workspace/golang/go-ethereum/core/vm/interpreter.go:265 +0x69c
github.com/ethereum/go-ethereum/eth/tracers.runTrace(0xc0000b4840, 0x92, 0xc0000b4840, 0x0, 0x0, 0x102b48400000000f)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer_test.go:59 +0x283
github.com/ethereum/go-ethereum/eth/tracers.TestRegressionPanicSlice(0xc0000f2400)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer_test.go:72 +0xa5
testing.tRunner(0xc0000f2400, 0x462a118)
	/usr/local/opt/go/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:960 +0x350
FAIL	github.com/ethereum/go-ethereum/eth/tracers	1.144s
FAIL
Error: Tests failed.
```

##### getUint(<=-32) panic

**code:** 

**Note**: see `@note` comments

https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/tracer.go#L105

```go
// getUint returns the 32 bytes at the specified address interpreted as a uint.
func (mw *memoryWrapper) getUint(addr int64) *big.Int {
	if mw.memory.Len() < int(addr)+32 {  //@note - panic addr <= -32
		// TODO(karalabe): We can't js-throw from Go inside duktape inside Go. The Go
		// runtime goes belly up https://github.com/golang/go/issues/15639.
		log.Warn("Tracer accessed out of bound memory", "available", mw.memory.Len(), "offset", addr, "size", 32)
		return new(big.Int)
	}
	return new(big.Int).SetBytes(mw.memory.GetPtr(addr, 32))
}
```

**testcase:** 
```javascript
{ depths: [], step: function(log, db) { this.depths.push(log.memory.getUint(-64));}, fault: function() {}, result: function() { return this.depths; }}
```

**stacktrace:**

```console
Running tool: /usr/local/opt/go/libexec/bin/go test -timeout 30s github.com/ethereum/go-ethereum/eth/tracers -run ^(TestRegressionPanicGetUint)$

--- FAIL: TestRegressionPanicGetUint (0.01s)
panic: runtime error: slice bounds out of range [:-32] [recovered]
	panic: runtime error: slice bounds out of range [:-32]

goroutine 30 [running]:
testing.tRunner.func1(0xc000110400)
	/usr/local/opt/go/libexec/src/testing/testing.go:874 +0x3a3
panic(0x45c6e20, 0xc00014c240)
	/usr/local/opt/go/libexec/src/runtime/panic.go:679 +0x1b2
github.com/ethereum/go-ethereum/core/vm.(*Memory).GetPtr(...)
	/Users/tintin/workspace/golang/go-ethereum/core/vm/memory.go:95
github.com/ethereum/go-ethereum/eth/tracers.(*memoryWrapper).getUint(0xc0000ae570, 0xffffffffffffffc0, 0xffffffffffffffc0)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:112 +0x2aa
github.com/ethereum/go-ethereum/eth/tracers.(*memoryWrapper).pushObject.func2(0xc0000ae588, 0x8277a50)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:141 +0x71
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0x8201f70, 0x0)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/duktape.go:156 +0xb7
gopkg.in/olebedev/go-duktape%2ev3._cgoexpwrap_062d6de2de8d_goFunctionCall(0x8201f70, 0x4060901)
	_cgo_gotypes.go:3511 +0x2b
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall_prop(0x8201f70, 0x200000000, 0x0)
	_cgo_gotypes.go:2310 +0x4d
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp.func1(0xc0000ae560, 0x0, 0x2, 0x8279690)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/api.go:786 +0x76
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp(0xc0000ae560, 0x0, 0x2, 0x2)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/api.go:786 +0x3f
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).call(0xc0000cc790, 0x460296c, 0x4, 0xc000292a38, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:508 +0x120
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).CaptureState(0xc0000cc790, 0xc000282000, 0x0, 0xc00029c060, 0x2710, 0x3, 0xc00010d6a0, 0xc00010d6c0, 0xc00013a240, 0x1, ...)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:568 +0x237
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc000286000, 0xc00013a240, 0x4a7b240, 0x0, 0x0, 0x2700, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tintin/workspace/golang/go-ethereum/core/vm/interpreter.go:265 +0x69c
github.com/ethereum/go-ethereum/eth/tracers.runTrace(0xc0000cc790, 0x96, 0xc0000cc790, 0x0, 0x0, 0xd6fba500000000f)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer_test.go:59 +0x283
github.com/ethereum/go-ethereum/eth/tracers.TestRegressionPanicGetUint(0xc000110400)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer_test.go:99 +0xa5
testing.tRunner(0xc000110400, 0x462a108)
	/usr/local/opt/go/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:960 +0x350
FAIL	github.com/ethereum/go-ethereum/eth/tracers	0.579s
FAIL
Error: Tests failed.

```

##### peek(negative) panic

**code:** 

**Note**: see `@note` comments

https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/tracer.go#L148

```go

// peek returns the nth-from-the-top element of the stack.
func (sw *stackWrapper) peek(idx int) *big.Int {
	if len(sw.stack.Data()) <= idx {  //@note - panic if idx is negative
		// TODO(karalabe): We can't js-throw from Go inside duktape inside Go. The Go
		// runtime goes belly up https://github.com/golang/go/issues/15639.
		log.Warn("Tracer accessed out of bound stack", "size", len(sw.stack.Data()), "index", idx)
		return new(big.Int)
	}
	return sw.stack.Data()[len(sw.stack.Data())-idx-1]
}

```

**testcase:** 
```javascript
{depths: [], step: function(log) { this.depths.push(log.stack.peek(-1)); }, fault: function() {}, result: function() { return this.depths; }}
```

**stacktrace:**

```console
Running tool: /usr/local/opt/go/libexec/bin/go test -timeout 30s github.com/ethereum/go-ethereum/eth/tracers -run ^(TestRegressionPanicPeek)$

--- FAIL: TestRegressionPanicPeek (0.01s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 30 [running]:
testing.tRunner.func1(0xc00010c400)
	/usr/local/opt/go/libexec/src/testing/testing.go:874 +0x3a3
panic(0x45c6e20, 0xc000146240)
	/usr/local/opt/go/libexec/src/runtime/panic.go:679 +0x1b2
github.com/ethereum/go-ethereum/eth/tracers.(*stackWrapper).peek(0xc0000b0568, 0xffffffffffffffff, 0xffffffffffffffff)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:160 +0x192
github.com/ethereum/go-ethereum/eth/tracers.(*stackWrapper).pushObject.func2(0xc0000b0588, 0x790a930)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:176 +0x71
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0x7801f90, 0x0)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/duktape.go:156 +0xb7
gopkg.in/olebedev/go-duktape%2ev3._cgoexpwrap_062d6de2de8d_goFunctionCall(0x7801f90, 0x4060901)
	_cgo_gotypes.go:3511 +0x2b
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall_prop(0x7801f90, 0x200000000, 0x0)
	_cgo_gotypes.go:2310 +0x4d
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp.func1(0xc0000b0560, 0x0, 0x2, 0x7983ce0)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/api.go:786 +0x76
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp(0xc0000b0560, 0x0, 0x2, 0x2)
	/Users/tintin/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20190213234257-ec84240a7772/api.go:786 +0x3f
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).call(0xc0000ca790, 0x460296c, 0x4, 0xc0002aaa38, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:508 +0x120
github.com/ethereum/go-ethereum/eth/tracers.(*Tracer).CaptureState(0xc0000ca790, 0xc00029a000, 0x0, 0xc0002b4060, 0x2710, 0x3, 0xc0001096a0, 0xc0001096c0, 0xc000134240, 0x1, ...)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer.go:568 +0x237
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc00029e000, 0xc000134240, 0x4a7b240, 0x0, 0x0, 0x2700, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tintin/workspace/golang/go-ethereum/core/vm/interpreter.go:265 +0x69c
github.com/ethereum/go-ethereum/eth/tracers.runTrace(0xc0000ca790, 0x8d, 0xc0000ca790, 0x0, 0x0, 0x1ec6cca80000000f)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer_test.go:59 +0x283
github.com/ethereum/go-ethereum/eth/tracers.TestRegressionPanicPeek(0xc00010c400)
	/Users/tintin/workspace/golang/go-ethereum/eth/tracers/tracer_test.go:85 +0xa5
testing.tRunner(0xc00010c400, 0x462a110)
	/usr/local/opt/go/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:960 +0x350
FAIL	github.com/ethereum/go-ethereum/eth/tracers	0.501s
FAIL
Error: Tests failed.
```

**Comment by tintinweb** [comment]
added regression tests #20612

**Comment by adamschmideg** [comment]
It seems #20612 fixes this issue. Can you confirm?

**Comment by adamschmideg** [comment]
I assume this issue has been fixed. If the problem persists, please open a new issue.
