### ISSUE TITLE
Geth 1.9.10-stable crashes while syncing

### ISSUE THREAD

**Issue by cleanunicorn** [ethereum/go-ethereum#20615]
I was thinking something interesting might be in here. 

#### System information

Geth version: `1.9.10-stable`
OS & Version: `Linux cola 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux`
Commit hash: `58cf5686eab9019cc01e202e846a6bbc70a3301d`

#### Expected behaviour

Does not crash while syncing.

#### Actual behaviour

```
INFO [02-03|03:21:05.907] Imported new chain segment               blocks=15  txs=839  mgas=70.770  elapsed=8.298s    mgasps=8.528  number=9394364 hash=816674…1159be age=1d20h54m dirty=152.16MiB
INFO [02-03|03:21:14.545] Imported new chain segment               blocks=14  txs=1274 mgas=97.024  elapsed=8.638s    mgasps=11.232 number=9394378 hash=200c06…4df6cd age=1d20h50m dirty=156.23MiB
INFO [02-03|03:21:22.835] Deep froze chain segment                 blocks=99  elapsed=202.819ms number=9304390 hash=658b32…fb7451
INFO [02-03|03:21:23.295] Imported new chain segment               blocks=14  txs=1277 mgas=96.934  elapsed=8.749s    mgasps=11.079 number=9394392 hash=c0efcb…0a7fb5 age=1d20h48m dirty=158.52MiB
INFO [02-03|03:21:31.559] Imported new chain segment               blocks=11  txs=873  mgas=81.030  elapsed=8.264s    mgasps=9.804  number=9394403 hash=3d1790…8b3864 age=1d20h46m dirty=162.87MiB
INFO [02-03|03:21:39.886] Imported new chain segment               blocks=12  txs=848  mgas=75.271  elapsed=8.326s    mgasps=9.040  number=9394415 hash=671ce4…38cfa7 age=1d20h44m dirty=164.10MiB
panic: node 7fa2ad95f1fb29b6df183a7da54615cb7868b9a3a7aec2926343ebf573ecaee2: invalid number of list elements: 0 (decode path: [5]<-full)

goroutine 227109 [running]:
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc106ae3f60, 0x20, 0x20, 0xc02c88ca00, 0x134, 0x140, 0x20, 0xc02c88ca00)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/node.go:111 +0x196
github.com/ethereum/go-ethereum/trie.(*Database).node(0xc0000fb000, 0xb629fbf195ada27f, 0xcb1546a57d3a18df, 0x92c2aea7a3b96878, 0xe2aeec73f5eb4363, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/database.go:369 +0x49d
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc0b947d360, 0xc0901a2d00, 0x20, 0x20, 0xc06e8f6b40, 0x3, 0x41, 0xc084543050, 0x9, 0x10, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:398 +0xdf
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0b947d360, 0x13e6ee0, 0xc0e7720120, 0xc06e8f6b40, 0x41, 0x41, 0x3, 0x20300e, 0x20300e, 0x20300e, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:133 +0xef
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0b947d360, 0x13e4e20, 0xc03aca8000, 0xc06e8f6b40, 0x41, 0x41, 0x2, 0x20300e, 0x20300e, 0x20300e, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0b947d360, 0x13e4e20, 0xc03ad07e00, 0xc06e8f6b40, 0x41, 0x41, 0x1, 0x88, 0xc0397eb8a8, 0x421e76, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0b947d360, 0x13e4e20, 0xc03ad137c0, 0xc06e8f6b40, 0x41, 0x41, 0x0, 0x20, 0xc0b947d378, 0x20, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:126 +0x695
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc0b947d360, 0xc0b947d378, 0x20, 0x20, 0xc0b947d378, 0x20, 0x20, 0xeefdc0, 0xc07a555f30)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:101 +0x78
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc0b947d360, 0xc106ae3f20, 0x20, 0x20, 0xc0b947d360, 0x9300000000000020, 0x2, 0xeefa70, 0xc03aba6a50)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:79 +0x7b
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetCommittedState(0xc03ac92960, 0x13fe980, 0xc002444980, 0x3159d5eeeec80f87, 0x759f6e4e362f3b4e, 0xbb325d7669a27099, 0x3bcbce180bb47640, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/state_object.go:203 +0x218
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetState(0xc03ac92960, 0x13fe980, 0xc002444980, 0x3159d5eeeec80f87, 0x759f6e4e362f3b4e, 0xbb325d7669a27099, 0x3bcbce180bb47640, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/state_object.go:182 +0x147
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetState(0xc05a1b7440, 0x1aabf1953a26ad98, 0x327cb0444d1ff4bf, 0xeec80f870a1a2540, 0x362f3b4e3159d5ee, 0x69a27099759f6e4e, 0xbb47640bb325d76, 0xc03bcbce18, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:288 +0xc9
github.com/ethereum/go-ethereum/core/vm.opSload(0xc078801b38, 0xc03ac9a000, 0xc03a827080, 0xc0ede7b840, 0xc0ede7b9a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/vm/instructions.go:629 +0x110
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc03ac9a000, 0xc03a827080, 0xc02f3e16e0, 0x4, 0x4, 0xc0397ec100, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/vm/interpreter.go:270 +0x4a6
github.com/ethereum/go-ethereum/core/vm.run(0xc03ac96000, 0xc03a827080, 0xc02f3e16e0, 0x4, 0x4, 0x2000, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/vm/evm.go:67 +0x276
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc03ac96000, 0x13d8540, 0xc106a0ae60, 0x1aabf1953a26ad98, 0x327cb0444d1ff4bf, 0xa1a2540, 0xc02f3e16e0, 0x4, 0x4, 0x44198, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/vm/evm.go:242 +0x517
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc08416bce0, 0x1402fa0, 0xc0d8b4c000, 0xc07ee86850, 0xc08416bce0, 0xc0d8b4c000, 0xc0d8b4c000, 0x1117a00)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state_transition.go:218 +0x3da
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc03ac96000, 0x1402fa0, 0xc0d8b4c000, 0xc07ee86850, 0x4b62b92556a24710, 0x2203b353, 0xc04dd876c0, 0xaae017dcd5540b5a, 0xd0a3bb42d3d38dc, 0x4c9c023e, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state_transition.go:136 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x1d6e720, 0x13e4160, 0xc0054fa000, 0x0, 0xc07ee86850, 0xc05a1b7440, 0xc051ae1440, 0xc05dce43f0, 0xc0397f3b08, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state_processor.go:99 +0x2ac
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc0001bf420, 0xc015078900, 0xc05a1b7440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state_processor.go:71 +0x41c
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0054fa000, 0xc0872f6000, 0x800, 0x800, 0xb903399edc574301, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1673 +0xca2
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0054fa000, 0xc0872f6000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1489 +0xccb
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc005578540, 0xc081e46000, 0x800, 0x800, 0x800, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1557 +0x534
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc005578540, 0xc0a60ffe00, 0x1246ad997651d5d3)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1531 +0x79
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc005578540, 0xc0b61a35c0, 0xc1453b2150)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:534 +0x63
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:534 +0xaf
```

#### Steps to reproduce the behaviour

It was started with arguments

```
./geth --datadir=./chaindata \
    --rpc --rpcapi="eth,net,rpc,web3,txpool,personal,debug,account" --ws \
    --rpccorsdomain='*' --port 30303 \
    --syncmode=fast \
    console
```

**Comment by holiman** [comment]
> I was thinking something interesting might be in here.

I'd agree. @fjl ISTR there is some way to check the db contents for the key `7fa2ad95f1fb29b6df183a7da54615cb7868b9a3a7aec2926343ebf573ecaee2`-- if so, we can verify the contents of @cleanunicorn 's db versus one of our nodes.

**Comment by cleanunicorn** [comment]
I already restarted the node, I'm not sure if the db is the same anymore. 

But if you tell me how to check the contents, I can still do it.

**Comment by holiman** [comment]
Did you just restart it, or did you re-sync it?

**Comment by cleanunicorn** [comment]
> Did you just restart it, or did you re-sync it?

Just restart and it did not error anymore.

**Comment by karalabe** [comment]
This seems an odd issue. It kind of points to the database getting corrupted, but not sure how that could happen really. With a resync solving it, I don't think it's a hardware error. Unfortunately there's not much information to go on. I could imagine a node going missing, but that has a different error (and no crash). The node being in the database (via it's hash) and failing to parse is super impossible-ish. I'll close this PR for now, maybe we can revisit if it pops up again.
