### ISSUE TITLE
Node crash during initial sync

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#2065]
```
I1211 05:28:13.413700    3202 blockchain.go:1230] imported 256 block(s) (0 queued 0 ignored) including 232 txs in 1.580951992s.
 #264331 [06112411 / c413284f]
I1211 05:28:16.122494    3202 blockchain.go:1230] imported 256 block(s) (0 queued 0 ignored) including 336 txs in 2.70766272s. 
#264587 [9701ca50 / 64aba473]
I1211 05:28:23.491829    3202 blockchain.go:1230] imported 256 block(s) (0 queued 0 ignored) including 1006 txs in 7.368080019s
. #264843 [4a1a3db0 / 7d4063ca]
E1211 05:28:24.752810    3202 trie.go:309] Dangling hash node ref 3c64633338376630323666623937613262333331633063386166356330326
1613833366262316664303238353339663961313762356661316531306262353633333e20: open /root/.ethereum/chaindata/038246.ldb: too many 
open files
E1211 05:28:24.753781    3202 trie.go:309] Dangling hash node ref 3c34366432343136616131356235386438336635376264346665646132316
6363733343836363262363135656565363630363130666363313238396666393332393e20: open /root/.ethereum/chaindata/040302.ldb: too many 
open files
E1211 05:28:24.836195    3202 trie.go:309] Dangling hash node ref 3c33636163353934343637333831626337663166613335626162663663656
5623838316237373438326236616434626331653466383232343034346363306132643e20: open /root/.ethereum/chaindata/040300.ldb: too many 
open files
E1211 05:28:24.836272    3202 trie.go:309] Dangling hash node ref 3c33636163353934343637333831626337663166613335626162663663656
5623838316237373438326236616434626331653466383232343034346363306132643e20: open /root/.ethereum/chaindata/040300.ldb: too many 
open files
E1211 05:28:24.836418    3202 trie.go:309] Dangling hash node ref 3c33636163353934343637333831626337663166613335626162663663656
5623838316237373438326236616434626331653466383232343034346363306132643e20: open /root/.ethereum/chaindata/040300.ldb: too many 
open files
E1211 05:28:24.836785    3202 blockchain.go:1363] Bad block #264887 (0x94b4c6332401f0c27566a99fe02dc1ff94c27dea4152cb0b12d76929
1ccaa10e)
E1211 05:28:24.836815    3202 blockchain.go:1364]     invalid receipt root hash. received=50eb1625350fe7bd5a1ec31ee10415df279602f890eefdc28bd5a922c13eff61 calculated=ecd51b07cd26198ba7f61d656578bd506b991287ee76e3beb1a40c6af57f1eda
I1211 05:28:24.836892    3202 downloader.go:267] Synchronisation failed: invalid receipt root hash. received=50eb1625350fe7bd5a1ec31ee10415df279602f890eefdc28bd5a922c13eff61 calculated=ecd51b07cd26198ba7f61d656578bd506b991287ee76e3beb1a40c6af57f1eda
E1211 05:28:24.907849    3202 trie.go:309] Dangling hash node ref 3c633434666630376434656234396335663431353765613932326164626462613139643535386639666138356436653135353237346635636238646464333262663e20: open /root/.ethereum/chaindata/040141.ldb: too many open files
E1211 05:28:24.908117    3202 trie.go:309] Dangling hash node ref 3c333363323564343263666631663161363532616138386330386539313436636236613332313161316364343934356364313035623264363661383865333530373e20: open /root/.ethereum/chaindata/038169.ldb: too many open files
E1211 05:28:24.908219    3202 trie.go:309] Dangling hash node ref 3c363136653164626635343561376664323964323562393664373535633661343336623866623966333937313663313339623365643136633066356339613232623e20: open /root/.ethereum/chaindata/040306.ldb: too many open files
```

and

```
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Execute(0xc8219f9350, 0xc8283ffcc0, 0x0, 0x0, 0x0, 0x0)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:127 +0xa1
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc822382fb0, 0xc8283ffcc0, 0x0, 0x0, 0x0, 0x0)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:67 +0x35f
github.com/ethereum/go-ethereum/rpc/comms.(*handler).ServeHTTP(0xc820d487c0, 0x7fcf4063faa0, 0xc82deffb80, 0xc824322540)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/comms/http.go:126 +0x5c6
net/http.serverHandler.ServeHTTP(0xc821a29620, 0x7fcf4063faa0, 0xc82deffb80, 0xc824322540)
        /usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82deffad0)
        /usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 195354 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc831431ce0, 0x0, 0x7fcf00000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/peer.go:354 +0x221
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc82016a240, 0xc833c2cc80, 0x0, 0x0)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/handler.go:254 +0xb7
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc82016a240, 0xc833c2cc80, 0x0, 0x0)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/handler.go:242 +0xa9e
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc835d66780, 0x7fcf558c2a18, 0xc831431ce0, 0x0, 0x0)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/handler.go:124 +0xae
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc831431ce0, 0xc835d66780)
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/peer.go:300 +0x8c
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /build/ethereum-AO9yaH/ethereum-1.3.2+2wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/peer.go:309 +0x304
```

**Comment by drupalnomad** [comment]
It was behaving very oddly on https://stats.ethdev.com/ - kept on switching between #1xx,xxx and #2xx,xxx as if there was a fork in the blockchain.

I have resumed the syncing and it is no longer doing this.

**Comment by fjl** [comment]
Do you have the full trace, by any chance?

**Comment by drupalnomad** [comment]
Shit I deleted it. It was 99 MB.

**Comment by fjl** [comment]
OK, the log snippets suggest that block data could not be read or written because it ran out of file descriptors.
This can mean two things: 

* The limit is set too low. Please check the limit using `ulimit -n`. What is displayed when you run this.
* Geth is leaking file descriptors.

**Comment by drupalnomad** [comment]
```
root@ubuntu:~# ulimit -u
7981
```

It's a fresh Ubuntu 15.10 Linode.

This is the command I used to run it:
```
geth --maxpeers 2500 --shh --rpc --rpcapi db,eth,net,web3,shh 2>/root/.ethereum/logfile &
```

**Comment by drupalnomad** [comment]
There was only about 20 peers connected when this occurred.

**Comment by fjl** [comment]
`ulimit -u` returns the limit on running processes. What does `ulimit -n` display?

**Comment by drupalnomad** [comment]
Oh sorry.
```
root@ubuntu:~# ulimit -n
1024
```

**Comment by drupalnomad** [comment]
It happened again: https://ipfs.io/ipfs/QmQqNucCJoXuPUSY5RbbxcKc7wf7nAm7jNKRjfzyY16MU6

**Comment by fjl** [comment]
Please kill geth with SIGQUIT (use `killall -QUIT geth`) so we can see the goroutine stacks.
That will make it possible to see whether something is blocking the closing of files.

**Comment by drupalnomad** [comment]
https://ipfs.io/ipfs/QmY2SBrQghAAcAL1WWHzF5mifpMakAqArzvx4ypVQvzcBB

**Comment by fjl** [comment]
Sorry, I meant please kill it while the issue happens.

**Comment by datajerk** [comment]
Hi, I get this as well from time to time, was it fixed?  Thanks.
