### ISSUE TITLE
You've encountered a sought after, hard to reproduce bug. Please report this to the developers 

### ISSUE THREAD

**Issue by atoken-ops** [ethereum/go-ethereum#20737]
INFO [03-03|14:24:56] Imported new chain segment               blocks=2 txs=154 mgas=0.439 elapsed=4.328s   mgasps=0.102 number=17506937 hash=cf8228…8bc63d cache=0.00B
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues

```
index allocation went beyond available resultCache space
/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510
goroutine 21486 [running]:
runtime/debug.Stack(0x4a, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x83
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1a
github.com/ethereum/go-ethereum/common.Report(0x17719cb0, 0x1, 0x1)
	/ext-go/1/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x164
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xe6b7f40, 0xb4ce240, 0x80, 0x171eb500, 0xd840ea0, 0x171eb520, 0x171eb540, 0x8b2469c, 0x0, 0x40600000, ...)
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510 +0x5bb
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xe6b7f40, 0xb4ce240, 0x80, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:462 +0xba
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xb4a8120, 0x8cd8ea0, 0xb48d1d0, 0xe77ee80, 0x17719f38, 0xd104dc0, 0x17719f30, 0x17719f68, 0x17719f60, 0x17719f58, ...)
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1115 +0x761
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xb4a8120, 0x10b2277, 0x0, 0x232013f, 0xd1190707)
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:936 +0x2ec
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0x16540fb4, 0x18da28b5)
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:466 +0x34
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0x16f99940, 0x16a10f00, 0x16f9d980)
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0x47
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/ext-go/1/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0x9a
#### BUG! PLEASE REPORT ####
INFO [03-03|14:25:05] Imported new chain segment               blocks=146 txs=1366 mgas=0.798 elapsed=9.253s   mgasps=0.086 number=17507083 hash=69a7c7…e390ba cache=0.00B
```

**Comment by karalabe** [comment]
What network is this on? It's def not Ethereum mainnet

**Comment by karalabe** [comment]
What version of Geth is this? Is it even Geth?
