### ISSUE TITLE
Invalid memory address 1.9.13, Windows

### ISSUE THREAD

**Issue by remyroy** [ethereum/go-ethereum#20977]
#### System information

Geth version: `geth version`
```
Version: 1.9.13-stable
Git Commit: cbc4ac264e9671898bff6ec7e434da3eca4bd273
Git Commit Date: 20200416
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: windows
GOPATH=
GOROOT=C:\go
```
OS & Version: Windows 10
Commit hash : 1.9.13 release

#### Expected behaviour
No crash during normal usage

#### Actual behaviour
Crashed randomly during normal usage

#### Steps to reproduce the behaviour
I'm not sure what are the exact steps to reproduce this issue. It seems a bit random but here is what I did.

- Start geth 1.9.13 with the following command line: `geth.exe --ipcdisable --verbosity 1 --light.serve 10 console`
- Perform some commands in console like typing `web3.net` to show network info.

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0xcb5ef9]

goroutine 727132 [running]:
github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg(0xc0053dc870, 0xc0c16eb950, 0xc016a68f50, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:183 +0x119
github.com/ethereum/go-ethereum/les.(*serverHandler).handle(0xc0053dc870, 0xc0c16eb950, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:172 +0x98f
github.com/ethereum/go-ethereum/les.(*serverHandler).runPeer(0xc0053dc870, 0x3, 0xc165792f60, 0x16c5f40, 0xc06b18f860, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:108 +0x115
github.com/ethereum/go-ethereum/les.(*lesCommons).makeProtocols.func1(0xc165792f60, 0x16c5f40, 0xc06b18f860, 0xc0851ea020, 0xc08c099fa0)
        C:/gopath/src/github.com/ethereum/go-ethereum/les/commons.go:94 +0x53
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc06b18f860, 0xc165792f60, 0x16c5f40, 0xc06b18f860)
        C:/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:368 +0x6d
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        C:/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:367 +0x20a
````

**Comment by karalabe** [comment]
We can't really see what's wrong with the code that would result in this crash. Did it happen ever again? Was this during shutdown or normal mode of operation?
