### ISSUE TITLE
Sync panic: runtime error: invalid memory address or nil pointer dereference (*Downloader).findAncestor

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#21001]
Running geth-linux-amd64-1.9.13-cbc4ac26

```
INFO [04-29|05:12:22.854] Importing sidechain segment              start=2603003 end=2603945                                                                       [1/1929]
ERROR[04-29|05:12:25.442] 
########## BAD BLOCK #########
Chain config: {ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 1561651, Muir Glaci
er: <nil>, Engine: clique}

Number: 2603095
Hash: 0x01484227c43905bc055d9009b9a1b79d7997d4a54a574379e0302141f69221c9
         0: cumulative: 21000 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x4469d486c75064a80c41e7ca35d5e95f8ed85f89c6ee25019391222b969fe
77c logs: [] bloom: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000 state: 
         1: cumulative: 3737295 gas: 3716295 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xcb55e49e6d1f92b8e8c26533573fc72bf6c959d2d18964ee13e159fff
cdaeacc logs: [] bloom: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000 state: 


Error: invalid merkle root (remote: 0475158b868e75fae8f71e0814d38fcec08056da9e413335e1e42b347ad952a8 local: db71c3fc0eda721f479cbc907659b1893414e9a2ba24dc841304145888b5f1f
1)
##############################
 
WARN [04-29|05:12:25.443] Synchronisation failed, dropping peer    peer=8ddd4ff70f007631 err="retrieved hash chain is invalid"
INFO [04-29|05:12:31.204] Looking for peers                        peercount=1 tried=5 static=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xb106dc]

goroutine 546 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00134d340, 0xc004558e10, 0xc000b34fc0, 0x0, 0x0, 0xa)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:877 +0x14fc
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00134d340, 0xc004558e10, 0x3c0784b3c4c884e2, 0xed832ec9a1495358, 0x5640864266891aeb, 0xb54f627
0a5a63cd3, 0xc00c4f6160, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:443 +0x3da
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc00134d340, 0xc000d86710, 0x10, 0x3c0784b3c4c884e2, 0xed832ec9a1495358, 0x5640864266891aeb, 0xb5
4f6270a5a63cd3, 0xc00c4f6160, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:411 +0x36c
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc00134d340, 0xc000d86710, 0x10, 0x3c0784b3c4c884e2, 0xed832ec9a1495358, 0x5640864266891aeb, 0xb5
4f6270a5a63cd3, 0xc00c4f6160, 0x0, 0x1000000000001, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:323 +0x8e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xc0013be5a0, 0xc00c4d2580, 0xf2c5cd888491b0b9, 0x3b88e5f085e0315c)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/sync.go:289 +0x98
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0013926f0, 0xc00c4d2580)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/sync.go:283 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/sync.go:283 +0x7a
```

**Comment by ligi** [comment]
Did you have an unclean shutdown before this crash?
We really need #20859 to not need to ask this question anymore

**Comment by ethers** [comment]
Yes it crashed before this one.  #20859 looks very helpful.

**Comment by holiman** [comment]
The root cause here is that the db has been corrupted. There's not a whole lot that can be done about it, right now, but @karalabe is working on making rollback-scenarios a lot better. We've also done some work trying to ensure that things like currentBlock etc are stored in the right order, to minimize the impacts of crashes.
