### ISSUE TITLE
fatal error: unexpected signal during runtime execution when starting peer to peer node

### ISSUE THREAD

**Issue by csyzhou1037** [ethereum/go-ethereum#21031]
#### System information

Geth
Version: 1.9.13-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.14.2_1/libexec
#### Expected behaviour

Geth should output "Starting peer-to-peer node" after outputting "Maximum peer count"

#### Actual behaviour

Output "fatal error: unexpected signal during runtime execution" and crash down

#### Steps to reproduce the behaviour

I only execute "geth"

#### Backtrace

````
INFO [05-06|16:44:05.841] Starting Geth on Ethereum mainnet...
INFO [05-06|16:44:05.841] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [05-06|16:44:05.842] Maximum peer count                       ETH=50 LES=0 total=50
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff35ba9d64]

runtime stack:
runtime.throw(0x4dcac0d, 0x2a)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/signal_unix.go:679 +0x46a

goroutine 1 [syscall]:
runtime.cgocall(0x4ac8867, 0xc00063db70, 0x0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc00063db40 sp=0xc00063db08 pc=0x4005afb
github.com/karalabe/usb._Cfunc_hid_enumerate(0x2c97, 0x0)
	_cgo_gotypes.go:270 +0x4e fp=0xc00063db70 sp=0xc00063db40 pc=0x472bc9e
github.com/karalabe/usb.enumerateHid(0x100002c97, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/hid_enabled.go:40 +0x83 fp=0xc00063dc88 sp=0xc00063db70 pc=0x472c963
github.com/karalabe/usb.Enumerate(0x2c97, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/usb_enabled.go:58 +0x10b fp=0xc00063dd38 sp=0xc00063dc88 pc=0x472b59b
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).refreshWallets(0xc0000c8000)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/accounts/usbwallet/hub.go:163 +0xd9 fp=0xc00063e1b0 sp=0xc00063dd38 pc=0x478f469
github.com/ethereum/go-ethereum/accounts/usbwallet.newHub(0x4d9a159, 0x6, 0x2c97, 0xc00003a480, 0x9, 0x9, 0xffa0, 0x0, 0x4e6deb8, 0x0, ...)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/accounts/usbwallet/hub.go:114 +0xe6 fp=0xc00063e1e8 sp=0xc00063e1b0 pc=0x478f186
github.com/ethereum/go-ethereum/accounts/usbwallet.NewLedgerHub(0x4c44c80, 0x0, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/accounts/usbwallet/hub.go:73 +0xa5 fp=0xc00063e258 sp=0xc00063e1e8 pc=0x478f065
github.com/ethereum/go-ethereum/node.makeAccountManager(0xc0001b4600, 0x4d978f9, 0x4, 0x0, 0xffffffffffffffff, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/node/config.go:499 +0x489 fp=0xc00063e3a0 sp=0xc00063e258 pc=0x47b8f69
github.com/ethereum/go-ethereum/node.New(0xc0001a0da0, 0xc0001a0da0, 0x6, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/node/node.go:103 +0x123 fp=0xc00063e468 sp=0xc00063e3a0 pc=0x47baa13
main.makeConfigNode(0xc00028e420, 0xc0005b0000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/cmd/geth/config.go:125 +0x2f7 fp=0xc00063f008 sp=0xc00063e468 pc=0x4a9d2e7
main.makeFullNode(0xc00028e420, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/cmd/geth/config.go:149 +0x72 fp=0xc00063fb78 sp=0xc00063f008 pc=0x4a9d752
main.geth(0xc00028e420, 0x0, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/cmd/geth/main.go:333 +0xf7 fp=0xc00063fbf0 sp=0xc00063fb78 pc=0x4aa15d7
gopkg.in/urfave/cli%2ev1.HandleAction(0x4bdba40, 0x4e6fce0, 0xc00028e420, 0xc0001d0960, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8 fp=0xc00063fc18 sp=0xc00063fbf0 pc=0x45dcc78
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002d4000, 0xc0001181b0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5dd fp=0xc00063ff28 sp=0xc00063fc18 pc=0x45dad9d
main.main()
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/cmd/geth/main.go:253 +0x55 fp=0xc00063ff88 sp=0xc00063ff28 pc=0x4aa07a5
runtime.main()
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203 +0x212 fp=0xc00063ffe0 sp=0xc00063ff88 pc=0x4039372
runtime.goexit()
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00063ffe8 sp=0xc00063ffe0 pc=0x4069ab1

goroutine 19 [chan receive]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc0001481e0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_recursive.go:125 +0xc4
created by github.com/rjeczalik/notify.newRecursiveTree
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_recursive.go:119 +0x132

goroutine 20 [syscall, locked to thread]:
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:224 +0x41
github.com/rjeczalik/notify.init.1.func1()
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_fsevents_cgo.go:72 +0x3c
created by github.com/rjeczalik/notify.init.1
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/.brew_home/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_fsevents_cgo.go:63 +0x4e

goroutine 21 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 22 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 23 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 24 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 25 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 26 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 27 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 28 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 29 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 30 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 31 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 32 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 33 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 34 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 35 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 36 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000192a40)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/core/tx_cacher.go:55 +0x9f

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x5a8d3c0)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/metrics/meter.go:289 +0x78
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/metrics/meter.go:70 +0x105

goroutine 7 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0003ba000)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/consensus/ethash/sealer.go:278 +0x258
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/consensus/ethash/sealer.go:262 +0x2ae

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/usr/local/Cellar/go/1.14.2_1/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/usr/local/Cellar/go/1.14.2_1/libexec/src/os/signal/signal.go:127 +0x44

goroutine 67 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc000129820)
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/accounts/keystore/watch.go:94 +0x4c1
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/private/tmp/ethereum-20200418-26198-18z4r79/go-ethereum-1.9.13/accounts/keystore/watch.go:52 +0x59
````

**Comment by csyzhou1037** [comment]
I install ethereum through homebrew:
````
brew install ethereum
````

**Comment by karalabe** [comment]
What macos version are you running on?

You can run with `--nousb` that should disable this part of the code, but it's a bit worrying that it crashed inside the usb library.

**Comment by csyzhou1037** [comment]
> What macos version are you running on?
> 
> You can run with `--nousb` that should disable this part of the code, but it's a bit worrying that it crashed inside the usb library.

The version is macOS Catalina 10.15.4. 

The error disappeared after I ran 'geth --nousb'. Things are going well by far.

**Comment by qasimraheem** [comment]
try to build with go version 1.16.6

**Comment by nesxezcovcy4jYrxob** [comment]
hh
