### ISSUE TITLE
panic (goja) on `personal.sign()`

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#21046]
start with e.g. `geth --dev console`

```
instance: Geth/v1.9.14-unstable-3ed1810a-20200507/linux-amd64/go1.13.4
coinbase: 0x6a4ef8a99898679e8a06b70688e1f66aa605e56b
at block: 0 (Thu Jan 01 1970 01:00:00 GMT+0100 (CET))
 datadir: 
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

> 
> personal.sign()
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xead2f9]

goroutine 164 [running]:
github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc000de7d38)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/runtime.go:889 +0x98
panic(0x1099940, 0x1ca6460)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/dop251/goja.(*vm).try.func1(0xc00047f450, 0x0, 0xc000de7c00, 0x0, 0x0, 0x0, 0xc000de7c58)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/vm.go:377 +0x3b0
panic(0x1099940, 0x1ca6460)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ethereum/go-ethereum/console.(*bridge).Sign(0xc0005ac390, 0x14cc2e0, 0xc0017e96e0, 0xc0000b8900, 0x0, 0x0, 0xc000429800, 0x1f4d680, 0x10, 0x203000, ...)
	/home/user/go/src/github.com/ethereum/go-ethereum/console/bridge.go:281 +0x159
github.com/ethereum/go-ethereum/internal/jsre.MakeCallback.func1(0x14cc2e0, 0xc0017e96e0, 0xc0000b8900, 0x0, 0x0, 0xc000de7a30, 0xc00181e480)
	/home/user/go/src/github.com/ethereum/go-ethereum/internal/jsre/jsre.go:264 +0x9f
github.com/dop251/goja.(*vm)._nativeCall(0xc00047f450, 0xc001903c30, 0x0)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/vm.go:1839 +0x291
github.com/dop251/goja.call.exec(0x0, 0xc00047f450)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/vm.go:1823 +0x4a2
github.com/dop251/goja.(*vm).run(0xc00047f450)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/vm.go:289 +0x99
github.com/dop251/goja.(*vm).try(0xc00047f450, 0xc000de7c60, 0x0)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/vm.go:383 +0x147
github.com/dop251/goja.(*vm).runTry(0xc00047f450, 0xe543e5)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/vm.go:388 +0x4e
github.com/dop251/goja.(*Runtime).RunProgram(0xc000429800, 0xc00018d680, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/runtime.go:900 +0x1ec
github.com/dop251/goja.(*Runtime).RunScript(0xc000429800, 0x0, 0x0, 0xc0002c88d0, 0x10, 0xc000000180, 0x3, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/runtime.go:879 +0x9d
github.com/dop251/goja.(*Runtime).RunString(...)
	/home/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20200219165308-d1232e640a87/runtime.go:868
github.com/ethereum/go-ethereum/internal/jsre.(*JSRE).Evaluate.func1(0xc000429800)
	/home/user/go/src/github.com/ethereum/go-ethereum/internal/jsre/jsre.go:275 +0x5c
github.com/ethereum/go-ethereum/internal/jsre.(*JSRE).runEventLoop(0xc000478b40)
	/home/user/go/src/github.com/ethereum/go-ethereum/internal/jsre/jsre.go:204 +0x603
created by github.com/ethereum/go-ethereum/internal/jsre.New
	/home/user/go/src/github.com/ethereum/go-ethereum/internal/jsre/jsre.go:79 +0x14b

```
Perhaps self-evident: If performed on an attached geth, the crash happens on the client, not the server.

**Comment by holiman** [comment]
Does not happen on `personal.sign("","")`

**Comment by holiman** [comment]
I noticed this while on a branch which _might_ not include any recent changes to goja

**Comment by holiman** [comment]
Nope, happens on `master` too
