### ISSUE TITLE
"Filter Not Found" random exception with Geth and Web3J

### ISSUE THREAD

**Issue by kunalbarchha** [ethereum/go-ethereum#21386]
Web3J version - 5.0.0 Geth version - 1.9.14 -Stable Ubuntu 18.04 - 64-bit 32GB RAM 1.9 TB HDD Geth fully synced and running JDK - 1.8 Spring - 1.5

I have two subscription method defined as @PostConstruct : TransactionFlowable and BlockFlowable.

The problem is that the transactionFlowable subscription randomly throws "Filter Not Found" exception. It runs for few minutes to few hours. When I check Geth, it is running perfectly fine and syncing new incoming blocks.

I have checked Web3J issues, StackOverflow, and what not. Somehow there are many people facing this issue, but there is no working solution posted. Some solutions are dated back to 2018, which are not relevant with latest version.

If someone can help out on the issue, that will be really nice. Need to run both the subscription reliably for production, 24x7.

Below is the code Snippet: 

```
@PostConstruct
public void start() throws OnErrorNotImplementedException, ConnectException {

WebSocketService socketService = new WebSocketService(config.getMainNetSocket(), true);        web3J();
log.info("Started >>>>>>> ");

Web3j web3jSocket = Web3j.build(socketService);
socketService.connect();

synchronized (this) {
    Disposable subscription = web3jSocket.transactionFlowable().subscribe(
            tx ->
            {
                log.info("Tx Hash > " + tx.getHash());
                getTransactionByHash(tx.getHash());

            }, throwable -> {
                log.info("Message >>>> " + throwable.getMessage());
                throwable.printStackTrace();
            });
}

```
Exception Log:

```
2020-06-10 11:27:25.284  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0x3ee4adbe9789189662cdc3d61655a4b68845c791f01c37db83c7e53ba8fa0a4c
2020-06-10 11:27:26.758  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0x72ebd62060f78d91dc4bc33e8d88f39307365f87
2020-06-10 11:27:26.760  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0x3d50ebcdb3fa95e81d9ef8f4ee978a80d3aa5a43b8d274d9f4860ee440d36e27
2020-06-10 11:27:28.187  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0xdac17f958d2ee523a2206206994597c13d831ec7
2020-06-10 11:27:28.189  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0xde55b36788acdfcf75fe080f1ca808a24e1e8e70bb266e0c6ce875892959d5d5
2020-06-10 11:27:29.602  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0x47dcfcaf9aca005cbe955fbaff11165e70d28bca
2020-06-10 11:27:29.603  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0x7592438f0a11f6cdcfb2f8374f8ffb5a2e7f6d0b1605b57676bfd0e26f9de2ff
2020-06-10 11:27:31.020  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0xca9ca2dabf9024e7588ab10c8c2116f5809fa561
2020-06-10 11:27:31.023  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0x3f36cd6caaa8b3d158bb3b6535cbe7502925a85ac44c405857473cec9aa8ee9f
2020-06-10 11:27:32.439  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0xdac17f958d2ee523a2206206994597c13d831ec7
2020-06-10 11:27:32.441  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0xd42751dded2588e9152bf3d81b3f84b729ee3aa17e6b46ebc8cbf09ee14e35bd
2020-06-10 11:27:34.639  INFO 20268 --- [pool-9-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0x98ad263a95f1ab1abff41f4d44b07c3240251a0a
2020-06-10 11:27:34.643  WARN 20268 --- [pool-9-thread-2] org.web3j.protocol.core.filters.Filter   : The filter has not been found. Filter id: 66674882484826508490032443079398703497
2020-06-10 11:27:34.654 ERROR 20268 --- [pool-9-thread-2] org.web3j.protocol.core.filters.Filter   : Error sending request

org.web3j.protocol.core.filters.FilterException: Error sending request
at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:194) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.run(Filter.java:104) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.reinstallFilter(Filter.java:155) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:137) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92) ~[core-5.0.0.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_241]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_241]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_241]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]
Caused by: java.io.IOException: Interrupted WebSocket request
at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:168) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.BlockFilter.sendRequest(BlockFil

ter.java:34) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.run(Filter.java:59) ~[core-5.0.0.jar:na]
... 10 common frames omitted
Caused by: java.lang.InterruptedException: null
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347) ~[na:1.8.0_241]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[na:1.8.0_241]
at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:165) ~[core-5.0.0.jar:na]
... 13 common frames omitted
```

**Comment by i-norden** [comment]
This looks like a [likely culprit](https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L77). If a filter goes stale and is removed then that error could be thrown [here](https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L379) or [here](https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L438).

**Comment by holiman** [comment]
> This looks like a likely culprit. If a filter goes stale and is removed then that error could be thrown here or here.

Well, the linked places does throw `fmt.Errorf("filter not found")`, but that exact sentence is not present in the logs. What we do see, however, is 
```
Caused by: java.io.IOException: Interrupted WebSocket request
at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:168) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.BlockFilter.sendRequest(BlockFil
```
So the cause might just as well be some websocket error. If geth returned an actual error to a json-rpc request, I would assume that the error message would be surfaced and included in the java log...?

**Comment by ligi** [comment]
@i-norden it would be really helpful if you could provide us with the code to reproduce the issue - ideally reduced to the minimum that triggers the problem.

**Comment by i-norden** [comment]
@ligi sorry for the confusion, it's not my error. I was just throwing a lead out there.

**Comment by kunalbarchha** [comment]
@ligi That's my error. 

"2020-06-10 11:27:34.643  WARN 20268 --- [pool-9-thread-2] org.web3j.protocol.core.filters.Filter   : The filter has not been found. Filter id: 66674882484826508490032443079398703497"

I am subscribing to pending transaction, it works perfectly fine for few minutes, but after that it throws above mentioned error. The same happens with block subscription. In short, Geth removes the filter after sometime and that causes this error. 

Google " Random Filter not found web3j" the issue is dated back to 2017 and I wonder why no one has yet posted it here. 

P.S : I tried running the local instance of GETH after full sync and also on Infura. The problem is same. I also talked with Infura support and they said it is a general issue most are facing. However, no one gave me a production-ready solution to this problem. 
Below is the minimum code to reproduce the error: 
```

WebSocketService socketService = new WebSocketService("wss://mainnet.infura.io/ws/v3/<infura token>", true);
    Web3j web3j = Web3j.build(new HttpService("https://rinkeby.infura.io/v3/<infura token>"));

    @PostConstruct
    public void start() throws OnErrorNotImplementedException, ConnectException {

        log.info("Started >>>>>>> ");

        Web3j web3jSocket = Web3j.build(socketService);
        socketService.connect();

        web3jSocket.transactionFlowable().subscribe(tx ->
                {
                    log.info("Tx Hash > " +tx.getHash());
//                    saveTxHash(tx.getHash());

//                }, throwable -> {
//                    log.info("Message >>>> "+throwable.getMessage());
//                        throwable.printStackTrace();
                        }); 
```

**Comment by kunalbarchha** [comment]
I think @i-norden  's comment makes sense : https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L77

I have tried tracking the time it takes to throw that exception, and it is usually in multiple of 5.

**Comment by ligi** [comment]
hm - I can't seem to repro it with the code you gave - running over 5min now - output here: https://gist.github.com/ligi/d7f8b0aeb19bbc81bf946249c3c553a2
code here: https://github.com/ligi/GethIssue21386

**Comment by ligi** [comment]
dam - directly after sending this issue I got that error:

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:275)
	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471)
	at org.web3j.protocol.core.filters.BlockFilter.process(BlockFilter.java:42)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:144)
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.web3j.protocol.rx.JsonRpc2_0Rx.toTransactions(JsonRpc2_0Rx.java:252)
	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:265)
	... 15 more
Exception in thread "pool-3-thread-2" io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:275)
	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471)
	at org.web3j.protocol.core.filters.BlockFilter.process(BlockFilter.java:42)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:144)
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.web3j.protocol.rx.JsonRpc2_0Rx.toTransactions(JsonRpc2_0Rx.java:252)
	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:265)
	... 15 more
```

**Comment by kunalbarchha** [comment]
@ligi You are getting different exception because you have not implemented OnErrorNotImplemented exception. if you surround it in try and catch, then print the exception message that you receive from Geth, it will likely be "Filter Not Found".

**Comment by ligi** [comment]
Yea - just wrapped your code with a gradle script so the one that wants to look at it from the go side does not need to deal with java tooling ..

**Comment by kunalbarchha** [comment]
Noted. I talked with Nethereum dev on Gitter and also with Web3J guy on Gitter, it has something to do with Filter being deleted by Geth. That was the same reply I got from Infura support.

**Comment by holiman** [comment]
Actually, looking at the source of web3, and the error: 
```
2020-06-10 11:27:34.643  WARN 20268 --- [pool-9-thread-2] org.web3j.protocol.core.filters.Filter   : The filter has not been found. Filter id: 66674882484826508490032443079398703497
2020-06-10 11:27:34.654 ERROR 20268 --- [pool-9-thread-2] org.web3j.protocol.core.filters.Filter   : Error sending request

org.web3j.protocol.core.filters.FilterException: Error sending request
at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:194) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.run(Filter.java:104) ~[core-5.0.0.jar:na]
at org.web3j.protocol.core.filters.Filter.reinstallFilter(Filter.java:155) ~[core-5.0.0.jar:na]
```

If the filter isn't found, they try to handle it here: https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L137 

The `reinstallfilter` tries to cancel it here: https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L154 

And the cancel tries to cancel the filter with the given id (the one that couldn't be found, earlier): https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L162 , and throws all kinds of errors if it fails to cancel the-filter-that-doesn't-exist. 

So it's definitely something that they try to handle, but fail to do. 

However, I've also tried to repro it locally. 

repro.sh
```bash
res=`curl -X POST -H "Content-type: application/json" --data '{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":73}' localhost:8545 | jq  ".result"`

payload="{\"jsonrpc\":\"2.0\",\"method\":\"eth_getFilterChanges\",\"params\":[$res],\"id\":73}"
echo payload is $payload

while :
do
  curl -X POST -H "Content-type: application/json" --data $payload localhost:8545
  sleep 10
done
```
Running geth with `build/bin/geth --dev --dev.period 5 --http --ws --ws.origins=http://127.0.0.1:8546`. I've modified the various timeout timits to be `5s`, but all results I'm getting are the expected ones. As long as the next request happens within that deadline, the deadline is bumped.

**Comment by kunalbarchha** [comment]
@holiman I tried going through source code of GETH, Web3J, talked with so many people, but the issue still prevails. Any workaround or fix for this ? I wonder how other apps like Binance, or Bitfinex handle this scenario.

**Comment by holiman** [comment]
Yes, so to be clear -- the workaround is to not throw all kinds of error when cancelling a filter that doesn't actually exist on the server. This line: https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L154 . One way would be to catch+ignore any exceptions thrown here, and just continue reinstalling the filter.

**Comment by holiman** [comment]
The root cause _may_ be due to some bug I haven't yet found in geth, but web3j should be able to handle this problem fine -- they have already implemented the handling. It's just that their handling of it is a bit wrong.

**Comment by kunalbarchha** [comment]
@holiman My code doesn't cancel any filter. I am just subscribing to transactionFlowable to get transaction. Using those txhashes, I use gettransaction and then compare to my DB to see if there is any app wallet transaction. Either web3 or geth is destroying the subscribed filter.

**Comment by holiman** [comment]
Hm, actuall, the line I pointed to isn't the culprit. I don't have a java workspace up, and can't really debug that now. But _something_ is funky with the lifecycle of filters in web3j, I think.

**Comment by kunalbarchha** [comment]
does this line seems to be a culprit in geth ? 

https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L77

**Comment by holiman** [comment]
There are a couple of paths which can delete the filter, that is one of them. It could happen that somehow the timer doesn't get reset properly (but my bash-repro above does reset the timer). The filter can also be deleted due to some internal error.
 
Basically, a filter can be deleted internally (e.g. due to timeout on low activity), and the caller should then try to reinstall a new filter, which web3j tries to do.

**Comment by kunalbarchha** [comment]
noted. Will wait for the update on fix, and same time will try to implement the workaround.

**Comment by kunalbarchha** [comment]
@holiman Any updates for the issue ?

**Comment by holiman** [comment]
No, and I'm unlikely to do any updates. I haven't found any error in the way geth works, and my attempt to repro the issue is not working. When I run it, things work as expected. 
In order to move the issue forward, a better reproduction case is needed (preferrably one that doesn't require kotlin/jvm to be installd). I suspect that the error is in Web3J, but I can't say for sure.

**Comment by holiman** [comment]
To clarify: 

> Basically, a filter can be deleted internally (e.g. due to timeout on low activity), and the caller should then try to reinstall a new filter, which web3j tries to do.

So basically, I think "Filter not found" is a red herring, and the real issue to investigate is why Web3J/geth fails during filter reinstallation.

**Comment by kunalbarchha** [comment]
@holiman I have taken a different approach now. Setup a cron to check for new block every thirty seconds, fetch all txhashes from there, and then get tx details from those hashes. Not an ideal solution, but it's at least reliable compared to socket.

**Comment by kunalbarchha** [comment]
The issue is resolved by using following logic:

Web3j web3j=Web3j.build((new HttpService("https://mainnet.infura.io/v3/<Infura Key>")));

@PostConstruct
public void getLatestBlock(){

    Thread thread = new Thread();
    BlockNumberEntity entity;
    Optional<BlockNumberEntity> optionalBlockNumberEntity=blockNumberRepository.findTopByIdGreaterThanEqual(1);

    if (optionalBlockNumberEntity.isPresent()) {
        thread.start();
        entity = optionalBlockNumberEntity.get();
        log.info("Last block number from DB >>>> " +entity.getLastBlockNumber());

        web3j.replayPastAndFutureTransactionsFlowable(DefaultBlockParameter.valueOf(entity.getLastBlockNumber().subtract(BigInteger.ONE)))
                .subscribe(tx -> {
                    entity.setLastBlockNumber(tx.getBlockNumber());
                    log.info("Block Number >>>> " + tx.getBlockNumber());
                    log.info("To Address >>>>> " + tx.getTo());
                    checkWalletAddress(tx.getHash(), tx.getTo());

                }, exception -> {
                    log.info(exception.getMessage());
                    if (exception != null) {
                        blockNumberRepository.deleteAll();
                        blockNumberRepository.save(entity);
                        thread.interrupt();
                        getLatestBlock();
                    }
                });
    }
    else{
        thread.start();
        entity=new BlockNumberEntity();
        web3j.transactionFlowable().subscribe(tx -> {
                    entity.setLastBlockNumber(tx.getBlockNumber());
                    log.info("Block Number >>>> " + tx.getBlockNumber());
                    log.info("To Address >>>>> " + tx.getTo());
                    checkWalletAddress(tx.getHash(), tx.getTo());
                }, exception -> {
                    log.info(exception.getMessage());
                    if (exception != null) {
                        blockNumberRepository.deleteAll();
                        blockNumberRepository.save(entity);
                        thread.interrupt();
                        getLatestBlock();
                    }
                });
    }

What this code does:

Initiate on deployment, and it checks DB if there is any last block sync available. If not, it will start syncing with TransactionFlowable. When exception occurs, it stores the last successfully block sync number in DB, closes the threads, and restarts the method. This time, the last blocknumber is available in DB, so it will use replayPastTransaction API and start syncing from there. On Exception, it will again update the lastBlocknumber in DB, close thread, and start the method.

Have been using it from last 72 hours, and achieved desired results.

**Comment by kunalbarchha** [comment]
Issue resolved with above code logic as workaround.

**Comment by KutkovetskyiVolodymyr** [comment]
Hello @kunalbarchha . I copied your code completely, and I still get an exception that is not caught:
It works at least 5 minutes, the maximum lasted half an hour.
web3j.version 5.0.0

[pool-2-thread-2] WARN org.web3j.protocol.core.filters.Filter - The filter has not been found. Filter id: 249646877427942250117165666998719809292
[pool-2-thread-2] ERROR org.web3j.protocol.core.filters.Filter - Error sending request
org.web3j.protocol.core.filters.FilterException: Error sending request
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:194)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:104)
	at org.web3j.protocol.core.filters.Filter.reinstallFilter(Filter.java:155)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:137)
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.kt:98)
	at okio.OutputStreamSink.write(Okio.kt:53)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:247)
	at okhttp3.internal.http2.Http2Writer.flush(Http2Writer.kt:120)
	at okhttp3.internal.http2.Http2Connection.flush(Http2Connection.kt:407)
	at okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.kt:626)
	at okio.ForwardingSink.close(ForwardingSink.kt:37)
	at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:245)
	at okio.RealBufferedSink.close(RealBufferedSink.kt:268)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:60)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
	at okhttp3.RealCall.execute(RealCall.kt:67)
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:160)
	at org.web3j.protocol.Service.send(Service.java:48)
	at org.web3j.protocol.core.Request.send(Request.java:87)
	at org.web3j.protocol.core.filters.BlockFilter.sendRequest(BlockFilter.java:34)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:59)
	... 9 more

**Comment by kunalbarchha** [comment]
Can you share your code snippet. The logic works fine for me since the day
I posted this solution.

**Comment by SantiagoEphere** [comment]
@kunalbarchha Hey, I am having this issue and trying to reproduce your solution. (Nice btw)
