### ISSUE TITLE
Websocket panic

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#21403]
geth version `Geth/v1.9.18-stable-f5382591/linux-amd64/go1.14.6`

Sometimes seen on the remix node: 

```
 Aug 01 15:58:49 remix-ropsten-001 geth INFO [08-01|13:58:49.098] Imported new chain segment blocks=1 txs=7 mgas=0.148 elapsed=7.008ms mgasps=21.142 number=8411849 hash="b9d108…ac6afc" dirty=0.00B
Aug 01 15:58:54 remix-ropsten-001 geth WARN [08-01|13:58:54.890] Full stats report failed err="tls: use of closed connection"
Aug 01 15:58:54 remix-ropsten-001 geth panic: concurrent write to websocket connection
Aug 01 15:58:54 remix-ropsten-001 geth goroutine 188 [running]:
Aug 01 15:58:54 remix-ropsten-001 geth github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc035940e10, 0x1, 0x0, 0x0, 0x0, 0xc022891000, 0x7fc9457d7400)
Aug 01 15:58:54 remix-ropsten-001 geth /go/pkg/mod/github.com/gorilla/websocket@v1.4.1-0.20190629185528-ae1634f6a989/conn.go:597 +0x5e9
Aug 01 15:58:54 remix-ropsten-001 geth github.com/gorilla/websocket.(*messageWriter).Close(0xc035940e10, 0x1045c60, 0xc041656720)
Aug 01 15:58:54 remix-ropsten-001 geth /go/pkg/mod/github.com/gorilla/websocket@v1.4.1-0.20190629185528-ae1634f6a989/conn.go:711 +0x62
Aug 01 15:58:54 remix-ropsten-001 geth github.com/gorilla/websocket.(*Conn).WriteJSON(0xc004618840, 0x1045c60, 0xc041656720, 0x4, 0x1225107)
Aug 01 15:58:54 remix-ropsten-001 geth /go/pkg/mod/github.com/gorilla/websocket@v1.4.1-0.20190629185528-ae1634f6a989/json.go:29 +0x12e
Aug 01 15:58:55 remix-ropsten-001 geth github.com/ethereum/go-ethereum/ethstats.(*Service).readLoop(0xc0002d84d0, 0xc004618840)
Aug 01 15:58:55 remix-ropsten-001 geth /go-ethereum/ethstats/ethstats.go:309 +0x1a1
Aug 01 15:58:55 remix-ropsten-001 geth created by github.com/ethereum/go-ethereum/ethstats.(*Service).loop
Aug 01 15:58:55 remix-ropsten-001 geth /go-ethereum/ethstats/ethstats.go:241 +0x865
```
I'm looking into it

**Comment by holiman** [comment]
Gorilla does not support multiple writers: https://github.com/gorilla/websocket/issues/596

I think the `readLoop` uses the same `conn`, and it conflicts with `loop` which also writes.

**Comment by holiman** [comment]
Seems introduced here: https://github.com/ethereum/go-ethereum/commit/0fef66c739c4a359ac438414d502d21ff1510fd2
