### ISSUE TITLE
Geth faild out of memory

### ISSUE THREAD

**Issue by manxiaqu** [ethereum/go-ethereum#21423]
Geth panic of "out of memory" when trying to start a geth node as rpc/mine node in a private poa network, which is the first time that I try to start geth after initing private genesis block. 

But, it does success running after trying several times to restart it(do nothing expect repeating execute cmd), don't know reason why.

cmd: `geth --datadir data --unlock 0xe7e549d77b7e8ece9194147395745d2f83ad6301 --password pw --allow-insecure-unlock --mine --rpc --rpcapi web3,eth,net`
#### System information

Geth version: `Geth
Version: 1.9.18-stable
Git Commit: f5382591874220287de253bfc08b10afd5244927
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.5
Operating System: linux
GOPATH=/home/ubuntu/gopath
GOROOT=/usr/local/go
`
OS & Version: `Linux, ubuntu 16.04`
Commit hash :`f5382591874220287de253bfc08b10afd5244927`

#### Expected behaviour

Geth start

#### Actual behaviour

panic of "out of memory"

#### Steps to reproduce the behaviour

geth --datadir data --unlock 0xe7e549d77b7e8ece9194147395745d2f83ad6301 --password pw --allow-insecure-unlock --mine --rpc --rpcapi web3,eth,net

#### Backtrace

````
INFO [08-07|10:53:45.668] Starting Geth on Ethereum mainnet... 
INFO [08-07|10:53:45.669] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [08-07|10:53:45.669] Sanitizing cache to Go's GC limits       provided=4096 updated=2534
INFO [08-07|10:53:45.670] Maximum peer count                       ETH=50 LES=0 total=50
WARN [08-07|10:53:45.670] The flag --rpc is deprecated and will be removed in the future, please use --http 
WARN [08-07|10:53:45.670] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api 
INFO [08-07|10:53:45.670] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-07|10:53:45.672] Set global gas cap                       cap=25000000
INFO [08-07|10:53:45.673] Starting peer-to-peer node               instance=Geth/v1.9.18-stable-f5382591/linux-amd64/go1.13.5
INFO [08-07|10:53:45.673] Allocated trie memory caches             clean=380.00MiB dirty=633.00MiB
INFO [08-07|10:53:45.673] Allocated cache and file handles         database=/home/ubuntu/xiongan-chain/data/geth/chaindata cache=1.24GiB handles=5120
INFO [08-07|10:53:45.701] Opened ancient database                  database=/home/ubuntu/xiongan-chain/data/geth/chaindata/ancient
INFO [08-07|10:53:45.702] Initialised chain configuration          config="{ChainID: 10315 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, YOLO v1: <nil>, Engine: clique}"
INFO [08-07|10:53:45.702] Initialising Ethereum protocol           versions="[65 64 63]" network=1 dbversion=7
INFO [08-07|10:53:45.702] Loaded most recent local header          number=0 hash="7be2e2…474a74" td=1 age=18m7s
INFO [08-07|10:53:45.702] Loaded most recent local full block      number=0 hash="7be2e2…474a74" td=1 age=18m7s
INFO [08-07|10:53:45.702] Loaded most recent local fast block      number=0 hash="7be2e2…474a74" td=1 age=18m7s
INFO [08-07|10:53:45.703] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-07|10:53:45.703] Regenerated local transaction journal    transactions=0 accounts=0
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x127e9e5, 0x16)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc02c000000, 0x40000000, 0x2166a58)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x214d380, 0x3f500000, 0x654a73, 0x203000)
	/usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x214d380, 0x1fa80, 0xffffffff)
	/usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x214d380, 0x1fa80, 0x2166a68, 0x0)
	/usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x214d380, 0x1fa80, 0x101, 0x7f0fb7ffee28)
	/usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x214d380, 0x1fa80, 0xc000010101, 0x7f0fc97c4da0)
	/usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x3f500000, 0x2160101, 0x7f0fc97c4da0)
	/usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x7f0fc51fdb90)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0004ba008 sp=0xc0004ba000 pc=0x474c20
runtime.mallocgc(0x3f500000, 0x106ece0, 0x421001, 0x20)
	/usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc0004ba0a8 sp=0xc0004ba008 pc=0x4238e5
runtime.makeslice(0x106ece0, 0x7ea0000, 0x7ea0000, 0x14b8360)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc0004ba0d8 sp=0xc0004ba0a8 pc=0x45d70c
github.com/steakknife/bloomfilter.newBits(...)
	/home/ubuntu/gopath/pkg/mod/github.com/steakknife/bloomfilter@v0.0.0-20180922174646-6819c0d2a570/new.go:102
github.com/steakknife/bloomfilter.NewWithKeys(0x1fa800000, 0xc000205a20, 0x3, 0x3, 0x0, 0xfbf058, 0x10eefc0)
	/home/ubuntu/gopath/pkg/mod/github.com/steakknife/bloomfilter@v0.0.0-20180922174646-6819c0d2a570/new.go:82 +0x24e fp=0xc0004ba168 sp=0xc0004ba0d8 pc=0x6c37ce
github.com/steakknife/bloomfilter.New(0x1fa800000, 0x3, 0x2163ed0, 0x0, 0x0)
	/home/ubuntu/gopath/pkg/mod/github.com/steakknife/bloomfilter@v0.0.0-20180922174646-6819c0d2a570/new.go:34 +0x39 fp=0xc0004ba1b0 sp=0xc0004ba168 pc=0x6c32e9
github.com/ethereum/go-ethereum/trie.NewSyncBloom(0x3f5, 0x7f0fc97c4da0, 0xc0001fa480, 0x7f0fc97c4da0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/trie/sync_bloom.go:71 +0x4d fp=0xc0004ba240 sp=0xc0004ba1b0 pc=0x6d8d8d
github.com/ethereum/go-ethereum/eth.NewProtocolManager(0xc0004c60a0, 0x0, 0xc000000001, 0x1, 0xc000243c50, 0x14ddbc0, 0xc00000c1e0, 0x14ec940, 0xc0000c4fc0, 0xc0004e7200, ...)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/eth/handler.go:154 +0x8f2 fp=0xc0004ba350 sp=0xc0004ba240 pc=0xcadb92
github.com/ethereum/go-ethereum/eth.New(0xc0004dc600, 0xc0004c8600, 0x12060a0, 0xc0004bb7f0, 0x423bd8)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/eth/backend.go:216 +0xbfa fp=0xc0004bb7a8 sp=0xc0004ba350 pc=0xca82da
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc0004dc600, 0xc000243e60, 0xc0004bb9a0, 0xc000177e80, 0x2)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1687 +0x3d fp=0xc0004bb800 sp=0xc0004bb7a8 pc=0xdcbfbd
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc0000d6c80, 0x0, 0x0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/node/node.go:210 +0x407 fp=0xc0004bba10 sp=0xc0004bb800 pc=0xc2e327
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc0000d6c80)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f fp=0xc0004bba58 sp=0xc0004bba10 pc=0xdbbaff
main.startNode(0xc00021e420, 0xc0000d6c80)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:366 +0x7e fp=0xc0004bbaf8 sp=0xc0004bba58 pc=0xf1d28e
main.geth(0xc00021e420, 0x0, 0x0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:354 +0xc8 fp=0xc0004bbba0 sp=0xc0004bbaf8 pc=0xf1d118
gopkg.in/urfave/cli%2ev1.HandleAction(0x108b800, 0x1343640, 0xc00021e420, 0xc0004cf5c0, 0x0)
	/home/ubuntu/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8 fp=0xc0004bbbc8 sp=0xc0004bbba0 pc=0xa2d0b8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002121a0, 0xc0000320c0, 0xc, 0xc, 0x0, 0x0)
	/home/ubuntu/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x58c fp=0xc0004bbf00 sp=0xc0004bbbc8 pc=0xa2b2bc
main.main()
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:272 +0x55 fp=0xc0004bbf60 sp=0xc0004bbf00 pc=0xf1c345
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0004bbfe0 sp=0xc0004bbf60 pc=0x44841e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004bbfe8 sp=0xc0004bbfe0 pc=0x476cf1

goroutine 9 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000868a0, 0xc0000867e0)
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0xdc

goroutine 10 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000868a0, 0xc000086840)
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x108

goroutine 11 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 12 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000174a50)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 13 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000174a50)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 14 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000174a50)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 15 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000174a50)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 35 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x213ab20)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/metrics/meter.go:289 +0x78
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/metrics/meter.go:70 +0x104

goroutine 36 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0002ee000)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:278 +0x276
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:262 +0x2ae

goroutine 27 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc000177bc0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:94 +0x50d
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x59

goroutine 39 [syscall]:
syscall.Syscall6(0xe8, 0x5, 0xc000229f9c, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x106ea60)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0x5, 0xc000229f9c, 0x1, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/home/ubuntu/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/unix/zsyscall_linux_amd64.go:76 +0x72
github.com/rjeczalik/notify.(*inotify).loop(0xc000116000, 0xc00009e0c0)
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:194 +0x77
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:134 +0x15b

goroutine 40 [chan receive]:
github.com/rjeczalik/notify.(*inotify).send(0xc000116000, 0xc00009e0c0)
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:254 +0xab
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:137 +0x1b4

goroutine 41 [chan receive]:
github.com/rjeczalik/notify.(*inotify).send(0xc000116000, 0xc00009e0c0)
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:254 +0xab
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/ubuntu/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:137 +0x1b4

goroutine 28 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).updater(0xc0002ee870)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:209 +0xcc
created by github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).Subscribe
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:196 +0x142

goroutine 29 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:105 +0x157
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).updater(0xc0004d7400)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:265 +0x3e
created by github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).Subscribe
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:254 +0x142

goroutine 30 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:105 +0x157
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).updater(0xc0004d7540)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:265 +0x3e
created by github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).Subscribe
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:254 +0x142

goroutine 31 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:105 +0x157
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).updater(0xc0004d7680)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:265 +0x3e
created by github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).Subscribe
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:254 +0x142

goroutine 32 [select]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc000211c70)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/manager.go:111 +0x1b8
created by github.com/ethereum/go-ethereum/accounts.NewManager
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/accounts/manager.go:79 +0x4be

goroutine 33 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000513340)
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/util/buffer_pool.go:206 +0x134
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/util/buffer_pool.go:237 +0x176

goroutine 82 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0002ee960)
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session_util.go:189 +0x5f9
created by github.com/syndtr/goleveldb/leveldb.newSession
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:93 +0x2b4

goroutine 83 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000166000)
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:91 +0xcd
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:148 +0x40c

goroutine 84 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000166000)
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:101 +0xf6
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x42e

goroutine 85 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000166000)
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:836 +0x25d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:155 +0x582

goroutine 86 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000166000)
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:773 +0x150
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/ubuntu/gopath/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:156 +0x5a4

goroutine 87 [select]:
github.com/ethereum/go-ethereum/ethdb/leveldb.(*Database).meter(0xc000216800, 0xb2d05e00)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:402 +0x1a28
created by github.com/ethereum/go-ethereum/ethdb/leveldb.New
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:132 +0xa25

goroutine 88 [select]:
github.com/ethereum/go-ethereum/core/rawdb.(*freezer).freeze(0xc000242900, 0x14e8100, 0xc000216800)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/rawdb/freezer.go:269 +0x1d52
created by github.com/ethereum/go-ethereum/core/rawdb.NewDatabaseWithFreezer
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/rawdb/database.go:178 +0x275

goroutine 89 [select]:
github.com/ethereum/go-ethereum/core.(*ChainIndexer).updateLoop(0xc000216900)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/chain_indexer.go:311 +0x11f
created by github.com/ethereum/go-ethereum/core.NewChainIndexer
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/chain_indexer.go:119 +0x24d

goroutine 90 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc0004e7200)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:2189 +0x10f
created by github.com/ethereum/go-ethereum/core.NewBlockChain
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:326 +0xc39

goroutine 91 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).maintainTxIndex(0xc0004e7200, 0x0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:2264 +0x213
created by github.com/ethereum/go-ethereum/core.NewBlockChain
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:329 +0xca7

goroutine 92 [select]:
github.com/ethereum/go-ethereum/core.(*ChainIndexer).eventLoop(0xc000216900, 0xc00010cd80, 0xc0001ad560, 0x14c7b00, 0xc00046c4a0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/chain_indexer.go:211 +0x2a2
created by github.com/ethereum/go-ethereum/core.(*ChainIndexer).Start
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/chain_indexer.go:152 +0xcf

goroutine 93 [select]:
github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop(0xc00000c1e0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:986 +0x23d
created by github.com/ethereum/go-ethereum/core.NewTxPool
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:289 +0x733

goroutine 94 [runnable]:
time.NewTicker(0x1dcd65000, 0x0)
	/usr/local/go/src/time/tick.go:28 +0x48
github.com/ethereum/go-ethereum/core.(*TxPool).loop(0xc00000c1e0)
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:320 +0x8e
created by github.com/ethereum/go-ethereum/core.NewTxPool
	/home/ubuntu/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:306 +0x7d2
````

**Comment by rjl493456442** [comment]
> geth --datadir data --unlock 0xe7e549d77b7e8ece9194147395745d2f83ad6301 --password pw --allow-insecure-unlock --mine --rpc --rpcapi web3,eth,net

It's the command for mainnet.

Besides, is your Geth starts without doing anything and then crash? Like your machine has 8GB memory, it shouldn't OOM that fast.

**Comment by manxiaqu** [comment]
Yes, the geth node does nothing and then crash. I will try to restart geth node as you say. So if the geth can't get enough memory place, it may crash?

**Comment by rjl493456442** [comment]
Usually, 8GB is not enough for mainnet. But I have no clue why during the setup the Geth will eat 8GB memory.

**Comment by karalabe** [comment]
The crash dump seems to indicate that the fast sync bloom filter is the one that blew up. That insta-allocates on startup a fair chunk of memory, though it should still only be the trie dirty cache size.

**Comment by karalabe** [comment]
@manxiaqu Could you check what `free` prints and share it? Curious how much RAM your system reports as free.

Also if you run with `--cache=1024` to deliberately reduce the defaults, does Geth start up? If yes, it should print a line `Allocated fast sync bloom                size=XXX MB`, could you please share that?

**Comment by manxiaqu** [comment]
Current mem info by `free`:
```
              total        used        free      shared  buff/cache   available
Mem:        7784560     6273220      141824      735736     1369516      349012
Swap:       7999484     7992288        7196
```
 
current log of geth without network id(success start):
```
INFO [08-07|15:42:18.745] Starting Geth on Ethereum mainnet... 
INFO [08-07|15:42:18.745] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [08-07|15:42:18.745] Sanitizing cache to Go's GC limits       provided=4096 updated=2534
INFO [08-07|15:42:18.747] Maximum peer count                       ETH=50 LES=0 total=50
WARN [08-07|15:42:18.747] The flag --rpc is deprecated and will be removed in the future, please use --http 
WARN [08-07|15:42:18.747] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api 
INFO [08-07|15:42:18.747] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-07|15:42:18.749] Set global gas cap                       cap=25000000
INFO [08-07|15:42:18.750] Starting peer-to-peer node               instance=Geth/v1.9.18-stable-f5382591/linux-amd64/go1.13.5
INFO [08-07|15:42:18.750] Allocated trie memory caches             clean=380.00MiB dirty=633.00MiB
INFO [08-07|15:42:18.751] Allocated cache and file handles         database=/home/ubuntu/xiongan-chain/data/geth/chaindata cache=1.24GiB handles=5120
INFO [08-07|15:42:18.788] Opened ancient database                  database=/home/ubuntu/xiongan-chain/data/geth/chaindata/ancient
INFO [08-07|15:42:18.788] Initialised chain configuration          config="{ChainID: 10315 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, YOLO v1: <nil>, Engine: clique}"
INFO [08-07|15:42:18.789] Initialising Ethereum protocol           versions="[65 64 63]" network=1 dbversion=7
INFO [08-07|15:42:18.789] Loaded most recent local header          number=106 hash="4d723e…dbd31d" td=213 age=28m6s
INFO [08-07|15:42:18.789] Loaded most recent local full block      number=106 hash="4d723e…dbd31d" td=213 age=28m6s
INFO [08-07|15:42:18.789] Loaded most recent local fast block      number=106 hash="4d723e…dbd31d" td=213 age=28m6s
INFO [08-07|15:42:18.801] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-07|15:42:18.801] Regenerated local transaction journal    transactions=0 accounts=0
WARN [08-07|15:42:18.801] Switch sync mode from fast sync to full sync 
INFO [08-07|15:42:19.128] New local node record                    seq=8 id=6397c9f468ebae87 ip=127.0.0.1 udp=30303 tcp=30303
INFO [08-07|15:42:19.129] Started P2P networking                   self=enode://8bff8b2ebefc65a66fd8610a2a82452cf558e86ff9c10a5503b5d99059e4c853ad80da8fa5a6812b02beee8a0444276ac7bf08134ead61bec31253f424b3bd73@127.0.0.1:30303
INFO [08-07|15:42:19.130] IPC endpoint opened                      url=/home/ubuntu/xiongan-chain/data/geth.ipc
INFO [08-07|15:42:19.130] HTTP endpoint opened                     url=http://127.0.0.1:8545/                   cors= vhosts=localhost
INFO [08-07|15:42:22.469] Unlocked account                         address=0xE7e549d77B7e8ecE9194147395745D2f83AD6301
INFO [08-07|15:42:22.470] Transaction pool price threshold updated price=1000000000
INFO [08-07|15:42:22.470] Transaction pool price threshold updated price=1000000000
INFO [08-07|15:42:22.470] Etherbase automatically configured       address=0xE7e549d77B7e8ecE9194147395745D2f83AD6301
```

I can't find the log info `Allocated fast sync bloom`.

**Comment by karalabe** [comment]
The issue seems to be that your machine is already fully saturated wrt RAM usage. It says you have 350MB free + 1.3GB used for buffers that can be reclaimed. Starting Geth with a 2.5GB cache allowance will blow through the available RAM instantly.

**Comment by manxiaqu** [comment]
Got it, Thank you!
