### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference - go-ethereum@v1.9.19/accounts/abi/bind/base.go:151

### ISSUE THREAD

**Issue by enqack** [ethereum/go-ethereum#21465]
Hi,

I'm using go-ethereum as a library for a project and have encountered an error I'm unable to resolve.  I'm attempting to interact with (read) Bancor's contract system.

I have followed instructions to generate a Go package from the [abi and bin files](https://github.com/bancorprotocol/contracts-solidity/tree/master/solidity/build) that are supplied by Bancor. Generating the package with `solc` produced abi and bin files was failing; i.e. `solc --abi Store.sol`. Preliminary interaction with the (Contract Registry) smart contracts is working as expected but when calling the `ConversionPath` function of the "network" contract the panic is raised. 

Thank you

#### System information

Geth version: 1.9.19
OS & Version: Popos (Ubuntu) 18.04 LTS
go version go1.15 linux/amd64

#### Expected behaviour

Return a conversion path used by the Bancor Network for rate data and token swapping.

#### Actual behaviour

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9ccf80]

#### Steps to reproduce the behaviour
````
$ abigen --bin BancorNetwork.bin --abi BancorNetwork.abi --pkg bancorNetwork -out BancorNetwork.go
$ abigen --bin ContractRegistry.bin --abi ContractRegistry.abi --pkg contractRegistry -out ContractRegistry.go
````

````
package main


import (
    "fmt"
    "log"
    "math/big"

    "github.com/ethereum/go-ethereum/common"
    "github.com/ethereum/go-ethereum/ethclient"

    "bancor/src/contracts/contractRegistry"
    "bancor/src/contracts/bancorNetwork"
)

func main() {
    var contractRegistryAdresss common.Address
    var networkAddress common.Address
    var inputAmount, _ = new(big.Int).SetString("154000000000", 10)

    client, err := ethclient.Dial("https://mainnet.infura.io/v3/<apikey>")
    if err != nil {
        log.Fatal(err)
    }

    inputToken := common.HexToAddress("0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
    outputToken := common.HexToAddress("0x6b175474e89094c44da98b954eedeac495271d0f")

    contractRegistryAdresss = common.HexToAddress("0x52Ae12ABe5D8BD778BD5397F99cA900624CfADD4")
    contractRegistryContract, _ := contractRegistry.NewContractRegistry(contractRegistryAdresss, client)

    value := [32]byte{}; copy(value[:], []byte("BancorNetwork"))
    networkAddress, _ = contractRegistryContract.AddressOf(nil, value)
    fmt.Printf("BancorNetwork contract address: %s\n", networkAddress.Hex())

    networkContract, _ := bancorNetwork.NewBancorNetwork(networkAddress, nil)

    conversionPath, _ := networkContract.ConversionPath(nil, inputToken, outputToken)

    bancorReturn, _ := networkContract.RateByPath(nil, conversionPath, inputAmount)
    fmt.Println(bancorReturn)
}
````
#### Backtrace

````
BancorNetwork contract address: 0x2F9EC37d6CcFFf1caB21733BdaDEdE11c823cCB0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9c0b80]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call(0xc0001a2780, 0xc00031f8f8, 0xa28740, 0xc0002e6060, 0xb3e98e, 0xe, 0xc00031fe20, 0x2, 0x2, 0x0, ...)
	/home/sysop/Projects/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.19/accounts/abi/bind/base.go:151 +0x520
bancor/src/contracts/bancorNetwork.(*BancorNetworkCaller).ConversionPath(0xc0002e6040, 0x0, 0xeeeeeeeeeeeeeeee, 0xeeeeeeeeeeeeeeee, 0x7454176beeeeeeee, 0x958ba94dc49490e8, 0xf1d2795c4eaed4e, 0x0, 0x0, 0x0, ...)
	/home/sysop/Projects/go/src/github.com/enqack/bancor/src/contracts/bancorNetwork/BancorNetwork.go:199 +0x16d
main.main()
	/home/sysop/Projects/go/src/github.com/enqack/bancor/src/main.go:38 +0x3ba
exit status 2

````

**Comment by karalabe** [comment]
Please add proper error checking and see if anything fails. Something in your flow probably broke and you kept going, ignoring errors.

**Comment by enqack** [comment]
No errors; just an example.

**Comment by enqack** [comment]
The following line needed the client:
````
networkContract, _ := bancorNetwork.NewBancorNetwork(networkAddress, nil)
````
Correction:
````
networkContract, _ := bancorNetwork.NewBancorNetwork(networkAddress, client)
````
