### ISSUE TITLE
Nodo ha dejado de funcionar - You've encountered a sought after, hard to reproduce bug

### ISSUE THREAD

**Issue by rrojasfp** [ethereum/go-ethereum#21513]
En los logs arroja lo siguiente:

WARN [09-02|15:58:40.822] Full stats report failed                 err="write tcp 172.17.0.2:35394->185.180.8.152:80: use of closed network connection"
INFO [09-02|15:58:51.103] Imported new chain segment               blocks=115 txs=17   mgas=2.880   elapsed=8.686s    mgasps=0.332  number=47769384 hash=2dd42b…486aa0 cache=642.72kB
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues
index allocation went beyond available resultCache space
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:512
goroutine 12355 [running]:
runtime/debug.Stack(0x5d, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ethereum/go-ethereum/common.Report(0xc427b4b918, 0x1, 0x1)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x1f2
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc422e71000, 0xc45b8bd2c0, 0x80, 0xc423cc36b0, 0xc426f64770, 0xc423cc36e0, 0xc423cc3710, 0x1180188, 0xc421ac2aa8, 0xc427b4b998, ...)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:512 +0x74b
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xc422e71000, 0xc45b8bd2c0, 0x80, 0x0, 0xc45b8bd200, 0x0, 0x0)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:464 +0xf1
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies-fm(0xc45b8bd2c0, 0x80, 0x3, 0x3, 0x4, 0x4)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:948 +0x3e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc420070ea0, 0x1a60b40, 0xc420270790, 0xc431e726c0, 0xc421318f40, 0xc43217f3b0, 0xc427b4beb0, 0xc427b4bf00, 0xc427b4bef0, 0xc427b4bee0, ...)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1126 +0x9ff
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xc420070ea0, 0x2d847d5, 0xc426acbf98, 0xc4222aeae0)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:947 +0x33e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0x8, 0x1182740)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:472 +0x37
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc420070ea0, 0xc439a024e0, 0xc44a1ccde0)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xb6
#### BUG! PLEASE REPORT ####

**Comment by holiman** [comment]
redirecting this, cc @jpmsam 
pleas file to https://github.com/jpmorganchase/quorum/issues
