### ISSUE TITLE
Change in eth_getTransactionCount  RPC response on develop branch

### ISSUE THREAD

**Issue by area** [ethereum/go-ethereum#2153]
With exactly the same (private) chain running locally, I get different responses from different versions of `geth`. Running `geth` v1.3.3:

```
 ~> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xaeafbd423c1620453bd3284e09cdf543e136dd0e","latest"],"id":1}' http://127.0.0.1:8545
{"id":1,"jsonrpc":"2.0","result":"0x26"}
 ~> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xaeafbd423c1620453bd3284e09cdf543e136dd0e","pending"],"id":1}' http://127.0.0.1:8545
{"id":1,"jsonrpc":"2.0","result":"0x26"}
```

Running `geth` from the develop branch (63e76482ac0):

```
 ~> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xaeafbd423c1620453bd3284e09cdf543e136dd0e","latest"],"id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","id":1,"result":"0x26"}
 ~> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0xaeafbd423c1620453bd3284e09cdf543e136dd0e","pending"],"id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```

**Comment by obscuren** [comment]
Thanks for reporting this issue. I've actually noticed this myself while we were working over the weekend at the Gophergala hackington.

It appears that the pending state is that of an empty state while it should be that of the current, pending, accumulated state. I'll look in to this.

**Comment by karalabe** [comment]
Running the RPC tests https://github.com/ethereum/rpc-tests

```
  1) db_getHex GO should return the previously stored value:
     Uncaught AssertionError: The method db_getHex does not exist/is not available: expected { Object (jsonrpc, id, ...) } to have a property 'result'
      at Function.assert.property (node_modules/chai/lib/chai/interface/assert.js:876:37)
      at test/db_getHex.js:19:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  2) db_getHex GO should return an error when no parameter is passed:
     Uncaught AssertionError: expected -32601 to equal -32602
      at test/db_getHex.js:41:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  3) db_getString GO should return the previously stored value:
     Uncaught AssertionError: The method db_getString does not exist/is not available: expected { Object (jsonrpc, id, ...) } to have a property 'result'
      at Function.assert.property (node_modules/chai/lib/chai/interface/assert.js:876:37)
      at test/db_getString.js:19:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  4) db_getString GO should return an error when no parameter is passed:
     Uncaught AssertionError: expected -32601 to equal -32602
      at test/db_getString.js:41:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  5) db_putHex GO should return TRUE:
     Uncaught AssertionError: The method db_putHex does not exist/is not available: expected { Object (jsonrpc, id, ...) } to have a property 'result'
      at Function.assert.property (node_modules/chai/lib/chai/interface/assert.js:876:37)
      at test/db_putHex.js:21:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  6) db_putHex GO should return an error when no parameter is passed:
     Uncaught AssertionError: expected -32601 to equal -32602
      at test/db_putHex.js:41:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  7) db_putString GO should return TRUE:
     Uncaught AssertionError: The method db_putString does not exist/is not available: expected { Object (jsonrpc, id, ...) } to have a property 'result'
      at Function.assert.property (node_modules/chai/lib/chai/interface/assert.js:876:37)
      at test/db_putString.js:21:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  8) db_putString GO should return an error when no parameter is passed:
     Uncaught AssertionError: expected -32601 to equal -32602
      at test/db_putString.js:41:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  9) eth_getBlockByNumber GO should return the pending block when using "pending":
     Uncaught AssertionError: block hash should be null: expected '0x1c0f3d86a440986fb7a6b3f2012dfaa324a51a1033770fc55542e85cbe08a543' to equal null
      at Function.assert.isNull (node_modules/chai/lib/chai/interface/assert.js:388:32)
      at test/eth_getBlockBy.js:25:20
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  10) eth_getCompilers GO should return an array with compilers:
     Uncaught AssertionError: exec: "solc": executable file not found in $PATH: expected { Object (jsonrpc, id, ...) } to have a property 'result'
      at Function.assert.property (node_modules/chai/lib/chai/interface/assert.js:876:37)
      at test/eth_getCompilers.js:19:16
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16

  11) eth_getFilterLogs GO should return a list of logs, when filtering with defining an address and using toBlock "pending":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  12) eth_getTransactionByBlockNumberAndIndex GO should return transactions for the pending block when using "pending" and sending transactions before:
     Uncaught AssertionError: is object: expected null to be an object
      at Function.assert.isObject (node_modules/chai/lib/chai/interface/assert.js:528:35)
      at test/eth_getTransactionBy.js:24:20
      at xhr.onreadystatechange (lib/helpers.js:40:29)
      at dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at _stream_readable.js:920:16
```

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/blob/develop/rpc/types.go#L309

**Comment by karalabe** [comment]
Ok, this is strange because we do get back the block and serialize it to a flat map, but then the response is lost inside the RPC implementation somehow and never sent out.

**Comment by karalabe** [comment]
This is a tricky construct that sort of doesn't do it's job: https://github.com/ethereum/go-ethereum/blob/develop/rpc/types.go#L176

An interface{} is only nil, if it was passed nil. A nil pointer however is already "something" so it's not nil any more. http://play.golang.org/p/1SomgEimrM

The check doesn't hurt per se, but we need to handle nil big.Ints within the big.Int branch. And no, this does not fix the issue yet.

**Comment by karalabe** [comment]
Proposed fix to this issue: https://github.com/ethereum/go-ethereum/pull/2154

**Comment by karalabe** [comment]
This should be fixed in develop for a while now. Closing. Please reopen if you still see any issues.

**Comment by Levino** [comment]
I am getting timeouts when calling "eth_getTransactionCount" with geth@1.5.2. Query is sent to RPC interface and times out with 504.
