### ISSUE TITLE
Invalid block header RLP    and  rlp: input string too short for common.Hash, decoding into (types.Header).Root

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#21558]
hi, when I run the geth as  a private chain node it shows error below:

```
C:\tools\src\github.com\ethereum\go-ethereum\geth.exe init C:\tools\src\github.com\ethereum\go-ethereum\genesis.json #gosetup
INFO [09-14|14:23:29.550] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-14|14:23:30.116] Set global gas cap                       cap=25000000
INFO [09-14|14:23:30.171] Allocated cache and file handles         database=C:\Users\root\AppData\Roaming\Ethereum\geth\chainda
ta cache=16.00MiB handles=16
ERROR[09-14|14:23:30.330] Invalid block header RLP                 hash="f7973e…d25ea5" err="rlp: input string too short for c
ommon.Hash, decoding into (types.Header).Root"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x54 pc=0x7b2e77]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.SetupGenesisBlock(0x12af540, 0xc00000a000, 0xc0000d0160, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00000
a000, 0x0)
        C:/tools/src/github.com/ethereum/go-ethereum/core/genesis.go:178 +0x397
main.initGenesis(0xc000202420, 0x0, 0x0)
        C:/tools/src/github.com/ethereum/go-ethereum/cmd/geth/chaincmd.go:251 +0x809
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc000202420, 0x0, 0xc000202420)
        C:/tools/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1899 +0xc7
gopkg.in/urfave/cli%2ev1.HandleAction(0xeafaa0, 0xc00004ed70, 0xc000202420, 0xc00013ce00, 0x0)
        C:/tools/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x89
gopkg.in/urfave/cli%2ev1.Command.Run(0x1078a71, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10b026e, 0x2c, 0x0, ...)
        C:/tools/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x9fb
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000641a0, 0xc000098000, 0x3, 0x4, 0x0, 0x0)
        C:/tools/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x768
main.main()
        C:/tools/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:273 +0x6a

Process finished with exit code 2
```

the genesis.json is :
```
{
  "config": {
    "chainId": 10,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0
  },
  "alloc": {},
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x20000",
  "extraData": "",
  "gasLimit": "0x47e7c4",
  "nonce": "0x0000000000000042",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

C:\tools\src\github.com\ethereum\go-ethereum>geth.exe version
Geth
Version: 1.9.22-unstable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.2
Operating System: windows
GOPATH=C:\tools
GOROOT=C:\Go\

So how to solve it? thank you very much !

**Comment by MariusVanDerWijden** [comment]
I can not reproduce your error...
```
geth init genesis.json --datadir .
INFO [09-14|09:07:05.702] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-14|09:07:05.702] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-14|09:07:05.710] Set global gas cap                       cap=25000000
INFO [09-14|09:07:05.710] Allocated cache and file handles         database=/home/matematik/ethereum/genesis/geth/chaindata cache=16.00MiB handles=16
INFO [09-14|09:07:05.723] Writing custom genesis block 
INFO [09-14|09:07:05.723] Persisted trie from memory database      nodes=0 size=0.00B time="8.446µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-14|09:07:05.723] Successfully wrote genesis state         database=chaindata hash="5ee339…cb06f5"
INFO [09-14|09:07:05.723] Allocated cache and file handles         database=/home/matematik/ethereum/genesis/geth/lightchaindata cache=16.00MiB handles=16
INFO [09-14|09:07:05.732] Writing custom genesis block 
INFO [09-14|09:07:05.732] Persisted trie from memory database      nodes=0 size=0.00B time="2.665µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-14|09:07:05.732] Successfully wrote genesis state         database=lightchaindata hash="5ee339…cb06f5"
```

**Comment by jiebanghan** [comment]
thank you @MariusVanDerWijden . I run OK when add parameter  --datadir .  
but  in the official documents is [here](https://github.com/ethereum/go-ethereum) :
```
With the genesis state defined in the above JSON file, you'll need to initialize every geth node with it prior to starting it up to ensure all blockchain parameters are correctly set:

$ geth init path/to/genesis.json
```

**Comment by MariusVanDerWijden** [comment]
So `--datadir .` uses the current directory as the data directory to save all blockchain state in it. 
If you don't specify it, geth will use the default .ethereum directory in your user directory to save the state.
If there are already files there (because you synced ETH before for example) the `geth init` command fails.
What I would suggest for you is to create a new directory where you want to save all the data for your private chain and specify it to the datadir flag (e.g. `geth init ./genesis.json --datadir C:/Users/asdf/privChain`)

**Comment by jiebanghan** [comment]
OK, thank you @MariusVanDerWijden . I will follow your suggestion.
