### ISSUE TITLE
SIGSEGV crash

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [ethereum/go-ethereum#21576]
#### System information

Geth version: 
```
Geth
Version: 1.9.21-stable
Git Commit: 0287d54847d3297f3ced62cd83a4c95ccbe0045b
Git Commit Date: 20200909
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.1
Operating System: linux
GOPATH=
GOROOT=go
```
OS & Version: Linux Ubuntu 18.04.5 bionic
Commit hash : 0287d54847d3297f3ced62cd83a4c95ccbe0045b

#### Expected behaviour

Should not crash

#### Actual behaviour

SIGSEGV

#### Steps to reproduce the behaviour

???

#### Backtrace

````
.../geth --syncmode light --nat extip:x.x.x.x --verbosity 5 --maxpeers 100
[...]
DEBUG[09-17|01:57:34.917] Inserted new header                      number=10813628 hash="3f1399…88e595"
DEBUG[09-17|01:57:34.917] Inserted new header                      number=10813629 hash="7e5e29…3648ee"
DEBUG[09-17|01:57:34.917] Inserted new header                      number=10813630 hash="0cff50…31fd62"
DEBUG[09-17|01:57:34.917] Inserted new header                      number=10813631 hash="b421fd…403c54"
INFO [09-17|01:57:34.917] Imported new block headers               count=192 elapsed=2.978s number=10813631 hash="b421fd…403c54" age=1w2d8h
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xda5a78]

goroutine 98 [running]:
github.com/ethereum/go-ethereum/light.(*TxPool).reorgOnNewHead(0xc000128f20, 0x1520660, 0xc004f9ca80, 0xc003506900, 0xc004f9ca80, 0xc004869500, 0x4664ac)
	github.com/ethereum/go-ethereum/light/txpool.go:229 +0x238
github.com/ethereum/go-ethereum/light.(*TxPool).setNewHead(0xc000128f20, 0xc003506900)
	github.com/ethereum/go-ethereum/light/txpool.go:310 +0xf7
github.com/ethereum/go-ethereum/light.(*TxPool).eventLoop(0xc000128f20)
	github.com/ethereum/go-ethereum/light/txpool.go:291 +0x56
created by github.com/ethereum/go-ethereum/light.NewTxPool
	github.com/ethereum/go-ethereum/light/txpool.go:108 +0x3da
````

**Comment by MariusVanDerWijden** [comment]
@nonlinear-chaos-order-etc-etal This is a known issue in v1.9.21. We fixed it here: https://github.com/ethereum/go-ethereum/pull/21537 You can either download the unstable master which has this fix or wait roughly a week until we publish a new release. Thank you for reporting!
