### ISSUE TITLE
Panic on invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yelsukov** [ethereum/go-ethereum#21583]
#### System information

Geth version: `v1.9.21`
OS & Version: `Ubuntu 16`

#### Expected behaviour
Keep calm and do not panic...

#### Actual behaviour
 panic: runtime error: invalid memory address or nil pointer dereference

#### Steps to reproduce the behaviour
Run the geth v.1.9.21 client in light mode and give it a time to find peers.

My docker-compose.yml:
```
version: '2'

services:
  geth:
    image: ethereum/client-go:v1.9.21
    restart: on-failure
    container_name: "geth_client"
    command: '--syncmode "light" --datadir "/var/data" --ws --wsaddr "0.0.0.0" --wsorigins "*" --rpc --rpcaddr "0.0.0.0" --rpcvhosts "*" --cache 256 --nousb --verbosity 3 --maxpeers=20'
    volumes:
      - /var/data/ethereum:/var/data
    logging:
      driver: syslog
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp

```

#### Backtrace

````
Sep 19 12:57:43: INFO [09-19|05:57:43.138] Looking for peers                        peercount=0 tried=12 static=0
Sep 19 12:57:53: INFO [09-19|05:57:53.141] Looking for peers                        peercount=0 tried=6  static=0
Sep 19 12:58:03: INFO [09-19|05:58:03.947] Looking for peers                        peercount=1 tried=6  static=0
Sep 19 12:58:14: INFO [09-19|05:58:14.138] Looking for peers                        peercount=1 tried=15 static=0
Sep 19 12:58:24: INFO [09-19|05:58:24.143] Looking for peers                        peercount=1 tried=13 static=0
Sep 19 12:58:34: INFO [09-19|05:58:34.145] Looking for peers                        peercount=1 tried=15 static=0
Sep 19 12:58:44: INFO [09-19|05:58:44.147] Looking for peers                        peercount=1 tried=13 static=0
Sep 19 12:58:54: INFO [09-19|05:58:54.149] Looking for peers                        peercount=1 tried=6  static=0
Sep 19 12:59:02: INFO [09-19|05:59:02.946] Imported new block headers               count=192 elapsed=233.407ms number=10888958 hash="31a202…e7bae2" age=7h9m38s
Sep 19 12:59:02: panic: runtime error: invalid memory address or nil pointer dereference
Sep 19 12:59:02: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xd49f50]
Sep 19 12:59:02: 
Sep 19 12:59:02: goroutine 78 [running]:
Sep 19 12:59:02: github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).lightFilterNewHead(0xc000145970, 0xc002e7c6c0, 0xc00d26db18)
Sep 19 12:59:02: 	github.com/ethereum/go-ethereum/eth/filters/filter_system.go:383 +0x250
Sep 19 12:59:02: github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).handleChainEvent(0xc000145970, 0xc00d26dcf8, 0xc001084510, 0xaa4e70eeb06ee4e, 0x71f8a741572392f0, 0xfefa25aa7a4c1c16, 0x6a0edf1a93b04bd7, 0x0, 0x0, 0x0)
Sep 19 12:59:02: 	github.com/ethereum/go-ethereum/eth/filters/filter_system.go:359 +0x1de
Sep 19 12:59:02: github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc000145970)
Sep 19 12:59:02: 	github.com/ethereum/go-ethereum/eth/filters/filter_system.go:469 +0x9ba
Sep 19 12:59:02: created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
Sep 19 12:59:02: 	github.com/ethereum/go-ethereum/eth/filters/filter_system.go:138 +0x345
````

**Comment by rjl493456442** [comment]
Hi @yelsukov Can you test with the latest master? (We may also prepare a new release very soon). 
We had a [fix](https://github.com/ethereum/go-ethereum/commit/367f12f73495b30c17c7d358cf71575f34f79757) for light client crashes I think it can also fix this issue.

**Comment by yelsukov** [comment]
Hi @rjl493456442 

Done. I will watch for a few days and report the results.

Thank you.

**Comment by yelsukov** [comment]
Hi @rjl493456442 

The issue seems to be fixed. Light client works stably for more than 4 days without incidents

Thank you.

**Comment by rjl493456442** [comment]
@yelsukov Cool! I'll close this issue right now. Feel free to reopen if panic happens again.
