### ISSUE TITLE
go routine leaks when deploying a contract

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#21818]
`goleak.VerifyTestMain` tracks goroutines and shows few leaks. this is probably not easy to solve, but it is worth looking into.

```
// Copyright (c) The Tellor Authors.
// Licensed under the MIT License.

package main

import (
	"context"
	"fmt"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/accounts/abi/bind/backends"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/crypto"
	"go.uber.org/goleak"
)

// TestMain check for goroutine leaks.
// It ensures that at the end of the tests there are no remaining go routines.
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}

func TestProfitCalc(t *testing.T) {
	// Generate a new random account and a funded simulator
	key, err := crypto.GenerateKey()
	if err != nil {
		t.Fatal(err)
	}

	auth := bind.NewKeyedTransactor(key)

	sim := backends.NewSimulatedBackend(core.GenesisAlloc{auth.From: {Balance: big.NewInt(10000000000)}}, 100000000000000000)

	// Deploy a token contract on the simulated blockchain
	_, tx, tellor, err := DeployMyToken(auth, sim, new(big.Int), "Simulated blockchain tokens", 0, "SBT")

	if err != nil {
		t.Fatal(err)
	}
	// Print the current (non existent) and pending name of the contract
	name, _ := tellor.Name(nil)
	fmt.Println("Pre-mining name:", name)

	name, _ = tellor.Name(&bind.CallOpts{Pending: true})
	fmt.Println("Pre-mining pending name:", name)

	// Commit all pending transactions in the simulator and print the names again
	sim.Commit()

	name, _ = tellor.Name(nil)
	fmt.Println("Post-mining name:", name)

	name, _ = tellor.Name(&bind.CallOpts{Pending: true})
	fmt.Println("Post-mining pending name:", name)

	rcpt, err := bind.WaitMined(context.Background(), sim, tx)
	if err != nil {
		t.Fatal(err)
	}
	if rcpt.Status != 1 {
		t.Fatal("deploy transaction failed")
	}
}

```

This is the code from Blockchain simulator in https://geth.ethereum.org/docs/dapp/native-bindings

It downloads the latest available versions of all dependencies.

and here is the output

<details>
<summary>Details</summary>

```
=== RUN   TestProfitCalc
Pre-mining name: 
Pre-mining pending name: Simulated blockchain tokens
Post-mining name: Simulated blockchain tokens
Post-mining pending name: Simulated blockchain tokens
--- PASS: TestProfitCalc (0.01s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 8 in state chan receive, with github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch on top of the stack:
goroutine 8 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc00007ed20, 0xc00007ec60)
	/home/krasi/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/home/krasi/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0xe5

 Goroutine 9 in state chan receive, with github.com/rjeczalik/notify.(*nonrecursiveTree).internal on top of the stack:
goroutine 9 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc00007ed20, 0xc00007ecc0)
	/home/krasi/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/home/krasi/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x111

 Goroutine 10 in state chan receive, with github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick on top of the stack:
goroutine 10 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x1242f00)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/metrics/meter.go:290 +0x7d
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/metrics/meter.go:71 +0x105

 Goroutine 11 in state select, with github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop on top of the stack:
goroutine 11 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0002562d0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/consensus/ethash/sealer.go:278 +0x25c
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/consensus/ethash/sealer.go:262 +0x2b2

 Goroutine 12 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 12 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 13 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 13 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 14 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 14 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 15 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 15 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 16 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 16 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 18 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 18 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 19 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 19 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 20 in state chan receive, with github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache on top of the stack:
goroutine 20 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00034cfe0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/tx_cacher.go:55 +0x9f

 Goroutine 36 in state select, with github.com/ethereum/go-ethereum/core.(*BlockChain).update on top of the stack:
goroutine 36 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc00009d900)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/blockchain.go:2213 +0x115
created by github.com/ethereum/go-ethereum/core.NewBlockChain
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/blockchain.go:345 +0xdab

 Goroutine 66 in state chan receive, with github.com/ethereum/go-ethereum/core/state/snapshot.(*diskLayer).generate on top of the stack:
goroutine 66 [chan receive]:
github.com/ethereum/go-ethereum/core/state/snapshot.(*diskLayer).generate(0xc000120000, 0xc000122000)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/state/snapshot/generate.go:277 +0x1b66
created by github.com/ethereum/go-ethereum/core/state/snapshot.generateSnapshot
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/core/state/snapshot/generate.go:114 +0x23f

 Goroutine 67 in state chan receive, with github.com/ethereum/go-ethereum/accounts/abi/bind/backends.nullSubscription.func1 on top of the stack:
goroutine 67 [chan receive]:
github.com/ethereum/go-ethereum/accounts/abi/bind/backends.nullSubscription.func1(0xc00011e0c0, 0x0, 0x0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/accounts/abi/bind/backends/simulated.go:790 +0x34
github.com/ethereum/go-ethereum/event.NewSubscription.func1(0xc000138060, 0xcb20b8)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/event/subscription.go:53 +0x66
created by github.com/ethereum/go-ethereum/event.NewSubscription
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/event/subscription.go:51 +0xc5

 Goroutine 68 in state chan receive, with github.com/ethereum/go-ethereum/accounts/abi/bind/backends.nullSubscription.func1 on top of the stack:
goroutine 68 [chan receive]:
github.com/ethereum/go-ethereum/accounts/abi/bind/backends.nullSubscription.func1(0xc00011e360, 0x0, 0x0)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/accounts/abi/bind/backends/simulated.go:790 +0x34
github.com/ethereum/go-ethereum/event.NewSubscription.func1(0xc0001380e0, 0xcb20b8)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/event/subscription.go:53 +0x66
created by github.com/ethereum/go-ethereum/event.NewSubscription
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/event/subscription.go:51 +0xc5

 Goroutine 69 in state select, with github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop on top of the stack:
goroutine 69 [select]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc0003e0000)
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/eth/filters/filter_system.go:459 +0x4cc
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
	/home/krasi/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/eth/filters/filter_system.go:138 +0x345
]
FAIL	github.com/tellor-io/TellorDocs	0.471s
FAIL

```

</details>

**Comment by holiman** [comment]
core/tx_cacher.go: 
```golang
// senderCacher is a concurrent transaction sender recoverer and cacher.
var senderCacher = newTxSenderCacher(runtime.NumCPU())
```
That one is used by both `blockchain` during block insertion, and the `txpool`. I guess it could be initialized using `sync.Once` when initializing either one of them, instead of always doing it.

**Comment by holiman** [comment]
The `tx_cacher` is actually fine, it's a global variable `var senderCacher = newTxSenderCacher(runtime.NumCPU())` -- that's why there's eight of them.

**Comment by holiman** [comment]
Adding shutdown hooks for libraries will just complicate things

**Comment by krasi-georgiev** [comment]
IIUC you prefer to leave the leaking go routines over adding shutdown logic?

**Comment by holiman** [comment]
Yes, the 'leaks' are just a few routines that will live until the program terminates. It costs a few kb in memory, but goroutines aren't full threads so it doesn't really matter whether there are a few extra ones in existence, basically.

**Comment by holiman** [comment]
I originally thought that the `tx_fetcher` goutines would be piled up when e.g. instantiating blockchain. But that wasn't the case

**Comment by krasi-georgiev** [comment]
but at shutdown, all of these should also be removed, no?

**Comment by holiman** [comment]
So, let's  use this as an example: https://github.com/ethereum/go-ethereum/blob/9940d93a43bab1f060e8fbfadff510c3298f2726/core/tx_cacher.go#L26

```
// senderCacher is a concurrent transaction sender recoverer and cacher.
var senderCacher = newTxSenderCacher(runtime.NumCPU())
```

It lives in the global context, and this spawns numcpu (in your case `8`) goroutines which sit idle. We don't worry about them, they do their work in the background, and when the go runtime exits, they simply die. 
For `geth`, this is totally what we want. 

Now, if someone wants to use go-ethereum  as a library, it's fully possible that these 8 goroutines are unnecessary, and, as you observed, stay alive even after whatever call you wanted to make inside the go-ethereum-codebase is over and done with. They'll die eventually when your program exits, but from a niceness-perspective, it's a couple of extra idle goroutines that _strictly speaking_ wouldn't be needed. 

If we were to fix that, we'd have to remove them from the global scope, and instead tie them to e.g. an instance of a `blockchain`. We would then also extend this little listenere (https://github.com/ethereum/go-ethereum/blob/9940d93a43bab1f060e8fbfadff510c3298f2726/core/tx_cacher.go#L63 ) to also check some shutdown-channel, so that they'd be torn down when the blockchain is torn down. 

It's basically a lot of hassle that doesn't improve `geth`, but make go-ethereum ever so slightly more well-behaving when used as a library. 

It's a very well-behaving "leak" -- usually a "leak" means that some resource is being drip-drained, and more resources lost as time goes by. This is just a constant little penalty of using go-ethereum as a library ;-)

**Comment by krasi-georgiev** [comment]
Yep, I see your point, what about adding context and just allow a global cancelation?
Wouldn't this solve the problem? 
Then library users can provide the context and cancel according to the execution workflow.
