### ISSUE TITLE
panic: invalid IP (length 0)

### ISSUE THREAD

**Issue by KevinVitale** [ethereum/go-ethereum#21849]
I updated my client this morning, and saw a panic come across the logs.

#### System information

Geth version: `v1.9.24-stable`
OS & Version: `linux-amd64/go1.15.5`
Commit hash : `cc05b050`

#### Backtrace

````
WARN [11-13|15:02:50.753] Synchronisation failed, dropping peer    peer=<REDACTED> err=timeout
panic: invalid IP (length 0)

goroutine 245853 [running]:
github.com/ethereum/go-ethereum/p2p/enode.nodeItemKey(0xe1e746b3728db12b, 0xf99e36e9d25005d, 0x7e0862ed8c5c18da, 0x3054f4210cdb23b2, 0x0, 0x0, 0x0, 0x132dc0a, 0x8, 0x30, ...)
	github.com/ethereum/go-ethereum/p2p/enode/nodedb.go:152 +0x49d
github.com/ethereum/go-ethereum/p2p/enode.(*DB).LastPingReceived(0xc01a7ca180, 0xe1e746b3728db12b, 0xf99e36e9d25005d, 0x7e0862ed8c5c18da, 0x3054f4210cdb23b2, 0x0, 0x0, 0x0, 0x1237f20, 0x1534101, ...)
	github.com/ethereum/go-ethereum/p2p/enode/nodedb.go:362 +0x78
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv4).ensureBond(0xc015fb8000, 0xe1e746b3728db12b, 0xf99e36e9d25005d, 0x7e0862ed8c5c18da, 0x3054f4210cdb23b2, 0xc068b7bd70)
	github.com/ethereum/go-ethereum/p2p/discover/v4_udp.go:571 +0x6c
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv4).RequestENR(0xc015fb8000, 0xc0660c56c0, 0x20300a, 0x20300a, 0x20300a)
	github.com/ethereum/go-ethereum/p2p/discover/v4_udp.go:342 +0x197
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv4).Resolve(0xc015fb8000, 0xc0660c56c0, 0xaa17db)
	github.com/ethereum/go-ethereum/p2p/discover/v4_udp.go:178 +0x50
github.com/ethereum/go-ethereum/p2p.(*dialTask).resolve(0xc05e907800, 0xc0177e8000, 0x0)
	github.com/ethereum/go-ethereum/p2p/dial.go:519 +0x8d
github.com/ethereum/go-ethereum/p2p.(*dialTask).run(0xc05e907800, 0xc0177e8000)
	github.com/ethereum/go-ethereum/p2p/dial.go:484 +0xda
github.com/ethereum/go-ethereum/p2p.(*dialScheduler).startDial.func1(0xc05e907800, 0xc0177e8000)
	github.com/ethereum/go-ethereum/p2p/dial.go:459 +0x35
created by github.com/ethereum/go-ethereum/p2p.(*dialScheduler).startDial
	github.com/ethereum/go-ethereum/p2p/dial.go:458 +0x42a
INFO [11-13|15:02:51.856] Starting Geth on Ethereum mainnet... 
````

**Comment by fjl** [comment]
Are you using the static nodes feature?

**Comment by KevinVitale** [comment]
> Are you using the static nodes feature?

Yes.

**Comment by fjl** [comment]
Thank you for the quick response. I'll fix this very soon, sorry for the inconvenience.
