### ISSUE TITLE
panic: close of closed channel 0.10.0

### ISSUE THREAD

**Issue by henrikno** [ethereum/go-ethereum#2187]
Just upgraded to 0.10 GA. It went fine for a day, but suddenly the process stopped, a bit after midnight.

```[retention] 2016/02/09 01:13:24 retention policy shard deletion check commencing
panic: close of closed channel

goroutine 272 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Close(0xc20811c960, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:147 +0x3e
github.com/influxdb/influxdb/tsdb.(*Shard).close(0xc2080f6160, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/shard.go:150 +0x54
github.com/influxdb/influxdb/tsdb.(*Shard).Close(0xc2080f6160, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x89
github.com/influxdb/influxdb/tsdb.(*Store).DeleteShard(0xc2080e0160, 0x56, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/store.go:134 +0xe4
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208140ae0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/services/retention/service.go:130 +0x8ab
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b8```

Full stacktrace: http://sprunge.us/JUPH (145645 goroutines)
Ubuntu 12.04 (2.6.32). Deb package.

**Comment by fjl** [comment]
This is a crash in influxdb. go-ethereum does not use influxdb in any way.

**Comment by henrikno** [comment]
I'm sorry, don't know how this got here :)
