### ISSUE TITLE
Can't figure out how to run own geth node for web3

### ISSUE THREAD

**Issue by thestick613** [ethereum/go-ethereum#21911]
Hello,

I've been using infura and linkpool as web3 providers:
from web3 import Web3
```
# w3 = Web3(Web3.HTTPProvider('https://main-rpc.linkpool.io'))
# w3 = Web3(Web3.HTTPProvider('https://mainnet.infura.io/v3/XxxxxxxxXXxxxxxxxxxxxxxxxxxxx/'))
```
but decided to run my own node, for better performance. I downloaded `geth-linux-amd64-1.9.24` and ran it like this:
`geth --cache 6144 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --rpcport 8080 --rpccorsdomain "*" --rpcaddr "127.0.0.1" --rpc`

`geth attach` and `eth.syncing` shows me
```
  currentBlock: 11339623,
  highestBlock: 11339709,
```
So i guess i'm synced.
However, when i run `w3.eth.getBalance(some_address)`, it returns 0. When i use linkpool or infura, i get a different value.

I'm also unable to interact with tether:

```
ERC20_ABI = [..]
tether_contract = w3.eth.contract('0xdAC17F958D2ee523a2206206994597C13D831ec7', abi=ERC20_ABI)
tether_contract.functions.balanceOf(that_address).call()
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1507, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/usr/local/lib/python3.6/dist-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/usr/local/lib/python3.6/dist-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.6/dist-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/usr/local/lib/python3.6/dist-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.6/dist-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/usr/local/lib/python3.6/dist-packages/eth_abi/decoding.py", line 308, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "testcode.py", line 46, in <module>
    usdt_balance = tether_contract.functions.balanceOf(that_address).call()
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 964, in call
    **self.kwargs
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1528, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```

What am i doing wrong?

**Comment by jmb-42** [comment]
Hi. This is pretty straightforward to fix: you just have to wait longer, because you are **not synced** yet. When your node has finished syncing, calling `eth.syncing` will return `false`.

The last chunk of blocks to sync takes a long time, and it varies depending on your hardware/network.

**Comment by thestick613** [comment]
Hello,

You are right, it works now.
Thanks
