### ISSUE TITLE
SIGINT never gets around to shutting down node

### ISSUE THREAD

**Issue by saurik** [ethereum/go-ethereum#21925]
#### System information

Geth version: 1.9.24-stable
OS & Version: Linux
Commit hash : cc05b050df5f88e80bb26aaf6d2f339c49c2d702

#### Expected behaviour

SIGINT causes node to shut down in a reasonable amount of time.

#### Actual behaviour

Over ten minutes later I'm still waiting for the node to shut down.

#### Steps to reproduce the behaviour

Attempt to shut down a running node using SIGINT.

#### Backtrace

I saw #1379 had been asked for the log after you just panic it, so:

[sigint.log](https://github.com/ethereum/go-ethereum/files/5616355/sigint.log)

**Comment by holiman** [comment]
Interesting. @zsfelfoldi the stack has a ton of these: 
```
goroutine 33251500 [sync.Cond.Wait, 12 minutes]:
runtime.goparkunlock(...)
        runtime/proc.go:312
sync.runtime_notifyListWait(0xc0fd57ca10, 0x7b)
        runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0fd57ca00)
        sync/cond.go:56 +0x9d
github.com/ethereum/go-ethereum/p2p/nodestate.(*NodeStateMachine).opStart(0xc0fd5d81c0, 0x35)
        github.com/ethereum/go-ethereum/p2p/nodestate/nodestate.go:703 +0x2c
github.com/ethereum/go-ethereum/p2p/nodestate.(*NodeStateMachine).SetField(0xc0fd5d81c0, 0xc119f781c0, 0x2, 0x1e6ea40, 0x0, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum/p2p/nodestate/nodestate.go:865 +0x7b
github.com/ethereum/go-ethereum/les.(*clientPool).disconnectNode(0xc109244420, 0xc119f781c0)
        github.com/ethereum/go-ethereum/les/clientpool.go:264 +0x65
github.com/ethereum/go-ethereum/les.(*clientPool).disconnect(0xc109244420, 0x1555560, 0xc188ef99e0)
        github.com/ethereum/go-ethereum/les/clientpool.go:259 +0x3f
github.com/ethereum/go-ethereum/les.(*serverHandler).handle.func3(0xc115b93790, 0xc0fc8e94a0, 0xc188ef99e0, 0x4cd377491a824)
        github.com/ethereum/go-ethereum/les/server_handler.go:180 +0x5e
github.com/ethereum/go-ethereum/les.(*serverHandler).handle(0xc0fc8e94a0, 0xc188ef99e0, 0x15349c0, 0xc00006a060)
        github.com/ethereum/go-ethereum/les/server_handler.go:200 +0xa40
github.com/ethereum/go-ethereum/les.(*serverHandler).runPeer(0xc0fc8e94a0, 0x3, 0xc1fed021e0, 0x15438a0, 0xc1c27d2a00, 0x0, 0x0)
        github.com/ethereum/go-ethereum/les/server_handler.go:112 +0x10e
github.com/ethereum/go-ethereum/les.(*lesCommons).makeProtocols.func1(0xc1fed021e0, 0x15438a0, 0xc1c27d2a00, 0xf8ae76f84067e5d4, 0x67f5d5406ab810c0)
        github.com/ethereum/go-ethereum/les/commons.go:97 +0x4c
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc1fed021e0, 0xc1c27d2a00, 0x15438a0, 0xc1c27d2a00)
        github.com/ethereum/go-ethereum/p2p/peer.go:379 +0x98
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        github.com/ethereum/go-ethereum/p2p/peer.go:377 +0x205
```
Where looks like we're trying to disconnect a node `les.(*clientPool).disconnectNode(`, but get stuck on some `sync.Cond`. PTAL

@saurik what's was the command line that started it?

**Comment by saurik** [comment]
```#!/bin/bash
ulimit -n 65535
exec geth \
    --cache $((24*1024)) \
    --http --http.addr 0.0.0.0 --http.api eth,web3,net --http.vhosts '*' \
    --ws --ws.addr 0.0.0.0 \
    --graphql --graphql.vhosts '*' \
    --nousb --light.serve 50
```

**Comment by holiman** [comment]
@zsfelfoldi 
```golang
// Output:
/*
=== RUN   TestDeadlock
Long running op started
Stopping the node machine
Calling setfield (id 3)
Calling setfield (id 0)
Calling setfield (id 1)
Calling setfield (id 2)
Long running op ended
Node machine stopped
Ok, exiting now (id 3)
*/
func TestDeadlock(t *testing.T){

	//mdb, clock := rawdb.NewMemoryDatabase(), &mclock.Simulated{}
	mdb, clock := rawdb.NewMemoryDatabase(), &mclock.Simulated{}

	s, _, _ := testSetup([]bool{false, false, false, false}, nil)
	ns := NewNodeStateMachine(mdb, []byte("-ns"), clock, s)
	ns.Start()
	startedCh := make(chan bool)
	// some operation takes a lot of time
	go func(){
		err := ns.Operation(func(){
			close(startedCh)
			fmt.Printf("Long running op started\n")
			// Wait here until someone signals us to go ahead
			time.Sleep(1*time.Second)
			//<- aChan
			fmt.Printf("Long running op ended\n")
		})
		if err != nil{
			t.Fatalf("error in test: %v", err)
		}
	}()
	<- startedCh
	var wg sync.WaitGroup
	// The long-running op is now executing.
	// While that's happening, four other guys wants to do sometihng
	for i := 0; i < 4 ; i++{
		wg.Add(4)
		go func(i int){
			fmt.Printf("Calling setfield (id %d)\n", i)
			ns.SetField(testNode(byte(i)), Field{}, nil)
			fmt.Printf("Ok, exiting now (id %d)\n", i)
			wg.Done()
		}(i)
	}
	// We stop the node machine
	fmt.Printf("Stopping the node machine\n")
	ns.Stop()
	fmt.Printf("Node machine stopped\n")
	wg.Wait()
}
```

**Comment by holiman** [comment]
> some kind of long-running leveldb compaction happening? 

Yes, it's a background compaction in leveldb

**Comment by holiman** [comment]
Thanks for the detailed report!
