### ISSUE TITLE
PoA Geth 1.8.16 shows an error of out of memory

### ISSUE THREAD

**Issue by cygnet-dev** [ethereum/go-ethereum#22074]
We are working with multi node setup on Ethereum private chain PoA for enterprise. We have all three validator nodes.
```
blockchain    
├── genesis.json    
├── node1    
│   ├── geth    
│   ├── keystore    
│   ├── password.txt    
│   └── static-nodes.json    
├── node2    
│   ├── geth    
│   ├── keystore
│   ├── password.txt    
│   └── static-nodes.json    
└── node3    
    ├── geth    
    ├── keystore
    ├── password.txt    
    └── static-nodes.json  
```

Our private blockchain is integrated with the web application written in ASP.NET Core. To send request from web to blockchain, we're using NodeJs api as a middle layer, which forward the request from the web app to blockchain. Each are located on different server.

`Web App > API > Blockchain`

Use Case:
When a user register with the web app, it sends the request to the blockchain and create a wallet for it. The wallet address, private-key are stored in database for further use. Also system will send some ethers to each user from the coinbase account.

### Issue: 
While sending **multiple concurrent request** of user creation, geth consumes all the available memory and and the first validator node goes down. 

Code to create wallets from API

```
var accountObj = provider.web3.eth.accounts.create();
var pivatekey = accountObj.privateKey.substring(2);        

provider.web3.eth.accounts.encrypt(accountObj.privateKey, request.walletPassword);

await provider.web3.eth.personal.importRawKey(pivatekey, request.walletPassword);

if (accountObj.address != null) {
    await provider.web3.eth.sendTransaction({
        from: await account.coinbase(),
        to: accountObj.address,
        value: await provider.web3.utils.toWei(20, "ether")
    });
}
```

Validator node start script

```
GLOBAL_ARGS="--networkid 1616 --nodiscover --gasprice 0 --targetgaslimit 470000000000 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --mine --etherbase 0x8003E64D0ge1f0BdC02DCA6009Bc57Bb77Aa4F66 --minerthreads 1"

echo "Starting node1 ...!"

nohup /usr/bin/geth -datadir=$pwd  $GLOBAL_ARGS --keystore /home/ubuntu/blockchain/keystore/ --rpcport 8545 --port 30303 --identity "validator_node_1" --unlock "0x8003E64D0ge1f0BdC02DCA6009Bc57Bb77Aa4F66" --password /home/ubuntu/blockchain/node1/password.txt &

echo "Node started successfully, check logs in nohup file!"
```

What we have tried?

1. Tried to add cache parameter like --cache=1024

Logs
```
fullhash=0xabf94d87d2a81e5e1a7583db67d22d7f3906b1a801cd560cf4be00564056b15f recipient=0xd7F9F336C2b48d7581BA834278db134b4625c2E5
INFO [12-24|22:12:49.309] Commit new mining work                   number=444 sealhash=e36aaaâ€¦3635e0 uncles=2 txs=1 gas=21000  fees=0 elapsed=285.611Âµs
INFO [12-24|22:12:49.534] Successfully sealed new block            number=444 sealhash=e36aaaâ€¦3635e0 hash=87a5b1â€¦994589 elapsed=225.051ms
INFO [12-24|22:12:49.534] ðŸ”¨ mined potential block                  number=444 hash=87a5b1â€¦994589
INFO [12-24|22:12:49.535] Chain reorg detected                     number=443 hash=67d5beâ€¦50d3d0 drop=1 dropfrom=87a5b1â€¦994589 add=1 addfrom=fdff76â€¦84249b
INFO [12-24|22:12:49.538] Imported new chain segment               blocks=1 txs=1 mgas=0.021 elapsed=2.953ms   mgasps=7.109  number=444 hash=fdff76â€¦84249b dirty=0.00B
INFO [12-24|22:12:49.540] Submitted transaction                    fullhash=0xace981b59f1fa88feffe27493904983e2e3df7c654609525da9106843efccd8a recipient=0x2F473A0783350fB7784F194751BdB62B0d54753F
INFO [12-24|22:12:49.540] Commit new mining work                   number=445 sealhash=f04ea2â€¦b42242 uncles=2 txs=1 gas=21000  fees=0 elapsed=318.91Âµs
INFO [12-24|22:12:49.620] Commit new mining work                   number=445 sealhash=be3656â€¦d4208c uncles=2 txs=0 gas=0      fees=0 elapsed=135.89Âµs
INFO [12-24|22:12:49.622] Sealing paused, waiting for transactions 
INFO [12-24|22:12:49.622] Commit new mining work                   number=445 sealhash=be3656â€¦d4208c uncles=2 txs=0 gas=0      fees=0 elapsed=1.337ms
INFO [12-24|22:12:49.622] Commit new mining work                   number=445 sealhash=f04ea2â€¦b42242 uncles=2 txs=1 gas=21000  fees=0 elapsed=1.545ms
INFO [12-24|22:12:49.624] Imported new chain segment               blocks=1 txs=1 mgas=0.021 elapsed=814.141Âµs mgasps=25.794 number=445 hash=f91028â€¦6e4cd0 dirty=0.00B
INFO [12-24|22:12:49.624] ðŸ˜± block lost                             number=438 hash=421f5dâ€¦ec4a59
INFO [12-24|22:12:49.624] Commit new mining work                   number=446 sealhash=dc3946â€¦e8b056 uncles=2 txs=0 gas=0      fees=0 elapsed=191.639Âµs
INFO [12-24|22:12:49.662] Sealing paused, waiting for transactions 
INFO [12-24|22:12:49.662] Commit new mining work                   number=446 sealhash=dc3946â€¦e8b056 uncles=2 txs=0 gas=0      fees=0 elapsed=38.517ms
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x116cb1a, 0x16)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc3f4000000, 0x10000000, 0x1ece0f8)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1e9ca40, 0x10000000, 0x8, 0x7facd280c518)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x1e9ca40, 0x8000, 0xffffffff)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x1e9ca40, 0x8000, 0x1ece108, 0x7facc67fbe48)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x1e9ca40, 0x8000, 0x7faccc120101, 0x7faccc129ae8)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x1e9ca40, 0x8000, 0x7faccc010101, 0x7facc67fbeb0)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x10000000, 0x7facc67f0101, 0x46fafe)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x7faccd28cbd0)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/proc.go:1146

goroutine 6761 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/asm_amd64.s:330 fp=0xc0006c2ec8 sp=0xc0006c2ec0 pc=0x473400
runtime.mallocgc(0x10000000, 0xf896c0, 0xc0000ec701, 0xc002702800)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:1032 +0x895 fp=0xc0006c2f68 sp=0xc0006c2ec8 pc=0x4223f5
runtime.makeslice(0xf896c0, 0x4000000, 0x4000000, 0xc002702800)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/slice.go:49 +0x6c fp=0xc0006c2f98 sp=0xc0006c2f68 pc=0x45beec
golang.org/x/crypto/scrypt.Key(0xc00444dc30, 0x9, 0x10, 0xc003e3c240, 0x20, 0x40, 0x40000, 0x8, 0x1, 0x20, ...)
	/home/travis/gopath/pkg/mod/golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2/scrypt/scrypt.go:236 +0x14b fp=0xc0006c3048 sp=0xc0006c2f98 pc=0x6fb41b
github.com/ethereum/go-ethereum/accounts/keystore.getKDFKey(0xc00444dbd0, 0xb, 0xc003e3c100, 0x40, 0xc00067af80, 0x20, 0xc00444dba8, 0x6, 0xc0042d7590, 0xc003e3c180, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:333 +0x6a2 fp=0xc0006c3130 sp=0xc0006c3048 pc=0x716432
github.com/ethereum/go-ethereum/accounts/keystore.DecryptDataV3(0xc00444dbd0, 0xb, 0xc003e3c100, 0x40, 0xc00067af80, 0x20, 0xc00444dba8, 0x6, 0xc0042d7590, 0xc003e3c180, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:258 +0x310 fp=0xc0006c3288 sp=0xc0006c3130 pc=0x715050
github.com/ethereum/go-ethereum/accounts/keystore.decryptKeyV3(0xc004475b00, 0xc003be18b0, 0x9, 0xf4b220, 0xc004475b00, 0x0, 0x0, 0x1eb, 0x3eb, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:280 +0x103 fp=0xc0006c33a8 sp=0xc0006c3288 pc=0x7154c3
github.com/ethereum/go-ethereum/accounts/keystore.DecryptKey(0xc0022f3800, 0x1eb, 0x3eb, 0xc003be18b0, 0x9, 0x0, 0x0, 0x52)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:224 +0x1c2 fp=0xc0006c3460 sp=0xc0006c33a8 pc=0x714a42
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.GetKey(0x7ffdb62a46a5, 0x2a, 0x40000, 0x1, 0x0, 0x8497d264029d6db4, 0xbf880273b21e4982, 0x7a34c9af, 0xc0028ea870, 0x86, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:89 +0x9c fp=0xc0006c34f8 sp=0xc0006c3460 pc=0x71312c
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.StoreKey(0x7ffdb62a46a5, 0x2a, 0x40000, 0x1, 0x0, 0xc0025ef800, 0x78, 0xc003dfb940, 0xc003be18b0, 0x9, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/passphrase.go:118 +0x1d2 fp=0xc0006c35d8 sp=0xc0006c34f8 pc=0x713692
github.com/ethereum/go-ethereum/accounts/keystore.(*keyStorePassphrase).StoreKey(0xc0001df4a0, 0xc0025ef800, 0x78, 0xc003dfb940, 0xc003be18b0, 0x9, 0x1ecd4c0, 0x29d6db4006d7180)
	<autogenerated>:1 +0xca fp=0xc0006c3670 sp=0xc0006c35d8 pc=0x71a0ca
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).importKey(0xc0000f0a80, 0xc003dfb940, 0xc003be18b0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:460 +0x15e fp=0xc0006c3710 sp=0xc0006c3670 pc=0x712b5e
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).ImportECDSA(0xc0000f0a80, 0xc0010f2420, 0xc003be18b0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:455 +0x182 fp=0xc0006c37e0 sp=0xc0006c3710 pc=0x712952
github.com/ethereum/go-ethereum/internal/ethapi.(*PrivateAccountAPI).ImportRawKey(0xc000814800, 0xc00287b080, 0x40, 0xc003be18b0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:305 +0x120 fp=0xc0006c38a8 sp=0xc0006c37e0 pc=0xb2d530
runtime.call128(0xc0010f2990, 0xc0001b1bb8, 0xc002b34fa0, 0x2800000050)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/asm_amd64.s:541 +0x52 fp=0xc0006c3938 sp=0xc0006c38a8 pc=0x4738d2
reflect.Value.call(0xc0001c3380, 0xc0001b1bb8, 0x13, 0x1157cf0, 0x4, 0xc003a99080, 0x3, 0x4, 0xc004c15bc8, 0x45beec, ...)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/reflect/value.go:460 +0x5f6 fp=0xc0006c3b58 sp=0xc0006c3938 pc=0x4abb96
reflect.Value.Call(0xc0001c3380, 0xc0001b1bb8, 0x13, 0xc003a99080, 0x3, 0x4, 0x2, 0x2, 0x2)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/reflect/value.go:321 +0xb4 fp=0xc0006c3bd8 sp=0xc0006c3b58 pc=0x4ab354
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc00114ab40, 0x13f7f20, 0xc003dfb880, 0xc0006016c0, 0x15, 0xc0010f2390, 0x2, 0x2, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/service.go:206 +0x2b9 fp=0xc0006c3d00 sp=0xc0006c3bd8 pc=0x888629
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0035bcea0, 0x13f7f20, 0xc003dfb880, 0xc000443ce0, 0xc00114ab40, 0xc0010f2390, 0x2, 0x2, 0x2)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:369 +0x8a fp=0xc0006c3d70 sp=0xc0006c3d00 pc=0x88185a
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc0035bcea0, 0xc0010f2240, 0xc000443ce0, 0xc0001a8330)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:331 +0x22c fp=0xc0006c3df0 sp=0xc0006c3d70 pc=0x880d6c
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc0035bcea0, 0xc0010f2240, 0xc000443ce0, 0x13e3701)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:298 +0x1f3 fp=0xc0006c3ea0 sp=0xc0006c3df0 pc=0x880543
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc0010f2240)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:139 +0x46 fp=0xc0006c3f10 sp=0xc0006c3ea0 pc=0x88d166
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1(0xc0035bcea0, 0xc0006d70e0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:226 +0x119 fp=0xc0006c3fd0 sp=0xc0006c3f10 pc=0x88d369
runtime.goexit()
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0006c3fd8 sp=0xc0006c3fd0 pc=0x4754d1
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:222 +0x66

```

Blockchain Server Configuration:

CPU: 4 core
Storage: 100 GB SSD
RAM: 16 GB
SWP: 976 MB
Geth: 1.8.16

`free` result 

![image](https://user-images.githubusercontent.com/42034837/103129866-4e85f880-46c0-11eb-98c1-7322879953ac.png)

**Comment by holiman** [comment]
That's scrypt, used for encrypting the keystore. It's designed to use a lot.of memory, to make brute force attacks slow. You can use --lightkdf to set the mem requirements lower.
