### ISSUE TITLE
nousb by default

### ISSUE THREAD

**Issue by pynixwang** [ethereum/go-ethereum#22080]
crash on macos when no `--nousb` flag

**Comment by pynixwang** [comment]
stacktrace

```
geth --goerli
INFO [12-27|12:41:22.420] Starting Geth on Görli testnet...
INFO [12-27|12:41:22.421] Maximum peer count                       ETH=50 LES=0 total=50
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff39b6afef]

runtime stack:
runtime.throw(0x4f1f7fb, 0x2a)
	runtime/panic.go:1116 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:726 +0x48c

goroutine 1 [syscall]:
runtime.cgocall(0x4c46155, 0xc00010f7f0, 0x0)
	runtime/cgocall.go:133 +0x5b fp=0xc00010f7c0 sp=0xc00010f788 pc=0x400811b
github.com/karalabe/usb._Cfunc_hid_enumerate(0xc000002c97, 0x0)
	_cgo_gotypes.go:276 +0x4e fp=0xc00010f7f0 sp=0xc00010f7c0 pc=0x476b0ae
github.com/karalabe/usb.enumerateHid(0xc000002c97, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/hid_enabled.go:40 +0x85 fp=0xc00010f908 sp=0xc00010f7f0 pc=0x476bee5
github.com/karalabe/usb.Enumerate(0x2c97, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/usb_enabled.go:58 +0x10b fp=0xc00010f9b0 sp=0xc00010f908 pc=0x476a96b
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).refreshWallets(0xc0000d1900)
	github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:163 +0xdd fp=0xc00010fe28 sp=0xc00010f9b0 pc=0x48550dd
github.com/ethereum/go-ethereum/accounts/usbwallet.newHub(0x4eec79d, 0x6, 0x2c97, 0xc00022c680, 0x9, 0x9, 0xffa0, 0x0, 0x4fc5648, 0x0, ...)
	github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:114 +0xe6 fp=0xc00010fe60 sp=0xc00010fe28 pc=0x4854de6
github.com/ethereum/go-ethereum/accounts/usbwallet.NewLedgerHub(0x4d860a0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:73 +0xa5 fp=0xc00010fed0 sp=0xc00010fe60 pc=0x4854cc5
github.com/ethereum/go-ethereum/node.makeAccountManager(0xc0000ec840, 0x0, 0x0, 0xc0001100d8, 0x4, 0x4)
	github.com/ethereum/go-ethereum/node/config.go:481 +0x48e fp=0xc000110018 sp=0xc00010fed0 pc=0x48fe76e
github.com/ethereum/go-ethereum/node.New(0xc00001b4d0, 0xc00001b4d0, 0x6, 0x0)
	github.com/ethereum/go-ethereum/node/node.go:117 +0x57f fp=0xc0001101c8 sp=0xc000110018 pc=0x490031f
main.makeConfigNode(0xc0000d82c0, 0xc00001ac00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:139 +0x35e fp=0xc000110d50 sp=0xc0001101c8 pc=0x4be60fe
main.makeFullNode(0xc0000d82c0, 0x4eede8a, 0x1, 0xc00047efa0)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:163 +0x85 fp=0xc000111b78 sp=0xc000110d50 pc=0x4be6645
main.geth(0xc0000d82c0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:354 +0xf4 fp=0xc000111bf0 sp=0xc000111b78 pc=0x4bea434
gopkg.in/urfave/cli%2ev1.HandleAction(0x4d17260, 0x4fc7cf0, 0xc0000d82c0, 0xc00007b500, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82 fp=0xc000111c18 sp=0xc000111bf0 pc=0x4675de2
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00009e4e0, 0xc0000a8020, 0x2, 0x2, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5 fp=0xc000111f28 sp=0xc000111c18 pc=0x4673e55
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:273 +0x55 fp=0xc000111f88 sp=0xc000111f28 pc=0x4be95f5
runtime.main()
	runtime/proc.go:204 +0x209 fp=0xc000111fe0 sp=0xc000111f88 pc=0x403e1e9
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc000111fe8 sp=0xc000111fe0 pc=0x4074841

goroutine 19 [chan receive]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc0000c60f0)
	github.com/rjeczalik/notify@v0.9.1/tree_recursive.go:125 +0xc7
created by github.com/rjeczalik/notify.newRecursiveTree
	github.com/rjeczalik/notify@v0.9.1/tree_recursive.go:119 +0x13b

goroutine 20 [syscall, locked to thread]:
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:232 +0x45
github.com/rjeczalik/notify.init.1.func1()
	github.com/rjeczalik/notify@v0.9.1/watcher_fsevents_cgo.go:72 +0x3f
created by github.com/rjeczalik/notify.init.1
	github.com/rjeczalik/notify@v0.9.1/watcher_fsevents_cgo.go:63 +0x4e

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x5a1d940)
	github.com/ethereum/go-ethereum/metrics/meter.go:290 +0x7d
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
	github.com/ethereum/go-ethereum/metrics/meter.go:71 +0x105

goroutine 23 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001a0bc0)
	github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 24 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001a0bc0)
	github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 25 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001a0bc0)
	github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 26 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001a0bc0)
	github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 36 [syscall]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:144 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x45

goroutine 8 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0003ca1e0)
	github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:278 +0x25c
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
	github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:262 +0x2b2

goroutine 11 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc0001906a0)
	github.com/ethereum/go-ethereum/accounts/keystore/watch.go:94 +0x4c5
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x59
```

**Comment by ligi** [comment]
relevant PR #21984

**Comment by holiman** [comment]
@pynixwang 
1. what OS version is it, more exactly? 
2. Does it happen every time, or was it just once?
3. What exact `geth` version  was used?

**Comment by pynixwang** [comment]
```
System Version: macOS 10.15.3 (19D76)
```
always crash if no flag.

macos stacktrace no usb info. maybe somethings I run on linux and find error message has 'usb', so I disable it.
```
geth version
Geth
Version: 1.9.25-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: darwin
GOPATH=/Users/pynix/go
GOROOT=go
```

**Comment by gballet** [comment]
Thanks for pointing this out. It should be fixed, please check again with next release and open a new issue if the problem persists.
