### ISSUE TITLE
secp256k throwing after windows build (32 bit go on win64)

### ISSUE THREAD

**Issue by androlo** [ethereum/go-ethereum#221]
Can't run on win64. Builds, but panics when secp256 function is called. Using MinGW32 gmp library as per the instructions. I have generated a working go executable using the gmp lib (5.1.2), so that part works. Output when running the secp256 tests:

```
=== RUN Test_Secp256_00
--- PASS: Test_Secp256_00 (0.00 seconds)
=== RUN Test_Secp256_01
2014/12/23 15:14:22 --- FAIL: Test_Secp256_01 (0.00 seconds)
panic:  [recovered]
        panic:

goroutine 21 [running]:
runtime.panic(0x5085a0, 0x124be118)
        C:/Go/src/pkg/runtime/panic.c:279 +0xe9
testing.func┬À006()
        C:/Go/src/pkg/testing/testing.go:416 +0x12d
runtime.panic(0x5085a0, 0x124be118)
        C:/Go/src/pkg/runtime/panic.c:248 +0x176
log.Panic(0x0, 0x0, 0x0)
        C:/Go/src/pkg/log/log.go:307 +0xa1
github.com/obscuren/secp256k1-go.VerifyPubkeyValidity(0x124ac4b0, 0x41, 0x41, 0x1)
        C:/Users/Andreas/go/src/github.com/obscuren/secp256k1-go/secp256.go:188 +0x38
github.com/obscuren/secp256k1-go.Test_Secp256_01(0x124ae6c0)
        C:/Users/Andreas/go/src/github.com/obscuren/secp256k1-go/secp256_test.go:45 +0xa6
testing.tRunner(0x124ae6c0, 0x5f292c)
        C:/Go/src/pkg/testing/testing.go:422 +0x87
created by testing.RunTests
        C:/Go/src/pkg/testing/testing.go:504 +0x720

goroutine 16 [chan receive]:
testing.RunTests(0x57ac04, 0x5f2920, 0x9, 0x9, 0x422101)
        C:/Go/src/pkg/testing/testing.go:505 +0x75c
testing.Main(0x57ac04, 0x5f2920, 0x9, 0x9, 0x5f8dc0, 0x0, 0x0, 0x5f8dc0, 0x0, 0x0)
        C:/Go/src/pkg/testing/testing.go:435 +0x6e
main.main()
        github.com/obscuren/secp256k1-go/_test/_testmain.go:63 +0x86

goroutine 17 [syscall]:
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1445

goroutine 19 [finalizer wait]:
runtime.park(0x412d30, 0x5f6998, 0x5f5c89)
        C:/Go/src/pkg/runtime/proc.c:1369 +0x94
runtime.parkunlock(0x5f6998, 0x5f5c89)
        C:/Go/src/pkg/runtime/proc.c:1385 +0x3f
runfinq()
        C:/Go/src/pkg/runtime/mgc0.c:2644 +0xc5
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1445
exit status 2
FAIL    github.com/obscuren/secp256k1-go        0.942s
```

Some info:

Windows 8.1, 64 bit
go 1.3.3, 32 bit
gcc 4.8.1
gmp-5.1.2-1-mingw32

**Comment by obscuren** [comment]
I've updated the sec256k1 repo which addresses the failing tests https://github.com/obscuren/secp256k1-go/commit/2169cf82b740b1c95b7d518ffc65f142589923c8
