### ISSUE TITLE
Generated Code From ABIGen May Panic Due To Unchecked Error Condition

### ISSUE THREAD

**Issue by bonedaddy** [ethereum/go-ethereum#22100]
#### System information

abigen version: `abigen version 1.9.23-stable-8c2f2715`

#### Generated Code

The following generated code is from running `abigen` against the Uniswap V2Pair contracts:

```
// GetReserves is a free data retrieval call binding the contract method 0x0902f1ac.
//
// Solidity: function getReserves() view returns(uint112 reserve0, uint112 reserve1, uint32 blockTimestampLast)
func (_Uniswapv2pair *Uniswapv2pairCaller) GetReserves(opts *bind.CallOpts) (struct {
	Reserve0           *big.Int
	Reserve1           *big.Int
	BlockTimestampLast uint32
}, error) {
	var out []interface{}
	err := _Uniswapv2pair.contract.Call(opts, &out, "getReserves")

	outstruct := new(struct {
		Reserve0           *big.Int
		Reserve1           *big.Int
		BlockTimestampLast uint32
	})

	outstruct.Reserve0 = out[0].(*big.Int)
	outstruct.Reserve1 = out[1].(*big.Int)
	outstruct.BlockTimestampLast = out[2].(uint32)

	return *outstruct, err

}
```

In the case where `err := _Uniswapv2pair.contract.Call(opts, &out, "getReserves")` results in `err` actually containing an error then the following will cause a panic because `out` will have no elements in it. This code expects that `err` is nil, which will be fine until there is an error which will produce a panic similar to:

```
2021/01/01 11:44:56 bot is now running
panic: runtime error: index out of range [0] with length 0

goroutine 29 [running]:
github.com/bonedaddy/go-indexed/bindings/uniswapv2/pair.(*Uniswapv2pairCaller).GetReserves(0xc0000ae5f0, 0xc000a77cf0, 0x2540be400, 0xecf0a0, 0xc0005cd1a0, 0xc000479b50, 0x0)
	/BUILD/bindings/uniswapv2/pair/v2pair.go:408 +0x1de
github.com/bonedaddy/go-indexed/uniswap.(*Client).GetReserves(0xc0000aec18, 0x8dfe23b239aa2ac0, 0x8d9ea274f5c0e0a, 0x7454176bc26c753c, 0x958ba94dc49490e8, 0xf1d2795c4eaed4e, 0x0, 0x0, 0x0)
	/BUILD/uniswap/client.go:52 +0x176
github.com/bonedaddy/go-indexed/bclient.(*Client).Reserves(0xc0004212d0, 0xd9a0ef, 0x7, 0xc26c753c08d9ea00, 0x0, 0x0)
	/BUILD/bclient/uniswap.go:110 +0x20c
github.com/bonedaddy/go-indexed/bclient.(*Client).EthDaiPrice(0xc0004212d0, 0xc0004810a0, 0x12, 0xc000481700)
	/BUILD/bclient/uniswap.go:87 +0x45
github.com/bonedaddy/go-indexed/bclient.(*Client).NdxDaiPrice(0xc0004212d0, 0x3, 0xc00053e3ca, 0x3)
	/BUILD/bclient/uniswap.go:35 +0xc9
github.com/bonedaddy/go-indexed/discord.launchWatchers.func1(0xc000430710, 0xc00044e6c0, 0xecf020, 0xc00030b140, 0xc0004212d0, 0xc0004306c0, 0x3)
	/BUILD/discord/discord.go:229 +0x6cf
created by github.com/bonedaddy/go-indexed/discord.launchWatchers
	/BUILD/discord/discord.go:192 +0x1b2
```

The correct way to handle this would e to get if `Call` returns an error, and if it does, skip processing the rest of the generated code.

**Comment by MariusVanDerWijden** [comment]
It's already been fixed on master: https://github.com/ethereum/go-ethereum/commit/38c1d592b7121f26dc661c1bc2bf0e32eba9d888

**Comment by bonedaddy** [comment]
Thanks this appears to have fixed the problem
