### ISSUE TITLE
Snap sync crash

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#22172]
#### System information

Geth version: running this PR: https://github.com/ethereum/go-ethereum/pull/22171

#### Backtrace

```
Jan 14 15:28:42 mon02.ethdevops.io geth ERROR[01-14|14:28:42.822] Failed to unregister sync peer peer=8d1da4c5bc682f8f err="peer is not registered"
Jan 14 15:28:42 mon02.ethdevops.io geth ERROR[01-14|14:28:42.822] Peer removal failed peer=8d1da4c5bc682f8f8ad141f60d2889fa4232144c7d2b29b88f81ca33e586ef9d err="peer not registered"
Jan 14 15:28:57 mon02.ethdevops.io geth INFO [01-14|14:28:57.753] Imported new block headers count=1 elapsed=5.663ms number=11653740 hash="ca00ee…31096b" age=1m17s
Jan 14 15:28:57 mon02.ethdevops.io geth WARN [01-14|14:28:57.811] Pivot became stale, moving old=11653614 new=11653678
Jan 14 15:28:58 mon02.ethdevops.io geth INFO [01-14|14:28:57.969] Imported new block receipts count=64 elapsed=156.810ms number=11653677 hash="09ff58…8b1d27" age=15m43s size=5.88MiB
Jan 14 15:28:58 mon02.ethdevops.io geth INFO [01-14|14:28:58.744] State sync in progress synced=+Inf% state=383.26KiB accounts=0@0.00B slots=2815@383.26KiB codes=0@0.00B eta=-1h15m20.520s
Jan 14 15:29:01 mon02.ethdevops.io geth INFO [01-14|14:29:01.804] State sync in progress synced=0.02% state=9.00MiB accounts=21455@4.06MiB slots=21586@3.85MiB codes=588@1.10MiB eta=6701h28m34.736s
Jan 14 15:29:05 mon02.ethdevops.io geth INFO [01-14|14:29:05.579] State sync in progress synced=0.04% state=21.92MiB accounts=42798@8.09MiB slots=69418@11.46MiB codes=1188@2.37MiB eta=3352h25m1.300s
Jan 14 15:29:08 mon02.ethdevops.io geth INFO [01-14|14:29:08.607] State sync in progress synced=0.06% state=36.05MiB accounts=64207@12.14MiB slots=116637@17.53MiB codes=2606@6.38MiB eta=2239h18m57.744s
Jan 14 15:29:12 mon02.ethdevops.io geth INFO [01-14|14:29:12.177] State sync in progress synced=0.07% state=45.75MiB accounts=85666@16.19MiB slots=142604@22.05MiB codes=2959@7.51MiB eta=1682h22m24.872s
Jan 14 15:29:13 mon02.ethdevops.io geth INFO [01-14|14:29:13.397] Imported new block headers count=1 elapsed=5.355ms number=11653741 hash="150ce8…7bede3" age=1m15s
Jan 14 15:29:16 mon02.ethdevops.io geth INFO [01-14|14:29:16.728] State sync in progress synced=0.13% state=65.67MiB accounts=149888@28.33MiB slots=188705@28.58MiB codes=3353@8.77MiB eta=961h4m59.606s
Jan 14 15:29:19 mon02.ethdevops.io geth INFO [01-14|14:29:19.768] State sync in progress synced=0.14% state=76.71MiB accounts=160571@30.35MiB slots=236529@36.75MiB codes=3590@9.61MiB eta=897h22m9.285s
Jan 14 15:29:19 mon02.ethdevops.io geth INFO [01-14|14:29:19.781] Imported new block headers count=1 elapsed=5.379ms number=11653742 hash="c93105…f76a8e"
Jan 14 15:29:22 mon02.ethdevops.io geth INFO [01-14|14:29:22.939] State sync in progress synced=0.14% state=96.79MiB accounts=160571@30.35MiB slots=394435@56.83MiB codes=3590@9.61MiB eta=897h59m34.760s
Jan 14 15:29:26 mon02.ethdevops.io geth INFO [01-14|14:29:26.080] State sync in progress synced=0.14% state=121.02MiB accounts=160571@30.35MiB slots=584668@81.06MiB codes=3590@9.61MiB eta=898h36m22.622s
Jan 14 15:29:29 mon02.ethdevops.io geth INFO [01-14|14:29:29.214] State sync in progress synced=0.14% state=142.79MiB accounts=160571@30.35MiB slots=755847@102.83MiB codes=3590@9.61MiB eta=899h14m25.858s
Jan 14 15:29:33 mon02.ethdevops.io geth INFO [01-14|14:29:33.642] State sync in progress synced=0.14% state=159.87MiB accounts=160571@30.35MiB slots=890132@119.91MiB codes=3590@9.61MiB eta=900h6m47.945s
Jan 14 15:29:36 mon02.ethdevops.io geth INFO [01-14|14:29:36.641] Imported new block headers count=1 elapsed=5.464ms number=11653743 hash="0bf83a…72df86"
Jan 14 15:29:36 mon02.ethdevops.io geth INFO [01-14|14:29:36.657] State sync in progress synced=0.15% state=175.22MiB accounts=171181@32.35MiB slots=989543@133.06MiB codes=3653@9.81MiB eta=844h57m46.180s
Jan 14 15:29:39 mon02.ethdevops.io geth INFO [01-14|14:29:39.665] Imported new block headers count=1 elapsed=5.435ms number=11653744 hash="740dd0…ea0477"
Jan 14 15:29:39 mon02.ethdevops.io geth INFO [01-14|14:29:39.753] State sync in progress synced=0.18% state=187.81MiB accounts=203316@38.43MiB slots=1032930@138.78MiB codes=3841@10.60MiB eta=712h10m49.300s
Jan 14 15:29:43 mon02.ethdevops.io geth INFO [01-14|14:29:43.081] State sync in progress synced=0.21% state=206.16MiB accounts=246120@46.52MiB slots=1104086@148.30MiB codes=4022@11.34MiB eta=588h41m28.830s
Jan 14 15:29:45 mon02.ethdevops.io geth INFO [01-14|14:29:45.701] Imported new block headers count=1 elapsed=5.661ms number=11653745 hash="3e6db2…8377c1"
Jan 14 15:29:46 mon02.ethdevops.io geth INFO [01-14|14:29:46.210] State sync in progress synced=0.23% state=221.47MiB accounts=267477@50.56MiB slots=1185296@159.03MiB codes=4153@11.88MiB eta=541h20m4.733s
Jan 14 15:29:46 mon02.ethdevops.io geth INFO [01-14|14:29:46.616] Downloader queue stats receiptTasks=0 blockTasks=0 itemSize=216.24KiB throttle=304
Jan 14 15:30:01 mon02.ethdevops.io geth INFO [01-14|14:30:01.595] State sync in progress synced=0.26% state=238.85MiB accounts=299513@56.62MiB slots=1265884@169.68MiB codes=4341@12.56MiB eta=484h37m45.071s
Jan 14 15:30:01 mon02.ethdevops.io geth WARN [01-14|14:30:01.720] Unexpected storage ranges packet peer=61673c82 reqid=136276793173600161
Jan 14 15:30:02 mon02.ethdevops.io geth INFO [01-14|14:30:02.206] State sync in progress synced=0.27% state=241.60MiB accounts=310233@58.65MiB slots=1269959@170.20MiB codes=4394@12.75MiB eta=468h5m37.166s
Jan 14 15:30:02 mon02.ethdevops.io geth WARN [01-14|14:30:02.442] Unexpected storage ranges packet peer=61673c82 reqid=4800569686397811391
Jan 14 15:30:16 mon02.ethdevops.io geth INFO [01-14|14:30:16.619] Imported new block headers count=2 elapsed=5.588ms number=11653747 hash="de47de…45b782"
Jan 14 15:30:17 mon02.ethdevops.io geth panic: runtime error: invalid memory address or nil pointer dereference
Jan 14 15:30:17 mon02.ethdevops.io geth [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcea28d]
Jan 14 15:30:17 mon02.ethdevops.io geth goroutine 177681 [running]:
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).processStorageResponse(0xc0001d0240, 0xc0123d7380)
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:1667 +0x6cd
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).Sync(0xc0001d0240, 0x5adaf56a2b368f2a, 0xd1d88311a54af9e9, 0xe744732bd26fc4dc, 0xec7a40fe5afd4f66, 0xc01e41eea0, 0x0, 0x0)
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:601 +0x94e
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/downloader.(*stateSync).run(0xc00d830d20)
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/downloader/statesync.go:318 +0x87
Jan 14 15:30:17 mon02.ethdevops.io geth created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).runStateSync
Jan 14 15:30:17 mon02.ethdevops.io geth github.com/ethereum/go-ethereum/eth/downloader/statesync.go:114 +0x1ef 

```
The remote peer `61673c82` was running `d13c59fef0926af0ef0cff0a2e793f95d46442f0` (master) , fully in sync.

**Comment by holiman** [comment]
Fixed in #22179
