### ISSUE TITLE
Getting Socket timeout issue from Node

### ISSUE THREAD

**Issue by Jorgeadverd** [ethereum/go-ethereum#22194]
Hi There,

I hope you are doing well,

After sync complete we get success transaction 2-3 times and without any changes on Node or code we start getting continues socket timeout, we have check all the connectivity and telnet also working fine.

Kindly help us to know what should we take next setup for this issue, also we have upgraded the required web3J as confirmed by web3j community.

```
 Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1119-aws x86_64)

instance: Geth/v1.9.13-stable-cbc4ac26/linux-amd64/go1.14.2
at block: 11687156 (Tue Jan 19 2021 17:40:37 GMT+0000 (UTC))
 datadir: /root/.ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 rpc:1.0 txpool:1.0 web3:1.0
```

#### Expected to have success all transaction to node to Mainnet network.
```
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
```
Many thanks in advance.

**Comment by ligi** [comment]
wondering why this is a geth issue and not a web3j issue

**Comment by ligi** [comment]
Which method are you calling? Do you change timeouts - or do you know what the default is
