### ISSUE TITLE
Bug reported installing on 10.8.5 using homebrew

### ISSUE THREAD

**Issue by smileymi6** [ethereum/go-ethereum#2243]
Tried to install on 10.8.5 using brew as suggested. 
```
brew tap ethereum/ethereum
brew install ethereum
```
and got the following error

```
Error: undefined method `bottle' for #<SoftwareSpec:0x101c12738>
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Formula/ethereum.rb:17
/usr/local/Library/Homebrew/formula.rb:707:in `instance_eval'
/usr/local/Library/Homebrew/formula.rb:707:in `devel'
/usr/local/Library/Formula/ethereum.rb:16
/usr/local/Library/Homebrew/formulary.rb:47:in `require'
/usr/local/Library/Homebrew/formulary.rb:47:in `klass'
/usr/local/Library/Homebrew/formulary.rb:97:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:182:in `factory'
/usr/local/Library/Homebrew/formula.rb:433:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:40:in `install'
/usr/local/Library/brew.rb:107:in `send'
/usr/local/Library/brew.rb:107
```
Cheers.

**Comment by smileymi6** [comment]
Probably should have created the issue on the Homebrew page as suggested.
