### ISSUE TITLE
Stuck at "Allocated cache and file handles" and SEGFAULT

### ISSUE THREAD

**Issue by elsampsa** [ethereum/go-ethereum#22440]
#### System information

Geth version: `1.9.25`
OS & Version: Linux
Commit hash : N/A

#### Expected behaviour

When started, geth should inform me that it's trying to find peers

#### Actual behaviour

The last log line says: "Allocated cache and file handles".
After that, geth gets complete stuck.  JS console doesn't work (it can't find the .ipc file).

I removed the "./ethereum/geth/LOCK" file & and cleaned the ".ethereum/geth/ethash/" directory before starting geth.  Doesn't help.

Interestingly, after I stop geth in a clean way (the log tells me "Stopped Ethereum go client"), the "LOCK" file persists.

#### Steps to reproduce the behaviour

Dirty-stop geth a few times

#### Backtrace

**UPDATE** 

Updated to "release/1.10" branch.  Actually I had to wait some time .. that reveals a segfault:
```
maalis 05 23:20:00 sampsa-asus geth[1221]: INFO [03-05|23:20:00.556] Starting Geth on Ethereum mainnet...
maalis 05 23:20:00 sampsa-asus geth[1221]: INFO [03-05|23:20:00.559] Maximum peer count                       ETH=50 LES=0 total=50
maalis 05 23:20:00 sampsa-asus geth[1221]: INFO [03-05|23:20:00.560] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
maalis 05 23:20:00 sampsa-asus systemd[1190]: Started Ethereum go client.
maalis 05 23:20:00 sampsa-asus geth[1221]: INFO [03-05|23:20:00.561] Set global gas cap                       cap=25000000
maalis 05 23:20:00 sampsa-asus geth[1221]: INFO [03-05|23:20:00.561] Allocated trie memory caches             clean=307.00MiB dirty=512.00MiB
maalis 05 23:20:00 sampsa-asus geth[1221]: INFO [03-05|23:20:00.561] Allocated cache and file handles         database=/home/sampsa/.ethereum/geth/chaindata cache=1024.00MiB handles=2048
maalis 05 23:20:05 sampsa-asus geth[1221]: INFO [03-05|23:20:05.065] Opened ancient database                  database=/home/sampsa/.ethereum/geth/chaindata/ancient
maalis 05 23:20:05 sampsa-asus geth[1221]: INFO [03-05|23:20:05.534] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: <nil>, YOLO v3: <nil>, Engine: ethash}"
maalis 05 23:20:11 sampsa-asus geth[1221]: INFO [03-05|23:20:11.885] Disk storage enabled for ethash caches   dir=/home/sampsa/.ethereum/geth/ethash count=3
maalis 05 23:20:11 sampsa-asus geth[1221]: INFO [03-05|23:20:11.885] Disk storage enabled for ethash DAGs     dir=/home/sampsa/.ethash               count=2
maalis 05 23:20:12 sampsa-asus geth[1221]: INFO [03-05|23:20:12.196] Initialising Ethereum protocol           network=1 dbversion=8
maalis 05 23:20:12 sampsa-asus geth[1221]: WARN [03-05|23:20:12.536] Head block missing, resetting chain      hash="77dc58…65f04a"
maalis 05 23:20:12 sampsa-asus geth[1221]: panic: runtime error: invalid memory address or nil pointer dereference
maalis 05 23:20:12 sampsa-asus geth[1221]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9eb734]
maalis 05 23:20:12 sampsa-asus geth[1221]: goroutine 1 [running]:
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/types/block.go:312
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core.(*BlockChain).SetHeadBeyondRoot(0xc0000af900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/blockchain.go:606 +0x1f4
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0xc0000af900, 0x0, 0xc0001c67e0, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/blockchain.go:480 +0x45
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core.(*BlockChain).ResetWithGenesisBlock(0xc0000af900, 0xc0001ac120, 0x0, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/blockchain.go:708 +0x65
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core.(*BlockChain).Reset(0xc0000af900, 0x1399f79, 0x23)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/blockchain.go:701 +0x37
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc0000af900, 0x1344000, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/blockchain.go:435 +0x13fc
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/core.NewBlockChain(0x15b4ec0, 0xc000184620, 0xc0066c94a0, 0x1e7b6e0, 0x15b20c0, 0xc0001c6620, 0x0, 0x0, 0x0, 0x0, ...)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/core/blockchain.go:280 +0x765
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/eth.New(0xc00019cd00, 0xc000437500, 0xc00002e178, 0xc00020aba0, 0xbf1cf0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/eth/backend.go:186 +0xbda
maalis 05 23:20:12 sampsa-asus geth[1221]: github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc00019cd00, 0xc000437500, 0xf, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/cmd/utils/flags.go:1677 +0x20f
maalis 05 23:20:12 sampsa-asus geth[1221]: main.makeFullNode(0xc0001a02c0, 0x13728bb, 0xc000010020, 0xc000167d40)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/cmd/geth/config.go:146 +0x145
maalis 05 23:20:12 sampsa-asus geth[1221]: main.geth(0xc0001a02c0, 0x0, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/cmd/geth/main.go:339 +0xf4
maalis 05 23:20:12 sampsa-asus geth[1221]: gopkg.in/urfave/cli%2ev1.HandleAction(0x1191200, 0x144f2f0, 0xc0001a02c0, 0xc00007c780, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
maalis 05 23:20:12 sampsa-asus geth[1221]: gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00009c340, 0xc0000320a0, 0x5, 0x5, 0x0, 0x0)
maalis 05 23:20:12 sampsa-asus geth[1221]:         gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
maalis 05 23:20:12 sampsa-asus geth[1221]: main.main()
maalis 05 23:20:12 sampsa-asus geth[1221]:         github.com/ethereum/go-ethereum/cmd/geth/main.go:260 +0x55
maalis 05 23:20:12 sampsa-asus systemd[1190]: geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
maalis 05 23:20:12 sampsa-asus systemd[1190]: geth.service: Failed with result 'exit-code'.
```

**Comment by elsampsa** [comment]
Updated to branch "release/1.10".. the same problem persists

**Comment by elsampsa** [comment]
recoving .ethereum folder from a backup disk solved the issue.  Please close this issue if you feel like it.

**Comment by holiman** [comment]
A follow-up question: You seem to be running this as some form of service (systemd?). When you close the process, do you properly allow it to exit gracefully, i.e sending it a `ctrl-c`-like signal and giving it two minutes to exit? 
Otherwise, if you just kill the process, it may cause data corruption.

**Comment by elsampsa** [comment]
Originally it was running as systemd daemon..  maybe that's the problem => systemd gives it not enough time to exit gracefully & the data got corrupted.  I finally recovered blockchain from a backup hdd & updated to 1.10 & started running it from the command line.  Not sure which one of these three things actually fixed the issue..

**Comment by holiman** [comment]
In that case, I'm fairly certain that insufficient time to exit is the culprit. There's a lot of data to be written to disk during exit. I'll close this ticket then. Thanks for confirming!
