### ISSUE TITLE
runtime: memory allocated by OS (2124673024) not in usable range [0x97520000,0x17520000)

### ISSUE THREAD

**Issue by brenzi** [ethereum/go-ethereum#2247]
Hi

geth repeatedly crashes while synching the blockchain on my Ubuntu 14.04
```
runtime: memory allocated by OS (2124673024) not in usable range [0x97520000,0x17520000)
fatal error: out of memory

runtime stack:
runtime.throw(0x890d4a0, 0xd)
        /usr/lib/go/src/runtime/panic.go:527 +0x7f
runtime.largeAlloc(0xcdc9, 0x1, 0xa6d38cc0)
        /usr/lib/go/src/runtime/malloc.go:747 +0xc3
runtime.mallocgc.func3()
        /usr/lib/go/src/runtime/malloc.go:634 +0x30
runtime.systemstack(0x97544000)
        /usr/lib/go/src/runtime/asm_386.s:267 +0x57
runtime.mstart()
        /usr/lib/go/src/runtime/proc1.go:674

goroutine 11805 [running]:
runtime.systemstack_switch()
        /usr/lib/go/src/runtime/asm_386.s:222 fp=0xa6d38bf4 sp=0xa6d38bf0
runtime.mallocgc(0xcdc9, 0x8728b20, 0x1, 0xb7416001)
        /usr/lib/go/src/runtime/malloc.go:635 +0x77f fp=0xa6d38c5c sp=0xa6d38bf4
runtime.newarray(0x8728b20, 0xcdc9, 0x3)
        /usr/lib/go/src/runtime/malloc.go:777 +0xbc fp=0xa6d38c80 sp=0xa6d38c5c
runtime.makeslice(0x8718560, 0xcc5c, 0x0, 0xcdc9, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/runtime/slice.go:32 +0x180 fp=0xa6d38cc0 sp=0xa6d38c80
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get(0x97530b00, 0xcc5c, 0x0, 0x0, 0x0)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:152 +0x8d9 fp=0xa6d38d38 sp=0xa6d38cc0
github.com/syndtr/goleveldb/leveldb/table.(*Reader).readRawBlock(0x9d330fa0, 0x1fcb00, 0x0, 0x9a2d, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:583 +0x612 fp=0xa6d38e00 sp=0xa6d38d38
github.com/syndtr/goleveldb/leveldb/table.(*Reader).readBlock(0x9d330fa0, 0x1fcb00, 0x0, 0x9a2d, 0x0, 0x1, 0xa6d38e01, 0x0, 0x0)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:599 +0x58 fp=0xa6d38e5c sp=0xa6d38e00
github.com/syndtr/goleveldb/leveldb/table.(*Reader).readBlockCached.func1(0x99599218, 0x0, 0x0)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:623 +0x4e fp=0xa6d38e94 sp=0xa6d38e5c
github.com/syndtr/goleveldb/leveldb/cache.(*Cache).Get(0x976953e0, 0x40e3, 0x0, 0x1fcb00, 0x0, 0xa6d38f6c, 0x0)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/cache/cache.go:385 +0x1b0 fp=0xa6d38ee0 sp=0xa6d38e94
github.com/syndtr/goleveldb/leveldb/cache.(*CacheGetter).Get(0x991d6e50, 0x1fcb00, 0x0, 0xa6d38f6c, 0x86af9748)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/cache/cache.go:56 +0x49 fp=0xa6d38f00 sp=0xa6d38ee0
github.com/syndtr/goleveldb/leveldb/table.(*Reader).readBlockCached(0x9d330fa0, 0x1fcb00, 0x0, 0x9a2d, 0x0, 0x80c0101, 0xa6d38fc0, 0x0, 0x0, 0x0, ...)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:628 +0xd7 fp=0xa6d38f90 sp=0xa6d38f00
github.com/syndtr/goleveldb/leveldb/table.(*Reader).getIndexBlock(0x9d330fa0, 0x8af7601, 0x9d330fa0, 0x0, 0x0, 0x0, 0x0)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:708 +0x66 fp=0xa6d38fc0 sp=0xa6d38f90
github.com/syndtr/goleveldb/leveldb/table.(*Reader).find(0x9d330fa0, 0x98891a00, 0x35, 0x35, 0x889b701, 0x0, 0x8451600, 0x0, 0x0, 0x0, ...)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:821 +0x126 fp=0xa6d39060 sp=0xa6d38fc0
github.com/syndtr/goleveldb/leveldb/table.(*Reader).Find(0x9d330fa0, 0x98891a00, 0x35, 0x35, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:888 +0x82 fp=0xa6d390ac sp=0xa6d39060
github.com/syndtr/goleveldb/leveldb.(*tOps).find(0x976b2f40, 0xa1951950, 0x98891a00, 0x35, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:382 +0x183 fp=0xa6d39114 sp=0xa6d390ac
github.com/syndtr/goleveldb/leveldb.(*version).get.func1(0x2, 0xa1951950, 0x2d)
        /home/brenzi/go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/version.go:167 +0x4a0 fp=0xa6d391d4 sp=0xa6d39114
```

this happened with the following version of geth

```
Geth
Version: 1.4.0-unstable
Git Commit: f8d98f7fcd08bd2eff36d5366ac2a14b52255d57
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
```

My system:

```
Intel(R) Pentium(R) CPU G850 @ 2.90GHz
8GB RAM
```

**Comment by karalabe** [comment]
Any particular reason you're running the 32 bit version of Geth? 32 bit programs can only use 2GB memory ever, so that's why you are hitting the limits. @fjl is working on getting the memory consumption down. What flags are you running Geth with?

**Comment by brenzi** [comment]
I've built geth from source without configuring anything. My ubuntu is 32 bit:

`Linux blackbox 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:28:41 UTC 2015 i686 i686 i686 GNU/Linux`

I'm running geth without any flags. To get the above message, I called it like this:
`geth > geth.log 2>&1`

can you tell me what to to do? I guess I can't run a 64bit application having a 32bit kernel, right?

**Comment by obscuren** [comment]
We are aware of a memory issue and @fjl is currently working on this.

**Comment by fjl** [comment]
This should be fixed in geth 1.3.4, which was just released.

**Comment by fjl** [comment]
I'll close this now because I'm pretty sure that it is resolved in a released version. Please reopen if it happens again.

**Comment by jordanmack** [comment]
I started getting this same `memory allocated by OS not in usable range` error today.

Geth version: 1.5.0-unstable
Geth options: --port 30304 --nat upnp --support-dao-fork

OS version: Ubuntu 16.04.1 32-bit

**Comment by jordanmack** [comment]
The newest snapshot seems to have fixed the issue.

`ethereum/xenial,now 1.5.0+149SNAPSHOT20161006163709xenial-0ubuntu1 i386 [installed]`
