### ISSUE TITLE
Puppeth nil point dereference

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#22622]
I deployed an ethstats module with nginx to network A at port P, then tried to deploy another ethstats module with nginx to network B at port P. This failed, so I went back to network A and tore those down. I then went back to B to tear down fail nginx deployment and received the follow exception:

Log:
```
What would you like to do? (default = stats)
 1. Show network stats
 2. Configure new genesis
 3. Manage tracked machines
 4. Manage network components
> 4

 1. Tear down Nginx on quilt.link
 2. Deploy new network component
> 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9766f2]

goroutine 1 [running]:
main.(*sshClient).Run(0x0, 0xc000150060, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum/cmd/puppeth/ssh.go:203 +0x52
main.tearDown(0x0, 0xc00029c450, 0x6, 0xabd617, 0x5, 0x1, 0x1, 0x21, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/cmd/puppeth/module.go:114 +0xea
main.(*wizard).manageComponents(0xc0001f0080)
        github.com/ethereum/go-ethereum/cmd/puppeth/wizard_network.go:144 +0x797
main.(*wizard).run(0xc0001f0080)
        github.com/ethereum/go-ethereum/cmd/puppeth/wizard_intro.go:163 +0xcee
main.runWizard(0xc0001a89a0, 0x3, 0xe780a0)
        github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:63 +0x2b1
gopkg.in/urfave/cli%2ev1.HandleAction(0x9f6fa0, 0xaf7e38, 0xc0001a89a0, 0xc000072720, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0001b9040, 0xc0000981b0, 0x1, 0x1, 0x0, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
        github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:54 +0x24d
```

**Comment by holiman** [comment]
`puppeth` is removed as of https://github.com/ethereum/go-ethereum/pull/26581. Closing puppeth-related tickets.
