### ISSUE TITLE
eth/downloader: index allocation went beyond available resultCache space

### ISSUE THREAD

**Issue by paul07481** [ethereum/go-ethereum#2264]
I have just downloaded the latest geth client and started to sync with the testnet. I got a hard to reproduce bug see below. Hope it helps. I'm running 64 bit Windows 10 Pro:

```
I0226 13:35:40.549677   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 9 txs in 1.4245174s. #198359 [4744047b / a0011a2b]
I0226 13:35:41.472225   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 4 txs in 916.5422ms. #198615 [d01c0d2b / 3dd65fbc]
I0226 13:35:42.290232   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 4 txs in 812.0006ms. #198871 [5fd0145a / 684cd43e]
I0226 13:35:43.497252   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 10 txs in 1.20152s. #199127 [4c574bea / 05c140db]
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues
index allocation went beyond available resultCache space
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:585
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/common/debug.go:33 (0x539abf)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:585 (0x8cccd8)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:536 (0x8cbe76)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1280 (0x8d3129)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1466 (0x8c1698)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1279 (0x8bfb46)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:417 (0x8d1ee2)
D:/builds/geth_win32/build-go-win-master/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:438 (0x8d20df)
c:/go/src/runtime/asm_amd64.s:1696 (0x49b271)
#### BUG! PLEASE REPORT ####
I0226 13:35:44.354259   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 4 txs in 842.0071ms. #199383 [cb721a8e / f2f7c38e]
I0226 13:35:45.185260   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 6 txs in 824.5013ms. #199639 [2b38f1fe / 13864f5f]
I0226 13:35:46.043258   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 11 txs in 853.4993ms. #199895 [b558d237 / 53b2edcb]
I0226 13:35:46.679259   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 8 txs in 631.4994ms. #200151 [5b940bd5 / 99f645e9]
I0226 13:35:46.794759   68828 blockchain.go:1243] imported 48 block(s) (0 queued 0 ignored) including 0 txs in 110.5005ms. #200199 [108f4c7c / 18b3e8d1]
I0226 13:35:49.401404   68828 blockchain.go:1243] imported 219 block(s) (0 queued 0 ignored) including 11 txs in 824.0285ms. #200418 [b9103dbd / ae954d14]
I0226 13:35:56.415110   68828 blockchain.go:1243] imported 256 block(s) (0 queued 0 ignored) including 22 txs in 7.0027072s. #200674 [24576ae6 / 9ae19cd0]
```

**Comment by obscuren** [comment]
Thanks for the report. @fjl you've added this one. Can you remember? https://github.com/ethereum/go-ethereum/blame/develop/eth/downloader/queue.go#L586

**Comment by obscuren** [comment]
@fjl ping

**Comment by fjl** [comment]
Sorry, I only got to it now. I added the call to `common.Report` together with @karalabe because this should usually not happen, but we didn't want to use `panic`. The scheduling logic is non-trivial and I'm can't think of a situation in which it could possibly happen.

**Comment by karalabe** [comment]
Yeah, I was pondering about this. But we've managed to encounter it for the first time in months after being added so it's on a very weird code path. I don't think we'll be able to debug it unless we can cat a full downloader log dump that lead to this.

**Comment by niarbeht** [comment]
Dunno if this will help.  Judging by how you guys say something about needing a full downloader log dump, I'm going to guess this won't help.
```
INFO [07-10|10:50:23] Imported new block receipts              count=10   elapsed=2.295ms   number=576536 hash=16b2f8…5bf200 ignored=0
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues
index allocation went beyond available resultCache space
/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:491
goroutine 46167 [running]:
runtime/debug.Stack(0x6d, 0x0, 0x0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/ethereum/go-ethereum/common.Report(0xc42b6997a0, 0x1, 0x1)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x232
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc42000b200, 0xc42046c900, 0x100, 0xc43570c990, 0xc420224500, 0xc43570c9c0, 0xc43570c9f0, 0xf5adc0, 0xc433052a40, 0xc42b699880, ...)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:491 +0x86e
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveReceipts(0xc42000b200, 0xc42046c900, 0x100, 0x0, 0xc42046c900, 0x0, 0x0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:455 +0xf4
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveReceipts-fm(0xc42046c900, 0x100, 0x18, 0x18, 0x2, 0x2)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:927 +0x3e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc4201581e0, 0x16c7960, 0xc4201ff170, 0xc4204d6cc0, 0xc426e8b290, 0xc42005d180, 0xc42b699e90, 0xc42b699ef0, 0xc42b699ee0, 0xc42b699ed0, ...)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1071 +0x784
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchReceipts(0xc4201581e0, 0x67086, 0xc42057a790, 0xc4392192c0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:928 +0x3da
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func5(0x8ca7980e00000008, 0xf5ccc8)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:448 +0x37
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc441da96f0, 0xc424301800, 0xc433666f60)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:472 +0x51
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:472 +0xd2
#### BUG! PLEASE REPORT ####
INFO [07-10|10:50:23] Imported new state entries               count=384  flushed=187 elapsed=22.423ms  processed=2262969 pending=29480 retry=0   duplicate=420 unexpected=2613
INFO [07-10|10:50:23] Imported new state entries               count=384  flushed=376 elapsed=6.942ms   processed=2263353 pending=29223 retry=0   duplicate=420 unexpected=2613
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x45ed18]

goroutine 46169 [running]:
github.com/ethereum/go-ethereum/rlp.Encode(0x7f313e412070, 0xc43155cfc0, 0xdd9820, 0xc42173c240, 0x0, 0x0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:92 +0x170
github.com/ethereum/go-ethereum/core/types.rlpHash(0xdd9820, 0xc42173c240, 0x0, 0x0, 0x0, 0x0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:126 +0xe6
github.com/ethereum/go-ethereum/core/types.(*Header).Hash(0xc42173c240, 0x0, 0x0, 0x0, 0x0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:102 +0x62
github.com/ethereum/go-ethereum/eth/downloader.(*queue).WaitResults(0xc42000b200, 0x0, 0x0, 0x0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:355 +0x1e2
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFastSyncContent(0xc4201581e0, 0xc4349c2d80, 0x0, 0x0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1356 +0x116
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func7(0x8, 0xf5ccc8)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:452 +0x33
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc441da96f0, 0xc424301800, 0xc433666fa0)
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:472 +0x51
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/build/geth/src/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:472 +0xd2
```

**Comment by karalabe** [comment]
Closing as it's an ancient bug and most of the downloader was rewritten since.
