### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference Docker container

### ISSUE THREAD

**Issue by StephenTurley** [ethereum/go-ethereum#22681]
#### System information

Geth version: `(DOCKER) ethereum/client-go:latest sha256:6cff4454ce05bbc1e4ab61e8477a8966926b9b71593eff08428f32359a153a60
`
OS & Version: Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
It runs 

#### Actual behaviour
It crashes with the following with nil pointer error

#### Steps to reproduce the behaviour
start the contatiner

#### Backtrace

````
INFO [04-16|00:29:15.285] Starting Geth on Ethereum mainnet...
INFO [04-16|00:29:15.285] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [04-16|00:29:15.288] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-16|00:29:15.288] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [04-16|00:29:15.289] Set global gas cap                       cap=25,000,000
INFO [04-16|00:29:15.289] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [04-16|00:29:15.289] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=2.00GiB handles=524,288
INFO [04-16|00:29:17.156] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient readonly=false
INFO [04-16|00:29:17.174] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, YOLO v3: <nil>, Engine: ethash}"
INFO [04-16|00:29:17.978] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
INFO [04-16|00:29:17.978] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
INFO [04-16|00:29:17.979] Initialising Ethereum protocol           network=1 dbversion=8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x54866b]

goroutine 1 [running]:
math/big.(*Int).QuoRem(0xc0000a1fe0, 0xc0000a1fe0, 0xc0000a10a0, 0x0, 0x0, 0x4281fb)
	math/big/int.go:239 +0x4b
math/big.(*Int).DivMod(0xc0000a1fe0, 0xc0000a1fe0, 0xc0000a10a0, 0x0, 0x5146b1, 0x1bf6840)
	math/big/int.go:301 +0xe5
github.com/ethereum/go-ethereum/log.formatLogfmtBigInt(0xc0000a1fe0, 0x68a10716a51cbf2c, 0x680000c0007e5d20)
	github.com/ethereum/go-ethereum/log/format.go:449 +0x11c
github.com/ethereum/go-ethereum/log.formatLogfmtValue(0x132ea20, 0xc0000a1fe0, 0x1, 0x0, 0x0)
	github.com/ethereum/go-ethereum/log/format.go:346 +0x70
github.com/ethereum/go-ethereum/log.logfmt(0xc0015ca1e0, 0xc000319e80, 0x8, 0x8, 0x0, 0x1)
	github.com/ethereum/go-ethereum/log/format.go:169 +0xf2
github.com/ethereum/go-ethereum/log.TerminalFormat.func1(0xc000342540, 0xc0003247d0, 0xc001872880, 0x32)
	github.com/ethereum/go-ethereum/log/format.go:143 +0x428
github.com/ethereum/go-ethereum/log.formatFunc.Format(0xc00003bff0, 0xc000342540, 0xc000300de0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/log/format.go:68 +0x30
github.com/ethereum/go-ethereum/log.StreamHandler.func1(0xc000342540, 0x10d273e62, 0x1)
	github.com/ethereum/go-ethereum/log/handler.go:43 +0x4f
github.com/ethereum/go-ethereum/log.funcHandler.Log(0xc00052e4b0, 0xc000342540, 0x767500, 0xc0033c6466)
	github.com/ethereum/go-ethereum/log/handler.go:31 +0x30
github.com/ethereum/go-ethereum/log.SyncHandler.func1(0xc000342540, 0x0, 0x0)
	github.com/ethereum/go-ethereum/log/handler.go:57 +0x82
github.com/ethereum/go-ethereum/log.funcHandler.Log(0xc0000a1f40, 0xc000342540, 0x0, 0x28fa20)
	github.com/ethereum/go-ethereum/log/handler.go:31 +0x30
github.com/ethereum/go-ethereum/log.LazyHandler.func1(0xc000342540, 0x7fd5d3c2cda0, 0x0)
	github.com/ethereum/go-ethereum/log/handler.go:299 +0x3a2
github.com/ethereum/go-ethereum/log.funcHandler.Log(0xc000118cc0, 0xc000342540, 0x18639e9, 0x1201b7)
	github.com/ethereum/go-ethereum/log/handler.go:31 +0x30
github.com/ethereum/go-ethereum/log.(*GlogHandler).Log(0xc000154000, 0xc000342540, 0xd8, 0x129a520)
	github.com/ethereum/go-ethereum/log/handler_glog.go:202 +0x60e
github.com/ethereum/go-ethereum/log.(*swapHandler).Log(0xc00007eb20, 0xc000342540, 0x1acc770, 0x163d7d1)
	github.com/ethereum/go-ethereum/log/handler_go14.go:14 +0x82
github.com/ethereum/go-ethereum/log.(*logger).write(0x1bf6280, 0x135bcd5, 0x1f, 0x3, 0xc0033c6ee0, 0x8, 0x8, 0x2)
	github.com/ethereum/go-ethereum/log/logger.go:134 +0x27d
github.com/ethereum/go-ethereum/log.Info(...)
	github.com/ethereum/go-ethereum/log/root.go:44
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc0000e3200, 0x130a700, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:467 +0x8f3
github.com/ethereum/go-ethereum/core.NewBlockChain(0x1575968, 0xc0005cc138, 0xc0070becd0, 0x1c04b20, 0x1572c30, 0xc0003422a0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/blockchain.go:280 +0x76b
github.com/ethereum/go-ethereum/eth.New(0xc000308d00, 0xc0000cd100, 0xc000336a18, 0xc000614b68, 0xbcfe30)
	github.com/ethereum/go-ethereum/eth/backend.go:190 +0xc3a
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc000308d00, 0xc0000cd100, 0xf, 0x0)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:1705 +0x20f
main.makeFullNode(0xc0000f6580, 0x133bd2e, 0x1, 0xc0000a1f20)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:146 +0x145
main.geth(0xc0000f6580, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:317 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x11629a0, 0x1417798, 0xc0000f6580, 0xc00010f7a0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000c6b60, 0xc0000320b0, 0xb, 0xb, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:257 +0x55
````

**Comment by liuhuanhui** [comment]
I'm the same mistake. Have you solved it?

**Comment by jackyxie** [comment]
I'm the same mistake.

**Comment by liuhuanhui** [comment]
Don't use the latest version, use the stable version, mine is OK
@jackyxie

**Comment by jackyxie** [comment]
thanks. use stable version is ok now.
@liuhuanhui

**Comment by StephenTurley** [comment]
Yup I switched to the stable version and it seems to be good. is `latest` intended to be a development build?

**Comment by karalabe** [comment]
I broke the dev branch for 8 hours. Please pull a fresh branch, it works :)
