### ISSUE TITLE
Factor out rpc.Client as interface to console 

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/go-ethereum#22890]
I want to reuse console in my own project but making a concrete rpc.Client is kinda annoying and becoming lots of trouble - can the project please factor out the needs of rpc.Client as an interface

**Comment by karalabe** [comment]
What's wrong with `rpc.Client`? Why not just use that directly?

**Comment by fxfactorial** [comment]
Because it’s too tied with the rest of the node stack - I tried having the client use a Socket pipe file and just read write off that but it was unsuccessful as well

**Comment by karalabe** [comment]
`rpc.Dial("/path/to/socket")`?

**Comment by fxfactorial** [comment]
yes - here's what happening

```go
var (
	pipeFile    = "pipe.log"
)

func scheduleWrite() {
	fmt.Println("start schedule writing.")
	f, err := os.OpenFile(pipeFile, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0777)
	if err != nil {
		log.Fatalf("error opening file: %v", err)
	}
	i := 0
	for {
		fmt.Println("write string to named pipe file.")
		f.WriteString(fmt.Sprintf("test write times:%d\n", i))
		i++
		time.Sleep(time.Second)
	}
}

```

and elsewhere down

```
		os.Remove(pipeFile)
		err := syscall.Mkfifo(pipeFile, 0666)
		if err != nil {
			return err
		}

		go scheduleWrite()
		fmt.Println("open a named pipe file for read.")
		file, err := os.OpenFile(pipeFile, os.O_CREATE, os.ModeNamedPipe)
		if err != nil {
			return err
		}

		reader := bufio.NewReader(file)

		go func() {
			for {
				line, err := reader.ReadBytes('\n')
				if err == nil {
					fmt.Print("load string:" + string(line))
				}
			}
		}()

		cl, err := rpc.Dial(pipeFile)

		if err != nil {
			fmt.Println(err)
		}

		config := console.Config{
			DataDir: *dbPath,
			DocRoot: "",
			Client:  cl,
			Preload: nil,
		}

		console, err := console.New(config)
		if err != nil {
			utils.Fatalf("Failed to start the JavaScript console: %v", err)
		}
		defer console.Stop(false)

		// Otherwise print the welcome screen and enter interactive mode
		console.Welcome()
		console.Interactive()

	}
```


but it explodes with 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x891b8b]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/rpc.(*Client).nextID(...)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/rpc/client.go:237
github.com/ethereum/go-ethereum/rpc.(*Client).newMessage(0x0, 0xeddcac, 0xb, 0x0, 0x0, 0x0, 0xf4ac08, 0xc0004e7eb0, 0x562c8b)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/rpc/client.go:469 +0x2b
github.com/ethereum/go-ethereum/rpc.(*Client).CallContext(0x0, 0x1032988, 0xc003433ec0, 0xd6d060, 0xc002e811d0, 0xeddcac, 0xb, 0x0, 0x0, 0x0, ...)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/rpc/client.go:295 +0x108
github.com/ethereum/go-ethereum/rpc.(*Client).SupportedModules(0x0, 0x0, 0x0, 0x0)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/rpc/client.go:247 +0xfe
github.com/ethereum/go-ethereum/console.(*Console).initExtensions(0xc00013f9d0, 0xc00112b260, 0x0)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/console/console.go:190 +0x46
github.com/ethereum/go-ethereum/console.(*Console).init(0xc00013f9d0, 0x0, 0x0, 0x0, 0x0, 0x30)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/console/console.go:121 +0x137
github.com/ethereum/go-ethereum/console.New(0x7ffed7cbbeb4, 0x36, 0x0, 0x0, 0x0, 0xed5264, 0x2, 0x1038428, 0xc000690000, 0x1022200, ...)
	/home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/console/console.go:105 +0x25b
main.program(0x0, 0x0)
	/home/edgar/Repos/run-evm-code/main.go:155 +0x11ae
main.main()
	/home/edgar/Repos/run-evm-code/main.go:198 +0x8a
```

not sure why it needs to immediately start querying the backend 

I want to have the miminial viable client -, hence i want the interface

**Comment by fxfactorial** [comment]
@karalabe ping - wondering your thoughts
