### ISSUE TITLE
unexpected fault address 0x7f638fc9d000

### ISSUE THREAD

**Issue by isamuelson** [ethereum/go-ethereum#23022]
dockerfile:
version: "2"
services:
  # ethereum 1 node
  eth1-node:
    image: ethereum/client-go
    container_name: eth1-node 
    command: "geth --ipcpath /geth.ipc --mainnet --cache=4096"
    networks:
    - ethereum_network
    volumes:
    - eth1-node-data:/root/.ethereum
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 8G
        limits:
          cpus: '4'
          memory: 8G
          
volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  eth1-node-data:
#    driver: local
    driver: azure_file
    driver_opts: 
      share_name: eth1-node-data
      storage_account_name: ethereumstorageaccount

networks:
  ethereum_network:
    external: true

-------

command: 
docker compose up 

// the docket context is on azure using azure containers
-----

LOGS:

INFO [06-09|11:19:09.926] Imported new block headers               count=768 elapsed=58.198ms  number=960 hash=916910..1d0e2a age=5y11mo1w
INFO [06-09|11:19:10.179] Imported new block receipts              count=2   elapsed=310.302ms number=2   hash=b495a1..4698c9 age=5y11mo1w size=1.69KiB
INFO [06-09|11:19:10.286] Imported new block receipts              count=1   elapsed=107.127ms number=3   hash=3d6122..8cf741 age=5y11mo1w size=1.09KiB
unexpected fault address 0x7f638fc9d000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f638fc9d000 pc=0xa37556]

goroutine 1906 [running]:
runtime.throw(0x1368e71, 0x5)
        runtime/panic.go:1117 +0x72 fp=0xc007eb8b68 sp=0xc007eb8b38 pc=0x452df2
runtime.sigpanic()
        runtime/signal_unix.go:731 +0x2c8 fp=0xc007eb8ba0 sp=0xc007eb8b68 pc=0x46a6c8
github.com/ethereum/go-ethereum/consensus/ethash.memoryMap(0xc006fe9040, 0x36, 0xc006fe9000, 0x36, 0x0, 0x0, 0x407f32, 0x407f32, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:88 +0x116 fp=0xc007eb8c50 sp=0xc007eb8ba0 pc=0xa37556
github.com/ethereum/go-ethereum/consensus/ethash.memoryMapAndGenerate(0xc006fe9040, 0x36, 0x101fcc0, 0xc00015b200, 0xc007eb8ea8, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:162 +0x3f8 fp=0xc007eb8d18 sp=0xc007eb8c50 pc=0xa37e18
github.com/ethereum/go-ethereum/consensus/ethash.(*cache).generate.func1()
        github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:268 +0x628 fp=0xc007eb8f10 sp=0xc007eb8d18 pc=0xa403c8
sync.(*Once).doSlow(0xc0038b03b0, 0xc0002f4f70)
        sync/once.go:68 +0xec fp=0xc007eb8f60 sp=0xc007eb8f10 pc=0x4a630c
sync.(*Once).Do(...)
        sync/once.go:59
github.com/ethereum/go-ethereum/consensus/ethash.(*cache).generate(0xc0038b0370, 0xc0048da6c0, 0x1b, 0x3, 0xc000040000)
        github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:234 +0xac fp=0xc007eb8fb8 sp=0xc007eb8f60 pc=0xa388cc
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc007eb8fc0 sp=0xc007eb8fb8 pc=0x48cfe1
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).cache
        github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:574 +0x139

**Comment by karalabe** [comment]
Do you have enough space on your partition? Does it have permissions / support memory mapping files?
