### ISSUE TITLE
findAncestorBinarySearch causes a panic

### ISSUE THREAD

**Issue by voronindev** [ethereum/go-ethereum#23224]
#### System information

Geth version: `v1.10.5-stable-33ca98ec`
OS & Version: `linux-amd64`

#### Expected behaviour
Works fine - finding peers, downloading recent blocks

#### Actual behaviour
Couldn't launch, panics always

#### Steps to reproduce the behaviour
Using following command:
`command: --gpo.blocks 10 --gpo.percentile 90 --ropsten --cache 2000 --syncmode "full" --nousb --http.api debug,eth,web3,personal,net --graphql --graphql.vhosts=* --http --http.addr "0.0.0.0" --http.vhosts="*" --ws --ws.addr "0.0.0.0" --ws.origins="*" --port 30303 --ws.port 8546 --http.port 8545`
Note: we noticed the lack of SSD memory, and thought thats the problem. After extending, the problem stays. This problem first appears at `geth v1.10.1`, after updating to `geth v1.10.5` we have the same behaviour.

#### Backtrace

````
geth_1  | INFO [07-16|09:34:35.125] Starting Geth on Ropsten testnet... 
geth_1  | INFO [07-16|09:34:35.129] Maximum peer count                       ETH=50 LES=0 total=50
geth_1  | INFO [07-16|09:34:35.131] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
geth_1  | WARN [07-16|09:34:35.131] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
geth_1  | INFO [07-16|09:34:35.139] Set global gas cap                       cap=50,000,000
geth_1  | INFO [07-16|09:34:35.140] Allocated trie memory caches             clean=300.00MiB dirty=500.00MiB
geth_1  | INFO [07-16|09:34:35.141] Allocated cache and file handles         database=/root/.ethereum/ropsten/geth/chaindata cache=1000.00MiB handles=524,288
geth_1  | INFO [07-16|09:34:36.441] Opened ancient database                  database=/root/.ethereum/ropsten/geth/chaindata/ancient readonly=false
geth_1  | INFO [07-16|09:34:36.511] Persisted trie from memory database      nodes=355 size=50.41KiB time=1.2949ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
geth_1  | INFO [07-16|09:34:36.512] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846, Muir Glacier: 7117117, Berlin: 9812189, London: 10499401, Engine: ethash}"
geth_1  | INFO [07-16|09:34:37.211] Disk storage enabled for ethash caches   dir=/root/.ethereum/ropsten/geth/ethash count=3
geth_1  | INFO [07-16|09:34:37.211] Disk storage enabled for ethash DAGs     dir=/root/.ethash                       count=2
geth_1  | INFO [07-16|09:34:37.226] Initialising Ethereum protocol           network=3 dbversion=8
geth_1  | INFO [07-16|09:34:38.325] Loaded most recent local header          number=10,457,262 hash=084563..9ceef5 td=33,813,146,509,283,441 age=4w21h12m
geth_1  | INFO [07-16|09:34:38.325] Loaded most recent local full block      number=0          hash=419410..ca4a2d td=1,048,576              age=52y3mo2w
geth_1  | INFO [07-16|09:34:38.326] Loaded most recent local fast block      number=10,457,262 hash=084563..9ceef5 td=33,813,146,509,283,441 age=4w21h12m
geth_1  | INFO [07-16|09:34:38.330] Loaded last fast-sync pivot marker       number=10,281,992
geth_1  | WARN [07-16|09:34:38.341] Enabling snapshot recovery               chainhead=0 diskbase=10,586,955
geth_1  | WARN [07-16|09:34:38.351] Loaded snapshot journal                  diskroot=ea6ae4..7d051e diffs=unmatched
geth_1  | WARN [07-16|09:34:38.351] Snapshot is not continuous with chain    snaproot=ea6ae4..7d051e chainroot=217b0b..62b77b
geth_1  | INFO [07-16|09:34:38.351] Loaded local transaction journal         transactions=0 dropped=0
geth_1  | INFO [07-16|09:34:38.352] Regenerated local transaction journal    transactions=0 accounts=0
geth_1  | WARN [07-16|09:34:38.352] Switch sync mode from full sync to fast sync 
geth_1  | INFO [07-16|09:34:38.369] Allocated fast sync bloom                size=1000.00MiB
geth_1  | INFO [07-16|09:34:38.381] Gasprice oracle is ignoring threshold set threshold=2
geth_1  | WARN [07-16|09:34:38.381] Old unclean shutdowns found              count=1029
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:13:23+0000 age=21m15s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:16:34+0000 age=18m4s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:18:59+0000 age=15m39s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:19:32+0000 age=15m6s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:21:06+0000 age=13m32s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:23:36+0000 age=11m2s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:25:07+0000 age=9m31s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:27:31+0000 age=7m7s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:29:33+0000 age=5m5s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:30:45+0000 age=3m53s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:31:50+0000 age=2m48s
geth_1  | INFO [07-16|09:34:38.389] Starting peer-to-peer node               instance=Geth/v1.10.5-stable-33ca98ec/linux-amd64/go1.16.6
geth_1  | INFO [07-16|09:34:38.716] New local node record                    seq=10267 id=bc62b4ffb0a676d2 ip=127.0.0.1 udp=30303 tcp=30303
geth_1  | INFO [07-16|09:34:38.717] Started P2P networking                   self=enode://983f856f18a8170b89e828fdec190870dd883024801f8953716e38131dc8a6388b6814e12a1c11ad172a5539b1aea638b69ee367ededb0e431bc38c993b958ca@127.0.0.1:30303
geth_1  | INFO [07-16|09:34:38.719] IPC endpoint opened                      url=/root/.ethereum/ropsten/geth.ipc
geth_1  | INFO [07-16|09:34:38.720] HTTP server started                      endpoint=[::]:8545 prefix= cors= vhosts=*
geth_1  | INFO [07-16|09:34:38.720] GraphQL enabled                          url=http://[::]:8545/graphql
geth_1  | INFO [07-16|09:34:38.720] GraphQL UI enabled                       url=http://[::]:8545/graphql/ui
geth_1  | INFO [07-16|09:34:38.720] WebSocket enabled                        url=ws://[::]:8546
geth_1  | INFO [07-16|09:34:46.380] Initializing state bloom                 items=2,212,352 errorrate=0.000 elapsed=8.000s
geth_1  | INFO [07-16|09:34:49.133] Looking for peers                        peercount=0 tried=27 static=0
geth_1  | INFO [07-16|09:34:51.145] Block synchronisation started 
geth_1  | WARN [07-16|09:34:51.145] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
geth_1  | INFO [07-16|09:34:51.250] New local node record                    seq=10268 id=bc62b4ffb0a676d2 ip=116.203.117.125 udp=1614  tcp=30303
geth_1  | INFO [07-16|09:34:54.380] Initializing state bloom                 items=5,503,851 errorrate=0.000 elapsed=16.000s
geth_1  | INFO [07-16|09:34:59.133] Looking for peers                        peercount=0 tried=29 static=0
geth_1  | INFO [07-16|09:35:02.380] Initializing state bloom                 items=8,171,468 errorrate=0.000 elapsed=24.000s
geth_1  | INFO [07-16|09:35:10.133] Looking for peers                        peercount=0 tried=24 static=0
geth_1  | INFO [07-16|09:35:10.381] Initializing state bloom                 items=11,054,838 errorrate=0.000 elapsed=32.001s
geth_1  | INFO [07-16|09:35:18.381] Initializing state bloom                 items=13,919,630 errorrate=0.000 elapsed=40.001s
geth_1  | INFO [07-16|09:35:20.134] Looking for peers                        peercount=0 tried=35 static=0
geth_1  | INFO [07-16|09:35:26.381] Initializing state bloom                 items=16,809,408 errorrate=0.000 elapsed=48.001s
geth_1  | INFO [07-16|09:35:30.465] Looking for peers                        peercount=0 tried=27 static=0
geth_1  | INFO [07-16|09:35:34.382] Initializing state bloom                 items=19,827,784 errorrate=0.000 elapsed=56.002s
geth_1  | INFO [07-16|09:35:40.466] Looking for peers                        peercount=0 tried=36 static=0
geth_1  | INFO [07-16|09:35:42.382] Initializing state bloom                 items=22,755,785 errorrate=0.000 elapsed=1m4.002s
geth_1  | INFO [07-16|09:35:50.382] Initializing state bloom                 items=25,732,713 errorrate=0.000 elapsed=1m12.002s
geth_1  | INFO [07-16|09:35:50.466] Looking for peers                        peercount=0 tried=24 static=0
geth_1  | INFO [07-16|09:35:58.384] Initializing state bloom                 items=28,528,212 errorrate=0.000 elapsed=1m20.004s
geth_1  | INFO [07-16|09:36:00.466] Looking for peers                        peercount=0 tried=28 static=0
geth_1  | WARN [07-16|09:36:00.845] Dropping unsynced node during sync       id=2a7a6163d539c3a8 conn=dyndial addr=3.231.157.25:30303 type=Geth/v1.10.4-stable-...
geth_1  | INFO [07-16|09:36:06.387] Initializing state bloom                 items=31,016,698 errorrate=0.000 elapsed=1m28.007s
geth_1  | WARN [07-16|09:36:09.105] Served admin_peers                       conn=193.56.29.33:53106 reqid=3 t="34.094µs" err="the method admin_peers does not exist/is not available"
geth_1  | WARN [07-16|09:36:09.105] Served parity_netPeers                   conn=193.56.29.33:53108 reqid=3 t="36.949µs" err="the method parity_netPeers does not exist/is not available"
geth_1  | INFO [07-16|09:36:11.133] Looking for peers                        peercount=0 tried=30 static=0
geth_1  | INFO [07-16|09:36:14.387] Initializing state bloom                 items=33,900,871 errorrate=0.000 elapsed=1m36.007s
geth_1  | INFO [07-16|09:36:21.139] Looking for peers                        peercount=0 tried=39 static=0
geth_1  | INFO [07-16|09:36:22.388] Initializing state bloom                 items=36,666,733 errorrate=0.000 elapsed=1m44.008s
geth_1  | WARN [07-16|09:36:24.066] Served parity_netPeers                   conn=193.56.29.33:39116 reqid=3 t="30.929µs" err="the method parity_netPeers does not exist/is not available"
geth_1  | WARN [07-16|09:36:24.067] Served admin_peers                       conn=193.56.29.33:39112 reqid=3 t="32.22µs"  err="the method admin_peers does not exist/is not available"
geth_1  | INFO [07-16|09:36:30.388] Initializing state bloom                 items=39,617,709 errorrate=0.000 elapsed=1m52.008s
geth_1  | INFO [07-16|09:36:31.152] Looking for peers                        peercount=0 tried=39 static=0
geth_1  | INFO [07-16|09:36:31.644] Got interrupt, shutting down... 
geth_1  | INFO [07-16|09:36:31.647] HTTP server stopped                      endpoint=[::]:8545
geth_1  | INFO [07-16|09:36:31.648] HTTP server stopped                      endpoint=[::]:8546
geth_1  | INFO [07-16|09:36:31.648] IPC endpoint closed                      url=/root/.ethereum/ropsten/geth.ipc
geth_1  | INFO [07-16|09:36:31.648] Initialized state bloom                  items=39,990,707 errorrate=0.000 elapsed=1m53.268s
geth_1  | INFO [07-16|09:36:31.649] Deallocated state bloom                  items=39,990,707 errorrate=0.000
geth_1  | INFO [07-16|09:36:31.768] Ethereum protocol stopped 
geth_1  | INFO [07-16|09:36:31.768] Transaction pool stopped 
geth_1  | ERROR[07-16|09:36:31.768] Failed to journal state snapshot         err="snapshot [0x217b0bbcfb72e2d57e28f33cb361b9983513177755dc3f33ce3e7022ed62b77b] missing"
geth_1  | INFO [07-16|09:36:31.769] Writing clean trie cache to disk         path=/root/.ethereum/ropsten/geth/triecache threads=4
geth_1  | INFO [07-16|09:36:32.190] Persisted the clean trie cache           path=/root/.ethereum/ropsten/geth/triecache elapsed=421.159ms
geth_1  | INFO [07-16|09:36:32.190] Blockchain stopped 
geth_1  | INFO [07-16|09:36:59.739] Starting Geth on Ropsten testnet... 
geth_1  | INFO [07-16|09:36:59.742] Maximum peer count                       ETH=50 LES=0 total=50
geth_1  | INFO [07-16|09:36:59.742] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
geth_1  | WARN [07-16|09:36:59.742] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
geth_1  | INFO [07-16|09:36:59.745] Set global gas cap                       cap=50,000,000
geth_1  | INFO [07-16|09:36:59.748] Allocated trie memory caches             clean=300.00MiB dirty=500.00MiB
geth_1  | INFO [07-16|09:36:59.748] Allocated cache and file handles         database=/root/.ethereum/ropsten/geth/chaindata cache=1000.00MiB handles=524,288
geth_1  | INFO [07-16|09:37:00.839] Opened ancient database                  database=/root/.ethereum/ropsten/geth/chaindata/ancient readonly=false
geth_1  | INFO [07-16|09:37:00.891] Persisted trie from memory database      nodes=355 size=50.41KiB time=1.468067ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
geth_1  | INFO [07-16|09:37:00.892] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846, Muir Glacier: 7117117, Berlin: 9812189, London: 10499401, Engine: ethash}"
geth_1  | INFO [07-16|09:37:01.590] Disk storage enabled for ethash caches   dir=/root/.ethereum/ropsten/geth/ethash count=3
geth_1  | INFO [07-16|09:37:01.590] Disk storage enabled for ethash DAGs     dir=/root/.ethash                       count=2
geth_1  | INFO [07-16|09:37:01.600] Initialising Ethereum protocol           network=3 dbversion=8
geth_1  | INFO [07-16|09:37:01.808] Loaded most recent local header          number=10,457,262 hash=084563..9ceef5 td=33,813,146,509,283,441 age=4w21h15m
geth_1  | INFO [07-16|09:37:01.808] Loaded most recent local full block      number=0          hash=419410..ca4a2d td=1,048,576              age=52y3mo2w
geth_1  | INFO [07-16|09:37:01.808] Loaded most recent local fast block      number=10,457,262 hash=084563..9ceef5 td=33,813,146,509,283,441 age=4w21h15m
geth_1  | INFO [07-16|09:37:01.811] Loaded last fast-sync pivot marker       number=10,281,992
geth_1  | WARN [07-16|09:37:01.818] Enabling snapshot recovery               chainhead=0 diskbase=10,586,955
geth_1  | WARN [07-16|09:37:01.824] Loaded snapshot journal                  diskroot=ea6ae4..7d051e diffs=unmatched
geth_1  | WARN [07-16|09:37:01.824] Snapshot is not continuous with chain    snaproot=ea6ae4..7d051e chainroot=217b0b..62b77b
geth_1  | INFO [07-16|09:37:01.824] Loaded local transaction journal         transactions=0 dropped=0
geth_1  | INFO [07-16|09:37:01.825] Regenerated local transaction journal    transactions=0 accounts=0
geth_1  | WARN [07-16|09:37:01.825] Switch sync mode from full sync to fast sync 
geth_1  | INFO [07-16|09:37:01.845] Allocated fast sync bloom                size=1000.00MiB
geth_1  | INFO [07-16|09:37:01.861] Gasprice oracle is ignoring threshold set threshold=2
geth_1  | WARN [07-16|09:37:01.862] Old unclean shutdowns found              count=1030
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:16:34+0000 age=20m27s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:18:59+0000 age=18m2s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:19:32+0000 age=17m29s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:21:06+0000 age=15m55s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:23:36+0000 age=13m25s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:25:07+0000 age=11m54s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:27:31+0000 age=9m30s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:29:33+0000 age=7m28s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:30:45+0000 age=6m16s
geth_1  | WARN [07-16|09:37:01.862] Unclean shutdown detected                booted=2021-07-16T09:31:50+0000 age=5m11s
geth_1  | INFO [07-16|09:37:01.869] Starting peer-to-peer node               instance=Geth/v1.10.5-stable-33ca98ec/linux-amd64/go1.16.6
geth_1  | INFO [07-16|09:37:02.189] New local node record                    seq=10269 id=bc62b4ffb0a676d2 ip=127.0.0.1 udp=30303 tcp=30303
geth_1  | INFO [07-16|09:37:02.190] Started P2P networking                   self=enode://983f856f18a8170b89e828fdec190870dd883024801f8953716e38131dc8a6388b6814e12a1c11ad172a5539b1aea638b69ee367ededb0e431bc38c993b958ca@127.0.0.1:30303
geth_1  | INFO [07-16|09:37:02.193] IPC endpoint opened                      url=/root/.ethereum/ropsten/geth.ipc
geth_1  | INFO [07-16|09:37:02.195] HTTP server started                      endpoint=[::]:8545 prefix= cors= vhosts=*
geth_1  | INFO [07-16|09:37:02.195] GraphQL enabled                          url=http://[::]:8545/graphql
geth_1  | INFO [07-16|09:37:02.195] GraphQL UI enabled                       url=http://[::]:8545/graphql/ui
geth_1  | INFO [07-16|09:37:02.195] WebSocket enabled                        url=ws://[::]:8546
geth_1  | INFO [07-16|09:37:09.856] Initializing state bloom                 items=2,263,793 errorrate=0.000 elapsed=8.000s
geth_1  | INFO [07-16|09:37:12.279] Looking for peers                        peercount=0 tried=23 static=0
geth_1  | INFO [07-16|09:37:17.712] New local node record                    seq=10270 id=bc62b4ffb0a676d2 ip=116.203.117.125 udp=30303 tcp=30303
geth_1  | INFO [07-16|09:37:17.856] Initializing state bloom                 items=5,342,050 errorrate=0.000 elapsed=16.001s
geth_1  | INFO [07-16|09:37:20.952] Block synchronisation started 
geth_1  | WARN [07-16|09:37:20.952] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
geth_1  | INFO [07-16|09:37:22.946] Looking for peers                        peercount=0 tried=32 static=0
geth_1  | INFO [07-16|09:37:25.856] Initializing state bloom                 items=8,191,985 errorrate=0.000 elapsed=24.001s
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xb2200f]
geth_1  | 
geth_1  | goroutine 630 [running]:
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc002084000, 0xc07ff425b0, 0x1, 0xa27785, 0x9e311e, 0x9e311e, 0x0, 0x156ebe0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:966 +0x58f
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc002084000, 0xc07ff425b0, 0xc07ffa2d80, 0xc07ffa2fc0, 0x0, 0x0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:818 +0x3a5
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc002084000, 0xc07ff425b0, 0xf91c0b16dc8b6409, 0xfc39f511e88bc7b0, 0xc72d7fe9e73daae4, 0xdd6117a79ff099a2, 0xc0827525c0, 0x0, 0x0)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:475 +0x517
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc002084000, 0xc07e73c700, 0x40, 0xf91c0b16dc8b6409, 0xfc39f511e88bc7b0, 0xc72d7fe9e73daae4, 0xdd6117a79ff099a2, 0xc0827525c0, 0xc000000001, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:431 +0x3b0
geth_1  | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc002084000, 0xc07e73c700, 0x40, 0xf91c0b16dc8b6409, 0xfc39f511e88bc7b0, 0xc72d7fe9e73daae4, 0xdd6117a79ff099a2, 0xc0827525c0, 0xc000000001, 0x0, ...)
geth_1  |       github.com/ethereum/go-ethereum/eth/downloader/downloader.go:326 +0x8c
geth_1  | github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc000b7d900, 0xc08273a1c0, 0xac90d5, 0xc07e5b2480)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:324 +0x125
geth_1  | github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0013a06f0, 0xc08273a1c0)
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:300 +0x38
geth_1  | created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
geth_1  |       github.com/ethereum/go-ethereum/eth/sync.go:300 +0x76
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
This can only happen if a requested header is not in the DB, you do have quite a bit of unclean shutdowns: 
```
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:13:23+0000 age=21m15s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:16:34+0000 age=18m4s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:18:59+0000 age=15m39s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:19:32+0000 age=15m6s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:21:06+0000 age=13m32s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:23:36+0000 age=11m2s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:25:07+0000 age=9m31s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:27:31+0000 age=7m7s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:29:33+0000 age=5m5s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:30:45+0000 age=3m53s
geth_1  | WARN [07-16|09:34:38.382] Unclean shutdown detected                booted=2021-07-16T09:31:50+0000 age=2m48s
```
It could be that one of those left the db in an inconsistent state.

**Comment by ligi** [comment]
there is nothing we can do here - the Unclean shutdowns and the resulting corrupted DB are most likely the problem. Please resync avoid unclean shutdowns.
