### ISSUE TITLE
Impossible reorg and impossible to cleanly shut down

### ISSUE THREAD

**Issue by zomglings** [ethereum/go-ethereum#23260]
#### System information

Geth version: `1.10.5-unstable`
OS & Version: Linux - Ubuntu 21.04
Commit hash : `4fcc93d9229e99b14d3d1500f05ada6ba1f789bb`

`uname -a`:
```
Linux <hostname> 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

`geth` built with `go 1.16.5`.

#### Expected behaviour

Node synchronizes with blockchain.

#### Actual behaviour

Woke up to the node giving me "CPU locked up messages" and had to restart.

Ever since, every time I try to sync, I get the following logs:

```
INFO [07-23|04:36:07.134] Downloader queue stats                   receiptTasks=0 blockTasks=66 itemSize=9.88KiB throttle=8192
ERROR[07-23|04:36:12.064] Snapshot extension registration failed   peer=35ba3061 err="peer connected on snap without compatible eth support"
INFO [07-23|04:36:13.641] Looking for peers                        peercount=5 tried=30 static=0
INFO [07-23|04:36:13.827] Importing heavy sidechain segment        blocks=1087 start=12,876,298 end=12,877,384
INFO [07-23|04:36:24.398] Looking for peers                        peercount=8 tried=35 static=0
ERROR[07-23|04:36:49.982] Snapshot extension registration failed   peer=fb0cdd32 err="peer connected on snap without compatible eth support"
ERROR[07-23|04:37:34.078] Impossible reorg, please file an issue   oldnum=12,807,492 oldhash=10f4c2..57462c newnum=12,807,492 newhash=10f4c2.
.57462c
^CINFO [07-23|04:39:09.060] Got interrupt, shutting down... 
INFO [07-23|04:39:09.951] IPC endpoint closed                      url=/media/neeraj/e3b8b293-486e-4a9b-8371-13b4c3c709ad/.ethereum/geth.ipc
ERROR[07-23|04:40:26.125] Snapshot extension registration failed   peer=18c44834 err="peer connected on snap without compatible eth support"
ERROR[07-23|04:40:59.872] Snapshot extension registration failed   peer=f56cd729 err="peer connected on snap without compatible eth support"
ERROR[07-23|04:41:08.575] Snapshot extension registration failed   peer=405ca82f err="peer connected on snap without compatible eth support"
ERROR[07-23|04:42:21.974] Snapshot extension registration failed   peer=70d956b8 err="peer connected on snap without compatible eth support"
ERROR[07-23|04:42:26.975] Snapshot extension registration failed   peer=24362cfc err="peer connected on snap without compatible eth support"
ERROR[07-23|04:43:28.026] Snapshot extension registration failed   peer=a8210c3c err="peer connected on snap without compatible eth support"
ERROR[07-23|04:44:29.872] Snapshot extension registration failed   peer=7387c717 err="peer connected on snap without compatible eth support"
ERROR[07-23|04:45:32.933] Snapshot extension registration failed   peer=b1de9ff2 err="peer connected on snap without compatible eth support"
ERROR[07-23|04:45:55.213] Snapshot extension registration failed   peer=9ee3322a err="peer connected on snap without compatible eth support"
ERROR[07-23|04:45:55.589] Snapshot extension registration failed   peer=2b78624f err="peer connected on snap without compatible eth support"
```

Note block number: `12,807,492`

Trying to shut down seems to hang the process with repeated `Snapshot extension registration failed` messages, although I think those are not strongly related to the underlying issue (speculation on my part).

#### Steps to reproduce the behaviour

No idea.

#### Backtrace

After many times hitting `ctrl+c` consecutively:

````
panic: boom

goroutine 229 [running]:
github.com/ethereum/go-ethereum/internal/debug.LoudPanic(...)
        github.com/ethereum/go-ethereum/internal/debug/loudpanic.go:26 
github.com/ethereum/go-ethereum/cmd/utils.StartNode.func1(0xc000132420, 0xc0001e9d40)
        github.com/ethereum/go-ethereum/cmd/utils/cmd.go:98 +0x475
created by github.com/ethereum/go-ethereum/cmd/utils.StartNode
        github.com/ethereum/go-ethereum/cmd/utils/cmd.go:73 +0xbe

goroutine 1 [chan receive, 20 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(...)
        github.com/ethereum/go-ethereum/node/node.go:420
main.geth(0xc000132420, 0x0, 0x0)
        github.com/ethereum/go-ethereum/cmd/geth/main.go:323 +0x157
gopkg.in/urfave/cli%2ev1.HandleAction(0x1195180, 0x14503d0, 0xc000132420, 0xc0000a44e0, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000bc820, 0xc000032070, 0x7, 0x7, 0x0, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
        github.com/ethereum/go-ethereum/cmd/geth/main.go:259 +0x55

goroutine 6 [chan receive, 22 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000a4360, 0xc0000a42a0)
        github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
        github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0xe5

goroutine 7 [chan receive, 22 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000a4360, 0xc0000a4300)
        github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
        github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x111

goroutine 8 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 9 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 10 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 11 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 12 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 13 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 14 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 15 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f
goroutine 16 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 18 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 19 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 20 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 21 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 22 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 23 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 24 [chan receive, 17 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0001ecbb0)
        github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 25 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x1ebc4e0)
        github.com/ethereum/go-ethereum/metrics/meter.go:290 +0x7d
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
        github.com/ethereum/go-ethereum/metrics/meter.go:71 +0x105

goroutine 26 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0000f20f0)
        github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:278 +0x20c
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
        github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:262 +0x2b2

goroutine 58 [syscall]:                                                                                               (0 results) [1369/3315]
os/signal.signal_recv(0x1596fc0)
        runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1 
        os/signal/signal.go:151 +0x45

goroutine 42 [syscall, 22 minutes]: 
syscall.Syscall6(0xe8, 0x9, 0xc00001779c, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0x9, 0xc00001779c, 0x1, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        golang.org/x/sys@v0.0.0-20210420205809-ac73e9fd8988/unix/zsyscall_linux_amd64.go:77 +0x72
github.com/rjeczalik/notify.(*inotify).loop(0xc000180000, 0xc000490000)
        github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:194 +0x79
created by github.com/rjeczalik/notify.(*inotify).lazyinit
        github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:134 +0x145

goroutine 60 [select, 22 minutes]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc000250ac0)
        github.com/ethereum/go-ethereum/accounts/keystore/watch.go:94 +0x3aa
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
        github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x59

goroutine 43 [chan receive, 22 minutes]:
github.com/rjeczalik/notify.(*inotify).send(0xc000180000, 0xc000490000)
        github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:254 +0xab
created by github.com/rjeczalik/notify.(*inotify).lazyinit
        github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:137 +0x19a

goroutine 44 [chan receive, 22 minutes]:
github.com/rjeczalik/notify.(*inotify).send(0xc000180000, 0xc000490000)
        github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:254 +0xab
created by github.com/rjeczalik/notify.(*inotify).lazyinit
        github.com/rjeczalik/notify@v0.9.1/watcher_inotify.go:137 +0x19a

goroutine 61 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).updater(0xc0000f2960)
        github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:209 +0x9f
created by github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).Subscribe
        github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:196 +0x12f

goroutine 62 [select, 22 minutes]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc000302ea0)
        github.com/ethereum/go-ethereum/accounts/manager.go:111 +0x185 
created by github.com/ethereum/go-ethereum/accounts.NewManager
        github.com/ethereum/go-ethereum/accounts/manager.go:79 +0x4e5

goroutine 66 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0005be000)
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/util/buffer_pool.go:209 +0x105
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/util/buffer_pool.go:240 +0x18c

goroutine 67 [select, 3 minutes]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0000f2a50)
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/session_util.go:189 +0x5b2
created by github.com/syndtr/goleveldb/leveldb.newSession
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/session.go:93 +0x2ca

goroutine 63 [select, 21 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc00033b180)
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_compaction.go:91 +0xb1
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db.go:148 +0x429

goroutine 64 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00033b180)
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_state.go:101 +0xd7
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db.go:149 +0x44b

goroutine 65 [select, 21 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc00033b180)
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_compaction.go:836 +0x228
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db.go:155 +0x5a5

goroutine 82 [select, 21 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc00033b180)
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db_compaction.go:773 +0x125
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210305035536-64b5b1c73954/leveldb/db.go:156 +0x5c7

goroutine 83 [select]:
github.com/ethereum/go-ethereum/ethdb/leveldb.(*Database).meter(0xc0065e2000, 0xb2d05e00)
        github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:431 +0x194f
created by github.com/ethereum/go-ethereum/ethdb/leveldb.NewCustom
        github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:147 +0xa05

goroutine 45 [select]:
github.com/ethereum/go-ethereum/core/rawdb.(*freezer).freeze(0xc000280900, 0x15ade58, 0xc0065e2000)
        github.com/ethereum/go-ethereum/core/rawdb/freezer.go:302 +0x295d
github.com/ethereum/go-ethereum/core/rawdb.NewDatabaseWithFreezer.func1(0xc000280900, 0x15ade58, 0xc0065e2000)
        github.com/ethereum/go-ethereum/core/rawdb/database.go:202 +0x3f
created by github.com/ethereum/go-ethereum/core/rawdb.NewDatabaseWithFreezer
        github.com/ethereum/go-ethereum/core/rawdb/database.go:201 +0x365

goroutine 33 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0000f2000)
        github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:278 +0x20c
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
        github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:262 +0x2b2

goroutine 98 [select, 20 minutes]:
github.com/ethereum/go-ethereum/core.(*ChainIndexer).updateLoop(0xc0000f2b40)
        github.com/ethereum/go-ethereum/core/chain_indexer.go:311 +0xdb
created by github.com/ethereum/go-ethereum/core.NewChainIndexer
        github.com/ethereum/go-ethereum/core/chain_indexer.go:119 +0x24d

goroutine 2377 [select, 17 minutes]:
github.com/ethereum/go-ethereum/p2p.(*Peer).run(0xc086d3d140, 0x114d160, 0xc047fd8f80, 0x0)
        github.com/ethereum/go-ethereum/p2p/peer.go:255 +0x265
github.com/ethereum/go-ethereum/p2p.(*Server).runPeer(0xc0003a2f00, 0xc086d3d140)
        github.com/ethereum/go-ethereum/p2p/server.go:1039 +0x1de
created by github.com/ethereum/go-ethereum/p2p.(*Server).launchPeer
        github.com/ethereum/go-ethereum/p2p/server.go:1022 +0xc5

goroutine 1002 [IO wait]:
internal/poll.runtime_pollWait(0x7f67b0460f08, 0x72, 0xffffffffffffffff)
        runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc01093cb18, 0x72, 0x29e000, 0x29e000, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc01093cb00, 0xc08d062000, 0x29e000, 0x29e000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc01093cb00, 0xc08d062000, 0x29e000, 0x29e000, 0xc0108fd880, 0xc41592af40, 0x20)
        net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0595fefc0, 0xc08d062000, 0x29e000, 0x29e000, 0x0, 0x0, 0x0)
        net/net.go:183 +0x91
io.ReadAtLeast(0x1587320, 0xc0595fefc0, 0xc08d062000, 0x29e000, 0x29e000, 0x20, 0x0, 0x0, 0xc00c0e1c70)
        io/io.go:328 +0x87
github.com/ethereum/go-ethereum/p2p/rlpx.(*readBuffer).read(0xc0108fd8c0, 0x1587320, 0xc0595fefc0, 0x20, 0x425ebf, 0xc000418000, 0x11fc3c0, 0
x1321d60, 0x1587320)
        github.com/ethereum/go-ethereum/p2p/rlpx/buffer.go:64 +0x12e
github.com/ethereum/go-ethereum/p2p/rlpx.(*sessionState).readFrame(0xc0108fd7c0, 0x1587320, 0xc0595fefc0, 0x1587320, 0xc0595fefc0, 0x1ec4be0,
 0xc01093cb00, 0x1450128)
        github.com/ethereum/go-ethereum/p2p/rlpx/rlpx.go:166 +0x105
github.com/ethereum/go-ethereum/p2p/rlpx.(*Conn).Read(0xc0107659a0, 0xc036c95e60b4f589, 0x13cb1c95c9f, 0x1ec4be0, 0x0, 0x0, 0x1ec4be0, 0x0)
        github.com/ethereum/go-ethereum/p2p/rlpx/rlpx.go:136 +0x98
github.com/ethereum/go-ethereum/p2p.(*rlpxTransport).ReadMsg(0xc00f0670c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/p2p/transport.go:64 +0x13e
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc059ca5800, 0xc059ca58c0)
        github.com/ethereum/go-ethereum/p2p/peer.go:308 +0xb5
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        github.com/ethereum/go-ethereum/p2p/peer.go:245 +0xfb

goroutine 145 [chan receive, 15 minutes]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync(0xc0627c0540, 0xc01805d440, 0x5, 0x8, 0x5, 0xc01805d440)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:584 +0x129
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0627c0540, 0xc087cfbee0, 0xef0246a7e9c32a9e, 0x8a756a51f04b89c4,
 0xc2302d142e1ad717, 0x8ec8f1c2a4ddbcee, 0xc00f20ec40, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:563 +0x885
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0627c0540, 0xc00ba44100, 0x40, 0xef0246a7e9c32a9e, 0x8a756a51f04b
89c4, 0xc2302d142e1ad717, 0x8ec8f1c2a4ddbcee, 0xc00f20ec40, 0xc000000000, 0x0, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:431 +0x3b0
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc0627c0540, 0xc00ba44100, 0x40, 0xef0246a7e9c32a9e, 0x8a756a51f04b
89c4, 0xc2302d142e1ad717, 0x8ec8f1c2a4ddbcee, 0xc00f20ec40, 0x0, 0x8000100000003, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:326 +0x8c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc086390200, 0xc033091e40, 0x1586080, 0xc063472000)
        github.com/ethereum/go-ethereum/eth/sync.go:324 +0x125
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0861fffb0, 0xc033091e40)
        github.com/ethereum/go-ethereum/eth/sync.go:300 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        github.com/ethereum/go-ethereum/eth/sync.go:300 +0x76

goroutine 108 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc0000d9200)
        github.com/ethereum/go-ethereum/core/blockchain.go:2257 +0xde
created by github.com/ethereum/go-ethereum/core.NewBlockChain
        github.com/ethereum/go-ethereum/core/blockchain.go:377 +0x1085 

goroutine 109 [select, 20 minutes]: 
github.com/ethereum/go-ethereum/core.(*BlockChain).maintainTxIndex(0xc0000d9200, 0x0)
        github.com/ethereum/go-ethereum/core/blockchain.go:2334 +0x205 
created by github.com/ethereum/go-ethereum/core.NewBlockChain
        github.com/ethereum/go-ethereum/core/blockchain.go:382 +0x12d7 

goroutine 110 [select, 20 minutes]:                                                                                   (0 results) [1190/3315]
github.com/ethereum/go-ethereum/trie.(*Database).SaveCachePeriodically(0xc0022841a0, 0xc001416ff0, 0x4b, 0x34630b8a000, 0xc00226e0c0)
        github.com/ethereum/go-ethereum/trie/database.go:882 +0xf8
github.com/ethereum/go-ethereum/core.NewBlockChain.func1(0xc0000d9200, 0xc0022841a0)
        github.com/ethereum/go-ethereum/core/blockchain.go:394 +0x8b
created by github.com/ethereum/go-ethereum/core.NewBlockChain
        github.com/ethereum/go-ethereum/core/blockchain.go:392 +0x1145 

goroutine 111 [select, 20 minutes]: 
github.com/ethereum/go-ethereum/core.(*ChainIndexer).eventLoop(0xc0000f2b40, 0xc0026feb40, 0xc08768fbc0, 0x1594db0, 0xc0879e0990)
        github.com/ethereum/go-ethereum/core/chain_indexer.go:211 +0x265
created by github.com/ethereum/go-ethereum/core.(*ChainIndexer).Start
        github.com/ethereum/go-ethereum/core/chain_indexer.go:152 +0xcf

goroutine 112 [select, 20 minutes]:
github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop(0xc0015ec5a0)
        github.com/ethereum/go-ethereum/core/tx_pool.go:1054 +0x1f9
created by github.com/ethereum/go-ethereum/core.NewTxPool
        github.com/ethereum/go-ethereum/core/tx_pool.go:299 +0x71d

goroutine 113 [select]:
github.com/ethereum/go-ethereum/core.(*TxPool).loop(0xc0015ec5a0)
        github.com/ethereum/go-ethereum/core/tx_pool.go:341 +0x285
created by github.com/ethereum/go-ethereum/core.NewTxPool
        github.com/ethereum/go-ethereum/core/tx_pool.go:316 +0x7bc

goroutine 147 [select, 20 minutes]:
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc05b25fb00) 
        github.com/ethereum/go-ethereum/miner/worker.go:448 +0x2a7
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum/miner/worker.go:228 +0x532

goroutine 148 [select, 20 minutes]: 
github.com/ethereum/go-ethereum/miner.(*worker).newWorkLoop(0xc05b25fb00, 0xb2d05e00)
        github.com/ethereum/go-ethereum/miner/worker.go:382 +0x247
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum/miner/worker.go:229 +0x55e

goroutine 149 [select, 20 minutes]: 
github.com/ethereum/go-ethereum/miner.(*worker).resultLoop(0xc05b25fb00)
        github.com/ethereum/go-ethereum/miner/worker.go:593 +0xb8
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum/miner/worker.go:230 +0x585

goroutine 150 [select, 20 minutes]: 
github.com/ethereum/go-ethereum/miner.(*worker).taskLoop(0xc05b25fb00) 
        github.com/ethereum/go-ethereum/miner/worker.go:558 +0xd0
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum/miner/worker.go:231 +0x5a7

goroutine 151 [select, 18 minutes]: 
github.com/ethereum/go-ethereum/miner.(*Miner).update(0xc086f3c780)
        github.com/ethereum/go-ethereum/miner/miner.go:99 +0x1fd
created by github.com/ethereum/go-ethereum/miner.New
        github.com/ethereum/go-ethereum/miner/miner.go:78 +0x1bb

goroutine 152 [select, 18 minutes]: 
github.com/ethereum/go-ethereum/eth/downloader.(*PublicDownloaderAPI).eventLoop(0xc00a591680)
        github.com/ethereum/go-ethereum/eth/downloader/api.go:63 +0x27a
created by github.com/ethereum/go-ethereum/eth/downloader.NewPublicDownloaderAPI
        github.com/ethereum/go-ethereum/eth/downloader/api.go:49 +0xca 

...
````

It goes on for another 1000 lines or so.

When submitting logs: please submit them as text and not screenshots.

**Comment by zomglings** [comment]
I will try downgrading to a stable version of `geth` and running the sync again.

**Comment by zomglings** [comment]
I will try upgrading to the latest commit and running the sync again. If that doesn't work, I will try downgrading to the most recent stable version and running the sync again.

:crossed_fingers:

**Comment by zomglings** [comment]
After pulling the latest `master` branch (`a1f16bc74c7efb593db2982c92222d1e4a201c25`, `v1.10.7-unstable`), I am still getting the impossible reorg message but it doesn't hang the geth process. Sync seems to be working again.
