### ISSUE TITLE
panic: runtime error: integer divide by zero Snapshot.go:.inturn()

### ISSUE THREAD

**Issue by akinmail** [ethereum/go-ethereum#23438]
#### System information

Geth version: ` instance=Geth/v1.10.7-stable-12f0ff40/darwin-amd64/go1.13.4`
OS & Version: Linux and OSX
Commit hash : 

#### Expected behaviour
After runnning geth init, trying to run geth and attach to it should work

#### Actual behaviour
trying to run geth and attach to it throws panic: runtime error: integer divide by zero Snapshot.go:.inturn()

#### Steps to reproduce the behaviour
```
git clone https://github.com/ethereum/go-ethereum.git
cd go-ethereum/
git checkout remotes/origin/release/1.10
make geth
cd build/bin
./geth --datadir="data" init dev.json

./geth --datadir="data" --unlock "0xxxxxx" --miner.etherbase "0xxxx" --password ./password.txt --txpool.nolocals --mine  --miner.threads 8 --rpc.gascap 0 --allow-insecure-unlock --nousb --networkid 200 --syncmode 'full' --http --http.addr '0.0.0.0' --http.port 8501 --http.api 'personal,eth,net,web3,txpool,miner' --ws  --ws.addr '0.0.0.0'  --ws.port 8601  --ws.api 'personal,eth,net,web3,txpool,miner'  --ws.origins '*' --http.corsdomain '*' --bootnodes "enode://44b7c541a6f7b8cb44f84f396b042c40dcdf79659273a9c991800794763523c18af5c94ef3df414e26939a7e06d8e7c75febab7aae20b8a4bca7cdbce33442d4@52.165.155.198:30301"
```

#### Backtrace

````
INFO [08-23|17:44:53.176] Maximum peer count                       ETH=50 LES=0 total=50
WARN [08-23|17:44:53.176] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
INFO [08-23|17:44:53.177] Global gas cap disabled 
INFO [08-23|17:44:53.177] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [08-23|17:44:53.177] Allocated cache and file handles         database=/Users/akinyemiakindele/Downloads/go-ethereum-latest/build/bin/data/geth/chaindata cache=512.00MiB handles=5120
INFO [08-23|17:44:53.379] Opened ancient database                  database=/Users/akinyemiakindele/Downloads/go-ethereum-latest/build/bin/data/geth/chaindata/ancient readonly=false
INFO [08-23|17:44:53.380] Initialised chain configuration          config="{ChainID: 200 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, Berlin: <nil>, London: <nil>, Engine: clique}"
INFO [08-23|17:44:53.381] Initialising Ethereum protocol           network=200 dbversion=8
INFO [08-23|17:44:53.382] Loaded most recent local header          number=0 hash=773cee..a7059e td=1 age=11mo2w3d
INFO [08-23|17:44:53.382] Loaded most recent local full block      number=0 hash=773cee..a7059e td=1 age=11mo2w3d
INFO [08-23|17:44:53.382] Loaded most recent local fast block      number=0 hash=773cee..a7059e td=1 age=11mo2w3d
WARN [08-23|17:44:53.382] Loaded snapshot journal                  diskroot=e1372c..239798 diffs=missing
INFO [08-23|17:44:53.383] Gasprice oracle is ignoring threshold set threshold=2
number is  1
WARN [08-23|17:44:53.384] Unclean shutdown detected                booted=2021-08-23T17:30:01+0400 age=14m52s
WARN [08-23|17:44:53.384] Unclean shutdown detected                booted=2021-08-23T17:43:40+0400 age=1m13s
INFO [08-23|17:44:53.384] Starting peer-to-peer node               instance=Geth/v1.10.7-stable-12f0ff40/darwin-amd64/go1.13.4
panic: runtime error: integer divide by zero

goroutine 103 [running]:
github.com/ethereum/go-ethereum/consensus/clique.(*Snapshot).inturn(0xc000226070, 0x1, 0x0, 0x0, 0x0, 0x5d4cf20)
        github.com/ethereum/go-ethereum@/consensus/clique/snapshot.go:327 +0x18d
github.com/ethereum/go-ethereum/consensus/clique.calcDifficulty(0xc000226070, 0x0, 0x0, 0x0, 0xbebffa7ceee3c77)
        github.com/ethereum/go-ethereum@/consensus/clique/clique.go:682 +0x67
github.com/ethereum/go-ethereum/consensus/clique.(*Clique).Prepare(0xc000120850, 0x52d7000, 0xc00037e000, 0xc0000de000, 0x9e05a7439da6001e, 0x0)
        github.com/ethereum/go-ethereum@/consensus/clique/clique.go:539 +0x43f
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc0004f58c0, 0xc000422000, 0x0, 0x6123a655)
        github.com/ethereum/go-ethereum@/miner/worker.go:920 +0x397
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc0004f58c0)
        github.com/ethereum/go-ethereum@/miner/worker.go:456 +0xcd5
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum@/miner/worker.go:228 +0x525

[backtrace]
````

I checked the code, and it seems to me that `Snapshot.signers()` is null or empty and because of that it is doing `number % uint64(len(signers))` causing it to divide by zero. I just want to start geth, is there anything i am doing wrong?
```
// inturn returns if a signer at a given block height is in-turn or not.
func (s *Snapshot) inturn(number uint64, signer common.Address) bool {
	signers, offset := s.signers(), 0
	for offset < len(signers) && signers[offset] != signer {
		offset++
	}
	return (number % uint64(len(signers))) == uint64(offset)
}
```

**Comment by karalabe** [comment]
My guess is that your `dev.json` is configured to be a Clique network with 0 signers. You'll need to have at least 1 signer in the genesis spec. Generating a clique generis is easier with `puppeth`.
