### ISSUE TITLE
Here's what happens after a transaction attempt, how do I fix it?

### ISSUE THREAD

**Issue by zrock23** [ethereum/go-ethereum#23533]
Here's what happens after a transaction attempt, how do I fix it?
geth --mine --miner.threads="1" --networkid="4" --datadir="/root/.ethereum/data/data" ...
...and funding address

web3.eth.sendTransaction({from:"0xd935646beb6ed878a4712f60a5e4aa84609a878e",to:"0xd1AC88f5a6E80E173D9CD294291Fe6e7c7cB8423", value: web3.toWei(1000,"ether"),gas: 21000, gasPrice: web3.toWei(3,"gwei")})
WARN [09-04|21:46:36.988|rpc/handler.go:306]             Served eth_sendTransaction               reqid=11 t="744.132µs" err="invalid transaction v, r, s values"
INFO [09-04|21:46:36.988|miner/worker.go:1032]           Commit new mining work                   number=1 sealhash=2ef33f..5b722c uncles=0 txs=0 gas=0 fees=0 elapsed="144.938µs"
Error: invalid transaction v, r, s values
        at web3.js:6357:37(47)
        at web3.js:5091:62(37)
        at <eval>:1:25(25)

**Comment by ligi** [comment]
seems there is a problem with the signature of the transaction - why do you think it's a go-ethereum issue?

**Comment by Sunset17** [comment]
There is a bug on the go Etherium chain

**Comment by rjl493456442** [comment]
You have to sign your transaction first before submitting it to network. 
Also `networkid=4` is the public rinkeby testnet, I don't think you have the right key to run as the sealer.

**Comment by karalabe** [comment]
If you made a custom network (please use a non-reserved network id), make sure you enabled all the past forks. I'm unsure if we still allow signing non-EIP155 transactions via the RPC (it's a fork done 5 years ago). Please share your genesis json and startup logs that print the chain specs.

**Comment by Sunset17** [comment]
I am just trying to figure out what I should do here there is so much mumbo jumbo that I don’t now what I have to do 


Sent from Yahoo Mail for iPhone


On Monday, September 6, 2021, 23:50, Péter Szilágyi ***@***.***> wrote:




If you made a custom network (please use a non-reserved network id), make sure you enabled all the past forks. I'm unsure if we still allow signing non-EIP155 transactions via the RPC (it's a fork done 5 years ago). Please share your genesis json and startup logs that print the chain specs.

**Comment by zrock23** [comment]
thanks that's enough!🥴
