### ISSUE TITLE
sigsev when tracing with light client

### ISSUE THREAD

**Issue by saman-pasha** [ethereum/go-ethereum#23766]
#### System information

Geth version: Version: 1.10.10-stable
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
debug internall calls with json rpc

#### Actual behaviour
geth crashes

#### Steps to reproduce the behaviour
I was searching for a way to get trace internal calls that I found [this link](https://github.com/ethereum/go-ethereum/pull/15516). I did that and `make clean`, `make geth` and run an ethereum light. after I send the subscription, `{"jsonrpc":"2.0","id":1,"result":"0xce32469e47c132d480cdff54f21ae2b3"}` I gave this result but a second after geth crashes with below error 

#### Backtrace

````
INFO [10-18|15:06:01.997] Imported new block headers               count=1  elapsed=6.040ms  number=13,441,578 hash=555638..d4667a
INFO [10-18|15:06:05.375] Imported new block headers               count=1  elapsed=6.269ms  number=13,441,579 hash=b3ed34..d9d1e4
INFO [10-18|15:06:06.102] Tracing chain segment                    start=0 end=65535 current=0 transactions=0 elapsed="49.105µs"
WARN [10-18|15:06:06.108] Chain tracing aborted                    start=0 end=65535 abort=2 transactions=0 elapsed=5.699454ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x777a1f]

goroutine 270 [running]:
github.com/ethereum/go-ethereum/trie.(*Database).Dereference(0x0, {0xd7, 0xf8, 0x97, 0x4f, 0xb5, 0xac, 0x78, 0xd9, 0xac, ...})
	github.com/ethereum/go-ethereum/trie/database.go:519 +0x9f
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceChain.func2()
	github.com/ethereum/go-ethereum/eth/tracers/api.go:334 +0xafb
created by github.com/ethereum/go-ethereum/eth/tracers.(*API).traceChain
	github.com/ethereum/go-ethereum/eth/tracers/api.go:299 +0x4d8
````

When submitting logs: please submit them as text and not screenshots.

**Comment by saman-pasha** [comment]
geth command:
```
[Unit]
Description=Ethereum Light Node
After=syslog.target

[Service]
User=www-data
Group=www-data
StandardOutput=append:/var/log/lightnode.log
StandardError=append:/var/log/lightnode.log
ExecStart=/bin/geth --mainnet --datadir /var/net/lightnode --http --http.addr=127.0.0.1 --http.vhosts=eilyaproject.com --http.port=8545 --http.corsdomain=* --http.api=net,eth,web3 --ws --ws.addr=188.40.23.246 --ws.api=net,eth,web3,debug --ws.origins=* --ws.port=8546 --syncmode=light

[Install]
WantedBy=multi-user.target
```
RPC command:
```
{"id": 1, "method": "debug_subscribe", "params": ["traceChain", "0x0", "0xffff", {"tracer": "callTracer"}]}
```

**Comment by karalabe** [comment]
I don't think LES supports chain tracing. LES does not execute blocks, rather it just pulls the parent state from the network and runs txs on top. The chain tracer on the other hand is running blocks locally and maintaining state locally.

I'm unsure if it's something we should support on LES?

**Comment by saman-pasha** [comment]
Does light client receive txs without internal txs?
