### ISSUE TITLE
Geth Node panics with SIGSEGV when using pending transaction filter

### ISSUE THREAD

**Issue by bscqt** [ethereum/go-ethereum#23839]
#### System information

Geth version: 1.12
Go Version: go1.15.5
OS & Version: Linux Centos

#### Expected behaviour
No-crash

#### Actual behaviour
Geth crashes due to listening for panding transactions. The pending transaction filter is in python via web3.

#### Steps to reproduce the behaviour
- Run a bsc fullnode
- Run the below script
```
pool = web3.eth.filter('pending')
while True:
        # Loop through new entries in tx pool
        for entry in pool.get_new_entries():
            n = 0
            ptx = []
            while n < 3:
                try:
                    ptx = dict(web3.eth.getTransaction(entry))
                    break
                except:
                    n = n+1
            if ptx == []:
                continue

...

```
- geth will eventualy crash with an error message similar to the below:
```
2021/10/06 20:24:43 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
2021/10/06 20:24:43 worker exits from panic: goroutine 18034 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1(0xc224864690)
github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x177
panic(0x14db6c0, 0x2586950)
runtime/panic.go:969 +0x1b9
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1()
github.com/ethereum/go-ethereum/eth/filters/api.go:129 +0x205
github.com/panjf2000/ants/v2.(*goWorker).run.func1(0xc224864690)
github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x94
created by github.com/panjf2000/ants/v2.(*goWorker).run
github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x4c

```

- See also https://github.com/ethereum/web3.py/issues/2034 for further information
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by bscqt** [comment]
I see this is referenced here: 

https://github.com/binance-chain/bsc/issues/388
