### ISSUE TITLE
eth.subscribe() does not fire any event

### ISSUE THREAD

**Issue by Art-Mas** [ethereum/go-ethereum#23943]
1. I have deployed and started a local node 

```
wget https://github.com/binance-chain/bsc/releases/download/v1.1.5/geth_linux

./geth_linux --config ./config.toml --datadir ./mainnet --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=snap --snapshot=false --diffsync
```

2. I can't say for sure, but it seems that it should be completely synchronized. Here is log from  `tail -f /home/geth/mainnet/bsc.log`: 

```

t=2021-11-21T08:22:27+0100 lvl=eror msg="Snapshot extension registration failed" peer=9c8d9aaf err="peer connected on snap without compatible eth support"
t=2021-11-21T08:22:28+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="186.589µs" number=12,827,964 hash=0x015adaddad770c83281031a0c0dca3e17aed39ee2620ac487c052f3edc07ae38
t=2021-11-21T08:22:29+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="208.147µs" number=12,827,965 hash=0xed1b2494dc1dcfdcd936eccfcf2b9f00447bd8994c039bc48f3b6ce6adcf11dc
t=2021-11-21T08:22:34+0100 lvl=info msg="Imported new block headers"             count=2    elapsed="302.325µs" number=12,827,967 hash=0x2aeae23dd0341ff4bc6e95364dfce19a9a8ad781478d407c8b652b80dee473f8
t=2021-11-21T08:22:34+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=160,512@11.63MiB codes=2921@22.77MiB nodes=98,984,729@22.79GiB pending=86084
t=2021-11-21T08:22:38+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="196.401µs" number=12,827,968 hash=0xe23fa128649ccc783e63d71186081e28162e3bd6d6d071cc9e8b2863fb6168f2
t=2021-11-21T08:22:41+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="379.502µs" number=12,827,969 hash=0x4da37f07fe2eb35fb3db1bb096e603ee1822828377c5a3d1e34fd4b0bab095db
t=2021-11-21T08:22:42+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=169,065@12.27MiB codes=2921@22.77MiB nodes=99,008,151@22.79GiB pending=80133
t=2021-11-21T08:22:45+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="239.071µs" number=12,827,970 hash=0xad366235b990877df41cb44837ae9d7e56efcb8943cebed608e10699cc1b5c1d
t=2021-11-21T08:22:47+0100 lvl=eror msg="Snapshot extension registration failed" peer=968fed87 err="peer connected on snap without compatible eth support"
t=2021-11-21T08:22:49+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="283.531µs" number=12,827,971 hash=0x7f6999a2faeda18a87d647ecc216591e80f2f6abaa0790a4911b17a227130b7e
t=2021-11-21T08:22:50+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=177,373@12.89MiB codes=2921@22.77MiB nodes=99,031,605@22.79GiB pending=79208
t=2021-11-21T08:22:53+0100 lvl=info msg="Imported new block headers"             count=2    elapsed="407.495µs" number=12,827,973 hash=0x070e3e5df153f4a54063a2e0072d0ca0f3171107cc12c05462e3e149d4388316
t=2021-11-21T08:22:56+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="205.154µs" number=12,827,974 hash=0xc5c6742d2d472c33620d7f50954b995613338a7e82fee531a3611fcfb4a641f8
t=2021-11-21T08:22:57+0100 lvl=info msg="Downloader queue stats"                 receiptTasks=0    blockTasks=0    itemSize="713.16 KiB" throttle=92
t=2021-11-21T08:22:58+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=200,269@14.55MiB codes=2921@22.77MiB nodes=99,073,508@22.80GiB pending=69433
t=2021-11-21T08:23:00+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="190.701µs" number=12,827,975 hash=0x1bdc8d305e07fded805e58ea15e5b70574e020cc732658e35dc4b6e1f199da26
t=2021-11-21T08:23:01+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="207.991µs" number=12,827,976 hash=0xabd776546e2e06b06659713860423bc386a1f4d482ce4b04dda529afa7c5d142
t=2021-11-21T08:23:05+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="275.947µs" number=12,827,977 hash=0xb1f4e8bd6b929fdade61118052fee70c34cace61ae220717e21bf87a199e352c
t=2021-11-21T08:23:06+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=204,695@14.86MiB codes=2921@22.77MiB nodes=99,090,703@22.80GiB pending=74850
t=2021-11-21T08:23:08+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="201.384µs" number=12,827,978 hash=0x7f202a77d91f32a914052626bca73899612ea1eca8f036887f1096986d32276c
t=2021-11-21T08:23:12+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="334.951µs" number=12,827,979 hash=0xa40e875a09e0f81bfacf80b99cfb860266fc25f7757da9f4b02c5ec541ddb239
t=2021-11-21T08:23:14+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=214,562@15.54MiB codes=2921@22.77MiB nodes=99,116,317@22.81GiB pending=68705
t=2021-11-21T08:23:16+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="235.803µs" number=12,827,980 hash=0x355abc69a20347c3a78943a48a7365241d98cc093985456fbf5eeaf8c95feac5
t=2021-11-21T08:23:16+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="179.303µs" number=12,827,981 hash=0xe9dbd8eaa60de26daa1c3cbe51df247da1d0a8ad10122bbc4d774f241b63d4f8
t=2021-11-21T08:23:21+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="202.442µs" number=12,827,982 hash=0xe578d24c514648a741ccb4cc5be8d08b0a9fb08cc4fe2dae754afbd25a66215a
t=2021-11-21T08:23:22+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=220,021@15.91MiB codes=2921@22.77MiB nodes=99,134,314@22.81GiB pending=68204
t=2021-11-21T08:23:25+0100 lvl=info msg="Imported new block headers"             count=2    elapsed=33.312ms    number=12,827,984 hash=0x2869380759013ebdac485c0d5483c9a5884a7c6ae6a10876305d7ee9570dfb95
t=2021-11-21T08:23:31+0100 lvl=info msg="State heal in progress"                 accounts=43560@2.51MiB   slots=226,319@16.36MiB codes=2921@22.77MiB nodes=99,155,048@22.82GiB pending=66858
t=2021-11-21T08:23:31+0100 lvl=eror msg="Snapshot extension registration failed" peer=70d956b8 err="peer connected on snap without compatible eth support"
t=2021-11-21T08:23:32+0100 lvl=info msg="Imported new block headers"             count=2    elapsed="487.893µs" number=12,827,986 hash=0x9bd9fa1fd4e2819b3f7453a6414be4eec34f03df4ede07a7a3f14598c2ccadd3
```

3. I successfully connect to ws, but in each type of subscribe (newBlockHeaders, pendingTransactions, syncing) no events except "connected" do not work. For example:

```
const PROVIDER = new Web3.providers.WebsocketProvider('ws://localhost:8546');
const web3 = new Web3(PROVIDER)

const subscription = web3.eth.subscribe('newBlockHeaders', (err, res) => {
  if (err) {
    console.log('here1', err);
  }
  console.log('here2', res)
});

subscription.on('error', error => {
  console.log('here3', error)
})

subscription.on('connected', () => {
  console.log('here4', 'connected to ws') // <---- Only this is displayed
})

subscription.on("changed", function(){
  console.log('here5')
});
  
subscription.on('data', (data) => {
  console.log('here6', data)
})

```
And after a short period of time (~ 5min) i got this output to console:

```
{ Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason string `Connection dropped by remote peer.`
    at Object.ConnectionError (/home/geth/nft-bot/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionCloseError (/home/geth/nft-bot/node_modules/web3-core-helpers/lib/errors.js:53:25)
    at /home/geth/nft-bot/node_modules/web3-core-requestmanager/lib/index.js:119:50
    at Map.forEach (<anonymous>)
    at WebsocketProvider.disconnect (/home/geth/nft-bot/node_modules/web3-core-requestmanager/lib/index.js:118:37)
    at WebsocketProvider.emit (/home/geth/nft-bot/node_modules/eventemitter3/index.js:181:35)
    at WebsocketProvider._onClose (/home/geth/nft-bot/node_modules/web3-providers-ws/lib/index.js:152:10)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/geth/nft-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/home/geth/nft-bot/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/geth/nft-bot/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.handleSocketClose (/home/geth/nft-bot/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:607:12) code: 1006, reason: 'Connection dropped by remote peer.' }
```

Please help me. I don't have any ideas how to fix it

**Comment by karalabe** [comment]
You are not is sync.

`"State heal in progress"                 accounts=43560@2.51MiB   slots=226,319@16.36MiB codes=2921@22.77MiB nodes=99,155,048@22.82GiB pending=66858`

You need to wait it out until it starts importing blocks (it will tell you that state heal finished).
