### ISSUE TITLE
Can't get syncStatus on mobile

### ISSUE THREAD

**Issue by markusbug** [ethereum/go-ethereum#24176]
#### System information

Geth version: `GethDroid/v1.10.15-unstable/android-arm64/go1.17.3`
OS & Version: Android

#### Expected behaviour
Should return a SyncProgress Object.

#### Actual behaviour
Fails with this message:
```
Caused by: go.Universe$proxyerror: json: cannot unmarshal string into Go struct field SyncProgress.CurrentBlock of type uint64
        at geth.EthereumClient.syncProgress(Native Method)
```

#### Steps to reproduce the behaviour
- Bind the mobile code with gomobile into an .aar file.
- Import .aar file into android studio project
- Get SyncProgress in Java

You can get the SyncProgress using this Code:
```
import geth.*;

Node node = Geth.newNode(getFilesDir()+"/.ethNode", nodeConfig);
node.start();

Context ctx = Geth.newContext();
SyncProgress syncProgress = node.getEthereumClient().syncProgress(ctx);
```

#### Backtrace

````
Caused by: go.Universe$proxyerror: json: cannot unmarshal string into Go struct field SyncProgress.CurrentBlock of type uint64
        at geth.EthereumClient.syncProgress(Native Method)
````

**Comment by fjl** [comment]
Closing because the underlying issue is #24180
