### ISSUE TITLE
fastsync - panic when RPC blockTag at fastsync'd block

### ISSUE THREAD

**Issue by kumavis** [ethereum/go-ethereum#2453]
When i request data early than block #1305087 (0x13e9ff), the request fails w/o an error, and the geth client logs a runTime error. this may be a result of using `--fast`.

#### System information

Geth version: `Geth/v1.3.6/linux/go1.5.1`
OS & Version: Linux/Ubuntu
Commit hash : recent docker image

#### Expected behaviour
Handle request or respond with error

#### Actual behaviour
Connection is dropped

#### Steps to reproduce the behaviour
notice the specified blockTag.

blockTag @ #1305087 - WORKS
```
curl -d '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params": ["0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5", 1305087], "id":1}' -X POST https://rpc.metamask.io 
```

blockTag @ #1305086 - CONNECTION DROPPED
```
curl -d '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params": ["0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5", 1305086], "id":1}' -X POST https://rpc.metamask.io 
```

#### Trace
```
I0413 22:58:17.057766       1 server.go:1934] http: panic serving 172.17.0.2:58544: runtime error: invalid memory address or nil pointer dereference
goroutine 844747 [running]:
net/http.(*conn).serve.func1(0xc82038d810, 0x7f0d15653e68, 0xc822237de8)
	/usr/lib/go/src/net/http/server.go:1287 +0xb5
github.com/ethereum/go-ethereum/xeth.(*XEth).TxCountAt(0x0, 0xc82433dcb0, 0x2a, 0x40)
	/build/ethereum-6ZKMRx/ethereum-1.3.6+10wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/xeth/xeth.go:473 +0x18
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).GetTransactionCount(0xc82046b380, 0xc825961f90, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-6ZKMRx/ethereum-1.3.6+10wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:215 +0x269
github.com/ethereum/go-ethereum/rpc/api.(*ethApi).Execute(0xc82046b380, 0xc825961f90, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-6ZKMRx/ethereum-1.3.6+10wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/api/eth.go:127 +0xa1
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc820196f40, 0xc825961f90, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-6ZKMRx/ethereum-1.3.6+10wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:67 +0x35f
github.com/ethereum/go-ethereum/rpc/comms.(*handler).ServeHTTP(0xc8203335c0, 0x7f0d14622618, 0xc824b98bb0, 0xc8225ab500)
	/build/ethereum-6ZKMRx/ethereum-1.3.6+10wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/comms/http.go:126 +0x5c6
github.com/rs/cors.(*Cors).Handler.func1(0x7f0d14622618, 0xc824b98bb0, 0xc8225ab500)
	/build/ethereum-6ZKMRx/ethereum-1.3.6+10wily/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc8203335e0, 0x7f0d14622618, 0xc824b98bb0, 0xc8225ab500)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc821a4ef60, 0x7f0d14622618, 0xc824b98bb0, 0xc8225ab500)
	/usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82038d810)
	/usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by kumavis** [comment]
seems that if i request the data at a block before `#1310720` (0x140000) on my node, it fails, dropping the connection. this may be a result of using --fastsync

**Comment by karalabe** [comment]
Thanks for reporting this. The crash actually doesn't happen any more on develop:

```
> eth.getTransactionCount("0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5", 1305086)
Missing trie node 1055ec6fc3012b17c71893bb8802b0f1e14fad9034e60f4c71407584b8f517cc
    at web3.js:3119:20
    at web3.js:6018:15
    at web3.js:4990:36
    at <anonymous>:1:1
```

```
$ curl -d '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params": ["0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5", 1305086], "id":1}' -X POST localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Missing trie node 1055ec6fc3012b17c71893bb8802b0f1e14fad9034e60f4c71407584b8f517cc"}}
```

Just a side note, a fast synced node (or a pruned one for that matter) will only be able to retrieve state data for the blocks that it still retains historical state (i.e. top 1-2K blocks +-). Hence the missing trie node error: there's simply not enough past data retained to answer this question.

**Comment by fjl** [comment]
kewl.
