### ISSUE TITLE
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#24634]
Currently seeing this when running lint on ARM on master:

```
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x488
util.go:48: exit status 2
exit status 1
```

**Comment by ligi** [comment]
Upstream issue: https://github.com/golangci/golangci-lint/issues/2649

**Comment by ligi** [comment]
the arm builder was still using go 1.17 that caused the problem - fixed
