### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by notooth1** [ethereum/go-ethereum#24981]
Geth gave me this error. Can anyone help?

```
INFO [05-27|14:07:55.320] Imported new block receipts              count=1    elapsed=3.271ms     number=14,852,614 hash=1804e7..1a0359 age=37m29s     size=114.39KiB
INFO [05-27|14:07:55.321] Rebuilding state snapshot 
INFO [05-27|14:07:55.328] Committed new head block                 number=14,852,614 hash=1804e7..1a0359
INFO [05-27|14:07:55.328] Resuming state snapshot generation       root=3671a7..9932f7 accounts=0                    slots=0                     storage=0.00B     elapsed=2.727ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5e1596]

goroutine 2517503 [running]:
github.com/ethereum/go-ethereum/params.(*BorConfig).CalculateBurntContract(0x0, 0xe2a207)
        github.com/ethereum/go-ethereum/params/config.go:565 +0x36
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc079226e00)
        github.com/ethereum/go-ethereum/core/state_transition.go:344 +0xb65
github.com/ethereum/go-ethereum/core.ApplyMessage(0x1800a60, {0x1800a60, 0xc10757fb00}, 0xc07a0605e0)
        github.com/ethereum/go-ethereum/core/state_transition.go:181 +0x2a
github.com/ethereum/go-ethereum/core.applyTransaction({0xc07920d440, {0x4, 0x5b, 0xf2, 0x41, 0x64, 0xb9, 0xdd, 0x59, 0x49, ...}, ...}, ...)
        github.com/ethereum/go-ethereum/core/state_processor.go:101 +0x1c5
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc1035f2760, 0xc035804bd0, 0xc0b92121a0, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}})
        github.com/ethereum/go-ethereum/core/state_processor.go:82 +0x898
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0003f0500, {0xc0b7824a80, 0xfe1dc51b054c828a, 0x6b}, 0x1, 0x1)
        github.com/ethereum/go-ethereum/core/blockchain.go:1693 +0x1f05
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0003f0500, {0xc0b7824a80, 0x6b, 0x6b})
        github.com/ethereum/go-ethereum/core/blockchain.go:1448 +0xb57
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc000492300, {0xc0b2250400, 0x6b, 0x0})
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1523 +0x487
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processSnapSyncContent(0xc000492300)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1656 +0xb66
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func8()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:594 +0x1d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:608 +0x70
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:608 +0x65
```

**Comment by rjl493456442** [comment]
`(*BorConfig) ` it's not something we have in Go-ethereum. I guess you submit the issue in the wrong repo.
