### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kumavis** [ethereum/go-ethereum#25731]
#### System information

Geth version: Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18.5

#### Expected behaviour
no crash

#### Actual behaviour
crash

#### Steps to reproduce the behaviour
fresh box
```
      - --datadir=/data/geth
      - --datadir.ancient=/extra-data/geth
      - --maxpeers=100
      - --nousb
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=eth1
      - --http.api=eth,net,web3
      - --metrics
      - --metrics.addr=0.0.0.0
```

#### Backtrace

````
eth1_1               | INFO [09-10|03:02:27.427] Block synchronisation started 
eth1_1               | panic: runtime error: invalid memory address or nil pointer dereference
eth1_1               | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa979d9]
eth1_1               | 
eth1_1               | goroutine 596 [running]:
eth1_1               | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc00046c600, 0xc0009d93e0, 0x1, 0xe5a519, 0xffffffffffffffff)
eth1_1               | 	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:965 +0x319
eth1_1               | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00046c600, 0xc0009d93e0, 0x1e?)
eth1_1               | 	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:857 +0x2db
eth1_1               | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00046c600, 0xc0009d93e0, {0x11, 0xc5, 0xa3, 0x59, 0xba, 0xc4, 0x15, 0xe5, ...}, ...)
eth1_1               | 	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:521 +0x985
eth1_1               | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x732085?, {0xc002097bc0, 0x40}, {0x11, 0xc5, 0xa3, 0x59, 0xba, 0xc4, 0x15, ...}, ...)
eth1_1               | 	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:439 +0x505
eth1_1               | github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).LegacySync(0xc00046c600, {0xc002097bc0, 0x40}, {0x11, 0xc5, 0xa3, 0x59, 0xba, 0xc4, 0x15, ...}, ...)
eth1_1               | 	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:334 +0x65
eth1_1               | github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc000780b00, 0xc00397b840?)
eth1_1               | 	github.com/ethereum/go-ethereum/eth/sync.go:255 +0x225
eth1_1               | github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1()
eth1_1               | 	github.com/ethereum/go-ethereum/eth/sync.go:231 +0x29
eth1_1               | created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
eth1_1               | 	github.com/ethereum/go-ethereum/eth/sync.go:231 +0xaa
````

When submitting logs: please submit them as text and not screenshots.

**Comment by kumavis** [comment]
i think the problem was that the ancient db's disk ran out of data which somehow corrupted the db.

**Comment by holiman** [comment]
Can you please try:geth  --datadir=/data/geth --datadir.ancient=/extra-data/geth db metadata

**Comment by karalabe** [comment]
This code path will be mostly moot from this point onward and without some more details there's not much we can do.
