### ISSUE TITLE
panic: runtime error: slice bounds out of range [:4611686018476719459] with capacity 322961408

### ISSUE THREAD

**Issue by ryny24** [ethereum/go-ethereum#25759]
I'm trying to do a fresh sync with Geth, but it keeps crashing. I noticed a new update today (1.10.24). The other day I was able to sync just fine (on 1.10.23-stable), but today geth keeps crashing. I've rebooted. Deleted .ethereum, but it keeps crashing. 

INFO [09-14|09:34:20.641] Imported new block headers               count=2048 elapsed=193.099ms   number=645,504 hash=ac5bca..f25841 age=6>
INFO [09-14|09:34:20.650] Imported new block receipts              count=948  elapsed=153.505ms   number=611,009 hash=7c592d..45fc63 age=6>
INFO [09-14|09:34:20.754] Imported new block headers               count=2048 elapsed=110.659ms   number=647,552 hash=bc9583..63d457 age=6>
INFO [09-14|09:34:20.760] Imported new block receipts              count=432  elapsed=106.191ms   number=611,441 hash=580a3d..0b04b6 age=6>
INFO [09-14|09:34:20.782] Imported new block headers               count=448  elapsed=25.951ms    number=648,000 hash=c70632..3210d5 age=6>
panic: runtime error: slice bounds out of range [:4611686018476719459] with capacity 322961408 [recovered]
        panic: runtime error: slice bounds out of range [:4611686018476719459] with capacity 322961408 [recovered]
        panic: runtime error: slice bounds out of range [:4611686018476719459] with capacity 322961408

goroutine 69 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction.func1()
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:763 +0xc5
panic({0x13fe5c0, 0xc01a31a510})
        runtime/panic.go:838 +0x207
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact.func1()
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:159 +0x9b
panic({0x13fe5c0, 0xc01a31a510})
        runtime/panic.go:838 +0x207
github.com/syndtr/goleveldb/leveldb/memdb.(*dbIter).fill(0x31?, 0xa5?, 0x43?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/memdb/memdb.go:42 +0x291
github.com/syndtr/goleveldb/leveldb/memdb.(*dbIter).Next(0xc003e181e0?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/memdb/memdb.go:131 +0x12e
github.com/syndtr/goleveldb/leveldb.(*tOps).createFrom(0xc0001ef4a0?, {0x17d1c60, 0xc0041aa700})
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table.go:396 +0x108
github.com/syndtr/goleveldb/leveldb.(*session).flushMemdb(0xc0000ec960, 0xc018180f00, 0xc01bd0c0e0, 0x7f4572b6da68?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_compaction.go:35 +0x105
github.com/syndtr/goleveldb/leveldb.(*DB).memCompaction.func1(0xc003e18101?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:305 +0x9c
github.com/syndtr/goleveldb/leveldb.(*compactionTransactFunc).run(0x3539393839350000?, 0x0?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:242 +0x1f

#### System information

Geth version: `1.10.24-stable`
OS & Version: Linux/Ubuntu

**Comment by ryny24** [comment]
FYI - I installed 1.10.23 and it seems to be syncing fine now. No crash yet, I'm well past that spot where it kept crashing.

**Comment by ryny24** [comment]
This might be a hardware issue. It eventually crashed on 1.10.23. Closing this now. Sorry.
