### ISSUE TITLE
`panic` in `findBeaconAncestor`

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#25787]
Crash on one of the bootnodes

`Geth/v1.11.0-unstable-6f9bc7b0-20220906/linux-amd64/go1.18.1`

```
INFO [09-15|23:44:14.693] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [09-15|23:44:14.693]
INFO [09-15|23:44:15.431] Loaded most recent local header number=15,542,291 hash=cbd5f0..a3fe79 td=58,750,003,716,598,352,816,469 age=28m16s
INFO [09-15|23:44:15.432] Loaded most recent local full block number=15,540,935 hash=207c21..5a6d5d td=58,750,003,716,598,352,816,469 age=5h3m4s
INFO [09-15|23:44:15.432] Loaded most recent local fast block number=15,542,291 hash=cbd5f0..a3fe79 td=58,750,003,716,598,352,816,469 age=28m16s
INFO [09-15|23:44:15.432] Loaded most recent local finalized block number=15,542,052 hash=21abe4..41b981 td=58,750,003,716,598,352,816,469 age=1h16m40s
INFO [09-15|23:44:15.432] Loaded last fast-sync pivot marker number=15,489,901
WARN [09-15|23:44:15.432] Enabling snapshot recovery chainhead=15,540,935 diskbase=15,542,283
WARN [09-15|23:44:15.433] Loaded snapshot journal diffs=missing
WARN [09-15|23:44:15.433] Snapshot is not continuous with chain snaproot=f135fc..60bc0c chainroot=55a45e..7d85e4
INFO [09-15|23:44:15.433] Loaded local transaction journal transactions=0 dropped=0
INFO [09-15|23:44:15.433] Resuming state snapshot generation root=f135fc..60bc0c in=2b33da..96de26 at=1b5041..895bdb accounts=30,662,550 slots=146,387,588 storage=12.03GiB dangling=0 elapsed="139.901µs"
INFO [09-15|23:44:15.434] Regenerated local transaction journal transactions=0 accounts=0
WARN [09-15|23:44:15.434] Switch sync mode from snap sync to full sync
INFO [09-15|23:44:15.434] Chain post-TTD, sync via beacon client
INFO [09-15|23:44:15.434] Gasprice oracle is ignoring threshold set threshold=2
WARN [09-15|23:44:15.434] Old unclean shutdowns found count=190
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:41:30+0000 age=2m45s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:41:43+0000 age=2m32s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:02+0000 age=2m13s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:12+0000 age=2m3s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:22+0000 age=1m53s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:30+0000 age=1m45s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:37+0000 age=1m38s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:46+0000 age=1m29s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:42:59+0000 age=1m16s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:43:16+0000 age=59s
WARN [09-15|23:44:15.434] Unclean shutdown detected booted=2022-09-15T23:43:49+0000 age=26s
INFO [09-15|23:44:15.434] Allocated cache and file handles database=/root/.ethereum/geth/les.server cache=16.00MiB handles=16
INFO [09-15|23:44:15.456] Trie missing, state snapshotting paused root=f135fc..60bc0c in=2b33da..96de26 at=1b5041..895bdb accounts=30,662,550 slots=146,387,588 storage=12.03GiB dangling=0 elapsed=22.247ms
INFO [09-15|23:44:15.489] Configured checkpoint oracle address=0x9a9070028361F7AAbeB3f2F2Dc07F82C4a98A02a signers=5 threshold=2
INFO [09-15|23:44:15.490] Loaded latest checkpoint section=473 head=4373f2..2811cb chtroot=6c987f..a0d3de bloomroot=7082f3..696e6d
WARN [09-15|23:44:15.490] Engine API enabled protocol=eth
INFO [09-15|23:44:15.490] Starting peer-to-peer node instance=Geth/v1.11.0-unstable-6f9bc7b0-20220906/linux-amd64/go1.18.1
INFO [09-15|23:44:15.522] Mapped network port proto=tcp extport=30303 intport=30303 interface=ExtIP(191.234.162.198)
INFO [09-15|23:44:15.522] Mapped network port proto=udp extport=30303 intport=30303 interface=ExtIP(191.234.162.198)
INFO [09-15|23:44:15.565] New local node record seq=1633 id=32f7e89d30e83b68 ip=191.234.162.198 udp=30303 tcp=30303
INFO [09-15|23:44:15.620] Started P2P networking self=enode://103858bdb88756c71f15e9b5e09b56dc1be52f0a5021d46301dbbfb7e130029cc9d0d6f73f693bc29b665770fff7da4d34f3c6379fe12721b5d7a0bcb5ca1fc1@191.234.162.198:30303
INFO [09-15|23:44:15.622] IPC endpoint opened url=/root/.ethereum/geth.ipc
INFO [09-15|23:44:15.622] Loaded JWT secret file path=/execution-auth.jwt crc32=0xba247cd0
INFO [09-15|23:44:15.623] WebSocket enabled url=ws://[::]:8551
INFO [09-15|23:44:15.623] HTTP server started endpoint=[::]:8551 auth=true prefix= cors=localhost vhosts=*
INFO [09-15|23:44:15.623] Stats daemon started
WARN [09-15|23:44:17.143] Ignoring payload with missing parent number=15,542,424 hash=72e967..35217c parent=14f7f8..8a14f6
INFO [09-15|23:44:17.287] Forkchoice requested sync to new head number=15,542,424 hash=72e967..35217c
INFO [09-15|23:44:17.289] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa92a88]
goroutine 1381 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findBeaconAncestor(0xc0001b4780)
github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:220 +0xe8
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0001b4780, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
github.com/ethereum/go-ethereum/eth/downloader/downloader.go:527 +0x911
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x100000000000003?, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
github.com/ethereum/go-ethereum/eth/downloader/downloader.go:439 +0x505
github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).resume.func1()
github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:108 +0x96
created by github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).resume
github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:98 +0x132
WARN [09-15|23:44:17.143] Ignoring payload with missing parent number=15,542,424 hash=72e967..35217c parent=14f7f8..8a14f6
INFO [09-15|23:44:17.287] Forkchoice requested sync to new head number=15,542,424 hash=72e967..35217c
INFO [09-15|23:44:17.289] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa92a88]
goroutine 1381 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findBeaconAncestor(0xc0001b4780)
github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:220 +0xe8
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0001b4780, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
github.com/ethereum/go-ethereum/eth/downloader/downloader.go:527 +0x911
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x100000000000003?, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
github.com/ethereum/go-ethereum/eth/downloader/downloader.go:439 +0x505
github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).resume.func1()
github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:108 +0x96
created by github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).resume
github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:98 +0x132
```

**Comment by holiman** [comment]
Duplicate of https://github.com/ethereum/go-ethereum/issues/26300

**Comment by holiman** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/26451
