### ISSUE TITLE
geth crashed with error "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#2581]
#### System information

Geth Version: 1.3.6
Protocol Versions: [63 62 61]
Go Version: go1.5.1
OS: linux Ubuntu14.04

#### Actual behaviour

I set up a private network with 4 geth nodes, one node crashed with error saying

I0518 15:42:58.128905    6956 blockchain.go:1220] [1463557378128899797] inserted block #2149 (0 TXs 0 G 0 UNCs) (9627ba0f...). Took 2.866448ms
I0518 15:42:58.128962    6956 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 2.929771ms. #2149 [9627ba0f / 9627ba0f]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x595594]

#### Steps to reproduce the behaviour

None.

#### Backtrace

```text
3928 I0518 15:42:58.128522    6956 database_util.go:346] stored block receipts [9627ba0fâ<80>¦]
3929 I0518 15:42:58.128539    6956 blockchain.go:1309] Chain split detected @ 50d950b5. Reorganising chain from #2148 aee98dc2 to 9627ba0f
3930 I0518 15:42:58.128823    6956 database_util.go:311] stored block total difficulty [9627ba0fâ<80>¦]: 490965963
3931 I0518 15:42:58.128854    6956 database_util.go:296] stored block body [9627ba0fâ<80>¦]
3932 I0518 15:42:58.128892    6956 database_util.go:281] stored header #2149 [9627ba0fâ<80>¦]
3933 I0518 15:42:58.128905    6956 blockchain.go:1220] [1463557378128899797] inserted block #2149 (0 TXs 0 G 0 UNCs) (9627ba0f...). Took 2.866448m     s
3934 I0518 15:42:58.128962    6956 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 2.929771ms. #2149 [9627ba0f / 9     627ba0f]
3935 panic: runtime error: invalid memory address or nil pointer dereference
3936 [signal 0xb code=0x1 addr=0x0 pc=0x595594]
3937
3938 goroutine 40 [running]:
3939 math/big.(*Int).Cmp(0xc8210ccba0, 0x0, 0xc8201b4520)
3940         /usr/lib/go/src/math/big/int.go:314 +0x24
3941 github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlock(0xc8201b4500, 0xc820e26100, 0xc8217d1b00, 0x0, 0x0)
3942         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/blockchain.go:1070 +0x2f     d
3943 github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc8201f2870)
3944         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/worker.go:299 +0xe12
3945 created by github.com/ethereum/go-ethereum/miner.newWorker
3946         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/worker.go:142 +0x3e0
3947
3948 goroutine 1 [chan receive, 9 minutes]:
3949 main.run(0xc820226240)
3950         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:418 +0x1fd
3951 github.com/codegangsta/cli.(*App).Run(0xc820226120, 0xc82005e300, 0x17, 0x18, 0x0, 0x0)
3952         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/codegangsta/cli/app.go:180 +0x1028
3953 main.main()
3954         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:373 +0x93
3955
3956 goroutine 17 [syscall, 9 minutes, locked to thread]:
3957 runtime.goexit()
3958         /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
3959
3960 goroutine 20 [syscall, 9 minutes]:
3961 os/signal.loop()
3962         /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
3963 created by os/signal.init.1
3964         /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
3965
3965
3966 goroutine 21 [chan receive]:
3967 github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x1709400)
3968         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x67
3969 created by github.com/ethereum/go-ethereum/logger/glog.init.1
3970         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x6f
3971
3972 goroutine 22 [select, 8 minutes]:
3973 github.com/ethereum/go-ethereum/logger.dispatchLoop()
3974         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x624
3975 created by github.com/ethereum/go-ethereum/logger.init.1
3976         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x2b
3977
3978 goroutine 68 [runnable]:
3979 github.com/ethereum/go-ethereum/eth/filters.(*FilterSystem).filterLoop(0xc8202797c0)
3980         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:     116 +0x613
3981 created by github.com/ethereum/go-ethereum/eth/filters.NewFilterSystem
3982         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:     53 +0x2ed
3983
3984 goroutine 67 [IO wait, 9 minutes]:
3985 net.runtime_pollWait(0x7f31fa30f418, 0x72, 0xc8200640a0)
3986         /usr/lib/go/src/runtime/netpoll.go:157 +0x60
3987 net.(*pollDesc).Wait(0xc821636530, 0x72, 0x0, 0x0)
3988         /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
3989 net.(*pollDesc).WaitRead(0xc821636530, 0x0, 0x0)
3990         /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
3991 net.(*netFD).accept(0xc8216364d0, 0x0, 0x7f31fa310090, 0xc82000dea0)
3992         /usr/lib/go/src/net/fd_unix.go:408 +0x27c
3993 net.(*UnixListener).AcceptUnix(0xc82000dca0, 0xc8216a0ed8, 0x0, 0x0)
3994         /usr/lib/go/src/net/unixsock_posix.go:304 +0x53
3995 net.(*UnixListener).Accept(0xc82000dca0, 0x0, 0x0, 0x0, 0x0)
3996         /usr/lib/go/src/net/unixsock_posix.go:314 +0x41
3997 github.com/ethereum/go-ethereum/rpc/comms.ipcLoop(0xc82000dbc0, 0x1e, 0x0, 0xc82000dbe0, 0x7f31fa311498, 0xc82000dca0)
3998         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/comms/ipc.go:116 +0x1aa
3999 created by github.com/ethereum/go-ethereum/rpc/comms.StartIpc
4000         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/comms/ipc.go:107 +0xd1
4001
4002 goroutine 6 [select]:
4003 github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc8202420e0)
4004         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x271
4005 created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
4006         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x26b
4007
4008 goroutine 69 [select]:
4009 github.com/ethereum/go-ethereum/xeth.(*XEth).start(0xc821638000)
4010         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/xeth/xeth.go:127 +0x779
4011 created by github.com/ethereum/go-ethereum/xeth.New
4012         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/xeth/xeth.go:118 +0x618
4013
4014 goroutine 70 [IO wait]:
4015 net.runtime_pollWait(0x7f31fa30f4d8, 0x72, 0xc8200640a0)
4016         /usr/lib/go/src/runtime/netpoll.go:157 +0x60
4017 net.(*pollDesc).Wait(0xc82018a060, 0x72, 0x0, 0x0)
4018         /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
4019 net.(*pollDesc).WaitRead(0xc82018a060, 0x0, 0x0)
4020         /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
4021 net.(*netFD).accept(0xc82018a000, 0x0, 0x7f31fa310090, 0xc8316c0d60)
4022         /usr/lib/go/src/net/fd_unix.go:408 +0x27c
4023 net.(*TCPListener).AcceptTCP(0xc8200280a8, 0xc82003beb0, 0x0, 0x0)
4024         /usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
4025 net.(*TCPListener).Accept(0xc8200280a8, 0x0, 0x0, 0x0, 0x0)
4026         /usr/lib/go/src/net/tcpsock_posix.go:264 +0x3d
4027 net/http.(*Server).Serve(0xc8200b80c0, 0x7f31fc466968, 0xc8200280a8, 0x0, 0x0)
4028         /usr/lib/go/src/net/http/server.go:1887 +0xb3
4029 created by github.com/ethereum/go-ethereum/rpc/comms.listenHTTP
4030         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/rpc/comms/http.go:188 +0x2ad
4031
4032 goroutine 10 [chan receive, 8 minutes]:
4033 github.com/ethereum/go-ethereum/logger.sysLoop(0x7f31fc45e628, 0xc82025c3e0, 0xc820014fc0, 0xc82000e0e0)
4034         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:117 +0x51
4035 created by github.com/ethereum/go-ethereum/logger.dispatchLoop.func1
4036         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:77 +0xdb
4037
4038 goroutine 29 [select, 8 minutes]:
4039 github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc82000a420)
4040         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x47c
4041 created by github.com/syndtr/goleveldb/leveldb.openDB
4042         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db.go:126 +0x7fc
4043
4044 goroutine 30 [select]:
4045 github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc82000a420)
4046         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14b
4047 created by github.com/syndtr/goleveldb/leveldb.openDB
4048         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db.go:127 +0x81e
4049
4050 goroutine 11 [select, 8 minutes]:
4051 github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc82000a420)
4052         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x7c8
4053 created by github.com/syndtr/goleveldb/leveldb.openDB
4054         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db.go:130 +0x86a
4055
4056 goroutine 12 [select, 9 minutes]:
4057 github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc82000a420)
4058         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x253
4059 created by github.com/syndtr/goleveldb/leveldb.openDB
4060         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db.go:131 +0x88c
4061
4062 goroutine 13 [select, 9 minutes]:
4063 github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc82000a420)
4064         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db_write.go:37 +0x1a2
4065 created by github.com/syndtr/goleveldb/leveldb.openDB
4066         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db.go:132 +0x8ae
4067
4068 goroutine 31 [select]:
4069 github.com/ethereum/go-ethereum/ethdb.(*LDBDatabase).meter(0xc82025e180, 0xb2d05e00)
4070         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/ethdb/database.go:255 +0xa96
4071 created by github.com/ethereum/go-ethereum/ethdb.(*LDBDatabase).Meter
4072         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/ethdb/database.go:187 +0x591
4073
4074 goroutine 32 [select]:
4075 github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc8200b60e0)
4076         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x271
4077 created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
4078         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x26b
4079
4080 goroutine 14 [select, 9 minutes]:
4081 github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc82000a580)
4082         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x47c
4083 created by github.com/syndtr/goleveldb/leveldb.openDB
4084         /build/ethereum-f3n5n5/ethereum-1.3.6+72trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.     com/syndtr/goleveldb/leveldb/db.go:126 +0x7fc
4085
```

**Comment by fjl** [comment]
It is very likely that this crash won't occur with geth 1.4. From the source file names it looks like you are using the PPA. Please update to geth 1.4.

**Comment by obscuren** [comment]
Please do as @fjl suggested and open a new issue. Thanks!

**Comment by dianabalasa** [comment]
Hi,

I get this error message when I am trying to set up an environment as Geth node:

**C:\Windows\system32>geth --datadir "C:\Windows\chaindata" --rpc --rpcapi "eth,we
b3,miner,admin,personal,net" --rpccorsdomain "*" --nodiscover --networkid 15**

**Fatal: Error starting protocol stack: listen tcp :30303: bind: Only one usage of
 each socket address (protocol/network address/port) is normally permitted.**

If I change the command to include another port other than 30303, I get the same error message as hievan.

**C:\Windows\system32>geth --datadir "C:\Windows\chaindata" --rpc --rpcapi "eth,we
b3,miner,admin,personal,net" --rpccorsdomain "*" --nodiscover --networkid 15 --p
ort 22222
INFO [05-12|16:22:13] Maximum peer count                       ETH=25 LES=0 tota
l=25
INFO [05-12|16:22:13] Starting peer-to-peer node               instance=Geth/v1.
8.7-stable-66432f38/windows-amd64/go1.10.1
INFO [05-12|16:22:13] Allocated cache and file handles         database=C:\\Wind
ows\\chaindata\\geth\\chaindata cache=768 handles=1024
INFO [05-12|16:22:13] Initialised chain configuration          config="{ChainID:
 42 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byza
ntium: 4 Constantinople: <nil> Engine: clique}"
INFO [05-12|16:22:13] Initialising Ethereum protocol           versions="[63 62]
" network=15
INFO [05-12|16:22:13] Loaded most recent local header          number=0 hash=f44
428.7e61f7 td=1
INFO [05-12|16:22:13] Loaded most recent local full block      number=0 hash=f44
428.7e61f7 td=1
INFO [05-12|16:22:14] Loaded most recent local fast block      number=0 hash=f44
428.7e61f7 td=1
INFO [05-12|16:22:14] Loaded local transaction journal         transactions=0 dr
opped=0
INFO [05-12|16:22:14] Regenerated local transaction journal    transactions=0 ac
counts=0
INFO [05-12|16:22:14] Starting P2P networking
INFO [05-12|16:22:14] RLPx listener up                         self="enode://c66
3aa3fbcbe073e57e920b308ea8edb476fb355158379268af46f74f0cb17158866ea0312df7848451
7ef58fe263921d62bf1a450a3d5d11a2226a17ca4d9e2@[::]:22222?discport=0"
INFO [05-12|16:22:14] Blockchain manager stopped
INFO [05-12|16:22:14] Stopping Ethereum protocol
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa72182]

goroutine 59 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc042059ec
0)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.
go:434 +0x2f2
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.
go:113 +0x10b**

Please bear in mind that I have enabled port 22222 on the firewall.
The O.S I am running the commands on is Windows 7 x64. 

I have also tried to force the system to choose a port for the node connectivity, but I get the same error message related to the memory address.

Can someone help me with this?

**Comment by mavericklin** [comment]
This also happens to me when using Geth 1.8.21, downgrade to 1.8.17 solves the issue.
