### ISSUE TITLE
[swarm] crash due to out of bound string index

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2605]
#### System information

swarm crashes on unsafe string index 

#### Backtrace

````
I0523 16:11:24.846222 swarm/network/syncdb.go:216] [BZZ] syncDb[5af75b13:2]: saved 0 keys (saved counter at 0)
panic: runtime error: slice bounds out of range

goroutine 104 [running]:
github.com/ethereum/go-ethereum/swarm/network.storeRequestMsgData.String(0xc828ae7940, 0x20, 0x20, 0xc824c9ac50, 0x8, 0x8, 0x3132ef63077c5a14, 0x0, 0x0, 0x0, ...)
        /home/tron/go/src/github.com/ethereum/go-ethereum/swarm/network/messages.go:80 +0x3bf
github.com/ethereum/go-ethereum/swarm/network.(*bzz).handle(0xc820112380, 0x0, 0x0)
        /home/tron/go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:223 +0xabe
github.com/ethereum/go-ethereum/swarm/network.run(0xc820123ba0, 0x7fb3ac443c30, 0xc8203a72f0, 0xc8201ca1e0, 0xc8203af0c0, 0xc8203afb90, 0xc82032e540, 0xc8219070c0, 0x7fb3ac444838, 0xc82032fab0, ...)
        /home/tron/go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:182 +0x2bb
github.com/ethereum/go-ethereum/swarm/network.Bzz.func1(0xc8219070c0, 0x7fb3ac444838, 0xc82032fab0, 0x0, 0x0)
        /home/tron/go/src/github.com/ethereum/go-ethereum/swarm/network/protocol.go:123 +0x9d
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc82032fab0, 0xc8219070c0)
        /home/tron/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:303 +0x8c
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /home/tron/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:312 +0x304
````

**Comment by zelig** [comment]
fixed on current swarm branch
