### ISSUE TITLE
`panic: interface conversion: interface {} is nil, not *simplelru.entry`

### ISSUE THREAD

**Issue by SeaMonkey82** [ethereum/go-ethereum#26163]
#### System information

Geth version: 

Geth
Version: 1.11.0-unstable
Git Commit: ea65edaa28286dad533df1b6defa73ecab2538b4
Git Commit Date: 20221111
Architecture: amd64
Go Version: go1.18.3
Operating System: linux
GOPATH=
GOROOT=go

CL client & version: Nimbus beacon node v22.10.1-04cbea-stateofus

#### Expected behaviour
Sync normally

#### Actual behaviour
```
INFO [11-11|12:54:48.876] Forkchoice requested sync to new head    number=7,935,224 hash=9f28e7..3951ec
panic: interface conversion: interface {} is nil, not *simplelru.entry

goroutine 5605 [running]:
github.com/hashicorp/golang-lru/simplelru.(*LRU).removeElement(0xc0004c70e0?, 0xc09f626608?)
        github.com/hashicorp/golang-lru@v0.5.5-0.20210104140557-80c98217689d/simplelru/lru.go:172 +0x107
github.com/hashicorp/golang-lru/simplelru.(*LRU).RemoveOldest(0x1320840?)
        github.com/hashicorp/golang-lru@v0.5.5-0.20210104140557-80c98217689d/simplelru/lru.go:115 +0x3d
github.com/ethereum/go-ethereum/common/lru.(*SizeConstrainedLRU).Add(0xc0056fad50, {0x7, 0xa5, 0xab, 0xba, 0x47, 0x4d, 0x23, 0x57, 0xc7, ...}, ...)
        github.com/ethereum/go-ethereum/common/lru/blob_lru.go:66 +0x225
github.com/ethereum/go-ethereum/core/state.(*cachingDB).ContractCode(0xc0056fad80, {0xf0, 0xa0, 0x37, 0x32, 0xbc, 0xff, 0xe0, 0x4c, 0xe2, ...}, ...)
        github.com/ethereum/go-ethereum/core/state/database.go:184 +0xf9
github.com/ethereum/go-ethereum/core/state.(*stateObject).Code(0xc0659a01e0, {0x183dc30, 0xc0056fad80})
        github.com/ethereum/go-ethereum/core/state/state_object.go:465 +0x1b3
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetCode(0xc0650a61c0, {0xbf, 0xe6, 0x8b, 0x62, 0xd3, 0x29, 0xe1, 0xb6, 0x30, ...})
        github.com/ethereum/go-ethereum/core/state/statedb.go:290 +0x57
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc065df07e0, {0x1832160, 0xc05afd9fe0}, {0xbf, 0xe6, 0x8b, 0x62, 0xd3, 0x29, 0xe1, ...}, ...)
        github.com/ethereum/go-ethereum/core/vm/evm.go:219 +0x9bd
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc056747b80)
        github.com/ethereum/go-ethereum/core/state_transition.go:335 +0x779
github.com/ethereum/go-ethereum/core.ApplyMessage(0x14cb660?, {0x18407b0?, 0xc05e87a480?}, 0xc065980860?)
        github.com/ethereum/go-ethereum/core/state_transition.go:186 +0x2a
github.com/ethereum/go-ethereum/core.applyTransaction({0xc05afd9e90, {0xf2, 0x21, 0xf2, 0xc9, 0x29, 0xaa, 0x1f, 0x6b, 0x55, ...}, ...}, ...)
        github.com/ethereum/go-ethereum/core/state_processor.go:101 +0x1c6
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc0004c7220, 0xc00b159280, 0xc0650a61c0, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}})
        github.com/ethereum/go-ethereum/core/state_processor.go:82 +0x885
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00035e480, {0xc01d56e000?, 0x2db, 0x350}, 0x0, 0x1)
        github.com/ethereum/go-ethereum/core/blockchain.go:1706 +0x1ec4
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSideChain(0xc00035e480, 0x154bcaf?, 0xc0172c5398)
        github.com/ethereum/go-ethereum/core/blockchain.go:1930 +0x19cc
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00035e480, {0xc009af38c0?, 0x1, 0x1}, 0x1, 0x1)
        github.com/ethereum/go-ethereum/core/blockchain.go:1577 +0xa4e
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00035e480, {0xc009af38c0?, 0x1, 0x1})
        github.com/ethereum/go-ethereum/core/blockchain.go:1476 +0xb51
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc023fb0d80, {0xc009af38b0, 0x1, 0x3?})
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1551 +0x45a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc023fb0d80, 0x0, 0x1)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1518 +0x17d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func9()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:622 +0x25
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:634 +0x70
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:634 +0x5f
```

#### Steps to reproduce the behaviour
`./go-ethereum/build/bin/geth --datadir /mnt/goerli/nimbus-geth --http --http.api="engine,eth,web3,net,debug" --http.corsdomain "*" --goerli --syncmode=snap --authrpc.jwtsecret=/home/seamonkey/eth/jwtsecret console --nat=extip:1.2.3.4 --port 13459 --http.corsdomain "moz-extension://a0ffd254-28a5-4292-bf02-4195ced390d3,moz-extension://d2439d33-79aa-4ee4-92a4-3cc0fc4ecb7f,moz-extension://f6780ea6-1162-4fe5-b170-c37b605ae299" --http.addr "192.168.0.2" --http.port 5067 --authrpc.port 8552`

`./nimbus-eth2/build/nimbus_beacon_node --network=goerli --web3-url=http://127.0.0.1:8552 --log-level=INFO --data-dir=/mnt/goerli/nimbus-geth --nat=extip:1.2.3.4 --tcp-port=13460 --udp-port=13460 --graffiti="nimbus-geth seamonkey.tech" --rest --rest-port=5059 --suggested-fee-recipient="0xA721da3d06813E764E94A23E377cC3E1729fCFD5" --jwt-secret=/home/seamonkey/eth/jwtsecret --payload-builder=on --payload-builder-url="http://localhost:18550"`

**Comment by holiman** [comment]
Thanks for the report, investigating!
