### ISSUE TITLE
TraceBlock RPC call crashed the node

### ISSUE THREAD

**Issue by bitrocks** [ethereum/go-ethereum#26347]
#### System information

Geth version: master
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Linux
Commit hash : develop
#### Expected behaviour
According to the geth implementation:
https://github.com/ethereum/go-ethereum/blob/262bd38fce0317f0123947add02cbb3ccde75f59/rpc/service.go#L194-L203
The defer function would catch the panic and throw an internalServerError, without crashing node. 

#### Actual behaviour
Crash the node

#### Steps to reproduce the behaviour
Listen to newHeads event, and call the `debug_traceBlock` immediately, after server blocks would crashes.

I check the node logs, and api like `debug_traceCall` failure can be handled as expected.

#### Backtrace

````
INFO [12-11|06:19:00.798] Imported new potential chain segment     number=16,159,627 hash=244dd4..344bce blocks=1 txs=125  mgas=25.645 elapsed=472.980ms    mgasps=54.221  dirty=1022.01MiB
INFO [12-11|06:19:00.861] Chain head was updated                   number=16,159,627 hash=244dd4..344bce root=450255..ab1921 elapsed=5.134407ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10a7354]

goroutine 88650593 [running]:
math/big.(*Int).Sign(...)
        /home/ec2-user/go/src/math/big/int.go:39
github.com/ethereum/go-ethereum/eth/tracers/native.(*account).exists(...)
        /data/go-ethereum/eth/tracers/native/prestate.go:48
github.com/ethereum/go-ethereum/eth/tracers/native.(*prestateTracer).CaptureTxEnd(0x4030471860, 0x40b25cd460?)
        /data/go-ethereum/eth/tracers/native/prestate.go:229 +0x664
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb.func1()
        /data/go-ethereum/core/state_transition.go:296 +0x38
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0x40bdffe300)
        /data/go-ethereum/core/state_transition.go:361 +0xbd8
github.com/ethereum/go-ethereum/core.ApplyMessage(0x1773578?, {0x177d0c8?, 0x40b093e510?}, 0xc18e41b0e6abebfe?)
        /data/go-ethereum/core/state_transition.go:186 +0x2c
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceTx(0x40036885d0, {0x1773578, 0x40a9390300}, {0x177d0c8, 0x40b093e510}, 0x406025dd10, {0x15c2028, 0x15c2030, 0x40be03e300, {0xfe, ...}, ...}, ...)
        /data/go-ethereum/eth/tracers/api.go:935 +0x418
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceBlock.func1()
        /data/go-ethereum/eth/tracers/api.go:632 +0x46c
created by github.com/ethereum/go-ethereum/eth/tracers.(*API).traceBlock
        /data/go-ethereum/eth/tracers/api.go:621 +0x428
INFO [12-11|06:35:55.339] Starting Geth on Ethereum mainnet...
INFO [12-11|06:35:55.340] Bumping default cache on mainnet         provided=1024 updated=409
````

When submitting logs: please submit them as text and not screenshots.

**Comment by bitrocks** [comment]
The issue need further confirmation
