### ISSUE TITLE
provider access race condition

### ISSUE THREAD

**Issue by NakedKoala** [ethereum/go-ethereum#26364]
My program uses `ethclient.Client` and `gethclient.Client` from multiple goroutines and it has experienced infrequent error due to race condition issues related to http and websocket.

In the beginning, all my goroutines try to use the same singleton instance of`Client`.

To address the issue, I refactor the code to have each goroutine creating its own provider via 

```
ethclient.Dial("http://127.0.0.1:8545")
ethclient.Dial("ws://127.0.0.1:8546")
rpc.Dial("http://127.0.0.1:8545")
rpc.Dial("ws://127.0.0.1:8546")

```

Note that I have a large number (can be up to 2 gouroutines per second) of ephemeral goroutines each creating its own provider to avoid race condition. 

However,  I still run into http & ws related race condition error  even after assigning unique provider to each goroutine.

```
goroutine 19491 [IO wait]:
internal/poll.runtime_pollWait(0x7f4cf147c700, 0x72)
        /usr/local/go/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0025c2080?, 0xc003f39c00?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0025c2080, {0xc003f39c00, 0x400, 0x400})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0025c2080, {0xc003f39c00?, 0x7f4cf8167c20?, 0x0?})
        /usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000ab4490, {0xc003f39c00?, 0x981c00?, 0xc002ecc380?})
        /usr/local/go/src/net/net.go:183 +0x45
bufio.(*Reader).fill(0xc003ca95c0)
        /usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc003ca95c0, 0x2)
        /usr/local/go/src/bufio/bufio.go:144 +0x5d
github.com/gorilla/websocket.(*Conn).read(0xc003eb91e0, 0xc001eaa0c0?)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x2c
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc003eb91e0)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x7b
github.com/gorilla/websocket.(*Conn).NextReader(0xc003eb91e0)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0xcc
github.com/gorilla/websocket.(*Conn).ReadJSON(0x18?, {0x927640, 0xc001ddd428})
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:50 +0x27
github.com/ethereum/go-ethereum/rpc.(*jsonCodec).readBatch(0xc002a35270)
        /root/workspace/go-ethereum/rpc/json.go:214 +0x4d
github.com/ethereum/go-ethereum/rpc.(*Client).read(0xc0025c2400, {0xadfd08, 0xc0009582d0})
        /root/workspace/go-ethereum/rpc/client.go:633 +0xb7
created by github.com/ethereum/go-ethereum/rpc.(*Client).dispatch
        /root/workspace/go-ethereum/rpc/client.go:557 +0x155

goroutine 19528 [select]:
github.com/ethereum/go-ethereum/rpc.(*Client).dispatch(0xc003de2880, {0xadfd08?, 0xc0007e3b00})
        /root/workspace/go-ethereum/rpc/client.go:560 +0x2cc
created by github.com/ethereum/go-ethereum/rpc.initClient
        /root/workspace/go-ethereum/rpc/client.go:224 +0x311

goroutine 19501 [select]:
github.com/ethereum/go-ethereum/rpc.(*Client).dispatch(0xc00080a280, {0xadfd08?, 0xc003703560})
        /root/workspace/go-ethereum/rpc/client.go:560 +0x2cc
created by github.com/ethereum/go-ethereum/rpc.initClient
        /root/workspace/go-ethereum/rpc/client.go:224 +0x311
exit status 2

```

Questions:
1.Is access of `Client` from multiple goroutines thread-safe without a global mutex ? 
2.Is creating multiple instances of provider from different goroutine thread-safe ? 
3.Is creating a large number of ephemeral instances of provider anti-pattern ? ( ie: would too many instances create unnecessary stress on the node ? )
4.If answer to question 3 is yes, what is the best way to access provider from many goroutines safely  ? ( I am hesitant to use a global mutex to protect singleton provider as it can become performance bottleneck)

**Comment by karalabe** [comment]
We'd need to see the top of the crash dump, that's where the interesting thing is.

**Comment by mohammadfarari1360** [comment]
Nice .
Thank you

**Comment by NakedKoala** [comment]
Turns out the race condition was with my own code and data structure. Not a GETH issue. Apologies for not looking at the top of error dump.  Closing the issue
