### ISSUE TITLE
Panic: invalid RLP string size 269 (want 0 or 32) (decode path: [4]<-full)

### ISSUE THREAD

**Issue by stefanosstef** [ethereum/go-ethereum#26363]
#### System information

Geth version: Version: 1.10.26-stable
CL client & version: Prysm/v3.1.2/648ab9f2c249f1d06d0aad4328e8df429ceaf66c
OS & Version: Windows 10, 32gb ram

#### Actual behaviour
The node was working find until now. When I run it it works fine for some time, then it crashes with the same error.

#### Steps to reproduce the behaviour

run arguments:`geth.exe --ws --ws.addr 192.168.2.9 --ws.port 8546 --ws.api=eth,debug,net,web3,txpool --authrpc.jwtsecret n:\jwt.hex --datadir n:\ethereum --nat extip:[my ip]`

#### Backtrace

````
panic: node 25cd7b75aa0c01ed48d74bba5fc459b899cead4d7b7b615476190f3fb2b3e727: invalid RLP string size 269 (want 0 or 32) (decode path: [4]<-full)

goroutine 286329 [running]:
github.com/ethereum/go-ethereum/trie.mustDecodeNodeUnsafe({0xc144fac100, 0x20, 0x20}, {0xc0606fef00?, 0xc0606fef00?, 0x243?})
        github.com/ethereum/go-ethereum/trie/node.go:116 +0xd4
github.com/ethereum/go-ethereum/trie.(*Database).node(0xc00015acc0, {0x25, 0xcd, 0x7b, 0x75, 0xaa, 0xc, 0x1, 0xed, 0x48, ...})
        github.com/ethereum/go-ethereum/trie/database.go:382 +0x239
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc0c377ed80, {0xc11b4b216f?, 0x7ff7bca230b6?, 0xc0293cf268?}, {0xc040991770, 0x5, 0x41})
        github.com/ethereum/go-ethereum/trie/trie.go:560 +0xe5
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0x20?, {0x7ff7bdfcdf10?, 0xc12e35bf98?}, {0xc040991770, 0x41, 0x41}, 0x5)
        github.com/ethereum/go-ethereum/trie/trie.go:176 +0xe6
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0c377ed80?, {0x7ff7bdfccef0?, 0xc02b4bca00?}, {0xc040991770, 0xc040991770?, 0x4?}, 0x4)
        github.com/ethereum/go-ethereum/trie/trie.go:169 +0x3f4
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0x4b5fcbac153cdbf?, {0x7ff7bdfcdf10?, 0xc110fe2258?}, {0xc040991770, 0x41, 0x41}, 0x4)
        github.com/ethereum/go-ethereum/trie/trie.go:180 +0x176
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0c377ed80?, {0x7ff7bdfccef0?, 0xc02b780140?}, {0xc040991770, 0xc040991770?, 0x3?}, 0x3)
        github.com/ethereum/go-ethereum/trie/trie.go:169 +0x3f4
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xf22ab52246add520?, {0x7ff7bdfcdf10?, 0xc0fab7e798?}, {0xc040991770, 0x41, 0x41}, 0x3)
        github.com/ethereum/go-ethereum/trie/trie.go:180 +0x176
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0c377ed80?, {0x7ff7bdfccef0?, 0xc02b780000?}, {0xc040991770, 0xc040991770?, 0x2?}, 0x2)
        github.com/ethereum/go-ethereum/trie/trie.go:169 +0x3f4
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0x2a1af08016459ffc?, {0x7ff7bdfcdf10?, 0xc14db04438?}, {0xc040991770, 0x41, 0x41}, 0x2)
        github.com/ethereum/go-ethereum/trie/trie.go:180 +0x176
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0c377ed80?, {0x7ff7bdfccef0?, 0xc02b27be00?}, {0xc040991770, 0xc040991770?, 0x1?}, 0x1)
        github.com/ethereum/go-ethereum/trie/trie.go:169 +0x3f4
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xdcb05640591b6065?, {0x7ff7bdfcdf10?, 0xc110cde450?}, {0xc040991770, 0x41, 0x41}, 0x1)
        github.com/ethereum/go-ethereum/trie/trie.go:180 +0x176
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0293cfce8?, {0x7ff7bdfccef0?, 0xc0299c4640?}, {0xc040991770, 0xc182149090?, 0x20?}, 0x0)
        github.com/ethereum/go-ethereum/trie/trie.go:169 +0x3f4
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc0c377ed80, {0xc0c377edd0, 0x20, 0x20?})
        github.com/ethereum/go-ethereum/trie/trie.go:144 +0xd6
github.com/ethereum/go-ethereum/trie.(*StateTrie).TryGet(0xc0c377ed80, {0xc152978ce0?, 0xc152978ce0?, 0x20?})
        github.com/ethereum/go-ethereum/trie/secure_trie.go:92 +0x3d
github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop(0xc0a945cf70)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:337 +0x810
created by github.com/ethereum/go-ethereum/core/state.newSubfetcher
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:236 +0x1cb
````

**Comment by holiman** [comment]
Could you show what you get from doing the following: `geth --datadir n:\ethereum db get 0x25cd7b75aa0c01ed48d74bba5fc459b899cead4d7b7b615476190f3fb2b3e727`

That ought to spit out the `269` byte long malformed rlp from the db, it would be interesting to try and determine what it is.

**Comment by holiman** [comment]
Ping? Otherwise, we'll just close this, not much we can do on our end on this ticket.

**Comment by stefanosstef** [comment]
I apologize, I never saw the first reply. I later remembered that I had removed the triecache folder I saw in my system drive just before this issue showed up (I also had a triecache folder in my N drive). I figured it must have been from an older sync because I set the datadir to be in my new drive. Not sure if I need to set it also for the triecache dir but I see nothing in my system drive after the new sync.

I resynced the chain and it's fine so you can close the ticket

**Comment by vehicles4real** [comment]
Cool
