### ISSUE TITLE
panic: leveldb: internal key "lz\x04\xb4\x90", len=5: invalid length

### ISSUE THREAD

**Issue by cryptid-beast** [ethereum/go-ethereum#26445]
#### System information

Geth version: 1.10.26-stable
CL client & version: prysm@v3.2.0
OS & Version: Linux

#### Expected behaviour
for my node to sync

#### Actual behaviour
crashes. since its a service it restarts, but then it keeps crashing and restarting nonstop

#### Steps to reproduce the behaviour
not sure

#### Backtrace

````
WARN [01-06|17:11:21.178] Ignoring payload while snap syncing      number=16,346,264 hash=cb7ad4..eb65af
WARN [01-06|17:11:21.214] Ignoring payload while snap syncing      number=16,346,265 hash=b27d30..797bd8
WARN [01-06|17:11:21.232] Ignoring payload while snap syncing      number=16,346,266 hash=55ce63..289c2f
WARN [01-06|17:11:21.250] Ignoring payload while snap syncing      number=16,346,267 hash=ad6923..a50682
INFO [01-06|17:11:21.261] Forkchoice requested sync to new head    number=16,346,267 hash=ad6923..a50682
INFO [01-06|17:11:21.316] Block synchronisation started
INFO [01-06|17:11:21.355] Disabling direct-ancient mode            origin=16,298,895 ancient=14,811,135
INFO [01-06|17:11:21.393] Syncing: state download in progress      synced=42.42% state=80.60GiB accounts=305,917,363@19.08GiB slots=307,409,409@60.90GiB codes=110,221@643.75MiB eta=-24.603ms
INFO [01-06|17:11:32.292] Forkchoice requested sync to new head    number=16,346,331 hash=a70d09..ac7d7b
WARN [01-06|17:11:33.585] Checkpoint challenge timed out, dropping id=1a8f6dc2279f063e conn=dyndial addr=3.225.199.99:30303   type=Geth/v1.10.26-stable...
INFO [01-06|17:11:33.585] Syncing: state download in progress      synced=42.42% state=80.60GiB accounts=305,917,363@19.08GiB slots=307,409,409@60.90GiB codes=110,221@643.75MiB eta=-12.216s
INFO [01-06|17:11:40.164] Forkchoice requested sync to new head    number=16,346,395 hash=0d836d..d780ff
INFO [01-06|17:11:41.415] Imported new block headers               count=0    elapsed=10.266s number=16,300,943 hash=6bbf7d..2a2a19 age=6d17h27m  ignored=2048
INFO [01-06|17:11:42.114] Downloader queue stats                   receiptTasks=1617 blockTasks=1825 itemSize=24.99KiB throttle=8192
INFO [01-06|17:11:48.352] Forkchoice requested sync to new head    number=16,346,458 hash=e45bb2..f34ec2
INFO [01-06|17:11:52.679] Imported new block headers               count=0    elapsed=10.760s number=16,302,991 hash=89f6ef..6fcbc2 age=6d10h36m  ignored=2048
INFO [01-06|17:11:52.680] Imported new block receipts              count=0    elapsed=10.566s number=16,298,896 hash=8079c3..a41004 age=1w20m5s   size=0.00B ignored=1
WARN [01-06|17:11:52.680] Rewinding blockchain                     target=16,300,942
panic: leveldb: internal key "lz\x04\xb4\x90", len=5: invalid length
goroutine 65537 [running]:
github.com/syndtr/goleveldb/leveldb.internalKey.assert(...)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/key.go:111
github.com/syndtr/goleveldb/leveldb.internalKey.ukey({0xc1dfd979dd?, 0x5?, 0x0?})
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/key.go:116 +0xb4
github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0xc0003c2500, {0xc1dfd979dd, 0x5, 0x2e37}, {0xc1c48ae570, 0x11, 0x11})
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/comparer.go:38 +0x58
github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0xc1dfb7d180?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/reader.go:71 +0x23c
sort.Search(0xc12a7bccf0?, 0xc12a7bcc88)
        sort/search.go:65 +0x48
github.com/syndtr/goleveldb/leveldb/table.(*block).seek(0xc0c443a940, {0x18941f0?, 0xc0003c2500?}, 0x0, 0x415627?, {0xc1c48ae570?, 0x1513d00?, 0x702a01?})
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/reader.go:65 +0x98
github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Seek(0xc1dfb7f0e0, {0xc1c48ae570, 0x11, 0x11})
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/reader.go:232 +0xbf
github.com/syndtr/goleveldb/leveldb/table.(*Reader).newBlockIter(0xc00362e0d0, 0xc0c443a940, {0x1885360?, 0xc1dfa45330}, 0xc1c437b9e0, 0x1)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/reader.go:740 +0x154
github.com/syndtr/goleveldb/leveldb/table.(*Reader).NewIterator(0xc00362e0d0, 0xc1c437b9e0, 0x0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/reader.go:812 +0x191
github.com/syndtr/goleveldb/leveldb.(*tOps).newIterator(0x146a380?, 0xc0f1813000?, 0xc12a7bceb0?, 0xc12a7bceb0?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table.go:479 +0x69
github.com/syndtr/goleveldb/leveldb.(*version).getIterators(0xc000201ec0, 0x0?, 0x6f3d20?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/version.go:266 +0x2eb
github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc000958540, 0x0, {0x0, 0x0, 0x415627?}, 0xc1c437b9e0, 0x71d286?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_iter.go:41 +0xc6
github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc000958540, 0x100c12a7bd180?, {0x0?, 0x0?, 0x0?}, 0x400000c00fdb33, 0xc12a7bd258?, 0xc1c48b6d50?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_iter.go:79 +0x331
github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0xc000958540, 0xc1c48b6d10?, 0x5a951ef087cdba8f?)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:897 +0x14f
github.com/ethereum/go-ethereum/ethdb/leveldb.(*Database).NewIterator(0xc00002d400, {0xc1c48b6d40?, 0x9, 0x10?}, {0x0, 0x0, 0x20?})
        github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:228 +0x1cb
github.com/ethereum/go-ethereum/core/rawdb.ReadAllHashes({0x7f6a1c3d80d0, 0xc00594f908}, 0xc009cf8480?)
        github.com/ethereum/go-ethereum/core/rawdb/accessors_chain.go:70 +0x122
github.com/ethereum/go-ethereum/core.(*HeaderChain).SetHead(0xc000040090, 0xf8bb8e, 0xc12a7bd770, 0xc12a7bd730)
        github.com/ethereum/go-ethereum/core/headerchain.go:612 +0x737
github.com/ethereum/go-ethereum/core.(*BlockChain).setHeadBeyondRoot(0xc000092900, 0xf8bb8e, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        github.com/ethereum/go-ethereum/core/blockchain.go:710 +0x36e
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0xc000092900, 0x7f6ab094ffe8?)
        github.com/ethereum/go-ethereum/core/blockchain.go:535 +0x2f
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders.func1()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1273 +0x402
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders(0xc000178c00, 0x18838c0?, 0xc0fde98810?, 0x0, 0x1)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1295 +0x2e5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func7()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:618 +0x30
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:639 +0x70
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:639 +0x5f
````

any help would be really appreciated

**Comment by rjl493456442** [comment]
Leveldb reports there is a data corruption inside(`panic: leveldb: internal key "lz\x04\xb4\x90", len=5: invalid length`)
We can't do too much in this case, but just resync the node.

**Comment by holiman** [comment]
Yes, these types of errors indicate either that a disk corruption occurred (check your disk or RAM for errors), or that a very abrupt crash occurred.
