### ISSUE TITLE
Panic when starting with datadir.ancient

### ISSUE THREAD

**Issue by caevv** [ethereum/go-ethereum#26788]
```
 INFO [03-02|10:13:12.169] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
 INFO [03-02|10:13:12.175] Set global gas cap                       cap=50,000,000
 INFO [03-02|10:13:12.184] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
 INFO [03-02|10:13:12.185] Using pebble as the backing database
 INFO [03-02|10:13:12.185] Allocated cache and file handles         database=/var/lib/goethereum/geth/chaindata cache=2.00GiB handles=524,288
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb7e6e5]

 goroutine 1 [running]:
 github.com/ethereum/go-ethereum/core/rawdb.NewFreezer({0xc0001e26f0, 0x21}, {0x194272f, 0x11}, 0x0, 0x0?, 0xc00060dce0?)
 	github.com/ethereum/go-ethereum/core/rawdb/freezer.go:102 +0x165
 github.com/ethereum/go-ethereum/core/rawdb.NewChainFreezer(...)
 	github.com/ethereum/go-ethereum/core/rawdb/freezer.go:85
 github.com/ethereum/go-ethereum/core/rawdb.newChainFreezer({0xc0001e26f0?, 0x1b?}, {0x194272f?, 0xc00060dd78?}, 0x78?)
 	github.com/ethereum/go-ethereum/core/rawdb/chain_freezer.go:59 +0x34
 github.com/ethereum/go-ethereum/core/rawdb.NewDatabaseWithFreezer({0x7f2ca4c1d7e0?, 0xc000508030}, {0x7ffc562fef0b, 0x1b}, {0x194272f, 0x11}, 0x2f?)
 	github.com/ethereum/go-ethereum/core/rawdb/database.go:203 +0x8b
 github.com/ethereum/go-ethereum/core/rawdb.Open({{0x0, 0x0}, {0xc0008b0060, 0x22}, {0x7ffc562fef0b, 0x1b}, {0x194272f, 0x11}, 0x800, 0x80000, ...})
 	github.com/ethereum/go-ethereum/core/rawdb/database.go:383 +0xc5
 github.com/ethereum/go-ethereum/node.(*Node).OpenDatabaseWithFreezer(0xc0000eca80, {0x193807f, 0x9}, 0x800, 0x80000, {0x7ffc562fef0b, 0x1b}, {0x194272f, 0x11}, 0x0)
 	github.com/ethereum/go-ethereum/node/node.go:744 +0x358
 github.com/ethereum/go-ethereum/eth.New(0xc0000eca80, 0xc00070e700)
 	github.com/ethereum/go-ethereum/eth/backend.go:130 +0x506
 github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc000000000?, 0xc00070e700)
 	github.com/ethereum/go-ethereum/cmd/utils/flags.go:2003 +0x1b0
 main.makeFullNode(0xc00060fc20?)
 	github.com/ethereum/go-ethereum/cmd/geth/config.go:165 +0x185
 main.geth(0xc00071ab80)
 	github.com/ethereum/go-ethereum/cmd/geth/main.go:341 +0xf3
 github.com/urfave/cli/v2.(*App).RunContext(0xc0000cca80, {0x1c901b0?, 0xc000044070}, {0xc000040280, 0x28, 0x28})
 	github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:395 +0x1070
 github.com/urfave/cli/v2.(*App).Run(...)
 	github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:252
 main.main()
 	github.com/ethereum/go-ethereum/cmd/geth/main.go:266 +0x47
```

#### System information

Geth version: `geth version`
```
geth version
Geth
Version: 1.11.2-stable
Git Commit: 73b01f40ceb6bcb6f9f44c2a3d6f963b40452b47
Architecture: amd64
Go Version: go1.20.1
Operating System: linux
GOPATH=
GOROOT=
```
OS & Version: Ubuntu

Running on a docker from eth-docker and setting the volume of the datadir.ancient as a docker volume.

**Comment by MariusVanDerWijden** [comment]
Can you past your startup command?

**Comment by caevv** [comment]
I think the issue is that it doesn't have permission to access the folder.

**Comment by karalabe** [comment]
Then fix the permissions :)

**Comment by caevv** [comment]
Yes, done that already. The initial issue still stands, imo it shouldn't panic.

**Comment by holiman** [comment]
> imo it shouldn't panic.

If geth winds up in an situation where it is unable to continue, and unable to exit gracefully, it is correct to panic. 
If we are told to "do your thing" on a readonly disk, then it's not much to do. Nothing wrong with `panic` here.
