### ISSUE TITLE
Panic when requesting `eth_getBlockByNumber`

### ISSUE THREAD

**Issue by guybrush** [ethereum/go-ethereum#26906]
#### System information

Geth version: `v1.11.4`
CL client & version: e.g. lighthouse@v3.5.1
OS & Version: Linux
Chain: goerli

#### Steps to reproduce the behaviour

note: geth is syncing:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":67}'
{"jsonrpc":"2.0","id":67,"result":{"currentBlock":"0x8433f5","healedBytecodeBytes":"0x1460015c","healedBytecodes":"0xbbb1","healedTrienodeBytes":"0x2792a5b0","healedTrienodes":"0x694248","healingBytecode":"0x0","healingTrienodes":"0x454","highestBlock":"0x843457","startingBlock":"0x841abb","syncedAccountBytes":"0x84a9c74d","syncedAccounts":"0x8a776a","syncedBytecodeBytes":"0x3e9a972a","syncedBytecodes":"0x22de3","syncedStorage":"0x4b7b5cb","syncedStorageBytes":"0x3f4cf20d6"}}

$ curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["finalized",false],"id":67}' localhost:8545
{"jsonrpc":"2.0","id":67,"error":{"code":-32603,"message":"method handler crashed"}}
```

#### Backtrace

````
ERROR[03-16|09:35:46.816] RPC method eth_getBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 5036713 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
	github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x16f0540, 0x2761530})
	runtime/panic.go:884 +0x213
github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).BlockByNumber(0xc002554dc8, {0x40bc2d?, 0x175b2c0?}, 0x3?)
	github.com/ethereum/go-ethereum/eth/api_backend.go:128 +0x15f
github.com/ethereum/go-ethereum/internal/ethapi.(*BlockChainAPI).GetBlockByNumber(0xc000298aa0, {0x1c96e98, 0xc02f5c3d10}, 0xfffffffffffffffd, 0x4?)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:765 +0x5b
reflect.Value.call({0xc004e35f10?, 0xc004eaa1f0?, 0x7f82154bb3b8?}, {0x1935cf1, 0x4}, {0xc03bd39680, 0x4, 0x0?})
	reflect/value.go:586 +0xb07
reflect.Value.Call({0xc004e35f10?, 0xc004eaa1f0?, 0x1?}, {0xc03bd39680?, 0x2?, 0x16?})
	reflect/value.go:370 +0xbc
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc004eadd40, {0x1c96e98?, 0xc02f5c3d10}, {0xc032228d20, 0x14}, {0xc0220f3bf0, 0x2, 0x4d3837?})
	github.com/ethereum/go-ethereum/rpc/service.go:205 +0x3c5
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc032228d38?, {0x1c96e98?, 0xc02f5c3d10?}, 0xc0242fbf10, 0x2?, {0xc0220f3bf0?, 0x417230?, 0x1723380?})
	github.com/ethereum/go-ethereum/rpc/handler.go:513 +0x45
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc0357fd7a0, 0xc0220f3b30, 0xc0242fbf10)
	github.com/ethereum/go-ethereum/rpc/handler.go:459 +0x239
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc0357fd7a0, 0xc0220f3b90?, 0xc0242fbf10)
	github.com/ethereum/go-ethereum/rpc/handler.go:420 +0x237
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc0220f3b30)
	github.com/ethereum/go-ethereum/rpc/handler.go:256 +0x1a5
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
	github.com/ethereum/go-ethereum/rpc/handler.go:348 +0xc5
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	github.com/ethereum/go-ethereum/rpc/handler.go:344 +0x8d

````

**Comment by s1na** [comment]
This should be fixed on master via https://github.com/ethereum/go-ethereum/pull/26862. But it's not released yet. Feel free to re-open if it persists after this patch.
