### ISSUE TITLE
"panic: execution timeout at bigInt:1" happens since I raised version to 1.11.5

### ISSUE THREAD

**Issue by KentaroWaki** [ethereum/go-ethereum#27077]
#### System information

Geth version: `v1.11.5`
CL client & version: prysmaticlabs/prysm@v4.0.1
OS & Version: Linux(AmazonLinux)
vCPU: 8
RAM: 32GB
storage:
  type: gp3
  size: 2000 GiB
  IOPS: 3000
  throughput: 125

#### Expected behaviour
no panic

#### Actual behaviour
geth got panic

#### Steps to reproduce the behaviour
I have encountered the following PANIC at least twice since I raised it to 1.11.5 on 4/10 and geth stopped.
- running option added this time
```
--db.engine pebble
```

#### Backtrace

````
Apr  9 17:52:25 geth: panic: execution timeout at bigInt:1:23925(46) [recovered]
Apr  9 17:52:25 geth: panic: execution timeout at bigInt:1:23925(46) [recovered]
Apr  9 17:52:25 geth: panic: execution timeout at bigInt:1:23925(46) [recovered]
Apr  9 17:52:25 geth: panic: execution timeout at bigInt:1:23925(46)
Apr  9 17:52:25 geth: goroutine 2132519 [running]:
Apr  9 17:52:25 geth: encoding/json.(*encodeState).marshal.func1()
Apr  9 17:52:25 geth: encoding/json/encode.go:326 +0x6e
Apr  9 17:52:25 geth: panic({0x1817080, 0xc0a9407700})
Apr  9 17:52:25 geth: runtime/panic.go:884 +0x213
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).handleThrow(0xc095f18d80, {0x1817080, 0xc0a9407700})
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:730 +0x3b8
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).try.func1()
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:749 +0x45
Apr  9 17:52:25 geth: panic({0x1817080, 0xc0a9407700})
Apr  9 17:52:25 geth: runtime/panic.go:884 +0x213
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).handleThrow(0xc095f18d80, {0x1817080, 0xc0a9407700})
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:730 +0x3b8
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).runTryInner.func1()
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:772 +0x45
Apr  9 17:52:25 geth: panic({0x1817080, 0xc0a9407700})
Apr  9 17:52:25 geth: runtime/panic.go:884 +0x213
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).run(0xc095f18d80)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:577 +0x133
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).runTryInner(0xc095f18d80?)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:776 +0x70
Apr  9 17:52:25 geth: github.com/dop251/goja.(*baseJsFuncObject).__call(0xc02e059d40, {0xc00a2e8800?, 0x1, 0xc00a2e87f0?}, {0x0?, 0x0}, {0x1cb46c8?, 0xc056e43470?})
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/func.go:378 +0x705
Apr  9 17:52:25 geth: github.com/dop251/goja.(*baseJsFuncObject)._call(...)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/func.go:394
Apr  9 17:52:25 geth: github.com/dop251/goja.(*baseJsFuncObject).call(0x1674d80?, {{0x1cb46c8, 0xc056e43470}, {0xc00a2e8800, 0x1, 0x1}}, {0x0?, 0x0?})
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/func.go:402 +0x7a
Apr  9 17:52:25 geth: github.com/dop251/goja.(*baseJsFuncObject).Call(...)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/func.go:334
Apr  9 17:52:25 geth: github.com/dop251/goja.(*_builtinJSON_stringifyContext).str(0xc01b859810, {0x1cb4c20?, 0xc00a2e87b0?}, 0xc056e43140)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/builtin_json.go:283 +0x1e9
Apr  9 17:52:25 geth: github.com/dop251/goja.(*_builtinJSON_stringifyContext).jo(0xc01b859810, 0xc056e43140)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/builtin_json.go:454 +0x2d3
Apr  9 17:52:25 geth: github.com/dop251/goja.(*_builtinJSON_stringifyContext).str(0xc01b859810, {0x1cb4c20?, 0xc00a2e87a0?}, 0xc0c5ab7620)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/builtin_json.go:368 +0x92f
Apr  9 17:52:25 geth: github.com/dop251/goja.(*_builtinJSON_stringifyContext).ja(0xc01b859810, 0xc0c5ab7620)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/builtin_json.go:402 +0x225
Apr  9 17:52:25 geth: github.com/dop251/goja.(*_builtinJSON_stringifyContext).str(0xc01b859810, {0x1cb4c20?, 0x2b39240?}, 0xc0a2e78c30)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/builtin_json.go:366 +0x91b
Apr  9 17:52:25 geth: github.com/dop251/goja.(*_builtinJSON_stringifyContext).do(0xc01b859810, {0x1cb46c8, 0xc0c5ab7620})
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/builtin_json.go:274 +0x28e
Apr  9 17:52:25 geth: github.com/dop251/goja.(*Object).MarshalJSON.func1()
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/value.go:928 +0x2d
Apr  9 17:52:25 geth: github.com/dop251/goja.(*vm).try(0xc095f18d80, 0xc01b8597f8)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/vm.go:753 +0x242
Apr  9 17:52:25 geth: github.com/dop251/goja.(*Object).MarshalJSON(0x19171e0?)
Apr  9 17:52:25 geth: github.com/dop251/goja@v0.0.0-20230122112309-96b1610dd4f7/value.go:927 +0x97
Apr  9 17:52:25 geth: encoding/json.marshalerEncoder(0xc03903ec80, {0x19171e0?, 0xc0c5ab7620?, 0xc0121323c0?}, {0x0?, 0x0?})
Apr  9 17:52:25 geth: encoding/json/encode.go:477 +0xbe
Apr  9 17:52:25 geth: encoding/json.(*encodeState).reflectValue(0xc01b8599d0?, {0x19171e0?, 0xc0c5ab7620?, 0x1?}, {0x0?, 0x28?})
Apr  9 17:52:25 geth: encoding/json/encode.go:358 +0x78
Apr  9 17:52:25 geth: encoding/json.(*encodeState).marshal(0xc0041ba400?, {0x19171e0?, 0xc0c5ab7620?}, {0x0?, 0x0?})
Apr  9 17:52:25 geth: encoding/json/encode.go:330 +0xfa
Apr  9 17:52:25 geth: encoding/json.Marshal({0x19171e0, 0xc0c5ab7620})
Apr  9 17:52:25 geth: encoding/json/encode.go:161 +0xe5
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers/js.(*jsTracer).GetResult(0xc0313faff0)
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers/js/goja.go:348 +0x151
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers.(*API).traceTx(0xc000197400, {0x1ca68d8, 0xc01de16640}, 0xc0cda914d0, 0xc02de52140, {0x1addc40, 0x1addc48, 0xc07a8666f0, {0xda, 0xfe, ...}, ...}, ...)
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers/api.go:992 +0x769
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers.(*API).traceBlockParallel.func1()
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers/api.go:681 +0x625
Apr  9 17:52:25 geth: created by github.com/ethereum/go-ethereum/eth/tracers.(*API).traceBlockParallel
Apr  9 17:52:25 geth: github.com/ethereum/go-ethereum/eth/tracers/api.go:670 +0x3bd
Apr  9 17:52:26 systemd: geth.service: main process exited, code=exited, status=2/INVALIDARGUMENT
````

**Comment by Skylerspencer** [comment]
Look guys are on drug's or something  panic not at all your should I would
appreciate if you would take your fake story lines and web creativeness and
try and see if you can  trick The Light before it get here oh oops you
really don't know do you?

**Comment by Skylerspencer** [comment]
>1-2-lights*<=com,-en =< (4,) U,,,, 5= should x=<quit/#666,~8"it/"2"
late!!! ;:;)))
