### ISSUE TITLE
Tests in console_test.go leaks some routines when error happens.

### ISSUE THREAD

**Issue by Mskxn** [ethereum/go-ethereum#27152]
I found there is some leak routines the tests using this test helper function.  It says that user should ensure to call Close to avoid leak, but it seems to be some leaks inside this function.
```
// newTester creates a test environment based on which the console can operate.
// Please ensure you call Close() on the returned tester to avoid leaks.
func newTester(t *testing.T, confOverride func(*ethconfig.Config)) *tester {
	// Create a temporary storage for the node keys and initialize it
	workspace := t.TempDir()

	// Create a networkless protocol stack and start an Ethereum service within
	stack, err := node.New(&node.Config{DataDir: workspace, UseLightweightKDF: true, Name: testInstance})
	if err != nil {
		t.Fatalf("failed to create node: %v", err)
	}
	ethConf := &ethconfig.Config{
		Genesis: core.DeveloperGenesisBlock(15, 11_500_000, common.Address{}),
		Miner: miner.Config{
			Etherbase: common.HexToAddress(testAddress),
		},
		Ethash: ethash.Config{
			PowMode: ethash.ModeTest,
		},
	}
	if confOverride != nil {
		confOverride(ethConf)
	}
	ethBackend, err := eth.New(stack, ethConf)
	if err != nil {
		t.Fatalf("failed to register Ethereum protocol: %v", err)
	}
	// Start the node and assemble the JavaScript console around it
	if err = stack.Start(); err != nil {
		t.Fatalf("failed to start test stack: %v", err)
	}
	client, err := stack.Attach()
	if err != nil {
		t.Fatalf("failed to attach to node: %v", err)
	}
	prompter := &hookedPrompter{scheduler: make(chan string)}
	printer := new(bytes.Buffer)

	console, err := New(Config{
		DataDir:  stack.DataDir(),
		DocRoot:  "testdata",
		Client:   client,
		Prompter: prompter,
		Printer:  printer,
		Preload:  []string{"preload.js"},
	})
	if err != nil {
		t.Fatalf("failed to create JavaScript console: %v", err)
	}
	// Create the final tester and return
	return &tester{
		workspace: workspace,
		stack:     stack,
		ethereum:  ethBackend,
		console:   console,
		input:     prompter,
		output:    printer,
	}
}
```
These tests, for example, `TestInteractive`, using defer to close the tester but still seems something leaks.
```
=== RUN   TestInteractive
    console_test.go: failed to create JavaScript console: write pipe: i/o timeout
        [Goroutine 27 in state select, with github.com/ethereum/go-ethereum/rpc.(*Client).dispatch on top of the stack:
        goroutine 27 [select]:
        github.com/ethereum/go-ethereum/rpc.(*Client).dispatch(0xc0015a0080, {0x185ade0?, 0xc00043e300})
                /tool/go-ethereum/rpc/client.go:619 +0x2b7
        created by github.com/ethereum/go-ethereum/rpc.initClient
                /tool/go-ethereum/rpc/client.go:259 +0x311
```

As these leak occurs always with a error of console-create-failed, I wonder if there is some cleanup missed during some error handling branch.

#### Steps to reproduce the behaviour
trigger this error
```
console_test.go: failed to create JavaScript console: write pipe: i/o timeout
```

The influence unit test are :
`TestPreload`
`TestWelcome`
`TestEvaluate`
`TestInteractive`
`TestPrettyError`
`TestPrettyPrinter`

**Comment by joohhnnn** [comment]
Hello, I have tried to fix some potential issues. Could you please test it?
```
func newTester(t *testing.T, confOverride func(*ethconfig.Config)) *tester {
    // Create a temporary storage for the node keys and initialize it
    workspace := t.TempDir()

    // Create a networkless protocol stack and start an Ethereum service within
    stack, err := node.New(&node.Config{DataDir: workspace, UseLightweightKDF: true, Name: testInstance})
    if err != nil {
        t.Fatalf("failed to create node: %v", err)
    }

    ethConf := &ethconfig.Config{
        Genesis: core.DeveloperGenesisBlock(15, 11_500_000, common.Address{}),
        Miner: miner.Config{
            Etherbase: common.HexToAddress(testAddress),
        },
        Ethash: ethash.Config{
            PowMode: ethash.ModeTest,
        },
    }
    if confOverride != nil {
        confOverride(ethConf)
    }
    ethBackend, err := eth.New(stack, ethConf)
    if err != nil {
        t.Fatalf("failed to register Ethereum protocol: %v", err)
    }

    // Start the node and assemble the JavaScript console around it
    if err = stack.Start(); err != nil {
        t.Fatalf("failed to start test stack: %v", err)
    } else {
        defer stack.Close()
    }

    client, err := stack.Attach()
    if err != nil {
        t.Fatalf("failed to attach to node: %v", err)
    }

    prompter := &hookedPrompter{scheduler: make(chan string)}
    printer := new(bytes.Buffer)

    console, err := New(Config{
        DataDir:  stack.DataDir(),
        DocRoot:  "testdata",
        Client:   client,
        Prompter: prompter,
        Printer:  printer,
        Preload:  []string{"preload.js"},
    })
    if err != nil {
        t.Fatalf("failed to create JavaScript console: %v", err)
    } else {
        defer console.Close()
    }

    // Create the final tester and return
    return &tester{
        workspace: workspace,
        stack:     stack,
        ethereum:  ethBackend,
        console:   console,
        input:     prompter,
        output:    printer,
    }
}

```

**Comment by jsvisa** [comment]
What's the environment are you running the tests, also what's the command?

**Comment by hhheiaenia** [comment]
Yes, I also found this problem.
