### ISSUE TITLE
Geth non-deterministically crashes on eth_getBlockByNumber call 

### ISSUE THREAD

**Issue by zimbabao** [ethereum/go-ethereum#27173]
#### System information

Geth version: `1.11.5`
CL client & version: lighthouse:v4.0.1
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
API returns the response.

#### Actual behaviour

```
ERROR[04-26|07:48:31.228] RPC method eth_getBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 8010512 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
	github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x16f15a0, 0x2763530})
	runtime/panic.go:884 +0x213
github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).BlockByNumber(0xc06d7daba0, {0x40bc2d?, 0x175c2a0?}, 0x3?)
	github.com/ethereum/go-ethereum/eth/api_backend.go:137 +0x1c4
github.com/ethereum/go-ethereum/internal/ethapi.(*BlockChainAPI).GetBlockByNumber(0xc056ce5710, {0x1c97f98, 0xc068a24f00}, 0xfffffffffffffffd, 0x4?)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:765 +0x5b
reflect.Value.call({0xc027b6b570?, 0xc027c640d0?, 0x7f12e701f4e8?}, {0x1936b91, 0x4}, {0xc075cd0480, 0x4, 0x0?})
	reflect/value.go:586 +0xb07
reflect.Value.Call({0xc027b6b570?, 0xc027c640d0?, 0x1?}, {0xc075cd0480?, 0x2?, 0x16?})
	reflect/value.go:370 +0xbc
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc05d100180, {0x1c97f98?, 0xc068a24f00}, {0xc0911c6798, 0x14}, {0xc071b6c120, 0x2, 0x4d3837?})
	github.com/ethereum/go-ethereum/rpc/service.go:205 +0x3c5
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0911c67b0?, {0x1c97f98?, 0xc068a24f00?}, 0xc0828dea10, 0x2?, {0xc071b6c120?, 0x417230?, 0x17243e0?})
	github.com/ethereum/go-ethereum/rpc/handler.go:513 +0x45
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc02fcf9c20, 0xc071b6c060, 0xc0828dea10)
	github.com/ethereum/go-ethereum/rpc/handler.go:459 +0x239
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc02fcf9c20, 0xc071b6c0c0?, 0xc0828dea10)
	github.com/ethereum/go-ethereum/rpc/handler.go:420 +0x237
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc071b6c060)
	github.com/ethereum/go-ethereum/rpc/handler.go:256 +0x1a5
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
	github.com/ethereum/go-ethereum/rpc/handler.go:348 +0xc5
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	github.com/ethereum/go-ethereum/rpc/handler.go:344 +0x8d
```

#### Steps to reproduce the behaviour
This is non deterministic. Keep calling the API as new nodes arrive. 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
This issue is fixed on master: https://github.com/ethereum/go-ethereum/pull/27162. Crash happens when using `finalized` and `safe` in `eth_getBlockByNumber` during sync. Feel free to re-open if that PR doesn't fix it for you.
