### ISSUE TITLE
node crash with fatal error: thread exhaustion runtime: program exceeds 10000-thread limit and rewound 26K blocks

### ISSUE THREAD

**Issue by zimbabao** [ethereum/go-ethereum#27260]
#### System information

Geth version: `geth version 1.11.7-unstable-8f373227`
CL client & version: e.g. lighthouse:v4.1.0
OS & Version: Windows/Linux/OSX: Linux
Commit hash : (if `develop`)

#### Expected behaviour
After a crash node restart and syncs from last known state.

#### Actual behaviour
Crashed with following msg and rewound 26K blocks. Node fell behind.

```
fatal error: thread exhaustion
runtime: program exceeds 10000-thread limit
```

#### Steps to reproduce the behaviour
n/a

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Do you have sone more logs from the crash? This is very strange since Go only uses a handful of OS threads and multiplexes everything on top. The only time Go needs to spin up a new thread is if the old one is blocked on IO, which would mean that you have 10K threads blocks on IO... shouldn't ever happen.

Did you massively rase some parameter in Geth? What's your usage? Is this stock Geth or some modified version?

**Comment by zimbabao** [comment]
I have been running the same config for 1.5 years. The node has been running fine since the crash on Friday.
I am running a stock image, and no custom changes are added.

More logs.
```
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0d0789fe8 sp=0xc0d0789fe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc0d0789fe0 sp=0xc0d0789fc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc0d0789fc8 sp=0xc0d0789f68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc0d0789f68 sp=0xc0d0789f40 pc=0x407c98
runtime.chanrecv2(0x36bc576808d30e5d?, 0x71c3c8103140aff6?)
	runtime/chan.go:583 +0x49d fp=0xc0d0789f40 sp=0xc0d0789eb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc0d0789fb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc0d0789eb0 sp=0xc0d0789e90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc0fec69a10?, 0xe?, 0x17?, 0x2?)
goroutine 14 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc01ee2cfe8 sp=0xc01ee2cfe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc01ee2cfe0 sp=0xc01ee2cfc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc01ee2cfc8 sp=0xc01ee2cf68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc01ee2cf68 sp=0xc01ee2cf40 pc=0x407c98
runtime.chanrecv2(0xde95aaaf9dfc77da?, 0x3a732bd65978d416?)
	runtime/chan.go:583 +0x49d fp=0xc01ee2cf40 sp=0xc01ee2ceb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc01ee2cfb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc01ee2ceb0 sp=0xc01ee2ce90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc06a9a6810?, 0x64?, 0x1?, 0x44cca7fef19600f9?)
goroutine 13 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00014afe8 sp=0xc00014afe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc00014afe0 sp=0xc00014afc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc00014afc8 sp=0xc00014af68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc00014af68 sp=0xc00014af40 pc=0x407c98
runtime.chanrecv2(0xe814d941198a5113?, 0xc005f80019651c31?)
	runtime/chan.go:583 +0x49d fp=0xc00014af40 sp=0xc00014aeb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc00014afb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc00014aeb0 sp=0xc00014ae90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc0cd5f7bf0?, 0x0?, 0x97?, 0xc0aaf9ab40?)
goroutine 12 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc020084fe8 sp=0xc020084fe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc020084fe0 sp=0xc020084fc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc020084fc8 sp=0xc020084f68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc020084f68 sp=0xc020084f40 pc=0x407c98
runtime.chanrecv2(0x42480df9f820d50f?, 0x8209d95e65513966?)
	runtime/chan.go:583 +0x49d fp=0xc020084f40 sp=0xc020084eb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc020084fb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc020084eb0 sp=0xc020084e90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc114d4abd0?, 0xe?, 0x17?, 0x2?)
goroutine 11 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc01ee30fe8 sp=0xc01ee30fe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc01ee30fe0 sp=0xc01ee30fc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc01ee30fc8 sp=0xc01ee30f68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc01ee30f68 sp=0xc01ee30f40 pc=0x407c98
runtime.chanrecv2(0x493e20bc2e83d6cb?, 0xe3fc67708971b7e2?)
	runtime/chan.go:583 +0x49d fp=0xc01ee30f40 sp=0xc01ee30eb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc01ee30fb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc01ee30eb0 sp=0xc01ee30e90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc0bcf9c030?, 0x0?, 0x0?, 0x0?)
goroutine 10 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc020220fe8 sp=0xc020220fe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc020220fe0 sp=0xc020220fc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc020220fc8 sp=0xc020220f68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc020220f68 sp=0xc020220f40 pc=0x407c98
runtime.chanrecv2(0x969d1d10e2e720ac?, 0x4bd2ed2224fa958e?)
	runtime/chan.go:583 +0x49d fp=0xc020220f40 sp=0xc020220eb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc020220fb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc020220eb0 sp=0xc020220e90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc0d7211140?, 0x0?, 0x0?, 0x0?)
goroutine 9 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00aa90fe8 sp=0xc00aa90fe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc00aa90fe0 sp=0xc00aa90fc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc00aa90fc8 sp=0xc00aa90f68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc00aa90f68 sp=0xc00aa90f40 pc=0x407c98
runtime.chanrecv2(0xbb0b43ee16e8ad91?, 0xf65146b29fe3a52f?)
	runtime/chan.go:583 +0x49d fp=0xc00aa90f40 sp=0xc00aa90eb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc00aa90fb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc00aa90eb0 sp=0xc00aa90e90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc09426a8a0?, 0x0?, 0x0?, 0x0?)
goroutine 8 [chan receive]:
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x75
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	runtime/asm_amd64.s:1598 +0x1 fp=0xc01c38ffe8 sp=0xc01c38ffe0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:55 +0x26 fp=0xc01c38ffe0 sp=0xc01c38ffc8 pc=0xcd5ea6
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	github.com/ethereum/go-ethereum/core/sender_cacher.go:63 +0x3b fp=0xc01c38ffc8 sp=0xc01c38ff68 pc=0xcd5f1b
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	runtime/chan.go:447 +0x18 fp=0xc01c38ff68 sp=0xc01c38ff40 pc=0x407c98
runtime.chanrecv2(0x601b55206bb8eae7?, 0x234136230ee2f0bc?)
	runtime/chan.go:583 +0x49d fp=0xc01c38ff40 sp=0xc01c38feb0 pc=0x40815d
runtime.chanrecv(0xc00016a9c0, 0xc01c38ffb0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc01c38feb0 sp=0xc01c38fe90 pc=0x43d016
runtime.gopark(0x1781b80?, 0xc1191382d0?, 0xda?, 0x9a?, 0x0?)
goroutine 7 [chan receive]:
	github.com/ethereum/go-ethereum/metrics/meter.go:56 +0xd3
created by github.com/ethereum/go-ethereum/metrics.NewMeter
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0001387e8 sp=0xc0001387e0 pc=0x4711e1
runtime.goexit()
	github.com/ethereum/go-ethereum/metrics/meter.go:56 +0x26 fp=0xc0001387e0 sp=0xc0001387c8 pc=0x6e9d46
github.com/ethereum/go-ethereum/metrics.NewMeter.func2()
	github.com/ethereum/go-ethereum/metrics/meter.go:293 +0x65 fp=0xc0001387c8 sp=0xc000138788 pc=0x6eb0c5
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x293c160)
	runtime/chan.go:447 +0x18 fp=0xc000138788 sp=0xc000138760 pc=0x407c98
runtime.chanrecv2(0x293c160?, 0xc000308930?)
	runtime/chan.go:583 +0x49d fp=0xc000138760 sp=0xc0001386d0 pc=0x40815d
runtime.chanrecv(0xc00023e7e0, 0xc0001387a0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc0001386d0 sp=0xc0001386b0 pc=0x43d016
runtime.gopark(0xc000138778?, 0x6eb1f7?, 0x10?, 0x87?, 0xc00019b1a0?)
goroutine 6 [chan receive]:
	runtime/mfinal.go:163 +0x45
created by runtime.createfing
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00013c7e8 sp=0xc00013c7e0 pc=0x4711e1
runtime.goexit()
	runtime/mfinal.go:193 +0x107 fp=0xc00013c7e0 sp=0xc00013c628 pc=0x41b2c7
runtime.runfinq()
	runtime/proc.go:381 +0xd6 fp=0xc00013c628 sp=0xc00013c608 pc=0x43d016
runtime.gopark(0x1a0?, 0x293d880?, 0xe0?, 0x24?, 0xc00013c770?)
goroutine 18 [finalizer wait, 6205 minutes]:
	runtime/mgc.go:179 +0xaa
created by runtime.gcenable
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00013dfe8 sp=0xc00013dfe0 pc=0x4711e1
runtime.goexit()
	runtime/mgc.go:179 +0x26 fp=0xc00013dfe0 sp=0xc00013dfc8 pc=0x41c226
runtime.gcenable.func2()
	runtime/mgcscavenge.go:633 +0x65 fp=0xc00013dfc8 sp=0xc00013dfa0 pc=0x4255a5
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:400 +0x53 fp=0xc00013dfa0 sp=0xc00013df70 pc=0x424fb3
runtime.(*scavengerState).park(0x293c9c0)
	runtime/proc.go:387
runtime.goparkunlock(...)
	runtime/proc.go:381 +0xd6 fp=0xc00013df70 sp=0xc00013df50 pc=0x43d016
runtime.gopark(0x465355bad9dea?, 0xae4d?, 0x0?, 0x0?, 0x0?)
goroutine 4 [GC scavenge wait]:
	runtime/mgc.go:178 +0x6b
created by runtime.gcenable
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00013d7e8 sp=0xc00013d7e0 pc=0x4711e1
runtime.goexit()
	runtime/mgc.go:178 +0x26 fp=0xc00013d7e0 sp=0xc00013d7c8 pc=0x41c286
runtime.gcenable.func1()
	runtime/mgcsweep.go:319 +0xde fp=0xc00013d7c8 sp=0xc00013d780 pc=0x4270be
runtime.bgsweep(0x0?)
	runtime/proc.go:387
runtime.goparkunlock(...)
	runtime/proc.go:381 +0xd6 fp=0xc00013d780 sp=0xc00013d760 pc=0x43d016
runtime.gopark(0x293c001?, 0x0?, 0x0?, 0x0?, 0x0?)
goroutine 3 [GC sweep wait]:
	runtime/proc.go:293 +0x25
created by runtime.init.6
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00013cfe8 sp=0xc00013cfe0 pc=0x4711e1
runtime.goexit()
	runtime/proc.go:305 +0xb0 fp=0xc00013cfe0 sp=0xc00013cfb0 pc=0x43ce50
runtime.forcegchelper()
	runtime/proc.go:387
runtime.goparkunlock(...)
	runtime/proc.go:381 +0xd6 fp=0xc00013cfb0 sp=0xc00013cf90 pc=0x43d016
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
goroutine 2 [force gc (idle), 6205 minutes]:
	runtime/asm_amd64.s:1598 +0x1 fp=0xc021153fe8 sp=0xc021153fe0 pc=0x4711e1
runtime.goexit()
	runtime/proc.go:250 +0x207 fp=0xc021153fe0 sp=0xc021153f80 pc=0x43cbe7
runtime.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:265 +0x47 fp=0xc021153f80 sp=0xc021153f30 pc=0x147d807
main.main()
	github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:252
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:395 +0x1070 fp=0xc021153f30 sp=0xc021153c50 pc=0xe982f0
github.com/urfave/cli/v2.(*App).RunContext(0xc0001f8e00, {0x1c84d30?, 0xc0001b2000}, {0xc0001b0000, 0x13, 0x14})
	github.com/ethereum/go-ethereum/cmd/geth/main.go:344 +0x14a fp=0xc021153c50 sp=0xc021153bb8 pc=0x147df4a
main.geth(0xc00097a2c0)
	github.com/ethereum/go-ethereum/node/node.go:541
github.com/ethereum/go-ethereum/node.(*Node).Wait(...)
	runtime/chan.go:442 +0x18 fp=0xc021153bb8 sp=0xc021153b90 pc=0x407c58
runtime.chanrecv1(0xc000a55c20?, 0xc000205340?)
	runtime/chan.go:583 +0x49d fp=0xc021153b90 sp=0xc021153b00 pc=0x40815d
runtime.chanrecv(0xc00018e6c0, 0x0, 0x1)
	runtime/proc.go:381 +0xd6 fp=0xc021153b00 sp=0xc021153ae0 pc=0x43d016
runtime.gopark(0xc0160f9b28?, 0xea381c?, 0x22?, 0x65?, 0x1926522?)
goroutine 1 [chan receive, 6205 minutes]:
	runtime/asm_amd64.s:452 +0x43 fp=0x7f6d084f1a48 sp=0x7f6d084f1a38 pc=0x46efa3
runtime.mcall()
	runtime/proc.go:3511 +0x12d fp=0x7f6d084f1a38 sp=0x7f6d084f1a08 pc=0x443a8d
runtime.park_m(0xc051e65380?)
	runtime/proc.go:3366 +0xd1 fp=0x7f6d084f1a08 sp=0x7f6d084f19d0 pc=0x443591
runtime.schedule()
	runtime/proc.go:3244 +0x49 fp=0x7f6d084f19d0 sp=0x7f6d084f19b0 pc=0x4431a9
runtime.resetspinning()
	runtime/proc.go:2541 +0xf6 fp=0x7f6d084f19b0 sp=0x7f6d084f1980 pc=0x441676
runtime.wakep()
	runtime/proc.go:2403 +0xac fp=0x7f6d084f1980 sp=0x7f6d084f1930 pc=0x44104c
runtime.startm(0xc00007d900, 0x1)
	runtime/proc.go:805 +0x36 fp=0x7f6d084f1930 sp=0x7f6d084f1908 pc=0x43e176
runtime.mReserveID()
	runtime/proc.go:789 +0x8c fp=0x7f6d084f1908 sp=0x7f6d084f18e0 pc=0x43e12c
runtime.checkmcount()
	runtime/panic.go:1047 +0x5d fp=0x7f6d084f18e0 sp=0x7f6d084f18b0 pc=0x43a2fd
runtime.throw({0x1938c67?, 0x1?})
runtime stack:
fatal error: thread exhaustion
runtime: program exceeds 10000-thread limit
```

**Comment by karalabe** [comment]
Can you paste / upload us the entire crash dump? If something's spinning up threads like crazy, those should be visible in the goroutine dump, but we need the entire thing to find what's so many and stuck that it piled unbounded.

**Comment by zimbabao** [comment]
I am attaching more logs. This is what I could retrieve from my logs storage.
[geth-crash.log](https://github.com/ethereum/go-ethereum/files/11481931/geth-crash.log)

**Comment by holiman** [comment]
```
$ more geth-crash.log | grep handleCall\( | wc -l 
1185
```
Lots of RPC calls going on

**Comment by fjl** [comment]
One theory here is that this crash happens because too many goroutines get stuck in I/O. When a goroutine blocks in a syscall for long enough, the scheduler will create a new thread to keep running. Overloading the node with requests can result in this condition.

We could try to prevent this by limiting the number of concurrent requests, either in the database, or in the RPC layer.

**Comment by holiman** [comment]
Seems like this is investigated and explained. I'll assume there's nothing more to do here, closing
