### ISSUE TITLE
Panic in tx-pool reorg handling

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#27301]
@protolambda reported the following issue which looks like something from upstream:
```
INFO [05-18|00:09:22.804] Loaded most recent local block           number=9   hash=da4cfa..75fed9 td=1 age=0
WARN [05-18|00:09:22.804] Rewinding blockchain to block            target=8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5cc1f]

goroutine 46922 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
    /go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101105.2-0.20230502202351-9cc072e922f6/core/types/block.go:333
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).reset(0xc02fafe600, 0xc0394c3440, 0xc0363b0b40)
    /go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101105.2-0.20230502202351-9cc072e922f6/core/txpool/txpool.go:1364 +0xfdf
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).runReorg(0xc02fafe600, 0xc0394a61e0, 0xc00c24e090, 0x0, 0xc0394a3170)
    /go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101105.2-0.20230502202351-9cc072e922f6/core/txpool/txpool.go:1268 +0x26b
created by github.com/ethereum/go-ethereum/core/txpool.(*TxPool).scheduleReorgLoop
    /go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101105.2-0.20230502202351-9cc072e922f6/core/txpool/txpool.go:1197 +0x1b3
 ```
 
Essentially the node tries to reorg the txpool to a new head and the newhead seems to be missing from the db. So we have the header but not the full block.

**Comment by karalabe** [comment]
I think we can get rid of rewinding altogether since post-merge it's not relevant any more.

As for the panic, we might want to add a check to the txpool just in case.
