### ISSUE TITLE
Geth Documentation Private Network example error⚠️

### ISSUE THREAD

**Issue by yug-am** [ethereum/go-ethereum#27431]
#### System information

Geth version: `1.12.0-stable-e501b3b0`

OS & Version: Windows11
#### Issue
Geth Documentation Private Network End-to-end example sending ether part [link](https://geth.ethereum.org/docs/fundamentals/private-network#end-to-end-example)
after ```geth attach``` on node1 pipe 
on command
 ``` 
eth.sendTransaction({  to: '<Node2 Address>',  from: eth.accounts[0],value: 250000});
``` 
#### Expected behaviour
geth attach 

#### Actual behaviour
```
 Error: gas required exceeds allowance (0)
        at web3.js:6365:9(39)
        at send (web3.js:5099:62(29))
        at <eval>:1:20(12)

```

#### Steps to reproduce the behaviour

Geth Documentation Private Network End-to-end example sending ether part [link](https://geth.ethereum.org/docs/fundamentals/private-network#end-to-end-example)

**Comment by imranmehdi5511** [comment]
Follow the book of imran bashir, mastering blockchain to get started.

**Comment by yug-am** [comment]
Thanks for a reading reference.
But underlying issue remains the same, Atleast the **documentation example should work as expected**, incase of potential unexpected behaviour, same should be mentioned in the example itself. 


> Follow the book of imran bashir, mastering blockchain to get started.

**Comment by karalabe** [comment]
Does your account have enough balance to cover the tx?

**Comment by yug-am** [comment]
More than sufficient.
The example is followed as mentioned and got similar results before the step on which issue is raised.
Have checked balance and also tried with gas fee zero.
Again mentioning this is POA, private chain.
Request follow along of tutorial to confirm results.

**Comment by MariusVanDerWijden** [comment]
We deprecated support for private networks
