### ISSUE TITLE
Private blockchain: ethash_full_new IO or memory error (new epoch starting at block #16092)

### ISSUE THREAD

**Issue by varunmamillapalli** [ethereum/go-ethereum#2783]
geth crashed while mining in a private blockchain. I don't think it's because of my low memory - 3GB (or is it?) like in [#1194](https://github.com/ethereum/go-ethereum/issues/1194) because I successfully generated DAG for `epoch 0` from the same system. This is the only miner in my network so I need this running at all times. 
I've seen that this problem was faced by many and pregenerating DAG and setting `--autodag=false` hasn't solved the problem (#1572)
It was also mentioned that 4GB of RAM is not sufficient to generate DAG (#2089), so how much memory is actually required? 

Also, from the logs below, a new DAG is being generated after block #16092. The `epoch` in the public blockchain is 30000 blocks (100 hours). Isn't it the same in a private blockchain?  
#### System information

Geth version: `1.4.9 - stable`
OS & Version: Virtual Machine - Ubuntu 16.04 LTS (RAM - 3GB)
#### Actual behaviour

```
I0704 09:52:11.304612 miner/worker.go:555] commit new work on block 16092 with 0 txs & 0 uncles. Took 170.524µs
I0704 09:53:05.103595 eth/api.go:1193] Tx(0xe95bbf9cac3b5d59fda66fa061043deafde9c3af13aa75007209abe56c7b0d33) to: 0x4f3a166b7fc6239b1775ced9e5404c538ea1cc14
I0704 09:53:32.056373 eth/backend.go:459] checking DAG (ethash dir: /home/varun/.ethash)
I0704 09:53:32.061462 eth/backend.go:473] Pregenerating DAG for epoch 1 (full-R23-290decd9548b62a8)    
I0704 09:53:32.062630 ethash.go:259] Generating DAG for epoch 1 (size 1082130304) (290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563)
panic: ethash_full_new IO or memory error

goroutine 13900 [running]:
panic(0x87e0d00, 0x1a404008)
/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
github.com/ethereum/ethash.(*dag).generate.func1()
/build/ethereum-WQA88w/ethereum-1.4.9+10xenial/obj-i686-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:273 +0x567
sync.(*Once).Do(0x1db8fd24, 0x1da93df0)
/usr/lib/go-1.6/src/sync/once.go:44 +0xcf
github.com/ethereum/ethash.(*dag).generate(0x1db8fd10)
/build/ethereum-WQA88w/ethereum-1.4.9+10xenial/obj-i686-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:277 +0x3d
github.com/ethereum/ethash.MakeDAG(0x7530, 0x0, 0x0, 0x0, 0x0, 0x0)
/build/ethereum-WQA88w/ethereum-1.4.9+10xenial/obj-i686-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:303 +0x192
github.com/ethereum/go-ethereum/eth.(*Ethereum).StartAutoDAG.func1(0x19364140)
/build/ethereum-WQA88w/ethereum-1.4.9+10xenial/obj-i686-linux-gnu/src/github.com/ethereum/go-ethereum/eth/backend.go:474 +0x966
created by github.com/ethereum/go-ethereum/eth.(*Ethereum).StartAutoDAG
/build/ethereum-WQA88w/ethereum-1.4.9+10xenial/obj-i686-linux-gnu/src/github.com/ethereum/go-ethereum/eth/backend.go:489 +0x3f
```

**Comment by wawrzek** [comment]
Someone from admins please mark it's with 'Private network' label.

**Comment by wawrzek** [comment]
I see similar problem with **geth 1.4.10** on **Ubuntu 16.04 LTS** (on Azure) with **7 GB** memory.

```
panic: ethash_full_new IO or memory error

goroutine 90 [running]:
panic(0xcf88a0, 0xc825abe200)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/ethereum/ethash.(*dag).generate.func1()
	/build/ethereum-d0U3kR/ethereum-1.4.10+11xenial/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:273 +0x5b7
sync.(*Once).Do(0xc8202ed220, 0xc8224ddac8)
	/usr/lib/go-1.6/src/sync/once.go:44 +0xe4
github.com/ethereum/ethash.(*dag).generate(0xc8202ed200)
	/build/ethereum-d0U3kR/ethereum-1.4.10+11xenial/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:277 +0x45
github.com/ethereum/ethash.(*Full).getDAG(0xc820266150, 0xa, 0xc8202ed200)
	/build/ethereum-d0U3kR/ethereum-1.4.10+11xenial/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:333 +0xaa
github.com/ethereum/ethash.(*Full).Search(0xc820266150, 0x7f276f168310, 0xc820243dd0, 0xc82003f5c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-d0U3kR/ethereum-1.4.10+11xenial/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:338 +0x73
github.com/ethereum/go-ethereum/miner.(*CpuAgent).mine(0xc820330d70, 0xc820344750, 0xc82003f5c0)
	/build/ethereum-d0U3kR/ethereum-1.4.10+11xenial/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:121 +0x1bc
created by github.com/ethereum/go-ethereum/miner.(*CpuAgent).update
	/build/ethereum-d0U3kR/ethereum-1.4.10+11xenial/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:90 +0x155
```

**Comment by wawrzek** [comment]
In my case it was wrong permission to a file in .ethereum directory. Looking at the code it seems that you have better dubug in place, you just don't use it.

**Comment by kevinmartinmauro** [comment]
Getting this also. It's been over 12 months since the intital bug report was filed.

**Comment by TUTUBIG** [comment]
I have a same problem on Windows10 and have not find a solution

**Comment by karalabe** [comment]
You machines doens't seem to have enough memory. It needs 4GB at least to generate a DAG, maybe more. How much do you have available?

**Comment by TUTUBIG** [comment]
@karalabe  but my machine has a 8G memory

**Comment by karalabe** [comment]
Are you running a 64 bit Windows **and** 64 bit version of Geth?

**Comment by TUTUBIG** [comment]
@karalabe  yes i am sure about this

**Comment by JosefJ** [comment]
Hey, I had a similar issue. It turned out RAM wasn't the reason but an insufficient storage on my system drive was. 

Anyway I had symbolic links pointing to my data drive but there was another problem with the link type. Hard link did the job for me:  `mklink /D "path-from" "path-to"`

**Comment by fjl** [comment]
This can't happen anymore because the ethash implementation was switched to Go code ~10 months ago.
