### ISSUE TITLE
`admin.getContractInfo` is not available

### ISSUE THREAD

**Issue by xavierlepretre** [ethereum/go-ethereum#2817]
#### System information

Geth version: 1.5.0+1002SNAPSHOT20160608110701trusty-0ubuntu1
Version: 1.5.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

OS & Version: Ubuntu Linux 16.04
Commit hash : (if `develop`)

#### Expected behaviour
`> admin.getContractInfo("0x33990122638b9132ca29c723bdf037f1a891a70c")` should return some information.

#### Actual behaviour
```javascript
> admin.getContractInfo("0x33990122638b9132ca29c723bdf037f1a891a70c")
The method admin_getContractInfo does not exist/is not available
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
`admin.getContractInfo` isn't part of our APIs (https://github.com/ethereum/go-ethereum/wiki/Management-APIs). Where did you find a reference to it?

**Comment by xavierlepretre** [comment]
There https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions#interacting-with-contracts

**Comment by cmoaciopm** [comment]
I'm using 1.6.0-unstable-f3579f64 and met the same issue.

It's documented here https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#admingetcontractinfo

**Comment by mikeshultz** [comment]
Still documented on the wiki.
