### ISSUE TITLE
panic: unhandled error: notify.FSEventsMustScanSubDirs|notify.FSEventsKernelDropped

### ISSUE THREAD

**Issue by pascalvanhecke** [ethereum/go-ethereum#2829]
#### System information
 
~ geth version
Geth
Version: 1.4.10-stable-5f55d95a
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.6.2/libexec

#### Actual behaviour

Software crash

#### Steps to reproduce the behaviour
No steps found to reproduce

#### Backtrace

````
I0717 23:50:36.332543 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 17.456699ms. #1903995 [5b577140 / 5b577140]
panic: unhandled error: notify.FSEventsMustScanSubDirs|notify.FSEventsKernelDropped

goroutine 37 [running]:
panic(0x48f1740, 0xc82a92f560)
	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/rjeczalik/notify.(*watch).Dispatch(0xc820177700, 0xc82f032500, 0x1, 0x1)
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go:136 +0x54f
github.com/rjeczalik/notify.(*watch).Dispatch-fm(0xc82f032500, 0x1, 0x1)
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go:205 +0x3e
github.com/rjeczalik/notify.gostream(0x5e032d0, 0x1, 0x1, 0x7007550, 0x7007560, 0x7007570)
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:104 +0x11c
github.com/rjeczalik/notify._cgoexpwrap_b138320e5461_gostream(0x5e032d0, 0x1, 0x1, 0x7007550, 0x7007560, 0x7007570)
	??:0 +0x53
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	??:0 +0x36
github.com/rjeczalik/notify.init.1.func1()
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:68 +0x112
created by github.com/rjeczalik/notify.init.1
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:70 +0x48
````

**Comment by pascalvanhecke** [comment]
Possible cause: I was running parity at the same time.  Maybe both geth and parity need access to the same folders/files?

**Comment by nvmr** [comment]
Probably the same error here. Nothing relevant running in parallel.

Steps to reproduce: (i) delete Library/Ethereum/chaindata, (ii) start geth (rescans blockchain)

$ ./build/bin/geth version
Geth
Version: 1.5.0-unstable-a4c4125b
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.6.2/libexec


```
I0802 10:47:24.007685 core/blockchain.go:971] imported 2048 block(s) (0 queued 0 ignored) including 2486 txs in 4.858215456s. #412053 [90c0310c / ce00b78b]
panic: unhandled error: notify.FSEventsKernelDropped|notify.FSEventsMustScanSubDirs

goroutine 22 [running]:
panic(0x4906d60, 0xc82eb0e600)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/rjeczalik/notify.(*watch).Dispatch(0xc820196000, 0xc825b12e60, 0x1, 0x1)
        /Users/ar/Code/Ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go:136 +0x54f
github.com/rjeczalik/notify.(*watch).Dispatch-fm(0xc825b12e60, 0x1, 0x1)
        /Users/ar/Code/Ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go:205 +0x3e
github.com/rjeczalik/notify.gostream(0x8500100, 0x1, 0x1, 0x5f02a70, 0x5f06440, 0x5f02ac0)
        /Users/ar/Code/Ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:104 +0x11c
github.com/rjeczalik/notify._cgoexpwrap_b138320e5461_gostream(0x8500100, 0x1, 0x1, 0x5f02a70, 0x5f06440, 0x5f02ac0)
        ??:0 +0x53
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
        ??:0 +0x36
github.com/rjeczalik/notify.init.1.func1()
        /Users/ar/Code/Ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:68 +0x112
created by github.com/rjeczalik/notify.init.1
        /Users/ar/Code/Ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:70 +0x48

```
