### ISSUE TITLE
what's wrong with invalid memory

### ISSUE THREAD

**Issue by PHPJourney** [ethereum/go-ethereum#28556]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
```
--- FAIL: TestNewAddress (1.47s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10014e8e2]

goroutine 6 [running]:
testing.tRunner.func1.2({0x100393360, 0x1006c8560})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x100393360, 0x1006c8560})
	/usr/local/go/src/runtime/panic.go:884 +0x213
math/big.(*Int).Cmp(0x0?, 0xc0001b0870?)
	/usr/local/go/src/math/big/int.go:373 +0x22
nftscan/utils.(*Scraper).NewAddress(0xc000014520, 0x1, 0x3e8)
```

I use ethclient dial a client. client rpc server has `wss://ethereum.publicnode.com`
and i call 
```
HeaderByNumber(context.Background(), nil) get latest height. 
```
see code:
```
import "github.com/ethereum/go-ethereum/ethclient"
type Scraper struct {
	client *ethclient.Client
}

func (s *Scraper) NewScraper() *Scraper {
	client, err := ethclient.Dial("wss://ethereum.publicnode.com")
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}

	return &Scraper{
		client: client,
	}
}
func (s *Scraper) NewAddress(min,max int64) error {
	var head *types.Header
	var	err  error
	head = &types.Header{}
	go func() {
		head,err = s.client.HeaderByNumber(context.Background(), nil)
		if r := recover(); r != nil {
			fmt.Println("recoverd from ", r)
		}
	}()
	if err != nil {
		log.Fatalf("Failed to get latest block header: %v", err)
		return err
	}
    return nil
}

```

**Comment by holiman** [comment]
The error is `nil pointer dereference`, which means you are trying to use something which is `nil`. In this case, the error happens at `math/big.(*Int).Cmp(0x0?, 0xc0001b0870?)`, so it's either `nil.Cmp(a)` or `a.Cmp(nil)`. 

It happens inside `(*Scraper).NewAddress(0xc000014520, 0x1, 0x3e8)`, and if you had added _one_ more line of the stack trace, we would have seen exactly where.

**Comment by holiman** [comment]
Also, if you want to catch the panic, you need to put the `if r := recover() ... ` into a `defer` clause. 

https://go.dev/blog/defer-panic-and-recover

**Comment by PHPJourney** [comment]
> The error is `nil pointer dereference`, which means you are trying to use something which is `nil`. In this case, the error happens at `math/big.(*Int).Cmp(0x0?, 0xc0001b0870?)`, so it's either `nil.Cmp(a)` or `a.Cmp(nil)`.
> 
> It happens inside `(*Scraper).NewAddress(0xc000014520, 0x1, 0x3e8)`, and if you had added _one_ more line of the stack trace, we would have seen exactly where.


```
--- FAIL: TestNewAddress (1.47s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10014e8e2]

goroutine 6 [running]:
testing.tRunner.func1.2({0x100393360, 0x1006c8560})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x100393360, 0x1006c8560})
	/usr/local/go/src/runtime/panic.go:884 +0x213
math/big.(*Int).Cmp(0x0?, 0xc0001b0870?)
	/usr/local/go/src/math/big/int.go:373 +0x22
nftscan/utils.(*Scraper).NewAddress(0xc000014520, 0x1, 0x3e8)
	/Users/journey/.cursor-tutor/projects/gowork/nftscan/utils/utils.go:73 +0x33a
nftscan/utils.TestNewAddress(0xc0001271e0)
	/Users/journey/.cursor-tutor/projects/gowork/nftscan/utils/utils_test.go:9 +0x47
testing.tRunner(0xc0001271e0, 0x10044f278)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL	nftscan/utils	1.504s
FAIL
```
this test all error track

**Comment by PHPJourney** [comment]
I get recover by 
```
recoverd from  runtime error: invalid memory address or nil pointer dereference
PASS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1003398d0]

goroutine 9 [running]:
github.com/ethereum/go-ethereum/ethclient.(*Client).HeaderByNumber(0x0, {0x1004aef88, 0xc000030148}, 0x0?)
	/Users/journey/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5/ethclient/ethclient.go:211 +0xf0
nftscan/utils.(*Scraper).NewAddress.func2()
	/Users/journey/.cursor-tutor/projects/gowork/nftscan/utils/utils.go:66 +0x46
created by nftscan/utils.(*Scraper).NewAddress
	/Users/journey/.cursor-tutor/projects/gowork/nftscan/utils/utils.go:65 +0x14c
FAIL	nftscan/utils	1.320s
FAIL
```

**Comment by holiman** [comment]
Well, 
```

github.com/ethereum/go-ethereum/ethclient.(*Client).HeaderByNumber(0x0, {0x1004aef88, 0xc000030148}, 0x0?)
	/Users/journey/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5/ethclient/ethclient.go:211 +0xf0
```
This one looks like maybe the `ethclient.c` (the internal client) is `nil`.

 Hard to say, since the line numbers do not match up with what you have posted. But: this is not a bug in our code. This is a learning experience for you to debug your own code. Good luck!

**Comment by PHPJourney** [comment]
@holiman you mean NewScraper func not finish init or struct not storage client?

**Comment by PHPJourney** [comment]
@holiman i found errno reason. you are right. my struct no update NewScraper result
