### ISSUE TITLE
Panic in filters.bloomFilter()

### ISSUE THREAD

**Issue by balboah** [ethereum/go-ethereum#2863]
#### System information

Geth version:
```
Version: 1.4.10-stable-5f55d95a
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: darwin
```

OS & Version: OSX 10.10.5

#### Expected behaviour

Clean shutdown after exiting `geth console` with ctrl+d.

#### Actual behaviour

Panic on filters.bloomFilter.

#### Steps to reproduce the behaviour
I used mist 0.8.1 to show the wallet account before exiting.

#### Backtrace

```
> I0725 20:18:50.781562 node/node.go:328] IPC endpoint closed: /Users/johnny/Library/Ethereum/geth.ipc
I0725 20:18:50.781599 core/blockchain.go:565] Chain manager stopped
I0725 20:18:50.781608 eth/handler.go:227] Stopping ethereum protocol handler...
I0725 20:18:50.782208 eth/handler.go:248] Ethereum protocol handler stopped
I0725 20:18:50.782242 core/tx_pool.go:163] Transaction pool stopped
I0725 20:18:50.782340 eth/backend.go:500] Automatic pregeneration of ethash DAG OFF (ethash dir: /Users/johnny/.ethash)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x454a221]

goroutine 19436 [running]:
panic(0x4aaef00, 0xc82000e110)
	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/ethereum/go-ethereum/eth/filters.(*Filter).bloomFilter(0xc82cbc9680, 0x0, 0xa792cc7a6a20405d)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:208 +0xf1
github.com/ethereum/go-ethereum/eth/filters.(*Filter).getLogs(0xc82cbc9680, 0x1a7570, 0x1a7957, 0xc831387ef0, 0x1, 0x1)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:137 +0x157
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82cbc9680, 0x19f0a0, 0x1ab3ef, 0x4, 0xc8310051c0, 0x4, 0x4)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:109 +0x391
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82cbc9680, 0x19f0a0, 0x1b773f, 0x3, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82cbc9680, 0x16e360, 0x1dc61d, 0x2, 0xc827890a00, 0x3d, 0x40)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82cbc9680, 0xf4240, 0x1dc61d, 0x1, 0xc8319a3000, 0xeb, 0x100)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82cbc9680, 0x61a80, 0x1dc61d, 0x0, 0xc833311c20, 0x9, 0xa)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).Find(0xc82cbc9680, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:91 +0x1bd
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc8200aa210, 0xc8311c47e0, 0x22, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/api.go:534 +0xf1
reflect.Value.call(0x49c5f00, 0x4bb1a68, 0x13, 0x4c01d68, 0x4, 0xc8311c4810, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/opt/go/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x49c5f00, 0x4bb1a68, 0x13, 0xc8311c4810, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/reflect/value.go:303 +0xb1
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc820401230, 0x89a43e8, 0xc833751170, 0x688a908, 0xc8265722d0, 0xc8261c7a40, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x1260
github.com/ethereum/go-ethereum/rpc.(*Server).execBatch(0xc820401230, 0x89a43e8, 0xc833751170, 0x688a908, 0xc8265722d0, 0xc82a5a6f58, 0x1, 0x1)
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:369 +0x48b
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/private/tmp/ethereum-20160716-3994-1sbxzy2/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:214 +0xc23
```

**Comment by fjl** [comment]
Related: #2858

**Comment by bas-vk** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/2873
