### ISSUE TITLE
Geth stucking at synchronizing

### ISSUE THREAD

**Issue by Xardesso** [ethereum/go-ethereum#28641]
I trying to run my eth mainnet node using Geth and prysm but synchronizing process still stucking.And when I stopping and restarting again this start form point when this started earlier and this everything goes into loop and I can't sync this.

Hardware 
Ryzen 5 3600 
16GB 3200 mhz ram 
Os 
Windows 11

Everything goes:
```
INFO [12-05|02:29:14.015] Syncing: state download in progress synced=0.36% state=961.17MiB accounts=828,468@197.22MiB slots=3,547,812@720.93MiB codes=13712@43.02MiB eta=5h39m55.204s 
```

But at some point:
```
INFO [12-05|02:29:14.329] Forkchoice requested sync to new head number=18,716,880 hash=6f3350..44c33b finalized=18,716,804 runtime: out of memory: cannot allocate 4194304-byte block (1434615808 in use) fatal error: out of memory goroutine 69976 [running]: runtime.throw({0x2372da2, 0xd}) runtime/panic.go:1077 +0x4d fp=0x51ee3658 sp=0x51ee3644 pc=0xd31a9d runtime.(*mcache).allocLarge(0x60109c8, 0x100000, 0x1) runtime/mcache.go:236 +0x1c5 fp=0x51ee3684 sp=0x51ee3658 pc=0xd093a5 runtime.mallocgc(0x100000, 0x0, 0x0) runtime/malloc.go:1123 +0x5bd fp=0x51ee36d8 sp=0x51ee3684 pc=0xd00edd github.com/cockroachdb/pebble/internal/rawalloc.New(...) github.com/cockroachdb/pebble@v0.0.0-20230928194634-aa077af62593/internal/rawalloc/rawalloc.go:22 github.com/cockroachdb/pebble.(*Batch).grow(0x7ab550e0, 0x4f) github.com/cockroachdb/pebble@v0.0.0-20230928194634-aa077af62593/batch.go:1392 +0x9b fp=0x51ee36fc sp=0x51ee36d8 pc=0x146069b
```

**Comment by weiihann** [comment]
I think the maintainers would appreciate it if you can provide the following details:
1. Available disk space
2. Geth version 
3. Geth startup command
4. Memory usage logs

My guess is that you are trying to run a node on your regular laptop machine, which has a bunch of other processes running at the same time, then they all compete for the same limited RAM, causing geth to produce out-of-memory (OOM) error.

**Comment by holiman** [comment]
> And when I stopping and restarting again

Stopping and restarting _during_ sync is _very_ bad for performance, since it may take quite some time to amass a good set of peers, and the chain progresses while you restart, so the local data you have is getting stale. 

> this everything goes into loop

So it may seem - how long has it been syncing? 

> ` Syncing: state download in progress synced=0.36% state=961.17MiB accounts=828,468@197.22MiB slots=3,547,812@720.93MiB codes=13712@43.02MiB eta=5h39m55.204s `

It gave you and eta of ~6 hours. 

> `Forkchoice requested sync to`

That's not an error, it's informing you that according to the CL node, the chain is progressing. That is to be expected. 

So far nothing you have described indicates an error.

**Comment by Xardesso** [comment]
> I think the maintainers would appreciate it if you can provide the following details:
> 
> 1. Available disk space
> 2. Geth version
> 3. Geth startup command
> 4. Memory usage logs
> 

> My guess is that you are trying to run a node on your regular laptop machine, which has a bunch of other processes running at the same time, then they all compete for the same limited RAM, causing geth to produce out-of-memory (OOM) error.

Avilable disk space 74GB
Version: 1.13.5-stable

Geth startup command 
geth --mainnet --http --http.api eth,net,engine,admin --authrpc.jwtsecret="E:\geth\etherum\jwt.hex"

Prysm startup command 
prysm.bat beacon-chain --execution-endpoint=http://localhost:8551 --mainnet --jwt-secret="E:\geth\etherum\jwt.hex" --accept-terms-of-use

I created logs but i got this in .blg file which i cannot attach so i converted it into csv format 
[logfile.csv](https://github.com/ethereum/go-ethereum/files/13559679/logfile.csv)

**Comment by Xardesso** [comment]
> The logfile is something else entirely, I have no idea what it is that you attached. The thing that you took a screenshot of, that is the log that would be interesting.
> 
> You seem to be running into out of memory, after allocating 1_297_448_960 bytes, or `1.3GB`. How much ram do you have?
> 
> EDIT: Saw now, `16GB` ram reported from the get-go. It's a bit odd that you run out of it so early...
> 
> Also `74GB` is far too little, you need quite a lot more than that, particularly with `scheme=hash` (which is default)

I can attach you logs in an original file using file io: 
https://www.file.io/xohi/download/Ize201u2bISn
And how much GB is recommended?

**Comment by Xardesso** [comment]
> 16GB total RAM is one thing, but what else is there running beside Geth? And how much cache did you permit Geth to use (did you set the --cache flag)?

I have few programs running in background but those program use very little amount of ram.And i don't used --cache flag earlier.And when the Geth is running i have around 60% of memory usage

**Comment by Xardesso** [comment]
> > I can attach you logs in an original file using file io:
> 
> I don't know what you have there, but it's not the geth-output anyway
its memory usage logs not geth logs

**Comment by weiihann** [comment]
> I can attach you logs in an original file using file io: https://www.file.io/xohi/download/Ize201u2bISn And how much GB is recommended?

Check the hardware requirements [here](https://geth.ethereum.org/docs/getting-started/hardware-requirements). You need at least 2TB of disk space to run both geth full node and a consensus client.

**Comment by Xardesso** [comment]
> > I can attach you logs in an original file using file io: https://www.file.io/xohi/download/Ize201u2bISn And how much GB is recommended?
> 
> Check the hardware requirements [here](https://geth.ethereum.org/docs/getting-started/hardware-requirements). You need at least 2TB of disk space to run both geth full node and a consensus client on ETH mainnet.

So maybe disk space causes errors.

**Comment by Xardesso** [comment]
I tried to run light node but i got this errors on geth and prysm 
![image](https://github.com/ethereum/go-ethereum/assets/112291196/89f15410-3c36-4049-a2c3-4248e16520d1)

**Comment by plscomeback** [comment]
i think is it disk
