### ISSUE TITLE
Panic in Trie Tracer when processing block from Sepoilia

### ISSUE THREAD

**Issue by dthuering** [ethereum/go-ethereum#28968]
#### System information

Geth version: `n/a`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

Block is processed

#### Actual behaviour

We are running Consensys Orchestrate, which uses an older version of go-ethereum that does not support Blob yet. So we tried upgrading to v1.12.2 and 1.13.12 but always got the panic attached below.

There is only one Sepolia chain setup using Infura.

What could cause this panic and how to mitigate?

#### Backtrace

```
INFO   [0006] (tx-listener.session.ethereum): fetch chain tip  chain=f75cb229-07c2-4232-8609-5ffb37821e53 number=5258223
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104170418]

goroutine 214 [running]:
github.com/ethereum/go-ethereum/trie.(*tracer).reset(...)
        /Users/danny/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.12/trie/tracer.go:88
github.com/ethereum/go-ethereum/trie.(*Trie).Reset(0x14000e4a370)
        /Users/danny/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.12/trie/trie.go:670 +0x58
github.com/ethereum/go-ethereum/core/types.DeriveSha({0x105277e20, 0x14000d1c078}, {0x105283228, 0x14000e4a370})
        /Users/danny/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.12/core/types/hashing.go:106 +0x48
github.com/ethereum/go-ethereum/core/types.NewBlock(0x14000828270?, {0x14000039000?, 0x4d, 0x80}, {0x106df6520, 0x0, 0x0}, {0x106df6520, 0x0, 0x0}, ...)
        /Users/danny/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.12/core/types/block.go:230 +0xe4
github.com/consensys/orchestrate/pkg/toolkit/ethclient/rpc.(*Client).BlockByNumber(0x5038ed?, {0x1052942b0, 0x140007542d0}, {0x14000e2a050, 0x47}, 0x1400050c380)
        /Users/danny/workspace/Webmobix/orchestrate/pkg/toolkit/ethclient/rpc/ethereum.go:47 +0x1ec
github.com/consensys/orchestrate/services/tx-listener/session/ethereum.(*Session).listen.(*Session).fetchBlock.func1.1()
        /Users/danny/workspace/Webmobix/orchestrate/services/tx-listener/session/ethereum/session.go:318 +0x80
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0x1400073bf48, {0x105277560, 0x1400050c340}, 0x1400073be90, {0x0?, 0x0?})
        /Users/danny/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:55 +0xc8
github.com/cenkalti/backoff/v4.RetryNotify(0x1052765e8?, {0x105277560?, 0x1400050c340?}, 0x0?)
        /Users/danny/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:34 +0x2c
github.com/consensys/orchestrate/services/tx-listener/session/ethereum.(*Session).listen.(*Session).fetchBlock.func1()
        /Users/danny/workspace/Webmobix/orchestrate/services/tx-listener/session/ethereum/session.go:316 +0xec
github.com/consensys/orchestrate/services/tx-listener/session/ethereum.NewFuture.func1()
        /Users/danny/workspace/Webmobix/orchestrate/services/tx-listener/session/ethereum/future.go:17 +0x30
created by github.com/consensys/orchestrate/services/tx-listener/session/ethereum.NewFuture in goroutine 114
        /Users/danny/workspace/Webmobix/orchestrate/services/tx-listener/session/ethereum/future.go:16 +0xd8
````

When submitting logs: please submit them as text and not screenshots.

**Comment by dthuering** [comment]
Having the same panic on mainnet too and it looks like the issue was introduced with v1.11.5.

**Comment by dthuering** [comment]
I can get rid of the nil pointer by changing `trie.go`s `Reset` method.

```go
//t.tracer.reset()
t.tracer = newTracer()
```
Now it works again on mainnet but getting new errors on Spolia related to the new BlobTx.

```
'r' value overflows uint256
```

Currently testing with v1.12.2. Will go back to v1.13.12 tomorrow.

**Comment by dthuering** [comment]
Found the root cause for the original issue. Orchetrate is calling `NewBlock` and passes a Trie created with `new(trie.Trie)` which will not have a Tracer set. Fixing it there.
