### ISSUE TITLE
Issues with macOS Sierra Beta, can't sync blocks

### ISSUE THREAD

**Issue by econoar** [ethereum/go-ethereum#2906]
#### System information

Geth version: 1.4.10
OS & Version: macOS Sierra

Mist/geth works fine on El Capitan but testing it out on the Sierra beta does not allow me to sync blocks.  I get fairly erratic behavior, sometimes it goes to the block count and just sits there and sometimes it says node sync failed right away.

Starting geth directly, I also see a variation of error messages.  The latest is below:

```
I0812 19:23:32.801542 ethdb/database.go:169] closed db:/Users/Eric/Library/Ethereum/chaindata
I0812 19:23:32.809829 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /Users/Eric/Library/Ethereum/chaindata
I0812 19:23:33.224751 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /Users/Eric/Library/Ethereum/dapp
I0812 19:23:33.235967 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0812 19:23:33.236251 eth/backend.go:201] Blockchain DB Version: 3
I0812 19:23:33.239279 core/blockchain.go:206] Last header: #2060236 [f58fc3c3…] TD=47316260148734322922
I0812 19:23:33.239329 core/blockchain.go:207] Last block: #2060236 [f58fc3c3…] TD=47316260148734322922
I0812 19:23:33.239358 core/blockchain.go:208] Fast block: #2060236 [f58fc3c3…] TD=47316260148734322922
I0812 19:23:33.246408 p2p/server.go:313] Starting Server
I0812 19:23:33.250067 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(10.0.1.1)
I0812 19:23:33.258826 p2p/discover/udp.go:217] Listening, enode://9d12afe2cd3a38fe3b2184bc60767cd4a94f21eca3500373ce8fa75b885fb7035288de6740f538410c25145c81dbf4b90eeacf2c00f8839cb478ea13f6a54d34@107.3.116.31:30303
I0812 19:23:33.260759 p2p/server.go:556] Listening on [::]:30303
I0812 19:23:33.262617 node/node.go:296] IPC endpoint opened: /Users/Eric/Library/Ethereum/geth.ipc
I0812 19:23:33.267424 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(10.0.1.1)
I0812 19:23:58.729932 eth/handler.go:295] Peer e8f86db2bdffd4c9 [eth/63]: timed out DAO fork-check, dropping
failed MSpanList_Insert 0x8998840 0x65eb043251e 0x0 0x0
fatal error: MSpanList_Insert

```

Sometimes I get this one though:
```

panic: sync: inconsistent mutex state

goroutine 501 [running]:
panic(0x48f6ea0, 0xc823b5cba0)
	/Users/jeffrey/goroot16/src/runtime/panic.go:464 +0x3e6
sync.(*Mutex).Lock(0xc821069270)
	/Users/jeffrey/goroot16/src/sync/mutex.go:75 +0x16d
github.com/ethereum/go-ethereum/p2p.(*rlpx).ReadMsg(0xc821069260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:86 +0x8a
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc8239e73c0, 0xc8212751a0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:214 +0x90
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/p2p/peer.go:145 +0xf9
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by econoar** [comment]
I found the fix but if I'm being completely honest I don't really understand it, but wanted to pass it onto the dev team.

https://forums.docker.com/t/docker-beta-for-mac-does-not-work-and-hangs-frequently-on-macos-10-12/18109/5

Disabling ntpd via sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist now lets me sync!  Not sure if this is an apple bug or go bug or what.

**Comment by fjl** [comment]
Please use Go 1.7rc6 [download here](https://golang.org/dl/) to compile geth on macOS Sierra.
