### ISSUE TITLE
panic occurs and cpu usage 100% 

### ISSUE THREAD

**Issue by hrkytzk** [ethereum/go-ethereum#29199]
Every 15 minutes, a panic occurs and the restart is repeated.
The CPU of the instance is at 100% at that time.
I don't see what the problem is....

CPU: 8cores
MEM: 32GB

#### System information

Geth version: `1.13.14`
CL client & version: prysm@v5.0.1 rc.3
OS & Version: Linux

#### Expected behaviour

no panic

#### Actual behaviour

cause panic

#### Steps to reproduce the behaviour

When I received this from my contact person, this problem had already occurred and I do not know how to reproduce it.
What is certain is that this problem continues to occur now.

#### Backtrace

````
Mar 08 17:13:11 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:11.589] Looking for peers                        peercount=1 tried=29 static=0
Mar 08 17:13:12 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:12.603] Forkchoice requested sync to new head    number=5,440,795 hash=51ab78..1e3893 finalized=5,440,708
Mar 08 17:13:18 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: WARN [03-08|17:13:18.802] Served debug_traceBlockByHash            conn=10.14.1.76:43476 reqid=1 duration=4.154727ms err="required historical state unavailable (reexec=128)"
Mar 08 17:13:22 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:22.184] Looking for peers                        peercount=1 tried=18 static=0
Mar 08 17:13:26 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:26.081] Forkchoice requested sync to new head    number=5,440,796 hash=5dfb8b..6122c0 finalized=5,440,708
Mar 08 17:13:26 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:26.440] Imported new chain segment               number=5,437,084 hash=48709f..20911e blocks=3  txs=217 mgas=31.259 elapsed=14.970s mgasps=2.088 age=13h3m26s  snapdiffs=253.27KiB triedirty=9.16MiB
Mar 08 17:13:32 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:32.670] Looking for peers                        peercount=1 tried=31 static=0
Mar 08 17:13:34 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:34.944] Imported new chain segment               number=5,437,086 hash=a383dc..c4d9c1 blocks=2  txs=142 mgas=17.740 elapsed=8.503s  mgasps=2.086 age=13h3m10s  snapdiffs=290.08KiB triedirty=10.47MiB
Mar 08 17:13:37 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:37.940] Forkchoice requested sync to new head    number=5,440,797 hash=7fee74..7f0039 finalized=5,440,708
Mar 08 17:13:40 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: WARN [03-08|17:13:40.639] Served debug_traceBlockByHash            conn=10.14.1.76:35842 reqid=1 duration=4.292915ms err="required historical state unavailable (reexec=128)"
Mar 08 17:13:43 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: INFO [03-08|17:13:43.225] Looking for peers                        peercount=1 tried=23 static=0
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: panic: execution timeout at bigInt:1:24234(0) [recovered]
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: panic: execution timeout at bigInt:1:24234(0) [recovered]
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: panic: execution timeout at bigInt:1:24234(0) [recovered]
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: panic: execution timeout at bigInt:1:24234(0)
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: goroutine 112864 [running]:
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: encoding/json.(*encodeState).marshal.func1()
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: encoding/json/encode.go:291 +0x6d
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: panic({0x17fc660?, 0xc030046f40?})
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: runtime/panic.go:914 +0x21f
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal systemd[1]: geth.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal systemd[1]: Unit geth.service entered failed state.
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal systemd[1]: geth.service failed.
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal systemd[1]: geth.service holdoff time over, scheduling restart.
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal systemd[1]: Stopped Geth Ethereum Daemon.
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal systemd[1]: Started Geth Ethereum Daemon.
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[18092]: INFO [03-08|17:13:45.447] Starting Geth on Sepolia testnet...
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[18092]: INFO [03-08|17:13:45.447] Maximum peer count                       ETH=50 total=50
Mar 08 17:13:45 ip-10-18-1-91.ap-northeast-1.compute.internal geth[18092]: INFO [03-08|17:13:45.448] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
````

and eth.syncing is odd....?
```
> eth.syncing
{
  currentBlock: 5437071,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 5440815,
  startingBlock: 5437135,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 2350000,
  txIndexRemainingBlocks: 0
}
```

I would appreciate it if someone could tell me what is going on.

**Comment by holiman** [comment]
What happens, is that you are hitting this: https://github.com/ethereum/go-ethereum/blob/c41105ce80f12f60ec4bf6c65c4c59c6bf4a86e7/eth/tracers/api.go#L967 . 

Someone (you? `10.14.1.76` )  is invoking the tracing functionality, 
```
Mar 08 17:13:40 ip-10-18-1-91.ap-northeast-1.compute.internal geth[9234]: WARN [03-08|17:13:40.639] Served debug_traceBlockByHash            conn=10.14.1.76:35842 reqid=1 duration=4.292915ms err="required historical state unavailable (reexec=128)"
```
The tracing is interrupted after a while. But I don't know why that causes a `panic`, or why it results in the main process dying with `status=2/INVALIDARGUMENT`.

**Comment by s1na** [comment]
I haven't been able to reproduce a panic by using a low timeout. Sure the tracer reports an unexpected error sometimes but geth doesn't panic. Can you please share more info what you're doing? possibly your tracer script?

Also as a side note, I recommend migrating to a [native Go tracer](https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer).

**Comment by holiman** [comment]
Seems abandoned/answered
