### ISSUE TITLE
geth 1.13.14 stops syncing after method panic engine_newPayloadV2 crashed: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/go-ethereum#29237]
#### System information

Geth version: `1.13.14-stable`
CL client & version: e.g. lighthouse
OS & Version: Linux

#### Actual behaviour
```
ERROR[03-12|16:27:36.476] RPC method engine_newPayloadV2 crashed: runtime error: makeslice: cap out of range
goroutine 133550795 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
        github.com/ethereum/go-ethereum/rpc/service.go:199 +0x85
panic({0x562aae1e1b20?, 0x562aae42b790?})
        runtime/panic.go:770 +0x132
github.com/ethereum/go-ethereum/triedb/pathdb.newHistory({0xb1, 0x9f, 0x2c, 0x32, 0x46, 0x9f, 0x14, 0xc6, 0x15, 0x3, ...}, ...)
        github.com/ethereum/go-ethereum/triedb/pathdb/history.go:268 +0x253
github.com/ethereum/go-ethereum/triedb/pathdb.writeHistory(0xc0187caf80, 0xc040e10310)
        github.com/ethereum/go-ethereum/triedb/pathdb/history.go:523 +0xe5
github.com/ethereum/go-ethereum/triedb/pathdb.(*diskLayer).commit(0xc021cdfc80, 0xc040e10310, 0x0)
        github.com/ethereum/go-ethereum/triedb/pathdb/disklayer.go:183 +0xe6
github.com/ethereum/go-ethereum/triedb/pathdb.diffToDisk(0xc040e10310, 0x0)
        github.com/ethereum/go-ethereum/triedb/pathdb/difflayer.go:173 +0x45
github.com/ethereum/go-ethereum/triedb/pathdb.(*diffLayer).persist(0xc040e10310, 0x0)
        github.com/ethereum/go-ethereum/triedb/pathdb/difflayer.go:163 +0xad
github.com/ethereum/go-ethereum/triedb/pathdb.(*layerTree).cap(0xc007d82100, {0x28, 0x12, 0xfb, 0x4, 0x41, 0xf0, 0x66, 0x72, 0x29, ...}, ...)
        github.com/ethereum/go-ethereum/triedb/pathdb/layertree.go:159 +0x4ff
github.com/ethereum/go-ethereum/triedb/pathdb.(*Database).Update(0xc0054140f0, {0x28, 0x12, 0xfb, 0x4, 0x41, 0xf0, 0x66, 0x72, 0x29, ...}, ...)
        github.com/ethereum/go-ethereum/triedb/pathdb/database.go:243 +0x1a5
github.com/ethereum/go-ethereum/triedb.(*Database).Update(0xc000433220?, {0x28, 0x12, 0xfb, 0x4, 0x41, 0xf0, 0x66, 0x72, 0x29, ...}, ...)
        github.com/ethereum/go-ethereum/triedb/database.go:148 +0xa3
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit(0xc0471934a0, 0x12852f3, 0xf3?)
        github.com/ethereum/go-ethereum/core/state/statedb.go:1280 +0xcb5
github.com/ethereum/go-ethereum/core.(*BlockChain).writeBlockWithState(0xc000307408, 0xc01fdfaa00, {0xc00ae14408, 0x92, 0x11f}, 0xc0471934a0)
        github.com/ethereum/go-ethereum/core/blockchain.go:1368 +0x792
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc000307408, {0xc00011f9c8, 0x1, 0x1}, 0x0)
        github.com/ethereum/go-ethereum/core/blockchain.go:1808 +0x2065
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertBlockWithoutSetHead(0xc000307408, 0xc01fdfaa00)
        github.com/ethereum/go-ethereum/core/blockchain.go:2287 +0xc7
github.com/ethereum/go-ethereum/eth/catalyst.(*ConsensusAPI).newPayload(_, {{0x54, 0x62, 0x4c, 0x4b, 0xb9, 0x29, 0x96, 0x98, 0x9d, ...}, ...}, ...)
        github.com/ethereum/go-ethereum/eth/catalyst/api.go:617 +0xe05
github.com/ethereum/go-ethereum/eth/catalyst.(*ConsensusAPI).NewPayloadV2(_, {{0x54, 0x62, 0x4c, 0x4b, 0xb9, 0x29, 0x96, 0x98, 0x9d, ...}, ...})
        github.com/ethereum/go-ethereum/eth/catalyst/api.go:508 +0x32b
reflect.Value.call({0xc0197cbbc0?, 0xc01b555af0?, 0x50?}, {0x562aadacecb0, 0x4}, {0xc04a50fcc0, 0x2, 0xc04a50fcc0?})
        reflect/value.go:596 +0xce5
reflect.Value.Call({0xc0197cbbc0?, 0xc01b555af0?, 0x1?}, {0xc04a50fcc0?, 0x16?, 0x16?})
        reflect/value.go:380 +0xb9
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc00598d260, {0x562aae441730, 0xc04a50fc20}, {0xc0280a4cc0, 0x13}, {0xc03c4b6558, 0x1, 0x562aaca21e6f?})
        github.com/ethereum/go-ethereum/rpc/service.go:205 +0x36d
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc055b2e000?, {0x562aae441730?, 0xc04a50fc20?}, 0xc01601e620, 0x1?, {0xc03c4b6558?, 0xc000c28dc0?, 0x562aac95edfa?})
        github.com/ethereum/go-ethereum/rpc/handler.go:565 +0x3c
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc01fdfa1e0, 0xc041a2f470, 0xc01601e620)
        github.com/ethereum/go-ethereum/rpc/handler.go:512 +0x22f
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc01fdfa1e0, 0xc041a2f470, 0xc01601e620)
        github.com/ethereum/go-ethereum/rpc/handler.go:470 +0x22d
github.com/ethereum/go-ethereum/rpc.(*handler).handleNonBatchCall(0xc01fdfa1e0, 0xc041a2f470, 0xc01601e620)
        github.com/ethereum/go-ethereum/rpc/handler.go:296 +0x18a
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1.1(0x562aae441730?)
        github.com/ethereum/go-ethereum/rpc/handler.go:269 +0x25
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
        github.com/ethereum/go-ethereum/rpc/handler.go:387 +0xbe
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc in goroutine 133478763
        github.com/ethereum/go-ethereum/rpc/handler.go:383 +0x79
WARN [03-12|16:27:36.477] Served engine_newPayloadV2               conn=XXX reqid=1 duration=79.385447ms err="method handler crashed"
WARN [03-12|16:27:50.662] Ignoring already known beacon payload    number=19,419,891 hash=b5a7f2..370f06 age=15s
WARN [03-12|16:30:02.388] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!

```

**Comment by karalabe** [comment]
This is extremely strange. That line is

```
slist := make([]common.Hash, 0, len(slots))
```

The only thing that's variable there is `len(slots)`, but `0` is valid https://go.dev/play/p/5znjcdUFtFP and it cannot return a negative value. Anything higher should also be valid.

**Comment by SjonHortensius** [comment]
yeah I couldn't replicate it either. Looking at https://github.com/golang/go/blob/34d28ba932cc26af9ae6c0233f4967a9b7cd94c2/src/runtime/slice.go#L94 the only valid reasons are:

* overflow
* mem > maxAlloc
* len < 0
* len > cap

with `len` being zero the last two are ruled out, as `cap` cannot be negative either (as it comes from another `len()` call

**Comment by learnerLj** [comment]
Could you please provide the memory used and CPU usage? I encountered similar problems in pebble library. And my answer is that 8 geth connecting to more than 10,000 peers exhaust the memory, causing strange runtime errors.

**Comment by rjl493456442** [comment]
> encountered similar problems in pebble library

Could you please share the panic logs in your case?

**Comment by learnerLj** [comment]
> Could you please share the panic logs in your case?

see on gist: https://gist.github.com/learnerLj/6bd9c2ffb24a0a628561f220af1afb11

I modify the DHT size of each bucket to 1000, and increase the maximal concurrent number of p2p to very large number.

**Comment by holiman** [comment]
This seems like a one-off, let's just blame cosmic radiation
