### ISSUE TITLE
beacon/light/api: eventsource client doesn't stop

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#29264]
Observed hang when stopping geth:

```
goroutine 4404 [runnable]:
github.com/ethereum/go-ethereum/beacon/light/api.(*BeaconLightApi).StartHeadListener.func2()
	/home/admin/go-ethereum/beacon/light/api/light_api.go:467 +0x3b7
created by github.com/ethereum/go-ethereum/beacon/light/api.(*BeaconLightApi).StartHeadListener in goroutine 1
	/home/admin/go-ethereum/beacon/light/api/light_api.go:449 +0x1f9

goroutine 4659 [chan receive]:
github.com/ethereum/go-ethereum/beacon/light/api.(*BeaconLightApi).StartHeadListener.func3()
	/home/admin/go-ethereum/beacon/light/api/light_api.go:505 +0x45
github.com/ethereum/go-ethereum/beacon/light/api.(*ApiServer).Unsubscribe(0x875402660)
	/home/admin/go-ethereum/beacon/light/api/api_server.go:100 +0x1d
github.com/ethereum/go-ethereum/beacon/light/request.(*serverWithTimeout).unsubscribe(0x8758ac0b0)
	/home/admin/go-ethereum/beacon/light/request/server.go:226 +0x12e
github.com/ethereum/go-ethereum/beacon/light/request.(*serverWithLimits).unsubscribe(0x8758ac0b0)
	/home/admin/go-ethereum/beacon/light/request/server.go:350 +0xe5
github.com/ethereum/go-ethereum/beacon/light/request.(*Scheduler).Stop(0x8745b8630)
	/home/admin/go-ethereum/beacon/light/request/scheduler.go:191 +0xd4
github.com/ethereum/go-ethereum/beacon/blsync.(*Client).Stop(0x874983f20)
```

I think we can fix this by using a shared base context for the eventsource HTTP requests. The context could be cancelled on stop.

**Comment by zsfelfoldi** [comment]
Fixed, looks like the eventsource was fine:
https://github.com/ethereum/go-ethereum/pull/29180/commits/49fd7f5097c1441f1d9c8aab126b4bc6bce6ee06
Not sure how it went unnoticed but it was already wrong on master. Blsync did exit because it just killed this loop but geth in light mode hung on exit.
