### ISSUE TITLE
DELEGATECALL not working on private chain

### ISSUE THREAD

**Issue by kevinday** [ethereum/go-ethereum#2937]
#### System information

```
Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

On a brand new VM, I am doing:

` geth init genesis.json `

with the following genesis.json

```
{
  "nonce": "0x0000000000000021",
  "difficulty": "0x00",
  "config": {
    "homesteadBlock": 0,
    "daoForkBlock" : 0,
    "daoForkSupport" : true
  },
  "alloc": {
    "7fbe93bc104ac4bcae5d643fd3747e1866f1ece4": {
      "balance": "1000000000000000000000000000000"
    }
  },
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x2fefd8"
}
```

Running geth by doing `/usr/bin/geth --password /home/auguruser/pw.txt --unlock 0 --maxpeers 0 --networkid 1101011 --rpcaddr "0.0.0.0" --rpc --rpccorsdomain "*" --ws --wsapi "eth,net,web3,txpool" --wsport 8546 --wsaddr "0.0.0.0" --wsorigins "*"`

Mining is turned on. All of the other contracts that I have loaded seem to work fine, except for those that make use of DELEGATECALL. (https://github.com/AugurProject/augur-core/blob/master/src/functions/createMarket.se#L38, for example).

Unfortunately attempting to trace the failing transaction is failing.

```

debug.traceTransaction("0x38a08e4eae300464e25c14ea32d6f33f41927a77f2288268bcbc00cc91e7d989")

Invalid JSON RPC response: {"error":{"EOF":"EOF","code":-32603},"id":8,"version":"2.0"}
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

Here is the block the transaction that is failing is in
```
eth.getBlock(53)
{
  difficulty: 131072,
  extraData: "0xd783010500844765746887676f312e352e31856c696e7578",
  gasLimit: 24872238750,
  gasUsed: 3135000,
  hash: "0x7ebbc1f08e00996fd8b14ee39c7ba069f9e3d137b044a0a8fe320b46c107e042",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x7fbe93bc104ac4bcae5d643fd3747e1866f1ece4",
  nonce: "0x60c1296dc375efb5",
  number: 53,
  parentHash: "0x9007e26f513cca1c91c50871b47af5b0cad78643d5d48c89c61dabfa27a59af5",
  receiptRoot: "0x2616ec74e34c22f223dc20ddb38930a7c19980b3f6c505dad710350252c50dfd",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 1267,
  stateRoot: "0x4a351d0ca1914b0b8b6eaf7413613fd360f83ea403a625a7cb686182311af957",
  timestamp: 1471994576,
  totalDifficulty: 6953216,
  transactions: ["0x38a08e4eae300464e25c14ea32d6f33f41927a77f2288268bcbc00cc91e7d989"],
  transactionsRoot: "0x692fdca5283f5213f4636ef10da88072a08da5f7b7c576e2dea336286651ab55",
  uncles: []
}
```

Is there an easy way to determine if my private chain is homestead enabled? Does that genesis.json look valid?

**Comment by kevinday** [comment]
Ok, after a bunch more digging I don't think this is a problem with geth. After disassembling the byteCode of my contract I noticed that it doesn't include `DELEGATECALL` anywhere.

Installing serpent as instructed by the serpent docs: `sudo pip install ethereum-serpent` apparently gives you a version of serpent that doesn't support DELEGATECALL, and instead just ignores the `call=delegate` bit of the contract.

That `pip install ethereum-serpent` doesn't do the right thing is a problem that should be fixed, but it isn't a problem with geth or this repo. Closing.
