### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#30591]
Another round of flaky tests

- [ ] `TestUDPv5_lookup` [log](https://ci.appveyor.com/project/ethereum/go-ethereum/builds/50779692/job/jlfnbvl27rqi2pod#L1113)
- [ ] `TestUDPv4_Lookup` [log](https://ci.appveyor.com/project/ethereum/go-ethereum/builds/50783875/job/6prad6hrqhawqrg7#L1113)

**Comment by holiman** [comment]
From the `v4` log
```
[00:27:16]     v4_udp.go:525: TRACE[10-12|17:54:22.059] >> PING/v4                                id=fb701727441d6fd5 addr=127.0.255.7:5000 err=<nil>
[00:27:16]     v4_udp.go:576: TRACE[10-12|17:54:22.060] << PONG/v4                                id=fb701727441d6fd5 addr=127.0.255.7:5000 err="unsolicited reply"
[00:27:16]     v4_lookup_test.go:161: error mismatch: got "unsolicited reply", want %!q(<nil>)
```
That's odd. We send a PING, then when we get the PONG, we deem it `unsolicited reply`

**Comment by holiman** [comment]
The v4 lookup test can be reproed locally with the following little change, simulating a bit of lag in the loop which handles adding the reply matcher

```
diff --git a/p2p/discover/v4_udp.go b/p2p/discover/v4_udp.go
index 29ae5f2c08..228175f6c8 100644
--- a/p2p/discover/v4_udp.go
+++ b/p2p/discover/v4_udp.go
@@ -466,6 +466,7 @@ func (t *UDPv4) loop() {
 			return
 
 		case p := <-t.addReplyMatcher:
+			time.Sleep(200 * time.Millisecond)
 			p.deadline = time.Now().Add(respTimeout)
 			plist.PushBack(p)
 
```

**Comment by holiman** [comment]
Odd. I tried this fix: 
```diff
diff --git a/p2p/discover/v4_udp.go b/p2p/discover/v4_udp.go
index 29ae5f2c08..cad16c54f7 100644
--- a/p2p/discover/v4_udp.go
+++ b/p2p/discover/v4_udp.go
@@ -76,12 +76,17 @@ type UDPv4 struct {
 	closeOnce   sync.Once
 	wg          sync.WaitGroup
 
-	addReplyMatcher chan *replyMatcher
+	addReplyMatcher chan *replyMatcherDone
 	gotreply        chan reply
 	closeCtx        context.Context
 	cancelCloseCtx  context.CancelFunc
 }
 
+type replyMatcherDone struct {
+	matcher *replyMatcher
+	done    chan struct{}
+}
+
 // replyMatcher represents a pending reply.
 //
 // Some implementations of the protocol wish to send more than one
@@ -137,7 +142,7 @@ func ListenV4(c UDPConn, ln *enode.LocalNode, cfg Config) (*UDPv4, error) {
 		localNode:       ln,
 		db:              ln.Database(),
 		gotreply:        make(chan reply),
-		addReplyMatcher: make(chan *replyMatcher),
+		addReplyMatcher: make(chan *replyMatcherDone),
 		closeCtx:        closeCtx,
 		cancelCloseCtx:  cancel,
 		log:             cfg.Log,
@@ -396,9 +401,10 @@ func (t *UDPv4) TableBuckets() [][]BucketNode {
 func (t *UDPv4) pending(id enode.ID, ip netip.Addr, ptype byte, callback replyMatchFunc) *replyMatcher {
 	ch := make(chan error, 1)
 	p := &replyMatcher{from: id, ip: ip, ptype: ptype, callback: callback, errc: ch}
+	pd := &replyMatcherDone{p, make(chan struct{})}
 	select {
-	case t.addReplyMatcher <- p:
-		// loop will handle it
+	case t.addReplyMatcher <- pd:
+		<-pd.done // wait until loop has handled it
 	case <-t.closeCtx.Done():
 		ch <- errClosed
 	}
@@ -465,9 +471,13 @@ func (t *UDPv4) loop() {
 			}
 			return
 
-		case p := <-t.addReplyMatcher:
-			p.deadline = time.Now().Add(respTimeout)
-			plist.PushBack(p)
+		case pd := <-t.addReplyMatcher:
+			time.Sleep(200 * time.Millisecond)
+			pd.matcher.deadline = time.Now().Add(respTimeout)
+			plist.PushBack(pd.matcher)
+			if pd.done != nil {
+				close(pd.done)
+			}
 
 		case r := <-t.gotreply:
 			var matched bool // whether any replyMatcher considered the reply acceptable.
diff --git a/p2p/discover/v4_udp_test.go b/p2p/discover/v4_udp_test.go
index 1af31f4f1b..f07056a11c 100644
--- a/p2p/discover/v4_udp_test.go
+++ b/p2p/discover/v4_udp_test.go
@@ -188,11 +188,11 @@ func TestUDPv4_responseTimeouts(t *testing.T) {
 		binary.BigEndian.PutUint64(p.from[:], uint64(i))
 		if p.ptype <= 128 {
 			p.errc = timeoutErr
-			test.udp.addReplyMatcher <- p
+			test.udp.addReplyMatcher <- &replyMatcherDone{p, nil}
 			nTimeouts++
 		} else {
 			p.errc = nilErr
-			test.udp.addReplyMatcher <- p
+			test.udp.addReplyMatcher <- &replyMatcherDone{p, nil}
 			time.AfterFunc(randomDuration(60*time.Millisecond), func() {
 				if !test.udp.handleReply(p.from, p.ip, testPacket(p.ptype)) {
 					t.Logf("not matched: %v", p)
```
But it still doesn't quite fix it. 
```
    v4_udp.go:535: TRACE[10-14|10:55:01.240] >> PING/v4                                id=92a53f9270c3f49a addr=127.0.252.1:5000 err=<nil>
    v4_udp.go:535: TRACE[10-14|10:55:01.441] >> PING/v4                                id=90fbc98b7a89b1f2 addr=127.0.252.0:5000 err=<nil>
    v4_udp.go:586: TRACE[10-14|10:55:01.441] << PONG/v4                                id=8fa27cc11cf1e325 addr=127.0.253.5:5000 err=<nil>
    table_reval.go:174: DEBUG[10-14|10:55:01.441] Node revalidated                          b=14 id=8fa27cc11cf1e325 checks=1 q=fast
    v4_udp.go:586: TRACE[10-14|10:55:01.444] << PONG/v4                                id=9274d81479b8baa8 addr=127.0.252.2:5000 err="unsolicited reply"
```

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by lightclient** [comment]
```
--- FAIL: TestWalletNotifications (0.54s)
    keystore_test.go:427: wallet list doesn't match required accounts: have 429, want 428
    keystore_test.go:455: can't find event with Kind=0 for 253061228b716cd444ccc9f3381792b538310045
FAIL
FAIL	github.com/ethereum/go-ethereum/accounts/keystore	8.741s
```

**Comment by lightclient** [comment]
```
--- FAIL: TestSimulatedBeaconSendWithdrawals (12.09s)
    simulated_beacon_test.go:139: timed out without including all withdrawals/txs
FAIL
FAIL	github.com/ethereum/go-ethereum/eth/catalyst	14.916s
```
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51457716/job/m50ess4o9qc47fur

**Comment by lightclient** [comment]
```
--- FAIL: TestBindings (129.24s)
    bind_test.go:2102: tmpdir /tmp/TestBindings1034863270/001/bindtest
    bind_test.go:2160: failed to run binding test: exit status 1
```
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51809451/job/201lshrjwbuq1jr0

**Comment by cskiraly** [comment]
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51967784/job/j0cwe8348m0we1aa
```
--- FAIL: TestAttachWelcome (5.47s)
    test_cmd.go:261: (stderr:1) WARN [04-29|14:02:22.341] Unknown config environment variable      envvar=GETH_ARCH
    test_cmd.go:261: (stderr:1) WARN [04-29|14:02:22.437] Unknown config environment variable      envvar=GETH_CC
    test_cmd.go:261: (stderr:1) WARN [04-29|14:02:22.437] Unknown config environment variable      envvar=GETH_MINGW
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.452] Starting Geth on Holesky testnet...
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.455] Maximum peer count                       ETH=0 total=0
    test_cmd.go:261: (stderr:1) WARN [04-29|14:02:22.460] Option --miner.etherbase is deprecated as the etherbase is set by the consensus client post-merge
    test_cmd.go:261: (stderr:1) WARN [04-29|14:02:22.467] Lowering memory allowance on 32bit arch  available=5998 addressable=2048
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.469] Set global gas cap                       cap=50,000,000
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.470] Initializing the KZG library             backend=gokzg
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.470] Allocated trie memory caches             clean=9.00MiB dirty=16.00MiB
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.470] Defaulting to pebble as the backing database
    test_cmd.go:261: (stderr:1) INFO [04-29|14:02:22.470] Allocated cache and file handles         database=C:\Users\appveyor\AppData\Local\Temp\1\TestAttachWelcome162174236\001\geth\chaindata cache=32.00MiB handles=8192
[...]
--- FAIL: TestAttachWelcome/ipc (4.02s)
[...]
--- FAIL: TestConsoleWelcome (30.13s)
```

**Comment by cskiraly** [comment]
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51846301/job/gv94cs1bi9ceh9rv
```
--- FAIL: TestBindings (133.02s)
    bind_test.go:2102: tmpdir /tmp/TestBindings2822256013/001/bindtest
    bind_test.go:2160: failed to run binding test: exit status 1
```

```
        --- FAIL: TestTuple (0.13s)
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        	panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1124cbd]
        
        goroutine 2372 [running]:
        testing.tRunner.func1.2({0x1399fa0, 0x24ff9e0})
        	/home/appveyor/.cache/geth-go-1.24.1-linux-amd64/go/src/testing/testing.go:1734 +0x21c
        testing.tRunner.func1()
        	/home/appveyor/.cache/geth-go-1.24.1-linux-amd64/go/src/testing/testing.go:1737 +0x35e
        panic({0x1399fa0?, 0x24ff9e0?})
        	/home/appveyor/.cache/geth-go-1.24.1-linux-amd64/go/src/runtime/panic.go:792 +0x132
        bindtest.TestTuple(0xc000fad180)
        	/tmp/TestBindings2822256013/001/bindtest/tuple_test.go:110 +0x173d
        testing.tRunner(0xc000fad180, 0x16d7bb0)
        	/home/appveyor/.cache/geth-go-1.24.1-linux-amd64/go/src/testing/testing.go:1792 +0xf4
        created by testing.(*T).Run in goroutine 1
        	/home/appveyor/.cache/geth-go-1.24.1-linux-amd64/go/src/testing/testing.go:1851 +0x413
        exit status 2
        FAIL	bindtest	2.956s
FAIL
FAIL	github.com/ethereum/go-ethereum/accounts/abi/abigen	133.080s
```

**Comment by cskiraly** [comment]
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51966681/job/9itl04p6akj4rwrf

```
--- FAIL: TestAllowedTxSize (0.01s)
    legacypool_test.go:1255: expected rejection on slightly oversize transaction
FAIL
FAIL	github.com/ethereum/go-ethereum/core/txpool/legacypool	10.425s
```

**Comment by jwasinger** [comment]
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51986510/job/6ngj0v1ktbyhbc1b
```
--- FAIL: TestSendTx (0.02s)
    api_backend_test.go:154: Unexpected error, want: in-flight transaction limit reached for delegated accounts, got: gapped-nonce tx from delegated accounts
```

**Comment by jwasinger** [comment]
`WebSocketLargeRead`: https://github.com/ethereum/go-ethereum/actions/runs/17145047311/job/48640027449
`DeploymentLibraries`: https://github.com/ethereum/go-ethereum/actions/runs/17129689768/job/48590946294

**Comment by ibondarev-gsu** [comment]
I would like to work on the TestUDPv4_Lookup subtask. On current master (7a1b11564, Go 1.25.12), the reported 200 ms delay in addReplyMatcher still reproduces the same unsolicited PONG failure on the first run. The unmodified test passed 100 race-enabled runs, so the failure appears scheduling-dependent. I will first add a deterministic regression test and investigate matcher scheduling and deadline handling rather than simply increasing respTimeout.
