### ISSUE TITLE
Out of memory with 1.4.13

### ISSUE THREAD

**Issue by chinh7** [ethereum/go-ethereum#3071]
Geth keeps crashing on a 4GB RAM x64 
Ubuntu box. Attached is the memory profile
[mem.txt](https://github.com/ethereum/go-ethereum/files/505647/mem.txt)

#### System information

Version: 1.4.13-stable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux

#### Actual behaviour

Out of Memory. Geth crashes 

#### Backtrace

````
goroutine 1206 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc823dc7d50, 0x0, 0x7f2600000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:357 +0x221
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc82037e0d0, 0xc8238575f0, 0x0, 0x0)
        /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:314 +0x97
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc82037e0d0, 0xc8238575f0, 0x0, 0x0)
        /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:303 +0xb36
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc8e2846d00, 0x7f26755a0928, 0xc823dc7d50, 0x0, 0x0)
        /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:138 +0x17b
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc823dc7d50, 0xc8e2846d00)
        /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:303 +0x8c
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:312 +0x304
````

**Comment by karalabe** [comment]
Yes, new morning, new attack :) Please update to Geth 1.4.15!

**Comment by ivands** [comment]
1.4.15 not available on via apt-get

**Comment by karalabe** [comment]
It seems to me from trusty upwards: https://launchpad.net/~ethereum/+archive/ubuntu/ethereum

**Comment by Mordong** [comment]
1.4.15 for Win10 ?

**Comment by karalabe** [comment]
Please see https://www.reddit.com/r/ethereum/comments/55muig/geth_1415_come_at_me_bro_dos_fixes/d8bwz0h

**Comment by Mordong** [comment]
got it, thanks, all blocks went through

**Comment by chinh7** [comment]
Looks like there's a new wave of attack. This is happening again with 1.4.15
