### ISSUE TITLE
Writing arbitrary values to the position of the bytes storage length causes storage errors.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/go-ethereum#30852]
#### System information

Geth version: 1.13.11(incorrect result), 1.14.12(crash)
CL client & version: None
OS & Version: Linux
Commit hash : relase

#### Description
First, write a large number to bytes.slot, then expand the bytes array. This will eventually cause a mismatch between the value stored at bytes.slot and the result in Remix.

#### Expected behaviour (Remix)
```solidity
contract C {
    bytes data;
    function fromStorage() public returns (uint) {
        assembly { sstore(data.slot, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00) }
        data.push();
        data.push();
        return data.length;
    }
}
```
```
{
	"0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563": {
		"key": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"value": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"
	}
}
```
After executing the program, according to the result in Remix, the value in data.slot is 0xfff...ff04.

#### Actual behaviour (1.13.11)
We instrumented [Geth](https://github.com/Subway2023/Geth-Instrument/tree/main) to output storage information. You can directly run /build/evm.

##### get function hash
```
solc test.sol --hashes --overwrite -o output
```
```
Function signatures:
c54699fb: fromStorage()
```
##### compile into bytecodes
```
solc test.sol --bin-runtime
```
```
608060405234801561000f575f80fd5b5060043610610029575f3560e01c8063c54699fb1461002d575b5f80fd5b61003561004b565b6040516100429190610158565b60405180910390f35b5f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff005f555f60018180548061007f9061019e565b80601f810361009c57835f5260205f2060ff1984168155603f9350505b506002820183556001810192505050038154600116156100c957905f5260205f2090602091828204019190065b90549050505f6001818054806100de9061019e565b80601f81036100fb57835f5260205f2060ff1984168155603f9350505b5060028201835560018101925050500381546001161561012857905f5260205f2090602091828204019190065b90549050505f80546101399061019e565b9050905090565b5f819050919050565b61015281610140565b82525050565b5f60208201905061016b5f830184610149565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52602260045260245ffd5b5f60028204905060018216806101b557607f821691505b6020821081036101c8576101c7610171565b5b5091905056fea2646970667358221220031cea2c5ef874a9f26658a88b97f9a3511aaa06f6199e5ca3f00eec7127dd2564736f6c634300081a0033
```

##### Run in evm
```
./build/bin/evm --debug --json --code 608060405234801561000f575f80fd5b5060043610610029575f3560e01c8063c54699fb1461002d575b5f80fd5b61003561004b565b6040516100429190610158565b60405180910390f35b5f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff005f555f60018180548061007f9061019e565b80601f810361009c57835f5260205f2060ff1984168155603f9350505b506002820183556001810192505050038154600116156100c957905f5260205f2090602091828204019190065b90549050505f6001818054806100de9061019e565b80601f81036100fb57835f5260205f2060ff1984168155603f9350505b5060028201835560018101925050500381546001161561012857905f5260205f2090602091828204019190065b90549050505f80546101399061019e565b9050905090565b5f819050919050565b61015281610140565b82525050565b5f60208201905061016b5f830184610149565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52602260045260245ffd5b5f60028204905060018216806101b557607f821691505b6020821081036101c8576101c7610171565b5b5091905056fea2646970667358221220031cea2c5ef874a9f26658a88b97f9a3511aaa06f6199e5ca3f00eec7127dd2564736f6c634300081a0033 --input c54699fb run > test.json
```
```
storage: {"0":"115792089237316195423570985008687907853269984665640564039457584007913129639684"}
```
When converting the storage value to hexadecimal, you get 0x100...00, which does not match the value in Remix.

#### Actual behaviour (1.14.12)
Running the same command on EVM results in the following error:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/vm.opMstore(0x0?, 0xc000440080, 0x0?)
        github.com/ethereum/go-ethereum/core/vm/instructions.go:508 +0x251
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc000440080, 0xc000500000, {0xc0004604d0, 0x4, 0x8}, 0x0)
        github.com/ethereum/go-ethereum/core/vm/interpreter.go:323 +0xd5e
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc0000ea000, {0x1662c20, 0xc000438030}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        github.com/ethereum/go-ethereum/core/vm/evm.go:224 +0xa2b
github.com/ethereum/go-ethereum/core/vm/runtime.Call({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        github.com/ethereum/go-ethereum/core/vm/runtime/runtime.go:216 +0x42c
main.runCmd.func2()
        github.com/ethereum/go-ethereum/cmd/evm/runner.go:285 +0x3d
main.timedExec(0x0?, 0xc00033c2d0)
        github.com/ethereum/go-ethereum/cmd/evm/runner.go:116 +0x390
main.runCmd(0xc00037d580)
        github.com/ethereum/go-ethereum/cmd/evm/runner.go:291 +0x1586
github.com/ethereum/go-ethereum/internal/flags.MigrateGlobalFlags.func2.1(0xc00037d580)
        github.com/ethereum/go-ethereum/internal/flags/helpers.go:90 +0x34
github.com/urfave/cli/v2.(*Command).Run(0x1f10a00, 0xc00037d580, {0xc000058cb0, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x93f
github.com/urfave/cli/v2.(*Command).Run(0xc00017e160, 0xc00036d1c0, {0xc000144000, 0x8, 0x8})
        github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xb7d
github.com/urfave/cli/v2.(*App).RunContext(0xc000452000, {0x166e130, 0x2119ac0}, {0xc000144000, 0x8, 0x8})
        github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x566
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
        github.com/ethereum/go-ethereum/cmd/evm/main.go:282 +0x45
```

**Comment by jwasinger** [comment]
You need to open this issue on the remix repository.  This is not a Geth issue.

**Comment by jwasinger** [comment]
> storage: {"0":"115792089237316195423570985008687907853269984665640564039457584007913129639684"}

You converted to hex incorrectly:
`hex(115792089237316195423570985008687907853269984665640564039457584007913129639684) == "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"`.  It outputs the result you expect.

So actually, it's not a bug in Remix or Geth.
