### ISSUE TITLE
geth 1.4.17 crash after block 2425548 (segfault)

### ISSUE THREAD

**Issue by celeduc** [ethereum/go-ethereum#3130]
#### System information

Geth version: 1.4.17
OS & Version: OSX El Capitan 10.11.6
Commit hash : geth-darwin-amd64-1.4.17-5a6008e0

#### Expected behaviour
Continued sync.

#### Actual behaviour
SIGSEGV after block 2425548.

Upon restart, geth syncs very slowly (< 3 block/min)

#### Steps to reproduce the behaviour
Normal sync, no other interaction.

#### Backtrace
full backtrace: https://gist.github.com/celeduc/de802ecdece18612abbe32094fde7fc2

Top:
````
I1012 10:36:36.552116 core/blockchain.go:975] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 22.407825ms. #2425548 [663c7c14 / 663c7c14]
unexpected fault address 0x204979bc00
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x204979bc00 pc=0x406fafb]

goroutine 2932477 [running]:
runtime.throw(0x48ecf4b, 0x5)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:566 +0x95 fp=0xc52ec0afe0 sp=0xc52ec0afc0
runtime.sigpanic()
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc52ec0b038 sp=0xc52ec0afe0
runtime.memmove(0xc52f406086, 0x204979bc00, 0xc4)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/memmove_amd64.s:204 +0x21b fp=0xc52ec0b040 sp=0xc52ec0b038
github.com/ethereum/go-ethereum/rlp.(*encbuf).encodeString(0xc5153b01e0, 0x204979bc00, 0xc4, 0xc4)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:208 +0x159 fp=0xc52ec0b0b0 sp=0xc52ec0b040
github.com/ethereum/go-ethereum/rlp.writeBytes(0x482a200, 0xc4a78fad60, 0x97, 0xc5153b01e0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:443 +0x6b fp=0xc52ec0b0f0 sp=0xc52ec0b0b0
github.com/ethereum/go-ethereum/rlp.writeInterface(0x481bf00, 0xc4a35b3c60, 0x94, 0xc5153b01e0, 0x481bf00, 0xc4a35b3c60)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:506 +0x1e7 fp=0xc52ec0b160 sp=0xc52ec0b0f0
github.com/ethereum/go-ethereum/rlp.makeSliceWriter.func1(0x47d0320, 0xc4a35b3c20, 0x91, 0xc5153b01e0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:520 +0xe6 fp=0xc52ec0b1c0 sp=0xc52ec0b160
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc5153b01e0, 0x47d0320, 0xc4a35b3c20, 0x47d0320, 0xc4a35b3c20)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:188 +0xdc fp=0xc52ec0b218 sp=0xc52ec0b1c0
github.com/ethereum/go-ethereum/rlp.Encode(0x4e53100, 0xc5153b01e0, 0x47d0320, 0xc4a35b3c20, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:84 +0x79 fp=0xc52ec0b258 sp=0xc52ec0b218
github.com/ethereum/go-ethereum/trie.fullNode.EncodeRLP(0x4e5a200, 0xc4a78fac00, 0x4e5a200, 0xc4a78faca0, 0x4e5a200, 0xc4a78fad00, 0x4e5a200, 0xc4a78fad20, 0x4e5a200, 0xc4a78fad60, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/node.go:53 +0x76 fp=0xc52ec0b298 sp=0xc52ec0b258
github.com/ethereum/go-ethereum/trie.(*fullNode).EncodeRLP(0xc473745680, 0x4e53100, 0xc5153b01e0, 0xc52ec0b420, 0xc473745680)
	<autogenerated>:7 +0x9d fp=0xc52ec0b3f8 sp=0xc52ec0b298
github.com/ethereum/go-ethereum/rlp.writeEncoder(0x4890100, 0xc473745680, 0x99, 0xc5153b01e0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:474 +0xad fp=0xc52ec0b440 sp=0xc52ec0b3f8
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc5153b01e0, 0x4890100, 0xc473745680, 0x488f000, 0xc5153b01e0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:188 +0xdc fp=0xc52ec0b498 sp=0xc52ec0b440
github.com/ethereum/go-ethereum/rlp.Encode(0x4e52180, 0xc4e5ae3030, 0x4890100, 0xc473745680, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:89 +0x14d fp=0xc52ec0b4d8 sp=0xc52ec0b498
github.com/ethereum/go-ethereum/trie.(*hasher).store(0xc4b0481fc0, 0x4e5a1c0, 0xc473745680, 0x0, 0x0, 0x4e5a100, 0xc473745680, 0x4e5a1c0, 0xc473745cc0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:140 +0x11e fp=0xc52ec0b580 sp=0xc52ec0b4d8
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc4b0481fc0, 0x4e5a1c0, 0xc471dbc280, 0x0, 0x0, 0x0, 0x4e5a200, 0xc4a78fabe0, 0x4e5a1c0, 0xc51db9f180, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:61 +0x22c fp=0xc52ec0b988 sp=0xc52ec0b580
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc4b0481fc0, 0x4e5a1c0, 0xc471dbc640, 0x0, 0x0, 0x4e5a100, 0x4e5a200, 0xc51d79dcc0, 0x0, 0x0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:114 +0x182 fp=0xc52ec0c1f8 sp=0xc52ec0b988
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc4b0481fc0, 0x4e5a1c0, 0xc471dbc640, 0x0, 0x0, 0x4e5a100, 0x4e5a200, 0xc51d79dd20, 0x4e5a1c0, 0xc4b6a22640, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:57 +0xdd fp=0xc52ec0c600 sp=0xc52ec0c1f8
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc4b0481fc0, 0x4e5a1c0, 0xc479d7f180, 0x0, 0x0, 0x4e5a100, 0x4e5a200, 0xc51d79d1e0, 0x0, 0x0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:114 +0x182 fp=0xc52ec0ce70 sp=0xc52ec0c600
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc4b0481fc0, 0x4e5a1c0, 0xc479d7f180, 0x0, 0x0, 0xc46ed0d600, 0x4e5a200, 0xc51d79d1e0, 0x4e5a1c0, 0xc4a97588c0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:57 +0xdd fp=0xc52ec0d278 sp=0xc52ec0ce70
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc4b0481fc0, 0x4e5a1c0, 0xc4a8c45900, 0x0, 0x0, 0x4e5a100, 0x4e5a200, 0xc47984e3e0, 0x0, 0x0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:114 +0x182 fp=0xc52ec0dae8 sp=0xc52ec0d278
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc4b0481fc0, 0x4e5a1c0, 0xc4a8c45900, 0x0, 0x0, 0x0, 0x4e5a200, 0xc47984e3e0, 0x4e5a1c0, 0xc472b3cdc0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:57 +0xdd fp=0xc52ec0def0 sp=0xc52ec0dae8
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc4b0481fc0, 0x4e5a1c0, 0xc4b4cb8dc0, 0x0, 0x0, 0x4e5a1c0, 0xc469354a00, 0x4e5a1c0, 0xc484a11cc0, 0x4e5a1c0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:114 +0x182 fp=0xc52ec0e760 sp=0xc52ec0def0
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc4b0481fc0, 0x4e5a1c0, 0xc4b4cb8dc0, 0x0, 0x0, 0x1, 0x14, 0xc4a0368ea0, 0xc43fb0fa60, 0xc4c0c61220, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/hasher.go:57 +0xdd fp=0xc52ec0eb68 sp=0xc52ec0e760
github.com/ethereum/go-ethereum/trie.(*Trie).hashRoot(0xc43fb0fa20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:480 +0x104 fp=0xc52ec0ec00 sp=0xc52ec0eb68
github.com/ethereum/go-ethereum/trie.(*Trie).Hash(0xc43fb0fa20, 0x0, 0x0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:441 +0x82 fp=0xc52ec0ecc0 sp=0xc52ec0ec00
github.com/ethereum/go-ethereum/trie.(*SecureTrie).Hash(0xc43fb0fa20, 0x0, 0x0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:148 +0x55 fp=0xc52ec0ed18 sp=0xc52ec0ecc0
github.com/ethereum/go-ethereum/core/state.(*StateDB).IntermediateRoot(0xc420449c20, 0x0, 0x0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:528 +0x1c5 fp=0xc52ec0ee00 sp=0xc52ec0ed18
github.com/ethereum/go-ethereum/core.ApplyTransaction(0xc4200b65c0, 0xc4202fa5a0, 0xc49c9b2700, 0xc420449c20, 0xc4e832b200, 0xc52290fcb0, 0xc49c9b25a0, 0x0, 0x0, 0x0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:100 +0x14c fp=0xc52ec0f1b0 sp=0xc52ec0ee00
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc4205c95e0, 0xc51e839950, 0xc420449c20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:75 +0x536 fp=0xc52ec0f3f8 sp=0xc52ec0f1b0
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc4202fa5a0, 0xc43dffde38, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:910 +0x12cb fp=0xc52ec0fc80 sp=0xc52ec0f3f8
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).insertChain(0xc42043d380, 0xc43dffde38, 0x1, 0x1, 0x8, 0x47d0800, 0xc548b4fd01)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:185 +0x51 fp=0xc52ec0fce0 sp=0xc52ec0fc80
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func6(0xc43dffde38, 0x1, 0x1, 0x4f24e01, 0xc483afa630, 0xc421050e18)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:172 +0x6d fp=0xc52ec0fd30 sp=0xc52ec0fce0
github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert.func1(0xc42043d450, 0xc5557925e0, 0xc51e839950, 0xc430adf840, 0x10)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:684 +0x404 fp=0xc52ec0ff48 sp=0xc52ec0fd30
runtime.goexit()
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc52ec0ff50 sp=0xc52ec0ff48
created by github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).insert
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:696 +0x255
````

Log after restart:
````
MacBook-Pro:~ $ geth-darwin-amd64-1.4.17-5a6008e0/geth
I1013 12:17:46.221962 ethdb/database.go:83] Alloted 128MB cache and 1024 file handles to /Users/cleduc/Library/Ethereum/chaindata
I1013 12:17:49.058050 cmd/utils/flags.go:830] ------------------------------------------------------------------------------------------------
I1013 12:17:49.058086 cmd/utils/flags.go:831] Geth is currently configured to SUPPORT the DAO hard-fork!
I1013 12:17:49.058098 cmd/utils/flags.go:832] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I1013 12:17:49.058109 cmd/utils/flags.go:833] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I1013 12:17:49.058119 cmd/utils/flags.go:834] ------------------------------------------------------------------------------------------------
I1013 12:17:49.250832 ethdb/database.go:171] closed db:/Users/cleduc/Library/Ethereum/chaindata
I1013 12:17:49.264745 ethdb/database.go:83] Alloted 128MB cache and 1024 file handles to /Users/cleduc/Library/Ethereum/chaindata
I1013 12:17:49.889753 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to /Users/cleduc/Library/Ethereum/dapp
I1013 12:17:49.908479 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I1013 12:17:49.919369 eth/backend.go:201] Blockchain DB Version: 3
I1013 12:17:49.946042 core/blockchain.go:214] Last header: #2425548 [663c7c14…] TD=73460689161884576955
I1013 12:17:49.946109 core/blockchain.go:215] Last block: #2425548 [663c7c14…] TD=73460689161884576955
I1013 12:17:49.946131 core/blockchain.go:216] Fast block: #2425548 [663c7c14…] TD=73460689161884576955
I1013 12:17:49.959393 p2p/server.go:313] Starting Server
I1013 12:17:50.483866 p2p/discover/udp.go:217] Listening, enode://a87180d8ab40ff6530b7c3d19764d53cb04bb446b1fa7ad8a28b3ce4b7b30d104c8d2f722097e47a195fa6e6750fb0e620ffdc6ad35103532102566ee0ee4089@[::]:30303
I1013 12:17:50.484499 p2p/server.go:556] Listening on [::]:30303
I1013 12:17:50.488356 node/node.go:296] IPC endpoint opened: /Users/cleduc/Library/Ethereum/geth.ipc
I1013 12:18:00.488286 eth/downloader/downloader.go:319] Block synchronisation started
I1013 12:19:12.095183 core/blockchain.go:975] imported 2 block(s) (0 queued 0 ignored) including 32 txs in 1m8.169121489s. #2425550 [39fda90a / 58d5a9b2]
I1013 12:19:22.496334 eth/handler.go:291] Peer 98ec49da904166d6 [eth/63]: timed out DAO fork-check, dropping
I1013 12:19:41.657940 eth/handler.go:291] Peer e49ba92cb8f961d6 [eth/63]: timed out DAO fork-check, dropping
I1013 12:38:39.114987 eth/handler.go:291] Peer 609d44663dd7f27b [eth/63]: timed out DAO fork-check, dropping
I1013 13:05:35.741492 eth/handler.go:291] Peer e003f67792fed744 [eth/63]: timed out DAO fork-check, dropping
````

**Comment by karalabe** [comment]
This was a side effect of the attacks. Please update to Geth 1.4.18, which should fix the issue.
