### ISSUE TITLE
UDP crash

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#314]
```
2015/02/15 14:57:13 [TXP] Known transaction (28bd85bf)
2015/02/15 14:57:13 [TXP] Known transaction (de4ea2b6)
2015/02/15 14:57:13 [TXP] Known transaction (eac76bc8)
2015/02/15 14:57:13 [TXP] Known transaction (a94416db)
2015/02/15 14:58:14 [Peer ec38655e49a561b3 208.52.168.126:49424] whisper stopped
panic: runtime error: slice bounds out of range

goroutine 24 [running]:
github.com/ethereum/go-ethereum/p2p/discover.(*udp).loop(0xc2080d0b40)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/p2p/discover/udp.go:259 +0x852
created by github.com/ethereum/go-ethereum/p2p/discover.ListenUDP
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/p2p/discover/udp.go:155 +0x5a6
```

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/316

**Comment by Gustav-Simonsson** [comment]
nm, realized now the copy method should also work with the last element; could this be a concurrency issue?

**Comment by fjl** [comment]
It cannot be a concurrency issue because it updates a slice in a loca variable. I know exactly how to test and fix it, just didn't do it yet.
