### ISSUE TITLE
geth console eth.compile.solidity returns "Error: invalid character"

### ISSUE THREAD

**Issue by cdetrio** [ethereum/go-ethereum#3399]
#### System information

instance: Geth/v1.5.5-unstable-2dcf75a7/darwin/go1.6.3

#### Expected behaviour

eth.compile.solidity at the console should work.

Here is the output from Geth/v1.4.19-stable-81d9d7d3/darwin/go1.6.3:

```
> eth.compile.solidity("contract MyContract { function MyContract() { int a; } }")
{
  MyContract: {
    code: "0x606060405260068060106000396000f3606060405200",
    info: {
      abiDefinition: [{...}],
      compilerOptions: "--bin --abi --userdoc --devdoc --add-std --optimize -o /var/folders/wb/d8qys65575g8m2691vvglpmm0000gn/T/solc222423419",
      compilerVersion: "0.3.6",
      developerDoc: {
        methods: {}
      },
      language: "Solidity",
      languageVersion: "0.3.6",
      source: "contract MyContract { function MyContract() { int a; } }",
      userDoc: {
        methods: {}
      }
    }
  }
}
>
```

#### Actual behaviour

```
> eth.compile.solidity("contract MyContract { function MyContract() { int a; } }")
Error: invalid character 'C' looking for beginning of value
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

**Comment by cdetrio** [comment]
Also, geth v1.4.19 still uses solidity version v0.3.6, but the latest is [v0.4.6](https://github.com/ethereum/solidity/releases/tag/v0.4.6).

**Comment by cdetrio** [comment]
Nevermind, fixed by updating system solc.
