### ISSUE TITLE
error when invoking call() with defaultBlock set to a block number

### ISSUE THREAD

**Issue by chafey** [ethereum/go-ethereum#3688]
#### System information

Geth version: 1.5.7-stable
OS & Version: OSX
Commit hash : da2a22c384a9b621ec853fe4b1aa651d606cf42b

#### Expected behaviour

Specifying a specific block number when invoking call() on a contract's constant function should return the value that would have been returned for that contract at that block number.

#### Actual behaviour

Error: new BigNumber() not a base 16 number: 

#### Steps to reproduce the behaviour

1) Deploy contract that has a public getter (constant) and setter for a property:
```
pragma solidity ^0.4.2;

contract Test {

  string public name;

  function SetName(string _name) {
    name = _name;
  }
}
```
2) Call the setter a few times, note the block numbers
```
test.SetName('test1'); // mined to block 10
test.SetName('test2'); // mined to block 20
test.SetName('test3'); // mined to block 30
```
3) Try invoking call for the getter on each of the block numbers to see the value at that block#:
```
  test.name.call(10); // error - expect value 'test1'
  test.name.call(20); //error - expect value 'test2'
```

#### Backtrace

````
Error: new BigNumber() not a base 16 number: 
    at raise (web3.js:14632:29)
    at web3.js:14620:33
    at BigNumber (web3.js:13667:28)
    at web3.js:1110:23
    at web3.js:1634:20
    at web3.js:826:16
    at map (<native code>)
    at web3.js:825:12
    at web3.js:4004:18
````

**Comment by chafey** [comment]
Update: this error only occurs when specifying a block number prior to when the contract is instantiated.  So the issue is only related to the error handling - leaving this open so we can consider returning a more sensible error

**Comment by chafey** [comment]
Closing as this is not a bug, but the error reporting could be improved (opened a separate issue for that)
