### ISSUE TITLE
pow: ethash test mode is broken on master branch

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#3784]
#### System information

OS & Version: OSX
Commit hash :  61ede86

#### Expected behaviour

`geth --dev --mine` should work.

#### Actual behaviour

It crashes.

#### Steps to reproduce the behaviour

```go
func TestSearchInTestMode(t *testing.T) {
	block := types.NewBlockWithHeader(&types.Header{
		UncleHash:   types.EmptyUncleHash,
		Root:        types.EmptyRootHash,
		TxHash:      types.EmptyRootHash,
		ReceiptHash: types.EmptyRootHash,
		Difficulty:  big.NewInt(100),
	})
	NewTestEthash().Search(block, nil)
}
```

#### Backtrace

```text
--- FAIL: TestSearchInTestMode (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41be9e2]

goroutine 34 [running]:
testing.tRunner.func1(0xc4200180d0)
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:622 +0x29d
panic(0x4215120, 0x43709a0)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/ethereum/go-ethereum/pow.(*Ethash).dataset(0xc42008c080, 0x0, 0xc4200d6c40, 0xc42003dcd0, 0x4e1c6741c63dc403)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/pow/ethash.go:542 +0x192
github.com/ethereum/go-ethereum/pow.(*Ethash).Search(0xc42008c080, 0x4357e60, 0xc4200b0120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/pow/ethash.go:490 +0x12e
github.com/ethereum/go-ethereum/pow.TestSearchInTestMode(0xc4200180d0)
	/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/pow/ethash_algo_test.go:41 +0x13f
testing.tRunner(0xc4200180d0, 0x426d598)
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:697 +0x2ca
```

**Comment by fjl** [comment]
There might be more issues like this ([from gitter chat](https://gitter.im/ethereum/go-ethereum?at=58c9f23b05a31d5a4a609bd5)):

```text
unexpected fault address 0x7f94de82ed08
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f94de8065c8 pc=0x8d08d8]

goroutine 2925 [running]:
runtime.throw(0x116a1f6, 0x5)
    /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42b0f9660 sp=0xc42b0f9640
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc42b0f96b0 sp=0xc42b0f9660
github.com/ethereum/go-ethereum/pow.fnvHash(0xc42b0f9788, 0x10, 0x10, 0x7f94de8065c8, 0x3fe240, 0x3fe240)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/pow/ethash_algo.go:188 +0x58 fp=0xc42b0f9738 sp=0xc42b0f96b0
github.com/ethereum/go-ethereum/pow.generateDatasetItem(0x7f94de7ff008, 0x3fffb0, 0x3fffb0, 0xc40082df48, 0xc428b92180, 0x10, 0x40, 0x40)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/pow/ethash_algo.go:215 +0x2dd fp=0xc42b0f97e0 sp=0xc42b0f9738
github.com/ethereum/go-ethereum/pow.hashimotoLight.func1(0xc40082df48, 0x20, 0x20, 0xc4260fa100)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/pow/ethash_algo.go:342 +0x51 fp=0xc42b0f9848 sp=0xc42b0f97e0
github.com/ethereum/go-ethereum/pow.hashimoto(0xc42b0f9b10, 0x20, 0x20, 0x7f8e89ecc9a8282a, 0x3ffff880, 0xc426283950, 0x42a39b73d9978dd, 0xb992d1db7e4d30c0, 0xf55142688366abe0, 0x7b964561d5a1f95, ...)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/pow/ethash_algo.go:318 +0x30d fp=0xc42b0f99e0 sp=0xc42b0f9848
github.com/ethereum/go-ethereum/pow.hashimotoLight(0x3ffff880, 0x7f94de7ff008, 0x3fffb0, 0x3fffb0, 0xc42b0f9b10, 0x20, 0x20, 0x7f8e89ecc9a8282a, 0x7f95000652b0, 0x45ace0, ...)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/pow/ethash_algo.go:350 +0x131 fp=0xc42b0f9a60 sp=0xc42b0f99e0
github.com/ethereum/go-ethereum/pow.(*Ethash).Verify(0xc4201ee780, 0x19b7320, 0xc42cbaa000, 0xc42b0f9d58, 0x1)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/pow/ethash.go:408 +0x1f8 fp=0xc42b0f9bd0 sp=0xc42b0f9a60
github.com/ethereum/go-ethereum/core.ValidateHeader(0xc4201e1b00, 0x19b27a0, 0xc4201ee780, 0xc421506000, 0xc421503d40, 0x7f95001f0001, 0xc42b0f9e70, 0x931cbe)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/core/block_validator.go:247 +0x935 fp=0xc42b0f9e08 sp=0xc42b0f9bd0
github.com/ethereum/go-ethereum/core.(*BlockValidator).ValidateHeader(0xc4201108c0, 0xc421506000, 0xc421503d40, 0x62ca212b3a13cf01, 0xd787390755280b18, 0x0)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/core/block_validator.go:201 +0x10d fp=0xc42b0f9e80 sp=0xc42b0f9e08
github.com/ethereum/go-ethereum/core.(*HeaderChain).InsertHeaderChain.func1(0x4)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/core/headerchain.go:284 +0x402 fp=0xc42b0f9fa0 sp=0xc42b0f9e80
github.com/ethereum/go-ethereum/core.(*HeaderChain).InsertHeaderChain.func2(0xc42e6b7a00, 0xc420318850, 0x4)
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/core/headerchain.go:299 +0x56 fp=0xc42b0f9fc8 sp=0xc42b0f9fa0
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42b0f9fd0 sp=0xc42b0f9fc8
created by github.com/ethereum/go-ethereum/core.(*HeaderChain).InsertHeaderChain
    /home/immesys/w/go/src/github.com/ethereum/go-ethereum/core/headerchain.go:300 +0x572
```

**Comment by fjl** [comment]
I have a hunch that this is related to the unsafe casts between `[]uint32` and `[]byte`.

**Comment by immesys** [comment]
So I can make the problem go away by:
- Put a global lock around the top half of Ethash.Verify() (ending just before it calls hashimotoLight), this may not be the minimal change
- Copy the cache uint32[] array inside the critical section, and pass the copy to hashimotoLight (after the lock is released)

If I do just the first step (still pass the original cache array to hashimotoLight) I get exactly the same crash. As soon as I swap the array to the copy, it has run fine overnight.

**Comment by immesys** [comment]
FYI I am on a private chain, and it crashes on a different block each time, so I don't think its the contents of what is being verified, just some race in the verification.

**Comment by immesys** [comment]
@karalabe I am not sure this problem is solved. I just got this again on 1.6.6:

```
unexpected fault address 0x7f87eafe6d08
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f87eafe6d08 pc=0x92159f]

goroutine 3017 [running]:
runtime.throw(0x11e4127, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc429d457d0 sp=0xc429d457b0
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc429d45820 sp=0xc429d457d0
github.com/ethereum/go-ethereum/consensus/ethash.fnvHash(0xc429d45880, 0x10, 0x10, 0x7f87eafe6d08, 0x4064b0, 0x4064b0)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:183 +0x2f fp=0xc429d45830 sp=0xc429d45820
github.com/ethereum/go-ethereum/consensus/ethash.generateDatasetItem(0x7f87eafc0008, 0x40fff0, 0x40fff0, 0xc4006fb18a, 0xc423df30c0, 0x10, 0x40, 0x40)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:210 +0x2dd fp=0xc429d458d8 sp=0xc429d45830
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoLight.func1(0xc4006fb18a, 0x20, 0x20, 0xc421281280)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:336 +0x51 fp=0xc429d45940 sp=0xc429d458d8
github.com/ethereum/go-ethereum/consensus/ethash.hashimoto(0xc429d45c00, 0x20, 0x20, 0x8bd27dbedc1a4441, 0x40ffef80, 0xc423e02030, 0x9dbabc8e5d2e7bbf, 0x1b79c118f127ffe2, 0x3a8aadddeea0cc5a, 0x21575580ec58deed, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:312 +0x30d fp=0xc429d45ad8 sp=0xc429d45940
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoLight(0x40ffef80, 0x7f87eafc0008, 0x40fff0, 0x40fff0, 0xc429d45c00, 0x20, 0x20, 0x8bd27dbedc1a4441, 0xc423e02000, 0x20, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:344 +0x131 fp=0xc429d45b58 sp=0xc429d45ad8
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifySeal(0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc42137c240, 0x1, 0x5)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:456 +0x1e2 fp=0xc429d45c88 sp=0xc429d45b58
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeader(0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc42137c240, 0xc42137c000, 0x10100, 0x0, 0xc42119a980)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:271 +0x6fd fp=0xc429d45e48 sp=0xc429d45c88
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeaderWorker(0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc4248fa000, 0x780, 0x780, 0xc43027c800, 0x780, 0x780, 0x38, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:164 +0x20c fp=0xc429d45ee8 sp=0xc429d45e48
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders.func1(0xc42ecf9f80, 0xc42c388000, 0x780, 0x780, 0xc4202f6600, 0x1a62da0, 0xc4202ca900, 0xc4248fa000, 0x780, 0x780, ...)
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:115 +0xe9 fp=0xc429d45f70 sp=0xc429d45ee8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc429d45f78 sp=0xc429d45f70
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders
	/home/michael/go/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:118 +0x320
```
