### ISSUE TITLE
core/state: unreasonable logic when change state object's property

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#3791]
#### Expected behaviour

when a operation wants to change a state object's property, such like `SetBalance`, `getStateObject` function should be used to retrieve a related obj instead of using `GetOrNewStateObject` function. Since if this obj is deleted before, a new obj will be created during the `SetBalance` operation, which leave a `createObjectChange` in journal. Unfortunately a panic will occur if eth try to do `RevertToSnapshot`

#### Actual behaviour

using `getStateObject` as a replace

**Comment by holiman** [comment]
Could you provide a trace from a `panic` ?

**Comment by rjl493456442** [comment]
You can run a unittest under the core/state package named `TestSnapshotRandom` which is skip now.  use less test address via modify `Generate` function just like this 

```
addrs := make([]common.Address, 2)

```

a panic could occur, the reason is as described before.

```

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4085f16]

goroutine 6 [running]:
panic(0x4392220, 0xc4200160a0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008c180)
	/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:579 +0x25d
panic(0x4392220, 0xc4200160a0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
github.com/rjl493456442/go-ethereum/core/state.(*stateObject).setBalance(0x0, 0xc4202cc360)
	/Users/gary/gopath/src/github.com/rjl493456442/go-ethereum/core/state/state_object.go:270 +0x26
github.com/rjl493456442/go-ethereum/core/state.balanceChange.undo(0xc4202b43c0, 0xc4202cc360, 0xc4202a4870)
	/Users/gary/gopath/src/github.com/rjl493456442/go-ethereum/core/state/journal.go:106 +0x59
github.com/rjl493456442/go-ethereum/core/state.(*balanceChange).undo(0xc420326f10, 0xc4202a4870)
	<autogenerated>:9 +0x65
github.com/rjl493456442/go-ethereum/core/state.(*StateDB).RevertToSnapshot(0xc4202a4870, 0x0)
	/Users/gary/gopath/src/github.com/rjl493456442/go-ethereum/core/state/statedb.go:549 +0x10e
github.com/rjl493456442/go-ethereum/core/state.(*snapshotTest).run(0xc4202cf4a0, 0x0)
	/Users/gary/gopath/src/github.com/rjl493456442/go-ethereum/core/state/statedb_test.go:305 +0x598
reflect.Value.call(0x437ff40, 0x4429510, 0x13, 0x43f576f, 0x4, 0xc4200ecec0, 0x1, 0x1, 0x418e204, 0x81, ...)
	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x437ff40, 0x4429510, 0x13, 0xc4200ecec0, 0x1, 0x1, 0xc4200ecee0, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:302 +0xa4
testing/quick.Check(0x437ff40, 0x4429510, 0xc420028758, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/testing/quick/quick.go:283 +0x28a
github.com/rjl493456442/go-ethereum/core/state.TestSnapshotRandom(0xc42008c180)
	/Users/gary/gopath/src/github.com/rjl493456442/go-ethereum/core/state/statedb_test.go:121 +0x88
testing.tRunner(0xc42008c180, 0x44295b0)
	/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:646 +0x2ec

```

I'll create a pull request try to fix this!

**Comment by fjl** [comment]
Thanks for looking into this! The test is skipped because some of its generated permutations 'cannot happen' in practice. The skipping was introduced as a quick fix during the work on the Spurious Dragon fork.

The fix I had in mind is to ensure that no duplicate calls to Create are generated. Looking forward to your solution.

**Comment by rjl493456442** [comment]
@fjl Here is a confusion that why a obj is not marked as `deleted` but is marked as `suicided`. Since as code show, a `suicided` obj can still act as a normal account util it been flush to db
