### ISSUE TITLE
JSON logging crash

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#451]
```
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 49 [running]:
encoding/json.func·002()
	/usr/local/go/src/encoding/json/encode.go:262 +0x8b
github.com/ethereum/go-ethereum/logger.utctime8601.MarshalJSON(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/logger/types.go:11 +0x179
github.com/ethereum/go-ethereum/logger.(*utctime8601).MarshalJSON(0x4cc8a68, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:5 +0xc5
encoding/json.marshalerEncoder(0xc209160630, 0x4720d60, 0xc209638278, 0xd9, 0x0)
	/usr/local/go/src/encoding/json/encode.go:416 +0x146
encoding/json.(*structEncoder).encode(0xc209aee150, 0xc209160630, 0x47749c0, 0xc209638240, 0xd9, 0xc2080a1400)
	/usr/local/go/src/encoding/json/encode.go:584 +0x2ba
encoding/json.*structEncoder.(encoding/json.encode)·fm(0xc209160630, 0x47749c0, 0xc209638240, 0xd9, 0xc209638200)
	/usr/local/go/src/encoding/json/encode.go:598 +0x58
encoding/json.(*ptrEncoder).encode(0xc2093d5580, 0xc209160630, 0x46edd60, 0xc209638240, 0x16, 0x0)
	/usr/local/go/src/encoding/json/encode.go:706 +0xeb
encoding/json.*ptrEncoder.(encoding/json.encode)·fm(0xc209160630, 0x46edd60, 0xc209638240, 0x16, 0xc209638200)
	/usr/local/go/src/encoding/json/encode.go:711 +0x58
encoding/json.(*encodeState).reflectValue(0xc209160630, 0x46edd60, 0xc209638240, 0x16)
	/usr/local/go/src/encoding/json/encode.go:299 +0x72
encoding/json.interfaceEncoder(0xc209160630, 0x45fca80, 0xc208125090, 0x54, 0xc208125000)
	/usr/local/go/src/encoding/json/encode.go:557 +0xd9
encoding/json.(*mapEncoder).encode(0xc208156668, 0xc209160630, 0x45ff740, 0xc209686d20, 0x15, 0x0)
	/usr/local/go/src/encoding/json/encode.go:619 +0x33d
encoding/json.*mapEncoder.(encoding/json.encode)·fm(0xc209160630, 0x45ff740, 0xc209686d20, 0x15, 0xc209686d00)
	/usr/local/go/src/encoding/json/encode.go:629 +0x58
encoding/json.(*encodeState).reflectValue(0xc209160630, 0x45ff740, 0xc209686d20, 0x15)
	/usr/local/go/src/encoding/json/encode.go:299 +0x72
encoding/json.(*encodeState).marshal(0xc209160630, 0x45ff740, 0xc209686d20, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:270 +0xca
encoding/json.Marshal(0x45ff740, 0xc209686d20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:135 +0x92
github.com/ethereum/go-ethereum/logger.(*JsonLogger).LogJson(0xc2080ee870, 0x596ca18, 0xc209638240)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/logger/loggers.go:131 +0x10b
github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc208146b00, 0xc2093d43f8, 0x1, 0x1, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/core/chain_manager.go:448 +0xd5c
github.com/ethereum/go-ethereum/core.*ChainManager.InsertChain·fm(0xc2093d43f8, 0x1, 0x1, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/eth/backend.go:197 +0x57
github.com/ethereum/go-ethereum/blockpool.(*peer).getBlockHashes(0xc208ea8000)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/blockpool/peers.go:420 +0x296
github.com/ethereum/go-ethereum/blockpool.(*peer).run(0xc208ea8000)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/blockpool/peers.go:507 +0x959
github.com/ethereum/go-ethereum/blockpool.func·006()
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/blockpool/peers.go:311 +0x38
created by github.com/ethereum/go-ethereum/blockpool.(*BlockPool).switchPeer
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/blockpool/peers.go:316 +0x4db
```

**Comment by tgerring** [comment]
Added length check in 61bf29be36a6678ba16c457229ca306339ea4ebc
