### ISSUE TITLE
RPC transact: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#453]
When creating a contract via RPC on `develop` build 5890911:

```
2015/03/11 11:15:07 http: panic serving 127.0.0.1:56212: runtime error: invalid memory address or nil pointer dereference
goroutine 207 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/accounts.(*Manager).Sign(0x0, 0xc297e91720, 0x14, 0x14, 0xc297e91de0, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-xzxuBX/src/github.com/ethereum/go-ethereum/accounts/account_manager.go:109 +0x1da
github.com/ethereum/go-ethereum/xeth.(*XEth).sign(0xc222f826e0, 0xc297e5f0e0, 0xc297e91720, 0x14, 0x14, 0xe00, 0x0, 0x0)
	/private/tmp/ethereum-xzxuBX/src/github.com/ethereum/go-ethereum/xeth/xeth.go:354 +0xf8
github.com/ethereum/go-ethereum/xeth.(*XEth).Transact(0xc222f826e0, 0xc297e7b2f0, 0x28, 0x0, 0x0, 0xc297e91640, 0x13, 0xc297e7ec78, 0x6, 0xc297e7ec80, ...)
	/private/tmp/ethereum-xzxuBX/src/github.com/ethereum/go-ethereum/xeth/xeth.go:334 +0x67c
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).Transact(0xc208264140, 0xc297e93110, 0xc297e7eb90, 0x0, 0x0)
	/private/tmp/ethereum-xzxuBX/src/github.com/ethereum/go-ethereum/rpc/api.go:264 +0x257
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc208264140, 0xc22485d180, 0xc297e7eb90, 0x0, 0x0)
	/private/tmp/ethereum-xzxuBX/src/github.com/ethereum/go-ethereum/rpc/api.go:560 +0x1cee
github.com/ethereum/go-ethereum/rpc.func·004(0x72b81b8, 0xc2248517c0, 0xc296e46ea0)
	/private/tmp/ethereum-xzxuBX/src/github.com/ethereum/go-ethereum/rpc/http.go:41 +0x519
net/http.HandlerFunc.ServeHTTP(0xc20858e3c0, 0x72b81b8, 0xc2248517c0, 0xc296e46ea0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2080d0840, 0x72b81b8, 0xc2248517c0, 0xc296e46ea0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc224851720)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
```

Ethereum started with:
```
ethereum account new
<password prompt>
ethereum -mine -rpc=true -rpcport=8080
```

**Comment by fjl** [comment]
This seems to be caused by using a `nil` account manager.

**Comment by maran** [comment]
@jorisbontje Which parameters are you using in your RPC request?

**Comment by jorisbontje** [comment]
@maran:
```
{'params': [{'gas': '998657', 'code': '0x33600055610e1880610012600039610e2a566000610c9f537c0100000000000000000000000000000000000000000000000000000000600035046326638a3881141561010a5760043560405260016040511415156100515760036040511415610054565b60005b156100655760056040511415610068565b60005b1561007857600060605260206060f35b604051670de0b6b3a7640000340514151561009857600060805260206080f35b60016001540160a05233600660a051026004015543600660a0510260050155604051600660a05102600601556001600660a051026009015560a0513374060000000000000000000000000000000000000004015560016001540160015560405160025401600255600160c052602060c0f35b6306675a518114156102ef5760043560e0526001600660e051026009015414151561013c57605a610100526020610100f35b33600660e051026004015414151561015b57605b610120526020610120f35b600660e051026005015461014052610140514313151561018257605c610160526020610160f35b60ff610140510143131561019d57605d610180526020610180f35b606060805990590160009052600381526101405140602082015260e051604082015264736c6574686060820152602081019050206101a05260006101a05114156101ee57605e6101e05260206101e0f35b6101a051600660e05102600801556180006101a0510661020052600660e05102600601546102205260005990590160009052601c60845990590160009052016396af264c601c820352610200516004820152610220516024820152604481016020610280604484600030602d5a03f150610280519050905090506102405261024051600660e05102600701556002600660e051026009015560006102405113156102ba5761024051600354016003556000600060006000670de0b6b3a7640000610240510233611388f1505b604059905901600090526001815260e051602082015260208101905033602082035160200282a15060016102e05260206102e0f35b6393a138008114156103ea5760043560e0526006602060e0599059016000905260068152600660e05102600401546020820152600660e05102600501546040820152600660e05102600601546060820152600660e05102600701546080820152600660e051026008015460a0820152600660e051026009015460c0820152602081019050035260e0602060e0599059016000905260068152600660e05102600401546020820152600660e05102600501546040820152600660e05102600601546060820152600660e05102600701546080820152600660e051026008015460a0820152600660e051026009015460c082015260208101905003f35b63489e185c81141561041a5733740600000000000000000000000000000000000000040154610340526020610340f35b6361837e4181141561048b57600360206080599059016000905260038152600154602082015260025460408201526003546060820152602081019050035260806020608059905901600090526003815260015460208201526002546040820152600354606082015260208101905003f35b636b734d17811415610ae7576004356103a0526024356103c0526044356103e0526a320a0f1419080604fa4b64610400526103c0516103a05114156104d8576103e0516103c051146104db565b60005b156104f7576104005160156103a051011a610420526020610420f35b60016103a05114801561050a5780610512565b60026103a051145b905080156105205780610528565b60036103a051145b9050156105675760016103c051148015610542578061054a565b60026103c051145b905080156105585780610560565b60036103c051145b905061056a565b60005b156105a75760016103e051148015610582578061058a565b60026103e051145b9050801561059857806105a0565b60036103e051145b90506105aa565b60005b156105bc576006610500526020610500f35b60056103a0511480156105cf57806105d7565b60066103a051145b905080156105e557806105ed565b60076103a051145b90501561062c5760056103c051148015610607578061060f565b60066103c051145b9050801561061d5780610625565b60076103c051145b905061062f565b60005b1561066c5760056103e051148015610647578061064f565b60066103e051145b9050801561065d5780610665565b60076103e051145b905061066f565b60005b156106815760026105e05260206105e0f35b60096103a05114156107bd576103e0516103c05114156106b2576104005160156103c051011a610600526020610600f35b60016103c0511480156106c557806106cd565b60026103c051145b905080156106db57806106e3565b60036103c051145b9050156107225760016103e0511480156106fd5780610705565b60026103e051145b90508015610713578061071b565b60036103e051145b9050610725565b60005b156107375760066106a05260206106a0f35b60056103c05114801561074a5780610752565b60066103c051145b905080156107605780610768565b60076103c051145b9050156107a75760056103e051148015610782578061078a565b60066103e051145b9050801561079857806107a0565b60076103e051145b90506107aa565b60005b156107bc576002610740526020610740f35b5b60096103c05114156108f9576103e0516103a05114156107ee576104005160156103a051011a610760526020610760f35b60016103a0511480156108015780610809565b60026103a051145b90508015610817578061081f565b60036103a051145b90501561085e5760016103e0511480156108395780610841565b60026103e051145b9050801561084f5780610857565b60036103e051145b9050610861565b60005b15610873576006610800526020610800f35b60056103a051148015610886578061088e565b60066103a051145b9050801561089c57806108a4565b60076103a051145b9050156108e35760056103e0511480156108be57806108c6565b60066103e051145b905080156108d457806108dc565b60076103e051145b90506108e6565b60005b156108f85760026108a05260206108a0f35b5b60096103e0511415610a35576103c0516103a051141561092a576104005160156103a051011a6108c05260206108c0f35b60016103a05114801561093d5780610945565b60026103a051145b90508015610953578061095b565b60036103a051145b90501561099a5760016103c051148015610975578061097d565b60026103c051145b9050801561098b5780610993565b60036103c051145b905061099d565b60005b156109af576006610960526020610960f35b60056103a0511480156109c257806109ca565b60066103a051145b905080156109d857806109e0565b60076103a051145b905015610a1f5760056103c0511480156109fa5780610a02565b60066103c051145b90508015610a105780610a18565b60076103c051145b9050610a22565b60005b15610a34576002610a00526020610a00f35b5b60096103c0511415610a4d5760096103e05114610a50565b60005b15610a6c576104005160156103a051011a610a20526020610a20f35b60096103a0511415610a845760096103e05114610a87565b60005b15610aa3576104005160156103c051011a610a40526020610a40f35b60096103a0511415610abb5760096103c05114610abe565b60005b15610ada576104005160156103e051011a610a60526020610a60f35b6000610a80526020610a80f35b632db2eee3811415610b6957600435610200526080599059016000905260038152602081019050610aa0526000610ae0525b6003610ae0511215610b545760206102005106610ae051602002610aa051015260206102005104610200526001610ae05101610ae052610b19565b60036020610aa051035260806020610aa05103f35b6396af264c811415610dfc5760043561020052602435610220526080599059016000905260038152602081019050610b00526080599059016000905260038152602081019050610b40526080599059016000905260038152602081019050610b805260005990590160009052601c6064599059016000905201632db2eee3601c820352610200516004820152602481016080599059016000905260038152602081019050608081602485600030602d5a03f150602081019050905090509050610aa0526000610ae0525b6003610ae0511215610d09577f0201070102070607030a0106010703040302040500060a0506050803000905046020610ae051610aa0515101061a610ae051602002610b005101527f06000a0306070902050203010502010a040508040706000107060301050907046020610ae0516020610aa051015101061a610ae051602002610b405101527f010402070506040a0705020006040a01070603000507020309030506010801036020610ae0516040610aa051015101061a610ae051602002610b805101526001610ae05101610ae052610c33565b6000610c00526000610c20526d0101010000000202020001020201610c40525b61022051610c20511215610ded5760005990590160009052601c60a4599059016000905201636b734d17601c820352610c40516012610c2051600302011a602002610b005101516004820152610c405160126001610c205160030201011a602002610b405101516024820152610c405160126002610c205160030201011a602002610b805101516044820152606481016020610c60606484600030602d5a03f150610c6051905090509050610c005101610c00526001610c205101610c2052610d29565b610c0051610c80526020610c80f35b63c96cd46f811415610e1657600054331415610e155733ff5b5b505b6000f3', 'from': '5bb70f8a60ee7fb4e056bddc1483aec5244110c0', 'value': '1000000000000000000', 'gasPrice': '10000000000000'}], 'jsonrpc': '2.0', 'id': '7fe86eb1-0224-4bf5-9072-f11edc6edf7a', 'method': 'eth_transact'}
```

**Comment by maran** [comment]
Ah I ran into something similar but I was omitting the from, (used to be defaulted). I guess this is something else the. I'm switching to `rpcfrontier` branch now, it might work there.

**Comment by obscuren** [comment]
I don't think will happen anymore because of validations. Could you check and confirm using current `develop`? I just merged `rpcfrontier` to `develop`.

**Comment by tgerring** [comment]
Note that the RPC updates include new method names. eth_transact has been renamed to [eth_sendTransaction](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction) and all arguments should be supplied as hexstrings instead of numbers.

**Comment by jorisbontje** [comment]
This isn't happening anymore after recent changes.
