### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#479]
running `develop` commit b927c29
```
$ ethereum -mine=true -rpc=true -rpcport=8080 --unlock=7807b6c3c5f84043257463f7193d0671f9fb86af:bla -minerthreads=1
Welcome to the FRONTIER
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40f0f3a]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/core/types/block.go:239 +0x3a
github.com/ethereum/go-ethereum/core.(*ChainManager).setLastBlock(0xc208161340)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/core/chain_manager.go:173 +0x112
github.com/ethereum/go-ethereum/core.NewChainManager(0x4e7f2b8, 0xc2080c2f90, 0x4e7f2b8, 0xc20811c520, 0xc208069410, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/core/chain_manager.go:99 +0x175
github.com/ethereum/go-ethereum/eth.New(0xc2080fa000, 0x4ca6b40, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/eth/backend.go:172 +0xc16
github.com/ethereum/go-ethereum/cmd/utils.GetEthereum(0x482b6f0, 0xb, 0x47fad70, 0x5, 0xc2080e2000, 0x18, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:211 +0x503
main.run(0xc2080e2000)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/cmd/ethereum/main.go:159 +0x9a
github.com/codegangsta/cli.(*App).Run(0xc208098000, 0xc20800a000, 0x6, 0x6, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:180 +0x1006
main.main()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/cmd/ethereum/main.go:150 +0x80

goroutine 5 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/logger/sys.go:41 +0x6d0
created by github.com/ethereum/go-ethereum/logger.init·1
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/logger/sys.go:20 +0x25

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/cmd/utils.func·001()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:51 +0x116
created by github.com/ethereum/go-ethereum/cmd/utils.HandleInterrupt
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:55 +0xb5

goroutine 8 [chan receive]:
github.com/ethereum/go-ethereum/p2p/nat.func·004(0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:142 +0x175
github.com/ethereum/go-ethereum/p2p/nat.func·005()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:185 +0x2f
created by github.com/ethereum/go-ethereum/p2p/nat.startautodisc
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:185 +0x19c

goroutine 18 [chan receive]:
github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP(0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:111 +0x109
github.com/ethereum/go-ethereum/p2p/nat.func·002()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:139 +0x28
created by github.com/ethereum/go-ethereum/p2p/nat.func·004
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:139 +0xcb

goroutine 19 [select]:
github.com/ethereum/go-ethereum/p2p/nat.discoverPMP(0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natpmp.go:70 +0x39d
github.com/ethereum/go-ethereum/p2p/nat.func·003()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:140 +0x28
created by github.com/ethereum/go-ethereum/p2p/nat.func·004
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:140 +0x121

goroutine 20 [IO wait]:
net.(*pollDesc).Wait(0xc208180060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208180060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208180000, 0xc208e8a000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x4e6f1b0, 0xc208112018)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc2080fc008, 0xc208e8a000, 0x800, 0x800, 0x40b40e0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc2080fc008, 0xc208e8a000, 0x800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:82 +0x12e
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc20801e100, 0xc20818a000, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0xba4
github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc20801e100, 0x4903150, 0x31, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x654
github.com/huin/goupnp.DiscoverDevices(0x4903150, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:55 +0x129
github.com/ethereum/go-ethereum/p2p/nat.discover(0xc208110060, 0x4903150, 0x31, 0x4a79aa0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:119 +0x40
created by github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:97 +0x84

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0xc208010140, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010140, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2080100e0, 0xc208e88000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x4e6f1b0, 0xc20811c068)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc208128008, 0xc208e88000, 0x800, 0x800, 0x40b40e0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc208128008, 0xc208e88000, 0x800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:82 +0x12e
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc208184000, 0xc20818c000, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0xba4
github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc208184000, 0x49031b0, 0x31, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x654
github.com/huin/goupnp.DiscoverDevices(0x49031b0, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:55 +0x129
github.com/ethereum/go-ethereum/p2p/nat.discover(0xc208110060, 0x49031b0, 0x31, 0x4a79aa8)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:119 +0x40
created by github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:109 +0xbd

goroutine 82 [chan receive]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x4e6faf0, 0xc2080c33c0, 0xc208111560, 0xc20801ea00)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/logger/sys.go:77 +0x67
created by github.com/ethereum/go-ethereum/logger.func·001
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/logger/sys.go:37 +0x176

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc2080b80d0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080b80d0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2080b8070, 0xc20802b120, 0xc, 0xc, 0x0, 0x0, 0x0, 0x4e6f1b0, 0xc20802b140)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc208162018, 0xc20802b120, 0xc, 0xc, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:67 +0x124
github.com/jackpal/go-nat-pmp.(*Client).rpc(0xc20814c340, 0xc20813dede, 0x2, 0x2, 0xc, 0xc20802b120, 0xc, 0xc, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/jackpal/go-nat-pmp/natpmp.go:126 +0x37a
github.com/jackpal/go-nat-pmp.(*Client).GetExternalAddress(0xc20814c340, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/jackpal/go-nat-pmp/natpmp.go:50 +0xc8
github.com/ethereum/go-ethereum/p2p/nat.func·006()
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natpmp.go:57 +0xa5
created by github.com/ethereum/go-ethereum/p2p/nat.discoverPMP
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/p2p/nat/natpmp.go:62 +0x1a1

goroutine 9 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc208033680)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:111 +0x284
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:116 +0x7dd

goroutine 10 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc208033680)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:666 +0x877
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:119 +0x821

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc208033680)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:615 +0x21a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:120 +0x83b

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc208033680)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x855

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc208032480)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:111 +0x284
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:116 +0x7dd

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc208032480)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:666 +0x877
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:119 +0x821

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc208032480)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:615 +0x21a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:120 +0x83b

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc208032480)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x855

goroutine 66 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080338c0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:111 +0x284
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:116 +0x7dd

goroutine 67 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2080338c0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:666 +0x877
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:119 +0x821

goroutine 68 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080338c0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:615 +0x21a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:120 +0x83b

goroutine 69 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080338c0)
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/private/tmp/ethereum-qUUnVd/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x855
```

**Comment by obscuren** [comment]
> Pushed develop. Please rm -rf ~/Library/Ethereum

:-)
