### ISSUE TITLE
Unable to open on Ubuntu 14.10

### ISSUE THREAD

**Issue by TYDIRocks** [ethereum/go-ethereum#483]
When I try to run mist in my terminal, this error comes up:

```
tyler@tyler-HP-ProBook:~$ mist
rlp: input list has too many elements for types.Header, decoding into (types.Block)(struct { Header *types.Header; Txs []*types.Transaction; Uncles []*types.Header; TD *big.Int }).Header
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x54887e]

goroutine 1 [running]:
runtime.panic(0xadb7c0, 0x15b3728)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0xc2115dd094, 0x20, 0x40)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/types/block.go:235 +0x1e
github.com/ethereum/go-ethereum/core.(*ChainManager).setLastBlock(0xc2115be420)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/chain_manager.go:173 +0xf9
github.com/ethereum/go-ethereum/core.NewChainManager(0x7fb89b6293f8, 0xc2100d3a80, 0x7fb89b6293f8, 0xc2100d3a00, 0xc21010ddb0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/chain_manager.go:99 +0xd6
github.com/ethereum/go-ethereum/eth.New(0xc210093210, 0xc210093210, 0x9, 0x0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/backend.go:172 +0x943
github.com/ethereum/go-ethereum/cmd/utils.GetEthereum(0xb9db60, 0x4, 0xb97e40, 0x5, 0xc2100673c0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:211 +0x3d2
main.run(0xc2100673c0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:98 +0xc1
github.com/codegangsta/cli.(*App).Run(0xc2100b4000, 0xc21000a000, 0x1, 0x1, 0x0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:180 +0xbd7
main.main()
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:82 +0x19e

goroutine 3 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 4 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:41 +0x512
created by github.com/ethereum/go-ethereum/logger.init·1
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:20 +0x21

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/cmd/utils.func·001()
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:51 +0xd0
created by github.com/ethereum/go-ethereum/cmd/utils.HandleInterrupt
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:55 +0x7f

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/p2p/nat.func·004(0x0, 0x0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:142 +0xe2
github.com/ethereum/go-ethereum/p2p/nat.func·005()
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:185 +0x2e
created by github.com/ethereum/go-ethereum/p2p/nat.startautodisc
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:185 +0xf6

goroutine 8 [chan receive]:
github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP(0x0, 0x0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:111 +0xd6
github.com/ethereum/go-ethereum/p2p/nat.func·002()
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:139 +0x27
created by github.com/ethereum/go-ethereum/p2p/nat.func·004
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:139 +0x7f

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7fb89b621b18, 0x72, 0x0)
	/usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2100aa0d0, 0x72, 0x7fb89b6202e0, 0xb)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2100aa0d0, 0xb, 0x7fb89b6202e0)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).ReadFrom(0xc2100aa070, 0xc21014d000, 0x800, 0x800, 0x0, ...)
	/usr/lib/go/src/pkg/net/fd_unix.go:231 +0x320
net.(*UDPConn).ReadFromUDP(0xc2100f3018, 0xc21014d000, 0x800, 0x800, 0x9cb340, ...)
	/usr/lib/go/src/pkg/net/udpsock_posix.go:67 +0x122
net.(*UDPConn).ReadFrom(0xc2100f3018, 0xc21014d000, 0x800, 0x800, 0x800, ...)
	/usr/lib/go/src/pkg/net/udpsock_posix.go:82 +0xf0
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc210048300, 0xc2100370d0, 0x7d2b7500, 0x3, 0x0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0x96e
github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc210048300, 0xc90bd0, 0x31, 0x2, 0x3, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x50d
github.com/huin/goupnp.DiscoverDevices(0xc90bd0, 0x31, 0x0, 0x0, 0x0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:55 +0x116
github.com/ethereum/go-ethereum/p2p/nat.discover(0xc21005c000, 0xc90bd0, 0x31, 0xcd3eb8)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:119 +0x3f
created by github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:97 +0x6a

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7fb89b621bc0, 0x72, 0x0)
	/usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2100a3060, 0x72, 0x7fb89b6202e0, 0xb)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2100a3060, 0xb, 0x7fb89b6202e0)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).ReadFrom(0xc2100a3000, 0xc21014e000, 0x800, 0x800, 0x0, ...)
	/usr/lib/go/src/pkg/net/fd_unix.go:231 +0x320
net.(*UDPConn).ReadFromUDP(0xc2100a6020, 0xc21014e000, 0x800, 0x800, 0x9cb340, ...)
	/usr/lib/go/src/pkg/net/udpsock_posix.go:67 +0x122
net.(*UDPConn).ReadFrom(0xc2100a6020, 0xc21014e000, 0x800, 0x800, 0x800, ...)
	/usr/lib/go/src/pkg/net/udpsock_posix.go:82 +0xf0
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc210096020, 0xc2100740d0, 0x7d2b7500, 0x3, 0x0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0x96e
github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc210096020, 0xc90c30, 0x31, 0x2, 0x3, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x50d
github.com/huin/goupnp.DiscoverDevices(0xc90c30, 0x31, 0x0, 0x0, 0x0, ...)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:55 +0x116
github.com/ethereum/go-ethereum/p2p/nat.discover(0xc21005c000, 0xc90c30, 0x31, 0xcd3ec0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:119 +0x3f
created by github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:109 +0x9f

goroutine 12 [chan receive]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x7fb89b620aa0, 0xc2100d32f0, 0xc2100df000, 0xc210048920)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:77 +0x3d
created by github.com/ethereum/go-ethereum/logger.func·001
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:37 +0x12d

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2100976c0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:111 +0x1c5
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:116 +0x465

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2100976c0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:666 +0x6d7
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:119 +0x4a6

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2100976c0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:615 +0x199
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:120 +0x4bd

goroutine 17 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2100976c0)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x13d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x4d4

goroutine 18 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc210097d80)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:111 +0x1c5
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:116 +0x465

goroutine 19 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc210097d80)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:666 +0x6d7
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:119 +0x4a6

goroutine 20 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc210097d80)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:615 +0x199
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:120 +0x4bd

goroutine 21 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc210097d80)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x13d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x4d4

goroutine 22 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc210097240)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:111 +0x1c5
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:116 +0x465

goroutine 23 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc210097240)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:666 +0x6d7
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:119 +0x4a6

goroutine 24 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc210097240)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:615 +0x199
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:120 +0x4bd

goroutine 25 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc210097240)
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x13d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.0+209SNAPSHOT20150314154347utopic/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:121 +0x4d4
```

**Comment by noflag** [comment]
same

**Comment by kobigurk** [comment]
I think what solved it for me was starting over - try renaming ~/.ethereum to something else

**Comment by fjl** [comment]
We have made several incompatible changes on the develop branch that will produce crashes like this if the database is not deleted.

Resetting the database is the official "fix" for this issue.�

**Comment by obscuren** [comment]
There was a change in the block chain database which causes this issue. There's no "proper" way to resolve this other than remove the block chain database.
