### ISSUE TITLE
How can I run the VMTests with go-ethereum?

### ISSUE THREAD

**Issue by nejucomo** [ethereum/go-ethereum#539]
**Summary:** I'm not sure which tool in this repository verifies compliance with the [VMTest interoperability tests](https://github.com/ethereum/tests/tree/develop/VMTests). Ideally this would be in an obvious documentation either in this repository or the interop repo, or both.

I want to use the [interoperability tests](https://github.com/ethereum/tests) to verify the behavior of arbitrary contracts. In particular I'd like to use the [VMTests](https://github.com/ethereum/tests/tree/develop/VMTests) schema since it seems most specific to individual contract message executions.

How can I run these tests? I've tried using [``ethtest``](https://github.com/ethereum/go-ethereum/tree/develop/cmd/ethtest) as the following transcript shows, but either it is the wrong tool or I'm using the wrong revision or other config.  (Note that I *can* use ``ethtest`` successfully on the [StateTests](https://github.com/ethereum/tests/tree/develop/StateTests).)

Here's my attempt to use ``ethtest`` on the ``VMTests``:

```bash
$ export PS1='\n\$ '

$ cd $GOPATH/src/github.com/ethereum/go-ethereum/cmd/ethtest/

$ git rev-parse --abbrev-ref HEAD ; git rev-parse HEAD
develop
e861bbe0c148389b381d31f9c877b75f39aa62ef

$ go install

$ cd $REPOS/github.com/ethereum/tests/VMTests/

$ ethtest < ./vmArithmeticTest.json
2015/03/20 11:11:04 [STATE] (+) 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x525efd]

goroutine 16 [running]:
runtime.panic(0x7b5c40, 0xc2f693)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/ethereum/go-ethereum/crypto.(*KeyPair).Address(0x0, 0x0, 0x0, 0x0)
        /home/n/go/src/github.com/ethereum/go-ethereum/crypto/keypair.go:35 +0x4d
github.com/ethereum/go-ethereum/tests/helper.RunState(0xc208167340, 0xc20822a090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /home/n/go/src/github.com/ethereum/go-ethereum/tests/helper/vm.go:174 +0x5bb
main.RunVmTest(0x7f33a2957520, 0xc208042000, 0x0)
        /home/n/go/src/github.com/ethereum/go-ethereum/cmd/ethtest/main.go:133 +0x7e6
main.main()
        /home/n/go/src/github.com/ethereum/go-ethereum/cmd/ethtest/main.go:208 +0x156

goroutine 19 [finalizer wait]:
runtime.park(0x42a690, 0xcdfda8, 0xc32409)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xcdfda8, 0xc32409)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
        /home/n/go/src/github.com/ethereum/go-ethereum/logger/sys.go:41 +0x634
created by github.com/ethereum/go-ethereum/logger.init·1
        /home/n/go/src/github.com/ethereum/go-ethereum/logger/sys.go:20 +0x22

goroutine 17 [syscall]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 21 [chan receive]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x7f33a2957f60, 0xc20809a520, 0xc20822e000, 0xc20803e020)
        /home/n/go/src/github.com/ethereum/go-ethereum/logger/sys.go:77 +0x54
created by github.com/ethereum/go-ethereum/logger.func·001
        /home/n/go/src/github.com/ethereum/go-ethereum/logger/sys.go:37 +0x12c
```

Here's how I *can* use ``ethtest`` on a ``StateTest`` successfully:

```bash
$ cd ../StateTests/

$ ethtest < stExample.json
2015/03/20 11:12:58 [STATE] (+) 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba
2015/03/20 11:12:58 [STATE] 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba: gas (+ 1000000)
2015/03/20 11:12:58 [STATE] a94f5374fce5edbc8e2a8697c15331677e6ebf0b: #0 999999999999600000 (- 400000)
2015/03/20 11:12:58 [STATE] a94f5374fce5edbc8e2a8697c15331677e6ebf0b: #1 999999999999500000 (- 100000)
2015/03/20 11:12:58 [STATE] 095e7baea6a6c7c4c2dfeb977efac326af552d87: #0 1000000000000100000 (+ 100000)
2015/03/20 11:12:58 [VM] (1) (a94f5374) 095e7baea6a6c7c4c2dfeb977efac326af552d87 (code=8) gas: 379000 (d)
2015/03/20 11:12:58 [VM] (pc) 0   -o- PUSH1          (m) 0    (s) 0    (g) 3   (379000) => 0x01
2015/03/20 11:12:58 [VM] (pc) 2   -o- PUSH1          (m) 0    (s) 1    (g) 3   (378997) => 0x01
2015/03/20 11:12:58 [VM] (pc) 4   -o- ADD            (m) 0    (s) 2    (g) 3   (378994) 1 + 1 = 2
2015/03/20 11:12:58 [VM] (pc) 5   -o- PUSH1          (m) 0    (s) 1    (g) 3   (378991) => 0x00
2015/03/20 11:12:58 [VM] (pc) 7   -o- SSTORE         (m) 0    (s) 2    (g) 20000 (378988) {0x : 0x02}
2015/03/20 11:12:58 [VM] (pc) 8   -o- STOP           (m) 0    (s) 0    (g) 0   (358988)
2015/03/20 11:12:58 [CHAIN] vm took 70.949us
2015/03/20 11:12:58 [STATE] a94f5374fce5edbc8e2a8697c15331677e6ebf0b: #1 999999999999858988 (+ 358988)
2015/03/20 11:12:58 [STATE] 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba: #0 41012 (+ 41012)
```

**Comment by obscuren** [comment]
* `cd tests/vm && go test`
* `cd cmd/ethtest && go install && cat myTestFile.json | ethtest`

Favour StateTests over VMTests. StateTests verify much more than simple VMTests.
