### ISSUE TITLE
RPC panic eth_getTransactionCount with pending

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#568]
Regression on develop 505f1fb

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x9dc2299a76b68b7ffa9e3ba0fd8cd7646d21d409","pending"],"id":1}' http://localhost:8080
```

Result:
```
Starting RPC on port:  8080
2015/03/25 15:29:59 http: panic serving 127.0.0.1:47820: runtime error: invalid memory address or nil pointer dereference
goroutine 59 [running]:
net/http.func·009()
	/usr/lib/go/src/pkg/net/http/server.go:1093 +0xae
runtime.panic(0x9e4660, 0x145dc08)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x106
github.com/ethereum/go-ethereum/xeth.(*XEth).AtStateNum(0xc210a0c880, 0xfffffffffffffffe, 0xc210063100)
	/home/user/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:123 +0xd3
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).xethAtStateNum(0xc210a19de0, 0xfffffffffffffffe, 0x0)
	/home/user/go/src/github.com/ethereum/go-ethereum/rpc/api.go:44 +0x3f
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc210a19de0, 0xc210a144b0, 0xc2100c7d30, 0xc210a144b0, 0x160)
	/home/user/go/src/github.com/ethereum/go-ethereum/rpc/api.go:138 +0x3d47
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc210a19de0, 0xc210a144b0, 0x600)
	/home/user/go/src/github.com/ethereum/go-ethereum/rpc/http.go:72 +0x77
github.com/ethereum/go-ethereum/rpc.func·001(0x7f9944606640, 0xc210a24320, 0xc210a0b680)
	/home/user/go/src/github.com/ethereum/go-ethereum/rpc/http.go:46 +0x3aa
net/http.HandlerFunc.ServeHTTP(0xc2100c7c50, 0x7f9944606640, 0xc210a24320, 0xc210a0b680)
	/usr/lib/go/src/pkg/net/http/server.go:1220 +0x40
net/http.serverHandler.ServeHTTP(0xc210a14410, 0x7f9944606640, 0xc210a24320, 0xc210a0b680)
	/usr/lib/go/src/pkg/net/http/server.go:1597 +0x16e
net/http.(*conn).serve(0xc210a0cf00)
	/usr/lib/go/src/pkg/net/http/server.go:1167 +0x7b7
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1644 +0x28b
```

**Comment by obscuren** [comment]
@tgerring could you look in to this? This is because of the `pending` defaultBlock

**Comment by tgerring** [comment]
Updated logic in 7e1e264. Please test and close if fixed.

**Comment by ethers** [comment]
:+1:  thanks @tgerring
