### ISSUE TITLE
Starting console and rpc from CLI it panics

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#577]
Starting with `ethereum --rpc console` will cause a panic in loading the `dapp` database

```
Starting RPC on port:  8545
panic: resource temporarily unavailable

goroutine 1 [running]:
github.com/ethereum/go-ethereum/rpc.NewEthereumApi(0xc2082ebb80, 0xc20808f940, 0x1f, 0xc208598e40)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/rpc/api.go:26 +0x10f
main.(*jsre).apiBindings(0xc208481ac0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/cmd/ethereum/js.go:94 +0x5b
main.newJSRE(0xc20818c000, 0x0, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/cmd/ethereum/js.go:74 +0x196
main.console(0xc2080f40c0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/cmd/ethereum/main.go:197 +0x1be
github.com/codegangsta/cli.Command.Run(0x4792030, 0x7, 0x0, 0x0, 0x4879eb0, 0x34, 0x49f78f0, 0xdc, 0x0, 0x0, ...)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:116 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc2080b8460, 0xc20800a000, 0x7, 0x7, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:168 +0xdce
main.main()
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/cmd/ethereum/main.go:169 +0x80
```

**Comment by tgerring** [comment]
PR #584 pushed and waiting for review/merge
