### ISSUE TITLE
Closes connection on error instead of returning proper error object

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#615]
I assume, something crashed inside the node and no reponse could be returned.

e.g. when sending:

```
{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":["0x1e0aa27e54970936aa910a71","0x6aa910a7186fdf"],"address":"0xfd9801e0aa27e54970936aa910a7186fdf5549bc","fromBlock":"0x1","toBlock":"0x2"}],"id":44}
```

**Comment by tgerring** [comment]
@frozeman What output does the node report or does it not output any? Please specify

**Comment by tgerring** [comment]
Stack trace that was omitted by submitter:

```
015/04/01 13:50:48 http: panic serving 127.0.0.1:56738: runtime error: index out of range
goroutine 1201 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/xeth.cTopics(0xc208d1e630, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:125 +0x28d
github.com/ethereum/go-ethereum/xeth.(*XEth).RegisterFilter(0xc20838e000, 0x1, 0x2, 0x0, 0x64, 0xc208a165f0, 0x1, 0x1, 0xc208d1e630, 0x2, ...)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:330 +0x1ed
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc20837e0c0, 0xc208d242d0, 0xc208a16470, 0x0, 0x0)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/rpc/api.go:279 +0x62ee
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc20837e0c0, 0xc208d242d0, 0x200)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/rpc/http.go:98 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x61bbd70, 0xc208d760a0, 0xc208d3a340)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/rpc/http.go:72 +0x496
net/http.HandlerFunc.ServeHTTP(0xc2080ea250, 0x61bbd70, 0xc208d760a0, 0xc208d3a340)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208145c80, 0x61bbd70, 0xc208d760a0, 0xc208d3a340)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208d76000)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
```
