### ISSUE TITLE
eth_getUncleCountByBlockNumber refuses connection

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#620]
sending

```
{ id: 1,
  jsonrpc: '2.0',
  method: 'eth_getUncleCountByBlockNumber',
  params: [ '0x1' ] }
```
refuses connection and outputs the following into the node console:
```js
2015/04/01 15:56:19 http: panic serving 127.0.0.1:54853: runtime error: invalid memory address or nil pointer dereference
goroutine 250 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/rpc.newHexData(0x473d900, 0x0, 0xc2083d12a0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/messages.go:61 +0x12d
github.com/ethereum/go-ethereum/rpc.NewTransactionRes(0xc208046680, 0xc2081802c0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/responses.go:98 +0x1f6
github.com/ethereum/go-ethereum/rpc.NewBlockRes(0xc208049540, 0x0, 0xc208049540)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/responses.go:61 +0xa23
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc20848a360, 0xc20843d2c0, 0xc2084e5d80, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:142 +0x5c61
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc20848a360, 0xc20843d2c0, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:98 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f2a3a0, 0xc2081b1180, 0xc208188dd0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:72 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20842ef40, 0x4f2a3a0, 0xc2081b1180, 0xc208188dd0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f2a3a0, 0xc2081b1180, 0xc208188dd0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc20848a380, 0x4f2a3a0, 0xc2081b1180, 0xc208188dd0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20822dda0, 0x4f2a3a0, 0xc2081b1180, 0xc208188dd0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081b10e0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
```

**Comment by tgerring** [comment]
Can you test this against the latest? I'm not getting a crash anymore and it may have been fixed by something else
