### ISSUE TITLE
crash when exiting from console during blockchain sync

### ISSUE THREAD

**Issue by tgerring** [ethereum/go-ethereum#672]
When the client is sync'ing with another peer and the user types `exit` on the console, geth will crash while stopping.

```
$ geth --datadir "/Users/tgerring/gethdata/1" --bootnodes "" --port "30301" console
Welcome to the FRONTIER
> eth.blockNumber
1273
> eth.blockNumber
1964
> exit
2015/04/08 08:57:13 [TXP] Stopped
2015/04/08 08:57:13 [Blockpool] Stopping...
2015/04/08 08:57:13 [Blockpool] Stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43dec0e]

goroutine 2429 [running]:
github.com/ethereum/go-ethereum/blockpool.(*peers).peerError(0x0, 0xc209a70990, 0x10, 0x0, 0x47afb30, 0x2, 0xc20d737b20, 0x1, 0x1)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/blockpool/peers.go:101 +0x20e
github.com/ethereum/go-ethereum/blockpool.func·009()
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/blockpool/section.go:139 +0x844
created by github.com/ethereum/go-ethereum/blockpool.(*section).addSectionToBlockChain
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/blockpool/section.go:194 +0x106

goroutine 1 [chan receive]:
github.com/ethereum/go-ethereum/ethdb.(*LDBDatabase).Close(0xc2080f83c0)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/ethdb/database.go:119 +0x77
github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc2080a4300)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/eth/backend.go:425 +0x2c7
main.console(0xc2080f00e0)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:284 +0x1df
github.com/codegangsta/cli.Command.Run(0x47c0cd0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x48adaf0, 0x30, 0x4a2e4f0, ...)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208100000, 0xc20800a000, 0x8, 0x8, 0x0, 0x0)
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
	/Users/tgerring/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:254 +0xb6
```

**Comment by zelig** [comment]
added to #563

**Comment by zelig** [comment]
new downloader makes this obsolete
