### ISSUE TITLE
Geth crashes in case an invalid logfile is given

### ISSUE THREAD

**Issue by bas-vk** [ethereum/go-ethereum#679]
When geth is started with an logfile argument that points to a non-existing path geth crashes.

```
> ./geth --logfile /tmp/nhonafsd/geth.log console
Welcome to the FRONTIER
panic: error opening log file '/tmp/nhonafsd/geth.log': open /tmp/nhonafsd/geth.log: no such file or directory

goroutine 1 [running]:
github.com/ethereum/go-ethereum/logger.openLogFile(0xc2080f2a20, 0x13, 0xc2080f2a40, 0x16, 0x2)
	/home/bas/Development/golang/src/github.com/ethereum/go-ethereum/logger/log.go:16 +0x22f
github.com/ethereum/go-ethereum/logger.New(0xc2080f2a20, 0x13, 0xc2080f2a40, 0x16, 0x3, 0x0, 0x0)
	/home/bas/Development/golang/src/github.com/ethereum/go-ethereum/logger/log.go:26 +0x1c4
github.com/ethereum/go-ethereum/eth.New(0xc2080352b0, 0x4, 0x0, 0x0)
	/home/bas/Development/golang/src/github.com/ethereum/go-ethereum/eth/backend.go:153 +0x91
main.console(0xc20806ac40)
	/home/bas/Development/golang/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:274 +0x6d
github.com/codegangsta/cli.Command.Run(0xbbedb0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcab390, 0x30, 0xe2bb30, ...)
	/home/bas/Development/golang/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc2080fe000, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
	/home/bas/Development/golang/src/github.com/codegangsta/cli/app.go:178 +0xeaa
main.main()
	/home/bas/Development/golang/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:253 +0xb6
```

**Comment by bas-vk** [comment]
The current logger will be replaced by glog.
After a brief talk with @obscuren this has no priority for now.
