### ISSUE TITLE
Eventer and RPC in deadlock but only when console is started

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#681]
on current develop, 

works:
```
./geth --datadir=/tmp/eth/60/11 -port 30300 -logfile /tmp/eth/60/11.09.log -loglevel 5 -rpc -rpccorsdomain "*" -mine 2> /tmp/eth/60/11.09.glog
```

deadlocks:
```
./geth --datadir=/tmp/eth/60/11 -port 30300 -logfile /tmp/eth/60/11.09.log -loglevel 5 -rpc -rpccorsdomain "*" -mine console 2> /tmp/eth/60/11.09.glog
```

find the trace here https://gist.github.com/zelig/2ba201b4461079b0abc4

**Comment by fjl** [comment]
Do you know which event is being delivered in this case?

**Comment by fjl** [comment]
This one also looks like a bug: 
```
goroutine 37 [chan send (nil chan), 9 minutes]:
github.com/ethereum/go-ethereum/miner.(*worker).push(0xc20c532000)
	/Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/miner/worker.go:228 +0x23e
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc20c532000)
	/Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/miner/worker.go:327 +0xa5a
github.com/ethereum/go-ethereum/miner.(*worker).update(0xc20c532000)
	/Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/miner/worker.go:162 +0x391
created by github.com/ethereum/go-ethereum/miner.newWorker
	/Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/miner/worker.go:103 +0x2cb
```

**Comment by zelig** [comment]
@fjl, yes it is ChainHeadEvent

**Comment by obscuren** [comment]
Not seen that one before. I'll have a look

**Comment by zelig** [comment]
@fjl no, unfortunately not able to reproduce. bit of a hit and miss

**Comment by zelig** [comment]
another case may be related https://gist.github.com/zelig/d83879d7f8e259c79d3b 
i was on commit https://github.com/ethereum/go-ethereum/commit/d82aaf617c8ec868446d8bd334d1e3dbc1475244
