### ISSUE TITLE
SIGABRT: abort during cgo execution

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#746]
**OS Information**

````
Linux dgxeth01 3.16.0-28-generic #37-Ubuntu SMP Mon Dec 8 17:15:28 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
````

**Git hash**
````
c39a7b5c0d2002d72df7a0517ccc6edd7557ab7d
````

**Trace**
````
I0418 07:50:45.317762   32671 agent.go:80] (re)started agent[10]. mining...
I0418 07:50:45.317797   32671 agent.go:80] (re)started agent[1]. mining...
I0418 07:50:45.319705   32671 state_object.go:238] 07ec469375e0b6c22a58cba7cfcb0ddd9aeb7184: gas (+ 3141592)
I0418 07:50:45.320034   32671 state_object.go:194] 07ec469375e0b6c22a58cba7cfcb0ddd9aeb7184: #0 1713325800000000000000 (+ 1500000000000000000)
SIGABRT: abort
PC=0x7f779537ce37
signal arrived during cgo execution

goroutine 6358 [syscall, locked to thread]:
runtime.cgocall_errno(0x404660, 0xc2cd4fbb30, 0x0)
  /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2cd4fbb10 sp=0xc2cd4fbae8
github.com/ethereum/ethash._Cfunc_free(0xc25c010008)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/:62 +0x45 fp=0xc2cd4fbb30 sp=0xc2cd4fbb10
github.com/ethereum/ethash.(*Ethash).UpdateDAG(0xc20ba6c500)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:179 +0x2c0 fp=0xc2cd4fbd48 sp=0xc2cd4fbb30
github.com/ethereum/ethash.(*Ethash).Search(0xc20ba6c500, 0x7f7790196660, 0xc2b0437a40, 0xc2a4a2f560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:310 +0x8a fp=0xc2cd4fbec0 sp=0xc2cd4fbd48
github.com/ethereum/go-ethereum/miner.(*CpuMiner).mine(0xc20b0e9440, 0xc2b0437a40)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/miner/agent.go:88 +0x23c fp=0xc2cd4fbfd0 sp=0xc2cd4fbec0
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2cd4fbfd8 sp=0xc2cd4fbfd0
created by github.com/ethereum/go-ethereum/miner.(*CpuMiner).update
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/miner/agent.go:59 +0x133

goroutine 1I0418 07:50:45.320511   32671 chain_manager.go:533] inserted block #30229 (0 TXs 0 UNCs) (c6419175...)
 [select, 2 minutes]:
github.com/peterh/liner.(*State).readNext(0xc20b698900, 0x0, 0x0, 0x0, 0x0)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/peterh/liner/input.go:140 +0x2a1d
github.com/peterh/liner.(*State).Prompt(0xc20b698900, 0xbefcd0, 0x2, 0x0, 0x0, 0x0, 0x0)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/peterh/liner/line.go:494 +0x443
main.(*jsre).interactive(0xc20a610000)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:172 +0x72
main.console(0xc20807a2a0)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:297 +0x1d1
github.com/codegangsta/cli.Command.Run(0xc03710, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd05210, 0x30, 0xe89c90, ...)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc2080da000, 0xc20800a000, 0xc, 0xc, 0x0, 0x0)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:269 +0xc7

goroutine 6 [runnable]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/logger/sys.go:65 +0x6d1
created by github.com/ethereum/go-ethereum/logger.init·1
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/logger/sys.go:44 +0x25

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x12cef20)
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x78
created by github.com/ethereum/go-ethereum/logger/glog.init·1
  /home/appuser/projects/gocode/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x77

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [syscall, 3 minutes]:
os/signal.loop()
  /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
  /usr/local/go/src/os/signal/signal_unix.go:27 +0x35
````

Full trace

https://gist.github.com/tymat/350300eda5684f86ad67

**Comment by obscuren** [comment]
Which version is this?

**Comment by tymat** [comment]
From: 
https://github.com/ethereum/go-ethereum/commit/525cefa37aafbc42de8911344c9853d950c06ded

**Comment by obscuren** [comment]
It's likely this issue will disappear when ethash has been fully updated. Will keep this open for now.

**Comment by obscuren** [comment]
Ethash has been updated. This shouldn't happen anymore
