### ISSUE TITLE
Develop suddenly fails to import test blockchain

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#788]
Importing the test blockchain fails now. It seems to hang because the block test have `0x00` as 0 values for numbers (which i requested, before it was `0x`) see: https://github.com/ethereum/tests/blob/develop/BlockTests/bcRPC_API_Test.json#L29

It run the last days even with the new `0x00` values, now it fails:

```js
➜  geth git:(develop) ✗ ./geth --rpccorsdomain "http://localhost:3000" blocktest ~/Developer/tests/BlockTests/bcRPC_API_Test.json RPC_API_Test rpc

Welcome to the FRONTIER
Fatal: bad test "RPC_API_Test": invalid integer: "0x00"
goroutine 1 [running]:
github.com/ethereum/go-ethereum/tests.func·001()
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/tests/block_test_util.go:199 +0xb5
github.com/ethereum/go-ethereum/tests.mustConvertBigInt(0xc20816e090, 0x4, 0xa, 0x1)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/tests/block_test_util.go:286 +0x1dd
github.com/ethereum/go-ethereum/tests.mustConvertHeader(0xc208164e00, 0x200, 0xc2080f5860, 0x28, 0xc208170080, 0x40, 0xc20816e0b0, 0x10, 0xc20816e0c0, 0x4, ...)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/tests/block_test_util.go:229 +0x220
github.com/ethereum/go-ethereum/tests.mustConvertGenesis(0xc208164e00, 0x200, 0xc2080f5860, 0x28, 0xc208170080, 0x40, 0xc20816e0b0, 0x10, 0xc20816e0c0, 0x4, ...)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/tests/block_test_util.go:209 +0x41
github.com/ethereum/go-ethereum/tests.convertTest(0xc208044dc0, 0xc20801d880, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/tests/block_test_util.go:204 +0x178
github.com/ethereum/go-ethereum/tests.LoadBlockTests(0x7fff5fbffc17, 0x3e, 0x3, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/tests/block_test_util.go:91 +0x1df
main.runBlockTest(0xc2081080c0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/cmd/geth/blocktest.go:46 +0xcb
github.com/codegangsta/cli.Command.Run(0x484c650, 0x9, 0x0, 0x0, 0x489d5d0, 0x17, 0x4a9d6d0, 0x120, 0x0, 0x0, ...)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:116 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc2080da000, 0xc20800a000, 0x7, 0x7, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:175 +0xfa0
main.main()
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:274 +0xb6
```

**Comment by obscuren** [comment]
@Gustav-Simonsson tests need to be updated
@frozeman the test actually fails correctly. It requires updating.

**Comment by frozeman** [comment]
@obscuren what exactly is wrong with the tests? should `0x00` be `0x0` ?

It worked fine before with and without the new `0x00`.

On the RPC side i need those values to be at least `0x0`, otherwise is can't simply transform them using `+0x0` to numbers and i would have to rewrite all tests to find a different solution.

**Comment by Gustav-Simonsson** [comment]
This is fixed in: https://github.com/ethereum/go-ethereum/pull/779

**Comment by frozeman** [comment]
Thanks god! :bow:

**Comment by obscuren** [comment]
Merged
