### ISSUE TITLE
eth: close of closed channel on shutdown

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#869]
at 82ac4712f17d69e6fa90949357ba0d97a3d8a770. 

```
panic: close of closed channel

goroutine 9 [running]:
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).Stop(0xc208176600)
        /home/staff/fjl/develop/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:124 +0x179
github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc20816a200)
        /home/staff/fjl/develop/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:501 +0x66
github.com/ethereum/go-ethereum/cmd/utils.func·002(0x2b8dd32fc100, 0xc21f81e238)
        /home/staff/fjl/develop/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:121 +0x2a
github.com/ethereum/go-ethereum/cmd/utils.RunInterruptCallbacks(0x2b8dd32fc100, 0xc21f81e238)
        /home/staff/fjl/develop/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:61 +0x77
github.com/ethereum/go-ethereum/cmd/utils.func·001()
        /home/staff/fjl/develop/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:54 +0x241
created by github.com/ethereum/go-ethereum/cmd/utils.HandleInterrupt
        /home/staff/fjl/develop/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:56 +0xb5
```

**Comment by obscuren** [comment]
@fjl pling
