### ISSUE TITLE
Creating whisper identity error

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#881]
While running the RPC tests it stops at `shh_newIdentity` and the node crashes with the following error:

```js
2015/05/08 10:36:59 http: panic serving 127.0.0.1:51190: runtime error: invalid memory address or nil pointer dereference
goroutine 2512 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/whisper.(*Whisper).NewIdentity(0x0, 0xc20815adf8)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/whisper/whisper.go:102 +0xdd
github.com/ethereum/go-ethereum/xeth.(*Whisper).NewIdentity(0xc20802a140, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/whisper.go:30 +0x3d
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc2282f1ba0, 0xc20802d7c0, 0xc2081f5cb0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:434 +0x7879
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc2282f1ba0, 0xc20802d7c0, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:115 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:89 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20817d7f0, 0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc2282f1bc0, 0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/types.go:295 +0x201
net/http.HandlerFunc.ServeHTTP(0xc2282f1be0, 0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208047ec0, 0x4f41da8, 0xc20820ad20, 0xc20803dd40)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2282c6dc0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
2015/05/08 10:36:59 http: panic serving 127.0.0.1:51191: runtime error: invalid memory address or nil pointer dereference
goroutine 2532 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/whisper.(*Whisper).HasIdentity(0x0, 0xc2282b4180, 0x40)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/whisper/whisper.go:110 +0x73
github.com/ethereum/go-ethereum/xeth.(*Whisper).HasIdentity(0xc20802a140, 0xc208090090, 0x82, 0x45da6a0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/whisper.go:37 +0x7e
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc2282f1ba0, 0xc2081360a0, 0xc2080dc1a0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:442 +0x74b8
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc2282f1ba0, 0xc2081360a0, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:115 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f41da8, 0xc22825c000, 0xc208144000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:89 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20817d7f0, 0x4f41da8, 0xc22825c000, 0xc208144000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f41da8, 0xc22825c000, 0xc208144000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc2282f1bc0, 0x4f41da8, 0xc22825c000, 0xc208144000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x4f41da8, 0xc22825c000, 0xc208144000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/types.go:295 +0x201
net/http.HandlerFunc.ServeHTTP(0xc2282f1be0, 0x4f41da8, 0xc22825c000, 0xc208144000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208047ec0, 0x4f41da8, 0xc22825c000, 0xc208144000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc22827df40)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
2015/05/08 10:36:59 http: panic serving 127.0.0.1:51193: runtime error: invalid memory address or nil pointer dereference
goroutine 2533 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/whisper.(*Whisper).Watch(0x0, 0xc2282b44e0, 0x0, 0xc2282b4500, 0x1, 0x1, 0xc2080dc610, 0xc2080da4b0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/whisper/whisper.go:129 +0x1df
github.com/ethereum/go-ethereum/xeth.(*Whisper).Watch(0xc20802a140, 0xc208206330, 0x2a, 0x0, 0x0, 0xc2282b4440, 0x1, 0x1, 0xc2282b4460, 0xc200000000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/whisper.go:93 +0x4f0
github.com/ethereum/go-ethereum/xeth.(*XEth).NewWhisperFilter(0xc2080afb00, 0xc208206330, 0x2a, 0x0, 0x0, 0xc2282b4440, 0x1, 0x1, 0xc208206240)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:473 +0x142
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc2282f1ba0, 0xc2081360f0, 0xc2080dc4c0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:450 +0x76ee
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc2282f1ba0, 0xc2081360f0, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:115 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:89 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20817d7f0, 0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc2282f1bc0, 0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/types.go:295 +0x201
net/http.HandlerFunc.ServeHTTP(0xc2282f1be0, 0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208047ec0, 0x4f41da8, 0xc22825c140, 0xc2081441a0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208166000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
2015/05/08 10:36:59 http: panic serving 127.0.0.1:51194: runtime error: invalid memory address or nil pointer dereference
goroutine 2518 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/whisper.(*Whisper).Watch(0x0, 0x0, 0x0, 0xc2282b4820, 0x1, 0x1, 0xc2080dd150, 0xc2080da780)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/whisper/whisper.go:129 +0x1df
github.com/ethereum/go-ethereum/xeth.(*Whisper).Watch(0xc20802a140, 0x0, 0x0, 0x0, 0x0, 0xc2282b47a0, 0x1, 0x1, 0xc2282b47c0, 0xc200000000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/whisper.go:93 +0x4f0
github.com/ethereum/go-ethereum/xeth.(*XEth).NewWhisperFilter(0xc2080afb00, 0x0, 0x0, 0x0, 0x0, 0xc2282b47a0, 0x1, 0x1, 0xc2082067e0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:473 +0x142
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc2282f1ba0, 0xc208136140, 0xc2080dc790, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:450 +0x76ee
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc2282f1ba0, 0xc208136140, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:115 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f41da8, 0xc22825c320, 0xc208144410)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:89 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20817d7f0, 0x4f41da8, 0xc22825c320, 0xc208144410)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f41da8, 0xc22825c320, 0xc208144410)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc2282f1bc0, 0x4f41da8, 0xc22825c320, 0xc208144410)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x4f41da8, 0xc22825c320, 0xc208144410)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/types.go:295 +0x201
net/http.HandlerFunc.ServeHTTP(0xc2282f1be0, 0x4f41da8, 0xc22825c320, 0xc208144410)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208047ec0, 0x4f41da8, 0xc22825c320, 0xc208144410)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc22825c280)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
2015/05/08 10:36:59 http: panic serving 127.0.0.1:51197: runtime error: invalid memory address or nil pointer dereference
goroutine 2535 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/whisper.(*Whisper).NewIdentity(0x0, 0xc20815edf8)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/whisper/whisper.go:102 +0xdd
github.com/ethereum/go-ethereum/xeth.(*Whisper).NewIdentity(0xc20802a140, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/whisper.go:30 +0x3d
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc2282f1ba0, 0xc2282a2050, 0xc20816c350, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:434 +0x7879
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc2282f1ba0, 0xc2282a2050, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:115 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:89 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20817d7f0, 0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc2282f1bc0, 0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/types.go:295 +0x201
net/http.HandlerFunc.ServeHTTP(0xc2282f1be0, 0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208047ec0, 0x4f41da8, 0xc2282c63c0, 0xc2081cc270)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2282c6280)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
2015/05/08 10:36:59 http: panic serving 127.0.0.1:51198: runtime error: invalid memory address or nil pointer dereference
goroutine 2536 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1130 +0xbb
github.com/ethereum/go-ethereum/whisper.(*Whisper).Watch(0x0, 0xc2282f0340, 0x0, 0xc20811e510, 0x2, 0x2, 0xc2080dc2a0, 0xc2080da1e0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/whisper/whisper.go:129 +0x1df
github.com/ethereum/go-ethereum/xeth.(*Whisper).Watch(0xc20802a140, 0xc20811e1b0, 0x2a, 0x0, 0x0, 0xc20811e1e0, 0x2, 0x2, 0xc2282f0200, 0xc200000000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/whisper.go:93 +0x4f0
github.com/ethereum/go-ethereum/xeth.(*XEth).NewWhisperFilter(0xc2080afb00, 0xc20811e1b0, 0x2a, 0x0, 0x0, 0xc20811e1e0, 0x2, 0x2, 0xc20811e150)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/xeth/xeth.go:473 +0x142
github.com/ethereum/go-ethereum/rpc.(*EthereumApi).GetRequestReply(0xc2282f1ba0, 0xc2282a20a0, 0xc2080dc050, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/api.go:450 +0x76ee
github.com/ethereum/go-ethereum/rpc.RpcResponse(0xc2282f1ba0, 0xc2282a20a0, 0x200)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:115 +0x7e
github.com/ethereum/go-ethereum/rpc.func·001(0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/http.go:89 +0x496
net/http.HandlerFunc.ServeHTTP(0xc20817d7f0, 0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/rs/cors.func·001(0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rs/cors/cors.go:122 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc2282f1bc0, 0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc.func·002(0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/rpc/types.go:295 +0x201
net/http.HandlerFunc.ServeHTTP(0xc2282f1be0, 0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208047ec0, 0x4f41da8, 0xc20811db80, 0xc2081ae000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2282c6000)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1751 +0x35e
```

**Comment by karalabe** [comment]
Could you post a semi easy command to reproduce this?

**Comment by frozeman** [comment]
Sure:
```js
// js
web3.shh.newIdentity()

// RPC
{jsonrpc: "2.0", method: "shh_newIdentity", params: [], id: 3}
```
