### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/go-ethereum#986]
Logs are hard to recover, so here's the best I've got:

```
$ geth -mine > ...
...
I0514 21:39:17.179016   11345 backend.go:239] Protocol Version: 60, Network Id: 0
I0514 21:39:17.179072   11345 backend.go:249] Blockchain DB Version: 2
I0514 21:39:17.180362   11345 chain_manager.go:235] Last block (#219270) 70a4b0fe1ee41734e3fc30096a16fba650f6fc28f0
b218b6a4b6178a8a7221a0 TD=2053411904204
I0514 21:39:17.787921   11345 cmd.go:107] Starting  Geth/v0.9.20/linux/go1.4.2
I0514 21:39:17.788052   11345 server.go:209] Starting Server
I0514 21:39:19.268560   11345 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discover
ed
I0514 21:39:19.274736   11345 udp.go:189] Listening, enode://951f0337ad6b9db040455c1e9e5587edca740677ef2bd270402ce3
7776887d749559b1d604a55f65315ceffbdd1230285700bd029ad476bd206547f1e3acd025@[::]:30303
I0514 21:39:19.274863   11345 backend.go:456] Server started
I0514 21:39:19.274881   11345 server.go:349] Listening on [::]:30303
I0514 21:39:19.274954   11345 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discover
ed
I0514 21:39:19.274978   11345 miner.go:52] Starting mining operation (CPU=16 TOT=16)
I0514 21:39:19.276002   11345 worker.go:337] commit new work on block 219271 with 0 txs & 0 uncles
I0514 21:39:19.276477   11345 ethash.go:185] Generating DAG for epoch 7 (6d29f6dd1270e49744bd5377ec86395b2de2abbe54
bae16281b8e39b35538dcd)
I0514 21:39:20.567570   11345 ethash.go:213] Still generating DAG: 0%
I0514 21:39:23.170494   11345 ethash.go:213] Still generating DAG: 1%
I0514 21:39:25.765700   11345 ethash.go:213] Still generating DAG: 2%
I0514 21:39:28.461091   11345 ethash.go:213] Still generating DAG: 3%
I0514 21:39:31.328037   11345 ethash.go:213] Still generating DAG: 4%
I0514 21:39:34.135322   11345 ethash.go:213] Still generating DAG: 5%
I0514 21:39:36.921122   11345 ethash.go:213] Still generating DAG: 6%
I0514 21:39:39.693175   11345 ethash.go:213] Still generating DAG: 7%
I0514 21:39:42.487175   11345 ethash.go:213] Still generating DAG: 8%
I0514 21:39:45.322370   11345 ethash.go:213] Still generating DAG: 9%
I0514 21:39:48.512658   11345 ethash.go:213] Still generating DAG: 10%
I0514 21:39:51.309217   11345 ethash.go:213] Still generating DAG: 11%
I0514 21:39:54.731379   11345 ethash.go:213] Still generating DAG: 12%
I0514 21:39:55.458437   11345 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 4.176890875s. #21
9526 [a53e8b10 / a4d86201]
I0514 21:39:55.459246   11345 worker.go:337] commit new work on block 219527 with 0 txs & 0 uncles
I0514 21:39:56.450996   11345 chain_manager.go:628] imported 128 block(s) (0 queued 0 ignored) in 992.452304ms. 
...
I0514 21:40:41.467341   11345 worker.go:337] commit new work on block 226055 with 0 txs & 0 uncles
fatal error: unexpected signal during runtime execution
[signal 0x7 code=0x2 addr=0x7f7acc810000 pc=0x404f56]
runtime stack:
runtime.gothrow(0xd8d090, 0x2a)
        /usr/lib/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/lib/go/src/runtime/sigpanic_unix.go:14 +0x5e
goroutine 178 [syscall, locked to thread]:
runtime.cgocall_errno(0x4029b0, 0xc20c02fa68, 0x0)
        /usr/lib/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20c02fa48 sp=0xc20c02fa20
github.com/ethereum/ethash._Cfunc_ethash_full_new_internal(0x7f7b14000b40, 0x97e47012ddf6296d, 0x5b3986ec7753bd44, 
0x62e1ba54beabe22d, 0xcd8d53359be3b881, 0x437fff80, 0x7f7b140008c0, 0x406000, 0x0)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/:51 +0x44 fp=0xc20c02fa68 sp=0xc20c02fa48
github.com/ethereum/ethash.func·002()
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/ethash.go:197 +0x3ef fp=0xc20c02fc20 sp=0xc20c02fa68
sync.(*Once).Do(0xc20b66c020, 0xc20c02fc48)
        /usr/lib/go/src/sync/once.go:44 +0xd4 fp=0xc20c02fc38 sp=0xc20c02fc20
github.com/ethereum/ethash.(*dag).generate(0xc20b66c000)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/ethash.go:203 +0x54 fp=0xc20c02fc60 sp=0xc20c02fc38
github.com/ethereum/ethash.(*Full).getDAG(0xc20b7ba450, 0x35887, 0xc20b66c000)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/ethash.go:255 +0xad fp=0xc20c02fc90 sp=0xc20c02fc60
github.com/ethereum/ethash.(*Full).Search(0xc20b7ba450, 0x7f7b1c7a28f0, 0xc20acae900, 0xc208eaa3c0, 0x0, 0x0, 0x0, 
0x0)
...
goroutine 2706 [semacquire]:
sync.(*Mutex).Lock(0xc20b66c020)
        /usr/lib/go/src/sync/mutex.go:66 +0xd3
sync.(*Once).Do(0xc20b66c020, 0xc211ca4448)
        /usr/lib/go/src/sync/once.go:40 +0x65
github.com/ethereum/ethash.(*dag).generate(0xc20b66c000)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/ethash.go:203 +0x54
github.com/ethereum/ethash.(*Full).getDAG(0xc20b7ba450, 0x37307, 0xc20b66c000)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/ethash.go:255 +0xad
github.com/ethereum/ethash.(*Full).Search(0xc20b7ba450, 0x7f7b1c7a28f0, 0xc212b026c0, 0xc212fbed20, 0x0, 0x0, 0x0, 
0x0)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_wor
kspace/src/github.com/ethereum/ethash/ethash.go:260 +0x7e
github.com/ethereum/go-ethereum/miner.(*CpuAgent).mine(0xc20b72c000, 0xc212b026c0)
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent
.go:88 +0x233
created by github.com/ethereum/go-ethereum/miner.(*CpuAgent).update
        /build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent
.go:59 +0x133
```

People mention it here: https://github.com/golang/go/issues/9549, so I don't know what can be done about it...

**Comment by anthony-cros** [comment]
I troubleshooted things a bit and it seems I had simply run out of disk space on the drive where .ethash lived

So I guess the only thing that could be done here is detect it and put an informative error message, though I don't know how hard that may be

Closing ticket
